### PR TITLE
Auditbeat: Add backpressure_strategy option (#7157)

### LINKED ISSUE #7157: [Auditbeat] Avoid having Linux wait on clearing a backlog
Back-pressure from Auditbeat is propagated to the kernel via the unicast netlink socket buffer and can cause delays in the kernel. The propagation of back-pressure was implemented with the assumption that the kernel drops messages when the backlog queue is full. This assumption is true, but it has an unwanted side-effect. When the backlog queue is full, the [kernel will wait](https://elixir.bootlin.com/linux/v2.6.39/source/kernel/audit.c#L1125) for the queue to "drain a little" before providing a buffer to the waiting auditable syscall. If the queue doesn't free up the kernel will log a warning and continue with the syscall.

The waiting period is defined by the `audit_backlog_wait_time` variable. Prior to v3.14 the variable [was not configurable](https://elixir.bootlin.com/linux/v2.6.39/source/kernel/audit.c#L100). Then in v3.14 a [commit](https://github.com/linux-audit/audit-kernel/commit/51cc83f024ee51de9da70c17e01ec6de524f5906) was made to make this configurable through the audit system.

We need to make two changes for Auditbeat:

- https://github.com/elastic/go-libaudit/issues/34 - For Linux 3.14+ set the backlog_wait_time to 0 by default to ensure that Auditbeat doens't causes any blocking.
- Modify Auditbeat such that the socket reading goroutine does not block when the output is blocked (e.g. back-pressure from the publisher pipeline, this can be mitigated by using [spooling to disk](https://github.com/elastic/beats/issues/6859)) or when processing of events cannot keep up with the rate from the kernel.

For confirmed bugs, please report:
- Version: 6.2.x - 6.3.0
- Operating System: Linux
- Discuss Forum URL: https://discuss.elastic.co/t/auditbeat-impacting-system-performance/131290
- Steps to Reproduce:
  - Enable the `auditd` module in unicast mode.
  - Audit some high volume syscalls.
  - Block the output in some way (bring down LS) or suspend the Auditbeat process.
  - Wait for the kernel's `audit_backlog_limit` to be exceeded. (Messages will start showing up in the kernel log with "audit: backlog limit exceeded". The message is rate limited.)
  - Syscalls that are auditable will be wait for the `audit_backlog_wait_time` period.

Workarounds:

- If you have kernel v3.14 or newer and the `auditd` package installed then you can manually set the `audit_backlog_wait_time` to 0 with `sudo auditctl --backlog_wait_time 0`.

### PR DESCRIPTION
**Pull request by adriansr**
This adds a new configuration option, "backpressure_strategy" to the auditd module in auditbeat. It allows setting different ways in which auditbeat can mitigate or avoid backpressure to propagate into the kernel and having an impact on audited processes.

The possible values are:
- `kernel`: Auditbeat will set the backlog_wait_time in the kernel's audit framework to 0. This causes events to be discarded in kernel if the audit backlog queue fills to capacity. Requires a 3.14 kernel or newer.
- `userspace`: Auditbeat will drop events when there is backpressure from the publishing pipeline.
- `both`: `kernel` and `userspace` strategies at the same time.
- `auto` (default): The `kernel` strategy will be used if supported. Otherwise will fall back to `userspace`.
- `none`: No backpressure mitigation measures will be enabled.

Closes #7157

### CODE REVIEW

**Comment by praseodym** [comment]
Note that the audit backlog is an array of [audit message structs of ~9000 bytes each](https://www.redhat.com/archives/linux-audit/2011-October/msg00007.html). Setting the backlog size to 2^14 will allocate 147 megabytes of kernel memory, which seems a little much. I would much prefer Auditbeat to do more buffering in userspace memory that can be reclaimed when it is no longer needed.

File: auditbeat/module/auditd/audit_linux.go [hunk 1]
```diff
@@ -140,14 +156,32 @@ func (ms *MetricSet) Run(reporter mb.PushReporterV2) {
...
-			return
-		case msgs := <-out:
-			reporter.Event(buildMetricbeatEvent(msgs, ms.config))
+	// Spawn the stream buffer consumers
+	numConsumers := ms.config.StreamBufferConsumers
+	// By default (stream_buffer_consumers=0) use as many consumers as local CPUs
+	// with a max of `maxDefaultStreamBufferConsumers`
+	if numConsumers == 0 {
+		if numConsumers = runtime.NumCPU(); numConsumers > maxDefaultStreamBufferConsumers {
+			numConsumers = maxDefaultStreamBufferConsumers
```
Comment (adriansr) [inline auditbeat/module/auditd/audit_linux.go]: I am not sure this makes much sense, as opposed to just set a default of 2

File: auditbeat/module/auditd/audit_linux.go [hunk 2]
```diff
@@ -140,14 +156,32 @@ func (ms *MetricSet) Run(reporter mb.PushReporterV2) {
...
-		case <-reporter.Done():
-			return
-		case msgs := <-out:
-			reporter.Event(buildMetricbeatEvent(msgs, ms.config))
+	// Spawn the stream buffer consumers
+	numConsumers := ms.config.StreamBufferConsumers
+	// By default (stream_buffer_consumers=0) use as many consumers as local CPUs
+	// with a max of `maxDefaultStreamBufferConsumers`
+	if numConsumers == 0 {
+		if numConsumers = runtime.NumCPU(); numConsumers > maxDefaultStreamBufferConsumers {
```
Comment (andrewkroh) [inline auditbeat/module/auditd/audit_linux.go]: Would it make sense to use `runtime.GOMAXPROCS(-1)` instead of `runtime.NumCPU`?

Comment (praseodym) [reply auditbeat/module/auditd/audit_linux.go]: I think so, although it could be beneficial to have more goroutines than CPUs (after all, goroutines aren't threads).

File: auditbeat/module/auditd/audit_linux.go [hunk 3]
```diff
@@ -140,14 +156,32 @@ func (ms *MetricSet) Run(reporter mb.PushReporterV2) {
...
+
+	for i := 0; i < numConsumers; i++ {
+		go func() {
+			defer wg.Done()
+			for {
+				select {
+				case <-reporter.Done():
+					return
+				case msgs := <-out:
+					reporter.Event(buildMetricbeatEvent(msgs, ms.config))
```
[the remark this answers is not in the document]
Comment (andrewkroh) [reply auditbeat/module/auditd/audit_linux.go]: Thanks for pointing this out. I'm going to do some more testing this week. And I'll investigate this.

**Comment by pmoust** [comment]
Could we see this in 6.x too as well?

Kudos for the detailed commit message, however public facing docs are missing, will they be tackled in a follow-up PR?

**Comment by adriansr** [comment]
@pmoust yes, docs will be ready when this is released

**Comment by jordansissel** [comment]
+1 to backport this into 6.x if possible.

**Comment by adriansr** [comment]
@jordansissel this will be in 6.4
