### PR TITLE
[Heartbeat] Reimplement Scheduler / Fix recurring tasks with limit

### LINKED ISSUE #14567: [Heatbeat] Scheduler does not re-schedule limited tasks correctly
Currently the heartbeat scheduler's behavior is broken when `heartbeat.scheduler.limit` is specified. If more tasks are scheduled than the limit allows for those tasks will be discarded. They will have a chance of running at the next scheduled interval. 

This was discovered after [this report in our forums](https://discuss.elastic.co/t/heartbeat-not-running-all-monitors-when-scheduler-limit-is-set/207792/3).

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes #14567

Took the opportunity to re-implement the heartbeat scheduler with an eye toward clarity as the original code was tricky to debug. While there are more LOC here, there are also additional tests and some additional features that made sense to include as well. The net result IMHO is a reduction in complexity.

This changes the behavior to start monitors using the `@every X` syntax immediately, rather than waiting `X` duration. So, we'll call this both an enhancement and a bugfix.

Structurally the code now relies more heavily on the go runtime scheduler, in combination with a new `throttler` package which helps constrain the maximum number of executing goroutines run by the scheduler in an efficient way. There may be another way to build the throttler using buffered go routines, but I'm on the fence whether reworking it is worth it in any way.

This PR also adds new metrics. You can query these by adding `http.enabled` to `heartbeat.yml` and invoking the following:

`curl http://localhost:5066/stats | jq .heartbeat.scheduler`
`curl http://localhost:5066/state | jq .heartbeat.scheduler`

```
➜  heartbeat git:(scheduler-fix) ✗ curl http://localhost:5066/stats | jq .heartbeat.scheduler && curl http://localhost:5066/state | jq .heartbeat.scheduler
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1357  100  1357    0     0   165k      0 --:--:-- --:--:-- --:--:--  165k
{
  "jobs": {
    "missed_deadline": 0
  }
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   774  100   774    0     0   755k      0 --:--:-- --:--:-- --:--:--  755k
{
  "jobs": {
    "active": 3
  },
  "tasks": {
    "active": 3,
    "waiting": 0
  }
}
```

### CODE REVIEW

**Comment by bwright1558** [comment]
@andrewvc: Prior to these changes, when a monitor had a schedule set to something like "5s", then the monitors wouldn't run until 5 seconds after heartbeat was started. Looking at the code, it looks like this change makes it where monitors will run as soon as heartbeat starts (looking at the `RunOnInit()` function) and then run at every "5s" after that.  Is this correct?

Not that I have a problem if this is going to be the new behavior. In fact, I'd prefer it.

**Comment by andrewvc** [comment]
@bwright1558 that is correct! I've updated the PR description to make this point explicitly.

I'm going to need to add some more tests and do some benchmarking before this PR is ready to be reviewed for real, but I think that's not a ton more effort.

File: heartbeat/scheduler/scheduler.go [hunk 1]
```diff
@@ -83,52 +95,83 @@ type taskOverSignal struct {
...
+		missedAtLastCheck := uint64(0)
+		for {
+			select {
+			case <-s.done:
+				t.Stop()
+				return
+			case <-t.C:
+				// Take a snapshot of items that have missed the deadline.
+				// We only need to mutex long enough to do this. Since maps are reference types we can
+				// do this through assignment
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: do we miss code here?

File: heartbeat/scheduler/scheduler.go [hunk 2]
```diff
@@ -139,281 +182,119 @@ var ErrAlreadyStopped = errors.New("attempted to add job to already stopped sche
...
-		// drain finished queue for active jobs to not leak
-		// go-routines on exit
-		for i := uint(0); i < s.active; i++ {
-			<-s.finished
+	removed := atomic.MakeBool(false)
+	removeCh := make(chan bool)
+	removeFn = func() error {
+		// Safely close the channel exactly once
+		// Clients may invoke this function multiple times
+		if removed.CAS(false, true) {
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: why not `sync.Once`?

File: heartbeat/scheduler/scheduler.go [hunk 3]
```diff
@@ -139,281 +182,119 @@ var ErrAlreadyStopped = errors.New("attempted to add job to already stopped sche
...
-			// Calculate the amount of time between now and the next execution
-			// since the timers operation on durations, not exact amounts of time
-			nextExecIn := next.Sub(time.Now().In(s.location))
-			timer = time.NewTimer(nextExecIn)
-		}
-
-		var timeSignal <-chan time.Time
-		if timer != nil {
-			timeSignal = timer.C
+	go func() {
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: Looks like we create a go-routine per job. I wonder how this changes memory usage if a large number of tasks are configured.

File: heartbeat/scheduler/scheduler.go [hunk 4]
```diff
@@ -139,281 +182,119 @@ var ErrAlreadyStopped = errors.New("attempted to add job to already stopped sche
...
 }
 
-func (s *Scheduler) startJob(j *job) {
-	j.running++
-	j.next = j.schedule.Next(j.next)
-	debugf("Start job '%v' at %v.", j.id, time.Now())
+// runOnce runs a TaskFunc and its continuations once.
+func (s *Scheduler) runOnce(id string, entrypoint TaskFunc) {
+	// Since we run all continuations asynchronously we use a wait group to block until we're done.
+	wg := sync.WaitGroup{}
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: nit; `var wg sync.WaitGroup`

File: heartbeat/scheduler/scheduler.go [hunk 5]
```diff
@@ -139,281 +182,119 @@ var ErrAlreadyStopped = errors.New("attempted to add job to already stopped sche
...
 
-	s.runTask(task{j, j.fn})
-}
+	// Since task funcs can emit continuations recursively we need a function to execute
+	// recursively. We declare the function variable before definition to allow for recursion.
+	var runRecursive func(task TaskFunc)
+	runRecursive = func(task TaskFunc) {
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: How about extracting the run into a separate function or type that gets initialized and runs the tasks?

File: heartbeat/scheduler/throttler/throttler.go [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+		released := atomic.NewBool(false)
+		return true, func() {
+			// Only release once even if this is invoked multiple times
+			if released.CAS(false, true) {
+				select {
+				case <-t.buf:
+					// release the acquired resource
+				case <-t.done:
+					// Release if we're shutdown
+				}
```
Comment (urso) [inline heartbeat/scheduler/throttler/throttler.go]: do we need the select? Given that we acquired a lease we must always be able to read from t.buf. If not than we clearly have a problem.

File: heartbeat/scheduler/throttler/throttler.go [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+		return false, func() {}
+	}
+
+	select {
+	// Block until a resource is available
+	case t.buf <- struct{}{}:
+		released := atomic.NewBool(false)
+		return true, func() {
+			// Only release once even if this is invoked multiple times
+			if released.CAS(false, true) {
```
Comment (urso) [inline heartbeat/scheduler/throttler/throttler.go]: why the CAS? Do we expect users to release the lock multiple times?

File: heartbeat/scheduler/throttler/throttler.go [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+		buf:     make(chan struct{}, limit),
+		done:    make(chan struct{}),
+		state:   atomic.MakeInt(stateUnstarted),
+		startWg: sync.WaitGroup{},
+	}
+
+	t.startWg.Add(1)
+
+	return t
+}
```
Comment (urso) [inline heartbeat/scheduler/throttler/throttler.go]: This looks like a simple counting semaphore would do the job. Any plans to add more functionality to the 'throttler'?

In case all we need is a semaphore, we can use this: https://godoc.org/golang.org/x/sync/semaphore. Block on start can be created by adjusting the count via Acquire and Release on init.

**Comment by urso** [comment]
With us creating more go-routines now, I'm really curious about differences in memory usage if a number of endpoints is configured. Especially if endpoints resolve to multiple IP adresses (we now create a go-routine per sub-task).

I'd like the scheduler to become reusable. This change ties the scheduler implementation to the monitoring registry + internal instances in heartbeat (global variables). Instead of working with globals and updating variables in the right place, how about an observer pattern? E.g.

```
type Observer struct {
  OnMissed(n int)
  JobActivated()
  JobFailed()
  JobDone()
  ...
}
```

This would allow us to reuse the scheduler without tying it to monitoring in heartbeat.

File: heartbeat/config/config.go [hunk 9]
```diff
@@ -36,7 +36,7 @@ type Config struct {
 
 // Scheduler defines the syntax of a heartbeat.yml scheduler block.
 type Scheduler struct {
-	Limit    uint   `config:"limit"  validate:"min=0"`
+	Limit    int64  `config:"limit"  validate:"min=0"`
```
Comment (andrewvc) [inline heartbeat/config/config.go]: Changed this type to reflect the underlying weighted semaphor which can track at most int64 entries.

File: heartbeat/scheduler/scheduler.go (hunk 1 above)
Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: Oops! That comment is from a previous draft. Will delete.

File: heartbeat/scheduler/scheduler.go (hunk 2 above)
Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: Good call, I forgot that existed! Will fix.

**Comment by andrewvc** [comment]
@urso I've moved this PR back to 'in progress'.

Testing it for memory usage yielded bad results. A big source of issues seemed to be using so many different timers. I'd thought there was an efficient under the hood impl. using a priority queue but that appears not to be the case.

I've taken another stab at it using a priority queue for the timers, which has brought the memory usage to negligibly lower than the current impl (402mb vs 440mb in one test).

I'm not quite sure about CPU, I think I need to have a precise way of measuring apples to apples (e.g. we run 200k monitor pings in this branch vs the old one), which is a bit tricky.

At this point given the memory usage I'm less certain about direction.

That said, using a PriorityQueue for this is classic (the JVM does it!), and perhaps less surprising for maintainers, though it's probably down to individual perspective.

**Comment by andrewvc** [comment]
By the way @urso definitely glad to switch to the observer pattern here. Let's validate that this refactor even makes sense first though :) I'll do some more benchmarking tomorrow.

**Comment by andrewvc** [comment]
@urso I should also mention I refactored the code to use `context.Context` heavily instead of lower level concurrency primitives, which cleaned it up a lot.

**Comment by andrewvc** [comment]
Latest benchmarks against the old code (I added the same benchmark in my `sched-bench` branch to master show a dramatic difference. Not sure if there's something I'm missing here, potentially a minimum time between tasks or something? At any rate here's the number, it's certainly not worse!

Old:

```

➜  scheduler git:(sched-bench) ✗ go test -bench=. -benchtime=10s
goos: linux
goarch: amd64
pkg: github.com/elastic/beats/heartbeat/scheduler
BenchmarkScheduler-12             167757             77871 ns/op
PASS
ok      github.com/elastic/beats/heartbeat/scheduler    13.790s
```

New:

```➜  scheduler git:(scheduler-fix) ✗ go test -bench=. -benchtime=10s
goos: linux
goarch: amd64
pkg: github.com/elastic/beats/heartbeat/scheduler
BenchmarkScheduler-12            9863347              1185 ns/op
PASS
ok      github.com/elastic/beats/heartbeat/scheduler    12.945s
```

File: heartbeat/hbregistry/hbregistry.go [hunk 10]
```diff
@@ -15,32 +15,15 @@
...
-	if b[i].next.IsZero() {
-		return false
-	}
-	if b[j].next.IsZero() {
-		return true
-	}
-	return b[i].next.Before(b[j].next)
-}
+// StateRegistry contains a singleton instance of the heartbeat state registry
+var StateRegistry = monitoring.GetNamespace("state").GetRegistry().NewRegistry("heartbeat")
```
Comment (urso) [inline heartbeat/hbregistry/hbregistry.go]: How about naming the `Telemetry` or adding a comment explaining what the two registries are used for?

File: heartbeat/scheduler/timerqueue/queue.go [hunk 11]
```diff
@@ -0,0 +1,163 @@
...
+func NewTimerTask(runAt time.Time, fn TimerTaskFn) *TimerTask {
+	return &TimerTask{runAt: runAt, fn: fn}
+}
+
+// TimerTaskFn is the function invoked by a TimerTask.
+type TimerTaskFn func(now time.Time)
+
+// TimerQueue represents a priority queue of timers.
+type TimerQueue struct {
+	th            *timerHeap
```
Comment (urso) [inline heartbeat/scheduler/timerqueue/queue.go]: hah, I was wondering where the timerHeap is used :)
How about namign the field `head` or `queue`?

File: heartbeat/scheduler/timerqueue/queue.go [hunk 12]
```diff
@@ -0,0 +1,163 @@
...
+				tq.updateTimer()
+			}
+		}
+	}()
+}
+
+func (tq *TimerQueue) updateTimer() {
+	if tq.th.Len() == 0 {
+		tq.nextRunAt = nil
+		tq.timer.Stop()
```
Comment (urso) [inline heartbeat/scheduler/timerqueue/queue.go]: Stopping timers can be subject to races, especially if a timer is reused via `Reset`. In case some element has been removed via pop and we are at 0 now, we still might have a timer that might have fired. Common pattern (according to go docs):

```
if !tq.timer.Stop() {
  <-tc.timer.C  // consume signal if timer did already fire
}
```

By not consuming from the channel we might reschedule a timer that is already marked as triggered and therefore fires immediately in the following select.

File: heartbeat/scheduler/scheduler.go [hunk 13]
```diff
@@ -18,118 +18,158 @@
...
 
 	location *time.Location
 
-	jobs   []*job
-	active uint // number of active entries
+	activeJobs         *monitoring.Uint // gauge showing number of active jobs
+	activeTasks        *monitoring.Uint // gauge showing number of active tasks
+	waitingTasks       *monitoring.Uint // number of tasks waiting to run, but constrained by scheduler limit
+	jobsPerSecond      *monitoring.Uint // rate of job processing computed over the past hour
+	jobsMissedDeadline *monitoring.Uint // counter for number of jobs that missed start deadline
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: in order to reduce the 'bloat' of fields on the scheduler type how about:

```
type Scheduler struct {
   ...
   stats schedulerStats
   ...
}

type schedulerStats struct {
    activeJobs         *monitoring.Uint // gauge showing number of active jobs
	active uint // number of active entries
	activeTasks        *monitoring.Uint // gauge showing number of active tasks
	waitingTasks       *monitoring.Uint // number of tasks waiting to run, but constrained by scheduler limit
	jobsPerSecond      *monitoring.Uint // rate of job processing computed over the past hour
	jobsMissedDeadline *monitoring.Uint // counter for number of jobs that missed start deadline
}
```

File: heartbeat/scheduler/timerqueue/heap.go [hunk 14]
```diff
@@ -0,0 +1,51 @@
...
+// software distributed under the License is distributed on an
+// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+package timerqueue
+
+// timerHeap is the internal type that implements container/heap
+type timerHeap []*TimerTask
```
Comment (urso) [inline heartbeat/scheduler/timerqueue/heap.go]: How about `timerHeap []TimerTask`? Right now another object is creating and scheduling the task by passing a pointer. Nothing prevents other objects to mess with the timestamp.

File: heartbeat/scheduler/timerqueue/queue.go [hunk 15]
```diff
@@ -0,0 +1,163 @@
...
+		pushCh:        make(chan *TimerTask),
+		timer:         time.NewTimer(0),
+	}
+	heap.Init(tq.th)
+
+	return tq
+}
+
+// Push adds a task to the queue
+func (tq *TimerQueue) Push(tt *TimerTask) {
```
Comment (urso) [inline heartbeat/scheduler/timerqueue/queue.go]: hm, do we even need to expose the TimerTask type? How about `func (tq *TimerQueue) Push(runAt time.Time, fn TimerTaskFn)` ?

File: heartbeat/scheduler/scheduler.go [hunk 16]
```diff
@@ -138,282 +178,102 @@ var ErrAlreadyStopped = errors.New("attempted to add job to already stopped sche
...
-		}
-		resched = true
+	taskFn = func(_ time.Time) {
+		// Attempt to acquire a resource to see if we're blocked
+		// We can't really tell if we're blocked because we need to acquire resources later
+		// for the entrypoint + continuations, but this is good enough for our lastRanAt
+		// accounting since we want that value set at the first plausible time where the
+		// job could run
+		s.sem.Acquire(s.ctx, 1)
+		s.sem.Release(1)
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: missing `defer` ?

File: heartbeat/scheduler/scheduler.go [hunk 17]
```diff
@@ -138,282 +178,102 @@ var ErrAlreadyStopped = errors.New("attempted to add job to already stopped sche
...
-	defer func() {
-		// drain finished queue for active jobs to not leak
-		// go-routines on exit
-		for i := uint(0); i < s.active; i++ {
-			<-s.finished
+		now := time.Now().In(s.location)
+		if next.Before(now) {
+			// Our last invocation went long!
+			s.jobsMissedDeadline.Inc()
+			taskFn(now)
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: is this an optimization to reuse the last go-routine? Can this impact a call to `Add`, which also calls `schedNextRun` as last step?

File: heartbeat/scheduler/scheduler.go [hunk 18]
```diff
@@ -138,282 +178,102 @@ var ErrAlreadyStopped = errors.New("attempted to add job to already stopped sche
...
-}
-
-func (s *Scheduler) signalFinished(j *job, cont []TaskFunc) {
-	var tasks []task
-	if len(cont) > 0 {
-		tasks = make([]task, len(cont))
-		for i, f := range cont {
-			tasks[i] = task{j, f}
+		for _, cont := range continuations {
+			go s.runRecursiveTask(jobCtx, cont, wg) // Run continuations in parallel, note that these each will acquire their own slots
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: Looks like we are missing calls to `wg.Add`. If the children go-routines call  `wg.Done` then the counter becomes negative and you have a panic.

No these recursive calls and proper usage of `sync.WaitGroup` become tricky. One must not call `Add` of some other go-routine is blocked on `Wait`. Otherwise the `Add` will panic. In order to resolve this one needs a local `sync.WaitGroup` and wait on it until all children are done. This way the 'finish' of a computation creates a cascade of go-routines shutting down one after anohter.

A waitGroup kind of acts like a barrier, but one must not add children while waiting for it.

Your use-case (quit finish go-routines before child go-routines) can be implemented using a reference counter + channel. Using the reference counter from [github.com/elastic/go-concert](https://github.com/elastic/go-concert/blob/master/refcount.go) the pattern becomes:

```
waitCh := make(chan struct{})
refCount := &concert.RefCount{
  Action: func(_ error) { close(waitCh) },
}

refCount.Retain() // add ownership for go-routine
go s.runRecursiveTask(jobCtx, task, refCount)

recCount.Release() // give up local ownership
<-waitCh // wait for all child go-routines to finish
```

with:

```
func (s *Scheduler) runRecursiveTask(jobCtx context.Context, task TaskFunc, refCount *concert.RefCount) {
  defer refCount.Release()
  
  ...
  for _, cont := range continuations {
    refCount.Retain() / add ownership for new go-routine
    go s.runRecursiveTask(jobCtx, cont, refCount)
  }
}
```

File: heartbeat/scheduler/timerqueue/heap.go (hunk 14 above)
Comment (andrewvc) [reply heartbeat/scheduler/timerqueue/heap.go]: AFAIK slices of pointers are usually faster (see https://stackoverflow.com/questions/27622083/slices-of-structs-vs-slices-of-pointers-to-structs ).

I'm not too worried about mutability given that we're the only users of this API. I'll clarify that the fields should not be changed after being scheduled.

File: heartbeat/scheduler/scheduler.go (hunk 13 above)
Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: great call, will do

File: heartbeat/scheduler/scheduler.go (hunk 16 above)
Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: This was all done to get a more accurate time for `lastStartedAt`. I'm realizing now that we can delete this mess and just have `runRecursive` return the timestamp of its first task which is both more accurate and simpler.

File: heartbeat/scheduler/scheduler.go (hunk 18 above)
Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: You're right! I'm missing an `Add` for the WaitGroup.

Are you sure that's true about `WaitGroup` though? In the [docs](https://golang.org/pkg/sync/#WaitGroup.Add) it says:

>  Note that calls with a positive delta that occur when the counter is zero must happen before a Wait. Calls with a negative delta, or calls with a positive delta that start when the counter is greater than zero, may happen at any time. 

The ref count approach is neat, but I think it's more complicated, and I'd rather not use it unless I have to.

Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: I've added the missing `add` and it seems to work fine. I'm realizing I need to add scheduler tests with continuations however.

File: heartbeat/scheduler/timerqueue/queue.go (hunk 15 above)
Comment (andrewvc) [reply heartbeat/scheduler/timerqueue/queue.go]: Good point, we don't!

File: heartbeat/hbregistry/hbregistry.go (hunk 10 above)
Comment (andrewvc) [reply heartbeat/hbregistry/hbregistry.go]: Done!

File: heartbeat/scheduler/timerqueue/queue.go (hunk 11 above)
Comment (andrewvc) [reply heartbeat/scheduler/timerqueue/queue.go]: Unfortunately yes do to the way the heap package works, I think it rewrites the reference.

Comment (andrewvc) [reply heartbeat/scheduler/timerqueue/queue.go]: See the examples in https://golang.org/pkg/container/heap/ for details.

File: heartbeat/scheduler/timerqueue/queue.go (hunk 12 above)
Comment (andrewvc) [reply heartbeat/scheduler/timerqueue/queue.go]: I don't think we can have races here since we do all scheduling and receiving in a single thread.

File: heartbeat/scheduler/scheduler.go (hunk 17 above)
Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: This optimization is now removed anyway, it was unnecessary with how efficient the timer is now.

**Comment by andrewvc** [comment]
@urso I think I've addressed all your previous critiques. I've also improved the documentation here and passed through the context to invoked tasks (which would be nice in the future so that cancelling the timer would cancel everything scheduled with it).

I think it's ready for another round of review.

File: heartbeat/scheduler/timerqueue/queue.go (hunk 12 above)
Comment (urso) [reply heartbeat/scheduler/timerqueue/queue.go]: You still rely on the timer package for waiting. `tc.timer` has type `*time.Timer`. The Timer type is tricky to use. Once scheduled via `Reset` the timer will not run in your thread/go-routine. It is the timer sub-system that is going to put a signal into the channel. Which means that `Stop` and `Reset` are always subject to races with the actual timer subsystem. According to `time.Timer` docs one must call Reset only after calling Stop, and on Stop one must be prepared to consumer a pending signal from C.

File: heartbeat/scheduler/scheduler.go (hunk 18 above)
Comment (urso) [reply heartbeat/scheduler/scheduler.go]: +1 on testing. Right, one must not run the first call to `Add` concurrently with `Wait`, but if the count counter is > 0 when calling `Add` it should be safe. When starting child go-routines waitGroup kind of should be used as a reference counter: Always call Add before giving up on the waitgroup by calling done.

File: heartbeat/scheduler/scheduler.go [hunk 19]
```diff
@@ -18,402 +18,252 @@
...
-			debugf("done")
+		case <-s.ctx.Done():
+			t.Stop()
 			return
-
+		case <-t.C:
+			missingNow := s.stats.jobsMissedDeadline.Get()
+			missedDelta := missingNow - missedAtLastCheck
+			if missedDelta > 0 {
+				logp.Warn("%d tasks have missed their schedule deadlines in the last %s.", missedDelta, interval)
```
Comment (urso) [inline heartbeat/scheduler/scheduler.go]: Better do not use logging functions in `lopg`, but have pass a `*logp.Logger`

File: heartbeat/scheduler/timerqueue/queue.go (hunk 11 above)
Comment (urso) [reply heartbeat/scheduler/timerqueue/queue.go]: If you look at the IntHeap example, they indeed allocate. But looking at the PriorityQueue, the queue is not allocated. Instead of having a pointer here you can use `heap.Init(&queue)`. In the end it depends on how you implement the methods (pass by value vs by pointer) and how/when you pass the pointer to the heap functions.

File: heartbeat/scheduler/timerqueue/queue.go (hunk 12 above)
Comment (andrewvc) [reply heartbeat/scheduler/timerqueue/queue.go]: Thanks for the clarification, will fix!

File: heartbeat/scheduler/timerqueue/queue.go (hunk 11 above)
Comment (andrewvc) [reply heartbeat/scheduler/timerqueue/queue.go]: Interesting, thanks for the clarification, I'll make that change.

File: heartbeat/scheduler/scheduler.go (hunk 18 above)
Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: 100% right. I think we're OK here since we increment the add counter before invoking the continuations.

File: heartbeat/scheduler/scheduler.go (hunk 19 above)
Comment (andrewvc) [reply heartbeat/scheduler/scheduler.go]: Do you mind if we defer that change for a later PR? That would require passing through quite a bit more context than we currently do. I'd prefer to have a follow-up PR that passes in a sort of global app context through the whole app rather than doing a one off here.

File: heartbeat/scheduler/timerqueue/queue.go (hunk 12 above)
Comment (andrewvc) [reply heartbeat/scheduler/timerqueue/queue.go]: I've since fixed this, the semantics here are really tricky (looking at the history of go timers it looks like they've been the topic of a lot of confusion and debate).

**Comment by andrewvc** [comment]
@urso I believe I've addressed all comments since your last review. Thanks for the careful reading of this tricky code.

**Comment by andrewvc** [comment]
Also, the latest iteration runs in 962 ns/op, which is ~80x faster than the current code assuming the benchmark is accurate.

**Comment by andrewvc** [comment]
Posting some benchmarks here for posterity


  | RSS | cpu_usr @ 100k executed | cpu_sys @ 100k
-- | -- | -- | --
OldSched | 635028 | 66.99 | 15.99
PQ Sched | 363296 | 49.81 | 14.69
