### PR TITLE
[beatreceivers] fix race condition in beat LoadMeta

### LINKED ISSUE #46841: [beat] LoadMeta has a race condition.
The `LoadMeta` function has a race condition if more than one beat has the same paths defined.

https://github.com/elastic/beats/blob/22a9a05dbc0e3f9a9901d381d3906381eccc016c/libbeat/cmd/instance/beat.go#L979-L1002

The `os.OpenFile` should be replaced with [os.CreateTemp](https://cs.opensource.google/go/go/+/go1.25.1:src/os/tempfile.go;l=35)

### PR DESCRIPTION
**Pull request by leehinman**
## Proposed commit message

Fix race condition in beat `LoadMeta` function.  If 2 (or more) beats had the same path to the meta file, then it was possible for one not to start.  This would only affect beat receivers because a normal beat requires a unique path to the meta file.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

``` shell
cd libbeat/cmd/instance
go test . -v -count 1 -run TestMultipleLoadMeta
```

## Related issues

- Closes #46841

### CODE REVIEW

File: libbeat/cmd/instance/beat.go [hunk 1]
```diff
@@ -977,31 +979,29 @@ func (b *Beat) LoadMeta(metaPath string) error {
 
 	// file does not exist or ID is invalid or first start time is not defined, let's create a new one
 
-	// write temporary file first
-	tempFile := metaPath + ".new"
-	f, err = os.OpenFile(tempFile, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0o600)
+	// write temporary file first, use same dir as destination to avoid invalid cross-device links
+	tmpFile, err := os.CreateTemp(filepath.Dir(metaPath), "new")
```
Comment (cmacknz) [inline libbeat/cmd/instance/beat.go]: nit: instead of the random file name just containing `new` shouldn't it contain the filename part of metaPath + .new instead?

Comment (leehinman) [reply libbeat/cmd/instance/beat.go]: changed to `filepath.Base(metaPath)+".new"`
