### PR TITLE
libbeat: Don't force an ignore_above limit on wildcard fields

### LINKED ISSUE #30096: Fields using `wildcard` type should not specify `ignore_above` param
**Version**: 8.0.0-rc1, 7.16.2
**Operating System**: Seen on Windows and MacOS

**Description**

Index templates created by Beats are still specifying an `ignore_above` setting for `wildcard` fields.

Example from the `winlogbeat-8.0.0-rc1` template on the `process.command_line` field:

```
            "command_line": {
              "ignore_above": 1024,
              "type": "wildcard",
              "fields": {
                "text": {
                  "type": "match_only_text"
                }
              }
```

Long field values are not being indexed as expected with `wildcard`. Kibana confirms:

Screen Shot 2022-01-28 at 3 21 14 PM

Keyword fields include an `ignore_above` param in their ECS field definitions, but `wildcard` fields do not:

https://github.com/elastic/beats/blob/8.0/libbeat/_meta/fields.ecs.yml#L4443-L4454

**Steps to Reproduce:**

* Install Beats `8.0.0-rc1` with default settings and run `setup` to install default index templates.
* Index events with values > 1024 in `wildcard` fields.

### PR DESCRIPTION
**Pull request by adriansr**
## What does this PR do?

Modifies libbeat's template processor to stop hardcoding a default `ignore_above` limit of 1024 on wildcard fields. This behavior was inherited from keyword fields.

From the Beats users point of view, I've considered this a bugfix. (Bugfix under Affecting All Beats in CHANGELOG).
From the community Beat developers point of view, I consider this a breaking change as someone may be relying on the previous default behavior (Breaking under Affecting all Beats in CHANGELOG-developer).

## Why is it important?

Some important ECS wildcard fields are not being indexed properly. See related issue.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

Closes #30096

### CODE REVIEW

File: libbeat/template/processor.go [hunk 1]
```diff
@@ -317,11 +317,10 @@ func (p *Processor) wildcard(f *mapping.Field, analyzers common.MapStr) common.M
...
 	property["type"] = "wildcard"
 
-	switch f.IgnoreAbove {
-	case 0: // Use libbeat default
-		property["ignore_above"] = defaultIgnoreAbove
-	case -1: // Use ES default
-	default: // Use user value
+	/* For wildcard fields, unlike keyword, don't force a default ignore_above limit.
+	   The default in ES will be used unless an explicit limit is set.
+	*/
```
Comment (cmacknz) [inline libbeat/template/processor.go:322]: Could you add some additional context for why this is the case? There is some good (and convincing) information in https://github.com/elastic/beats/issues/30096, specifically:

> A big benefit wildcard has over keyword is the indexing of strings larger than the 32,766 byte Lucene max, but users can't gain that benefit if ignore_above is set to ignore string values greater than 1024 chars.

**Comment by cmacknz** [comment]
As far as I can tell the last time this `ignore_above` code was touched was https://github.com/elastic/beats/commit/fabdf0b6094370fd9b32e61286b685396448d9d8 by @ph in 2018. I'm not sure he remembers the context after that long but tagging him anyway just in case.

**Review by cmacknz — APPROVED** [review]

**Comment by ph** [comment]
This is indeed a really long time ago, the `ignore_older` limit was indeed added for keyword. I don't exactly remember the actual issues here @ruflin maybe you know?

**Comment by ph** [comment]
I've read about wildcard, since the limit was added previously. I am ok to thread wildcard differently than keywords but @adriansr what kind of data are you indexing in that field?

**Comment by ebeahan** [comment]
@ph I'll jump in and answer since I originally opened #30096.

Security-focused users have pointed out how specific shell commands, URLs, or encoded payloads values could exceed the 1024 character convention. Not having these values indexed can create detection blindspots. Users can adjust the `ignore_above` limit, but if you need to capture an immense value, you eventually hit the 32766 bytes Lucene max.

ECS [migrated](https://github.com/elastic/ecs/blob/main/rfcs/text/0001-wildcard-data-type.md) a small number of fields to use `wildcard`. Fields more likely to contain very long strings, like URLs or command-line executions, were picked. These migrations made it into Beats, but `wildcard` strings > 1024 characters are still not indexed since the `ignore_above` value is set on `wildcard` fields in the mappings.

Wildcard fields have some other benefits, but that's outside the scope of the focus here. 😄
