### PR TITLE
x-pack/filebeat/input/entityanalytics/provider/azuread: fix query handling

### LINKED ISSUE #39419: [Microsoft Entra ID Entity Analytics] Adding custom options such as department do not take affect.
I added - department as an option to the Entra ID integration but it did not work on the 15 minute checks or the full 24 hour sync.

image

I did not see any issues in the error logs but it is a busy agent with 20+ integrations.

Am I missing something?

Conversation here: https://elasticstack.slack.com/archives/CNRTGB9A4/p1711751406843169?thread_ts=1711141962.535729&cid=CNRTGB9A4

Also, if I removed fields from the list and only supplied one field, nothing changes, and the same default fields come in as said.

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

See title.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Fixes #39419

### CODE REVIEW

**Review by chemamartinez — APPROVED** [review]

File: x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go [hunk 1]
```diff
@@ -353,21 +354,21 @@ func New(cfg *config.C, logger *logp.Logger, auth authenticator.Authenticator) (
 	if err != nil {
 		return nil, fmt.Errorf("invalid groups URL endpoint: %w", err)
 	}
-	groupsURL.RawQuery = url.QueryEscape(formatQuery(c.Select.GroupQuery, defaultGroupsQuery))
+	groupsURL.RawQuery = queryName + "=" + url.QueryEscape(formatQuery(c.Select.GroupQuery, defaultGroupsQuery))
```
Comment (andrewkroh) [inline x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go:357]: Should the `$select` be subjected to query escaping as well? IIUC the only part that we don't want to escape is the `=`. 

Perhaps building this up with `url.Values{...}.Encode()` would be safer since it handles the escaping for us.

Comment (efd6) [reply x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go:357]: OK

**Review by andrewkroh — APPROVED** [review]

**Review by zmoog — APPROVED** [review]
