### PR TITLE
Disable part of topology test on Solaris

### LINKED ISSUE #1285: Topology test failure Solaris
[`TestPublisherTypeUpdateTopologyPeriodically`](https://github.com/elastic/beats/blob/09ca0f4cf67a314366d2023525858c1b8e8efa65/libbeat/publisher/publish_test.go#L52-L52) fails on Solaris because [`common. LocalIpAddrsAsStrings`](https://github.com/elastic/beats/blob/c7566d2e6bb43da5780787392111429bf367fd6a/libbeat/common/net.go#L27-L27) always returns zero IPs. This is because `net.InterfaceAddrs()` is not implemented on Solaris; it's a [stub](https://golang.org/src/net/interface_stub.go).

I assume this means topology is broken for Solaris. 

What should we do? At a minimum I would like to fix the test case.

### PR DESCRIPTION
**Pull request by andrewkroh**
Go cannot return the local interfaces because the method is not implemented on Solaris. The local interfaces are used in determining the topology.

Fixes #1285

### CODE REVIEW

File: libbeat/publisher/publish_test.go [hunk 1]
```diff
@@ -70,5 +71,10 @@ func TestPublisherTypeUpdateTopologyPeriodically(t *testing.T) {
 
 	// Validate that PublishTopology was invoked.
 	assert.Equal(t, shipperName, <-topo.publishName)
-	assert.True(t, len(<-topo.publishLocalAddrs) > 0)
+	switch runtime.GOOS {
+	default:
```
Comment (ruflin) [inline libbeat/publisher/publish_test.go]: minor detail: I'm somehow used to have default at the end.
