### PR TITLE
filebeat/input/udp - Fix panic in linux input metrics

### LINKED ISSUE #35064: [Filebeat] TCP/UDP input cause a panic on Linux under certain conditions
- Version: `v8.7.0`, `main`
- Operating System: Linux

## Steps to Reproduce
1. Start Filebeat with UDP input (or any input that uses UDP, like syslog)
   ```yaml
   filebeat.inputs:
   - type: udp
     host: "localhost:9009"

   output.console:
     enabled: true
   ```
2. Wait for about a minute (no need to ingest any data), you'll see a panic
   ```
   panic: runtime error: index out of range [1] with length 0
   
   goroutine 62 [running]:
   github.com/elastic/beats/v7/filebeat/input/udp.procNetUDP({0xc0002b0980?, 0x1, 0x2})
           /home/tiago/devel/beats/filebeat/input/udp/input.go:271 +0x552
   github.com/elastic/beats/v7/filebeat/input/udp.(*inputMetrics).poll(0xc000458680, {0xc0002b0980, 0x1, 0x2}, 0x0?, 0xc00066e040)
           /home/tiago/devel/beats/filebeat/input/udp/input.go:242 +0xd1
   created by github.com/elastic/beats/v7/filebeat/input/udp.newInputMetrics
           /home/tiago/devel/beats/filebeat/input/udp/input.go:216 +0xa70
   ```

# The problem
The panic comes from the `procNetUDP` function that gathers some UDP metrics from `/proc/net/udp`:
https://github.com/elastic/beats/blob/a8dbc6c06381f4fe33a5dc23906d63c04c9e2444/filebeat/input/udp/input.go#L256-L288

It seems some times the data is on a format different than what the function expects.

# Workaround
Currently the only know workaround is to downgrade to `v8.6.2`.

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

A panic occurred while parsing /proc/net/udp and reaching the final empty line. This occurred on Linux when the desired socket was not found in the list.

Fixes #35064

## Why is it important?

The panic causes Filebeat to exit.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Fixes #35064

### CODE REVIEW

**Review by P1llus — APPROVED** [review]
Link in the Changelog is the wrong issue, except that LGTM! :)

File: filebeat/input/udp/input.go [hunk 1]
```diff
@@ -268,7 +268,7 @@ func procNetUDP(addr []string) (rx, drops int64, err error) {
 	}
 	for _, l := range lines[1:] {
 		f := bytes.Fields(l)
-		if contains(f[1], addr) {
+		if len(f) > 12 && contains(f[1], addr) {
```
Comment (leehinman) [inline filebeat/input/udp/input.go:271]: `12` is a little "magical",  how about at least a link to kernel docs for why there should be this many fields?
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/net/ipv4/udp.c?h=v4.14.312#n2764

also fmt.Errorf above should probably use the `path` variable instead of "/proc/net/udp" now.

**Review by leehinman — APPROVED** [review]
Code LGTM

just a suggestion on documenting why 12 fields and making the error message consistent with inputs.

File: filebeat/input/udp/input.go (hunk 1 above)
Comment (andrewkroh) [reply filebeat/input/udp/input.go:271]: The reason I checked for 12 is because it is highest field indexed (e.g. `f[12]`) by this section of code.

> fmt.Errorf above should probably use the path

Yeah, that thought crossed my mind. I didn't do it because it was parameterized only for testing purposes. But if you had the thought too then I will change it.
