### PR TITLE
[Heartbeat] Fix NXDOMAIN errors

### LINKED ISSUE #10734: Heartbeat showing NX domains as down
Somewhere, according to git bisect, in e2701baa2d56b147f8f22a17ea0ab07c538485ff we broke NX domain errors. We also, apparently, don't have tests for this. If you configure an HTTP monitor against `fake.elastic.co` it comes up as 'up'.

### PR DESCRIPTION
**Pull request by andrewvc**
Heartbeat 6.7 broke NXDOMAIN errors by accident. This PR adds test coverage for NXDOMAIN issues as well.

Heartbeat 7.0.0 is immune due to a simplified and improved error handling control flow.

Fixes #10734

### CODE REVIEW

File: heartbeat/monitors/active/tcp/tcp_test.go [hunk 1]
```diff
@@ -202,3 +202,32 @@ func TestUnreachableEndpointJob(t *testing.T) {
...
+// Note, this depends on the system having a DNS resolver that doesn't hijack NXDOMAIN Results.
+func TestNXDomain(t *testing.T) {
+	host := "notadomainatallforsure.notadomain.notatldreally"
+	port := uint16(1234)
+	event := testTCPCheck(t, host, port)
+
+	dialErr := fmt.Sprintf("lookup %s", host)
+	mapvaltest.Test(
+		t,
+		mapval.Strict(mapval.Compose(
```
Comment (andrewvc) [inline heartbeat/monitors/active/tcp/tcp_test.go]: I verified that the generated fields are correct against heartbeat 6.4 before the bug was introduced.

Heartbeat 7.0 has a more sane field generation approach, not dropping fields like `monitor.port` just because an error occurred during the DNS lookup phase.

File: heartbeat/monitors/util.go [hunk 2]
```diff
@@ -274,8 +274,8 @@ func makeByHostAnyIPJob(
 		resolveStart := time.Now()
 		ip, err := net.ResolveIPAddr(network, host)
 		if err != nil {
-			resolveErr(event, host, err)
-			return nil, nil
+			resolveErr(event, host)
```
Comment (andrewvc) [inline heartbeat/monitors/util.go]: I think that during the refactor my thought was that we'd add the error fields in `resolveErr` directly, which was obviously incorrect.

File: heartbeat/monitors/active/tcp/tcp_test.go (hunk 1 above)
Comment (ruflin) [reply heartbeat/monitors/active/tcp/tcp_test.go]: So this bug is in 6.5 and 6.6?

Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tcp_test.go]: Nope! I validated that it's not in 6.6 either. I just happened to have 6.4 handy to test the structure. I'm sure 6.6 is fine.
