### PR TITLE
[Heartbeat] Refactor TCP Monitor

### LINKED ISSUE #17123: Heartbeat TLS servername set incorrectly
From: https://discuss.elastic.co/t/heartbeat-tls-servername-not-being-set-correctly/224280

When trying to monitor an SSL enabled endpoint it seems like Heartbeat is setting the ServerName to the IP address instead of the hostname. For setups where the certificate is only signed with the domain (and not all IP addresses) this causes verification to fail. For setups where different certificates are served depending on hostname (Kubernetes nginx-ingress being a popular example) it means that Heartbeat tries to verify the invalid fake certificate that is returned when no matching domains are found. 

Looking through the code and docs I can't find a way to have the verified ServerName be the domain instead of the resolved IP address.

Example configuration:

```
- type: "tcp"
  name: "elastic.co"
  schedule: "@every 60s"
  hosts: ["tls://elastic.co:443"]
  ssl:
    enabled: true
```

Error message:

```
x509: cannot validate certificate for 151.101.194.217 because it doesn't contain any IP SANs"
```

Here is the section which is setting the ServerName

https://github.com/elastic/beats/blob/4f5d1a1bee508e8fcd35531cfcc8509563314517/libbeat/common/transport/tlscommon/tls_config.go#L109-L118

The `host` string which gets passed in actually ends up being the resolved IP address. 

To confirm that this was the issue I hard coded it to "elastic.co" allows the certificate to be verified properly.

```
config.ServerName = "elastic.co"
```

I have reproduced this with the latest releases version (running from official Docker images) and also with the latest builds from the master branch.

### PR DESCRIPTION
**Pull request by andrewvc**
## What does this PR do?

Refactors the TCP monitor to make the code easier to follow, more testable, and fixes #17123 where TLS server name was not correctly sent. This is important because the code had accrued a lot of cruft and become very hard to follow. There were many wrappers and intermediate variable names that often subtly changed names as they crossed various functions. When debugging elastic/beats#17123 I frequently found myself lost tracing the execution.

This new code should be simpler to understand for a few reasons:

1. Less code (almost a 2x reduction) and fewer, simpler, better organized functions
1. Less variable passing/renaming due to use of struct for key config variables
1. More consistent and descriptive variable names
1. Creation of the dialer as late as possible, to remove the confusing partial states, and clarity as to when which dialer layers are used.
1. Adds (frustratingly tricky) integration tests for #17123 using mismatched TLS certs, and also against a real SOCKS5 proxy
1. Adds, for testing only, the ability to override the real network resolver for TCP checks which is invaluable in debugging TLS checks that depend on setting hostnames correctly. In the future if we decide to let users use a custom DNS resolver this will be nice.
1. Reorganized giant TCP test file into multiple files

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Run the sample config in https://github.com/elastic/beats/issues/17123

### CODE REVIEW

File: heartbeat/hbtest/hbtestutil.go [hunk 1]
```diff
@@ -153,6 +153,15 @@ func SummaryChecks(up int, down int) validator.Validator {
 	})
 }
 
+func ResolveChecks(ip string) validator.Validator {
```
Comment (exekias) [inline heartbeat/hbtest/hbtestutil.go:156]: It would be nice to add a comment to this function

File: heartbeat/monitors/active/tcp/endpoint.go [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+		} else {
+			scheme = u.Scheme
+			host = u.Host
+		}
+		debugf("Add tcp endpoint '%v://%v'.", scheme, host)
+
+		switch scheme {
+		case "tcp", "plain", "tls", "ssl":
+		default:
+			err := fmt.Errorf("'%v' is not a supported connection scheme in '%v'", scheme, h)
```
Comment (exekias) [inline heartbeat/monitors/active/tcp/endpoint.go:67]: nit: it could be worth listing the supported schemes in the error

File: heartbeat/monitors/active/tcp/endpoint.go [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+			return nil, err
+		}
+
+		pair := strings.SplitN(host, ":", 2)
```
Comment (exekias) [inline heartbeat/monitors/active/tcp/endpoint.go:71]: is IPv6 supported? This would break it. Consider using SplitHostPort: https://golang.org/pkg/net/#SplitHostPort

File: heartbeat/monitors/active/tcp/tcp.go [hunk 4]
```diff
@@ -39,113 +43,223 @@ func init() {
...
+	dc.AddLayer(dialchain.ConstAddrLayer(dialAddr))
+
+	// If we're using TLS we need to add a fake layer so that the TLS layer knows the hostname we're connecting to
+	// So, the canonical URL is fixed via a ConstAddrLayer to override the TLS layer's x509 logic so it doesn't
+	// try and directly match the IP from the prior ConstAddrLayer to the cert.
+	isTLS := true
+	if canonicalURL.Scheme == "tcp" || canonicalURL.Scheme == "plain" {
+		isTLS = false
+	}
+	if isTLS {
```
Comment (exekias) [inline heartbeat/monitors/active/tcp/tcp.go:207]:
```suggestion
	if canonicalURL.Scheme != "tcp" && canonicalURL.Scheme != "plain" {
```

File: heartbeat/monitors/resolver.go [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+// potentially with custom functionality
+type Resolver interface {
+	// ResolveIPAddr is an analog of net.ResolveIPAddr
+	ResolveIPAddr(network string, host string) (*net.IPAddr, error)
+	// LookupIP is an analog of net.LookupIP
+	LookupIP(host string) ([]net.IP, error)
+}
+
+// stdResolver uses the go std library to perform DNS resolution.
+type stdResolver struct{}
```
Comment (exekias) [inline heartbeat/monitors/resolver.go:35]: wdyt about adding unit tests for this one?

File: heartbeat/monitors/active/tcp/endpoint.go (hunk 2 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/endpoint.go]: Done!

File: heartbeat/monitors/active/tcp/endpoint.go (hunk 3 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/endpoint.go]: I just pushed a fix here where I rewrote all this logic and added a ton of tests as well. It's a weird thing to parse since we support hosts, ips, and URLs (there isn't an RFC for this either AFAICT), but I think then new logic does what the docs say, and has tests to back it up (including ipv6 tests).

File: heartbeat/monitors/active/tcp/tcp.go (hunk 4 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tcp.go:207]: yup! Committed this locally, since it's easier.

File: heartbeat/monitors/resolver.go (hunk 5 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go:35]: I think you're right to add tests for the static resolver which I've done, but given that this one just passes the functions through to stdlib, I don't see how we could write significantly useful tests. We could compare output for a limited set of inputs but that doesn't say much. IMHO, the utility of those tests is pretty low.

It's not a huge deal, I'll add some simple ones if you think it's important, but I don't think tests on `stdResolver` will decrease chances of a future regression.

**Comment by andrewvc** [comment]
@exekias I've either responded to or fixed all of the issues you found in my most recent commits. I rewrote the code that parses hostnames/urls (it was weird for sure), and added a bunch of tests to boot. LMK if more is needed.

@mtojek thanks for taking a look. Let's address those concerns out of band of this issue and keep the focus more narrow here.

**Comment by andrewvc** [comment]
@exekias hmmm I see these unit tests for ipv6 I added to address your comment don't work so well on our [CI servers](https://beats-ci.elastic.co/job/Beats/job/beats-beats-mbp/job/PR-17549/11/execution/node/449/log/). I'm getting:

```
22:57:11  panic: failed to listen on localhost: listen tcp [::1]:0: bind: cannot assign requested address [recovered]
22:57:11  	panic: failed to listen on localhost: listen tcp [::1]:0: bind: cannot assign requested address
```

These pass on my box. I'll reach out to infra tomorrow and see what ideas they have. If you know of a workaround that'd be awesome of course.

File: heartbeat/monitors/active/tcp/tcp.go [hunk 6]
```diff
@@ -39,113 +43,219 @@ func init() {
...
+type jobFactory struct {
+	config        Config
+	tlsConfig     *tlscommon.TLSConfig
+	defaultScheme string
+	endpoints     []endpoint
+	dataCheck     dataCheck
+	resolver      monitors.Resolver
+}
+
+func makeJobFactory(commonCfg *common.Config, resolver monitors.Resolver) (jf *jobFactory, err error) {
```
Comment (mtojek) [inline heartbeat/monitors/active/tcp/tcp.go:83]: No need to name returned variables if you don't use it this way (single "return").

File: heartbeat/monitors/active/tcp/tcp.go [hunk 7]
```diff
@@ -39,113 +43,219 @@ func init() {
...
+	err = jf.loadConfig(commonCfg)
+	if err != nil {
+		return nil, err
+	}
+
+	return jf, nil
+}
+
+// loadConfig parses the YAML config and populates the jobFactory fields.
+func (jf *jobFactory) loadConfig(commonCfg *common.Config) (err error) {
```
Comment (mtojek) [inline heartbeat/monitors/active/tcp/tcp.go:94]: same here, just: (error)

File: heartbeat/monitors/resolver.go [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+
+func (s stdResolver) ResolveIPAddr(network string, host string) (*net.IPAddr, error) {
+	return net.ResolveIPAddr(network, host)
+}
+
+func (s stdResolver) LookupIP(host string) ([]net.IP, error) {
+	return net.LookupIP(host)
+}
+
+type InvalidIPStringError struct {
```
Comment (mtojek) [inline heartbeat/monitors/resolver.go:48]: I wonder if dedicated structures for errors don't blow up the code base. In this case you use it only to prepare a string message. Maybe it's worth considering getting rid of it?

File: heartbeat/monitors/resolver.go [hunk 9]
```diff
@@ -0,0 +1,102 @@
...
+	ResolveIPAddr(network string, host string) (*net.IPAddr, error)
+	// LookupIP is an analog of net.LookupIP
+	LookupIP(host string) ([]net.IP, error)
+}
+
+// stdResolver uses the go std library to perform DNS resolution.
+type stdResolver struct{}
+
+// We only ever need one instance of this
+var StdResolver = stdResolver{}
```
Comment (mtojek) [inline heartbeat/monitors/resolver.go:38]: I'm not a fan of such defined globals/singletons. Is there a way to create an instance once it's needed?

File: heartbeat/monitors/resolver.go [hunk 10]
```diff
@@ -0,0 +1,102 @@
...
+
+func CreateStaticResolver() staticResolver {
+	return staticResolver{mapping: map[string][]net.IP{}}
+}
+
+func (i InvalidIPStringError) Error() string {
+	return fmt.Sprintf("Could not parse IP from string %s", i.ipString)
+}
+
+func (s staticResolver) Add(hostname string, ip string) error {
```
Comment (mtojek) [inline heartbeat/monitors/resolver.go:66]: Might be a stupid question: is there a need for any TTL for IP addresses?

File: heartbeat/monitors/active/tcp/tls_test.go [hunk 11]
```diff
@@ -0,0 +1,162 @@
...
+	cert, err = x509.ParseCertificate(server.TLS.Certificates[0].Certificate[0])
+	require.NoError(t, err)
+
+	// Save the server's cert to a file so heartbeat can use it
+	certFile = hbtest.CertToTempFile(t, cert)
+	require.NoError(t, certFile.Close())
+
+	return ip, port, cert, certFile, func() {
+		os.Remove(certFile.Name())
+		server.Close()
```
Comment (mtojek) [inline heartbeat/monitors/active/tcp/tls_test.go:136]: defer?

File: heartbeat/monitors/active/tcp/tcp_test.go [hunk 12]
```diff
@@ -51,139 +48,66 @@ func testTCPCheck(t *testing.T, host string, port uint16) *beat.Event {
...
-	listener, err := net.Listen("tcp", "localhost:0")
-	if err != nil {
-		panic("failed to listen on localhost: " + err.Error())
+// TestUpEndpointJob tests an up endpoint configured using either direct lookups or IPs
+func TestUpEndpointJob(t *testing.T) {
+	// Test with domain, IPv4 and IPv6
+	scenarios := []struct {
+		name       string
+		hostname   string
+		isIp       bool
```
Comment (mtojek) [inline heartbeat/monitors/active/tcp/tcp_test.go:57]: nit: isIP

File: heartbeat/monitors/active/tcp/tcp_test.go [hunk 13]
```diff
@@ -51,139 +48,66 @@ func testTCPCheck(t *testing.T, host string, port uint16) *beat.Event {
...
+		expectedIp string
```
Comment (mtojek) [inline heartbeat/monitors/active/tcp/tcp_test.go:58]: nit: expectedIP or expectedIPAddress

**Comment by mtojek** [comment]
I don't know if it's because the PR is in WIP, but there might be some flakiness in CI:

```
go: finding github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
panic: failed to listen on localhost: listen tcp [::1]:0: bind: cannot assign requested address [recovered]
	panic: failed to listen on localhost: listen tcp [::1]:0: bind: cannot assign requested address
goroutine 59 [running]:
testing.tRunner.func1(0xc0000ab700)
	/home/travis/.gimme/versions/go1.13.9.linux.amd64/src/testing/testing.go:874 +0x3a3
panic(0xb19360, 0xc0002232e0)
	/home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/panic.go:679 +0x1b2
github.com/elastic/beats/v7/heartbeat/monitors/active/tcp.newHostTestServer(0xc9d820, 0xc000195270, 0xbe782c, 0x3, 0xc000195270)
	/home/travis/gopath/src/github.com/elastic/beats/heartbeat/monitors/active/tcp/helpers_test.go:70 +0x2b1
github.com/elastic/beats/v7/heartbeat/monitors/active/tcp.TestUpEndpointJob.func1.1(0xc9d820, 0xc000195270, 0xd9fa98)
	/home/travis/gopath/src/github.com/elastic/beats/heartbeat/monitors/active/tcp/tcp_test.go:82 +0x4b
github.com/elastic/beats/v7/heartbeat/monitors/active/tcp.setupServer(0xc0000ab700, 0xc00004eed0, 0x0, 0xb89840)
	/home/travis/gopath/src/github.com/elastic/beats/heartbeat/monitors/active/tcp/helpers_test.go:56 +0x43
github.com/elastic/beats/v7/heartbeat/monitors/active/tcp.TestUpEndpointJob.func1(0xc0000ab700)
	/home/travis/gopath/src/github.com/elastic/beats/heartbeat/monitors/active/tcp/tcp_test.go:81 +0x7e
testing.tRunner(0xc0000ab700, 0xc0002232a0)
	/home/travis/.gimme/versions/go1.13.9.linux.amd64/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.13.9.linux.amd64/src/testing/testing.go:960 +0x350
FAIL	github.com/elastic/beats/v7/heartbeat/monitors/active/tcp	0.015s
FAIL
```

File: heartbeat/monitors/resolver.go (hunk 9 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go:38]: Singletons and globals do indeed create problems with using unnecessary memory, data races with concurrent access etc, testability as well. 

Since we exclusively use the `Resolver` interface we're OK on testability. Since we don't have any state (it's an empty struct), and hence to threadsafety issues there's no worries around any of the singleton concerns that I can think of. If there are other concerns, please let me know!

Contrast that with the `StaticResolver` type below this one which does have those concerns. For that one there is no singleton instance, but rather a constructor is used.

File: heartbeat/monitors/resolver.go (hunk 10 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go:66]: No, an IP has no TTL, routing is determined dynamically by the next hop on your network, so there's nothing to expire.

File: heartbeat/monitors/active/tcp/tls_test.go (hunk 11 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tls_test.go:136]: This function is returned in this way for the caller to call it in its own `defer`. The purpose of this function is to return a working TCP server, so we don't want to close the socket before the consumer has had a chance to use it :)

File: heartbeat/monitors/active/tcp/tcp.go (hunk 7 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tcp.go:94]: Later in the function there's an assignment direct to a struct `jf.tlsConfig, err = tlscommon.LoadTLSConfig(jf.config.TLS)` member that requires the declaration of `err`. Using `:=` does not solve that. It's a weird thing in go

Comment (mtojek) [reply heartbeat/monitors/active/tcp/tcp.go:94]: Maybe I wasn't clear - I see a value in having a consistency in method definitions. Either name returned variables or not. If you insist on naming them (line 94), adjust all the places where there isn't a plain "return" command.

Personally I prefer not to name them and just define returned types. I'm fine with naming them, but not using a single "return" command is redundant.

File: heartbeat/monitors/resolver.go (hunk 9 above)
Comment (mtojek) [reply heartbeat/monitors/resolver.go:38]: >  If there are other concerns, please let me know!

Well, in general this is an anti-pattern. You won't be able to detect if any other piece of code modifies it, including unit tests.

File: heartbeat/monitors/resolver.go (hunk 10 above)
Comment (mtojek) [reply heartbeat/monitors/resolver.go:58]: I was thinking rather about hostname and dynamically changed IP addresses..

File: heartbeat/monitors/active/tcp/tls_test.go (hunk 11 above)
Comment (mtojek) [reply heartbeat/monitors/active/tcp/tls_test.go:140]: I think you got me wrong. You can define `defer` in the body of the closure (`func()`). There is nothing preventing from calling defer in defer.

File: heartbeat/monitors/active/tcp/tcp.go (hunk 7 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tcp.go:94]: Consistency is very important! The style across heartbeat tends to be, if you need to initialize a var that's returned later, initialize it in the function return type definition.

File: heartbeat/monitors/resolver.go (hunk 9 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go:38]: There are exceptions to every rule. This would be an exception because none of the reasons why singletons are generally an anti-pattern apply in this specific case. If there are specific drawbacks here, please let me know.

File: heartbeat/monitors/resolver.go (hunk 10 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go:58]: Sure, well, the goal here is for this to copy the interface of the go standard library and let us swap it out for test purposes, so adding functionality on top of that is probably not what we want here.

File: heartbeat/monitors/active/tcp/tcp.go (hunk 7 above)
Comment (mtojek) [reply heartbeat/monitors/active/tcp/tcp.go:94]: Correct, but adjust then actual `return` statements:

```go
func (jf *jobFactory) loadConfig(commonCfg *common.Config) (err error) {
	if err = commonCfg.Unpack(&jf.config); err != nil {
		return err
	}
```

```return err``` -> ```return```

File: heartbeat/monitors/resolver.go (hunk 9 above)
Comment (mtojek) [reply heartbeat/monitors/resolver.go:38]: I'm happy to hear other voices here. I admit I didn't spend any time on heartbeat implementation.

**Comment by andrewvc** [comment]
I believe I've addressed all PR feedback except a few minor points.

WRT the failing test, it's one of the new ones I added for ipv6 addresses. It seems that on our CI boxes either ipv6 is not configured, or we don't have permission to bind to `::1`. I've altered the test to skip in this case. If we can't use ipv6 on the machine we can't test it :) I'll reach out to infra to see if there's something we can do here, but I don't think it should hold up the PR.

File: heartbeat/monitors/resolver.go (hunk 10 above)
Comment (mtojek) [reply heartbeat/monitors/resolver.go:58]: Same here, looking forward to hear other voices.

File: heartbeat/monitors/resolver.go (hunk 9 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go:38]: BTW, WRT modifying it, go won't let you because the var is typed as `stdResolver{}`. You could assign it a different instance of `stdResolver`, but there's no reason anyone would do that, and even if you did, it wouldn't do anything different in terms of behavior, since it's just an empty struct.

**Comment by andrewvc** [comment]
As an update, it looks like our CI servers do not have IPv6 enabled, so it makes sense to keep the tests as-is, where we check for IPv6 capabilities, and skip those tests if not present.

File: heartbeat/monitors/active/tcp/endpoint.go [hunk 14]
```diff
@@ -0,0 +1,108 @@
...
+	Hostname string
+	Ports    []uint16
+}
+
+// perPortURLs returns a list containing one URL per port
+func (e endpoint) perPortURLs() (urls []*url.URL) {
+	for _, port := range e.Ports {
+		urls = append(urls, &url.URL{
+			Scheme: e.Scheme,
+			Host:   net.JoinHostPort(e.Hostname, strconv.Itoa(int(port))),
```
Comment (urso) [inline heartbeat/monitors/active/tcp/endpoint.go:42]: Can `Hostname` already have a port number configured?

File: heartbeat/monitors/active/tcp/tcp.go [hunk 15]
```diff
@@ -39,113 +43,219 @@ func init() {
...
+type jobFactory struct {
+	config        Config
+	tlsConfig     *tlscommon.TLSConfig
+	defaultScheme string
+	endpoints     []endpoint
+	dataCheck     dataCheck
+	resolver      monitors.Resolver
+}
+
+func makeJobFactory(commonCfg *common.Config, resolver monitors.Resolver) (*jobFactory, error) {
```
Comment (urso) [inline heartbeat/monitors/active/tcp/tcp.go:83]: nit, as we allocate + to be consistent with Beats code base: newJobFactory

File: heartbeat/monitors/active/tcp/tcp.go (hunk 7 above)
Comment (urso) [reply heartbeat/monitors/active/tcp/tcp.go:94]: > Later in the function there's an assignment direct to a struct jf.tlsConfig, err = 

this can be solved by having a `var err error` before the call to tlsConfig, or store the result of LoadTLSConfig in a temporary variable. The `:=` is similar to `var`, but `jf.tlsConfig` is now new variable.

For Named returns I like the answer here: https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters

> Don't name result parameters just to avoid declaring a var inside the function; that trades off a minor implementation brevity at the cost of unnecessary API verbosity

File: heartbeat/monitors/resolver.go (hunk 9 above)
Comment (urso) [reply heartbeat/monitors/resolver.go:38]: I'd also prefer not to use `var` for globals, even if one can not really assign it. Singleton pattern might be ok, as this is an empty struct, but still prefer to provide a constructor function like so:

```
var stdResolverSingleton Resolver = stdResolver{}

func (New)StandardResolver() Resolver {
  return stdResolverSingleton
}
```

As the struct is empty the singleton doesn't even save you an alloc. It's a very small micro-optimisation saving you some call into the runtime converting the struct to an interface.

File: heartbeat/monitors/active/tcp/tcp.go [hunk 16]
```diff
@@ -39,113 +43,219 @@ func init() {
...
+	jf := &jobFactory{config: DefaultConfig, resolver: resolver}
```
Comment (urso) [inline heartbeat/monitors/active/tcp/tcp.go:84]: Consider to not export DefaultConfig. If possible change it to `func defaultConfig() config`. This reduces the chance of accidentily (introducing) sharing of references to settings in some global struct. E.g. slices and maps would be shared by reference if they are not nil before `Unpack`.

**Comment by urso** [comment]
Loads of complexity comes from the amount of jobs (permutations) created per monitor configuration. Settings contributing to this are `mode: all`, `hosts`, and `ports`. For 8.0 we might consider to deprecate some?

- `mode:all`: Most complexity and dialer chain have been introduced thanks to this setting. If `all` is set a DNS is request is made to collect all known IPs for a hostname, and create a dialer and follow up task per IP. Initially this has been a hard requirement. Is this still the case?

- `hosts`: we allow multiple hosts to be configured per monitor. `hosts` instead of `host` was introduced for consistency with other Beats. Users have only one config, at the cost of some more 'complexity' in code on the initial setup. I think that's ok and I would keep the setting.

- `ports`: This is the one I regret the most. If one only wants to check if TCP connectivity is there, ports might be convenient for users. But once you introduce 'contents' checks to your configuration, you might prefer to test one port anyways. Maybe we can deprecate this in favor of `port`, and move the responsibility to the user/UI/configuration template to create multiple monitoring configs if this is required.

File: heartbeat/monitors/active/tcp/tcp.go [hunk 17]
```diff
@@ -39,113 +43,219 @@ func init() {
...
+// makeJobs returns the actual schedulable jobs for this monitor.
+func (jf *jobFactory) makeJobs() ([]jobs.Job, error) {
+	var jobs []jobs.Job
+	for _, endpoint := range jf.endpoints {
+		for _, url := range endpoint.perPortURLs() {
+			endpointJob, err := jf.makeEndpointJob(url)
+			if err != nil {
+				return nil, err
+			}
+			jobs = append(jobs, wrappers.WithURLField(url, endpointJob))
```
Comment (urso) [inline heartbeat/monitors/active/tcp/tcp.go:128]: I wonder if this is a change in semantics introduced here or a while ago already. By creating a job per complete URL, we will have each Job do it's own DNS request. Originally only one job was created to do the initial DNS lookup, with follow up tasks per IP:Port combination. On Windows/MacOS DNS is cached automatically, but we have had incidents on Linux overloading DNS servers, due to missing caching.

File: heartbeat/monitors/resolver.go (hunk 10 above)
Comment (urso) [reply heartbeat/monitors/resolver.go:58]: The DNS resolver in the go stdlib (and in Beats) do not cache results. Heartbeat has no custom DNS client yet. Caching and TTL is currently determined by the OS configuration.

I think I'm fine not having a TTL here on the method. If we want to introduce alternative implementations with caching functionality, then TTL should be given on init to the resolver.

File: heartbeat/monitors/resolver.go [hunk 18]
```diff
@@ -0,0 +1,94 @@
...
+	return net.LookupIP(host)
+}
+
+// staticResolver allows for a custom in-memory mapping of hosts to IPs, it ignores network names
+// and zones.
+type staticResolver struct {
+	mapping map[string][]net.IP
+}
+
+func CreateStaticResolver() staticResolver {
```
Comment (urso) [inline heartbeat/monitors/resolver.go:54]: Do not return private types from an exported function/method. Why do you need CreateStaticResolver to be exported? If it is only for testing, how about having a special package with testing utilities, to make the intent more clear?

When introducing something like this resolver (so we don't have to modify the /etc/hosts file), then the resolver should become 'stackable', so we can fallback to another resolver if the hostname has not been configured.

If we use this for testing, how about accepting a `map[string][]net.IP` as parameter to `CreateStaticResolver`?

Comment (andrewvc) [reply heartbeat/monitors/resolver.go:54]: It doesn't need to be exported, just an oversight :)

File: heartbeat/monitors/active/tcp/tls_test.go (hunk 11 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tls_test.go:140]: @mtojek I may be missing something here, but why do we need a defer in the close? We don't have any branching that would prevent both statements from being executed.

Comment (mtojek) [reply heartbeat/monitors/active/tcp/tls_test.go:140]: If you know that the server should be closed as the last (one of the few last) actions in this function, you can put it in defer.
It will prevent from any potential programming errors, when somebody adds a condition causing a premature exit from the function. 
In this case the `os.Remove` function returns an error if the operation fails. If anyone checks this error and decides to fail fast (`if err != nil { return err }`), then they might forget about closing the server.

(This is only suggestion, I understand that it may bring too little value at the moment.)

Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tls_test.go:140]: I see what you mean. I'm not checking the error there because as you mention it's not really a huge value (it's a tempfile created by a test). That said, I think it does make sense to fail the test if the tempfile can't be removed (we have the test context here) and use defer to close the server.

I'll make that change and add the defer.

File: heartbeat/monitors/active/tcp/endpoint.go (hunk 14 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/endpoint.go:42]: No, the `endpoint` type has had this removed. The goal of `endpoint` is to normalize things so we have a `hostname` instead of a `host` (following the convention of go's URL package where a `Host` is a URL+Port and a `Hostname` is just the name).

So, if there was a port combined with a hostname it's been split out.

File: heartbeat/monitors/resolver.go (hunk 18 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go:54]: I take it back, it does need to be exported because it's used by the tcp monitor package tests. I could move it there, but I think it makes more sense to keep it here since we'll eventually use it in tests for http/icmp.

File: heartbeat/monitors/active/tcp/tls_test.go (hunk 11 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tls_test.go]: Changed added!

File: heartbeat/monitors/resolver.go (hunk 18 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go]: Alternatively I could extract all this resolver stuff to its own package, but I'm indifferent on that matter.

File: heartbeat/monitors/active/tcp/tcp.go (hunk 17 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tcp.go:128]: I took a look at the code here, and I do think we can fix this so we restore the behavior before this patch. However, I agree with you that it's not a clear win for `ports` because that code is tricky. I think for `mode: all` it still makes sense to keep the behavior, because more people use that (and it provides benefits for icmp/tcp/http not just tcp).

However, for TCP, given that this is a very rarely used feature AFAICT I don't think the code complexity is worth maintaining the single DNS lookup. Additionally, there are workarounds in the rare case where DNS load is too high. One could always install a caching resolver on the same box as heartbeat in the worst case.

**Comment by andrewvc** [comment]
@urso thanks for the review. I'd rather not make *too* many changes in this PR re mode/ports/hosts . The original purpose here was fixing the TLS hostname bug, and we've already gone far past that point, and cleaned up the code substantially.

I agree that it's worth considering deprecating `ports`, but I'd ask that we have that discussion in a separate issue since we'd be waiting till 8.0 to remove the code.

File: heartbeat/monitors/active/tcp/tcp.go (hunk 15 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tcp.go]: Done in this one case and the new resolver, but I'm trying to keep a lid on scope for this PR. We use make/create all over the heartbeat codebase.

File: heartbeat/monitors/resolver.go (hunk 18 above)
Comment (urso) [reply heartbeat/monitors/resolver.go]: If it's purpose is to be used for testing only, then we should at least have this reflected in the package name.

Comment (andrewvc) [reply heartbeat/monitors/resolver.go]: Well, `StdResolver` is used for production, `StaticResolver` is used in another package for test purposes. I could break it out to its own package, but that seems a bit excessive, since that package would have to export it.

We could put `StaticResolver` in a test file in the `tcp` package, but in the future we'll probably have tests that want to reuse it from the `http` and `icmp` monitors.

What do you think the best way forward is?

File: heartbeat/monitors/active/tcp/tcp.go (hunk 7 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tcp.go]: Changed per the go styleguide

File: heartbeat/monitors/resolver.go (hunk 9 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go]: Changed, given that there's consensus around using a constructor I just ditched the var.

File: heartbeat/monitors/resolver.go (hunk 18 above)
Comment (urso) [reply heartbeat/monitors/resolver.go]: Can we think of other testing helpers? E.g. some helper that would drive a 'job' with it's followup tasks?

Comment (andrewvc) [reply heartbeat/monitors/resolver.go]: This has been moved to the tcp test package for now.

File: heartbeat/monitors/resolver.go (hunk 10 above)
Comment (andrewvc) [reply heartbeat/monitors/resolver.go]: OK, given that we don't have any feature supporting TTLs, there doesn't seem to be a reason to add that in this PR

File: heartbeat/monitors/active/dialchain/net.go [hunk 19]
```diff
@@ -45,7 +45,7 @@ import (
 //    }
 //  }
 func TCPDialer(to time.Duration) NetDialer {
```
Comment (mtojek) [inline heartbeat/monitors/active/dialchain/net.go:47]: nit: I see that the file `net.go` contains only dialers. Do you think we can rename it to `dialers.go`?
Also, there are some functions in `util.go` that refer to `transport.Dialer`, I wonder if we can divide the stuff in  these two files into `dialers.go` and `layers.go`. We could get rid of utils ;)

File: heartbeat/monitors/active/tcp/tcp_test.go [hunk 20]
```diff
@@ -18,22 +18,19 @@
...
 	"net"
 	"net/http"
 	"net/http/httptest"
 	"net/url"
-	"os"
 	"strconv"
 	"testing"
-	"time"
+
+	"github.com/elastic/go-lookslike/validator"
```
Comment (mtojek) [inline heartbeat/monitors/active/tcp/tcp_test.go:29]: nit: please sort imports

File: heartbeat/monitors/active/dialchain/net.go (hunk 19 above)
Comment (andrewvc) [reply heartbeat/monitors/active/dialchain/net.go:47]: Yep, good call.

File: heartbeat/monitors/active/tcp/tcp_test.go (hunk 20 above)
Comment (andrewvc) [reply heartbeat/monitors/active/tcp/tcp_test.go:29]: ++, I reset my IDE and lost my auto-sorter.
