### PR TITLE
Stop using mage:import in custom beats 7.4

### LINKED ISSUE #13998: mage:import doesn't use vendored beats on custom beats
Since 7.4.0, custom beats reuse common mage targets from beats, for that they make use of `mage:import`. This is not using vendored beats in the `vendor` directory, though other go tools do use it. This causes problems if a different version of beats is in the `GOPATH`, like this one:
```
# command-line-arguments
./mage_output_file.go:498:5: undefined: common.AddLicenseHeaders
./mage_output_file.go:518:5: undefined: common.CheckLicenseHeaders
Error: error compiling magefiles
```

It was reported in the mage repository (https://github.com/magefile/mage/issues/244). Migration of Beats to go modules is proposed there as solution.

We will need to look for another solution in the meantime. Or look for an alternative way of reusing targets.

For confirmed bugs, please report:
- Version: >= 7.4.0
- Steps to Reproduce: Create a new beat from a version of beats that makes use of `mage:import` in magefiles, and checkout a different version in the `GOPATH`.

// cc: @radoondas

### PR DESCRIPTION
**Pull request by jsoriano**
`mage:import` doesn't take into account vendorized dependencies, this is a
problen for custom beats, because by default they have libbeat as a
vendorized dependency. The solution would be to use go modules, but in
the meantime lets remove the use of `mage:import` from the magefiles
intended to be used by custom beats.

Revert part of #13239 related to custom beats, backports part of #14162.

Fixes #13998 for 7.4.

### CODE REVIEW

File: generator/metricbeat/{beat}/magefile.go [hunk 1]
```diff
@@ -96,6 +121,20 @@ func CollectDocs() error {
...
+func GoTestUnit(ctx context.Context) error {
+	return devtools.GoTest(ctx, devtools.DefaultGoTestUnitArgs())
+}
+
+// GoTestIntegration executes the Go integration tests.
+// Use TEST_COVERAGE=true to enable code coverage profiling.
+// Use RACE_DETECTOR=true to enable the race detector.
+func GoTestIntegration(ctx context.Context) error {
+	return devtools.GoTest(ctx, devtools.DefaultGoTestIntegrationArgs())
+}
```
Comment (jsoriano) [inline generator/metricbeat/{beat}/magefile.go]: @fearful-symmetry so it seems that we had also a target for integration tests before, maybe I should include this target too in the changes for master/7.5. WDYT?

Comment (fearful-symmetry) [reply generator/metricbeat/{beat}/magefile.go]: I would think so, yah
