### PR TITLE
Log monitoring bulk failures

### LINKED ISSUE #14303: Beats will not log monitoring bulk index failure
When the monitoring user does not have the required privileges to write into `.monitoring-beats-*` but does have other indexing privileges (e.g. to write to `auditbeat-*`), a Beat will not log any errors about the failed monitoring bulk index requests.

The reason is that while Elasticsearch will return `403 Forbidden` when the user has no write privileges at all, it will return `200` for a `_bulk` request if a user has at least one write privilege - even if it's not for the monitoring index.

Instead, errors are going to be returned in the body, e.g. see the following (I had to add a debug statement into the code, this is not what a Beat actually prints):
```
2019-10-29T10:33:46.579Z        DEBUG   [elasticsearch] elasticsearch/client.go:835     POST http://localhost:9200/.monitoring-beats-7-2019.10.29/_bulk 200 {"took":0,"errors":true,"items":[{"index":{"_index":".monitoring-beats-7-2019.10.29","_id":null,"status":403,"error":{"type":"security_exception","reason":"action [indices:admin/create] is unauthorized for user [auditbeat]"}}}]} {}
```

For normal event publishing, Libbeat parses the return body in a function called `bulkCollectPublishFails`:
https://github.com/elastic/beats/blob/9b96d62882d054a33250497908976325fa7dd0c2/libbeat/outputs/elasticsearch/client.go#L471-L475

But this does not happen for the body of monitoring data bulk requests.

I tried to fix this, but the two logics for sending collected vs. monitoring data are quite different so couldn't do it easily.

/cc @ycombinator - seems you've touched this code most recently

### PR DESCRIPTION
**Pull request by ycombinator**
Resolves #14303.

As reported in #14303, when the Elasticsearch monitoring reporter in libbeat sends a bulk API request to Elasticsearch, and that request fails, the errors are currently swallowed. This is because the actual response code for the bulk API request is `200 OK`; the actual errors are embedded in the request's response body.

This PR teaches the Elasticsearch monitoring reporter to parse the bulk API response and log any errors. For the parsing, the same code as the Elasticsearch output is reused.

## Testing this PR
1. Start up Elasticsearch with security enabled. Make sure you know the password for the `elastic` superuser.

2. Create a role that grants necessary privileges for managing and writing to `metricbeat-*` indices.
   ```
   curl -s -u elastic -H 'Content-Type: application/json' 'http://localhost:9200/_security/role/mb_writer' -d '{ "cluster": [ "monitor", "manage_ilm", "manage_index_templates" ], "indices": [ { "names": [ "metricbeat-*" ], "privileges": [ "all" ] } ] }'
   ```

3. Create a user with the above role.
   ```
   curl -s -u elastic -H 'Content-Type: application/json' 'http://localhost:9200/_security/user/mb_writer' -d '{ "password": "mb_writer", "roles": [ "mb_writer" ] }'
   ```

4. Build Metricbeat with this PR.
   ```
   cd $GOPATH/src/github.com/elastic/beats/metricbeat
   mage build
   ```

5. Start Metricbeat with monitoring enabled and specifying the credentials of the above user for the `elasticsearch` output.
   ```
   ./metricbeat -e -E output.elasticsearch.username=mb_writer -E output.elasticsearch.password=mb_writer -E monitoring.enabled=true
   ```

6. Verify that `metricbeat-*` indices are being created and populated in Elasticsearch but no `.monitoring-beats-*`  indices are being created.
   ```
   curl -s -u elastic 'http://localhost:9200/_cat/indices'
   ```

7. Verify that there **are** warnings in the log like so:
   ```
   2019-11-01T08:57:43.910-0700    WARN    elasticsearch/client.go:258     monitoring bulk item insert failed (i=0, status=403): {"type":"security_exception","reason":"action [indices:admin/create] is unauthorized for user [mb_writer]"}
   ```

### CODE REVIEW

**Comment by ycombinator** [comment]
jenkins, test this

File: libbeat/outputs/elasticsearch/bulkapi.go [hunk 1]
```diff
@@ -34,16 +35,15 @@ type bulkRequest struct {
 	requ *http.Request
 }
 
-type bulkResult struct {
-	raw []byte
-}
+// BulkResult contains the result of a bulk API request.
+type BulkResult json.RawMessage
```
Comment (ph) [inline libbeat/outputs/elasticsearch/bulkapi.go]: +1 nice change

File: libbeat/outputs/elasticsearch/client.go [hunk 2]
```diff
@@ -553,9 +527,43 @@ func bulkCollectPublishFails(
 	return failed, stats
 }
 
-func itemStatus(reader *jsonReader) (int, []byte, error) {
+// BulkReadToItems reads the bulk response up to (but not including) items
```
Comment (ph) [inline libbeat/outputs/elasticsearch/client.go]:
```suggestion
// BulkReadToItems reads the bulk response up to (but not including) items.
```

**Comment by ycombinator** [comment]
Travis CI is green. Jenkins CI failures are unrelated. Merging.
