### PR TITLE
[winlogbeat] Add formatted index setting to event log configs

### LINKED ISSUE #15062: [Winlogbeat] Allow inputs to specify output index
This is a sub-issue of the larger meta-issue elastic/beats#13255 (broken out for project tracking): to allow Winlogbeat inputs to set a custom output index, similar to what elastic/beats#14010 did for Filebeat.

### PR DESCRIPTION
**Pull request by faec**
Resolves #15062.

Adds an `index` setting to all Event Log types to specify the output index for events from that source.

### CODE REVIEW

File: winlogbeat/eventlog/eventlog.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ type Record struct {
 	Offset checkpoint.EventLogState // Position of the record within its source stream.
 }
 
-// ToMapStr returns a new MapStr containing the data from this Record.
+// ToEvent returns a new beat.Event containing the data from this Record.
```
Comment (ycombinator) [inline winlogbeat/eventlog/eventlog.go]: Good catch — thanks for fixing!
