### PR TITLE
Fix startup with failing configuration

### LINKED ISSUE #25829: [Agent]: On restarting Agent host, Metricbeat is orphaned & stuck in crash loop (relates to policy changes + possibly w Fleet server usage)
**Steps followed:**

1. Login to self-managed Kibana environment.
2. Install Agent with Default Fleet Server Policy.
3. Assign "Agent" to Default policy having System, Endpoint and Fleet Server Integration.
4. Restart elastic-agent from services.
5. Navigate to agent "Logs" tab and observe Metricbeat service stuck in "Starting-Restarting-Crashed" loop.

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6532594/logs.zip)

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

What is going on is a bit weird race.
Basically we start ok but troubles come on restart.

On restart we apply stored config to start MB (`mb1`) with failing configuration, 
MB does not exit just reports Failed state because it cannot apply `system/load` on windows.
At this time 10 second timer to recover is started otherwise we plan a restart.

Then we pull config from fleet and decide MB should be started. 
We start MB `mb2` while `mb1` is still running. We are starting it because check checks for terminal statuses and Failed is one of them. 
This `mb2` starts reports running, timer for killing `mb1` is stopped. Because MB is running and it does not differentiate between processes.
`mb2` fails on `data.path` conflict with `mb1`

watcher detects stopped metricbeat and `mb3` is started, `mb1` is still running, we dont have any information about `mb1` anymore anywhere.
`mb3` fails on same thing `mb2` failed and exits.

`mb1` still running in Failed state and we try `mbX` over and over again.

This PR adds some closers to watcher, some checks on Failure termination and passing proc so watcher and terminator are killing the process they were designed to kill. 

While this fix works, i dont like the whole approach where we handle start/stop/restart from 4-5 places and they can be conflicting. I would like to see this redesigned. But i've spent 5 days chasing this and need some social distancing from the topic so this fix is OK at the moment for me.

How to test:
- Build 
- Create config with fleet-server, system and endpoint integration
- Deploy on windows machine
- Wait for everything to settle and restart a lot of times to check if you see 3 metricbeat processes running in Task Manager. 

How it behaved before the fix: we had 3 metricbeats, 2 with stable PID (one for monitoring, one is `mb1`) and then thirds MB process kept changing PID (crash-restart loop)

## Why is it important?

Fixes #25829 

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

File: x-pack/elastic-agent/pkg/core/plugin/process/app.go [hunk 1]
```diff
@@ -192,16 +196,32 @@ func (a *Application) watch(ctx context.Context, p app.Taggable, proc *process.I
 		case ps := <-a.waitProc(proc.Process):
 			procState = ps
 		case <-a.bgContext.Done():
-			a.Stop()
+			return
```
Comment (kvch) [inline x-pack/elastic-agent/pkg/core/plugin/process/app.go:199]: Just curious: is there any connection between `a.bgContext` and `ctx`? Does `ctx` has to be cancelled when `a.bgContext` is cancelled?

Comment (michalpristas) [reply x-pack/elastic-agent/pkg/core/plugin/process/app.go:199]: bgContext is like a cancellation token passed from top of the app and cancelled on exit or unenroll, so agent cleans and backs up everything in a nice manner. we want to avoid just shutting down agent without any cleaning as this may turn out problematic

File: x-pack/elastic-agent/pkg/core/plugin/process/app.go [hunk 2]
```diff
@@ -192,16 +196,32 @@ func (a *Application) watch(ctx context.Context, p app.Taggable, proc *process.I
...
+		case <-ctx.Done():
+			// closer called
 			return
 		}
 
 		a.appLock.Lock()
 		if a.state.ProcessInfo != proc {
+			// kill original process if possible
+			if proc != nil && proc.Process != nil {
+				_ = proc.Process.Kill()
```
Comment (urso) [inline x-pack/elastic-agent/pkg/core/plugin/process/app.go:209]: shall we wait or check for other errors?

File: x-pack/elastic-agent/pkg/core/plugin/process/app.go [hunk 3]
```diff
@@ -192,16 +196,32 @@ func (a *Application) watch(ctx context.Context, p app.Taggable, proc *process.I
...
 			a.appLock.Unlock()
 			return
 		}
+
+		// stop the watcher
+		a.stopWatcher(a.state.ProcessInfo)
+
+		// was already stopped by Stop, do not restart
+		if a.state.Status == state.Stopped {
+			return
```
Comment (urso) [inline x-pack/elastic-agent/pkg/core/plugin/process/app.go:222]: are we missing a `a.appLock.Unlock()t here?

File: x-pack/elastic-agent/pkg/core/plugin/process/app.go (hunk 2 above)
Comment (michalpristas) [reply x-pack/elastic-agent/pkg/core/plugin/process/app.go:209]: this is best effort

File: x-pack/elastic-agent/pkg/core/plugin/process/app.go (hunk 3 above)
Comment (michalpristas) [reply x-pack/elastic-agent/pkg/core/plugin/process/app.go:222]: true

Comment (urso) [reply x-pack/elastic-agent/pkg/core/plugin/process/app.go:223]: checking the complete function body, we always use `Unlock` for each exit path. Better add the `defer unlock` right after the `lock` in order to reduce the chance of introducing new deadlocks in the future.

File: x-pack/elastic-agent/pkg/core/plugin/process/app.go [hunk 4]
```diff
@@ -250,3 +274,31 @@ func (a *Application) setState(s state.Status, msg string, payload map[string]in
...
 	a.monitor.Cleanup(a.desc.Spec(), a.pipelineID)
 }
+
+func gracefulKill(proc *process.Info) {
+	if proc == nil || proc.Process == nil {
+		return
+	}
+
+	// send stop signal to request stop
+	proc.Process.Signal(os.Interrupt)
```
Comment (blakerouse) [inline x-pack/elastic-agent/pkg/core/plugin/process/app.go:284]: Does this work on Windows? I thought `process.Info` had each OS implementation that is why it was added. Should we just move this logic into the `Stop()` function of `process.Info`?

Comment (michalpristas) [reply x-pack/elastic-agent/pkg/core/plugin/process/app.go:284]: you're right windows does not implement sending interupt. using Stop function instead

**Review by blakerouse — APPROVED** [review]
With the latest change to using `Stop` this looks good.

**Comment by EricDavisX** [comment]
not sure if the 7.13.2 label helps, but i def would like to see this back ported to 7.13.x - @michalpristas
