### PR TITLE
Fix Metricbeat k8s metadata sometimes not being present at startup

### LINKED ISSUE #41213: K8s metadata for metricbeat Kubernetes module missing at startup
When using the kubernetes module, metadata can randomly be missing after metricbeat starts. I've noticed this with `Deployment` metadata while testing fixes for https://github.com/elastic/elastic-agent/issues/5623, but I suspect it can happen whenever a metadata watcher is shared between multiple enrichers.

The problem presents as metadata not being present for data coming from a given metricbeat instance. Restarting can fix the issue, or create it if it wasn't present. Modifying any of the resources which are the source of the metadata (in my case, ReplicaSets) makes the metadata appear, suggesting that the enricher doesn't see the initial resource list from the watcher, but does see subsequent changes.

Here's a simple dashboard I've created to track the metadata across elastic-agent restarts:

Image

I strongly suspect we have a race condition in the [enricher initialization code](https://github.com/elastic/beats/blob/9fde7b0078774c4c7df1c87cbc3b4a7b6b463e66/metricbeat/module/kubernetes/util/kubernetes.go#L968), and I've fixed the issue in a PoC by getting rid of this initialization. However, I haven't been able to definitively explain how it could happen given the locking we do around it. In any case, what we do there is far from optimal, and worth improving if it fixes this issue.

### PR DESCRIPTION
**Pull request by swiatekm**
## Proposed commit message

Fix Metricbeat k8s metadata sometimes not being present at startup

In the metricbeat k8s module, each metricset has an enricher, which is used to add k8s metadata to events. Enrichers use watchers to watch k8s resource changes, and these watchers can be shared between enrichers. This is implemented by each enricher maintaining a writethrough cache of metadata - when a K8s event indicating a change to a resource is received, the metadata cache is updated.

The problem with this is that a watcher is only started once, so enrichers which are created after it was started, have to catch up on the resource change events. This is a great opportunity for race conditions, and is in general unnecessarily complicated.

Instead, we turn the writethrough cache into a readthrough cache. The change event handlers now only invalidate the cache, and the enricher computes the metadata when it is first requested. This completely sidesteps the catch up problem, as we only compute the metadata lazily.

I've also refactored the code a bit:

- Resource event handlers are now added to a watcher when it is created, as opposed to when an enricher is created. They're always the same, so there's no reason to do it multiple times.
- Removed `TestBuildMetadataEnricher_EventHandler_PastObjects`, as it doesn't seem to check anything not covered by other tests.
- Rearranged the `createWatcher` function, so actual watcher creation (as opposed to skipping because it's already there) happens on the main path.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Install elastic-agent in K8s using the standalone manifests and track the metadata.

## Related issues

- Closes #41213

### CODE REVIEW

**Comment by MichaelKatsoulis** [comment]
I took a look and the code changes look ok to me. The part of the [enricher initialization code](https://github.com/elastic/beats/blob/9fde7b0078774c4c7df1c87cbc3b4a7b6b463e66/metricbeat/module/kubernetes/util/kubernetes.go#L968) was the most tricky one when we implemented the shared watchers logic.  Maybe we overcomplicated it.

I am not sure still about the problem it tries to solve, as we had tested these scenarios a lot. 
But this new approach looks simpler.

**Review by MichaelKatsoulis — APPROVED** [review]

File: metricbeat/module/kubernetes/util/kubernetes.go [hunk 1]
```diff
@@ -1142,11 +1086,8 @@ func (e *enricher) Stop(resourceWatchers *Watchers) {
 // This method is executed whenever a new event is created and about to be published.
 // The enricher's index method is used to retrieve the resource identifier from each event.
 func (e *enricher) Enrich(events []mapstr.M) {
-	e.RLock()
-	defer e.RUnlock()
-
 	for _, event := range events {
-		if meta := e.metadata[e.index(event)]; meta != nil {
+		if meta := e.getMetadata(event); meta != nil {
```
Comment (pkoutsovasilis) [inline metricbeat/module/kubernetes/util/kubernetes.go:1090]: with the lock moved from above just in the scope of `getMetadata` doesn't this mean that all of the below

```
k8s, err := meta.GetValue("kubernetes")
```

```
if podMeta, ok := k8sMeta["pod"].(mapstr.M); ok {
  event.DeepUpdate(podMeta)
}
```

are prone to race conditions?

Comment (swiatekm) [reply metricbeat/module/kubernetes/util/kubernetes.go:1090]: Good catch. I think in practice everything is fine, as we never actually modify the metadata after creating it. But I would like to rewrite this so the safety is immediately apparent. I think the simplest way of achieving this would be to make a copy in `getMetadata` and then avoid making copies here in `Enrich`. Let me try that.

File: metricbeat/module/kubernetes/util/kubernetes.go [hunk 2]
```diff
@@ -1163,10 +1104,9 @@ func (e *enricher) Enrich(events []mapstr.M) {
 				}
 
 				// don't apply pod metadata to module level
-				k8sMeta = k8sMeta.Clone()
 				delete(k8sMeta, "pod")
 			}
-			ecsMeta := meta.Clone()
+			ecsMeta := meta
```
Comment (pkoutsovasilis) [inline metricbeat/module/kubernetes/util/kubernetes.go:1109]: nit: not required since the Clone is now handled by the e.getMetadata(...)

File: metricbeat/module/kubernetes/util/kubernetes.go (hunk 1 above)
Comment (pkoutsovasilis) [reply metricbeat/module/kubernetes/util/kubernetes.go:1090]: ok since we may do the Clone, let's be "eager" about it

**Review by pkoutsovasilis — APPROVED** [review]

File: metricbeat/module/kubernetes/util/kubernetes.go (hunk 2 above)
Comment (swiatekm) [reply metricbeat/module/kubernetes/util/kubernetes.go:1109]: This is just renaming the variable for clarity. Maps are reference types in Go, so this really just copies a pointer.

Comment (pkoutsovasilis) [reply metricbeat/module/kubernetes/util/kubernetes.go:1109]: I know that maps are built-in references ty 🙂 I have to admit that this is the first time I witness a new variable assignment in the same scope for clarity reasons; however, I have seen comments added or renaming the variable at the creation time, for clarity reasons

Comment (swiatekm) [reply metricbeat/module/kubernetes/util/kubernetes.go:1109]: The real meaning of this series of statements is "`ecsMeta` is `meta` without the `kubernetes` key". It was clearer when we were actually cloning `meta`, but we don't need to do that anymore. I can change it to only use `meta` if you think this is confusing.

**Comment by swiatekm** [comment]
@gizas are you ok with me merging this? I know you wanted to try reproducing #41213 first.

**Comment by gizas** [comment]
Sure @swiatekm , I did not have time to reproduce tbh. But as long I understood the visalisation and why the issue was raised I am ok

**Review by gizas — APPROVED** [review]
