### PR TITLE
Do not fail recursive watches due to unaccessible subdir

### LINKED ISSUE #5911: Auditbeat - Windows recursive file watches
Opening this as a reminder to investigate this more. Recursive watches on Windows for some of the directories in our default config were failing.

For confirmed bugs, please report:
- Version: master
- Operating System: Windows 2012 R2
- Steps to Reproduce:
  - Start auditbeat.exe as Administrator (vagrant in my case). 
  - Use the default config, but enable recursive file watches.

Logs:

2017-12-18T16:01:04.719-0800	WARN	file_integrity/eventreader_fsnotify.go:43	[file_integrity] Failed to watch C:\Windows\System32: CreateFile: Access is denied.

2017-12-18T16:01:04.458-0800	WARN	file_integrity/eventreader_fsnotify.go:43	[file_integrity] Failed to watch C:\Windows: CreateFile: Access is denied.

### PR DESCRIPTION
**Pull request by adriansr**
When some subdirectory of a watched dir can't be watched (inaccessible due to permissions for example), do not fail to watch the whole tree.

Fixes #5911

### CODE REVIEW

File: auditbeat/module/file_integrity/monitor/monitor_test.go [hunk 1]
```diff
@@ -213,16 +309,23 @@ func testDirOps(t *testing.T, dir string, watcher Watcher) {
...
+			return fsnotify.Event{}, errReadTimeout
+
+		case msg, ok := <-watcher.EventChannel():
+			if !ok {
+				return fsnotify.Event{}, errors.New("channel closed")
+			}
+			return msg, nil
+
+		case err := <-watcher.ErrorChannel():
+			fmt.Printf("readTimeout got error: %v\n", err)
```
Comment (andrewkroh) [inline auditbeat/module/file_integrity/monitor/monitor_test.go]: Can you pass a testing.TB interface and use Logf instead. It will keep the output clean for the non-verbose runs.
