### PR TITLE
Fix TestDockerStart flaky test

### LINKED ISSUE #20360: TestDockerStart flaky test
Recently the TestDockerStart test is failing always:

```
[2020-07-30T13:17:45.664Z] FAILURES:

[2020-07-30T13:17:45.664Z] Package: github.com/elastic/beats/v7/libbeat/autodiscover/providers/docker

[2020-07-30T13:17:45.664Z] Test:    TestDockerStart

[2020-07-30T13:17:45.664Z]     TestDockerStart: docker_integration_test.go:125: Timeout waiting for provider events

[2020-07-30T13:17:45.664Z] ----

[2020-07-30T13:17:45.664Z] SUMMARY:

[2020-07-30T13:17:45.664Z]   Fail:     1

[2020-07-30T13:17:45.664Z]   Skip:     9

[2020-07-30T13:17:45.664Z]   Pass:     1917

[2020-07-30T13:17:45.664Z]   Packages: 114

[2020-07-30T13:17:45.664Z]   Duration: 7m31.342788597s

[2020-07-30T13:17:45.664Z]   Coverage Report: /go/src/github.com/elastic/beats/libbeat/build/TEST-go-integration.html

[2020-07-30T13:17:45.664Z]   JUnit Report:    /go/src/github.com/elastic/beats/libbeat/build/TEST-go-integration.xml

[2020-07-30T13:17:45.664Z]   Output File:     /go/src/github.com/elastic/beats/libbeat/build/TEST-go-integration.out

[2020-07-30T13:17:45.664Z] >> go test: Integration Test Failed

[2020-07-30T13:17:45.664Z] Error: go test failed: 1 test failures

[2020-07-30T13:17:45.664Z] github.com/elastic/beats/v7/dev-tools/mage.GoTest

[2020-07-30T13:17:45.664Z] 	/var/lib/jenkins/workspace/Beats_beats_master/src/github.com/elastic/beats/dev-tools/mage/gotest.go:309

[2020-07-30T13:17:45.664Z] github.com/elastic/beats/v7/dev-tools/mage/target/integtest.GoIntegTest.func1

[2020-07-30T13:17:45.664Z] 	/var/lib/jenkins/workspace/Beats_beats_master/src/github.com/elastic/beats/dev-tools/mage/target/integtest/integtest.go:71

[2020-07-30T13:17:45.664Z] github.com/elastic/beats/v7/dev-tools/mage.(*DockerIntegrationTester).InsideTest

[2020-07-30T13:17:45.664Z] 	/var/lib/jenkins/workspace/Beats_beats_master/src/github.com/elastic/beats/dev-tools/mage/integtest_docker.go:175

[2020-07-30T13:17:45.664Z] github.com/elastic/beats/v7/dev-tools/mage.(*IntegrationRunner).Test

[2020-07-30T13:17:45.664Z] 	/var/lib/jenkins/workspace/Beats_beats_master/src/github.com/elastic/beats/dev-tools/mage/integtest.go:263

[2020-07-30T13:17:45.664Z] github.com/elastic/beats/v7/dev-tools/mage/target/integtest.GoIntegTest

[2020-07-30T13:17:45.664Z] 	/var/lib/jenkins/workspace/Beats_beats_master/src/github.com/elastic/beats/dev-tools/mage/target/integtest/integtest.go:70

[2020-07-30T13:17:45.664Z] main.main.func26

[2020-07-30T13:17:45.664Z] 	/var/lib/jenkins/workspace/Beats_beats_master/src/github.com/elastic/beats/libbeat/mage_output_file.go:569

[2020-07-30T13:17:45.664Z] main.main.func12.1

[2020-07-30T13:17:45.664Z] 	/var/lib/jenkins/workspace/Beats_beats_master/src/github.com/elastic/beats/libbeat/mage_output_file.go:284

[2020-07-30T13:17:45.664Z] runtime.goexit

[2020-07-30T13:17:45.664Z] 	/var/lib/jenkins/workspace/Beats_beats_master/.gvm/versions/go1.14.4.linux.amd64/src/runtime/asm_amd64.s:1373
```

### PR DESCRIPTION
**Pull request by jsoriano**
Some changes are done to give more resilience to the test:
* Wait till image pull is finished, and retry in case of failure.
* Checked events are filtered by container id instead of image name,
  so tests are not affected by other containers that may be running
  in the system.
* Check timeout is for all events now, instead of being reset after an
  event is received.
* Container is removed after test is finished.

Fixes #20360.

### CODE REVIEW

**Comment by jsoriano** [comment]
jenkins run the tests again please

File: libbeat/tests/docker/docker.go [hunk 1]
```diff
@@ -65,6 +66,36 @@ func (c Client) ContainerStart(image string, cmd []string, labels map[string]str
...
 
+// imagePull pulls an image
+func (c Client) imagePull(image string) (err error) {
+	ctx := context.Background()
+	_, _, err = c.cli.ImageInspectWithRaw(ctx, image)
+	if err == nil {
+		// Image already available, do nothing
+		return nil
+	}
+	for retry := 0; retry < 3; retry++ {
```
Comment (ChrsMark) [inline libbeat/tests/docker/docker.go:77]: Not sure if we could make it configurable like having this number of retries to be a function variable. Also maybe to add sleep time between each of the retries, however not sure if this is needed at all since not familiar with the nature of the errors that may occur here.

Suggestion would look like:
`imagePullWithRetry(image string, retries int, interval int)`

**Review by ChrsMark — APPROVED** [review]
lgtm. Just left a suggestion/question to evaluate. No blocking though.

File: libbeat/tests/docker/docker.go (hunk 1 above)
Comment (jsoriano) [reply libbeat/tests/docker/docker.go:77]: Good suggestion, but I think this wouldn't be needed by now, and in any case we wouldn't expose these settings in the public methods.
I would prefer to  add them if we need it at some moment.

Comment (ChrsMark) [reply libbeat/tests/docker/docker.go:77]: 👍
