### PR TITLE
Error out on invalid Autodiscover template conditions settings

### LINKED ISSUE #7183: Empty condition in configuration crashes beats
When a `condition` from the configuration has no sub-fields,  `NewCondition` will return a `nil` condition. However, this `nil` condition will result in a panic when any of its methods is invoked.

- Version: 6.2.4
- Operating System: N/A
- Discuss Forum URL: https://discuss.elastic.co/t/filebeats-autodiscover-segmentation-violation/133342
- Steps to Reproduce: 

Use this broken config from the discuss thread above (note that the `equals` clause is wrongly indented at the same level as `condition`):
```
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
          equals:
            docker.container.image: nginx
          config:
            - module: nginx
              access:
                prospector:
                  type: docker
                  container.ids:
                    - "${data.docker.container.id}"
              error:
                prospector:
                  type: docker
                  container.ids:
                    - "${data.docker.container.id}"
```

will result in a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xebfea6]
goroutine 58 [running]:
github.com/elastic/beats/libbeat/processors.(*Condition).Check(0x0, 0x1f36d60, 0xc42007d5c0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/processors/condition.go:205 +0x26
github.com/elastic/beats/libbeat/autodiscover/template.(*Mapper).GetConfig(0xc42049c380, 0xc42007d5c0, 0xc4204bc528, 0xac369f, 0x10)
	/go/src/github.com/elastic/beats/libbeat/autodiscover/template/config.go:62 +0x63e
github.com/elastic/beats/libbeat/autodiscover/providers/docker.(*Provider).publish(0xc4205340c0, 0xc42007d5c0)
	/go/src/github.com/elastic/beats/libbeat/autodiscover/providers/docker/docker.go:137 +0x3d
github.com/elastic/beats/libbeat/autodiscover/providers/docker.(*Provider).emitContainer(0xc4205340c0, 0xc42015a240, 0x16c6c00, 0x5)
	/go/src/github.com/elastic/beats/libbeat/autodiscover/providers/docker/docker.go:110 +0x78a
github.com/elastic/beats/libbeat/autodiscover/providers/docker.(*Provider).Start.func1(0xc4205340c0)
	/go/src/github.com/elastic/beats/libbeat/autodiscover/providers/docker/docker.go:74 +0x1e9
created by github.com/elastic/beats/libbeat/autodiscover/providers/docker.(*Provider).Start
	/go/src/github.com/elastic/beats/libbeat/autodiscover/providers/docker/docker.go:65 +0x3f
```

Apart from NewCondition always returning an usable condition, we should try to warn the user or err on this configuration mistake

### PR DESCRIPTION
**Pull request by exekias**
This should fix #7183

### CODE REVIEW

File: libbeat/autodiscover/autodiscover.go [hunk 1]
```diff
@@ -54,7 +56,7 @@ func NewAutodiscover(name string, pipeline beat.Pipeline, adapter Adapter, confi
 	for _, providerCfg := range config.Providers {
 		provider, err := Registry.BuildProvider(bus, providerCfg)
 		if err != nil {
-			return nil, err
+			return nil, errors.Wrap(err, "Error in autodiscover provider settings")
```
Comment (ph) [inline libbeat/autodiscover/autodiscover.go]: s/Error/error
