### PR TITLE
kubernetes processor use correct os path separator

### LINKED ISSUE #9196: kubernetes_metadata metadata does not work on windows
Version: 6.5.1

[Due to a trailing `/`](https://github.com/elastic/beats/blob/99824df163863478d27688206e18ec27bc1b3ac5/filebeat/processor/add_kubernetes_metadata/matchers.go#L62) that is placed at the end of the `LogPath`, the containerId is unable to be retrieved from the log path. 

```
2018-11-21T12:08:59.849Z        DEBUG   [kubernetes]    add_kubernetes_metadata/matchers.go:82  Incoming source value: C:\containerLogs\95357c516f55177400115df7d530626af3fb304709d52766ea4cc3989525d95f\95357c516f55177400115df7d530626af3fb304709d52766ea4cc3989525d95f-json.log
2018-11-21T12:08:59.849Z        DEBUG   [kubernetes]    add_kubernetes_metadata/matchers.go:85  Error extracting container id - source value does not contain matcher's logs_path 'C:\containerLogs/'.
```

Note the `/` at the end of the `C:\containerLogs` 
config:
```yaml
    filebeat.prospectors:
      - type: log
        paths:
          - "C:\\containerLogs\\*\\*.log"
        json.message_key: log
        json.keys_under_root: true
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
              default_matchers.enabled: false
              matchers:
              - logs_path:
                  logs_path: "C:\\containerLogs"
```

Where log path on windows host is mounted in k8s by
```yaml
  - name: dockercontainers
    hostPath:
      path: "C:/ProgramData/Docker/containers"
```

the path should probably either be used un-modified by the user, or else using platform detection the appropriate seperator should be used.

### PR DESCRIPTION
**Pull request by exekias**
This PR completes elastic/beats#9205 to support windows nodes (and log paths) when adding kubernetes metadata

Original author: @zentron
closes elastic/beats#9196

### CODE REVIEW

File: filebeat/processor/add_kubernetes_metadata/matchers.go [hunk 1]
```diff
@@ -38,6 +40,7 @@ func init() {
 }
 
 const LogPathMatcherName = "logs_path"
+const pathSeparator = string(os.PathSeparator)
```
Comment (odacremolbap) [inline filebeat/processor/add_kubernetes_metadata/matchers.go]: os.PathSeparator is already a const.
Probably there is no point redefining here, unless you think it makes things more clear. I'd assume people reading this will be glad to find old good `os.PathSeparator` vs our own const

**Comment by odacremolbap** [comment]
Not necesarily part of this review, but probably something to discuss:
**Tests** are kinda innovative, I would expect more table like and would dare to say that's the case for anyone hitting this piece of code.

https://github.com/elastic/beats/blob/5a8c137568dd1f7a0dfd90238bafa6abda526fbc/filebeat/processor/add_kubernetes_metadata/matchers_test.go#L124

**Comment by odacremolbap** [comment]
Not necesarily part of this review, but probably something to discuss:

I don't think there might be many kubelets running at locations others than default at **linux**, but could happen.
**Windows** is a different story, by default `C:` is where the OS lies, some admins choose a different location for any App that runs on it. We can't take for granted `C:`

We to add these locations to the config file, and provide current values as defaults

File: filebeat/processor/add_kubernetes_metadata/matchers.go (hunk 1 above)
Comment (exekias) [reply filebeat/processor/add_kubernetes_metadata/matchers.go]: I guess the original author wanted to avoid casting to `string` on every single use?

**Comment by exekias** [comment]
tbh, I agree this whole code needs a refactor to better handle the different use cases (docker, kubernetes, OS)..., will put some time on improve it :+1:

File: filebeat/processor/add_kubernetes_metadata/matchers.go (hunk 1 above)
Comment (odacremolbap) [reply filebeat/processor/add_kubernetes_metadata/matchers.go]: I didn't thought of that.
ok

**Comment by kaiyan-sheng** [comment]
> We to add these locations to the config file, and provide current values as defaults
I like the idea of adding default log path, pod logs path and container logs path into config. If they are missing from config, then use the default in the code 😄

**Comment by exekias** [comment]
merging this now, we can revisit this code later, I think it needs a broader refactor
