### PR TITLE
Expose region in AWS configuration so Functionbeat can deploy the Lamba in the correct place

### LINKED ISSUE #26497: Functionbeat ignores default region - only deploys to us-east-1 (AWS)
For confirmed bugs, please report:
- Version: 7.13.2
- Operating System: Darwin
- Discuss Forum URL: https://discuss.elastic.co/t/functionbeat-ignores-default-region-only-deploys-to-us-east-1-aws/276002
- Steps to Reproduce: Follow the setup instructions to deploy to any AWS region other than us-east-1

Deployment works fine with 7.12.1

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

This PR exposes the configuration option `region` for AWS. It also passes the region configuration from `AWS_REGION` environment variable if set.

## Why is it important?

Previously, since Functionbeat uses the common AWS package, it always deployed the Lamdba function to the region us-east-1. From now in it can be overwritten from both environment variable and configuration files.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

Closes #26497

### CODE REVIEW

File: x-pack/libbeat/common/aws/credentials.go [hunk 1]
```diff
@@ -94,8 +100,13 @@ func getSharedCredentialProfile(config ConfigAWS) (awssdk.Config, error) {
 		return awsConfig, errors.Wrap(err, "external.LoadDefaultAWSConfig failed with shared credential profile given")
 	}
 
-	// Set default region to make initial aws api call
-	awsConfig.Region = "us-east-1"
+	if awsConfig.Region == "" {
```
Comment (blakerouse) [inline x-pack/libbeat/common/aws/credentials.go:103]: This reads that the region in the loaded AWS configuration is taken over the region passed into the beat, is that expected behavior? I would expect that if beats configuration had an explicit region it would override the config from AWS? Unless that has an unknown side-effect?

File: x-pack/libbeat/common/aws/credentials_test.go [hunk 2]
```diff
@@ -55,6 +55,7 @@ func TestEnrichAWSConfigWithEndpoint(t *testing.T) {
 			awssdk.Config{},
 			awssdk.Config{
 				EndpointResolver: awssdk.ResolveWithEndpointURL("https://cloudwatch.us-west-1.amazonaws.com"),
+				Region:           "us-west-1",
```
Comment (michel-laterman) [inline x-pack/libbeat/common/aws/credentials_test.go:58]: Does the other testcase validate that the region defaults to `us-east-1` if it's empty?

Comment (kvch) [reply x-pack/libbeat/common/aws/credentials_test.go:58]: No, it is unrelated. Defaulting to `us-east-1` is temporary for AWS input while authenticating. The `ResolveWithEndpointURL` functions are used for finding the resources to read from.

**Review by kaiyan-sheng — COMMENTED** [review]
Hi @kvch, I wonder if we should add the `region` parameter in Functionbeat only instead of libbeat. In Metricbeat, we have a `regions` parameter so users can specify a list of regions they want to collect monitoring metrics from. With `regions` in Metricbeat and `region` in libbeat, do you think it might create confusion?

**Review by kaiyan-sheng — APPROVED** [review]
LGTM

**Comment by BaronWhite** [comment]
Could the docs be updated to include this?
If it's not set we get the error `Function: cloudwatch, could not deploy, error: bucket 'functionbeat-deploy' already exist and you don't have permission to access it: MissingRegion: could not find region configuration`, which is confusing considering the docs only mention the environment vars, which weren't working for me.

Cheers

**Comment by tehmaspc** [comment]
Please update the documentation around this required parameter. I just upgraded from FnB 7.12.1 to 7.15.2 and had to figure this out reversely instead of being able to just peruse the docs like normal.  Thanks.
