### PR TITLE
Remove sip.timestamp field

### LINKED ISSUE #22500: [Packetbeat] sip.timestamp in epoch ns fails to index in ES
While using Packetbeat's sip plugin I'm getting errors like:

`{"type":"mapper_parsing_exception","reason":"failed to parse field [sip.timestamp] of type [date_nanos] in document with id '4KpdrnUB1IqNYvPbLDQw'. Preview of field's value: '1604948142953141464'","caused_by":{"type":"illegal_argument_exception","reason":"date[+50860752-01-08T14:05:41.464Z] is after 2262-04-11T23:47:16.854775807 and cannot be stored in nanosecond resolution"}}`

The format is epoch ns from what I can tell, but ES doesn't recognize that format from what I see in [formats](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-date-format.html#strict-date-time). It looks like the ISO format is needed to use nanos.

Version: packetbeat version 8.0.0 (arm64), libbeat 8.0.0 [0a1a59f06d6d38659cf35bdd2e019de19670ec88 built 2020-11-09 13:46:45 +0000 UTC]

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

The field was only used to add the time that the packet was processed
and it had the wrong format for the mapping being used.

## Why is it important?

Fixes #22500

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Fixes #22500

### CODE REVIEW

File: packetbeat/protos/sip/plugin.go [hunk 1]
```diff
@@ -160,7 +159,6 @@ func (p *plugin) buildEvent(m *message, pkt *protos.Packet) (*beat.Event, error)
 	fields["status"] = status
 
 	var sipFields ProtocolFields
-	sipFields.Timestamp = time.Now().UnixNano()
```
Comment (andrewstucki) [inline packetbeat/protos/sip/plugin.go:163]: Just wondering--do we set `event.created`? Because this looks like it was basically trying to do that.

**Review by andrewstucki — APPROVED** [review]

File: packetbeat/protos/sip/plugin.go (hunk 1 above)
Comment (andrewkroh) [reply packetbeat/protos/sip/plugin.go:163]: I don't believe there is any event.created in Packetbeat, but it does have an `event.start` and `event.end` which should be pretty close (except maybe for PCAPs).
