### PR TITLE
Increase wait time to stabilize `TestRotateDateSuffix`

### LINKED ISSUE #25868: Flaky: TestRotateDateSuffix
The issue spotted in https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-25863/2/console

```
09:04:06  === Failed
09:04:06  === FAIL: libbeat/common/file TestRotateDateSuffix (3.00s)
09:04:06      rotator_test.go:233: 
09:04:06          	Error Trace:	rotator_test.go:289
09:04:06          	            				rotator_test.go:233
09:04:06          	Error:      	Should be true
09:04:06          	Test:       	TestRotateDateSuffix
09:04:06          	Messages:   	pattern: beatname-20210526070302.* name: beatname-20210526070303
09:04:06  
```

It looks like there are issues related to this unit test:
1. It's flaky - timestamps might differ.
2. The unit test depends on real Time implementation which elongates test execution. I believe that `time` interface should be mocked.

cc @kvch

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

This PR increases the wait time to make sure files get rotated enough times.

## Why is it important?

The test has been flaky.

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

Closes #25868

### CODE REVIEW

File: libbeat/common/file/rotator_test.go [hunk 1]
```diff
@@ -216,15 +216,15 @@ func TestRotateDateSuffix(t *testing.T) {
 	firstExpectedPattern := fmt.Sprintf("%s-%s.*", logname, time.Now().Format("20060102150405"))
 	AssertDirContentsPattern(t, dir, firstExpectedPattern)
 
-	time.Sleep(1500 * time.Millisecond)
+	time.Sleep(2 * time.Second)
```
Comment (mtojek) [inline libbeat/common/file/rotator_test.go:219]: I understand this is a quick fix, but in general this is an antipattern as it elongates the test execution. Do you think it's possible to replace it with mocked `time` instance?

Comment (kvch) [reply libbeat/common/file/rotator_test.go:219]: It is indeed not the best solution. It is possible to refactor the code, however, I do not think it worth saving a few seconds when the whole build process for touching `libbeat` takes 2-3 hours.

Comment (mtojek) [reply libbeat/common/file/rotator_test.go:219]: I understand your concerns, but it's definitely a code smell. I suggest to open a followup Beats issue to fix this test.

**Review by mtojek — APPROVED** [review]
