### PR TITLE
Avoid generating incomplete configurations in autodiscover

### LINKED ISSUE #20568: Improve logging when autodiscover configs fail
When using autodiscover with Filebeat, errors like the following occur:
```
ERROR [autodiscover] autodiscover/autodiscover.go:209 Auto discover config check failed for config '{
"docker-json": {
"cri_flags": true,
"format": "auto",
"partial": true,
"stream": "all"
},
"json": {
"add_error_key": true,
"keys_under_root": true,
"overwrite_keys": true
},
"symlinks": true,
"type": "container"
}', won't start runner: each input must have at least one path defined
```
This kind of errors can be considered as non-fatal since they came from Pod events introduced at https://github.com/elastic/beats/pull/18979/files#diff-3a3ae93d44b91ab240d462f8f7eddc2cR365.

However we should avoid logging them since it can be confusing when looking at the logs for actual errors.

Related to https://github.com/elastic/beats/issues/11834#issuecomment-672551945.

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

Handle errors when configuration unpacking fails. In principle this can
only happen when some variable is missing, because configuration has
been previously parsed as YAML. Errors on unpacking were previously
ignored.

When a variable is missing, this is clearly logged at the debug level.

This changes the behaviour, previously an incomplete configuration was
generated on this case.

## Why is it important?

To detect problems with incomplete configuration earlier and improve feedback in logs
when a variable is missing in event.

Since #18979 this error is more frequent, as a legit configuration for containers produces
errors with pod events that don't contain container fields.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ~~I have made corresponding changes to the documentation~~
- [x] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Related to #18979.
- Fixes #20568.

## Logs

For example the following configuration includes an incorrect field `container.id`.
```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${container.id}/*.log
```

Before this change, an incomplete configuration is generated, and errors like these ones are logged:
```
2020-09-01T16:52:50.094+0200	ERROR	[autodiscover]	autodiscover/autodiscover.go:209	Auto discover config check failed for config '{
  "docker-json": {
    "cri_flags": true,
    "format": "auto",
    "partial": true,
    "stream": "all"
  },
  "symlinks": true,
  "type": "container"
}', won't start runner: each input must have at least one path defined
```
After this change, the cause of the problem is more clear, and it is only logged at the debug level:
```
2020-09-02T11:57:08.225+0200	DEBUG	[autodiscover]	template/config.go:156	Configuration template cannot be resolved: field 'container.id' not available in event or environment accessing 'paths' (source:'/home/jaime/tmp/filebeat-autodiscover-docker-hints.yml')
```

### CODE REVIEW

File: libbeat/autodiscover/template/config.go [hunk 1]
```diff
@@ -123,11 +126,20 @@ func ApplyConfigTemplate(event bus.Event, configs []*common.Config, options ...u
...
 	}
+
 	opts := []ucfg.Option{
 		ucfg.PathSep("."),
 		ucfg.Env(vars),
 		ucfg.ResolveEnv,
 		ucfg.VarExp,
+
+		// Catch-all resolve function to log fields not resolved in any other way.
+		ucfg.Resolve(func(name string) (string, parse.Config, error) {
```
Comment (ChrsMark) [inline libbeat/autodiscover/template/config.go:137]: Has this option to be added at the very end of the options list? If so, maybe it can be added after line 144 where extra options (related to keystore) are added?

**Review by ChrsMark — COMMENTED** [review]
Looks good to me! Thanks for fixing this! I just left a nit question.

File: libbeat/autodiscover/template/config.go (hunk 1 above)
Comment (jsoriano) [reply libbeat/autodiscover/template/config.go:137]: I thought the same and initially implemented it this way, but then I saw that this resolver was always executed, so it seems that they are executed in inverse order to the one they are added.

This seems to confirm that: https://github.com/elastic/go-ucfg/blob/bbb885db44c36f545b8a57b6a74ff0d7b09a37c6/variables.go#L150

Though this makes me think that I should then be adding it before `ResolveEnv` too.

Comment (ChrsMark) [reply libbeat/autodiscover/template/config.go:133]: 👍  it sounds sane to me!

Comment (jsoriano) [reply libbeat/autodiscover/template/config.go:133]: Yep, it should be added before `ResolveEnv`, I have reordered options. Thanks for pointing to this!

Comment (jsoriano) [reply libbeat/autodiscover/template/config.go:133]: Oh, and by adding it the first, its error is the one returned by `Unpack`, much better, I will remove the other debug log.

**Review by ChrsMark — APPROVED** [review]
