### PR TITLE
Move Metricbeat modules.d dir to /etc/metricbeat

### LINKED ISSUE #8104: [Metricbeat] modules.d installed to wrong location
In 6.4.0 the .deb and .rpm packages install the modules.d directory to `/usr/share/metricbeat/modules.d` but they are expected to be at `/etc/metricbeat/modules.d`.

As a workaround you can copy or move the files. Or you can tell metricbeat to look in the /usr with`metricbeat.config.modules.path: '${path.home}/modules.d/*.yml'`. You can test if that works with `metricbeat modules list`.

### PR DESCRIPTION
**Pull request by andrewkroh**
This fixes the location of the Metricbeat modules.d directory as installed by .deb and .rpm packages.

Fixes #8104

### CODE REVIEW

**Comment by tsg** [comment]
jenkins, package it

File: metricbeat/magefile.go [hunk 1]
```diff
@@ -126,9 +126,8 @@ func GoTestIntegration(ctx context.Context) error {
 // not supported.
 func customizePackaging() {
 	var (
-		archiveModulesDir   = "modules.d"
-		linuxPkgModulesDir  = "/usr/share/{{.BeatName}}/modules.d"
-		darwinDMGModulesDir = "/Library/Application Support/{{.BeatVendor}}/{{.BeatName}}/modules.d"
```
Comment (ruflin) [inline metricbeat/magefile.go]: Is it in purpose that now the Mac files are placed under a different location?

Comment (andrewkroh) [reply metricbeat/magefile.go]: The new MacOS installer puts our typical `path.home` files into `/Library/Application Support` because this is conventional (it's like `/usr/share`).

The config and logs go to `/etc` and `/var `just like Linux. So the `modules.d` was wrong for MacOS too.

**Comment by tsg** [comment]
jenkins, package it

**Comment by ruflin** [comment]
Trying to trigger a packaging build here: https://beats-ci.elastic.co/job/elastic+beats+pull-request+package/47/console
