### PR TITLE
winlogbeat/sys/wineventlog: extend testing and fix bugs

### LINKED ISSUE #30621: winlogbeat: system.test_wineventlog failures for Windows-2022
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: `main`
- Operating System: `windows-2022`
- Steps to Reproduce: `mage build unitTest`

#### Test failures

- winlogbeat.tests.system.test_wineventlog.Test.test_fields_not_under_root
- winlogbeat.tests.system.test_wineventlog.Test.test_fields_under_root
- winlogbeat.tests.system.test_wineventlog.Test.test_include_xml
- winlogbeat.tests.system.test_wineventlog.Test.test_multiline_events
- winlogbeat.tests.system.test_wineventlog.Test.test_query_multi_param
- winlogbeat.tests.system.test_wineventlog.Test.test_read_one_event
- winlogbeat.tests.system.test_wineventlog.Test.test_read_unknown_event_id
- winlogbeat.tests.system.test_wineventlog.Test.test_read_unknown_sid
- winlogbeat.tests.system.test_wineventlog.Test.test_resume_reading_events
- winlogbeat.tests.system.test_wineventlog.Test.test_utf16_characters

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This fixes a couple of bug identified in #30621 and extends the test fixture to allow addition of further test cases.

This fixes [failures in event handling on Windows 2022](https://github.com/elastic/beats/issues/30621) where parts of
events available from the Windows API are [not reflected in the events recovered by winlogbeat](https://github.com/elastic/beats/pull/30622#issuecomment-1055477970).

There is unfortunately quite a lot of movement in this change due to the
need to satisfy linter requirements. Beyond those changes, the substantive
changes here are:

1. Addition of new testing infrastructure to allow addition of evtx files
   and comparison with there expected XML renderings, and adding some test
   cases.
2. Fixing a buffer length parameter in the call to _EvtFormatMessage in
   evtFormatMessage that was the result of a lack of clarity in the API
   documentation for that syscall.
3. Fixing a var shadowing decl of the publisher handle EvtHandle in
   FormatEventString.
4. Providing a call back for the legacy (non-experimental) API through
   wineventlog.Message to allow it to obtain the event message in the case
   that the RenderingInfo element is not available via the Windows API.
5. Ensure that keyword, opcode and level are obtained by the non-experimental
   API by calling winevent.EnrichRawValuesWithNames in buildRecordFromXML.
   This change also required making winevent.Event.OpcodeRaw a pointer to
   allow an absent System>Opcode element to be distinquished from the zero,
   but present element.

The change also enables testing on Windows 2022.

## Why is it important?

The bugs look to have caused CI failure when adding Windows2022 to the build matrix #30622.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #30621
- Relates #30622

### CODE REVIEW

**Comment by andrewkroh** [comment]
I pushed in a change to see how the tests react with Windows 2022.

**Comment by efd6** [comment]
```
[](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-30942/6/pipeline#step-5772-log-25)[](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-30942/6/pipeline#step-5772-log-26)[2022-03-22T21:17:16.590Z] winlogbeat/sys/wineventlog/format_message.go:26:2: import of package `github.com/pkg/errors` is blocked because the module is in the blocked modules list. `errors` and `fmt` are recommended modules. This package is deprecated, use `fmt.Errorf` with `%!w(MISSING)` instead. (gomodguard)
[2022-03-22T21:17:16.590Z] 	"github.com/pkg/errors"
[2022-03-22T21:17:16.590Z] 	^
```
🤣 

I'll fix this.

File: winlogbeat/eventlog/wineventlog.go [hunk 1]
```diff
@@ -197,9 +197,9 @@ func (l *winEventLog) openChannel(bookmark win.EvtHandle) error {
 	// https://msdn.microsoft.com/en-us/library/windows/desktop/aa385771(v=vs.85).aspx#pull
 	signalEvent, err := windows.CreateEvent(nil, 0, 0, nil)
 	if err != nil {
-		return nil
+		return err
```
Comment (efd6) [inline winlogbeat/eventlog/wineventlog.go:200]: @andrewkroh Please confirm that this is a correct change; the sys packages have no docs, so it could be that you intended this to be a silent no-op on failure, but I have guessed the contrary. Neither option fails tests.

Comment (andrewkroh) [reply winlogbeat/eventlog/wineventlog.go:200]: 👍

File: winlogbeat/eventlog/wineventlog_test.go [hunk 2]
```diff
@@ -189,6 +190,25 @@ func testWindowsEventLog(t *testing.T, api string) {
...
+	t.Run("has_message", func(t *testing.T) {
+		log := openLog(t, map[string]interface{}{"name": providerName, "batch_read_size": 1})
+		defer log.Close()
+
+		for i := 0; i < 10; i++ {
+			records, err := log.Read()
+			require.NotEmpty(t, records)
+			require.NoError(t, err)
+			if i == 0 {
+				// The first event in a collection of events created by eventcreate
```
Comment (andrewkroh) [inline winlogbeat/eventlog/wineventlog_test.go:202]: IIRC the modulo on L186 is bad. The eventcreate event ID values should range on [1-1000] instead of [0-1000]. Saw this too when I was hacking.

> Specifies the event ID for the event. A valid ID is any number from 1 to 1000.

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/eventcreate

**Comment by andrewkroh** [comment]
It looks like there is progress on the `message` front 👍 . Now the python tests are failing because other rendering info from the XML is missing such as the `winlog.keywords` and `winlog.opcode`

**Comment by efd6** [comment]
> Now the python tests are failing because other rendering info from the XML is missing such as the `winlog.keywords` and `winlog.opcode`

Yea. It's not clear to me how to get that. The change in 7c44687 does the majority of that, but the keywords are not obtainable through that path.

**Review by andrewkroh — APPROVED** [review]
The tests are passing on Windows 2022 🍾

**Comment by efd6** [comment]
Because of the amount of delint spam, I'll write a fairly detailed commit message since the actual fix was only really two minor changes.

**Comment by andrewkroh** [comment]
That would be helpful, and can you add that message somewhere in the PR description too.
