### PR TITLE
fix: don't fail merticbeat/windows/perfmon when no data is available

### LINKED ISSUE #42802: [IIS]: Agent displayed as unhealthy when no data found
Please see more info in the original issue: https://github.com/elastic/integrations/issues/12484

Opening this issue for PR linking since the cause for this is in `beats` not in `integrations`

### PR DESCRIPTION
**Pull request by stefans-elastic**
## Proposed commit message

The bug causes issue in iis/webserver module when IIS isn't installed (meaning there is no data to collect), it makes elastic-agent to go to DEGRATED state:
Screenshot 2025-02-17 at 12 56 07 PM

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

Closes #42802 

-

## Screenshots
Screenshot 2025-02-20 at 3 01 53 PM

### CODE REVIEW

File: metricbeat/module/windows/perfmon/reader.go [hunk 1]
```diff
@@ -98,8 +98,13 @@ func (re *Reader) Read() ([]mb.Event, error) {
 	if err := re.query.CollectData(); err != nil {
 		// users can encounter the case no counters are found (services/processes stopped), this should not generate an event with the error message,
 		//could be the case the specific services are started after and picked up by the next RefreshCounterPaths func
-		if err == pdh.PDH_NO_COUNTERS { //nolint:errorlint // Bad linter! This is always errno or nil.
+		if err == pdh.PDH_NO_COUNTERS { //nolint:errorlint // linter complains about comparing error using '==' operator but here error is always of type pdh.PdhErrno (or nil) so `errors.Is` is redundant here
 			re.log.Warnf("%s %v", collectFailedMsg, err)
+		} else if err == pdh.PDH_NO_DATA { //nolint:errorlint // the same thing as above ^
```
Comment (leehinman) [inline metricbeat/module/windows/perfmon/reader.go:103]: Any chance I could convince you to turn this into a switch statement?  Usually once you need an `else if` a `switch` ends up being a little cleaner.

File: metricbeat/module/windows/perfmon/reader.go [hunk 2]
```diff
@@ -98,8 +98,13 @@ func (re *Reader) Read() ([]mb.Event, error) {
...
+			re.log.Warnf("%s %v", collectFailedMsg, err)
+
+			// without the return statement here it still fails when trying to get counter values
+			return nil, nil
```
Comment (ishleenk17) [inline metricbeat/module/windows/perfmon/reader.go:107]: Like for PDH_NO_COUNTERS, we still try to get values, which would return error. 
Why are we trying getvalues here for this case ?

IMO, we are doing the right thing by returning when PDH_NO_DATA is hit and not propagating the error to getvalues. 
thoughts on this behaviour difference between the two error handling?

**Comment by ishleenk17** [comment]
@stefans-elastic : It would be good to add tests for the check

File: metricbeat/module/windows/perfmon/reader.go (hunk 2 above)
Comment (stefans-elastic) [reply metricbeat/module/windows/perfmon/reader.go:107]: > thoughts on this behaviour difference between the two error handling?

I'm not sure. It is the reason I've implemented it this way (instead of doing something like `if err == pdh.PDH_NO_COUNTERS || err == pdh.PDH_NO_DATA`) - I din't want to change original behavior since I'm not sure 'why' it was done this way. Although now that I'm thinking about this again I think it is a bug in original behavior and I probably should change to something like
```
if err == pdh.PDH_NO_COUNTERS ||  err == pdh.PDH_NO_DATA {
    re.log.Warnf("%s %v", collectFailedMsg, err)

    // without the return statement here it still fails when trying to get counter values
    return nil, nil
}
```
WDYT?

Comment (stefans-elastic) [reply metricbeat/module/windows/perfmon/reader.go:105]: I've made the change

Comment (ishleenk17) [reply metricbeat/module/windows/perfmon/reader.go:105]: Yeah, in case of pdh.PDH_NO_COUNTERS, getValues will always return nil, nil. 
Is there any scenario otherwise?
In that case returning nil early on makes sense.

**Comment by stefans-elastic** [comment]
> > Unfortunately the way it was implemented doesn't allow usage of mocks which prevents us from adding tests for this function
> 
> Rather than a full refactor, I'd suggest pulling out the contents of the error handling (the interior of `if err := re.query.CollectData(); err != nil { ... }` into a helper function (named something like `handleCollectDataError`), and use this function when CollectData returns a non-nil error. Then this function could easily be unit tested for the relevant condition, even though the calling function is more monolithic..

Oh haven't even thought about this. Great idea, I will do so.
Thank you!

File: metricbeat/module/windows/perfmon/reader.go (hunk 2 above)
Comment (stefans-elastic) [reply metricbeat/module/windows/perfmon/reader.go:105]: I might be wrong but I don't see such scenario

**Comment by stefans-elastic** [comment]
I've added tests for this PR

**Review by faec — APPROVED** [review]
Looks good, thanks for the tests!
