### PR TITLE
Alter agent install to detect installation from package

### LINKED ISSUE #25967: [Agent] Using Fleet Server with 'install' command with RPM/DEB is not supported, can we fix the install cmd to check if RPM/DEB is installed and skip to the 'enroll' step?
This is a request we could have put in a while back, it occurs to me now that it may be doable to allow DEB/RPM usage to use 'install' as well, if we fix the install command to be cognizant of if the install locations exist on disk already where the DEB/RPM package manager puts them.

This has come up a number of times and requires additional testing and additional docs and special cases, it might be nice to clean this up and make for a smoother consistent experience (and allow for less maintenance on the Docs / testing side!)

The error gotten at 'install' time (this is not the documented command to use with RPM/DEB at this time, mind you) is below, it doesn't give enough context for even experienced Admins / Elastic users to know why it failed, so we could improve the logging additionally / separately, too:

[root@ip-172-31-41-197 elastic-agent]# rpm -vi /tmp/elastic-agent-7.13.0-x86_64.rpm
Preparing packages...
elastic-agent-7.13.0-1.x86_64
[root@ip-172-31-41-197 elastic-agent]# sudo elastic-agent install -f --url=https://f9d0e1efab154f2cb28ec074d0a3bd1a.fleet.us-east-1.aws.found.io:443 --enrollment-token=M1pwUEpuUUJfRWJ3MENBX0FwNFY6OEp3STBzX2RRcTZRUVdvT19mX3c3dw==
The Elastic Agent is currently in BETA and should not be used in production
Error: failed to discover the source directory for installation: missing elastic-agent

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Alter the elastic-agent install command to not run the installation or
uninstall steps (on failure) when the agent has been installed via the
package manager of a Linux os. Instead the enroll command will be
executed.

## Why is it important?

The current documentation/Kibana gives install commands, having these fail can be frustrating.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [] ~~I have made corresponding changes to the documentation~~
- [x] I have made corresponding change to the default configuration files [PR](https://github.com/elastic/observability-docs/pull/1616)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Install the rpm/deb package and run the install command that Kibana provides:

```
vagrant@ubuntu-focal:~$ sudo dpkg -i elastic-agent-8.2.0-SNAPSHOT-amd64.deb
Selecting previously unselected package elastic-agent.
(Reading database ... 69907 files and directories currently installed.)
Preparing to unpack elastic-agent-8.2.0-SNAPSHOT-amd64.deb ...
Unpacking elastic-agent (8.2.0) ...
Setting up elastic-agent (8.2.0) ...
Processing triggers for systemd (245.4-4ubuntu3.15) ...
vagrant@ubuntu-focal:~$ sudo elastic-agent install --url=https://579a0b58293d477da089b3e048311a63.fleet.us-central1.gcp.qa.cld.elstc.co:443 --enrollment-token=NTFqWF8zNEIyWVJ5Qm1EbkY1dzg6RUZVd1lIVEVTQk9oeXVtY3FHZ2pnZw==
Installed as a system package, installation will not be altered.
{"log.level":"info","@timestamp":"2022-02-16T00:10:23.061Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":455},"message":"Starting enrollment to URL: https://579a0b58293d477da089b3e048311a63.fleet.us-central1.gcp.qa.cld.elstc.co:443/","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-02-16T00:10:24.414Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":253},"message":"Elastic Agent might not be running; unable to trigger restart","ecs.version":"1.6.0"}
Successfully enrolled the Elastic Agent.
Elastic Agent has been successfully installed.
vagrant@ubuntu-focal:~$ ls /opt/
vagrant@ubuntu-focal:~$ systemctl status elastic-agent.service
● elastic-agent.service - Agent manages other beats based on configuration provided.
     Loaded: loaded (/lib/systemd/system/elastic-agent.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: https://www.elastic.co/beats/elastic-agent
```

## Related issues

- Closes #25967

### CODE REVIEW

File: Vagrantfile [hunk 1]
```diff
@@ -53,6 +53,8 @@ TEST_BOXES = [
   {:name => "amazon2", :box => "bento/amazonlinux-2", :platform => "centos"},
 
   # Unsupported platforms
+  {:name => "opensuse153", :box => "bento/opensuse-leap-15.3", :platform => "opensuse"},
+  {:name => "sles12", :box => "elastic/sles-12-x86_64", :platform => "sles"},
```
Comment (michel-laterman) [inline Vagrantfile:57]: opensuse/sles12 added to help test suse

File: x-pack/elastic-agent/pkg/agent/cmd/install.go [hunk 2]
```diff
@@ -141,30 +145,33 @@ func installCmd(streams *cli.IOStreams, cmd *cobra.Command, args []string) error
...
-		if err != nil {
-			install.Uninstall(cfgFile)
-		}
-	}()
-
-	if !delayEnroll {
-		err = install.StartService()
+	cfgFile := paths.ConfigFile()
+	if status != install.PackageInstall {
+		err = install.Install(cfgFile) // can't run install for package installed agent, but must stop the running service and re-enroll, then start the service?
```
Comment (michel-laterman) [inline x-pack/elastic-agent/pkg/agent/cmd/install.go:151]: not sure if we need to do the commented steps, currently the enroll command will be ran with the `--from-install` flag, but I don't know if that's correct

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go [hunk 3]
```diff
@@ -7,8 +7,59 @@
...
 }
+
+func checkPackageInstall() bool {
+	if runtime.GOOS != "linux" {
+		return false
+	}
+
+	// NOTE searching for english words might not be a great idea as far as portability goes.
+	// list all installed packages then search for paths.BinaryName?
+	// dpkg is strange as the remove and purge processes leads to the package bing isted after a remove, but not after a purge
```
Comment (michel-laterman) [inline x-pack/elastic-agent/pkg/agent/install/install_unix.go:32]: would like feedback for this suggestion

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go [hunk 4]
```diff
@@ -7,8 +7,59 @@
...
+
+	// check debian based systems (or systems that use dpkg)
+	// If the package has been installed, the status starts with "install"
+	// If the package has been removed (but not pruged) status starts with "deinstall"
+	// If purged or never installed, rc is 1
+	if _, err := os.Stat("/etc/dpkg"); err == nil {
```
Comment (blakerouse) [inline x-pack/elastic-agent/pkg/agent/install/install_unix.go:38]: What do you thing about doing a `which dpkg-query` instead? Only thing would be is `which` always present on a system? I believe so.

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go (hunk 3 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:32]: This is expected because remove does not remove modified configuration files, those will remain. Only remove with purge completely removes all data on the system related to a package.

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go [hunk 5]
```diff
@@ -7,8 +7,59 @@
...
+		out, err := exec.Command("dpkg-query", "-W", "-f", "${Status}", paths.BinaryName).Output()
```
Comment (blakerouse) [inline x-pack/elastic-agent/pkg/agent/install/install_unix.go:39]: It would be better to use the package name explicitly instead of the binary name. Even if they are the same at the moment use a specific constant for that would be better, that way if it ever changes.

Could you also use `-s` which will only show the status?

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go [hunk 6]
```diff
@@ -7,8 +7,59 @@
...
+		if strings.HasPrefix(string(out), "deinstall") {
+			return false
+		}
+		return true
+	}
+
+	// check rhel and sles based systems (or systems that use rpm)
+	// if package has been installed query retuns with a list of associated files.
+	// otherwise if uninstalled, or has never been installled status ends with "not installed"
+	if _, err := os.Stat("/etc/rpm"); err == nil {
```
Comment (blakerouse) [inline x-pack/elastic-agent/pkg/agent/install/install_unix.go:52]: What about `which rpm` here as well?

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go (hunk 5 above)
Comment (michel-laterman) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:39]: The output of `-s` includes more information than what we need:
```
vagrant@ubuntu-focal:~$ dpkg-query -s elastic-agent
Package: elastic-agent
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 427208
Maintainer: <@ace0c0ea54fb>
Architecture: amd64
Version: 8.2.0
Conffiles:
 /etc/elastic-agent/.elastic-agent.active.commit 75bbbe44ef52356bb5e85a458166b1b6
 /etc/elastic-agent/elastic-agent.reference.yml 23aa69e9e641a43d7daaa0975edf0ec6
 /etc/elastic-agent/elastic-agent.yml f169e731b8e4c8a571dca0107954534d
 /etc/init.d/elastic-agent 79b301b56cc62629b9d276d6ae24ca2f
Description: Agent manages other beats based on configuration provided.
License: Elastic-License
Vendor: Elastic
Homepage: https://www.elastic.co/beats/elastic-agent
```
where the `-W -f '${Status}'` flags will give just that Status line

Comment (michel-laterman) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:39]: @blakerouse, do you know where the package name is defined?

Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:38]: I believe it is using the name of the beat for the package name, so the way you have it works. I am just suggesting we use a different constant, with the same value. Just to future proof it that maybe one day they could be different.

Its more of a nitpick and if you prefer they way you have it, that is okay as well.

File: Vagrantfile [hunk 7]
```diff
@@ -103,14 +105,14 @@ Vagrant.configure("2") do |config|
...
-      # Freebsd 
+      # Freebsd
       if node[:platform] == "freebsd"
         nodeconfig.vm.provision "shell", path: "dev-tools/vagrant_scripts/unixProvision.sh", args: "gvm amd64 freebsd #{GO_VERSION}", privileged: false
         nodeconfig.vm.provision "shell", inline: "sudo mount -t linprocfs /dev/null /proc", privileged: false
       end
 
       # gvm install
-      if node[:platform] == "centos" or node[:platform] == "ubuntu" or node[:platform] == "debian" or node[:platorm] == "archlinux"
+      if node[:platform] == "centos" or node[:platform] == "ubuntu" or node[:platform] == "debian" or node[:platform] == "archlinux" or node[:platform] == "opensuse" or node[:platform] == "sles"
```
Comment (ph) [inline Vagrantfile:115]:
```suggestion
      if [:centos, :ubuntu, :debian, :archlinux, :opensuse, :sles].include?(node[:platform].to_sym)
```

This statement is starting to be big...

File: x-pack/elastic-agent/pkg/agent/cmd/install.go (hunk 2 above)
Comment (ph) [reply x-pack/elastic-agent/pkg/agent/cmd/install.go:151]: Not sure either, what is the behavior in the OS?

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go (hunk 3 above)
Comment (ph) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:31]: Sadly yes, this is expected.

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go (hunk 5 above)
Comment (ph) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:38]: One question, here, I see we are interacting directly with the `CLI`, is there any C-Libary of even `go package` that we can use to abstract the package manager?

**Review by ph — CHANGES_REQUESTED** [review]

File: Vagrantfile (hunk 7 above)
Comment (ph) [reply Vagrantfile:115]: I hope my ruby memory is still ok.

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go (hunk 5 above)
Comment (michel-laterman) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:38]: I'm not finding a c or go library that can query dpkg/rpm for installed packages

File: x-pack/elastic-agent/pkg/agent/cmd/install.go (hunk 2 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/cmd/install.go:151]: Do not need to stop the running service, it should just enroll and then trigger a restart through the Elastic Agent control protocol. It should not need to be restarted through the service manager of the host.

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go (hunk 5 above)
Comment (michel-laterman) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:38]: After a bit of digging we can find that the package name is defined by our Mage files as the `BeatServiceName`, this defaults to the same as `BeatName` for almost all cases (exception being heartbeat).
https://github.com/elastic/beats/blob/237937085a5a7337ba06f1268cfc55cd4b869e31/dev-tools/mage/settings.go#L70-L71
The value is set to the directory name we run mage out of (i.e., x-pack/`elastic-agent`). So I don't think it's a good idea to introduce a new variable for package name within the current codebase as it won't be picked up by our tooling.

Comment (ph) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:38]: sound good

File: x-pack/elastic-agent/pkg/agent/install/install_unix.go (hunk 3 above)
Comment (michel-laterman) [reply x-pack/elastic-agent/pkg/agent/install/install_unix.go:31]: i'll keep the comments here as the extra documentation can help if anyone else needs to work on this

**Review by blakerouse — APPROVED** [review]
Looks ready to me!
