### PR TITLE
Document and improve permission checks when running socket metricset from Docker

### LINKED ISSUE #11929: [metricbeat] undocumented behavior of system/socket metricset when running in docker
For confirmed bugs, please report:
- Version: 7.0
- Operating System: linux
- Steps to Reproduce: 
1. setup docker based on the configuration here: https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html

```
docker run \
  --user=root \
  --name=metricbeat-test \
  --mount type=bind,source=/proc,target=/hostfs/proc,readonly \
  --mount type=bind,source=/sys/fs/cgroup,target=/hostfs/sys/fs/cgroup,readonly \
  --mount type=bind,source=/,target=/hostfs,readonly \
  --net=host \
  --volume="$(pwd)/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro" \
   docker.elastic.co/beats/metricbeat:7.0.0 \
  -e -system.hostfs=/hostfs
```

2. enable the system/socket metricset 

3. Get some weird errors:
```
  "system": {
    "socket": {
      "local": {
        "port": 22,
        "ip": "::"
      }
    }
  },
  "ecs": {
    "version": "1.0.0"
  },
  "server": {
    "ip": "::",
    "port": 22
  },
  "error": {
    "code": "process not found. inode=29023, tcp_state=LISTEN"
  },
```

What's happening here is that the metricset is using netlink to actually grab socket data, and then using procfs to map the inodes back to processes. Even when running as `root` the container process doesn't have permissions to access the host symlinks in `/proc/$pid/fd`, hence the error. A temporary workaround is to use `--privileged`, which is a tad blunt. You can also omit the `--user=root`, although having metricbeat just monitor its own socket usage isn't that helpful, as an info message will tell you:
```
INFO	socket/socket.go:81	socket process info will only be available for metricbeat because the process is running as a non-root user
```

It seems to be we should either alter the behavior of the metricset or document how to work around this. Having metricbeat monitor the host system from inside docker seems to be a supported use case, and I don't see anything on the above-linked page that would allow the socket metricset to just work. We may also want to document that without `--user=root` the metricset will just monitor itself, as `--user=root` is mentioned on the above-linked page, but never really explained. We may also want to do some kind of permissions check at runtime and print another info message similar to the one above.

### PR DESCRIPTION
**Pull request by jsoriano**
Update instructions for system/socket metricset on Docker. And base
permission checks on capabilities rather than on the effective uid.
Running a process as root doesn't mean that it has all privileges,
specially when run as container.

Fix elastic/beats#11929

### CODE REVIEW

File: libbeat/common/seccomp/policy_linux_amd64.go [hunk 1]
```diff
@@ -34,6 +34,7 @@ func init() {
 					"arch_prctl",
 					"bind",
 					"brk",
+					"capget",
```
Comment (jsoriano) [inline libbeat/common/seccomp/policy_linux_amd64.go]: @andrewkroh I didn't manage to update these files with `make seccomp`, it created new include files under metricbeat.
I have added this by hand here.

File: libbeat/common/capabilities_linux.go [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+}
+
+const (
+	capabilityVersion1 = 0x19980330 // Version 1, 32-bit capabilities
+	capabilityVersion3 = 0x20080522 // Version 3, 64-bit capabilities (replaced version 2)
+)
+
+// GetCapabilities gets the capabilities of this process using system calls to avoid
+// depending on procfs or library functions for permission checks
+func GetCapabilities() CapabilitiesData {
```
Comment (andrewkroh) [inline libbeat/common/capabilities_linux.go]: Would go-sysinfo work for this?

```
	p, err := sysinfo.Self()
	if err != nil {
		return err
	}

	var caps types.CapabilityInfo
	if c, ok := p.(types.Capabilities); ok {
		caps, err = c.Capabilities()
		if err != nil {
			return err
		}
	}

	// Check that caps.Effective contains {"sys_ptrace", "dac_read_search"}.
```

File: metricbeat/module/system/socket/socket.go [hunk 3]
```diff
@@ -77,9 +77,10 @@ func New(base mb.BaseMetricSet) (mb.MetricSet, error) {
 	if err != nil {
 		return nil, err
 	}
-	if os.Geteuid() != 0 {
-		logp.Info("socket process info will only be available for " +
-			"metricbeat because the process is running as a non-root user")
+	if !ptable.Privileged() {
+		logp.Info("socket process info will only be available for metricbeat process " +
```
Comment (andrewkroh) [inline metricbeat/module/system/socket/socket.go]: This code is resused by Auditbeat so hard-coding "metricbeat" isn't ideal. How about

```suggestion
		logp.Info("socket process info will only be available for the Beat process " +
```

File: metricbeat/docs/running-on-docker.asciidoc [hunk 4]
```diff
@@ -19,6 +19,7 @@ docker run \
   --mount type=bind,source=/sys/fs/cgroup,target=/hostfs/sys/fs/cgroup,readonly \ <2>
   --mount type=bind,source=/,target=/hostfs,readonly \ <3>
   --net=host \ <4>
+  --user root --privileged \ <5>
```
[the remark this answers is not in the document]
Comment (jsoriano) [reply metricbeat/docs/running-on-docker.asciidoc]: Agree, I will change it. Root user is still needed because of https://github.com/moby/moby/issues/38664
As an alternative we could set these capabilities in the extended attributes as we do in heartbeat and auditbeat, but I think that these capabilities are too powerful to be enabled by default.

File: libbeat/common/capabilities_linux.go (hunk 2 above)
Comment (jsoriano) [reply libbeat/common/capabilities_linux.go]: Yeah, I guess this could work too, I was worried of having to depend on procfs to check the effective capabilities when they are also available from a syscall, but probably we can assume that procfs is going to be there. I will give a try to this.

File: metricbeat/module/system/socket/socket.go (hunk 3 above)
Comment (jsoriano) [reply metricbeat/module/system/socket/socket.go]: Ok, I will change this.

**Comment by jsoriano** [comment]
@andrewkroh thanks for your comments! This would be ready for another look.

File: metricbeat/docs/running-on-docker.asciidoc [hunk 5]
```diff
@@ -41,6 +42,11 @@ of the container. They can be mounted at any location.
 to make this file contain the host's network devices is to use the `--net=host`
 flag. This is due to Linux namespacing; simply bind mounting the host's `/proc`
 to `/hostfs/proc` is not sufficient.
+<5> The <<metricbeat-metricset-system-socket,system socket metricset>> needs to
```
Comment (exekias) [inline metricbeat/docs/running-on-docker.asciidoc]: perhaps you can say this module is not enabled by default?, to avoid any doubt

File: metricbeat/docs/running-on-docker.asciidoc [hunk 6]
```diff
@@ -19,6 +19,7 @@ docker run \
   --mount type=bind,source=/sys/fs/cgroup,target=/hostfs/sys/fs/cgroup,readonly \ <2>
   --mount type=bind,source=/,target=/hostfs,readonly \ <3>
   --net=host \ <4>
+  --user root --cap-add sys_ptrace --cap-add dac_read_search \ <5>
```
Comment (exekias) [inline metricbeat/docs/running-on-docker.asciidoc]: This is not needed with default settings, I wonder if it adding these here will mislead users to always add this capabilities

Comment (fearful-symmetry) [reply metricbeat/docs/running-on-docker.asciidoc]: The comment _does_ mention that this is for the system/socket metricset, which is probably enough. Also, I wouldn't be surprised if other metricsets have similar permissions issues that we haven't discovered.

File: metricbeat/module/system/socket/_meta/docs.asciidoc [hunk 7]
```diff
@@ -20,8 +20,8 @@ metricbeat.modules:
 `period` value than the other metricsets.
 
 The metricset reports the process that has the socket open. In order to provide
-this information, Metricbeat must be running as root. Root access is also
-required to read the file descriptor information of other processes.
+this information for all processes in the system, Metricbeat must be run with
```
Comment (fearful-symmetry) [inline metricbeat/module/system/socket/_meta/docs.asciidoc]: We may want to specify that this is required if we're running in docker/not as root, lest users get confused and think there's something special they need to do if they're running a 'normal' install from an RPM or something.

**Comment by jsoriano** [comment]
@exekias @fearful-symmetry thanks for your reviews, I have done some changes in docs to be more explicit on when these privileges are required, let me know what you think.

**Comment by jsoriano** [comment]
jenkins, test this again please

**Comment by jsoriano** [comment]
Failures in travis don't seem related
