### PR TITLE
Fix unintended skip in metric collection on Azure Monitor

### LINKED ISSUE #37204: Azure Monitor may skip a metric collection depending on the timing
I found a regression on Azure Metrics while testing the PR https://github.com/elastic/beats/pull/37177 to backport  https://github.com/elastic/beats/pull/36823 to 8.11.

CleanShot 2023-11-26 at 09 27 09@2x

The metricset does not collect all the metric values during each iteration. 

Here's what I can see on the Compute VM dashboard:

1. Two consecutive collections, and then one skipped; then repeat.
2. As a workaround, if I set the collection period to a lower value than the smallest time grain — for example, from 300s to 60s — I get data for every metric with a time grain of PT5M or greater.

### PR DESCRIPTION
**Pull request by zmoog**
## Proposed commit message

Due to the use of `time.Now()` to set the value of the reference time used to decide if collect the value of the metric, the metricset may skip a metric collection.

Made two changes to the Azure Monitor metricset:

- moved `referenceTime` into the `Fetch()` and truncated its value to seconds to have a more predictable reference time for comparison.
- Updated the `MetricRegistry.NeedsUpdate()` method to use `referenceTime` vs. using "now" to compare with the time grain duration.

Current tests seem fine, with PT5M time grain and collection periods of 300s and 60s.

I am also adding some structured logging messages to track registry decisions at the debug log level.

Here's how to parse the structured logs to get a nice table view:

```shell
$ cat metricbeat.log.json | grep "MetricRegistry" | jq -r  '[.key, .needs_update, .reference_time, .now, .time_grain_start_time//"n/a", .last_collection_at//"n/a"] | @tsv'
fdd3a07a3cabd90233c083950a4bc30c        true    2023-11-26T15:51:30.000Z        2023-11-26T15:51:30.967Z        2023-11-26T15:46:30.000Z        2023-11-26T15:46:30.000Z
6ee8809577a906538473e3e5e98dc893        true    2023-11-26T15:51:30.000Z        2023-11-26T15:51:35.257Z        2023-11-26T15:46:30.000Z        2023-11-26T15:46:30.000Z
6aedb7dffafbfe9ca19e0aa01436d30a        false   2023-11-26T15:51:30.000Z        2023-11-26T15:51:35.757Z        2023-11-26T15:46:30.000Z        2023-11-26T15:48:30.000Z
```

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #37204 

## Screenshots

Here's the compute vm dashboard running a custom agent build from this PR:

CleanShot 2023-11-26 at 17 43 11@2x

### CODE REVIEW

File: x-pack/metricbeat/module/azure/azure.go [hunk 1]
```diff
@@ -87,6 +88,18 @@ func NewMetricSet(base mb.BaseMetricSet) (*MetricSet, error) {
...
 func (m *MetricSet) Fetch(report mb.ReporterV2) error {
+	// Set the reference time for the current fetch.
+	//
+	// The reference time is used to calculate time intervals
+	// and compare with collection info in the metric
+	// registry to decide whether to collect metrics or not,
+	// depending on metric time grain (check `MetricRegistry`
+	// for more information).
+	//
+	// We truncate the reference time to the second to avoid
```
Comment (tommyers-elastic) [inline x-pack/metricbeat/module/azure/azure.go:99]: nit: i think it's worth being specific about what the millisecond issue is. e.g. 

```
We truncate the reference time to the second to avoid millisecond
variations in the collection period causing skipped collections. 
```

**Review by lucian-ioan — APPROVED** [review]
Changes LGTM.

File: x-pack/metricbeat/module/azure/client.go [hunk 2]
```diff
@@ -176,11 +224,11 @@ func (client *Client) InitResources(fn mapResourceMetrics) error {
 }
 
 // GetMetricValues returns the metric values for the given cloud resources.
-func (client *Client) GetMetricValues(metrics []Metric, reporter mb.ReporterV2) []Metric {
+func (client *Client) GetMetricValues(referenceTime time.Time, metrics []Metric, reporter mb.ReporterV2) []Metric {
 	var result []Metric
 
 	// Same end time for all metrics in the same batch.
-	referenceTime := time.Now().UTC()
+	//referenceTime := time.Now().UTC()
```
Comment (ritalwar) [inline x-pack/metricbeat/module/azure/client.go:231]: Let's eliminate the commented-out code?

File: x-pack/metricbeat/module/azure/client.go [hunk 3]
```diff
@@ -38,26 +40,70 @@ func (m *MetricRegistry) Update(metric Metric, info MetricCollectionInfo) {
...
+	if collection, exists := m.collectionsInfo[metricKey]; exists {
+		// Turn the time grain into a duration (for example, PT5M -> 5 minutes).
+		timeGrainDuration := convertTimeGrainToDuration(collection.timeGrain)
+
+		// Calculate the start time of the time grain in relation to
+		// the reference time.
+		timeGrainStartTime := referenceTime.Add(-timeGrainDuration)
+
+		// If the last collection time is after the start time of the time grain,
+		// it means that we already have a value for the give time grain.
```
Comment (ritalwar) [inline x-pack/metricbeat/module/azure/client.go:65]:
```suggestion
		// it means that we already have a value for the given time grain.
```

**Review by ritalwar — APPROVED** [review]

File: x-pack/metricbeat/module/azure/azure.go (hunk 1 above)
Comment (zmoog) [reply x-pack/metricbeat/module/azure/azure.go:99]: Sweet, adding it!
