### PR TITLE
[metricbeat][system/process, system/process_summary]: mark module as healthy if metrics are partially filled

### LINKED ISSUE #40542: [Elastic Agent] The system process metricsets should not report as degraded when metrics are partially collected
In https://github.com/elastic/beats/pull/40400 we added the ability for metricsets to report their status using the Elastic Agent control protocol to make errors more visible. One consequence of this has been surfacing previously hidden problems collecting information about PIDs. 

It appears that by default we fail to get complete metrics for some PIDs on both Windows and Linux, resulting in the Elastic Agent being permanently unhealthy in the Fleet UI where no quick fix:
- [ ] https://github.com/elastic/elastic-agent/issues/5300
- [x] https://github.com/elastic/beats/issues/40537

While this functionality is useful and has helped us find bugs, we do not want users to immediately experience unhealthy agents they can't obviously fix. As a stop gap while we fix the underlying problems, let's keep reporting the error message but have the system process metricsets report as healthy. This will put the errors messages in the UI without making the agent unhealthy, which most users treat as something to quickly fix.

For example we see something like the following in our leak detection tests regularly:

```yaml
    - id: system/metrics-default
      state:
        message: 'Healthy: communicating with pid ''1556'''
        pid: 0
        state: 2
        units:
            input-system/metrics-default-system/metrics-system-5f5e65eb-2fd6-41e1-8c29-f24d57e66509:
                state: DEGRADED
                message: |-
                    Error fetching data for metricset system.process_summary: Not enough privileges to fetch information: Not enough privileges to fetch information: GetInfoForPid: could not get all information for PID 0: error fetching name: OpenProcess failed for pid=0: The parameter is incorrect.
                    error fetching status: OpenProcess failed for pid=0: The parameter is incorrect.
                    GetInfoForPid: could not get all information for PID 4: error fetching name: GetProcessImageFileName failed for pid=4: GetProcessImageFileName failed: invalid argument
                payload:
                    streams:
                        system/metrics-system.process.summary-5f5e65eb-2fd6-41e1-8c29-f24d57e66509:
                            error: |-
                                Error fetching data for metricset system.process_summary: Not enough privileges to fetch information: Not enough privileges to fetch information: GetInfoForPid: could not get all information for PID 0: error fetching name: OpenProcess failed for pid=0: The parameter is incorrect.
                                error fetching status: OpenProcess failed for pid=0: The parameter is incorrect.
                                GetInfoForPid: could not get all information for PID 4: error fetching name: GetProcessImageFileName failed for pid=4: GetProcessImageFileName failed: invalid argument
                            status: DEGRADED
```

The proposal is that we keep the error messages, but report the state as healthy.

```yaml
    - id: system/metrics-default
      state:
        message: 'Healthy: communicating with pid ''1556'''
        pid: 0
        state: 2
        units:
            input-system/metrics-default-system/metrics-system-5f5e65eb-2fd6-41e1-8c29-f24d57e66509:
                state: HEALTHY
                message: |-
                    Error fetching data for metricset system.process_summary: Not enough privileges to fetch information: Not enough privileges to fetch information: GetInfoForPid: could not get all information for PID 0: error fetching name: OpenProcess failed for pid=0: The parameter is incorrect.
                    error fetching status: OpenProcess failed for pid=0: The parameter is incorrect.
                    GetInfoForPid: could not get all information for PID 4: error fetching name: GetProcessImageFileName failed for pid=4: GetProcessImageFileName failed: invalid argument
                payload:
                    streams:
                        system/metrics-system.process.summary-5f5e65eb-2fd6-41e1-8c29-f24d57e66509:
                            error: |-
                                Error fetching data for metricset system.process_summary: Not enough privileges to fetch information: Not enough privileges to fetch information: GetInfoForPid: could not get all information for PID 0: error fetching name: OpenProcess failed for pid=0: The parameter is incorrect.
                                error fetching status: OpenProcess failed for pid=0: The parameter is incorrect.
                                GetInfoForPid: could not get all information for PID 4: error fetching name: GetProcessImageFileName failed for pid=4: GetProcessImageFileName failed: invalid argument
                            status: HEALTHY
```

This will keep the information accessible for bug reports but should hopefully reduce the perceived urgency of the problem and the level of support cases. The control protocol always allows both a state and a message regardless of what the state is, see [here](https://github.com/elastic/elastic-agent-client/blob/f66604cbb9146380e8194fda745c4e80440acc85/elastic-agent-client.proto#L326-L330).

There will be a follow up issue to make switching between these two.

### PR DESCRIPTION
**Pull request by VihasMakwana**
- Bug

## Proposed commit message

- If metrics are partially available for system.process and system.process_summary, do not mark metricset as degraded.
- Instead, keep it healthy and display the message

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

- Clone from this branch
- Do `mage package` from `x-pack/agentbeat`
- Run elastic agent with new `agentbeat` binary
- Run as unprivileged mode, and run `elastic-agent status --output=json`
- You should see `HEALTHY` state and error message displayed

## Related issues

- Closes #40542

## Screenshots

Screenshot 2024-08-22 at 12 38 05 PM
Screenshot 2024-08-22 at 12 38 13 PM

### CODE REVIEW

**Review by leehinman — APPROVED** [review]

**Comment by leehinman** [comment]
Needs a changelog entry

File: metricbeat/mb/event.go [hunk 1]
```diff
@@ -214,3 +214,18 @@ func tryToMapStr(v interface{}) (mapstr.M, bool) {
 		return nil, false
 	}
 }
+
+// Following error indicates that the metrics are partially filled.
```
Comment (mauri870) [inline metricbeat/mb/event.go:218]:
```suggestion
// PartialMetricsError indicates that metrics are only partially filled.
```

**Review by mauri870 — APPROVED** [review]

**Review by faec — APPROVED** [review]
