### PR TITLE
Fix issue where default go logger is not discarded when either * or stdout is selected.

### LINKED ISSUE #10251: Logger from the standard library is not correctly disabled.
I've seen a report where a keep alive TCP connection received some garbage from the remote end, since we didn't have anything configured to handle that request the http client did just log the error directly using the default logger. Since beats was running as a service the log went to stdout/stderr and was dump to the `/var/log/message`, This is indeed an unexpected behavior.

The following code is not exactly what it need to be. We have to setup `ioutil.Discard` when the catch all selector `*` is not set or `stdlog` is not set. When either of the selector is defined we need to use our logger output.

https://github.com/elastic/beats/blob/4cb9bd7e75b3eb1ce8f3e8ea3a115dc34674fa16/libbeat/logp/core.go#L101-L105

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fix issue where default go logger is not discarded when either * or stdout is selected. 

## Why is it important?

Prevents other imported modules from outputting log messages.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [X] I have added tests that prove my fix is effective or that my feature works

## Related issues

- Closes #10251

### CODE REVIEW

**Comment by urso** [comment]
@ph @andrewkroh Can you have a look, please?

File: libbeat/logp/core.go [hunk 1]
```diff
@@ -98,10 +99,14 @@ func Configure(cfg Config) error {
 			selectors["*"] = struct{}{}
 		}
 
-		if _, enabled := selectors["stdlog"]; !enabled {
+		_, stdlogEnabled := selectors["stdlog"]
+		_, allEnabled := selectors["*"]
+		if !stdlogEnabled || !allEnabled {
 			// Disable standard logging by default (this is sometimes used by
 			// libraries and we don't want their spam).
 			golog.SetOutput(ioutil.Discard)
```
Comment (andrewkroh) [inline libbeat/logp/core.go]: IIUC the goal is to by default set the output of the `log` package to `ioutil.Discard`. So this call should happen always. In it's current location it only happens if we are running with `logging.level: debug and len(logging.selectors) > 0`. I think it needs be moved outside the `if` block.

Then the case were we do want to allow the `log` pkg to output can happen here.

File: libbeat/logp/core_test.go [hunk 2]
```diff
@@ -116,3 +118,14 @@ func TestL(t *testing.T) {
...
+
+func TestAllStdoutDisablesDefaultGoLogger(t *testing.T) {
+	DevelopmentSetup(WithSelectors("*"))
+	assert.Equal(t, ioutil.Discard, golog.Writer())
+
+	DevelopmentSetup(WithSelectors("stdlog"))
+	assert.Equal(t, ioutil.Discard, golog.Writer())
+
+	DevelopmentSetup(WithSelectors("*", "stdlog"))
+	assert.NotEqual(t, ioutil.Discard, golog.Writer())
```
Comment (andrewkroh) [inline libbeat/logp/core_test.go]: I'd like to see a test case with a different log level and a test case with no selectors.

File: libbeat/logp/core.go (hunk 1 above)
Comment (ph) [reply libbeat/logp/core.go]: I think its more like this:

```golang

// If we are in debug mode and we have the all selectors actived we also redirect the golog output.
_, allEnabled := selectors["*"]
if cfg.Level.Enabled(DebugLevel) && allEnabled { // "*"
    golog.SetOutput(_defaultGoLog)
} else {
    golog.SetOutput(ioutil.Discard) 
}

```
The other case is when we are in debug mode + stdlog selector activated.
``` golang
/// specific _stdlog_ selector when debug is on.
, stdlogEnabled := selectors["stdlog"]
if !stdlogEnabled {
golog.SetOutput(_defaultGoLog)
}
```

Comment (ph) [reply libbeat/logp/core.go]: Added the CLI flag to the above command to hopefull better understand how a human would use this.

File: libbeat/logp/core_test.go (hunk 2 above)
Comment (ph) [reply libbeat/logp/core_test.go]: based on the above log level suggestion and selectors https://github.com/elastic/beats/pull/15708/files#r370756892

**Comment by ph** [comment]
I need to check my zube rules for this, i've missed you initial ping @blakerouse

**Comment by blakerouse** [comment]
@andrewkroh @ph Adjusted the code based on the review, if you could give this another look.
