### PR TITLE
Refactor docker watcher to fix flaky test and other small issues

### LINKED ISSUE #7906: [Libbeat] Flaky TestWatcherDie test
Link: https://beats-ci.elastic.co/job/elastic+beats+master+multijob-windows/beat=libbeat,label=windows/1331/console
Platform: Windows

Error
```
>> go test: Unit Testing
11:34:30 FAILURES:
11:34:30 Error: go test failed: 1 test failures
11:34:30 Package: github.com/elastic/beats/libbeat/common/docker
11:34:30 Test:    TestWatcherDie
11:34:30 assertions.go:247: 
11:34:30                           
11:34:30 	Error Trace:	watcher_test.go:385
11:34:30 	
11:34:30 	Error:      	Not equal: 
11:34:30 	
11:34:30 	            	expected: 1
11:34:30 	
11:34:30 	            	actual  : 0
11:34:31 	
11:34:31 	Test:       	TestWatcherDie
11:34:31 assertions.go:247: 
11:34:31                           
11:34:31 	Error Trace:	watcher_test.go:385
11:34:31 	
11:34:31 	Error:      	Not equal: 
11:34:31 	
11:34:31 	            	expected: 1
11:34:31 	
11:34:31 	            	actual  : 0
11:34:31 	
11:34:31 	Test:       	TestWatcherDie
11:34:31 assertions.go:247: 
11:34:31                           
11:34:31 	Error Trace:	watcher_test.go:385
11:34:31 	
11:34:31 	Error:      	Not equal: 
11:34:31 	
11:34:31 	            	expected: 1
11:34:31 	
11:34:31 	            	actual  : 0
11:34:31 	
11:34:31 	Test:       	TestWatcherDie
11:34:31 assertions.go:247: 
11:34:31                           
11:34:31 	Error Trace:	watcher_test.go:385
11:34:31 	
11:34:31 	Error:      	Not equal: 
11:34:31 	
11:34:31 	            	expected: 1
11:34:31 	
11:34:31 	            	actual  : 0
11:34:31 	
11:34:31 	Test:       	TestWatcherDie
11:34:31 ----
11:34:31 SUMMARY:
11:34:31   Fail:     1
11:34:31   Skip:     6
11:34:31   Pass:     788
11:34:31   Packages: 70
11:34:31   Duration: 33.5826022s
```

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

Refactor docker watcher to fix some small issues and improve testability:
* Actually release resources of previous connections when reconnecting.
* Watcher uses a clock that can be mocked in tests for time-sensitive functionality.
* Use nanoseconds-precision from events timestamps, this is important to avoid duplicated events on reconnection.
* Fix logger initialization (it was being initialized as `docker.docker`).
* Refactor test helpers to have more control on test watcher when needed.
* Some other code refactors.

## Why is it important?

* Fixes flaky test #7906.
* Watch loop relied on deferred calls to do cleanups, but the watch loop never finished, so resources associated to each reconnection were never released. On reconnections caused by not receiving events, previous connections were not being closed, so several connections were kept alive, but all except the last one were ignored.
* Fix duplication of events on reconnections. Each reconnection asks for events since last received events, using seconds granularity made each reconnection to retrieve again the events happened during the second the last event was received, including the event itself. API supports nanosecond granularity, that avoids this problem.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ~~I have made corresponding changes to the documentation~~
- [x] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Fixes #7906.
```
$ go test -count 10000 ./libbeat/common/docker/
ok  	github.com/elastic/beats/v7/libbeat/common/docker	5.220s
```

### CODE REVIEW

File: libbeat/common/docker/watcher.go [hunk 1]
```diff
@@ -236,108 +232,124 @@ func (w *watcher) Start() error {
...
+				return false
 			case <-tickChan.C:
-				if time.Since(w.lastWatchReceivedEventTime) > dockerEventsWatchPityTimerTimeout {
-					log.Infof("No events received within %s, restarting watch call", dockerEventsWatchPityTimerTimeout)
-					time.Sleep(1 * time.Second)
-					break WATCH
+				if time.Since(lastReceivedEventTime) > dockerEventsWatchPityTimerTimeout {
+					w.log.Infof("No events received within %s, restarting watch call", dockerEventsWatchPityTimerTimeout)
+					return false
 				}
```
Comment (jsoriano) [inline libbeat/common/docker/watcher.go:295]: Not sure if this reconnection is needed, leaving it just in case, I guess this is to handle connections being stalled for some reason.

Comment (ChrsMark) [reply libbeat/common/docker/watcher.go:295]: 👍

File: libbeat/common/docker/watcher_test.go [hunk 2]
```diff
@@ -472,16 +486,37 @@ func runWatcherShortID(t *testing.T, kill bool, containers [][]types.Container,
...
-	}
+	return watcher, client.done
+}
 
-	<-client.done
-	if kill {
-		watcher.Stop()
-		watcher.stopped.Wait()
-	}
+func runAndWait(w *watcher, done chan interface{}) *watcher {
```
Comment (ChrsMark) [inline libbeat/common/docker/watcher_test.go:492]: Just wondering, do we actually pass this channel in any of the calls?

**Review by ChrsMark — COMMENTED** [review]
Looks really good. Just left some comments/questions.

File: libbeat/common/docker/watcher.go [hunk 3]
```diff
@@ -447,3 +462,11 @@ func (w *watcher) ListenStart() bus.Listener {
 func (w *watcher) ListenStop() bus.Listener {
 	return w.bus.Subscribe("stop")
 }
+
+type clock interface {
```
[the remark this answers is not in the document]
Comment (jsoriano) [reply libbeat/common/docker/watcher.go]: Moved to where it is used :+1:

File: libbeat/common/docker/watcher_test.go (hunk 2 above)
Comment (jsoriano) [reply libbeat/common/docker/watcher_test.go:492]: `runAndWait` is used with the returned values of `testWatcher`/`testWatcherShortID`, they return a watcher and a done channel, exactly the parameters `runAndWait` expect.
A `nil` channel would block.

Comment (ChrsMark) [reply libbeat/common/docker/watcher_test.go:492]: 👍 thanks for clarifying

File: libbeat/common/docker/watcher.go [hunk 4]
```diff
@@ -447,3 +467,7 @@ func (w *watcher) ListenStart() bus.Listener {
 func (w *watcher) ListenStop() bus.Listener {
 	return w.bus.Subscribe("stop")
 }
+
+type systemClock struct{}
```
Comment (ChrsMark) [inline libbeat/common/docker/watcher.go:471]: Ah, I had in mind about moving this interface implementation too to the top 😬 .

File: libbeat/common/docker/watcher.go [hunk 5]
```diff
@@ -447,3 +467,7 @@ func (w *watcher) ListenStart() bus.Listener {
...
+
+func (*systemClock) Now() time.Time { return time.Now() }
```
Comment (ChrsMark) [inline libbeat/common/docker/watcher.go:473]: this one too :)

**Review by ChrsMark — APPROVED** [review]
lgtm

just one non-blocking suggestion

File: libbeat/common/docker/watcher.go (hunk 4 above)
Comment (jsoriano) [reply libbeat/common/docker/watcher.go]: Ok, moved :slightly_smiling_face:

**Review by ChrsMark — APPROVED** [review]
