### PR TITLE
Fix double fetch

### LINKED ISSUE #35646: [Heartbeat] The `/tmp` folder doesn’t seem to be getting cleaned up
We are observing that the `/tmp` folder within the running container of an Elastic Agent being used for a Private Location, is continually growing and may eventually cause the host to fill up.

This has been observed with both 8.7.0 and 8.8.0, where `/tmp`is growing ~40MB per day (on an example Private Location running 5 browser monitors, 3 of which run every 5 minutes, 2 of which run every 3 minutes).

Looking at `/tmp` on the running container, there are many `elastic-synthetics-unzip-nnnn` subfolders, for example:

```
drwxrwx--- 5 elastic-agent elastic-agent  4096 Jun  1 13:22 elastic-synthetics-unzip-2857552961
drwxrwx--- 5 elastic-agent elastic-agent  4096 Jun  1 14:22 elastic-synthetics-unzip-2865044517
drwxrwx--- 5 elastic-agent elastic-agent  4096 Jun  1 12:37 elastic-synthetics-unzip-2881487560
drwxrwx--- 5 elastic-agent elastic-agent  4096 Jun  1 14:27 elastic-synthetics-unzip-2914827838
drwxrwx--- 5 elastic-agent elastic-agent  4096 Jun  1 13:17 elastic-synthetics-unzip-2929753614
drwxrwx--- 5 elastic-agent elastic-agent  4096 Jun  1 14:07 elastic-synthetics-unzip-2955987070
drwxrwx--- 5 elastic-agent elastic-agent  4096 Jun  1 13:47 elastic-synthetics-unzip-3022192703
```

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes #35646 by only unpacking project monitors once.

This fixes the ever growing temp folder issue and is more efficient to boot. Previously we would call `fetch` on a monitor source every time it was run, but only cleanup the fetched resource once, when the monitor was unloaded. We now fetch once and cleanup once.

This project also fixes the very confusing issue of two files `browser/project.go` and `browser/source/project.go`, we have renamed `browser/project.go` to `browser/sourcejob.go` which makes reasoning about this change simpler.

## Manual testing

Test with a config like [this one](https://gist.githubusercontent.com/andrewvc/b55c420f688b465352b0abebdfa64e8e/raw/abaf3d0a35b2a92006ce1bbb222d66463c9c4df3/project.yml) by placing it in your `monitors.d` folder in `x-pack/heartbeat`.

Then, in your `heartbeat.yml` enable config reloading. Finally, test by running:

```
mage build && ELASTIC_SYNTHETICS_CAPABLE=true ./heartbeat -e 2>&1 -E cloud.id=$CLOUD_ID -E cloud.auth=$CLOUD_AUTH -E output.elasticsearch.allow_older_versions=true -E logging.level=debug | jq .message | grep "browser project"
```

You should see logs like the following:

```
"browser project: unpack source: /var/folders/pl/wjbh5yrd2dz19mlwpckxrvdm0000gn/T/elastic-synthetics-unzip-1594999618"
"browser project: re-use already unpacked source: /var/folders/pl/wjbh5yrd2dz19mlwpckxrvdm0000gn/T/elastic-synthetics-unzip-1594999618"
"browser project: re-use already unpacked source: /var/folders/pl/wjbh5yrd2dz19mlwpckxrvdm0000gn/T/elastic-synthetics-unzip-1594999618"
// Change made to config file here forcing reload
"browser project: close project source: /var/folders/pl/wjbh5yrd2dz19mlwpckxrvdm0000gn/T/elastic-synthetics-unzip-1594999618"
"browser project: unpack source: /var/folders/pl/wjbh5yrd2dz19mlwpckxrvdm0000gn/T/elastic-synthetics-unzip-2539246959"
"browser project: re-use already unpacked source: /var/folders/pl/wjbh5yrd2dz19mlwpckxrvdm0000gn/T/elastic-synthetics-unzip-2539246959"
```
You should then be able to editor your config in `monitors.d`, perhaps changing the schedule field, etc, forcing it to reload, and see the temp directories used by heartbeat changing, but that only one at a time exists, with the old ones being cleaned up.

### CODE REVIEW

File: x-pack/heartbeat/monitors/browser/source/project.go [hunk 1]
```diff
@@ -39,6 +42,16 @@ func (p *ProjectSource) Validate() error {
...
 func (p *ProjectSource) Fetch() error {
+	// We only need to unzip the source exactly once
+	p.mtx.Lock()
+	defer p.mtx.Unlock()
+	if p.fetched {
+		logp.L().Debugf("browser project: re-use already unpacked source: %s", p.Workdir())
+		return nil
+	}
+
+	p.fetched = true
```
Comment (emilioalvap) [inline x-pack/heartbeat/monitors/browser/source/project.go:53]: @andrewvc, can we defer this assignment until the source is successfully extracted? If it fails for a transient error, as it is it will never retry

**Comment by emilioalvap** [comment]
@andrewvc I hope you don't mind, I pushed some fixes to unit tests since I was testing locally

File: x-pack/heartbeat/monitors/browser/source/project.go (hunk 1 above)
Comment (andrewvc) [reply x-pack/heartbeat/monitors/browser/source/project.go:53]: I've done so, but it's unlikely to be transient as we're just unpacking a file, though I suppose a full disk could be freed (unlikely on a container however).

**Review by emilioalvap — APPROVED** [review]
LGTM
