### PR TITLE
[Elastic Agent] Fix issues with enrollment key fetching

### LINKED ISSUE #24310: [7.13.0-SNAPSHOT] Elastic-Agent: unable to find enrollment token named "Default" in policy "Default policy"
Today we spotted an issue while running Elastic Agent:

```
Attaching to elastic-package-stack_elastic-agent_1
[36melastic-agent_1              |[0m Performing setup of Fleet in Kibana
[36melastic-agent_1              |[0m Error: unable to find enrollment token named "Default" in policy "Default policy"
```

Link: https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-269/3/artifact/build/elastic-stack-dump/stack/logs/elastic-agent.log

The issue will fail all master builds for elastic/integrations and elastic/elastic-package.

Steps to reproduce:

```
elastic-package stack update -v
elastic-package stack up -v -d
```

For reference:
https://github.com/elastic/elastic-package/pull/269

EDIT:

Keep in mind that we had to push a workaround for the agent's image. You can find Docker Compose definitions here: https://github.com/elastic/elastic-package/blob/c8b00a93596e157c7eafb8b0163440cf88ced59f/internal/install/static_snapshot_yml.go

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes an issue with the new `container` sub-command. It was not handling the naming of the enrollment tokens correctly and when not running without Fleet Server the `api_key` is not returned in the listing, requiring a detailed fetch to retrieve it.

## Why is it important?

So usage of the Elastic Agent container on 7.13 works.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #24310

### CODE REVIEW

File: x-pack/elastic-agent/pkg/agent/cmd/container.go [hunk 1]
```diff
@@ -35,6 +36,10 @@ const (
 	maxRequestRetries = 30              // maximum number of retries for HTTP requests
 )
 
+var (
+	tokenNameStrip = regexp.MustCompile(`\s\([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\)$`)
```
Comment (michalpristas) [inline x-pack/elastic-agent/pkg/agent/cmd/container.go:40]: can you add a comment here why and what this is?

File: x-pack/elastic-agent/pkg/agent/cmd/container.go [hunk 2]
```diff
@@ -317,7 +327,7 @@ func findPolicy(policies []kibanaPolicy) (*kibanaPolicy, error) {
 func findKey(keys []kibanaAPIKey, policy *kibanaPolicy) (*kibanaAPIKey, error) {
 	tokenName := envWithDefault(defaultTokenName, "FLEET_TOKEN_NAME")
 	for _, key := range keys {
-		name := strings.TrimSpace(strings.Replace(key.Name, fmt.Sprintf(" (%s)", key.ID), "", 1))
+		name := tokenNameStrip.ReplaceAllString(key.Name, "")
```
Comment (michalpristas) [inline x-pack/elastic-agent/pkg/agent/cmd/container.go:330]: can it be that there will be trailing/leading space after replace as these were removed before

**Review by michalpristas — APPROVED** [review]
LGTM

File: x-pack/elastic-agent/pkg/agent/cmd/container.go (hunk 1 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/cmd/container.go:42]: added

File: x-pack/elastic-agent/pkg/agent/cmd/container.go (hunk 2 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/cmd/container.go]: nice catch, I added the `strings.TrimSpace` back in

**Comment by mtojek** [comment]
Please remember about backporting this issue, so we can pull it to the 7.13.0-SNAPSHOT.

**Comment by ruflin** [comment]
If there are multiple keys with the same name, which one will it take?
