### PR TITLE
[Heartbeat] Handle TLS certs missing notBefore/notAfter

### LINKED ISSUE #9556: stacktrace in heartbeat
```
- Version:  6.5.1
- Operating System: linux centos 7 
```
For our http module configuration 

```
- type: http
  name: foo/bar
  # List or urls to query
  urls: [
    "http://localhost/analytics",
    "https://localhost/analytics"
  ]
  # Configure task schedule
  schedule: "@every 30s"
  username: yyy
  password: zzz
  ssl:
    verification_mode: none
```

We see this stack trace

```
2018-12-14T14:54:24.421Z	ERROR	scheduler/scheduler.go:355	Panic in job foo/bar@https://localhost/analytics'. Recovering, but please report this: runtime error: invalid memory address or nil pointer dereference.
2018-12-14T14:54:24.422Z	ERROR	scheduler/scheduler.go:357	Stacktrace: goroutine 17450 [running]:
runtime/debug.Stack(0x16ad273, 0x3a, 0xc42058c8b8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/elastic/beats/heartbeat/scheduler.(*Scheduler).runTask.func1.1(0xc4201aa6e0, 0xc4203a6080)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/scheduler.go:357 +0xf7
panic(0x14f98a0, 0x1f689f0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/elastic/beats/heartbeat/monitors/active/dialchain.TLSLayer.func1.1(0x1757340, 0xc4201de700, 0x3, 0xc4201733c0, 0xd, 0x1757340)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/dialchain/tls.go:83 +0x45b
github.com/elastic/beats/heartbeat/monitors/active/dialchain.afterDial.func1(0x1670dc2, 0x3, 0xc4201733c0, 0xd, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/dialchain/util.go:89 +0xba
github.com/elastic/beats/libbeat/outputs/transport.DialerFunc.Dial(0xc42000d320, 0x1670dc2, 0x3, 0xc4201733c0, 0xd, 0x9bfe99, 0xc4206a5630, 0x50, 0x48)
	/go/src/github.com/elastic/beats/libbeat/outputs/transport/transport.go:40 +0x4e
github.com/elastic/beats/heartbeat/monitors/active/http.(*SimpleTransport).RoundTrip(0xc420693650, 0xc42019ee00, 0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/simple_transp.go:84 +0xfe
net/http.send(0xc42019ed00, 0x173b820, 0xc420693650, 0xbefd0eec14077578, 0xba8640061a, 0x1fc6900, 0xc4200bc2b0, 0xbefd0eec14077578, 0xc4205a9068, 0x1)
	/usr/local/go/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0xc420693680, 0xc42019ed00, 0xbefd0eec14077578, 0xba8640061a, 0x1fc6900, 0xc4200bc2b0, 0x0, 0x1, 0x3)
	/usr/local/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0xc420693680, 0xc42019ed00, 0x1fc6900, 0xc42019ed00, 0xb1597b)
	/usr/local/go/src/net/http/client.go:615 +0x28d
github.com/elastic/beats/heartbeat/monitors/active/http.execRequest(0xc420693680, 0xc42019ed00, 0x16bffd0, 0xbefd0ee814077485, 0xb6cc93652a, 0x1fc6900, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:252 +0xa6
github.com/elastic/beats/heartbeat/monitors/active/http.execPing(0xc420693680, 0xc4201bca00, 0x0, 0x0, 0x0, 0x3b9aca000, 0x16bffd0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:226 +0x13c
github.com/elastic/beats/heartbeat/monitors/active/http.createPingFactory.func1(0xc420693500, 0x9bf995, 0x7f8cec1221c8, 0x81)
	/go/src/github.com/elastic/beats/heartbeat/monitors/active/http/task.go:171 +0x442
github.com/elastic/beats/heartbeat/monitors.MakePingIPFactory.func1.1(0x6, 0xc4205a9778, 0x9bfe99)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:194 +0x31
github.com/elastic/beats/heartbeat/monitors.MakeSimpleCont.func1(0x10, 0x1534380, 0xc4205a97a8, 0x9bfe99, 0xc42000d060, 0x20)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:184 +0x26
github.com/elastic/beats/heartbeat/monitors.funcTask.Run(0xc4200705e0, 0x18, 0x20, 0x20, 0xc42000d060, 0x0, 0xc42008cc00)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:440 +0x27
github.com/elastic/beats/heartbeat/monitors.WithFields.func1(0xc4205a9701, 0xc42000d060, 0xc4205a97f8, 0xd62c21, 0x1566780, 0xc42000d060)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:398 +0x4a
github.com/elastic/beats/heartbeat/monitors.funcTask.Run(0xc42000d060, 0x173dee0, 0xc4200705e0, 0x173dee0, 0xc42000d060, 0x1fc6900, 0x14a912)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:440 +0x27
github.com/elastic/beats/heartbeat/monitors.makeByHostAnyIPJob.func1(0x0, 0x0, 0xc4203389b0, 0x9e43ab, 0x0, 0xc4203389c0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:323 +0x939
github.com/elastic/beats/heartbeat/monitors.annotated.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42040e7c0, 0xa, 0xffffffffffffffff, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:140 +0xc7
github.com/elastic/beats/heartbeat/monitors.MakeJob.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420346000, 0xc420296f98, 0x0, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:127 +0xe8
github.com/elastic/beats/heartbeat/monitors.(*funcJob).Run(0xc4201cf3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42015e388, 0xc42015e438, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/util.go:438 +0x82
github.com/elastic/beats/heartbeat/monitors.(Job).Run-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420381701, 0xc4201b6020, 0xa27918, ...)
	/go/src/github.com/elastic/beats/heartbeat/monitors/task.go:120 +0x86
github.com/elastic/beats/heartbeat/monitors.(*task).prepareSchedulerJob.func1(0x10, 0x16c0020, 0xc4201aa6e0)
	/go/src/github.com/elastic/beats/heartbeat/monitors/task.go:85 +0x7d
github.com/elastic/beats/heartbeat/scheduler.(*Scheduler).runTask.func1(0xc4201aa6e0, 0xc4203a6080, 0xc4201aa6e0, 0xc4201cfc40)
	/go/src/github.com/elastic/beats/heartbeat/scheduler/scheduler.go:362 +0x5b
created by github.com/elastic/beats/heartbeat/scheduler.(*Scheduler).runTask
	/go/src/github.com/elastic/beats/heartbeat/scheduler/scheduler.go:352 +0x5c



```

### PR DESCRIPTION
**Pull request by andrewvc**
Some certs in the wild don't set these standard fields and can cause an NPE. I left a long comment in the code, this is sort of a bizarre situation.

Fixes #9556

### CODE REVIEW

File: heartbeat/monitors/active/dialchain/tls.go [hunk 1]
```diff
@@ -60,30 +61,53 @@ func TLSLayer(cfg *transport.TLSConfig, to time.Duration) Layer {
...
-			event.Put("tls.certificate_not_valid_after", *chainNotValidAfter)
+			addCertMetdata(event, tlsConn.ConnectionState().VerifiedChains)
 
 			return conn, nil
 		}), nil
 	}
 }
+
+func addCertMetdata(event common.MapStr, chains [][]*x509.Certificate) {
+	// The behavior here might seem strange. We *always* set a notBefore, but only optionally set a notAfter.
```
Comment (ruflin) [inline heartbeat/monitors/active/dialchain/tls.go]: Thanks for all the details here in case someone wants to change this in the future.

**Comment by andrewvc** [comment]
@ruflin thanks for the review. Changelog pushed. Am I good to merge?

File: CHANGELOG.asciidoc [hunk 2]
```diff
@@ -68,6 +68,8 @@ https://github.com/elastic/beats/compare/v7.0.0-alpha1...master[Check the HEAD d
 
 *Heartbeat*
 
+- Fixed rare issue where TLS connections to endpoints with x509 certificates missing either notBefore or notAfter would cause the check to fail with a stacktrace.
```
Comment (ruflin) [inline CHANGELOG.asciidoc]:
```suggestion
 - Fixed rare issue where TLS connections to endpoints with x509 certificates missing either notBefore or notAfter would cause the check to fail with a stacktrace. {issue}9556[9556] {pull}9566[9566]
```

**Comment by andrewvc** [comment]
jenkins, retest this please
