### PR TITLE
[Flaky Test] oteltest.CheckReceivers increase timeout

### LINKED ISSUE #43832: [Flaky Test] x-pack/filebeat/fbreceiver TestMultipleReceivers and TestFilebeatOTelMultipleReceiversE2E
## Flaky Test

* **Test Name:** x-pack/filebeat/fbreceiver TestMultipleReceivers
* **Link:** [Failure](https://github.com/elastic/beats/blob/019fe1d13bb8edc552ddea00420a16376c5f4a13/x-pack/filebeat/fbreceiver/receiver_test.go#L206-L208)
* **Branch:** Git branch the test was seen in. If a PR, the branch the PR was based off.
* **Artifact Link:** [Failure in CI](https://buildkite.com/elastic/beats-xpack-filebeat/builds/13552/steps?jid=01961fb7-b7a6-4f7b-8a92-41beb8d87d55), [retry also failed](https://buildkite.com/elastic/beats-xpack-filebeat/builds/13552/steps?jid=01961fce-be3e-4d62-b23d-4484e078e4dd)
* **Notes:** Additional details about the test. e.g. theory as to failure cause

### Stack Trace

```
2025-04-10 15:06:03 CEST	=== Failed
2025-04-10 15:06:03 CEST	=== FAIL: x-pack/filebeat/fbreceiver TestMultipleReceivers (66.13s)
2025-04-10 15:06:03 CEST	SDK 2025/04/10 13:02:50 WARN falling back to IMDSv1: operation error ec2imds: getToken, http response error StatusCode: 405, request to EC2 IMDS failed
2025-04-10 15:06:03 CEST	SDK 2025/04/10 13:02:53 WARN falling back to IMDSv1: operation error ec2imds: getToken, http response error StatusCode: 405, request to EC2 IMDS failed
2025-04-10 15:06:03 CEST	    oteltest.go:124:
2025-04-10 15:06:03 CEST	        	Error Trace:	C:/buildkite-agent/builds/bk-agent-prod-gcp-1744289200299222169/elastic/beats-xpack-filebeat/x-pack/filebeat/fbreceiver/receiver_test.go:206
2025-04-10 15:06:03 CEST	        	            				C:/buildkite-agent/builds/bk-agent-prod-gcp-1744289200299222169/elastic/beats-xpack-filebeat/libbeat/otelbeat/oteltest/oteltest.go:136
2025-04-10 15:06:03 CEST	        	            				C:/Users/Buildkite/.go/go-1.24.1/src/runtime/asm_amd64.s:1700
2025-04-10 15:06:03 CEST	        	Error:      	Condition failed!
2025-04-10 15:06:03 CEST	        	Messages:   	expected receivers to have logs, got logs: map[r2:[{"@timestamp":"2025-04-10T13:02:56.719Z","agent":{"ephemeral_id":"14428d21-ab6a-47f8-872c-cfe0f50bd2c6","id":"51d909ae-29f1-42d9-9996-dbec579795a1","name":"bk-agent-prod-gcp-1744289200299222169","type":"filebeat","version":"9.1.0"},"cloud":{"account":{"id":"elastic-ci-prod"},"availability_zone":"us-central1-b","instance":{"id":"1565360607196742494","name":"bk-agent-prod-gcp-1744289200299222169"},"machine":{"type":"n1-standard-4"},"project":{"id":"elastic-ci-prod"},"provider":"gcp","region":"us-central1","service":{"name":"GCE"}},"ecs":{"version":"8.0.0"},"filename":0,"host":"xxxxx","input":{"type":"benchmark"},"line":0,"message":"test","thread":0}]]
2025-04-10 15:06:03 CEST	    oteltest.go:124:
2025-04-10 15:06:03 CEST	        	Error Trace:	C:/buildkite-agent/builds/bk-agent-prod-gcp-1744289200299222169/elastic/beats-xpack-filebeat/libbeat/otelbeat/oteltest/oteltest.go:124
2025-04-10 15:06:03 CEST	        	            				C:/buildkite-agent/builds/bk-agent-prod-gcp-1744289200299222169/elastic/beats-xpack-filebeat/x-pack/filebeat/fbreceiver/receiver_test.go:191
2025-04-10 15:06:03 CEST	        	Error:      	Condition never satisfied
2025-04-10 15:06:03 CEST	        	Test:       	TestMultipleReceivers
2025-04-10 15:06:03 CEST	        	Messages:   	timeout waiting for assertion to pass
```

### PR DESCRIPTION
**Pull request by AndersonQ**
## Proposed commit message

```
oteltest.CheckReceivers increase timeout

There are test failing, the issue seems to be a too short timeout, so this change relaxes it.
```
## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Disruptive User Impact

- N/A

## How to test this PR locally

run the test until you're satisfied

```
go test -count 1000 -timeout=0 -run TestMultipleReceivers ./x-pack/filebeat/fbreceiver
```

## Related issues

- Relates #43832

### CODE REVIEW

File: x-pack/filebeat/fbreceiver/receiver_test.go [hunk 1]
```diff
@@ -203,9 +203,8 @@ func TestMultipleReceivers(t *testing.T) {
 			},
 		},
 		AssertFunc: func(t *assert.CollectT, logs map[string][]mapstr.M, zapLogs *observer.ObservedLogs) {
-			require.Conditionf(t, func() bool {
-				return len(logs["r1"]) > 0 && len(logs["r2"]) > 0
-			}, "expected receivers to have logs, got logs: %v", logs)
+			assert.Greater(t, len(logs["r1"]), 0, "receive r1 does not have ny logs")
+			assert.Greater(t, len(logs["r2"]), 0, "receive r2 does not have ny logs")
```
Comment (leehinman) [inline x-pack/filebeat/fbreceiver/receiver_test.go:207]:
```suggestion
			assert.Greater(t, len(logs["r1"]), 0, "receive r1 does not have any logs")
			assert.Greater(t, len(logs["r2"]), 0, "receive r2 does not have any logs")
```

**Review by leehinman — APPROVED** [review]
typo suggestion, but otherwise LGTM

**Comment by AndersonQ** [comment]
I'll merge it anyway, the new logs are useful. However there is still the possibility to see it failing according to my tests, see below.

The fact it's always `r1` the one without logs leads me to believe there might be something else going on there, not just a too short timeout. Also I run this on my mac, which is only for test and had nothing running at the time, so plenty of processing power available.

```
❯ go test -count 1000 -timeout=0 -run TestMultipleReceivers ./x-pack/filebeat/fbreceiver
--- FAIL: TestMultipleReceivers (126.23s)
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:206
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:136
                                                        /Users/ainsoph/devel/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/asm_arm64.s:1223
                Error:          "[]" should have 1 item(s), but has 0
                Messages:       receive r1 does not have ny logs
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:124
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:191
                Error:          Condition never satisfied
                Test:           TestMultipleReceivers
                Messages:       timeout waiting for logger fields from the OTel collector are present in the logs and other assertions to be met
--- FAIL: TestMultipleReceivers (126.22s)
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:206
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:136
                                                        /Users/ainsoph/devel/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/asm_arm64.s:1223
                Error:          "[]" should have 1 item(s), but has 0
                Messages:       receive r1 does not have ny logs
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:124
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:191
                Error:          Condition never satisfied
                Test:           TestMultipleReceivers
                Messages:       timeout waiting for logger fields from the OTel collector are present in the logs and other assertions to be met
--- FAIL: TestMultipleReceivers (126.21s)
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:206
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:136
                                                        /Users/ainsoph/devel/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/asm_arm64.s:1223
                Error:          "[]" should have 1 item(s), but has 0
                Messages:       receive r1 does not have ny logs
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:124
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:191
                Error:          Condition never satisfied
                Test:           TestMultipleReceivers
                Messages:       timeout waiting for logger fields from the OTel collector are present in the logs and other assertions to be met
--- FAIL: TestMultipleReceivers (126.22s)
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:206
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:136
                                                        /Users/ainsoph/devel/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/asm_arm64.s:1223
                Error:          "[]" should have 1 item(s), but has 0
                Messages:       receive r1 does not have ny logs
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:124
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:191
                Error:          Condition never satisfied
                Test:           TestMultipleReceivers
                Messages:       timeout waiting for logger fields from the OTel collector are present in the logs and other assertions to be met
--- FAIL: TestMultipleReceivers (126.21s)
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:206
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:136
                                                        /Users/ainsoph/devel/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/asm_arm64.s:1223
                Error:          "[]" should have 1 item(s), but has 0
                Messages:       receive r1 does not have ny logs
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:124
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:191
                Error:          Condition never satisfied
                Test:           TestMultipleReceivers
                Messages:       timeout waiting for logger fields from the OTel collector are present in the logs and other assertions to be met
--- FAIL: TestMultipleReceivers (126.16s)
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:206
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:136
                                                        /Users/ainsoph/devel/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.darwin-arm64/src/runtime/asm_arm64.s:1223
                Error:          "[]" should have 1 item(s), but has 0
                Messages:       receive r1 does not have ny logs
    oteltest.go:124:
                Error Trace:    /Users/ainsoph/devel/github.com/elastic/beats-tmp/libbeat/otelbeat/oteltest/oteltest.go:124
                                                        /Users/ainsoph/devel/github.com/elastic/beats-tmp/x-pack/filebeat/fbreceiver/receiver_test.go:191
                Error:          Condition never satisfied
                Test:           TestMultipleReceivers
                Messages:       timeout waiting for logger fields from the OTel collector are present in the logs and other assertions to be met
FAIL
FAIL    github.com/elastic/beats/v7/x-pack/filebeat/fbreceiver  16980.396s
FAIL

```
