### PR TITLE
x-pack/auditbeat/module/socket/guess: fix creds trigger for newer kernels

### LINKED ISSUE #36905: [Auditbeat] error: system/socket dataset setup failed: unable to guess one or more required parameters: guess_struct_creds failed: timeout while waiting for event
Version: Auditbeat 8.4.3 - Auditbeat 8.10.4
Operating System: 
CentOS Linux release 8.8 (Green Obsidian)
Kernel 6.3.6-1.el8.x86_64

Beats fails to start with error:
`Exiting: 1 error: system/socket dataset setup failed: unable to guess one or more required parameters: guess_struct_creds failed: timeout while waiting for event`

I think the `struct_creds` definition changed / was removed around the 6.1.

Using the kernel version 6.1.38-1.el8.x86_64 works alright.

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

In kernel commit [981ee95c](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?h=981ee95cc1f5905ae4936b0dd501085909cdc14f) (into v6.3) calls to access_override_creds
were gated behind a test for the requirement for the call. This change
results in non-execution of prepare_creds and so failure of the guess.

An alternative has been identified that does not exhibit this behaviour,
mq_open which calls dentry_open with creds in the third parameter. So
replace the sys_access trigger with sys_mq_open and add the probe to
dentry_open with P3 for the address.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Fixes #36905

### CODE REVIEW

File: x-pack/auditbeat/module/system/socket/guess/creds.go [hunk 1]
```diff
@@ -138,13 +149,26 @@ func (g *guessStructCreds) Extract(ev interface{}) (mapstr.M, bool) {
...
-//	int access(const char *pathname, int mode);
+// Trigger invokes the SYS_MQ_OPEN syscall:
 //
-// The function call will return an error due to path being NULL, but it will
-// have invoked prepare_creds before argument validation.
+//	int mq_open(const char *name, int oflag, mode_t mode, struct mq_attr *attr);
 func (g *guessStructCreds) Trigger() error {
-	syscall.Syscall(unix.SYS_ACCESS, 0, 0, 0)
-	return nil
+	name, err := unix.BytePtrFromString("omg")
```
Comment (haesbaert) [inline x-pack/auditbeat/module/system/socket/guess/creds.go:156]: I'd use a more unique string here __guess_creds or something.

File: x-pack/auditbeat/seccomp_linux.go [hunk 2]
```diff
@@ -16,12 +16,22 @@ func init() {
 		// The system/package dataset uses librpm which has additional syscall
 		// requirements beyond the default policy from libbeat so whitelist
 		// these additional syscalls.
-		if err := seccomp.ModifyDefaultPolicy(seccomp.AddSyscall, "umask", "mremap"); err != nil {
+		if err := seccomp.ModifyDefaultPolicy(seccomp.AddSyscall,
+			"mremap",
+			"umask",
+		); err != nil {
```
Comment (haesbaert) [inline x-pack/auditbeat/seccomp_linux.go:22]: solely whitespace changes would be nicer in a second commit.

Comment (efd6) [reply x-pack/auditbeat/seccomp_linux.go:22]: Agreed, but unfortunately this will all get squashed.

**Review by haesbaert — APPROVED** [review]
lgtm!

**Review by kgeller — APPROVED** [review]

**Comment by andrewkroh** [comment]
@Mergifyio backport 7.17
