### PR TITLE
fix(otelconsumer): add back-off to retries

### LINKED ISSUE #50217: otelconsumer tight-loops retries on 401 with zero backoff (9.3.2)
# otelconsumer tight-loops retries on 401 with zero backoff (9.3.2)

When ES returns 401, `otelconsumer` republishes the failed batch immediately with no backoff. The loop sustains **~660 retries/sec per component**, saturates CPU (350–425 %), and rotates 10 MB of error logs every ~9 s. Reproduced on two independent 9.3.2 installs on the same network after the ES backend came up with a stale API key post-reboot.

Code path: `x-pack/libbeat/outputs/otelconsumer/otelconsumer.go:202` — `(*otelConsumer).logsPublish`.

## Expected

`otelconsumer` should back off on repeated failures regardless of what the downstream exporter decides. Today it implicitly relies on `elasticsearchexporter` for backoff, but when the exporter short-circuits on a non-retryable status (e.g. 401 isn't in `retry_on_status`) there's nothing throttling the pipeline-level `batch.Retry()`, so it spins.

## Related (not duplicates, same class)

- [#13505](https://github.com/elastic/elastic-agent/issues/13505) — "zero-backoff retry storms" (open, P1). This bug is the 401 instance of that class.
- [elastic/beats#48803](https://github.com/elastic/beats/issues/48803) / [#48807](https://github.com/elastic/beats/pull/48807) — queue-full log flood at 300–500/s; log-suppression fix only.
- [elastic/beats#45652](https://github.com/elastic/beats/issues/45652) / [#45637](https://github.com/elastic/beats/pull/45637) — otelconsumer retry semantics fixed pre-9.3.
- [elastic/beats#47892](https://github.com/elastic/beats/issues/47892) — beats-receiver retry rework in progress.
- [#12522](https://github.com/elastic/elastic-agent/issues/12522) — ES exporter retry metrics gap.

<details>
<summary>Measurements</summary>

Over one rotated log file (`elastic-agent-20260419-242.ndjson`, 10 MB):

- Entries: 5716
- Span: 8.63 s
- Rate: **662 retries/sec**
- Inter-event gap distribution: `<1ms: 619`, `1–10ms: 5012`, `10–100ms: 84`, `100ms–1s: 0`, `>=1s: 0`

Over ~10 minutes: 50+ rotated 10 MB files (`-194` → `-244+`). Host load avg ~40 on 32 cores. Second agent in an LXC on the same host did the same thing independently.

</details>

<details>
<summary>Representative log line (sanitized)</summary>

```json
{
  "log.level": "error",
  "@timestamp": "2026-04-19T13:07:15.369Z",
  "message": "failed to publish batch events to otel collector pipeline: flush failed (401): {\"error\":{...\"reason\":\"unable to authenticate with provided credentials...\",\"additional_unsuccessful_credentials\":\"API key: apikey authentication for id <REDACTED> encountered a failure\"...},\"status\":401}",
  "otelcol.component.id": "filebeatreceiver/_agent-component/filestream-monitoring",
  "log.logger": "otelconsumer",
  "log.origin": {"file.line": 202, "file.name": "otelconsumer/otelconsumer.go", "function": "github.com/elastic/beats/v7/x-pack/libbeat/outputs/otelconsumer.(*otelConsumer).logsPublish"}
}
```

Five consecutive entries: `13:07:15.369` → `.370` → `.375` → `.378` → `.390` (gaps 1, 5, 3, 12 ms).

</details>

<details>
<summary>Exporter config (from <code>edot/otel-merged-actual.yaml</code>)</summary>

```yaml
retry:
  enabled: true
  initial_interval: 1s
  max_interval: 1m
  max_retries: 3
  retry_on_status: [429, 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511]
sending_queue:
  block_on_overflow: true
  wait_for_result: true
```

401 is (correctly) not listed. The exporter returns the error up; `otelconsumer` then calls `batch.Retry()` without any rate limiting of its own.

</details>

<details>
<summary>Environment & diagnostics</summary>

- Elastic Agent: `9.3.2`, build `491f2c68f087ccd2f55c97531745f4f4b9f6d921`
- Component: `elastic-otel-collector`, filebeatreceiver → elasticsearchexporter
- Affected: `filestream-monitoring` (agent self-monitoring)
- OS: Debian-family Proxmox host and an LXC container — same result
- Trigger: ES rejected the monitoring API key (cluster came back post-reboot with the key no longer valid)

I have a full `elastic-agent diagnostics` bundle (3.8 MB) including goroutine / heap / allocs / block / mutex profiles for the supervisor and EDOT, `components-{expected,actual}.yaml`, full state, and a complete 10 MB rotated log file showing the 662/s rate. Happy to share privately — it still has internal IPs / agent UUIDs / one API key ID I'd rather not publish.

</details>

## Workaround

Fix the credentials, or stop the filebeatreceiver component. No runtime flag in 9.3.2 makes `otelconsumer` back off on its own.

### PR DESCRIPTION
**Pull request by andrzej-stencel**
## Proposed commit message

Adds exponential backoff with random jitter to retries in otelconsumer. This prevents flooding Elasticsearch (or other endpoint) with retries as described in https://github.com/elastic/beats/issues/50217.
 
The backoff settings are at this stage not user configurable and hardcoded to 1s initial backoff and 60s max backoff.

There are a couple considerations that should be weighed long term after the immediate fix implemented in this change.

1. **Should otelconsumer retry at all?** In OTel Collector pipelines it is usually the exporter that takes care of queueing, batching and retrying failed requests. Note that currently the Elasticsearch does not support infinite retries ([1](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45618#issuecomment-3834973853), [2](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45747#issuecomment-3877336544)), so the retries in otelconsumer serve as a workaround for this missing feature of the exporter. Long term, it should be considered what benefits, if any, retrying in otelconsumer serves and whether it should be kept or removed in favor of OTelCol exporter retries.
2. With this change, **backoff increases only every (NumCPU) retries.** For example, on my MacBook M2 with 12-core CPU, otelconsumer retries 12 times with ~1s backoff, then 12 times with ~2s backoff, 12 times with ~4s backoff, etc. This is because `MakeOtelConsumer` returns an output group consisting of (NumCPU) otelconsumer instances, and each otelconsumer instance creates its own backoff instance, but all the workers share single retry queue. We could change the implementation for all otelconsumers to share a single backoff instance, but this would require synchronization, increasing complexity. I decided to leave this out until we decide if we want to keep (NumCPU) workers.
3. Related to the above, I want to understand **why there are (NumCPU) otelconsumer workers created** and what advantages and/or drawbacks of this approach.

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works. Where relevant, I have used the [`stresstest.sh`](https://github.com/elastic/beats/blob/main/script/stresstest.sh) script to run them under stress conditions and race detector to verify their stability.
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent-changelog-tool/blob/main/docs/usage.md).~~

## Disruptive User Impact

Introducing exponential backoff to retries should only be beneficial to users. The initial backoff is a reasonable 1s, the same as the [default backoff settings in Elatsicsearch output](https://www.elastic.co/docs/reference/beats/filebeat/elasticsearch-output#backoff-init-option).

## How to test this PR locally

- Build Elastic Agent with this Beats change.
- Run Agent with the below `config.yaml`.

The retries should happen with backoff instead of hundreds retries per second like before.

I used the following Python command to start an HTTP server responding with a selected HTTP status:

```python
python3 -c "
from http.server import HTTPServer, BaseHTTPRequestHandler
class H(BaseHTTPRequestHandler):
    def do_POST(self):
        data = self.rfile.read(int(self.headers['Content-Length']))
        print(f'{self.path} ({len(data)} bytes)')
        self.send_response(504)
        self.end_headers()
HTTPServer(('', 1234), H).serve_forever()
"
```

Note that the OTLP/HTTP exporter only treats the following error codes as retryable: 429, 502, 503, 504 ([spec](https://opentelemetry.io/docs/specs/otlp/#retryable-response-codes)). All other error codes are sent back by OTLP/HTTP exporter as permanent up the pipeline, causing otelconsumer to not retry them.

config.yaml:

```yaml
service:
  pipelines:
    logs:
      receivers:
        - filebeatreceiver
      exporters:
        - otlp_http
receivers:
  filebeatreceiver:
    filebeat:
      inputs:
        - type: filestream
          id: logs1
          paths:
            - /tmp/log1k.log
    path.data: /tmp/0424/data
    path.logs: /tmp/0424/logs
    queue.mem:
      flush.timeout: 0
exporters:
  otlp_http:
    endpoint: http://localhost:1234
    retry_on_failure:
      enabled: false
    sending_queue:
      enabled: false
```

### CODE REVIEW

**Comment by mauri870** [comment]
Regarding the decision to go with multiple parallel otelconsumer outputs, it was a stopgap to implement behavior similar to the [beats presets](https://www.elastic.co/docs/reference/beats/filebeat/elasticsearch-output#_preset), more details [here](https://github.com/elastic/ingest-dev/issues/5212). @VihasMakwana might have more insights on this.

**Comment by cmacknz** [comment]
The unit of concurrency for a Beat input is the publish client that writes to the Beat queue. This is independent of the number of workers in the Beat output. 

Since a beat receiver is an entire Beat pipeline from input publish client -> queue -> output by using only a single otelconsumer worker we remove the link between input concurrency and output concurrency that we would want. Using NumCPUs gave us good enough results as stop gap.

What we would ideally want is to have each publish Client be a collector pipeline client, then the input concurrency would match. However the collector pipeline also wants you to write batches and not individual events for best performance, and the beat queue does not require this. So there is still a mismatch. It is also the case that the libbeat pipeline implements the acknowledgement logic that lets inputs write to their state store like the Filebeat registry so removing it requires replacing that mechanism as well.

This is tied into the work in https://github.com/elastic/elastic-agent/issues/12753 which will get us down to a single Beat queue for all Beat receivers, this is also tied into the idea of removing otelconsumer entirely which Fae outlines is more challenging than we'd like in https://github.com/elastic/beats/issues/44105#issuecomment-3474947187.

So there is work ongoing to make this a bit better but we still need a bridge between the Beat pipeline concept and the collector pipeline client concept as they don't have exactly the same semantics for the short-medium term. If we can come up with a way to get rid of the Beat pipeline in receivers entirely that would be amazing but that's easier said than done.

File: libbeat/otel/otelconsumer/otelconsumer_test.go [hunk 1]
```diff
@@ -266,6 +266,72 @@ func TestPublish(t *testing.T) {
 		assert.Equal(t, outest.BatchRetry, batch.Signals[0].Tag)
 	})
 
+	t.Run("backoff resets on success", func(t *testing.T) {
```
Comment (AndersonQ) [inline libbeat/otel/otelconsumer/otelconsumer_test.go:297]: It isn't asserting the backoff reset, it's just asserting it retries. What was the real intention of the test? Test the retry or the backoff reset?

File: libbeat/otel/otelconsumer/otelconsumer.go [hunk 2]
```diff
@@ -204,19 +234,18 @@ func (out *otelConsumer) logsPublish(ctx context.Context, batch publisher.Batch)
 			batch.Drop()
 		} else {
 			st.RetryableErrors(len(events))
+			if !out.retryBackoff.Wait() {
```
Comment (AndersonQ) [inline libbeat/otel/otelconsumer/otelconsumer.go:237]: Unless I'm missing something, it'll block the Publish, then it'll add the batch to the queue to be retried, is it?

File: libbeat/otel/otelconsumer/otelconsumer.go [hunk 3]
```diff
@@ -191,9 +211,19 @@ func (out *otelConsumer) logsPublish(ctx context.Context, batch publisher.Batch)
 		}
 	}
 
+	out.backoffInit.Do(func() {
+		out.retryBackoff = backoff.NewEqualJitterBackoff(ctx.Done(), out.retry.init, out.retry.max)
+	})
```
Comment (AndersonQ) [inline libbeat/otel/otelconsumer/otelconsumer.go:216]: Why isn't it on the constrictor? It's a hot path, is it the right place for that?

Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer.go:216]: In the constructor we don't have access to the context yet to capture its Done channel.

File: libbeat/otel/otelconsumer/otelconsumer.go (hunk 2 above)
Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer.go:237]: Yes, this is the idea.

File: libbeat/otel/otelconsumer/otelconsumer_test.go (hunk 1 above)
Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer_test.go:297]: Yeah sorry these tests were generated by Claude, let me take a closer look.

File: libbeat/otel/otelconsumer/otelconsumer.go (hunk 2 above)
Comment (cmacknz) [reply libbeat/otel/otelconsumer/otelconsumer.go:237]: This is the output side of the Beat, so inputs can still write data as long as 1 there is space in the Beat queue and 2 all the otelconsumer workers aren't blocked.

Is there a way to know which specific event in the batch caused the problem? Or does it all fail together?

File: libbeat/otel/otelconsumer/otelconsumer.go (hunk 3 above)
Comment (mauri870) [reply libbeat/otel/otelconsumer/otelconsumer.go]: Don't see why it can't be in the constructor, looks like the proper place for this.

File: libbeat/otel/otelconsumer/otelconsumer_test.go (hunk 1 above)
Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer_test.go:297]: Hey @AndersonQ I've reworked the tests in https://github.com/elastic/beats/pull/50294/commits/073bbbddf28db44006cead572dc2cc4aa6770a72, please take a look.

File: libbeat/otel/otelconsumer/otelconsumer_test.go [hunk 4]
```diff
@@ -266,6 +266,102 @@ func TestPublish(t *testing.T) {
...
+		// not the grown level which would be [4*init, 8*init) = [200ms, 400ms).
+		batch4 := outest.NewBatch(event1)
+		start := time.Now()
+		err = otelConsumer.Publish(ctx, batch4)
+		duration := time.Since(start)
+		require.NoError(t, err)
+		assert.Equal(t, outest.BatchRetry, batch4.Signals[0].Tag, "fourth batch should be retried")
+		// In equal jitter backoff strategy, initial backoff is between initBackoff and 2*initBackoff.
+		assert.Less(t, duration, 2*initBackoff, "after success, backoff should reset to init level, not continue growing (got %v)", duration)
+	})
```
[the remark this answers is not in the document]
Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer_test.go:341]: Added margin in https://github.com/elastic/beats/pull/50294/commits/b3277050fdfe485b0dd63b546d3ec1cfb2ffd96e.

File: libbeat/otel/otelconsumer/otelconsumer.go [hunk 5]
```diff
@@ -191,9 +211,19 @@ func (out *otelConsumer) logsPublish(ctx context.Context, batch publisher.Batch)
 		}
 	}
 
+	out.backoffInit.Do(func() {
+		out.retryBackoff = backoff.NewEqualJitterBackoff(ctx.Done(), out.retry.init, out.retry.max)
```
Comment (AndersonQ) [inline libbeat/otel/otelconsumer/otelconsumer.go:215]: [Blocker]

Unless I'm missing something, I believe there is a problem here:

This is configuring the backoff with the 1st context ever passed to a Publish call. I don't think it's the best design. It's using the wrong context, how could we guaratee every call to Publish is done with the same context? if at any point another context is used and the 1st in cancelled, the backoff will not work anymore.

Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer.go:215]: I know this looks suspicious, I had the same thought. But I believe this is the right context, it does not change for the lifetime of otelconsumer. See here: https://github.com/elastic/beats/blob/c37cfcf3301467e52ec0278ad6fb5eb4f93a191b/libbeat/publisher/pipeline/client_worker.go#L101.

Comment (AndersonQ) [reply libbeat/otel/otelconsumer/otelconsumer.go:215]: Yes, it seems to work, but it makes an really unclear and error prone API, a context passed to a call to publish should not interfere with any subsequent calls.

At the very least it needs to be documented on Publish. but Ideally, it should not be like that. Probably  [`MakeOtelConsumer`](https://github.com/elastic/beats/blob/bbc0482d99b056865215c04f492df8fc5af9196d/libbeat/publisher/pipeline/output_otel.go#L77) and [`makeClientWorker`](https://github.com/elastic/beats/blob/bbc0482d99b056865215c04f492df8fc5af9196d/libbeat/publisher/pipeline/output_otel.go#L89) should receive the same parent context and use them.

That's been said, as it works for now, I think we can go forward to get it in for the next release. But it'd be good to have an issue to fix it. Do you agree @andrzej-stencel

**Review by AndersonQ — APPROVED** [review]
As we'd like to get it in so it makes to the next release, I think it's ok as it is. 

I could not test it with the agent because there is a breaking change on the beats and the agent needs to be fixed.

Also, I think it's better to improve how the backoff gets its context, using the 1st ever passed to a call to `Publish` makes a API that can cause problems in the future.

File: libbeat/otel/otelconsumer/otelconsumer.go (hunk 2 above)
Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer.go:237]: > Is there a way to know which specific event in the batch caused the problem? Or does it all fail together?

The Elasticsearch exporter [returns the original error](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.151.0/exporter/elasticsearchexporter/bulkindexer.go#L478) from [docappender.(*BulkIndexer).Flush](https://github.com/elastic/go-docappender/blob/v2.14.1/bulk_indexer.go#L486) method, which includes the response string, so I think it's technically possible to read the details of the response.

Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer.go:237]: The OTel Collector has a (half-baked) concept of PartialSuccess response that's based on the [OTLP Partial Success spec](https://opentelemetry.io/docs/specs/otlp/#partial-success). It is only implemented in OTLP exporters ([otlp_grpc](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.151.0/exporter/otlpexporter/otlp.go#L144), [otlp_http](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.151.0/exporter/otlphttpexporter/otlp.go#L424), [otelarrow](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/otelarrowexporter/otelarrow.go#L262)). 

The way partial success responses are treated in those OTLP exporters is that only logs/metrics are recorded in the exporter, and they return no errors - so to upstream components, partial success looks like full success.

There's an issue (part of v1 milestone) to handle partial errors in Collector's consumer error infrastructure: https://github.com/open-telemetry/opentelemetry-collector/issues/13423.

File: libbeat/otel/otelconsumer/otelconsumer.go (hunk 5 above)
Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer.go:215]: Looking at this closer, should the backoff constructor even accept the context cancel channel? Wouldn't it make more sense for the `Wait` method to accept a Context parameter? 🤔 If that were the case, each call to `Wait` could naturally use the current available context.

Comment (andrzej-stencel) [reply libbeat/otel/otelconsumer/otelconsumer.go:215]: We discussed this today in the Data Plane team meeting. I'm going to create a separate PR changing the Backoff interface API to `Wait(Context)`.
