### PR TITLE
Log any FQDN lookup errors and fallback to OS-reported hostname

### LINKED ISSUE #34910: Cannot start Beats - fails with error: could not get FQDN
I'm unable to start Metricbeat and Filebeat.

For confirmed bugs, please report:
- Version: main from b8e0449d12b1a4
- Operating System: macOS 13.2.1 (22D68)
- Discuss Forum URL:
- Steps to Reproduce: 
1. Try to get the Metricbeat version.

```
./metricbeat version
error initializing beat: failed to get host information: 1 error: could not get FQDN, all methods failed: failed looking up CNAME: lookup mac16-m1: no such host: failed looking up IP: lookup mac16-m1: no such host
```

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR fixes a bug wherein a Beat would fail to start if the FQDN lookup failed.

## Why is it important?

FQDN lookup is "best effort".  As such, if the lookup fails for some reason, we should not fail to start a Beat or halt execution otherwise.  Instead, we should fallback to the OS-provided hostname and continue execution.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~I have made corresponding changes to the documentation~
- [ ] ~I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] ~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

## How to test this PR locally

1. Build Filebeat (or any other Beat) with this PR.
   ```sh
   cd beats/filebeat
   mage clean build
   ```

2. Set hostname to something that wouldn't resolve via DNS.  On MacOS this can be done via:
   ```sh
   orig_hostname=$(hostname -f)
   sudo scutil --set HostName cowchicken
   ```

3. Run `filebeat version`.  This command should report the version as usual and NOT fail with an FQDN-related error (as reported in #34910)
   ```sh
   ./filebeat version
   ```
   ```
   filebeat version 8.8.0 (arm64), libbeat 8.8.0 [528128f44ee870cedca830d8acbf63d8ee35ae26 built 2023-03-28 16:45:09 +0000 UTC]
   ```

4. Create a configuration file for the Beat that enables the `add_host_metadata` processor and also enables the FQDN feature flag.
   ```sh
   cat <<EOF >filebeat.test.yml
   filebeat.inputs:
   - type: stdin
   
   processors:
   - add_host_metadata: ~
   
   features.fqdn.enabled: true
   output.console.enabled: true
   EOF
   ```

5.  Start the Beat with the above configuration and look for log entries mentioning `FQDN`.  You should see two log entries in all, one from Beat initialization and one from the `add_host_metadata` processor.

    ```sh
    ./filebeat -c ./filebeat.test.yml -e 2>&1 | grep -i fqdn
    ```

    ```
    {"log.level":"warn","@timestamp":"2023-03-28T11:38:17.639-0700","log.origin":{"file.name":"instance/beat.go","file.line":802},"message":"unable to lookup FQDN: could not get FQDN, all methods failed: failed looking up CNAME: lookup cowchicken: no such host: failed looking up IP: lookup cowchicken: no such host, using hostname = cowchicken as FQDN","service.name":"filebeat","ecs.version":"1.6.0"}
    {"log.level":"warn","@timestamp":"2023-03-28T11:38:17.642-0700","log.logger":"add_host_metadata","log.origin":{"file.name":"add_host_metadata/add_host_metadata.go","file.line":152},"message":"unable to lookup FQDN: could not get FQDN, all methods failed: failed looking up CNAME: lookup cowchicken: no such host: failed looking up IP: lookup cowchicken: no such host, using hostname = cowchicken as FQDN","service.name":"filebeat","ecs.version":"1.6.0"}
    ```

99. Reset hostname at the end of the test.  On MacOS this can be done via:
    ```sh
    sudo scutil --set HostName $orig_hostname
    ```

## Related issues

- Closes #34910
- Follow up to https://github.com/elastic/beats/pull/34456

### CODE REVIEW

File: libbeat/processors/add_host_metadata/add_host_metadata.go [hunk 1]
```diff
@@ -143,7 +143,19 @@ func (p *addHostMetadata) loadData() error {
...
+		if err != nil {
+			// FQDN lookup is "best effort".  We log the error, fallback to
+			// the OS-reported hostname, and move on.
+			p.logger.Infof("unable to lookup FQDN: %s", err.Error())
+		} else {
+			hostname = fqdn
+		}
+	}
+
+	data := host.MapHostInfo(h.Info(), hostname)
```
Comment (ycombinator) [inline libbeat/processors/add_host_metadata/add_host_metadata.go:158]: Depends on https://github.com/elastic/elastic-agent-system-metrics/pull/81 being merged and dependency on `elastic-agent-system-metrics` being bumped up.

File: libbeat/cmd/instance/beat.go [hunk 2]
```diff
@@ -595,7 +602,7 @@ func (b *Beat) RegisterHostname(useFQDN bool) {
 
 	// state.host
 	stateRegistry := monitoring.GetNamespace("state").GetRegistry()
-	monitoring.NewFunc(stateRegistry, "host", host.ReportInfo(useFQDN), monitoring.Report)
+	monitoring.NewFunc(stateRegistry, "host", host.ReportInfo(hostname), monitoring.Report)
```
Comment (ycombinator) [inline libbeat/cmd/instance/beat.go:605]: Depends on https://github.com/elastic/elastic-agent-system-metrics/pull/81 being merged and dependency on `elastic-agent-system-metrics` being bumped up.

File: libbeat/cmd/instance/beat.go [hunk 3]
```diff
@@ -248,7 +248,14 @@ func NewBeat(name, indexPrefix, v string, elasticLicensed bool) (*Beat, error) {
 	if err != nil {
 		return nil, fmt.Errorf("failed to get host information: %w", err)
 	}
-	fqdn := h.Info().FQDN
+
+	fqdn, err := h.FQDN()
+	if err != nil {
+		// FQDN lookup is "best effort".  We log the error, fallback to
+		// the OS-reported hostname, and move on.
+		logp.NewLogger(name).Infof("unable to lookup FQDN: %s, using hostname = %s", err.Error(), hostname)
```
Comment (ycombinator) [inline libbeat/cmd/instance/beat.go:256]: I'm not able to get this log message to be printed to the logs.  After reading the godoc for the `logp.NewLogger` function, I've also tried using `logp.L()` instead but that didn't work either.  Adding a `fmt.Println` right above this line works, though.  @faec is helping me figure out why the logging might not be working here.

Comment (ycombinator) [reply libbeat/cmd/instance/beat.go:256]: Turns out logging isn't configured at this point so we need to move the FQDN initialization to slightly later in the execution.

File: libbeat/cmd/instance/beat.go [hunk 4]
```diff
@@ -244,12 +244,6 @@ func NewBeat(name, indexPrefix, v string, elasticLicensed bool) (*Beat, error) {
 		return nil, err
 	}
 
-	h, err := sysinfo.Host()
-	if err != nil {
-		return nil, fmt.Errorf("failed to get host information: %w", err)
-	}
-	fqdn := h.Info().FQDN
-
```
Comment (ycombinator) [inline libbeat/cmd/instance/beat.go:252]: This piece of code had to be moved to slightly later in the Beat's execution because we need logging to be configured to emit a warning if the FQDN lookup fails.  You'll find it elsewhere in this PR, along with the logging.

File: libbeat/processors/add_host_metadata/add_host_metadata.go [hunk 5]
```diff
@@ -143,7 +143,19 @@ func (p *addHostMetadata) loadData() error {
...
 	}
 
-	data := host.MapHostInfo(features.FQDN(), h.Info())
+	hostname := h.Info().Hostname
+	if features.FQDN() {
+		fqdn, err := h.FQDN()
+		if err != nil {
+			// FQDN lookup is "best effort".  We log the error, fallback to
+			// the OS-reported hostname, and move on.
+			p.logger.Warnf("unable to lookup FQDN: %s, using hostname = %s as FQDN", err.Error(), hostname)
```
Comment (cmacknz) [inline libbeat/processors/add_host_metadata/add_host_metadata.go:152]: How often would this be logged? We may want to lower this to Debug to avoid unnecessarily spamming the logs when this fails.

Comment (cmacknz) [reply libbeat/processors/add_host_metadata/add_host_metadata.go:152]: It feels like we would be better off with a metrics counter for how often this resolution has failed.

That would tell us it's failing without worrying about log spam, and we could then turn on debug logging to see exactly what is happening.

**Comment by cmacknz** [comment]
I assume writing a regression test for this is challenging because it requires us to modify the hostname of the system running the tests to one that doesn't resolve via DNS?

File: libbeat/processors/add_host_metadata/add_host_metadata.go (hunk 5 above)
Comment (ycombinator) [reply libbeat/processors/add_host_metadata/add_host_metadata.go:152]: > It feels like we would be better off with a metrics counter for how often this resolution has failed.
> 
> That would tell us it's failing without worrying about log spam, and we could then turn on debug logging to see exactly what is happening.

Makes sense.  Let me look into implementing a metrics counter.

**Comment by cmacknz** [comment]
Also your test steps are excellent, thank you! I followed them exactly and the lack of fqdn logs caught that my attempt to switch branches failed because I had local file modifications to discard first :p

**Comment by ycombinator** [comment]
> I assume writing a regression test for this is challenging because it requires us to modify the hostname of the system running the tests to one that doesn't resolve via DNS?

Yes. Perhaps we can do something with a Docker testcontainer, though.  Let me look into that.

**Comment by leehinman** [comment]
> > I assume writing a regression test for this is challenging because it requires us to modify the hostname of the system running the tests to one that doesn't resolve via DNS?
> 
> Yes. Perhaps we can do something with a Docker testcontainer, though. Let me look into that.

maybe https://github.com/foxcpp/go-mockdns ?

**Comment by ycombinator** [comment]
Thanks to @leehinman's suggestion about https://github.com/foxcpp/go-mockdns, I was able to implement a couple of unit test cases - one where the FQDN lookup will succeed and one where it will fail.  I've also implemented the metrics counter and dropped the log level for the FQDN lookup failure in the `add_host_metadata` processor to `debug`, as suggested by @cmacknz.

This PR is ready for review again.

File: libbeat/processors/add_host_metadata/add_host_metadata.go [hunk 6]
```diff
@@ -48,23 +63,30 @@ type addHostMetadata struct {
...
 // New constructs a new add_host_metadata processor.
 func New(cfg *config.C) (processors.Processor, error) {
 	c := defaultConfig()
 	if err := cfg.Unpack(&c); err != nil {
 		return nil, fmt.Errorf("fail to unpack the %v configuration: %w", processorName, err)
 	}
 
+	// Logging and metrics (each processor instance has a unique ID).
+	var (
+		id     = int(instanceID.Inc())
```
Comment (cmacknz) [inline libbeat/processors/add_host_metadata/add_host_metadata.go:78]: First time I've seen this way of getting around the namespace collision issue. CC @fearful-symmetry, this could help the version of this problem you have in the shipper.

File: libbeat/processors/add_host_metadata/add_host_metadata.go [hunk 7]
```diff
@@ -48,23 +63,30 @@ type addHostMetadata struct {
...
+		logger = logp.NewLogger(logName).With("instance_id", id)
+		reg    = monitoring.Default.NewRegistry(logName+"."+strconv.Itoa(id), monitoring.DoNotReport)
```
Comment (cmacknz) [inline libbeat/processors/add_host_metadata/add_host_metadata.go:80]: Do we actually need a separate instance of this per processor? Do we expect the errors to be unique per processor instance? There's also no way to map the ID here back to the configuration, so it seems a bit arbitrary and is probably simpler if we just have one atomic counter shared by all instances of this processor.

```json
      "processor": {
        "add_host_metadata": {
          "1": {
            "fqdn_lookup_failed": 1
          }
        }
      },
```

99% of the time there is just going to be the one add_host_metadata instance applied to each event collected since that is what is configured by default. If someone configured this to be per input we could end up with a lot of processor instances (think k8s autodiscovery where every pod gets its own input).

Comment (ycombinator) [reply libbeat/processors/add_host_metadata/add_host_metadata.go]: Fixed via d9d55c7735.

File: libbeat/processors/add_host_metadata/add_host_metadata.go (hunk 6 above)
Comment (fearful-symmetry) [reply libbeat/processors/add_host_metadata/add_host_metadata.go]: huh, interesting!
