### PR TITLE
stop monitoring excluded paths

### LINKED ISSUE #21278: should not emit fsnotify watcher error for files match excluded_files pattern
**Describe the enhancement:**
as title

**Describe a specific use case for the enhancement or feature:**
warning errors are flooding while there is no way to stop it, sample logs is attached as below, some paths of source code in the stack trace are masked.

```
2020-09-24T02:24:13.740Z        WARN    [file_integrity]        file_integrity/eventreader_fsnotify.go:151      fsnotify watcher error  {"error": "failed to visit created path '/run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e29f16a651a5b6a94365a3132b563a2c3362f5546972fdc783f3d6071542831/rootfs/etc/runit/runsvdir/default/mcelog/supervise/stat.new': path component stat.new not found in /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e29f16a651a5b6a94365a3132b563a2c3362f5546972fdc783f3d6071542831/rootfs/etc/runit/runsvdir/default/mcelog/supervise/stat.new", "errorVerbose": "path component stat.new not found in /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e29f16a651a5b6a94365a3132b563a2c3362f5546972fdc783f3d6071542831/rootfs/etc/runit/runsvdir/default/mcelog/supervise/stat.new\nfailed to visit created path '/run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e29f16a651a5b6a94365a3132b563a2c3362f5546972fdc783f3d6071542831/rootfs/etc/runit/runsvdir/default/mcelog/supervise/stat.new'\ngithub.com/elastic/beats/v7/auditbeat/module/file_integrity/monitor.(*recursiveWatcher).forwardEvents\n\t/go/src/xxx/xxx/beats-xxx/vendor/github.com/elastic/beats/v7/auditbeat/module/file_integrity/monitor/recursive.go:168\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
```

### PR DESCRIPTION
**Pull request by newly12**
## What does this PR do?

If the files match the excluded pattern, `recursiveWatcher` does not emit events for them, as well as errors if any.

## Why is it important?

This eliminates unnecessary warning logs for file paths that user intends to exclude.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ~~I have made corresponding changes to the documentation~~
- [x] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

run test case `TestRecursiveExcludedPaths`

## Related issues

- Closes elastic/beats#21278

### CODE REVIEW

**Comment by newly12** [comment]
Hi,

Could someone please have a look at this PR? Feel free to let me know your thought on this. Thanks in advance.

**Comment by marc-gr** [comment]
jenkins run tests

**Comment by newly12** [comment]
Hi,

the test is completed. is there any concern regarding this PR? Please let me know.

File: auditbeat/module/file_integrity/monitor/recursive.go [hunk 1]
```diff
@@ -154,7 +161,7 @@ func (watcher *recursiveWatcher) forwardEvents() error {
 			switch event.Op {
 			case fsnotify.Create:
 				err := watcher.addRecursive(event.Name)
-				if err != nil {
+				if err != nil && !watcher.isExcludedPath(event.Name) {
```
Comment (adriansr) [inline auditbeat/module/file_integrity/monitor/recursive.go:164]: So the changes to this function are ignoring errors related to ignored paths. Does it still make sense to act on events for ignored paths?

For example, adding a recursive watch on an ignored directory. I wonder if it will make more sense to just skip events for ignored paths.

**Review by adriansr — CHANGES_REQUESTED** [review]

File: auditbeat/module/file_integrity/monitor/recursive.go (hunk 1 above)
Comment (newly12) [reply auditbeat/module/file_integrity/monitor/recursive.go]: @adriansr Thanks for the review, it makes more sense to stop watching them. I've updated this PR regarding your suggestion, please have a look.

**Comment by adriansr** [comment]
jenkins, test this

**Comment by adriansr** [comment]
jenkins, test this please

**Comment by vjsamuel** [comment]
@adriansr  do we have anything left to address as part of this PR? would love to get this in so that we can reenable log shipping on our end.

**Comment by adriansr** [comment]
enkins run tests

**Review by adriansr — COMMENTED** [review]
@newly12, all is looking good. Only needs a changelog entry in CHANGELOG.next.asciidoc.

**Comment by newly12** [comment]
Thanks @adriansr ! I've `CHANGELOG.next.asciidoc` and title of this PR as _stop monitoring excluded paths_ to reflect what it really does. Please let me know if anything.

**Comment by marc-gr** [comment]
jenkins run tests

**Review by adriansr — APPROVED** [review]
