### PR TITLE
Log: Add experimental option "redirect_stderr" (#8430)

### LINKED ISSUE #8430: Some panics stacktraces are lost when Beats run as a service
We rely on wrapping goroutines on logp.Recover so those panics make their way to logfiles. However, for non-wrapped goroutines, this information is printed to standard error and the Beat terminated, making some crashes hard to spot.

### PR DESCRIPTION
**Pull request by adriansr**
This patch adds a new option to log file output: `redirect_stderr`.

When it is set, any messages written to stderr from the beat process
will be written to the log file. This allows to capture panics that are
not catched by logp.Recover.

Fixes #8430

### CODE REVIEW

File: libbeat/logp/config.go [hunk 1]
```diff
@@ -42,12 +42,13 @@ type Config struct {
...
-	MaxBackups  uint          `config:"keepfiles" validate:"max=1024"`
-	Permissions uint32        `config:"permissions"`
-	Interval    time.Duration `config:"interval"`
+	Path           string        `config:"path"`
+	Name           string        `config:"name"`
+	MaxSize        uint          `config:"rotateeverybytes" validate:"min=1"`
+	MaxBackups     uint          `config:"keepfiles" validate:"max=1024"`
+	Permissions    uint32        `config:"permissions"`
+	Interval       time.Duration `config:"interval"`
+	RedirectStderr bool          `config:"redirect_stderr"`
```
Comment (andrewkroh) [inline libbeat/logp/config.go]: This should be added to the reference config files.

**Comment by adriansr** [comment]
jenkins, test this

File: libbeat/docs/loggingconfig.asciidoc [hunk 2]
```diff
@@ -169,6 +169,15 @@ unix epoch. Defaults to disabled.
 
 When true, logs messages in JSON format. The default is false.
 
+[float]
+==== `logging.files.redirect_stderr` experimental[]
+
+When true, diagnostic messages printed to {beatname_uc}'s standard error output
```
Comment (andrewkroh) [inline libbeat/docs/loggingconfig.asciidoc]: This only works with the file output, right? If so I'd add a note about that just so that no one expects it to work with syslog or event_log outputs.

**Comment by adriansr** [comment]
jenkins, test this
