### PR TITLE
[Filebeat] Fix hardcoded amazonaws.com endpoint

### LINKED ISSUE #24420: Filebeat AWS Module S3 input error queueURL is not in format
Trying to use filebeat to monitor my AWS resources in ISO environment. It looks like the AWS standard endpoint is hard coded.

my filebeat.yml

Copy to clipboard
filebeat.inputs:
- type: s3
  queue_url: https://sqs.us-iso-east-1.c2s.ic.gov/#####/name
  visibility_timeout: 300s
Errors

Copy to clipboard
ERROR	[s3]	s3/input.go:93 Input 'S3' failed with: getRegionFromQueueURL failed: queueURL is not in format: https://sqs.{REGION_ENDPOINT}.amazonaws.com/{ACCOUNT_NUMBER}/{QUEUE_NAME} 

looks like it is hardcoded to only work if the endpoint is in AWS Commercial with .amazonaws.com as the endpoint, it looks for that in the code. we would need it to be a variable so instead of looking for say
https://sqs.{REGION_ENDPOINT}.amazonaws.com/{ACCOUNT_NUMBER}/{QUEUE_NAME}
It should be something like
https://sqs.{REGION_ENDPOINT}.{ENDPOINT}/{ACCOUNT_NUMBER}/{QUEUE_NAME}
Allowing you to set the endpoint to whatever AWS ENV you are in so in our case c2s.ic.gov
This is probably also hurting the people in Gov cloud and anything else that does not point to amazonaws.com

Built from the topic below:
https://discuss.elastic.co/t/filebeat-aws-module-s3-input-error-queueurl-is-not-in-format/261850

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Updates the S3 input validation for the queue url to check for the amazonaws.com domain or for the domain to match the endpoint config parameter that already exists.

## Why is it important?

Adds the ability for to use non amazonaws.com domains for Filebeat S3 input.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

closes #24420

### CODE REVIEW

**Comment by legoguy1000** [comment]
Besides running the standard `pythonIntegTest` I'm not sure how to best test changes to the Go code besides trying to spin up the binary and test the configs.

**Comment by kaiyan-sheng** [comment]
> Besides running the standard `pythonIntegTest` I'm not sure how to best test changes to the Go code besides trying to spin up the binary and test the configs.

@legoguy1000 Thanks for your contribution! We have unit tests for the golang code and for this function `getRegionFromQueueURL` specifically, there is `TestGetRegionFromQueueURL` under `beats/x-pack/filebeat/input/awss3/collector_test.go`. Please add some test cases there for URLs that have a different endpoint. Thank you!!

File: x-pack/filebeat/input/awss3/collector.go [hunk 1]
```diff
@@ -226,14 +226,14 @@ func (c *s3Collector) changeVisibilityTimeout(queueURL string, visibilityTimeout
...
+func getRegionFromQueueURL(queueURL string, endpoint string) (string, error) {
 	// get region from queueURL
 	// Example: https://sqs.us-east-1.amazonaws.com/627959692251/test-s3-logs
 	queueURLSplit := strings.Split(queueURL, ".")
-	if queueURLSplit[0] == "https://sqs" && queueURLSplit[2] == "amazonaws" {
+	if queueURLSplit[0] == "https://sqs" && ((endpoint != "" && strings.Join(queueURLSplit[2:], ".") == endpoint) || queueURLSplit[2] == "amazonaws") {
 		return queueURLSplit[1], nil
 	}
-	return "", fmt.Errorf("queueURL is not in format: https://sqs.{REGION_ENDPOINT}.amazonaws.com/{ACCOUNT_NUMBER}/{QUEUE_NAME}")
+	return "", fmt.Errorf("queueURL is not in format: https://sqs.{REGION_ENDPOINT}.amazonaws.com/{ACCOUNT_NUMBER}/{QUEUE_NAME} or https://sqs.{REGION_ENDPOINT}.{ENDPOINT}/{ACCOUNT_NUMBER}/{QUEUE_NAME}")
```
Comment (kaiyan-sheng) [inline x-pack/filebeat/input/awss3/collector.go:236]: I think you can just use `https://sqs.{REGION_ENDPOINT}.{ENDPOINT}/{ACCOUNT_NUMBER}/{QUEUE_NAME}` in the error message because this also includes the case with default `amazonaws.com`.

Comment (legoguy1000) [reply x-pack/filebeat/input/awss3/collector.go:236]: done

**Comment by legoguy1000** [comment]
> > Besides running the standard `pythonIntegTest` I'm not sure how to best test changes to the Go code besides trying to spin up the binary and test the configs.
> 
> @legoguy1000 Thanks for your contribution! We have unit tests for the golang code and for this function `getRegionFromQueueURL` specifically, there is `TestGetRegionFromQueueURL` under `beats/x-pack/filebeat/input/awss3/collector_test.go`. Please add some test cases there for URLs that have a different endpoint. Thank you!!

Done.

File: x-pack/filebeat/input/awss3/collector_test.go [hunk 2]
```diff
@@ -58,11 +58,25 @@ func (m *MockS3Client) GetObjectRequest(input *s3.GetObjectInput) s3.GetObjectRe
 
 func TestGetRegionFromQueueURL(t *testing.T) {
 	queueURL := "https://sqs.us-east-1.amazonaws.com/627959692251/test-s3-logs"
-	regionName, err := getRegionFromQueueURL(queueURL)
+	regionName, err := getRegionFromQueueURL(queueURL, "")
 	assert.NoError(t, err)
 	assert.Equal(t, "us-east-1", regionName)
 }
 
+func TestGetRegionFromQueueURLOtherEndpoint(t *testing.T) {
```
Comment (kaiyan-sheng) [inline x-pack/filebeat/input/awss3/collector_test.go:66]: Thank you for adding the test! Could you actually combine these two tests together using the `[]struct` please? You can follow `TestHandleMessage` for syntax.

Comment (legoguy1000) [reply x-pack/filebeat/input/awss3/collector_test.go:66]: Will do.

Comment (legoguy1000) [reply x-pack/filebeat/input/awss3/collector_test.go]: done

File: x-pack/filebeat/input/awss3/collector.go [hunk 3]
```diff
@@ -226,14 +226,20 @@ func (c *s3Collector) changeVisibilityTimeout(queueURL string, visibilityTimeout
...
-func getRegionFromQueueURL(queueURL string) (string, error) {
+func getRegionFromQueueURL(queueURL string, endpoint string) (string, error) {
 	// get region from queueURL
 	// Example: https://sqs.us-east-1.amazonaws.com/627959692251/test-s3-logs
-	queueURLSplit := strings.Split(queueURL, ".")
-	if queueURLSplit[0] == "https://sqs" && queueURLSplit[2] == "amazonaws" {
-		return queueURLSplit[1], nil
+	url, err := url.Parse(queueURL)
+	if err != nil {
+		return "", fmt.Errorf("QueueURL is not a valid URL")
```
Comment (kaiyan-sheng) [inline x-pack/filebeat/input/awss3/collector.go:234]: nit: Could we expose the actual `queueURL` in this error message please?

Comment (legoguy1000) [reply x-pack/filebeat/input/awss3/collector.go]: done

**Review by kaiyan-sheng — APPROVED** [review]
Thanks for your contribution!! This PR looks good to me!
