### PR TITLE
filebeat: input/v2: NewPipelineClientListener reuses existing metrics

### LINKED ISSUE #43884: filebeat input aws-s3 panics for waf datastream
Filebeat is panicking for an test on the integrations repo:
 - https://github.com/elastic/integrations/issues/13524

For confirmed bugs, please report:
- Version: main, 8.19.0-SNAPSHOT
- Operating System: all
- Discuss Forum URL: N/A
- Steps to Reproduce: see https://github.com/elastic/integrations/issues/13524

### PR DESCRIPTION
**Pull request by AndersonQ**
The input/v2.NewPipelineClientListener function now checks if pipeline metrics are already registered in the registry. If found, the existing metrics instance is reused instead of creating a new one.

## Proposed commit message

```
filebeat: input/v2: NewPipelineClientListener reuses existing metrics

The input/v2.NewPipelineClientListener function now checks if pipeline
metrics are already registered in the registry. If found, the existing
metrics instance is reused instead of creating a new one.
```

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Disruptive User Impact

 - n/a

## How to test this PR locally

 - TODO

## Related issues

- Closes #43884
- Closes https://github.com/elastic/integrations/issues/13524

### CODE REVIEW

File: filebeat/input/v2/input.go [hunk 1]
```diff
@@ -114,27 +120,50 @@ func (c *Context) UpdateStatus(status status.Status, msg string) {
...
-			reg, "events_pipeline_published_total"),
+	pcl := &PipelineClientListener{}
+
+	if monVar := reg.Get(metricEventsPipelineTotal); monVar == nil {
+		pcl.eventsTotal = monitoring.NewUint(
+			reg, metricEventsPipelineTotal)
+	} else {
+		if monUInt, ok := monVar.(*monitoring.Uint); ok {
+			pcl.eventsTotal = monUInt
+		}
```
Comment (efd6) [inline filebeat/input/v2/input.go:137]: This looks like it could be factored out in to a helper.

Comment (AndersonQ) [reply filebeat/input/v2/input.go]: done

**Review by efd6 — APPROVED** [review]
LGTM

It would be nice to be able to test the case that triggered the bug. I think the way to do that might be to run a test case on that input with multiple workers. That appears to be what triggered the issue.

**Comment by AndersonQ** [comment]
> It would be nice to be able to test the case that triggered the bug. I think the way to do that might be to run a test case on that input with multiple workers. That appears to be what triggered the issue.

yeah, but now there is a test for the underlying cause of the problem and we do have the tests on the integrations repo anyway, so we're covered even without this test

**Review by faec — APPROVED** [review]
