### PR TITLE
Fix #7998: ignore event fields that contains a nil interface of type encoding.TextMarshaler

### LINKED ISSUE #7998: [libbeat] crashes when the eventMap contains an implementation of type *encoding.TextMarshaler and value nil
Version: libbeat any version (tested against mater 264e7b428389e73246deaf05913f274cf6fd5e2b)

**Steps to reproduce**

```
var completed *time.Time // not yet completed
event := common.MapStr{
    "date.completed": completed
}
esclient.Publish(event)
```

**Expected result**

The `date.completed` field is dropped similar to other nil pointers

**Actual result**
```
panic: value method time.Time.MarshalText called using nil *Time pointer [recovered]
        panic: value method time.Time.MarshalText called using nil *Time pointer
```

**Reason:**
`time.Time` implements `encoding.TextMarshaler`. therefore it goes to a specific case that doesn't check for nil values

### PR DESCRIPTION
**Pull request by cyrilleverrier**
Fix #7998: ignore event fields that contains a nil interface of type encoding.TextMarshaler

### CODE REVIEW

**Comment by kvch** [comment]
jenkins test this

File: libbeat/common/event.go [hunk 1]
```diff
@@ -158,6 +158,9 @@ func normalizeValue(value interface{}, keys ...string) (interface{}, []error) {
 
 	switch value.(type) {
 	case encoding.TextMarshaler:
+		if reflect.ValueOf(value).Kind() == reflect.Ptr && reflect.ValueOf(value).IsNil() {
```
Comment (andrewkroh) [inline libbeat/common/event.go]: Does it make sense to do this check up on line 135 where we check for plain old `nil`?

Comment (andrewkroh) [reply libbeat/common/event.go]: Right, but should we do this check immediately upon entering `normalizeValue` so that we drop all interfaces storing nil pointers?

Comment (cyrilleverrier) [reply libbeat/common/event.go]: @andrewkroh: I didn't want to add a run-time check for all fields in the event map.

The 2 cases where the `interface{}` can store a pointer to a nil value are `encoding.TextMarshaler` and `followPointer`. And `followPointer`  already checks for nil pointer
 

If you prefer, I can move the test to the beginning of the function `normalizeValue`.
It could be safer if a new encoder case is added later.

Comment (andrewkroh) [reply libbeat/common/event.go]: > I didn't want to add a run-time check for all fields in the event map.

I suspected that might be a reason for not doing it at method entry.

**Comment by andrewkroh** [comment]
jenkins test this
