### PR TITLE
[Bug] fix high IO after sudden filebeat stop (#35893)

### LINKED ISSUE #35893: High io consumption after sudden filebeat stop
Hi! I tried to [ask](https://discuss.elastic.co/t/high-iops-from-filebeat/334399) on discuss.elastic.co but no answer.

The problem is very high io, after sudden termination of a filebeat. The reason is a [checkpoint](https://github.com/elastic/beats/blob/master/libbeat/statestore/backend/memlog/store.go#L212-L214) action on each log operation. It is because of [log_invalid](https://github.com/elastic/beats/blob/master/libbeat/statestore/backend/memlog/diskstore.go#L210-L212) flag set to true, after failed initial log [read operation](https://github.com/elastic/beats/blob/master/libbeat/statestore/backend/memlog/store.go#L123-L133). After abnormal termination of a filebeat, log may be in a inconsistent state and read of log like this can cause error `Incomplete or corrupted log file in /usr/share/filebeat/data/registry/filebeat. Continue with last known complete and consistent state. Reason: invalid character '\\x00' looking for beginning of value`
After that, filebeat clears log file, but still not trying to write, and just make checkpoint by checkpoint.

- Version: 8.1.0 but i think bug still in the master 
- Operating System:  Ubuntu 18.04 kernel 5.4.0-139-generic
- Discuss Forum URL: https://discuss.elastic.co/t/high-iops-from-filebeat/334399
- Steps to Reproduce: 
1. Start filebeat
2. Shutdown machine suddenly
3. Start machine again
4. Start filebeat
5. Check the log for an errors

### PR DESCRIPTION
**Pull request by emmanueltouzery**
## Proposed commit message

In case of corrupted log file (which has good chances to happen in case of sudden unclean system shutdown), we set a flag which causes us to checkpoint immediately, but never do anything else besides that. This causes filebeat to just checkpoint on each log operation (therefore causing a high IO load on the server and also causing filebeat to fall behind).

This change resets the logInvalid flag after a successful checkpointing.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

I have not in fact tested the PR. I have only checked that it builds. I'm also not 100% sure of the correctness, but the change is really simple and I hope that a maintainer can quickly confirm whether the fix is correct. In any case the current code clearly will cause the issues I described, since `logInvalid` is only ever set to `true`, never to `false`. Therefore I think that the beat trivially cannot recover.

## Related issues

- Closes #35893

## Logs

See details in #35893 but the issue we fix otherwise manifests itself with a message of:
> WARN memlog/store.go:130 Incomplete or corrupted log file in /var/lib/filebeat/registry/filebeat. Continue with last known complete and consistent state. Reason: unexpected EOF

(or `invalid character '\x00'` instead of EOF)

### CODE REVIEW

**Comment by belimawr** [comment]
Hi @emmanueltouzery, looking at the code and the original issue, I can see it indeed is a bug. Restarting Filebeat should fix the problem, but I didn't have time to test it.

To get this merged we'd need some tests, setting `logInvalid` to `false` can be done right after truncating the log file.

Would you be interested in further working on this PR? I didn't take a deep look at our current tests, but I believe it would be simple to write a unit test that simulates this condition and ensure the fix works as expected.

I can try guiding you on this.

**Comment by emmanueltouzery** [comment]
Well first off I'm delighted that the issue will likely be fixed

**Comment by emmanueltouzery** [comment]
Sorry for closing and reopening, I'm typing on a smartphone.

I can confirm that restarting filebeat fixes the issue.

So if you think it makes sense for you, I can try to improve the PR further with your guidance and worst-case you take over. 

To start with, could you tell me in which file the test should be added?

With regards to when to reset the flag, you mention truncating the log, is that the checkpointing operation or does that happen elsewhere?

**Comment by emmanueltouzery** [comment]
ping?

**Comment by emmanueltouzery** [comment]
@belimawr I'm interested in trying to get a fix merged for this issue. 

could you tell me in which file the test should be added?

With regards to when to reset the flag, you mention truncating the log, is that the checkpointing operation or does that happen elsewhere?

Thank you!

**Comment by belimawr** [comment]
Hey @emmanueltouzery, sorry the delay in replying.

> With regards to when to reset the flag, you mention truncating the log, is that the checkpointing operation or does that happen elsewhere?

Yes, the checkpoint operation, once the log file is truncated, it will be in a valid state, so we can already reset the `logInvalid` flag.

https://github.com/elastic/beats/blob/23d106637069322b39b7f808b3940a788c82660c/libbeat/statestore/backend/memlog/diskstore.go#L396-L417

> could you tell me in which file the test should be added?

As you're modifying `diskstore.go`, you can create a test file next to it, `diskstore_test.go` and add at least one unit test there. I believe it should be simple to instantiate the disk store pointing to a file you can easily corrupt, validate that `logInvalid` gets reset and new data starts to be added to the log file.

Ping me if  you need more guidance.  The other tests in this package might help you.

**Comment by emmanueltouzery** [comment]
I have updated the PR now. I added the test against store, not diskstore, because the read validation is done in store. I also reused an invalid truncated log sample file from another test. Let me know whether that looks good!

I saw the CI fail, the errors seem unrelated to my code. Let me know if I'm wrong.

**Comment by emmanueltouzery** [comment]
I also added a second commit to fix deprecation warnings in diskstore.

File: libbeat/statestore/backend/memlog/store_test.go [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+	})
+	assert.NoError(t, err)
+
+	assert.Equal(t, true, store.disk.logInvalid)
+
+	err = store.logOperation(&opSet{K: "key", V: mapstr.M{
+		"field": 42,
+	}})
+	assert.NoError(t, err)
+	assert.Equal(t, false, store.disk.logInvalid)
```
Comment (belimawr) [inline libbeat/statestore/backend/memlog/store_test.go:53]: A few things here:
1. You can use `require` instead of assert when a condition that won't let the test continue happens, this way the test is interrupted
2. It's good practice to always add a message explaining why the test failed.

```suggestion
	require.NoError(t, err, "openStore must succeed")
	require.True(t, store.disk.logInvalid, "expecting the log file to be invalid")

	err = store.logOperation(&opSet{K: "key", V: mapstr.M{
		"field": 42,
	}})
	require.NoError(t, err, "logOperation must succeed")
	require.Equal(t, false, store.disk.logInvalid, "log file must be valid")
```

There are a couple of other things that would be good to assert here:
1. The checkpoint file was created (check the file `7.json` was created)
2. The log file is not corrupted any more/was truncated (check `log.json` is emtpy/0 bytes in size).

**Review by belimawr — CHANGES_REQUESTED** [review]
The PR is looking great @emmanueltouzery! There are a few things to improve/add and we'll be ready to merge it :star_struck:

**Comment by emmanueltouzery** [comment]
updated the PR, thanks for the great feedback!

now the docs fail, apparently i should run `make update`. if I run that in the libbeat subfolder, it succeeds but doesn't touch the disk. if I run it in the root of the folder, it fails with that output:
```
Generating NOTICE
go mod tidy
go: github.com/prometheus/prometheus@v1.8.2-0.20210701133801-b0944590a1c9 requires
        github.com/influxdata/influxdb@v1.9.2 requires
        github.com/influxdata/flux@v0.113.0 requires
        github.com/SAP/go-hdb@v0.14.1: reading github.com/SAP/go-hdb/go.mod at revision v0.14.1: unknown revision v0.14.1
make: *** [Makefile:172: notice] Error 1
```

so i'm not sure how to fix that.

**Comment by belimawr** [comment]
> updated the PR, thanks for the great feedback!
> 
> now the docs fail, apparently i should run `make update`. if I run that in the libbeat subfolder, it succeeds but doesn't touch the disk. if I run it in the root of the folder, it fails with that output:
> 
> ```
> Generating NOTICE
> go mod tidy
> go: github.com/prometheus/prometheus@v1.8.2-0.20210701133801-b0944590a1c9 requires
>         github.com/influxdata/influxdb@v1.9.2 requires
>         github.com/influxdata/flux@v0.113.0 requires
>         github.com/SAP/go-hdb@v0.14.1: reading github.com/SAP/go-hdb/go.mod at revision v0.14.1: unknown revision v0.14.1
> make: *** [Makefile:172: notice] Error 1
> ```
> 
> so i'm not sure how to fix that.

That's odd.

I tried here with your branch and it is working for me, here is what you can try:
1. Ensure all modified files are commited/stashed
2. Ensure you're running Go 1.21.10 and your environment has the $PATH correctly set for the `go` command and binaries `go install` might install.
3. Make sure you have [`mage`](https://magefile.org/) installed
4. From the root of the repository run:
    ```
    make clean
    make update
    make check
    ```

**Comment by belimawr** [comment]
I was looking again into it, and what is failing is one of the files is not formated as expected, to fix it:
```
cd libbeat
mage fmt
```
Then commit the updated file.

**Comment by emmanueltouzery** [comment]
thanks for the help, indeed that did it :tada:

File: libbeat/statestore/backend/memlog/store_test.go [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+		return false
+	})
+	require.NoError(t, err, "openStore must succeed")
+	require.True(t, store.disk.logInvalid, "expecting the log file to be invalid")
+
+	err = store.logOperation(&opSet{K: "key", V: mapstr.M{
+		"field": 42,
+	}})
+	require.NoError(t, err, "logOperation must succeed")
+	require.Equal(t, false, store.disk.logInvalid, "log file must be valid")
```
Comment (belimawr) [inline libbeat/statestore/backend/memlog/store_test.go:49]: Sorry I missed that in my last review, but here you can use `require.False`
```suggestion
	require.False(t, store.disk.logInvalid, "log file must be valid")
```

**Review by belimawr — CHANGES_REQUESTED** [review]
The PR is looking great! Just one small change and I'll approve it.

**Comment by emmanueltouzery** [comment]
applied your suggestion :+1: 
i was wondering, will this get backported to 7.x as well?

**Comment by dliappis** [comment]
test

**Review by belimawr — APPROVED** [review]

**Comment by belimawr** [comment]
> applied your suggestion 👍 i was wondering, will this get backported to 7.x as well?

I didn't look at the 7.17 code, but if the bug is also there, yes, we can backport it. I'll add the label to create the backport PR

**Comment by belimawr** [comment]
The lastest test run failed because of a known issue: https://github.com/elastic/beats/issues/39698. We'll have to wait for the test to be fixed or skipped and then update this PR with `main`.

**Comment by emmanueltouzery** [comment]
I can confirm that 7.x is affected too.

**Comment by emmanueltouzery** [comment]
> The lastest test run failed because of a known issue: https://github.com/elastic/beats/issues/39698. We'll have to wait for the test to be fixed or skipped and then update this PR with main.

but i see other things getting merged despite this? and no activity on #39698 in the last five days?

i'm mentioning this because from my point of view this issue we're fixing here is not that benign... i'm hoping the fix goes in sometime soon.

**Comment by belimawr** [comment]
> i'm mentioning this because from my point of view this issue we're fixing here is not that benign... i'm hoping the fix goes in sometime soon.

You're right, the issue is not with your PR. We do our best not to force merge PRs if CI is failing, even if it is for unrelated reasons. If there is a flaky tests, some times not all PRs fails on it, so they get merged.

I'll update your branch with the latest `main` and re-trigger CI.

**Comment by dliappis** [comment]
run docs-build

**Comment by belimawr** [comment]
Thank you so much for the help @emmanueltouzery !!

**Comment by emmanueltouzery** [comment]
I see this is not in 8.14.0. so this will be released in 8.15.0?

Thank you, and great we got this in!

**Comment by pierrehilbert** [comment]
Yes this will land in 8.15.0 in the current state but I think we should backport it to have it in 8.14.1.
@belimawr WDYT?
