### PR TITLE
Encode API key as base64 in common code

### LINKED ISSUE #18939: monitoring.elasticsearch.api_key needs to be base64 encoded
For confirmed bugs, please report:
- Version: 7.7.0
- Operating System: -
- Discuss Forum URL: -
- Steps to Reproduce: 

Both `output.elasticsearch` and `monitoring.elasticsearch` support the `api_key` setting (see [docs](https://www.elastic.co/guide/en/beats/filebeat/master/beats-api-keys.html)).

Furthermore, `monitoring.elasticsearch` will use the same `api_key` defined in `output.elasticsearch`, unless overridden by a different value.

However, since 7.7.0, either setting a custom api_key for monitoring or inheriting the key in output.elasticsearch will result in an authentication error:

```
 2020-05-27T13:41:56.219+0700    DEBUG   [monitoring]    elasticsearch/elasticsearch.go:254      Monitoring could not connect to Elasticsearch, failed with 401 Unauthorized: {"error    ":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey",    "Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Beare    r realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}
cannot connect underlying Elasticsearch client
github.com/elastic/beats/v7/libbeat/monitoring/report/elasticsearch.(*publishClient).Connect
         /go/src/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/client.go:66
 github.com/elastic/beats/v7/libbeat/monitoring/report/elasticsearch.(*reporter).initLoop
         /go/src/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/elasticsearch.go:245
 runtime.goexit
         /usr/local/go/src/runtime/asm_amd64.s:1357
```

After checking with Wireshark, I can see that `output.elasticsearch.api_key` results in an Authorization header that contains the original API key base64-encoded:
`Authorization: ApiKey MTV6S2VYSUJOQlZwREVmNXMySXI6M1oyTHI5RnFUSWlhLVE0el9QQndOQQ==`

but the monitoring requests, while using the same `api_key`, don't base64 encode the key in the header:
`Authorization: ApiKey 15zKeXIBNBVpDEf5s2Ir:3Z2Lr9FqTIia-Q4z_PBwNA`

Resulting in a `401 Unauthorized` error.

As a workaround, setting `monitoring.elasticsearch.api_key` to the base64-encoded API key fixes the issue.

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

Encodes the API key supplied to the Elasticsearch client with base64 encoding right before setting it in the `Authorization` request header.

## Why is it important?

The Elasticsearch client is shared by the Elasticsearch output as well as the Elasticsearch monitoring reporter. Rather than base64-encoding the API key in each of these places, it is better to base64-encode it within the client code itself.

In fact, prior to this PR, we were base64-encoding the key in the Elasticsearch output but not in the Elasticsearch monitoring reporter.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~I have made corresponding changes to the documentation~
- [ ] ~I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Fixes elastic/beats#18939

### CODE REVIEW

**Comment by ycombinator** [comment]
From my checking, the APM Server code is not directly calling `eslegclient.NewConnection` anywhere so they should be good with this change. Nevertheless, it would be good for someone from @elastic/apm-server to confirm. Thank you!

**Comment by simitt** [comment]
Thanks for the ping, the APM Server will not be affected by this change.

File: libbeat/esleg/eslegclient/connection.go [hunk 1]
```diff
@@ -436,7 +437,8 @@ func (conn *Connection) execHTTPRequest(req *http.Request) (int, []byte, error)
 	}
 
 	if conn.APIKey != "" {
-		req.Header.Add("Authorization", "ApiKey "+conn.APIKey)
+		encoded := base64.StdEncoding.EncodeToString([]byte(conn.APIKey))
+		req.Header.Add("Authorization", "ApiKey "+encoded)
```
Comment (urso) [inline libbeat/esleg/eslegclient/connection.go:441]: would it make sense to cache the result in a private variable like `conn.encodedAPIKey` ?

Comment (ycombinator) [reply libbeat/esleg/eslegclient/connection.go:441]: Yes, it would. No need to encode it each time we make a request to ES. Thanks for the suggestion, will implement!

Comment (ycombinator) [reply libbeat/esleg/eslegclient/connection.go]: Done in c3e5b43.

File: libbeat/esleg/eslegclient/connection.go [hunk 2]
```diff
@@ -75,6 +76,8 @@ type ConnectionSettings struct {
 
 	Timeout         time.Duration
 	IdleConnTimeout time.Duration
+
+	encodedAPIKey string // Base64-encoded API key
```
Comment (urso) [inline libbeat/esleg/eslegclient/connection.go:80]: Maybe we want to move the field to `Connection` ?

Comment (ycombinator) [reply libbeat/esleg/eslegclient/connection.go:80]: Sure, I guess because you want to keep `ConnectionSettings` just as the public settings API?

Comment (ycombinator) [reply libbeat/esleg/eslegclient/connection.go]: Done in dc4e921.

**Comment by andrewkroh** [comment]
On a related not I think our Beat docs are not clear on the expected format for the `api_key` value. I think the api_key reference docs should mention that the value is the "id and api_key joined by a colon". And this example is not correct since the value should be of the format `'<id>:<api_key>'`. Or am I misunderstanding how these are used?

Screen Shot 2020-06-04 at 5 59 59 PM

**Comment by ycombinator** [comment]
Thanks for pointing that out, @andrewkroh.  I agree that the example value in the doc is incorrect (it looks already base64-encoded). I will add the doc update to this PR.

**Comment by ycombinator** [comment]
Documentation for `api_key` setting updated in 22a25cc6be1c8f0c955f7a61a5c3f3503138628a. @andrewkroh @dedemorton would you mind taking a look? Thanks!

File: libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc [hunk 3]
```diff
@@ -37,13 +37,14 @@ output.elasticsearch:
   password: "{pwd}"
 ------------------------------------------------------------------------------
 
-To use an API key to connect to {es}, use `api_key`.
+To use an API key to connect to {es}, use `api_key`. The value must be the ID of
+the API key and the API key joined by a colon.
```
Comment (andrewkroh) [inline libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc:41]: This info would be good down on line 137 with the `api_key`.

File: libbeat/esleg/eslegclient/connection.go (hunk 2 above)
Comment (urso) [reply libbeat/esleg/eslegclient/connection.go]: > Sure, I guess because you want to keep ConnectionSettings just as the public settings API?

yep.

File: libbeat/esleg/eslegclient/connection.go [hunk 4]
```diff
@@ -435,8 +443,8 @@ func (conn *Connection) execHTTPRequest(req *http.Request) (int, []byte, error)
 		req.SetBasicAuth(conn.Username, conn.Password)
 	}
 
-	if conn.APIKey != "" {
-		req.Header.Add("Authorization", "ApiKey "+conn.APIKey)
+	if conn.encodedAPIKey != "" {
+		req.Header.Add("Authorization", "ApiKey "+conn.encodedAPIKey)
```
Comment (urso) [inline libbeat/esleg/eslegclient/connection.go:447]: nit: We still have an unnecessary alloc + copy here. If we initialize `encodedAPIKey = "ApiKey " + ...`, then we can just pass it to `Header` as is.

File: libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc (hunk 3 above)
Comment (ycombinator) [reply libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc:41]: Done in 42d288616.

File: libbeat/esleg/eslegclient/connection.go (hunk 4 above)
Comment (ycombinator) [reply libbeat/esleg/eslegclient/connection.go]: Changed in 47c9aacaaa04e9cc1e304d517144386a77483e02.

**Comment by ycombinator** [comment]
jenkins, run tests please
