### PR TITLE
[Filebeat] Improve aws-s3 gzip file detection to avoid false negatives

### LINKED ISSUE #29968: [filebeat] aws-s3 input falsely detects gzip file as a font
The aws-s3 input can fail to properly detect gzip files. We have a file that is falsely matched as application/vnd.ms-fontobject by https://pkg.go.dev/net/http#DetectContentType. I think we can replace the usage of that stdlib method with a more direct gzip magic number check. This would avoid the chance of falsely matching other signatures that are listed before gzip.

```diff
$ git diff s3_objects.go 
diff --git a/x-pack/filebeat/input/awss3/s3_objects.go b/x-pack/filebeat/input/awss3/s3_objects.go
index 7fe6b193fa..ebe1a5f082 100644
--- a/x-pack/filebeat/input/awss3/s3_objects.go
+++ b/x-pack/filebeat/input/awss3/s3_objects.go
@@ -15,7 +15,6 @@ import (
        "fmt"
        "io"
        "io/ioutil"
-       "net/http"
        "reflect"
        "strings"
        "time"
@@ -375,18 +374,13 @@ func s3ObjectHash(obj s3EventV2) string {
 // stream without consuming it. This makes it convenient for code executed after this function call
 // to consume the stream if it wants.
 func isStreamGzipped(r *bufio.Reader) (bool, error) {
-       // Why 512? See https://godoc.org/net/http#DetectContentType
-       buf, err := r.Peek(512)
+       buf, err := r.Peek(3)
        if err != nil && err != io.EOF {
                return false, err
        }
 
-       switch http.DetectContentType(buf) {
-       case "application/x-gzip", "application/zip":
-               return true, nil
-       default:
-               return false, nil
-       }
+       // gzip magic number (1f 8b) and the compression method (08 for DEFLATE).
+       return bytes.HasPrefix(buf, []byte{0x1F, 0x8B, 0x08}), nil
 }
 
 // s3Metadata returns a map containing the selected S3 object metadata keys.
```

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

Directly check the byte stream for the gzip magic number and deflate
compression type. Avoid using http.DetectContentType because it returns
the first match it finds while checking many signatures.

Closes #29968

## Why is it important?

Incorrect content type detection can result in garbage data being ingested.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #29968

### CODE REVIEW

File: x-pack/filebeat/input/awss3/s3_objects.go [hunk 1]
```diff
@@ -375,18 +374,13 @@ func s3ObjectHash(obj s3EventV2) string {
...
 	}
 
-	switch http.DetectContentType(buf) {
-	case "application/x-gzip", "application/zip":
-		return true, nil
-	default:
-		return false, nil
-	}
+	// gzip magic number (1f 8b) and the compression method (08 for DEFLATE).
+	return bytes.HasPrefix(buf, []byte{0x1F, 0x8B, 0x08}), nil
```
Comment (efd6) [inline x-pack/filebeat/input/awss3/s3_objects.go:383]: In case this throws false positives, an approach that can be used is to peek enough of the stream to allow the gzip header to be read, an error indicates definitively that the stream is not a gzip. **Noting here for future consideration only.**

**Review by efd6 — APPROVED** [review]
