### PR TITLE
Regenerate UUID of a Beat when meta.json is empty

### LINKED ISSUE #8558: Auditbeat doesn't start due to corrupt meta.json
@xeraa reports a fresh install of Auditbeat 6.4.2 on a fresh VM fails to start due to a corrupted `meta.json`.

```
2018-10-03T08:06:22.814Z        INFO    instance/beat.go:544    Home path: [/usr/share/auditbeat] Config path: [/etc/auditbeat] Data path: [/var/lib/auditbeat] Logs path: [/var/log/auditbeat]
2018-10-03T08:06:22.815Z        INFO    instance/beat.go:315    auditbeat stopped.
2018-10-03T08:06:22.824Z        ERROR   instance/beat.go:743    Exiting: Beat meta file reading error: EOF
```

meta.json is empty:
```
-rw------- 1 root root     0 Oct  2 23:46 meta.json
```

Auditbeat started fine after the file is removed.

- [ ] investigate what could've caused the empty file in the first place.
- [ ] (discuss) consider not failing startup when loading `meta.json` files.

For confirmed bugs, please report:
- Version: 6.4.2
- Operating System: Ubuntu 16.04
- Discuss Forum URL: n/a
- Steps to Reproduce:

### PR DESCRIPTION
**Pull request by michalpristas**
When meta.json exists but does not contain any data beats fails on `Beat meta reading error`
This fix treats an empty file as a non-existing file so UUID is regenerated

Other thing this PR fixes is atomic write of `meta.json`
flow changed from
`create meta.json.new`->`write meta.json.new`->`rename to meta.json`->`fsync parent dir`
to
`create meta.json.new`->`write meta.json.new`->`fsync meta.json.new`->`rename to meta.json`->`fsync parent dir`

as suspicion is that there is a race between write from buffer and fsync on dir (which does not care about the content) 

Fixes #8558

### CODE REVIEW

File: libbeat/cmd/instance/beat_test.go [hunk 1]
```diff
@@ -92,3 +95,37 @@ func TestInitKibanaConfig(t *testing.T) {
...
+	// cleanup
+	os.Remove(metaPath)
+	if backedUp {
+		err = os.Rename(backupMetaPath, metaPath)
+		assert.Equal(t, nil, err, "Cleanup failed")
+	}
+
+	assert.Equal(t, nil, metaErr, "Unable to load meta file properly")
+	assert.NotEqual(t, uuid.Nil, b.Info.ID, "Beats UUID is not set")
+}
```
Comment (ph) [inline libbeat/cmd/instance/beat_test.go]: Currently we do not execute tests in parallels, every time that we rely on the filesystem for testing this could lead to races condition when we moved to that.

I see two things we could do:
- Either we write a new system test to validates the issue, they are run in isolation and slower.
- Or we make the `loadMeta(metapath string)` take an arguments instead and test with a random file.

Also, looking at the original issue did we find out why this is happening?
Also you will need to add an item to the CHANGELOG.next.md as a bugfix.

Comment (michalpristas) [reply libbeat/cmd/instance/beat_test.go]: good point, i worked on an assumption that this will not be run in parallel, better safe than sorry
will go with filename arg to`loadMeta` func to keep tests short.
regarding root cause nothing found yet

**Comment by JHerget** [comment]
this is a dublicate PR #8858

**Comment by ph** [comment]
Sorry @JHerget, I've missed your original PR, when we looked through the backlog it was not linked to the original issue. The way done is a bit different in this PR, so have a defensive check and regenerate the meta.json is the file is empty and we also ensure a fsync, @michalpristas is also looking to add system test to this PR.

I think we can collaborate to correctly fixes this issue for good, like you we were not able to reproduce the problem consistenly, so your last comment concerning fsync and visibility look really like the cause here.

**Comment by michalpristas** [comment]
@JHerget ping for any additional thought

**Comment by ph** [comment]
@michalpristas LGTM, you will need to rebase.

**Comment by ph** [comment]
I have added the need backport label, let's backport it to 7.0.

**Comment by ph** [comment]
removing need backport because the backport was already done in 7.0
