### PR TITLE
Fix icmp duration

### LINKED ISSUE #17796: [Heartbeat] ICMP RTT field is missing
We [document](https://www.elastic.co/guide/en/beats/heartbeat/master/exported-fields-icmp.html) the `icmp.rtt.us` field, but probably lost it at some point in 7.x. We should bring this back, it's useful because it tracks ping time less DNS resolution time. 

This came up in [this forum thread](https://discuss.elastic.co/t/cannot-show-ping-because-icmp-rtt-us-no-value/226011/6)

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes elastic/beats#17796 

At some point in 7.x (probably 7.0) we stopped actually shipping the documented [ICMP fields](https://www.elastic.co/guide/en/beats/heartbeat/master/exported-fields-icmp.html). 

This PR fixes that, which is a minor change (it was just us nesting the field wrong). The larger change here is that this actually adds some basic tests to the ICMP plugin, and restructures the code so that it's more testable (somewhat similar to the TCP plugin). We never had tests for ICMP because testing ICMP presents unique problems in that it must run with elevated privileges that are not available on our CI servers.

The solution here is to abstract the actual ICMP loop and make that pluggable, letting our fields test here use a mock ICMP request. It's not ideal, but it's an improvement over the current code. This required moving some code around and adding an interface, but I tried to change the minimum number of lines to support the structure.

 More tests should be added in the future, but this definitely improves the situation for ICMP.
## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist / Testing locally

- [ ] Configure an ICMP check and verify that the heartbeat event shows up in ES with `icmp.rtt.us` and `icmp.requests` indexed and properly mapped.

### CODE REVIEW

File: heartbeat/monitors/active/icmp/icmp.go [hunk 1]
```diff
@@ -82,25 +107,25 @@ func create(
...
+	return monitors.MakePingIPFactory(func(event *beat.Event, ip *net.IPAddr) error {
+		rtt, n, err := jf.loop.ping(ip, config.Timeout, config.Wait)
 		if err != nil {
 			return err
 		}
 
 		icmpFields := common.MapStr{"requests": n}
 		if err == nil {
 			icmpFields["rtt"] = look.RTT(rtt)
-			eventext.MergeEventFields(event, icmpFields)
```
Comment (andrewvc) [inline heartbeat/monitors/active/icmp/icmp.go:101]: This was the main issue in the original code, we merged `icmpFields` into the root of the event, when it should have been nested in the `"icmp"` key.

File: heartbeat/monitors/active/icmp/loop.go [hunk 2]
```diff
@@ -18,371 +18,15 @@
...
-// timeoutError implements net.Error interface
-func (timeoutError) Error() string   { return "ping timeout" }
-func (timeoutError) Timeout() bool   { return true }
-func (timeoutError) Temporary() bool { return true }
-
-func (r *requestContext) Stop() {
-	r.l.mutex.Lock()
-	delete(r.l.requests, r.id)
-	r.l.mutex.Unlock()
+type ICMPLoop interface {
```
Comment (andrewvc) [inline heartbeat/monitors/active/icmp/loop.go:25]: This filename made more sense to hold the common interface that we can make a mock version of in tests.

File: heartbeat/monitors/active/icmp/stdloop.go [hunk 3]
```diff
@@ -0,0 +1,402 @@
+// Licensed to Elasticsearch B.V. under one or more contributor
```
Comment (andrewvc) [inline heartbeat/monitors/active/icmp/stdloop.go:1]: There are very few new changes in this file, it's just been moved from `loop.go` but the old filename didn't make much sense. I'll comment where the actual changes are

File: heartbeat/monitors/active/icmp/stdloop.go [hunk 4]
```diff
@@ -0,0 +1,402 @@
...
+	ts     time.Time
+	result chan requestResult
+}
+
+type requestResult struct {
+	packet packet
+	err    error
+}
+
+// stdLoop is a singleton for our main ICMP loop since it doesn't
```
Comment (andrewvc) [inline heartbeat/monitors/active/icmp/stdloop.go:83]: This comment has been added

File: heartbeat/monitors/active/icmp/stdloop.go [hunk 5]
```diff
@@ -0,0 +1,402 @@
...
+// is mandatory for the ICMP interface in go, where all monitors
+// must share a single loop.
+// These vars should not be used directly, but rather getStdLoop
+// should be invoked to initialize and return stdLoop.
+var (
+	stdICMPLoopInit      sync.Once
+	stdICMPLoopSingleton *stdICMPLoop
+)
+
+func getStdLoop() (*stdICMPLoop, error) {
```
Comment (andrewvc) [inline heartbeat/monitors/active/icmp/stdloop.go:94]: This function is new, and cleanly abstracts the singleton nature of the vars above, which previously were accessed directly in `icmp.go`

File: heartbeat/monitors/active/icmp/icmp.go [hunk 6]
```diff
@@ -82,25 +107,25 @@ func create(
 			return nil, 0, err
 		}
 
-		jobs = append(jobs, wrappers.WithURLField(u, job))
+		j = append(j, wrappers.WithURLField(u, job))
```
Comment (andrewvc) [inline heartbeat/monitors/active/icmp/icmp.go:110]: `jobs` isn't a great name since it conflicts with the `jobs` package
