### PR TITLE
x-pack/filebeat/input/httpjson: add fleet input status updating

### LINKED ISSUE #44282: [Filebeat] Add health status reporting to httpjson input
Update the HTTPJSON input to report its health status, providing better visibility into the operational state for users.

The HTTPJSON input should report its health status using the [`context.UpdateStatus()`](https://github.com/elastic/beats/blob/9190f776f5fb612a880cb013a9eec8a49fe17afd/filebeat/input/v2/input.go#L112) method. Status changes should only be reported when the status actually changes (don't repeatedly send HEALTHY if the status is already HEALTHY).

### Status Reporting
The input should report the following states:

- **STARTING**: When the input is initializing before making HTTP requests.
- **CONFIGURING**: When setting up HTTP client and validating configuration.
- **HEALTHY**: When successfully making requests and processing JSON responses.
  - HTTP 429 rate limiting responses
- **DEGRADED**: When encountering non-fatal errors but can still operate. Examples:
  - Template errors
  - API response errors
  - JSON parsing failures
  - Temporary network connectivity issues
- **FAILED**: When encountering fatal errors preventing operation. Examples:
  - Authentication failures (failed to obtain credentials)
  - Configuration errors (invalid URL, headers, etc.)

Include relevant context information with non-HEALTHY states:

- For HTTP status errors: Include status code and API endpoint (without credentials)
- For authentication issues: Include error message (but no sensitive data)
- For parsing issues: Include details about the invalid format or unexpected structure
- For rate limiting: Include rate limit headers if available or when it will resume
- For network issues: Include connection timeout details or DNS resolution problems

## References
See the CEL input implementation for reference:
https://github.com/elastic/beats/blob/6409d005a31e0147a40f0872794880b3df15a69c/x-pack/filebeat/input/cel/input.go#L111

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

See title.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #44282

### CODE REVIEW

File: x-pack/filebeat/input/httpjson/pagination.go [hunk 1]
```diff
@@ -161,6 +167,7 @@ func (iter *pageIterator) next() (*response, bool, error) {
 func (iter *pageIterator) getPage() (*response, error) {
 	bodyBytes, err := io.ReadAll(iter.resp.Body)
 	if err != nil {
+		iter.status.UpdateStatus(status.Degraded, "failed to read page body: "+err.Error())
```
Comment (bhapas) [inline x-pack/filebeat/input/httpjson/pagination.go:170]: Will dumping an error to the UI back to user related to input internals help? Can we make this more actionable , if it can be. 

Like, what should the user do if they encounter this error in their UI?

If elastic originated issue , then probably a quick SDH , but if it is something related to the vendor then the user does not have to come to elastic and then realise later that vendor is causing trouble.

File: x-pack/filebeat/input/httpjson/pagination.go [hunk 2]
```diff
@@ -182,6 +189,7 @@ func (iter *pageIterator) getPage() (*response, error) {
 			err = decode(iter.resp.Header.Get("Content-Type"), bodyBytes, &r)
 		}
 		if err != nil {
+			iter.status.UpdateStatus(status.Degraded, "failed to decode page: "+err.Error())
```
Comment (bhapas) [inline x-pack/filebeat/input/httpjson/pagination.go:192]: Similar to dumping an error back at the user.

File: x-pack/filebeat/input/httpjson/rate_limiter.go [hunk 3]
```diff
@@ -75,6 +78,7 @@ func (r *rateLimiter) applyRateLimit(ctx context.Context, resp *http.Response) (
 		return limitReached, nil
 	}
 	r.log.Debugf("Rate Limit: Wait until %v for the rate limit to reset.", t)
+	r.status.UpdateStatus(status.Degraded, "rate limited: waiting "+w.String())
```
Comment (bhapas) [inline x-pack/filebeat/input/httpjson/rate_limiter.go:81]: Isn't this in [Duration](https://pkg.go.dev/time#Until) which is int64 nanosecond
```suggestion
	r.status.UpdateStatus(status.Degraded, "rate limited: waiting "+math.Ceil(w.Seconds()+ " seconds")
```

File: x-pack/filebeat/input/httpjson/request.go [hunk 4]
```diff
@@ -57,20 +58,26 @@ func (r *requester) doRequest(ctx context.Context, trCtx *transformContext, publ
 			// perform and store regular call responses
 			httpResp, err = rf.collectResponse(ctx, trCtx, r)
 			if err != nil {
-				return fmt.Errorf("failed to collect first response: %w", err)
+				err = fmt.Errorf("failed to collect first response: %w", err)
+				r.status.UpdateStatus(status.Degraded, err.Error())
```
Comment (bhapas) [inline x-pack/filebeat/input/httpjson/request.go:62]: Anyway this can be turned into an actionable message? What should user do in this case?

**Review by bhapas — COMMENTED** [review]
I like the way different input errors are being surfaced through input health reporting. I would like to add one general comment on those UpdateStatus messages going back to the UI - They seem to be too technical and related to internal input impl which are going back to the user. Can we make these error messages actionable to the users , meaning what do we expect the user to do in case they see this error on their UI. Is there anything that they can try to resolve the error apart from reaching support and an eventual SDH?

cc: @andrewkroh @cmacknz

File: x-pack/filebeat/input/httpjson/rate_limiter.go (hunk 3 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/rate_limiter.go:81]: `time.Duration` has is a `fmt.Stringer`.

File: x-pack/filebeat/input/httpjson/pagination.go (hunk 1 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/pagination.go:170]: All the possible errors that can be returned by the call above are relatively simple, and approximately maximally information dense. I do not think that this is "dumping" an error on the user.

File: x-pack/filebeat/input/httpjson/pagination.go (hunk 2 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/pagination.go:192]: Same here; all of the errors that are returned by the two calls above have been conditioned to return contextually meaninful errors that would help a person understand the cause of the issue.

File: x-pack/filebeat/input/httpjson/request.go (hunk 4 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/request.go:62]: Same here.

File: x-pack/filebeat/input/httpjson/pagination.go (hunk 1 above)
Comment (bhapas) [reply x-pack/filebeat/input/httpjson/pagination.go:170]: Can you give an example error possible here.. And what could be possible action for a non technical user installing an integration with httpjson input who sees the same error in the agent input health reporting.

Comment (efd6) [reply x-pack/filebeat/input/httpjson/pagination.go:170]: The call here reads all of the `(*http.Response).Body`, so any error that can be returned by that (except for `io.EOF` which is [filtered](https://pkg.go.dev/io#ReadAll) by `io.ReadAll`). These will be in this case …reads quickly through net/http…, mostly timeout errors or network failure errors.

Comment (bhapas) [reply x-pack/filebeat/input/httpjson/pagination.go:170]: Which means this is more like `Internal Error`. Should we have a new status saying `InternalError` or similar? The error will still be in logs for further action by support.

Comment (efd6) [reply x-pack/filebeat/input/httpjson/pagination.go:170]: > Which means this is more like `Internal Error`.

I don't think so. If the system can report immediately to the user, e.g. host unreachable, then that is something that they can potentially address without reaching out to support, unless we hide the information in the logs.

I'm reminded of "Everything should be made as simple as possible, but not simpler." We are approximately there. Even with the CEL eval error above, I'm not sure that the simpler rendering that would be possible of "failed evaluation" is any better than what is there now; there is no text that is going to be more informative than that without significant investigation, and the text that _is_ rendered _may_ be helpful. The context to the error would potentially be helpful, but that context is potentially very large, and the kibana rendering of errors is already broken (fixing that might improve matters) without adding more text.

File: CHANGELOG.next.asciidoc [hunk 5]
```diff
@@ -430,6 +430,7 @@ otherwise no tag is added. {issue}42208[42208] {pull}42403[42403]
 - Add support to the Active Directory entity analytics provider for device entities. {pull}44309[44309]
 - Add support for OPTIONS request to HTTP Endpoint input. {issue}43930[43930] {pull}44387[44387]
```
Comment (efd6) [inline CHANGELOG.next.asciidoc:432]:
```suggestion
```

File: x-pack/filebeat/input/httpjson/rate_limiter.go (hunk 3 above)
Comment (chrisberkhout) [inline x-pack/filebeat/input/httpjson/rate_limiter.go]: https://github.com/elastic/beats/issues/44282 suggests HTTP 429 rate limiting responses should be considered HEALTHY (Running). This wait may even happen before receiving a 429, right?

It would be a pity to see Degraded going on and off frequently in normal operation that is just consuming its request budget.

It would be nice to see Degraded if we get consecutive 429s.

File: x-pack/filebeat/input/httpjson/request.go [hunk 6]
```diff
@@ -204,6 +217,7 @@ func (r *requester) doRequest(ctx context.Context, trCtx *transformContext, publ
 	if isChainWithPageExpected {
 		n += r.processRemainingChainEvents(ctx, trCtx, publisher, initialResponse, chainIndex)
 	}
+	r.status.UpdateStatus(status.Running, "")
```
Comment (chrisberkhout) [inline x-pack/filebeat/input/httpjson/request.go:220]: This seems good to me.

https://github.com/elastic/beats/issues/44282 says:
> don't repeatedly send HEALTHY if the status is already HEALTHY

If that needs to be avoided, I would expect it to be done in `UpdateStatus`.

I think it's using the [BeatV2Manager implementation](https://github.com/elastic/beats/blob/cde01f1eeacdced731c828498175fc4e2fcfd38b/x-pack/libbeat/management/managerV2.go#L248-L256), which doesn't handle repeats like [this older implementation](https://github.com/elastic/beats/blob/cde01f1eeacdced731c828498175fc4e2fcfd38b/libbeat/management/management.go#L131-L139).

Is this all good as is?

File: x-pack/filebeat/input/httpjson/pagination.go (hunk 1 above)
Comment (bhapas) [reply x-pack/filebeat/input/httpjson/pagination.go:170]: True. This is not straight forward.

File: x-pack/filebeat/input/httpjson/request.go (hunk 6 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/request.go:220]: > https://github.com/elastic/beats/issues/44282 says:
>
>> don't repeatedly send HEALTHY if the status is already HEALTHY

That should be fixed in the status reporter. I'll add that in another PR. As a side note, there are far too many implementations of this interface and they are not discoverable.

File: x-pack/filebeat/input/httpjson/rate_limiter.go (hunk 3 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/rate_limiter.go]: I'll add that logic.

File: x-pack/filebeat/input/httpjson/request.go (hunk 6 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/request.go:220]: PR: #44716

**Review by bmorelli25 — APPROVED** [review]

File: x-pack/filebeat/input/httpjson/input.go [hunk 7]
```diff
@@ -175,8 +176,14 @@ func runWithMetrics(ctx v2.Context, cfg config, pub inputcursor.Publisher, crsr
 }
 
 func run(ctx v2.Context, cfg config, pub inputcursor.Publisher, crsr *inputcursor.Cursor, reg *monitoring.Registry) error {
-	log := ctx.Logger.With("input_url", cfg.Request.URL)
+	stat := ctx.StatusReporter
+	if stat == nil {
+		stat = noopReporter{}
+	}
+	stat.UpdateStatus(status.Starting, "")
+	stat.UpdateStatus(status.Configuring, "")
```
Comment (ShourieG) [inline x-pack/filebeat/input/httpjson/input.go:184]: Does two different statuses here make sense since they seem to basically happen instantaneously one after another ? Also there does not seem to be any points of possible failure between them, so can we not combine these 2 into something singular ?

File: x-pack/filebeat/input/httpjson/input.go [hunk 8]
```diff
@@ -196,12 +203,13 @@ func run(ctx v2.Context, cfg config, pub inputcursor.Publisher, crsr *inputcurso
 
 	metrics := newInputMetrics(reg)
 
-	client, err := newHTTPClient(stdCtx, cfg, log, reg)
+	client, err := newHTTPClient(stdCtx, cfg, stat, log, reg)
 	if err != nil {
+		ctx.UpdateStatus(status.Failed, "failed to create HTTP client: "+err.Error())
```
Comment (ShourieG) [inline x-pack/filebeat/input/httpjson/input.go]: why not `stat.UpdateStatus` here ? We seem to be assigning `stat := ctx.StatusReporter` before.

File: x-pack/filebeat/input/httpjson/input.go [hunk 9]
```diff
@@ -286,7 +300,7 @@ func newHTTPClient(ctx context.Context, config config, log *logp.Logger, reg *mo
 		}).StandardClient()
 	}
 
-	limiter := newRateLimiterFromConfig(config.Request.RateLimit, log)
+	limiter := newRateLimiterFromConfig(config.Request.RateLimit, stat, log)
 
 	if config.Auth.OAuth2.isEnabled() {
 		authClient, err := config.Auth.OAuth2.client(ctx, client)
```
Comment (ShourieG) [inline x-pack/filebeat/input/httpjson/input.go:306]: `stat.UpdateStatus(status.Stopped, "")` for OAuth2 client creation failure ?

File: x-pack/filebeat/input/httpjson/request.go [hunk 10]
```diff
@@ -222,12 +236,16 @@ func (rf *requestFactory) collectResponse(ctx context.Context, trCtx *transformC
...
+			r.status.UpdateStatus(status.Degraded, err.Error())
+			return nil, err
 		}
 	} else {
 		httpResp, err = r.client.do(ctx, req)
 		if err != nil {
-			return nil, fmt.Errorf("failed to execute http %s: %w", req.Method, err)
+			err = fmt.Errorf("failed to execute http %s: %w", req.Method, err)
+			r.status.UpdateStatus(status.Degraded, err.Error())
+			return nil, err
```
Comment (ShourieG) [inline x-pack/filebeat/input/httpjson/request.go]: So we are already doing an **UpdateStatus(Degraded)** for `httpResp, err = rf.collectResponse(ctx, trCtx, r)` everywhere, do we also require it in `collectResponse()` ?

File: x-pack/filebeat/input/httpjson/input.go [hunk 11]
```diff
@@ -196,12 +203,13 @@ func run(ctx v2.Context, cfg config, pub inputcursor.Publisher, crsr *inputcurso
...
 	if err != nil {
+		ctx.UpdateStatus(status.Failed, "failed to create HTTP client: "+err.Error())
 		return err
 	}
 
-	requestFactory, err := newRequestFactory(stdCtx, cfg, log, metrics, reg)
+	requestFactory, err := newRequestFactory(stdCtx, cfg, stat, log, metrics, reg)
 	if err != nil {
 		log.Errorf("Error while creating requestFactory: %v", err)
 		return err
```
Comment (ShourieG) [inline x-pack/filebeat/input/httpjson/input.go:216]: `stat.UpdateStatus(status.Failed, "failed to create requestFactory: "+err.Error())` makes sense here ?

File: x-pack/filebeat/input/httpjson/request.go [hunk 12]
```diff
@@ -308,14 +327,16 @@ func newRequestFactory(ctx context.Context, config config, log *logp.Logger, met
...
 		if ch.Step != nil {
-			ts, _ := newBasicTransformsFromConfig(registeredTransforms, ch.Step.Request.Transforms, requestNamespace, log)
+			ts, _ := newBasicTransformsFromConfig(registeredTransforms, ch.Step.Request.Transforms, requestNamespace, stat, log)
 			ch.Step.Auth = tryAssignAuth(config.Auth, ch.Step.Auth)
-			client, err := newChainHTTPClient(ctx, ch.Step.Auth, ch.Step.Request, log, reg)
+			client, err := newChainHTTPClient(ctx, ch.Step.Auth, ch.Step.Request, stat, log, reg)
 			if err != nil {
-				return nil, fmt.Errorf("failed in creating chain http client with error: %w", err)
+				err = fmt.Errorf("failed in creating chain http client with error: %w", err)
+				stat.UpdateStatus(status.Degraded, err.Error())
```
Comment (ShourieG) [inline x-pack/filebeat/input/httpjson/request.go]: Does **Degraded** make sense here ? Any error returned from `newRequestFactory()` would bubble upto to run() and exit. Also we could just keep the status update localised in run() since it's at the upper level.

File: x-pack/filebeat/input/httpjson/request.go [hunk 13]
```diff
@@ -334,15 +355,17 @@ func newRequestFactory(ctx context.Context, config config, log *logp.Logger, met
...
-			policy := newHTTPPolicy(evaluateResponse, ch.While.Until, log)
+			ts, _ := newBasicTransformsFromConfig(registeredTransforms, ch.While.Request.Transforms, requestNamespace, stat, log)
+			policy := newHTTPPolicy(evaluateResponse, ch.While.Until, stat, log)
 			ch.While.Auth = tryAssignAuth(config.Auth, ch.While.Auth)
-			client, err := newChainHTTPClient(ctx, ch.While.Auth, ch.While.Request, log, reg, policy)
+			client, err := newChainHTTPClient(ctx, ch.While.Auth, ch.While.Request, stat, log, reg, policy)
 			if err != nil {
-				return nil, fmt.Errorf("failed in creating chain http client with error: %w", err)
+				err = fmt.Errorf("failed in creating chain http client with error: %w", err)
+				stat.UpdateStatus(status.Degraded, err.Error())
```
Comment (ShourieG) [inline x-pack/filebeat/input/httpjson/request.go]: same comment as above.

File: x-pack/filebeat/input/httpjson/input.go (hunk 7 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/input.go:184]: They get written into the logs as well. I was wondering about this, but event with arbitrarily distant status changes, we cannot guarantee that a user will see a status notification in the UI, so this is qualitatively no different to any other sequence of state changes.

I personally think that the allowable changes in the state machine that the API represents should be documented in the interface so that this becomes less ambiguous. cc @pkoutsovasilis

File: x-pack/filebeat/input/httpjson/input.go (hunk 8 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/input.go]: We could. There is no real difference between the two.

File: x-pack/filebeat/input/httpjson/request.go (hunk 10 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/request.go]: I'll remove the status updates in `collectResponse` and add the missing caller update status call in `processChainPaginationEvents`.

File: x-pack/filebeat/input/httpjson/input.go (hunk 11 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/input.go:216]: Added

File: x-pack/filebeat/input/httpjson/request.go (hunk 12 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/request.go]: Good point. Removed here since it will be handled by `run`.

File: x-pack/filebeat/input/httpjson/request.go (hunk 13 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/request.go]: Removed

**Review by ShourieG — APPROVED** [review]
LGTM, I think the major points of contact have all been addressed, the rest are tests and methods propagating the health status object, so all looks good from my end.

File: x-pack/filebeat/input/httpjson/input.go (hunk 7 above)
Comment (pkoutsovasilis) [reply x-pack/filebeat/input/httpjson/input.go:184]: @efd6 👋 what is the ask exactly here? 🙂  It's been a while since I did the first implementation of status reporting for cel input so please bear with me. 

I would expect the logs, when running under elastic-agent, to always report `Starting` because of the following

https://github.com/elastic/elastic-agent/blob/d1bf1641e497837b08e7b0c7540ba6466ca90626/pkg/component/runtime/state.go#L222-L231

So you checked the logs and you didn't see it and that's why you added explicitly the `Starting` status before the `Configuring` one? 🙂

Comment (efd6) [reply x-pack/filebeat/input/httpjson/input.go:184]: @pkoutsovasilis No, I was thinking about the documentation. The state diagram (or some representation of it) would be helpful [somewhere here](https://github.com/elastic/beats/blob/6b6941eed4967419043c6fe9810f9f9ea2f042cc/libbeat/management/status/status.go#L18-L49), I guess with an indication that the status is already at Starting when the reporter is handed to the input.
