### PR TITLE
TCP input message size problem fix

### LINKED ISSUE #11966: TCP input message size problem, maybe a bug
When Filebeat uses `TCP input`, we can set the option `max_message_size` as maximum size in bytes of the message received over TCP. But, there is another option that limits the message size when Filebeat calls 

> scanner.Scan()

 to collect data: `MaxScanTokenSize`, the meaning of this option is the maximum size used to buffer a message. Filebeat does not override `MaxScanTokenSize` with `max_message_size`, which causes an error when the value of `max_message_size` we set is greater than `MaxScanTokenSize` and the length of our message is greater than `MaxScanTokenSize` and less than `max_message_size`. (position: `filebeat/inputsource/tcp`) . beats version: 6.5.4, but 7.0 also has this problem.

### PR DESCRIPTION
**Pull request by olimpias**
Scanner buffer size is set to `maxMessageSize`

Fixes #11966

### CODE REVIEW

**Comment by olimpias** [comment]
Could someone retrigger the travis? I m also using osx but I'm not having this type of issue.

**Comment by kvch** [comment]
jenkins test this

File: filebeat/inputsource/tcp/client.go [hunk 1]
```diff
@@ -73,7 +73,9 @@ func (c *client) handle() error {
 	buf := bufio.NewReader(r)
 	scanner := bufio.NewScanner(buf)
 	scanner.Split(c.splitFunc)
-
+	//16 is ratio of MaxScanTokenSize/startBufSize
+	buffer := make([]byte, c.maxMessageSize/16)
```
Comment (kvch) [inline filebeat/inputsource/tcp/client.go]: Why 16?

Comment (olimpias) [reply filebeat/inputsource/tcp/client.go]: Bufio scan uses default buffer size as 4096 and `MaxScanTokenSize` as 64 * 1024. I thought, when we set maxMessageSize to  `MaxScanTokenSize`, I should keep the ratio between maxScantoken size and buffer size. That is why I divided maxMessageSize to 16.

Comment (olimpias) [reply filebeat/inputsource/tcp/client.go]: @kvch I have a question for you. When I run in my local, I m not having any issue on unit tests. I have tried in my macos and Linux env. Both were fine. But for some reason, it is failing in travis and jenkins. Am I missing some configuration or config file? I m using `go test -race -cover ./...` under filebeat folder to run the unit testes.

Comment (olimpias) [reply filebeat/inputsource/tcp/client.go]: I could able to address the problem when I run with `make testsuite` :)

**Comment by kvch** [comment]
Failing tests on Travis are unrelated.
