### PR TITLE
Fix Filebeat autodiscover hints default settings

### LINKED ISSUE #12346: Filebeat autodiscover hints fail to create inputs
Filebeat autodiscover hints don't create valid inputs on 7.2 branch, possibly related to #12162 and/or #12272.

For confirmed bugs, please report:
- Version: 7.2 branch
- Operating System: Linux
- Steps to Reproduce: Use filebeat with hints-based autodiscover

This error appears continuously in filebeat log:
```
2019-05-29T15:40:46.071Z	ERROR	[autodiscover]	cfgfile/list.go:96	Error creating runner from config: each input must have at least one path defined
```

Tested configuration:
```
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
```

There is a workaround with the new possibility of adding a different default config (#12272), this works:
```
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.container.id}.log
```

### PR DESCRIPTION
**Pull request by exekias**
Default settings were broken after #12162, this code updates them to the
new input and makes sure that enable/disable logic works correctly.

Tests have been added to make sure this changes still work.

Fixes #12346

### CODE REVIEW

File: filebeat/autodiscover/builder/hints/config.go [hunk 1]
```diff
@@ -53,7 +51,16 @@ func (c *config) Unpack(from *common.Config) error {
...
+		fields := config.GetFields()
+		if len(fields) == 1 && fields[0] == "enabled" {
+			// only enabling/disabling default config:
+			if err := c.DefaultConfig.Merge(config); err != nil {
+				return nil
+			}
+		} else {
+			// full config provided, discard default
+			c.DefaultConfig = config
+		}
```
Comment (jsoriano) [inline filebeat/autodiscover/builder/hints/config.go]: What if a full config is provided, but also with the enabled setting set to true?
Would this work?
```
          hints.default_config:
            type: container
            enabled: true
            paths:
              - "/var/log/pods/${data.kubernetes.pod.uid}/${data.kubernetes.container.name}/*.log"
```

Comment (exekias) [reply filebeat/autodiscover/builder/hints/config.go]: It should, as I'm checking number of fields == 1

Comment (jsoriano) [reply filebeat/autodiscover/builder/hints/config.go]: Oh, right
