### PR TITLE
fix(filebeat/cel): avoid counting degraded runs as success

### LINKED ISSUE #48714: [Filebeat] CEL input `input.cel.periodic.program.run.success` metric counts evaluation failures as successes
**Version:** v9.3.0
**Operating System:** All
**Component:** x-pack/filebeat/input/cel

### Summary

The `input.cel.periodic.program.run.success` OTel metric incorrectly counts CEL program evaluation failures as successes, resulting in artificially inflated success rates (observed 100% success rate when failures are expected).

### Description

The metric documentation at [`doc.go L64`](https://github.com/elastic/beats/blob/0f4fc63162db855e0a1c5f0ec5894a8939e31d80/x-pack/filebeat/input/cel/doc.go#L64) states that `input.cel.periodic.program.run.success` measures "the number of times a program terminated without an error in a periodic run."

However, the implementation at [`input.go L617-619`](https://github.com/elastic/beats/blob/0f4fc63162db855e0a1c5f0ec5894a8939e31d80/x-pack/filebeat/input/cel/input.go#L617-L619) only checks whether event *publication* succeeded (`!hadPublicationError`), ignoring the `isDegraded` flag which tracks actual evaluation failures.

### Root Cause

When `evalWith` fails, the error is wrapped as an event at [`input.go L1342`](https://github.com/elastic/beats/blob/0f4fc63162db855e0a1c5f0ec5894a8939e31d80/x-pack/filebeat/input/cel/input.go#L1342). The error handling at [`input.go L323-345`](https://github.com/elastic/beats/blob/0f4fc63162db855e0a1c5f0ec5894a8939e31d80/x-pack/filebeat/input/cel/input.go#L323-L345) logs the error and sets `isDegraded = true`, but does not return early.

The error event then flows through to publication. If publication succeeds, `hadPublicationError` remains `false`, and `AddProgramSuccessExecution` is called—despite the evaluation having failed.

The same issue occurs when a single error object is returned by the CEL program, which sets `isDegraded = true` at [`input.go L490`](https://github.com/elastic/beats/blob/0f4fc63162db855e0a1c5f0ec5894a8939e31d80/x-pack/filebeat/input/cel/input.go#L490) but continues to publication.

### Steps to Reproduce

1. Configure a CEL input targeting an endpoint that returns intermittent errors (5xx, network timeouts, etc.)
2. Enable OTel metrics export
3. Compute success rate: `input.cel.periodic.program.run.success / input.cel.periodic.program.run.started`
4. Observe 100% success rate even when evaluation errors appear in logs

### Expected Behavior

The success rate should reflect actual CEL program execution success, excluding runs where `isDegraded` was set.

### Proposed Fix

The condition at [`input.go L617`](https://github.com/elastic/beats/blob/0f4fc63162db855e0a1c5f0ec5894a8939e31d80/x-pack/filebeat/input/cel/input.go#L617) should check both `!hadPublicationError && !isDegraded` to ensure success is only counted when the program executed without errors.

### PR DESCRIPTION
**Pull request by andrewkroh**
## Proposed commit message

```
The `input.cel.periodic.program.run.success` OTel metric was incorrectly
counting CEL program evaluation failures as successes, resulting in
artificially inflated success rates. This occurred because success was
recorded when event publication succeeded, ignoring the `isDegraded` flag
that tracks actual evaluation failures.

This change ensures program success is recorded only when publication
succeeds and no degraded execution occurred, and adds a regression test
covering error-event runs via the OTel exporter.

Fixes #48714
```

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works. Where relevant, I have used the [`stresstest.sh`](https://github.com/elastic/beats/blob/main/script/stresstest.sh) script to run them under stress conditions and race detector to verify their stability.
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent-changelog-tool/blob/main/docs/usage.md).

## Related issues

- Fixes #48714

### CODE REVIEW

File: x-pack/filebeat/input/cel/cel_metrics_test.go [hunk 1]
```diff
@@ -181,3 +187,141 @@ func TestOTELCELMetrics(t *testing.T) {
...
+// inMemoryExporter is a metrics exporter that stores metrics in memory for testing.
+type inMemoryExporter struct {
+	mu      sync.Mutex
+	metrics []metricdata.ResourceMetrics
+}
+
+func (e *inMemoryExporter) Export(_ context.Context, metrics *metricdata.ResourceMetrics) error {
+	e.mu.Lock()
+	defer e.mu.Unlock()
+	e.metrics = append(e.metrics, *metrics)
```
Comment (efd6) [inline x-pack/filebeat/input/cel/cel_metrics_test.go:201]:
```suggestion
	e.mu.Lock()
	e.metrics = append(e.metrics, *metrics)
	e.mu.Unlock()
```

File: x-pack/filebeat/input/cel/cel_metrics_test.go [hunk 2]
```diff
@@ -181,3 +187,141 @@ func TestOTELCELMetrics(t *testing.T) {
...
+	return nil
+}
+
+func (e *inMemoryExporter) Shutdown(_ context.Context) error   { return nil }
```
Comment (efd6) [inline x-pack/filebeat/input/cel/cel_metrics_test.go]:
```suggestion
func (e *inMemoryExporter) Shutdown(context.Context) error   { return nil }
```
(similar below)

File: x-pack/filebeat/input/cel/cel_metrics_test.go [hunk 3]
```diff
@@ -181,3 +187,141 @@ func TestOTELCELMetrics(t *testing.T) {
 		t.Errorf("celProcessingTime.Sum() = %v, want %v", inputMetrics.celProcessingTime.Sum(), totalCelDuration.Nanoseconds())
 	}
 }
+
+// inMemoryExporter is a metrics exporter that stores metrics in memory for testing.
+type inMemoryExporter struct {
+	mu      sync.Mutex
+	metrics []metricdata.ResourceMetrics
+}
+
```
Comment (efd6) [inline x-pack/filebeat/input/cel/cel_metrics_test.go:196]: Purely for documentation purposes…
```suggestion

var _ sdkmetric.Exporter = (*inMemoryExporter)(nil)

```

File: x-pack/filebeat/input/cel/cel_metrics_test.go [hunk 4]
```diff
@@ -181,3 +187,141 @@ func TestOTELCELMetrics(t *testing.T) {
...
+	select {
+	case <-eventPublished:
+		// Event published, the program ran and we can check metrics.
+	case <-time.After(30 * time.Second):
+		t.Fatal("Timed out waiting for event to be published")
+	}
+
+	// Cancel context to stop the input.
+	cancel()
+	<-errCh
```
Comment (efd6) [inline x-pack/filebeat/input/cel/cel_metrics_test.go:308]: Safe because there is always a value on exit, even if nil.

File: x-pack/filebeat/otel/exporter_factory.go [hunk 5]
```diff
@@ -102,6 +102,14 @@ func NewMetricsExporterFactory(exporterOptions MetricExporterOptions) *MetricsEx
 	}
 }
 
+// SetGlobalMetricsExporter sets the global metrics exporter.
+// This is used for testing.
+func (ef *MetricsExporterFactory) SetGlobalMetricsExporter(exporter sdkmetric.Exporter) {
+	ef.lock.Lock()
+	defer ef.lock.Unlock()
+	ef.globalMetricsExporter = exporter
```
Comment (efd6) [inline x-pack/filebeat/otel/exporter_factory.go:109]:
```suggestion
	ef.lock.Lock()
	ef.globalMetricsExporter = exporter
	ef.lock.Unlock()
```

**Review by efd6 — APPROVED** [review]
