### PR TITLE
Fix flaky FSWatch/FSScanner tests

### LINKED ISSUE #21489: filestream flaky tests
## Flaky Test

* **Test Name:** `TestFileWatchNewDeleteModified`, `TestFileScanner`
* **Link:** https://github.com/elastic/beats/blob/35a76dfe2c3caa19969fde4484792355077b58e2/filebeat/input/filestream/fswatch_test.go
* **Branch:** Reproduced locally, seen in these PRs:
  * https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-21444/3/
  * https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-21482/1/
* **Notes:**
  * Possibly related to #21444
  * Reproduced in linux with `while go test -count=1 ./filebeat/input/filestream/...; do true; done`.

### Stack Trace

```
--- FAIL: TestFileWatchNewDeleteModified (0.00s)
    --- FAIL: TestFileWatchNewDeleteModified/two_modified_files (0.00s)
        fswatch_test.go:210: 
            	Error Trace:	fswatch_test.go:210
            	Error:      	Not equal: 
            	            	expected: input_logfile.FSEvent{NewPath:"path1", OldPath:"path1", Op:0x2, Info:filestream.testFileInfo{path:"path1", size:10, time:time.Time{wall:0xbfd5f554f5d9c463, ext:5008327320, loc:(*time.Location)(0xf80b40)}}}
            	            	actual  : input_logfile.FSEvent{NewPath:"path2", OldPath:"path2", Op:0x2, Info:filestream.testFileInfo{path:"path2", size:10, time:time.Time{wall:0xbfd5f554f5d9c463, ext:5008327320, loc:(*time.Location)(0xf80b40)}}}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,7 +1,7 @@
            	            	 (input_logfile.FSEvent) {
            	            	- NewPath: (string) (len=5) "path1",
            	            	- OldPath: (string) (len=5) "path1",
            	            	+ NewPath: (string) (len=5) "path2",
            	            	+ OldPath: (string) (len=5) "path2",
            	            	  Op: (input_logfile.Operation) 2,
            	            	  Info: (filestream.testFileInfo) {
            	            	-  path: (string) (len=5) "path1",
            	            	+  path: (string) (len=5) "path2",
            	            	   size: (int64) 10,
            	Test:       	TestFileWatchNewDeleteModified/two_modified_files
        fswatch_test.go:210: 
            	Error Trace:	fswatch_test.go:210
            	Error:      	Not equal: 
            	            	expected: input_logfile.FSEvent{NewPath:"path2", OldPath:"path2", Op:0x2, Info:filestream.testFileInfo{path:"path2", size:10, time:time.Time{wall:0xbfd5f554f5d9c463, ext:5008327320, loc:(*time.Location)(0xf80b40)}}}
            	            	actual  : input_logfile.FSEvent{NewPath:"path1", OldPath:"path1", Op:0x2, Info:filestream.testFileInfo{path:"path1", size:10, time:time.Time{wall:0xbfd5f554f5d9c463, ext:5008327320, loc:(*time.Location)(0xf80b40)}}}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,7 +1,7 @@
            	            	 (input_logfile.FSEvent) {
            	            	- NewPath: (string) (len=5) "path2",
            	            	- OldPath: (string) (len=5) "path2",
            	            	+ NewPath: (string) (len=5) "path1",
            	            	+ OldPath: (string) (len=5) "path1",
            	            	  Op: (input_logfile.Operation) 2,
            	            	  Info: (filestream.testFileInfo) {
            	            	-  path: (string) (len=5) "path2",
            	            	+  path: (string) (len=5) "path1",
            	            	   size: (int64) 10,
            	Test:       	TestFileWatchNewDeleteModified/two_modified_files
FAIL
FAIL	github.com/elastic/beats/v7/filebeat/input/filestream	0.018s
```

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

Unit tests in for `fswatch.go` do not depend on the order of the returned events anymore.

## Why is it important?

The tests have been flaky.

## Checklist

~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

Closes #21489

### CODE REVIEW

File: filebeat/input/filestream/fswatch_test.go [hunk 1]
```diff
@@ -38,7 +38,6 @@ var (
 )
 
 func TestFileScanner(t *testing.T) {
-	t.Skip("Flaky test: https://github.com/elastic/beats/issues/21489")
```
Comment (jsoriano) [inline filebeat/input/filestream/fswatch_test.go:41]: Nit. Empty line.
```suggestion
```

File: filebeat/input/filestream/fswatch_test.go [hunk 2]
```diff
@@ -116,25 +115,7 @@ func removeFilesOfScannerTest(t *testing.T) {
...
-			if oneElem == otherElem {
-				mustFind--
-			}
-		}
-	}
-	return mustFind == 0
-}
-
 func TestFileWatchNewDeleteModified(t *testing.T) {
-	t.Skip("Flaky test: https://github.com/elastic/beats/issues/21489")
```
Comment (jsoriano) [inline filebeat/input/filestream/fswatch_test.go:119]: Nit. Empty line.
```suggestion
```

**Review by jsoriano — APPROVED** [review]
Thanks!
