### PR TITLE
[libbeat][aws] Fix AWS config initialization issue when using a role

### LINKED ISSUE #30999: [Filebeat] sqs ReceiveMessage failed: unknown endpoint, could not resolve endpoint
For confirmed bugs, please report:

- Version: Filebeat 8.1.1
- Operating System: macOS 12.3 (21E230) (arm64)
- Discuss Forum URL: N/A
- Steps to Reproduce: 

If I run Filebeat using the following command line:

```shell
-e
-v
-d
*
--strict.perms=false
--path.home
/Users/zmoog/code/projects/zmoog/beats/x-pack/filebeat
-E
cloud.id=<CLOUD_ID>
-E
cloud.api_key=<CLOUD_API_KEY>
-E
gc_percent=100
-E
setup.ilm.enabled=false
-E
setup.template.enabled=false
--modules
aws
-M
aws.s3access.enabled=true
-M
aws.s3access.input.credential_profile_name=elastic-agent
-M
aws.s3access.input.default_region=eu-west-1
-M
aws.s3access.input.queue_url=https://sqs.us-east-1.amazonaws.com/000123456789/elastic-cloudtrail-logs
-M
aws.s3access.input.role_arn=arn:aws:iam::000123456789:role/elastic-agent-role
```

## Expected Result

Filebeat retrieving messages from the SQS queue with the logs from CloudTrail.

## Actual Result

Filebeat can't successfully connect to SQS to retrieve the message with the CloudTrail logs, and I the following error message:

```json
{
    "log.level": "warn",
    "@timestamp": "2022-03-24T18:18:23.740+0100",
    "log.logger": "input.aws-s3.sqs",
    "log.origin": {
        "file.name": "awss3/sqs.go",
        "file.line": 66
    },
    "message": "SQS ReceiveMessage returned an error. Will retry after a short delay.",
    "service.name": "filebeat",
    "id": "1E95C04FA21E9A36",
    "queue_url": "https://sqs.us-east-1.amazonaws.com/000123456789/elastic-cloudtrail-logs",
    "error": {
        "message": "sqs ReceiveMessage failed: unknown endpoint, could not resolve endpoint, partition: \"aws\", service: \"sts\", region: \"\", known: [us-east-2-fips us-west-2-fips ca-central-1 eu-north-1 eu-west-2 eu-south-1 eu-west-1 eu-west-3 me-south-1 us-east-2 af-south-1 ap-northeast-1 ap-southeast-2 us-west-1-fips sa-east-1 us-west-1 us-west-2 ap-south-1 aws-global eu-central-1 us-east-1 us-east-1-fips ap-east-1 ap-northeast-2 ap-southeast-1]"
    },
    "ecs.version": "1.6.0"
}
```

## Root cause

The `AssumeRoleProvider` used to retrieve the temporary credentials receives an AWS SDK client without the region.

In details, during the input execution the AWS SDK client configuration is:

1. loaded from external files (for example, `~/.aws/config`),
2. passed to the `AssumeRoleProvider`,
3. and then updated with the region from the commant-line.

The update at step 3 happens too late in the flow, and the `AssumeRoleProvider` is still using a copy of the AWS configuration from the external files; when it calls the STS service to retrieve the temporary credentials, it fails due to the missing region.

### PR DESCRIPTION
**Pull request by zmoog**
## What does this PR do?

Set up the `AssumeRoleProvider` after the AWS region value from Filebeat settings is applied to the AWS SDK configuration.

## Why is it important?

When Filebeat uses a role ARN, it sets up `AssumeRoleProvider` before evaluating the region value from its settings.

If the AWS SDK configuration loaded from `~/.aws/config` does not contain a region, the error described in #30999 happens.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

Requirements:

- A SQS queue (in this example, `https://sqs.eu-west-1.amazonaws.com/000123456789/elastic-cloudtrail-logs`),
- an IAM role ARN (in this example, `arn:aws:iam::000123456789:role/elastic-agent-role`)

Configure the IAM Role as EC2 instance role with the following trust relationship:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

Also add some permission to the role to access SQS and S3 ("Amazon SQS Full Access" and "SQS Read only Access" are probably fine for a quick test).

Here's an example command line arguments for Filebeat:

```text
-e
-v
-d
*
--strict.perms=false
--path.home
/Users/zmoog/code/projects/zmoog/beats/x-pack/filebeat
-E
cloud.id=<CLOUD_ID>
-E
cloud.api_key=<CLOUD_API_KEY>
-E
gc_percent=100
-E
setup.ilm.enabled=false
-E
setup.template.enabled=false
--modules
aws
-M
aws.s3access.enabled=true
-M
aws.s3access.input.default_region=eu-west-1
-M
aws.s3access.input.queue_url=https://sqs.eu-west-1.amazonaws.com/000123456789/elastic-cloudtrail-logs
-M
aws.s3access.input.role_arn=arn:aws:iam::000123456789:role/elastic-agent-role
```

## Related issues

- Closes #30999

### CODE REVIEW

File: x-pack/libbeat/common/aws/credentials.go [hunk 1]
```diff
@@ -53,6 +54,13 @@ func InitializeAWSConfig(config ConfigAWS) (awssdk.Config, error) {
 			AWSConfig.Region = "us-east-1"
 		}
 	}
+
+	// Assume IAM role if iam_role config parameter is given
+	if config.RoleArn != "" {
+		logger.Debug("Switching credentials provider to AssumeRoleProvider")
```
Comment (aspacca) [inline x-pack/libbeat/common/aws/credentials.go:60]: nit: I would move the logging inside `switchToAssumeRoleProvider`, in case we will invoke the function somewhere else in the future

**Review by aspacca — APPROVED** [review]

**Comment by zmoog** [comment]
> Looks good to me! Could you add a changelog to it please? Thanks!

Oh! 🤦 

Thanks for the heads up! 🙇

**Comment by zmoog** [comment]
@kaiyan-sheng could you please double check the CHANGELOG entry is in the right place for this issue?

**Review by kaiyan-sheng — APPROVED** [review]
The changelog entry looks good to me! Thanks!
