### PR TITLE
harden pgsql parser

### LINKED ISSUE #565: packetbeat nightly151201180656 crashing psql
just updated to packetbeat 1.0.1 and checked if the issue #342 is now fixed in this version.

after running for about 10 minutes I got this error in the log file:

2015-12-18T23:07:11.921545+01:00 somehost /usr/bin/packetbeat[13560]: log.go:114: Stacktrace: /go/src/github.com/elastic/beats/libbeat/logp/log.go:114 (0x48c5c6)#012/usr/local/go/src/runtime/asm_amd64.s:437 (0x47d8fe)#012/usr/local/go/src/runtime/panic.go:423 (0x44d4f9)#012/usr/local/go/src/runtime/panic.go:18 (0x44ba39)#012/go/src/github.com/elastic/beats/packetbeat/protos/pgsql/pgsql.go:279 (0x512203)#012/go/src/github.com/elastic/beats/packetbeat/protos/pgsql/pgsql.go:610 (0x5146de)#012/go/src/github.com/elastic/beats/packetbeat/protos/pgsql/pgsql.go:707 (0x51515d)#012/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:87 (0x521093)#012/go/src/github.com/elastic/beats/packetbeat/protos/tcp/tcp.go:173 (0x5221cd)#012/go/src/github.com/elastic/beats/packetbeat/decoder/decoder.go:136 (0x6c8ad1)#012/go/src/github.com/elastic/beats/packetbeat/sniffer/sniffer.go:352 (0x5337a9)#012/go/src/github.com/elastic/beats/packetbeat/packetbeat.go:212 (0x422f2b)#012/usr/local/go/src/runtime/asm_amd64.s:1696 (0x47fc41)

seams to be still a problem here. 

I can do a capture again if needed!

### PR DESCRIPTION
**Pull request by urso**
Resolves #565

- Split parser loop in more fine-grained parser functions
- check pgsql strings really end with \0
- check pgsql message type
- limit data row/column/fields parsing buffer regarding to length field
- check row/column/fields parser consumed exactly `length` bytes
- do not skip some parsing errors, but report to kill stream

### CODE REVIEW

**Comment by urso** [comment]
also fix off-by one error in comparison leading up to panic when accessing buffer

**Comment by monicasarbu** [comment]
LGTM

File: packetbeat/protos/pgsql/parse.go [hunk 1]
```diff
@@ -0,0 +1,567 @@
...
+	switch s.parseState {
+	case PgsqlStartState:
+		ok, complete = pgsql.parseMessageStart(s)
+	case PgsqlGetDataState:
+		ok, complete = pgsql.parseMessageData(s)
+	default:
+		logp.Critical("Pgsql invalid parser state")
+	}
+
+	detailedf("parseMessage return: ok=%v, complete=%v, off=%v",
```
Comment (andrewkroh) [inline packetbeat/protos/pgsql/parse.go]: Did you intend for `parseMessage` to be `pgsqlMessageParser`?

**Comment by andrewkroh** [comment]
LGTM

File: packetbeat/protos/pgsql/parse.go (hunk 1 above)
Comment (urso) [inline packetbeat/protos/pgsql/parse.go]: actually no. it was for wrapping the switch statements, but I see what you mean. Will update the output.
