### PR TITLE
Abort delayed stop autodiscover events on docker restart

### LINKED ISSUE #12962: [filebeat] autodiscover remove input after corresponding service restart
Filebeat: 7.2.0 docker container
OS: Ubuntu 18.04.2 LTS
Parity: docker container

config filebeat.yml:
[filebeat.txt](https://github.com/elastic/beats/files/3405201/filebeat.txt)

1. started filebeat, parity events appeared in kibana
2. stopped/started parity: docker stop parity, docker start parity
3. on first attempt everything went fine, but on second attempt like 10 sec after parity started got number of messages like
2019-07-18T06:34:14.349Z	DEBUG	[autodiscover]	autodiscover/autodiscover.go:230	Got a stop event: map[config:[0xc0002290b0] container:{"id":"44e30ae98d153681ab77c05346100a78278c39b266e965ae8d0119891194b05a","image":{"name":"parity/parity:v2.4.5"},"labels":{"MAINTAINER":"Parity Technologies \u003cdevops-team@parity.io\u003e"},"name":"parity"} docker:{"container":{"id":"44e30ae98d153681ab77c05346100a78278c39b266e965ae8d0119891194b05a","image":"parity/parity:v2.4.5","labels":{"MAINTAINER":"Parity Technologies \u003cdevops-team@parity.io\u003e"},"name":"parity"}} host:172.17.0.3 id:44e30ae98d153681ab77c05346100a78278c39b266e965ae8d0119891194b05a meta:{"container":{"id":"44e30ae98d153681ab77c05346100a78278c39b266e965ae8d0119891194b05a","image":{"name":"parity/parity:v2.4.5"},"name":"parity"},"docker":{"container":{"labels":{"MAINTAINER":"Parity Technologies \u003cdevops-team@parity.io\u003e"}}}} port:8545 provider:7614a03c-df13-4169-8cbe-1afceb242df3 stop:true]

and filebeat stop processing parity logs despite the fact parity is running and healthy and its logs are ok

it looks like filebeat process stop event after parity start and think container is down

here is full log of this: 
[filebeat_parity.log](https://github.com/elastic/beats/files/3405204/filebeat_parity.log)

Steps to reproduce:
1. configure filebeat to autodiscover parity docker container
2. stop/start parity 
3. wait few seconds and sometime (very often) it stop processing parity container log after receiving stop event despite the fact parity started and running

### PR DESCRIPTION
**Pull request by jsoriano**
If a container is being restarted and `cleanup_timeout` is greater than
zero (as is by default), the stop event may arrive after the new start,
what stops resources started for the container. This change aborts the
scheduled stops if the same container is started during the grace
period.

`cleanup_timeout` was added on #10905, in 7.0, and disabled by default in 6.7.

Fix #12962.

### CODE REVIEW

**Comment by jsoriano** [comment]
Not sure about backporting this, as it slightly changes the behaviour.

File: libbeat/autodiscover/providers/docker/docker.go [hunk 1]
```diff
@@ -192,12 +210,51 @@ func (d *Provider) generateMetaDocker(event bus.Event) (*docker.Container, *dock
...
+	d.emitContainer(container, meta, "start")
+}
+
+func (d *Provider) scheduleStopContainer(event bus.Event) {
 	container, meta := d.generateMetaDocker(event)
 	if container == nil || meta == nil {
 		return
 	}
 
+	if d.config.CleanupTimeout <= 0 {
```
Comment (kaiyan-sheng) [inline libbeat/autodiscover/providers/docker/docker.go]: Can user set a CleanupTimeout to be <= 0? Maybe this can be in some kind of a Validate() function for config?

Comment (jsoriano) [reply libbeat/autodiscover/providers/docker/docker.go]: Added validate annotation for config, but I am going to keep the `<=` here because it feels safer :innocent:

**Comment by jsoriano** [comment]
jenkins, test this again

**Comment by exekias** [comment]
I saw this cool implementation just now, did you consider doing the same for the Kubernetes provider? it would solve the same issues?

**Comment by jsoriano** [comment]
> I saw this cool implementation just now, did you consider doing the same for the Kubernetes provider? it would solve the same issues?

I don't think that these issues can happen with Kubernetes. Stop events in Kubernetes are caused by destroyed pods, that cannot be restarted.
