### PR TITLE
[GCP] Log `ListTimeSeries` and `AggregatedList` requests duration

### LINKED ISSUE #40584: [GCP] Improve logging and exception handling
A pretty large customer observed performance issues with the GCP metrics when collecting data from a large number of projects. This issue can often result in metrics and/or metadata not being collected. When there's a failure due to API rate limiting or other issues related to scale, the team is unable to troubleshoot or debug it. It just fails passively.

The ask is to improve the logging message. This serves two purposes:

- The customer can set up monitoring alerts for occurrences of the error based on pattern matching.
- They can also use the message to inform project scoping decisions.

### PR DESCRIPTION
**Pull request by ghost**
## Overview

Adds a debug log to show the total time taken for all `ListTimeSeries` and `AggregatedList` requests. This is useful to understand if it takes more than the `period` defined in config.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #40584

### CODE REVIEW

File: x-pack/metricbeat/module/gcp/metrics/metrics_requester.go [hunk 1]
```diff
@@ -124,6 +124,13 @@ func (r *metricsRequester) Metrics(ctx context.Context, serviceName string, alig
 		}
 	}
 
+	start := time.Now()
+	r.logger.Debug("started ListTimeSeries requests")
```
Comment (kaiyan-sheng) [inline x-pack/metricbeat/module/gcp/metrics/metrics_requester.go:128]: do we still need this debug log here?

File: x-pack/metricbeat/module/gcp/metrics/compute/metadata.go [hunk 2]
```diff
@@ -188,6 +189,12 @@ func (s *metadataCollector) getComputeInstances(ctx context.Context) {
 
 	defer instancesClient.Close()
 
+	start := time.Now()
+	defer func() {
+		totalTime := time.Since(start)
+		s.logger.Debugf("total time taken for compute AggregatedList request: %s", totalTime)
```
Comment (shmsr) [inline x-pack/metricbeat/module/gcp/metrics/compute/metadata.go:195]:
```suggestion
		s.logger.Debugf("Total time taken for compute AggregatedList request: %s", totalTime)
```

File: x-pack/metricbeat/module/gcp/metrics/metrics_requester.go [hunk 3]
```diff
@@ -124,6 +124,12 @@ func (r *metricsRequester) Metrics(ctx context.Context, serviceName string, alig
 		}
 	}
 
+	start := time.Now()
+	defer func() {
+		totalTime := time.Since(start)
+		r.logger.Debugf("total time taken for all ListTimeSeries requests: %s config period: %s", totalTime, r.config.period.AsDuration())
```
Comment (shmsr) [inline x-pack/metricbeat/module/gcp/metrics/metrics_requester.go:130]:
```suggestion
		r.logger.Debugf("Total time taken for all ListTimeSeries requests: %s and config period: %s", totalTime, r.config.period.AsDuration())
```

**Review by shmsr — APPROVED** [review]

File: x-pack/metricbeat/module/gcp/metrics/compute/metadata.go [hunk 4]
```diff
@@ -188,6 +189,12 @@ func (s *metadataCollector) getComputeInstances(ctx context.Context) {
...
+	}()
```
Comment (harnish-elastic) [inline x-pack/metricbeat/module/gcp/metrics/compute/metadata.go:196]: I think we can do the below to reduce space complexity! WDYT?

```suggestion
	defer func() {
		s.logger.Debugf("total time taken for compute AggregatedList request: %s", time.Since(time.Now()))
	}()
```

File: x-pack/metricbeat/module/gcp/metrics/metrics_requester.go [hunk 5]
```diff
@@ -124,6 +124,12 @@ func (r *metricsRequester) Metrics(ctx context.Context, serviceName string, alig
...
+	}()
+
```
Comment (harnish-elastic) [inline x-pack/metricbeat/module/gcp/metrics/metrics_requester.go:132]: Same here,

```suggestion
	defer func() {
		s.logger.Debugf("total time taken for compute AggregatedList request: %s", time.Since(time.Now()))
	}()
```

**Review by harnish-elastic — CHANGES_REQUESTED** [review]

**Review by Linu-Elias — APPROVED** [review]

File: x-pack/metricbeat/module/gcp/metrics/compute/metadata.go [hunk 6]
```diff
@@ -188,6 +189,12 @@ func (s *metadataCollector) getComputeInstances(ctx context.Context) {
 
 	defer instancesClient.Close()
 
+	start := time.Now()
+	defer func() {
+		totalTime := time.Since(start)
+		s.logger.Debugf("Total time taken for compute AggregatedList request: %s", totalTime)
+	}()
```
Comment (harnish-elastic) [inline x-pack/metricbeat/module/gcp/metrics/compute/metadata.go:196]: We can reduce space complexity,

```suggestion
	defer func() {
		s.logger.Debugf("Total time taken for compute AggregatedList request: %s", time.Since(start))
	}()
```

File: x-pack/metricbeat/module/gcp/metrics/metrics_requester.go [hunk 7]
```diff
@@ -124,6 +124,12 @@ func (r *metricsRequester) Metrics(ctx context.Context, serviceName string, alig
 		}
 	}
 
+	start := time.Now()
+	defer func() {
+		totalTime := time.Since(start)
+		r.logger.Debugf("Total time taken for all ListTimeSeries requests: %s and config period: %s", totalTime, r.config.period.AsDuration())
+	}()
```
Comment (harnish-elastic) [inline x-pack/metricbeat/module/gcp/metrics/metrics_requester.go:131]: Same as above,

```suggestion
	defer func() {
		r.logger.Debugf("Total time taken for all ListTimeSeries requests: %s and config period: %s", time.Since(start), r.config.period.AsDuration())
	}()
```

**Review by harnish-crest-data — APPROVED** [review]
Given minor comments otherwise LGTM!

**Review by devamanv — APPROVED** [review]
