### PR TITLE
x-pack/filebeat/input/http_endpoint: decouple shared server lifetime from individual inputs

### LINKED ISSUE #47770: `http_endpoint` input mishandles run context cancellation
The `http_endpoint` input supports running distinct inputs on the same host/port, by maintaining an internal server table that is shared between different instances so new URL paths can be added to an existing http listener.

The implementation of this server sharing overrides the input context provided by Filebeat, by having all inputs with the same host and port wait only on the context cancellation of the input that started the http listener (while ignoring their own run context cancellation):
- If an `http_endpoint` input was not the one that created an http listener, then cancelling its run context and calling `Wait` to detect completed shutdown will deadlock.
- If an `http_endpoint` input _did_ create an http listener, then cancelling its run context will also shut down every other instance using the same host/port. (This is the less severe outcome in general, since an input that terminates unexpectedly can eventually be restarted, although in this case there is also an [independent bug](https://github.com/elastic/beats/issues/47769) in Filebeat itself that keeps that from happening.)

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message
```
x-pack/filebeat/input/http_endpoint: decouple shared server lifetime from individual inputs

The http_endpoint input lets multiple inputs share a single HTTP
listener on the same host:port. The server's context was derived
from the creator input's cancellation context, causing two bugs:

1. Joiner deadlock: when only a joiner's context was cancelled,
   its Run goroutine blocked forever on the server context because
   it never monitored its own cancellation signal.

2. Creator kills everyone: when the creator was cancelled, the
   shared server was closed, taking down all other inputs on the
   same port even though they were still wanted.

Replace http.ServeMux with a mutable mux that supports dynamic
handler removal. Give the server an independent context tied to
its own lifetime rather than any single input's. Both creator and
joiner now select on their own cancellation and the server context,
deregistering cleanly when stopped. The server shuts down only
when the last input deregisters or the listener returns an error.

Each handler receives a per-input context derived from that input's
cancellation, so in-flight ACK waits abort before the pipeline
client is closed during deregistration.
```

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works. Where relevant, I have used the [`stresstest.sh`](https://github.com/elastic/beats/blob/main/script/stresstest.sh) script to run them under stress conditions and race detector to verify their stability.
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent-changelog-tool/blob/main/docs/usage.md).

## Author's Checklist

- [ ]

## How to test this PR locally

Test locally by running `go test` in the http_endpoint package (with and without `-race`). To check change fixes the issue, the two tests, `TestJoinerDeregisterKeepsServer` and `TestPatternReregistration` can be copied onto tip; without the fix these are expected to fail:
```
--- FAIL: TestJoinerDeregisterKeepsServer (5.50s)
    input_test.go:758: joiner did not return in time
--- FAIL: TestCreatorDeregisterKeepsServer (5.51s)
    input_test.go:850: creator did not return in time
```

## Related issues

- Closes #47770

### CODE REVIEW

File: x-pack/filebeat/input/http_endpoint/input.go [hunk 1]
```diff
@@ -206,54 +219,89 @@ func (p *pool) serve(ctx v2.Context, e *httpEndpoint, pub func(beat.Event), metr
 			s.setErr(err)
 			s.cancel()
 			p.mu.Unlock()
+			handlerCancel()
 			ctx.UpdateStatus(status.Failed, err.Error())
 			return err
 		}
```
Comment (chrisberkhout) [inline x-pack/filebeat/input/http_endpoint/input.go:224]: If there's an attempt to register a duplicate path, that should be rejected, but it shouldn't take down the server, should it?

Also, the way it is, `s.cancel()` will make the server hang because `s.srv.Close()` isn't done.

File: x-pack/filebeat/input/http_endpoint/input.go [hunk 2]
```diff
@@ -357,6 +415,100 @@ func (s *server) getErr() error {
...
+func (m *mux) ServeHTTP(w http.ResponseWriter, r *http.Request) {
+	m.mu.RLock()
+	h := m.match(r.URL.Path)
+	m.mu.RUnlock()
+	if h == nil {
+		http.NotFound(w, r)
+		return
+	}
+	h.ServeHTTP(w, r)
+}
```
Comment (chrisberkhout) [inline x-pack/filebeat/input/http_endpoint/input.go:493]: Switching to the custom mux means we lose the [trailing-slash and request sanitizing redirects](https://pkg.go.dev/net/http#hdr-Trailing_slash_redirection-ServeMux).

To keep those, the new struct could add functionality but delegate to a mux from `http.NewServerMux()`.

File: x-pack/filebeat/input/http_endpoint/input_test.go [hunk 3]
```diff
@@ -693,3 +694,439 @@ func dump(r io.ReadCloser) []byte {
...
+		m.ServeHTTP(rec, httptest.NewRequest("GET", "/bar", nil))
+		if rec.Code != http.StatusNotFound {
+			t.Errorf("got status %d, want %d", rec.Code, http.StatusNotFound)
+		}
+	})
+}
+
+func newRecorder() *httptest.ResponseRecorder {
+	return httptest.NewRecorder()
+}
```
Comment (chrisberkhout) [inline x-pack/filebeat/input/http_endpoint/input_test.go]: nit: would be okay to use this directly.

File: x-pack/filebeat/input/http_endpoint/input.go [hunk 4]
```diff
@@ -206,54 +219,89 @@ func (p *pool) serve(ctx v2.Context, e *httpEndpoint, pub func(beat.Event), metr
...
+		// closed it). Wait for the listener goroutine to finish so
+		// s.err is set before we read it.
+		<-s.done
+		err := s.getErr()
+		if err != nil && !errors.Is(err, http.ErrServerClosed) {
+			ctx.UpdateStatus(status.Failed, "server exited unexpectedly: "+err.Error())
+		} else {
+			ctx.UpdateStatus(status.Stopping, "")
+		}
+		return err
```
Comment (chrisberkhout) [inline x-pack/filebeat/input/http_endpoint/input.go:291]: Firing the `handlerCancel` functions here would match the normal shutdown and let the tracer cleanup happen.

File: x-pack/filebeat/input/http_endpoint/input_test.go [hunk 5]
```diff
@@ -693,3 +694,439 @@ func dump(r io.ReadCloser) []byte {
...
+	wg.Add(2)
+	go func() {
+		defer wg.Done()
+		errA <- servers.serve(ctxA, cfgA, pub.Publish, metrics)
+	}()
+	go func() {
+		defer wg.Done()
+		errB <- servers.serve(ctxB, cfgB, pub.Publish, metrics)
+	}()
+	time.Sleep(500 * time.Millisecond)
```
Comment (chrisberkhout) [inline x-pack/filebeat/input/http_endpoint/input_test.go]: It's better to not have tests do sleeps. Making a helper to wait for the port to accept connections is easy enough, but in this case we also need both handlers to be registered.

I think ideally the implementation could be be modified to optionally close a channel when its ready. The tests would provide the channel. For other uses that don't, branch prediction would make the extra work negligible.

File: x-pack/filebeat/input/http_endpoint/input.go
Comment (chrisberkhout) [inline x-pack/filebeat/input/http_endpoint/input.go]: nit, also not in the diff: there's some duplication here. The address and listen parts could be written once, and the ln.Close+ServeTLS/Serve parts could be done directly where these are called.

File: x-pack/filebeat/input/http_endpoint/input.go (hunk 2 above)
Comment (efd6) [reply x-pack/filebeat/input/http_endpoint/input.go:493]: Delegation is not an option, but we can replicate the behaviour.

Comment (chrisberkhout) [reply x-pack/filebeat/input/http_endpoint/input.go:493]: I think delegation could be done with the wrapper being responsible for tracking handlers and building a new `http.ServeMux` on each change, and delegating to the current `http.ServeMux` for each request.

But replicating the behavior is simple and better :+1:

File: x-pack/filebeat/input/http_endpoint/input_test.go (hunk 5 above)
Comment (chrisberkhout) [reply x-pack/filebeat/input/http_endpoint/input_test.go]: Having a port readiness check without handler readiness checks could still be flaky.

The handler approach I had in mind is like this:

<details>
<summary>Expand for diff</summary>

```diff
diff --git a/x-pack/filebeat/input/http_endpoint/input.go b/x-pack/filebeat/input/http_endpoint/input.go
index 2283bd6b74..9c6f25c975 100644
--- a/x-pack/filebeat/input/http_endpoint/input.go
+++ b/x-pack/filebeat/input/http_endpoint/input.go
@@ -138,7 +138,7 @@ func (e *httpEndpoint) Run(ctx v2.Context, pipeline beat.Pipeline) error {
 	}
 	defer client.Close()
 
-	err = servers.serve(ctx, e, client.Publish, metrics)
+	err = servers.serve(ctx, e, client.Publish, metrics, nil)
 	if err != nil && !errors.Is(err, http.ErrServerClosed) {
 		return fmt.Errorf("unable to start server due to error: %w", err)
 	}
@@ -175,7 +175,11 @@ type pool struct {
 // blocking until the input's context is cancelled or the server dies. Each
 // input monitors its own context and deregisters cleanly when stopped; the
 // server lives as long as at least one input is registered.
-func (p *pool) serve(ctx v2.Context, e *httpEndpoint, pub func(beat.Event), metrics *inputMetrics) error {
+//
+// If ready is non-nil, it is closed once handler registration and server
+// setup is complete, but before the listener is guaranteed to be accepting
+// connections.
+func (p *pool) serve(ctx v2.Context, e *httpEndpoint, pub func(beat.Event), metrics *inputMetrics, ready chan<- struct{}) error {
 	log := ctx.Logger.With("address", e.addr)
 
 	u, err := url.Parse(e.config.URL)
@@ -271,6 +275,10 @@ func (p *pool) serve(ctx v2.Context, e *httpEndpoint, pub func(beat.Event), metr
 		}()
 	}
 
+	if ready != nil {
+		close(ready)
+	}
+
 	ctx.UpdateStatus(status.Running, "")
 
 	select {
diff --git a/x-pack/filebeat/input/http_endpoint/input_test.go b/x-pack/filebeat/input/http_endpoint/input_test.go
index 21dab6120b..6e9e1beaea 100644
--- a/x-pack/filebeat/input/http_endpoint/input_test.go
+++ b/x-pack/filebeat/input/http_endpoint/input_test.go
@@ -450,12 +450,15 @@ func TestServerPool(t *testing.T) {
 			ctx, cancel := newCtx("server_pool_test", test.name)
 			metrics := newInputMetrics(monitoring.NewRegistry(), logp.NewNopLogger())
 			var wg sync.WaitGroup
+			readyChans := make([]<-chan struct{}, 0, len(test.cfgs))
 			for _, cfg := range test.cfgs {
 				cfg := cfg
+				ready := make(chan struct{})
+				readyChans = append(readyChans, ready)
 				wg.Add(1)
 				go func() {
 					defer wg.Done()
-					err := servers.serve(ctx, cfg, pub.Publish, metrics)
+					err := servers.serve(ctx, cfg, pub.Publish, metrics, ready)
 					if err != http.ErrServerClosed {
 						select {
 						case fails <- err:
@@ -465,6 +468,9 @@ func TestServerPool(t *testing.T) {
 				}()
 			}
 			if test.wantErr == nil {
+				for _, ready := range readyChans {
+					<-ready
+				}
 				seen := make(map[string]bool)
 				for _, cfg := range test.cfgs {
 					if !seen[cfg.addr] {
@@ -524,7 +530,7 @@ func TestServerPool(t *testing.T) {
 				wg.Add(1)
 				go func() {
 					defer wg.Done()
-					err := servers.serve(ctx, cfg, pub.Publish, metrics)
+					err := servers.serve(ctx, cfg, pub.Publish, metrics, nil)
 					if err != nil && err != http.ErrServerClosed && test.wantErr == nil {
 						t.Errorf("failed to re-register %v: %v", cfg.addr, err)
 					}
@@ -586,7 +592,7 @@ func TestConcurrentExceedMaxInFlight(t *testing.T) {
 	wg.Add(1)
 	go func() {
 		defer wg.Done()
-		err := servers.serve(ctx, cfg, delayedPublish, metrics)
+		err := servers.serve(ctx, cfg, delayedPublish, metrics, nil)
 		if err != nil && err != http.ErrServerClosed {
 			t.Errorf("unexpected serve error: %v", err)
 		}
@@ -886,16 +892,20 @@ func TestJoinerDeregisterKeepsServer(t *testing.T) {
 	var wg sync.WaitGroup
 	errA := make(chan error, 1)
 	errB := make(chan error, 1)
+	readyA := make(chan struct{})
+	readyB := make(chan struct{})
 
 	wg.Add(2)
 	go func() {
 		defer wg.Done()
-		errA <- servers.serve(ctxA, cfgA, pub.Publish, metrics)
+		errA <- servers.serve(ctxA, cfgA, pub.Publish, metrics, readyA)
 	}()
 	go func() {
 		defer wg.Done()
-		errB <- servers.serve(ctxB, cfgB, pub.Publish, metrics)
+		errB <- servers.serve(ctxB, cfgB, pub.Publish, metrics, readyB)
 	}()
+	<-readyA
+	<-readyB
 	waitForServer(t, "127.0.0.1:9021", 5*time.Second)
 
 	// Stop B (joiner). A's server should stay alive.
@@ -978,16 +988,20 @@ func TestCreatorDeregisterKeepsServer(t *testing.T) {
 	var wg sync.WaitGroup
 	errA := make(chan error, 1)
 	errB := make(chan error, 1)
+	readyA := make(chan struct{})
+	readyB := make(chan struct{})
 
 	wg.Add(2)
 	go func() {
 		defer wg.Done()
-		errA <- servers.serve(ctxA, cfgA, pub.Publish, metrics)
+		errA <- servers.serve(ctxA, cfgA, pub.Publish, metrics, readyA)
 	}()
 	go func() {
 		defer wg.Done()
-		errB <- servers.serve(ctxB, cfgB, pub.Publish, metrics)
+		errB <- servers.serve(ctxB, cfgB, pub.Publish, metrics, readyB)
 	}()
+	<-readyA
+	<-readyB
 	waitForServer(t, "127.0.0.1:9022", 5*time.Second)
 
 	// Stop A (creator). B's server should stay alive.
@@ -1056,11 +1070,13 @@ func TestPatternReregistration(t *testing.T) {
 	ctx1, cancel1 := newCtx("test", "input-1")
 	var wg sync.WaitGroup
 	err1 := make(chan error, 1)
+	ready1 := make(chan struct{})
 	wg.Add(1)
 	go func() {
 		defer wg.Done()
-		err1 <- servers.serve(ctx1, cfg, pub.Publish, metrics)
+		err1 <- servers.serve(ctx1, cfg, pub.Publish, metrics, ready1)
 	}()
+	<-ready1
 	waitForServer(t, "127.0.0.1:9023", 5*time.Second)
 
 	resp, err := doRequest("", "http://127.0.0.1:9023/a/", "application/json", strings.NewReader(`{"x":1}`))
@@ -1087,11 +1103,13 @@ func TestPatternReregistration(t *testing.T) {
 	// Re-register same pattern on a new server.
 	ctx2, cancel2 := newCtx("test", "input-2")
 	err2 := make(chan error, 1)
+	ready2 := make(chan struct{})
 	wg.Add(1)
 	go func() {
 		defer wg.Done()
-		err2 <- servers.serve(ctx2, cfg, pub.Publish, metrics)
+		err2 <- servers.serve(ctx2, cfg, pub.Publish, metrics, ready2)
 	}()
+	<-ready2
 	waitForServer(t, "127.0.0.1:9023", 5*time.Second)
 
 	resp, err = doRequest("", "http://127.0.0.1:9023/a/", "application/json", strings.NewReader(`{"x":2}`))
@@ -1151,16 +1169,20 @@ func TestSimultaneousShutdown(t *testing.T) {
 	var wg sync.WaitGroup
 	errA := make(chan error, 1)
 	errB := make(chan error, 1)
+	readyA := make(chan struct{})
+	readyB := make(chan struct{})
 
 	wg.Add(2)
 	go func() {
 		defer wg.Done()
-		errA <- servers.serve(ctxA, cfgA, pub.Publish, metrics)
+		errA <- servers.serve(ctxA, cfgA, pub.Publish, metrics, readyA)
 	}()
 	go func() {
 		defer wg.Done()
-		errB <- servers.serve(ctxB, cfgB, pub.Publish, metrics)
+		errB <- servers.serve(ctxB, cfgB, pub.Publish, metrics, readyB)
 	}()
+	<-readyA
+	<-readyB
 	waitForServer(t, "127.0.0.1:9024", 5*time.Second)
 
 	// Cancel both at once.

```

</details>

The port check could be kept as is.

Alternatively, it could be moved into the `if ready != nil {` block, but that's probably moving a bit too much test logic to the implementation code.

The change on the implementation side could be avoided entirely, but I think it's not bad design for an implementation to have an opt-in way to get more visibility for testing purposes.

**Review by chrisberkhout — COMMENTED** [review]
The implementation looks good.

There's follow-up comment about potential flakiness on the earlier slow test comment.

**Comment by efd6** [comment]
The race there is vanishingly unlikely, but I've tightened it away.
