### PR TITLE
filebeat: make deep copy before notifying of config change

### LINKED ISSUE #42815: [Filebeat] Initial errors/failures observed when testing AbuseCH integration in Agentless
Please include configurations and logs if available.
[elastic-agent-diagnostics-2025-02-20T20-36-47Z-00.zip](https://github.com/user-attachments/files/18894500/elastic-agent-diagnostics-2025-02-20T20-36-47Z-00.zip)

For confirmed bugs, please report:
## Version: 
9.0.0-beta1

## Operating System: 
Agentless Deployment

## Steps to Reproduce: 
1. Instantiate a cloud security elastic stack instance on staging against v9.0.0
2. Install a modified `ti_abusech` integration with agentless enabled using `elastic-package` to the instance
3. Create/Install an AbuseCH integration in Agentless
4. After a few minutes when logs have been ingested, capture an agent diagnostic
5. note errors within agent logs
```
{"log.level":"error","@timestamp":"2025-02-20T20:05:47.646Z","message":"fatal error: concurrent map read and map write","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"cel-default","type":"cel"},"log":{"source":"cel-default"},"ecs.version":"1.6.0"}
```

Running it through the agent analyzer synposis looks like this:
```
2025-02-20T20:05:47.68Z: Component state changed cel-default (HEALTHY->FAILED): Failed: pid '68' exited with code '2'
2025-02-20T20:05:47.68Z: Unit state changed cel-default (STARTING->FAILED): Failed: pid '68' exited with code '2'
2025-02-20T20:05:47.68Z: Unit state changed cel-default-cel-ti_abusech-06203ce2-d5cc-43a6-83f6-d43252af6890 (STARTING->FAILED): Failed: pid '68' exited with code '2'
2025-02-20T20:06:44.379Z: Component state changed cel-default (HEALTHY->FAILED): Failed: pid '161' exited with code '2'
2025-02-20T20:06:44.379Z: Unit state changed cel-default-cel-ti_abusech-06203ce2-d5cc-43a6-83f6-d43252af6890 (STARTING->FAILED): Failed: pid '161' exited with code '2'
2025-02-20T20:06:44.379Z: Unit state changed cel-default (STARTING->FAILED): Failed: pid '161' exited with code '2'
2025-02-20T20:07:21.605Z: Component state changed cel-default (HEALTHY->FAILED): Failed: pid '226' exited with code '2'
2025-02-20T20:07:21.605Z: Unit state changed cel-default-cel-ti_abusech-06203ce2-d5cc-43a6-83f6-d43252af6890 (STARTING->FAILED): Failed: pid '226' exited with code '2'
2025-02-20T20:07:21.605Z: Unit state changed cel-default (STARTING->FAILED): Failed: pid '226' exited with code '2'
2025-02-20T20:09:12.822Z: Component state changed cel-default (HEALTHY->FAILED): Failed: pid '417' exited with code '2'
2025-02-20T20:09:12.823Z: Unit state changed cel-default-cel-ti_abusech-06203ce2-d5cc-43a6-83f6-d43252af6890 (STARTING->FAILED): Failed: pid '417' exited with code '2'
2025-02-20T20:09:12.823Z: Unit state changed cel-default (STARTING->FAILED): Failed: pid '417' exited with code '2'
2025-02-20T20:09:57.277Z: Component state changed cel-default (HEALTHY->FAILED): Failed: pid '491' exited with code '2'
```

and
```
2025-02-20T20:07:43.807Z: Error fetching data for metricset http.json: error making http request: Get "http://unix/inputs": dial unix /agentless/data/tmp/WDSbrgjXxHKnME7Z0CSyI1xJnirO2oRp.sock: connect: connection refused
2025-02-20T20:10:41.879Z: Error fetching data for metricset http.json: error making http request: Get "http://unix/stats": dial unix /agentless/data/tmp/WDSbrgjXxHKnME7Z0CSyI1xJnirO2oRp.sock: connect: connection refused
```

### PR DESCRIPTION
**Pull request by orestisfl**
## Proposed commit message

This prevents concurrent read & write map access.

Unrelated, but I've escalated one log line to `Info` to allow for easier verifying that ES store is being used from agent logs.

Fixes #42815

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ~~I have made corresponding changes to the documentation~~
- [x] ~~I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## How to test this PR locally

This is a blind spot: We have reproduced this on agentless deployments using abusech (see issue). However, I couldn't find a way to reproduce in an integration or unit test.

The closest is this hacky test:
```diff
diff --git a/libbeat/cmd/instance/beat_test.go b/libbeat/cmd/instance/beat_test.go
index ebfecf191c..8efea8eadd 100644
--- a/libbeat/cmd/instance/beat_test.go
+++ b/libbeat/cmd/instance/beat_test.go
@@ -15,14 +15,14 @@
 // specific language governing permissions and limitations
 // under the License.
 
-//go:build !integration
-
 package instance
 
 import (
 	"bytes"
+	es "github.com/elastic/beats/v7/libbeat/statestore/backend/es"
 	"io/ioutil"
 	"os"
+	"sync"
 	"testing"
 
 	"github.com/elastic/beats/v7/libbeat/cfgfile"
@@ -262,6 +262,72 @@ elasticsearch:
 		require.Same(t, c, m.cfg.Config)
 		require.False(t, b.isConnectionToOlderVersionAllowed(), "allow_older_versions flag should now be set to false")
 	})
+
+	t.Run("test tmp", func(t *testing.T) {
+		b, err := NewBeat("testbeat", "testidx", "0.9", false, nil)
+		require.NoError(t, err)
+
+		cfg := `
+elasticsearch:
+  hosts: ["https://127.0.0.1:9200"]
+  username: "elastic"
+  allow_older_versions: false
+`
+		c, err := config.NewConfigWithYAML([]byte(cfg), cfg)
+		require.NoError(t, err)
+		outCfg, err := c.Child("elasticsearch", -1)
+		require.NoError(t, err)
+
+		var wg sync.WaitGroup
+		defer wg.Wait()
+
+		const size = 100
+		wg.Add(size)
+		notifiers := make([]*es.Notifier, size)
+		for i := 0; i < size; i++ {
+			n := es.NewNotifier()
+			notifiers[i] = n
+			if i%2 == 0 {
+				n.Subscribe(func(c *config.C) {
+					defer wg.Done()
+					t.Log(c.FlattenedKeys())
+				})
+			} else {
+				n.Subscribe(func(c *config.C) {
+					defer wg.Done()
+					c.Merge(map[string]string{"test": "test"})
+				})
+			}
+		}
+
+		update := &reload.ConfigWithMeta{Config: c}
+		b.OutputConfigReloader = reload.ReloadableFunc(func(r *reload.ConfigWithMeta) error {
+			for i := 0; i < size; i++ {
+				outCfg := config.Namespace{}
+				if err := r.Config.Unpack(&outCfg); err != nil || outCfg.Name() != "elasticsearch" {
+					logp.Err("Failed to unpack the output config: %v", err)
+					return nil
+				}
+				c, err := config.NewConfigFrom(outCfg.Config())
+				require.NoError(t, err)
+
+				notifiers[i].Notify(c)
+			}
+			return nil
+		})
+		m := &outputReloaderMock{}
+		reloader := b.makeOutputReloader(m)
+
+		require.False(t, b.Config.Output.IsSet(), "the output should not be set yet")
+		require.True(t, b.isConnectionToOlderVersionAllowed(), "allow_older_versions flag should be true from 8.11")
+
+		err = reloader.Reload(update)
+		require.NoError(t, err)
+		require.True(t, b.Config.Output.IsSet(), "now the output should be set")
+		require.Equal(t, outCfg, b.Config.Output.Config())
+		require.Same(t, c, m.cfg.Config)
+		require.False(t, b.isConnectionToOlderVersionAllowed(), "allow_older_versions flag should now be set to false")
+	})
 }
 
 type outputReloaderMock struct {
```
however, that doesn't test any code to be commited

## Related issues

- Fixes 42815
- Related to https://github.com/elastic/beats/pull/41446

## Screenshots

Errors stop once the image with the fix is deployed
image

### CODE REVIEW

**Review by AndersonQ — APPROVED** [review]
LGTM. There is at least a test failing, but it seems some flakyness, you might retry it.

Btw, the test you added in the PR description, should it trigger the issue? I tried here and it passes with and without the change. So I don't really get the idea of that test.

**Comment by orestisfl** [comment]
> LGTM. There is at least a test failing, but it seems some flakyness, you might retry it. If you want, you can also open a flaky test issue, that would be the best so we can track the flakyness

https://github.com/elastic/beats/issues/42995

File: filebeat/beater/filebeat.go [hunk 1]
```diff
@@ -329,7 +329,15 @@ func (fb *Filebeat) Run(b *beat.Beat) error {
 				return nil
 			}
 
-			stateStore.notifier.Notify(outCfg.Config())
+			// Create a new config with the output configuration. Since r.Config is a pointer, a copy is required to
+			// avoid concurrent map read and write.
+			// See https://github.com/elastic/beats/issues/42815
+			configCopy, err := conf.NewConfigFrom(outCfg.Config())
```
Comment (mauri870) [inline filebeat/beater/filebeat.go:335]: a `(c *C) Clone() *C` would be quite useful here, I'm not sure what others think about it.

Comment (mauri870) [reply filebeat/beater/filebeat.go:335]: Needs changes in elastic-agent-libs, which is outside the scope of this change. We can leave it as is.
