### PR TITLE
[Heartbeat] Fix reload policy hash consistency, browser monitor cleanup and semaphore release

### LINKED ISSUE #34629: [Heartbeat] Private location policy update breaks scheduling
- Version: `>8.6.1 `
- Operating System: Docker

### Summary 

When running browser monitors through a private location policy, any updates to the policy prevents further iterations from running.
It also seems synthetic process are being intefered with when an agent update occurs, since running monitors at the time reach the timeout and terminate on error consistently:

```
{"log.level":"info","@timestamp":"2023-02-21T11:52:47.610Z","message":"Command has completed(-1): /usr/share/elastic-agent/.node/node/bin/elastic-synthetics elastic-synthetics --screenshots on --throttling 5d/3u/20l --inline --rich-events","component":{"binary":"heartbeat","dataset":"elastic_agent.heartbeat","id":"synthetics/browser-default","type":"synthetics/browser"},"log":{"source":"synthetics/browser-default"},"service.name":"heartbeat","ecs.version":"1.6.0","log.origin":{"file.line":276,"file.name":"synthexec/synthexec.go"},"ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-02-21T11:52:47.611Z","message":"Error executing command '/usr/share/elastic-agent/.node/node/bin/elastic-synthetics elastic-synthetics --screenshots on --throttling 5d/3u/20l --inline --rich-events' (-1): signal: killed","component":{"binary":"heartbeat","dataset":"elastic_agent.heartbeat","id":"synthetics/browser-default","type":"synthetics/browser"},"log":{"source":"synthetics/browser-default"},"service.name":"heartbeat","ecs.version":"1.6.0","log.origin":{"file.line":282,"file.name":"synthexec/synthexec.go"},"ecs.version":"1.6.0"}
```

When collecting `elastic-agent diagnostics`, it seems it's not able to serialize heartbeat integrations correctly:
```
root@bce4abe537ff:/usr/share/elastic-agent# elastic-agent diagnostics collect
[WARNING] Could not redact state.yaml due to unmarshalling error: yaml: invalid map key: map[interface {}]interface {}{"unitid":"synthetics/browser-default", "unittype":1}
Created diagnostics archive "elastic-agent-diagnostics-2023-02-21T12-52-40Z-00.zip"
```

### How to repro?

1. Create a private location policy with long running monitors, eg:
```js
step("Test", async () => {
    await page.goto("https://google.es");
    await page.waitForTimeout(600e3);
})
```

2. Enroll and agent and wait for monitors to start running:
```
{"log.level":"info","@timestamp":"2023-02-21T11:37:17.603Z","message":"Running command: /usr/share/elastic-
agent/.node/node/bin/elastic-synthetics elastic-synthetics --screenshots on...
```

3. Update any of the monitors to trigger a policy update.
4. Wait for next monitor iteration to happen.

### PR DESCRIPTION
**Pull request by emilioalvap**
## What does this PR do?

Closes #34629.

Addresses multiple issues with private location updates:
- Remove global fields from policy to prevent agent from stopping integrations which have not been updated.
- Detect browser monitor has ben cancelled by having a global (to the monitor) context .
- Fix an issue where job limit semaphore was not released after being acquired.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

1. Create a private location policy with multiple long-running browser monitors.
```js
step("Test", async () => {
    await page.goto("https://google.es");
    await page.waitForTimeout(600e3);
})
```
2. Enroll an agent in the policy.
3. On a different window, monitor processes executed by agent-heartbeat. This is an example to monitor a docker instance:
```zsh
$: docker exec -it -u root agent watch ps -aef
```
4.  Start updating monitors in Kibana (can be by enabling/disabling them) one by one and watch for agent reaction.
    - When a monitor that is running is disabled, heartbeat should kill the synthetics process and schedule the next job.
    - When a monitor that is **not** running is updated, heartbeat should not terminate any of the running jobs.
    - After multiple updates, heartbeat should still continue scheduling jobs since the job limit semaphore is updated even when a job is cancelled.

### CODE REVIEW

File: x-pack/heartbeat/monitors/browser/project.go [hunk 1]
```diff
@@ -27,12 +27,20 @@ type JourneyLister func(ctx context.Context, projectPath string, params mapstr.M
 type Project struct {
 	rawCfg     *config.C
 	projectCfg *Config
+	ctx        context.Context
+	cancel     context.CancelFunc
 }
 
 func NewProject(rawCfg *config.C) (*Project, error) {
+	// Global project context to cancell all jobs
```
Comment (emilioalvap) [inline x-pack/heartbeat/monitors/browser/project.go:35]:
```suggestion
	// Global project context to cancel all jobs
```

File: heartbeat/scheduler/schedjob.go [hunk 2]
```diff
@@ -62,7 +62,9 @@ func (sj *schedJob) run() (startedAt time.Time) {
 	sj.activeTasks.Inc()
 	if sj.jobLimitSem != nil {
 		err := sj.jobLimitSem.Acquire(sj.ctx, 1)
-		if err != nil {
+		if err == nil {
```
Comment (emilioalvap) [inline heartbeat/scheduler/schedjob.go:65]:
```suggestion
		// Defer release only if it acquired
		if err == nil {
```

**Comment by andrewvc** [comment]
LGTM, confirmed with local testing

**Review by andrewvc — APPROVED** [review]
