### PR TITLE
[Filebeat][httpjson] Fix date_cursor validation

### LINKED ISSUE #21748: Flaky test TestConfigOauth2Validation/date_cursor.date_format_will_fail_if_invalid
## Flaky Test

* **Test Name:** `TestConfigOauth2Validation/date_cursor.date_format_will_fail_if_invalid`
* **Link:** https://github.com/elastic/beats/blob/1824e849978f248f4e2da75ae51732963379714a/x-pack/filebeat/input/httpjson/config_test.go#L366
* **Branch:** Seen in several branches.

### Stack Trace

```
    config_test.go:428: Configuration validation failed. expecting "invalid configuration: date_format is not a valid date layout accessing 'date_cursor'" error but got %!q(<nil>)
```

### PR DESCRIPTION
**Pull request by marc-gr**
## What does this PR do?

It fixes the `httpjson` `date_cursor` config validation by using a fixed date for format validation.

## Why is it important?

Before `now` was used as the date to validate the format against, some formats (like the one used in the tests, which caused a new failing test recently https://github.com/elastic/beats/issues/21748) depending on the current date, would fail or not, causing flaky validation outputs.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

## Related issues

- Closes #21748

### CODE REVIEW

File: x-pack/filebeat/input/httpjson/config.go [hunk 1]
```diff
@@ -125,10 +125,16 @@ func (dc *dateCursorConfig) Validate() error {
 	if dc.DateFormat == "" {
 		return nil
 	}
-	now := time.Now().Format(dc.DateFormat)
-	if _, err := time.Parse(dc.DateFormat, now); err != nil {
+
+	const knownTimestamp = 1602601228 // 2020-10-13T15:00:28+00:00 RFC3339
+
+	// if we can't get back the same date from Format than from Parse
```
Comment (andrewkroh) [inline x-pack/filebeat/input/httpjson/config.go:131]: Is there a requirement for the format to include seconds? Without seconds in the format this test won't pass, right?

Comment (marc-gr) [reply x-pack/filebeat/input/httpjson/config.go]: True, and the same applies for any other element of the date since we can't know the intent of the format. I changed it to just check for parse errors instead, just as a sanity check. Since now it is against a known date we can trigger a parse error from the tests.

**Review by andrewkroh — APPROVED** [review]
LGTM. I think the docs may be missing some of the new cursor options for HTTP JSON.

**Comment by jsoriano** [comment]
Hey @marc-gr, thanks for fixing this. These tests seem to be flaky in 7.9 branch too, could you please backport the change to this branch?
