### PR TITLE
fix(libbeat): Prevent panic in replace processor for non-string values

### LINKED ISSUE #42308: [libbeat] - replace processor panics for non-string values
When the replace processor executes on a value that is not a string it will panic.

- `input panic with: interface conversion: interface {} is nil, not string`
- `input panic with: interface conversion: interface {} is float64, not string`

Full panic

```
input panic with: interface conversion: interface {} is float64, not string
goroutine 30 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).runSource.func1()
	github.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:144 +0x48
panic({0x10520cc20?, 0x14001971320?})
	runtime/panic.go:770 +0x124
github.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).replaceField(0x140015b5830, {0x14001058048, 0x18}, 0x14000b16780, {0x1085673a0, 0x1}, 0x1400196eb40)
	github.com/elastic/beats/v7/libbeat/processors/actions/replace.go:118 +0x204
github.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).Run(0x140015b5830, 0x1400196eb40)
	github.com/elastic/beats/v7/libbeat/processors/actions/replace.go:92 +0xa4
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run(0x140015b5920, 0x1400196eb40?)
	github.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:128 +0x84
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run(0x140015b58f0, 0x10560bae0?)
	github.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:128 +0x84
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).publish(0x1400087e070, {{0xc1d9d2c72bb18fe8, 0x65b9fb7, 0x10880fee0}, 0x0, 0x14001970b70, {0x0, 0x0}, 0x0})
	github.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:93 +0xec
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Publish(0x1092aff48?, {{0xc1d9d2c72bb18fe8, 0x65b9fb7, 0x10880fee0}, 0x0, 0x14001970b70, {0x0, 0x0}, 0x0})
	github.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:73 +0xf8
github.com/elastic/beats/v7/filebeat/beater.(*countingClient).Publish(0x14000f9acc0, {{0xc1d9d2c72bb18fe8, 0x65b9fb7, 0x10880fee0}, 0x0, 0x14001970b70, {0x0, 0x0}, 0x0})
	github.com/elastic/beats/v7/filebeat/beater/channels.go:136 +0xa0
github.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*cursorPublisher).forward(0x140015b5e30, {{0xc1d9d2c72bb18fe8, 0x65b9fb7, 0x10880fee0}, 0x0, 0x14001970b70, {0x0, 0x0}, 0x0})
	github.com/elastic/beats/v7/filebeat/input/v2/input-cursor/publish.go:81 +0x6c
github.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*cursorPublisher).Publish(0x105107660?, {{0xc1d9d2c72bb18fe8, 0x65b9fb7, 0x10880fee0}, 0x0, 0x14001970b70, {0x0, 0x0}, 0x0}, {0x0?, ...})
	github.com/elastic/beats/v7/filebeat/input/v2/input-cursor/publish.go:68 +0xe0
github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1()
	github.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:484 +0x1974
github.com/elastic/beats/v7/x-pack/filebeat/input/cel.periodically({0x105a56588, 0x1400003a9b0}, 0xdf8475800, 0x14001927210)
	github.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:547 +0x34
github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run({_}, {0x14000fa9240, {0x1400007e4e0, 0x1a}, {0x140018ac6a0, 0x10}, {{0x10421d913, 0x8}, {0x10421d913, 0x8}, ...}, ...}, ...)
	github.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:224 +0x6d4
github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.Run({_}, {0x14000fa9240, {0x1400007e4e0, 0x1a}, {0x140018ac6a0, 0x10}, {{0x10421d913, 0x8}, {0x10421d913, 0x8}, ...}, ...}, ...)
	github.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:119 +0x110
github.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).runSource(_, {0x14000fa9240, {0x1400007e4e0, 0x1a}, {0x140018ac6a0, 0x10}, {{0x10421d913, 0x8}, {0x10421d913, 0x8}, ...}, ...}, ...)
	github.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:168 +0x398
github.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).Run.func1()
	github.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:123 +0x178
github.com/elastic/go-concert/unison.(*MultiErrGroup).Go.func1()
	github.com/elastic/go-concert@v0.3.0/unison/multierrgroup.go:42 +0x6c
created by github.com/elastic/go-concert/unison.(*MultiErrGroup).Go in goroutine 100
	github.com/elastic/go-concert@v0.3.0/unison/multierrgroup.go:40 +0x84
```

For confirmed bugs, please report:
- Version: 8.15.2
- Operating System: n/a
- Steps to Reproduce: 

```
---

filebeat.inputs:
  - type: cel
    interval: 1m
    resource:
      url: NOT_USED
    redact:
      fields: ~
    keep_null: true
    program: |
      {
          'want_more': false,
          'events': [
              {"okta":{"profile":{"mobilePhone":null}}},
              {"okta":{"profile":{"mobilePhone":"555-555-55555"}}},
              {"okta":{"profile":{"mobilePhone":55555555555}}},
          ],
      }
    processors:
      - replace:
          fields:
            - field: okta.profile.mobilePhone
              pattern: '\d'
              replacement: X
          ignore_missing: true

output.console.pretty: true
```

### PR DESCRIPTION
**Pull request by orestisfl**
## Proposed commit message
The replace processor would panic with an interface conversion error if it attempted to process a field that contained a non-string value (e.g., nil, integer, float).

This commit adds a type check to safely validate that the field's value is a string before attempting the replacement operation. If the value is not a string, the processor will now return an error instead of panicking, making the processor more robust against malformed or unexpected data types.

Closes #42308

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

```sh
cfg=$(cat <<EOF
filebeat.inputs:
  - type: cel
    interval: 1m
    resource:
      url: NOT_USED
    redact:
      fields: ~
    keep_null: true
    program: |
      {
          'want_more': false,
          'events': [
              {"okta":{"profile":{"mobilePhone":null}}},
              {"okta":{"profile":{"mobilePhone":"555-555-55555"}}},
              {"okta":{"profile":{"mobilePhone":55555555555}}},
          ],
      }
    processors:
      - replace:
          fields:
            - field: okta.profile.mobilePhone
              pattern: '\d'
              replacement: X
          ignore_missing: true

output.console.pretty: true
EOF
)
x-pack/filebeat/filebeat -c <(echo "$cfg") -e
```

Before:
```json
{"log.level":"info","@timestamp":"2025-10-09T20:12:16.302+0200","log.logger":"input.cel.metric_registry","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/monitoring/inputmon.NewMetricsRegistry","file.name":"inputmon/input.go","file.line":182},"message":"registering","service.name":"filebeat","id":"448BD05089734E53","registry_id":"448BD05089734E53","input_id":"448BD05089734E53","input_type":"cel","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-10-09T20:12:16.302+0200","log.logger":"input.cel.metric_registry","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/monitoring/inputmon.NewMetricsRegistry","file.name":"inputmon/input.go","file.line":182},"message":"registering","service.name":"filebeat","id":"448BD05089734E53","input_source":"NOT_USED","registry_id":"448BD05089734E53::NOT_USED","input_id":"448BD05089734E53::NOT_USED","input_type":"cel","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-10-09T20:12:16.303+0200","log.logger":"input.cel","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1","file.name":"cel/input.go","file.line":241},"message":"process periodic request","service.name":"filebeat","id":"448BD05089734E53","input_source":"NOT_USED","input_url":"NOT_USED","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2025-10-09T20:12:16.303+0200","log.logger":"input.cel","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).runSource.func1","file.name":"input-cursor/input.go","file.line":173},"message":"Input crashed with: input panic with: interface conversion: interface {} is nil, not string\ngoroutine 106 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:26 +0x5e\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).runSource.func1()\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:172 +0x58\npanic({0x607a9fe183a0?, 0xc000c7f140?})\n\truntime/panic.go:783 +0x132\ngithub.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).replaceField(0xc000c11260, {0xc00099a1e0, 0x18}, 0xc00084d180, {0x607a9f5828e0, 0x1}, 0xc000c925c0)\n\tgithub.com/elastic/beats/v7/libbeat/processors/actions/replace.go:118 +0x26b\ngithub.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).Run(0xc000c11260, 0xc000c925c0)\n\tgithub.com/elastic/beats/v7/libbeat/processors/actions/replace.go:92 +0xb7\ngithub.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run(0xc000c11350, 0xc000c925c0?)\n\tgithub.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:127 +0x82\ngithub.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run(0xc000c11320, 0xc001105f01?)\n\tgithub.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:127 +0x82\ngithub.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).publish(0xc000425ab0, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0})\n\tgithub.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:93 +0x11a\ngithub.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Publish(0x607a9e661ec7?, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0})\n\tgithub.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:73 +0xfa\ngithub.com/elastic/beats/v7/filebeat/beater.(*countingClient).Publish(0xc000bdb4b8, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0})\n\tgithub.com/elastic/beats/v7/filebeat/beater/channels.go:133 +0xa7\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*cursorPublisher).forward(0xc000c113e0, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0})\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/publish.go:81 +0x75\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*cursorPublisher).Publish(0x607a9eb28aa8?, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0}, {0x0, ...})\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/publish.go:68 +0x109\ngithub.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1()\n\tgithub.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:514 +0x1ead\ngithub.com/elastic/beats/v7/x-pack/filebeat/input/cel.periodically({0x607aa093f508, 0xc000c00460}, 0xdf8475800, 0xc000c57658)\n\tgithub.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:580 +0x2e\ngithub.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run({_}, {0xc000bdb380, {0xc000735120, 0x1a}, {0xc001105850, 0x10}, {0x607a9eb246cb, 0x3}, {{0x607a9eb2e48b, 0x8}, ...}, ...}, ...)\n\tgithub.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:240 +0xa0b\ngithub.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.Run({_}, {0xc000bdb380, {0xc000735120, 0x1a}, {0xc001105850, 0x10}, {0x607a9eb246cb, 0x3}, {{0x607a9eb2e48b, 0x8}, ...}, ...}, ...)\n\tgithub.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:122 +0x132\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).runSource(_, {0xc000bdb380, {0xc000735120, 0x1a}, {0xc001105850, 0x10}, {0x607a9eb246cb, 0x3}, {{0x607a9eb2e48b, 0x8}, ...}, ...}, ...)\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:196 +0x479\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).Run.func1()\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:151 +0x2f2\ngithub.com/elastic/go-concert/unison.(*MultiErrGroup).Go.func1()\n\tgithub.com/elastic/go-concert@v0.3.0/unison/multierrgroup.go:42 +0x66\ncreated by github.com/elastic/go-concert/unison.(*MultiErrGroup).Go in goroutine 104\n\tgithub.com/elastic/go-concert@v0.3.0/unison/multierrgroup.go:40 +0x76\n","service.name":"filebeat","id":"448BD05089734E53","input_source":"NOT_USED","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-10-09T20:12:16.303+0200","log.logger":"input.cel.metric_registry","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/monitoring/inputmon.CancelMetricsRegistry","file.name":"inputmon/input.go","file.line":198},"message":"unregistering","service.name":"filebeat","id":"448BD05089734E53","input_source":"NOT_USED","registry_id":"448BD05089734E53::NOT_USED","input_id":"448BD05089734E53::NOT_USED","input_type":"cel","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2025-10-09T20:12:16.303+0200","log.logger":"input.cel","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/v2/compat.(*runner).Start.func1","file.name":"compat/compat.go","file.line":164},"message":"Input 'cel' failed with: input 448BD05089734E53 failed: input panic with: interface conversion: interface {} is nil, not string\ngoroutine 106 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:26 +0x5e\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).runSource.func1()\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:172 +0x58\npanic({0x607a9fe183a0?, 0xc000c7f140?})\n\truntime/panic.go:783 +0x132\ngithub.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).replaceField(0xc000c11260, {0xc00099a1e0, 0x18}, 0xc00084d180, {0x607a9f5828e0, 0x1}, 0xc000c925c0)\n\tgithub.com/elastic/beats/v7/libbeat/processors/actions/replace.go:118 +0x26b\ngithub.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).Run(0xc000c11260, 0xc000c925c0)\n\tgithub.com/elastic/beats/v7/libbeat/processors/actions/replace.go:92 +0xb7\ngithub.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run(0xc000c11350, 0xc000c925c0?)\n\tgithub.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:127 +0x82\ngithub.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run(0xc000c11320, 0xc001105f01?)\n\tgithub.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:127 +0x82\ngithub.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).publish(0xc000425ab0, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0})\n\tgithub.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:93 +0x11a\ngithub.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Publish(0x607a9e661ec7?, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0})\n\tgithub.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:73 +0xfa\ngithub.com/elastic/beats/v7/filebeat/beater.(*countingClient).Publish(0xc000bdb4b8, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0})\n\tgithub.com/elastic/beats/v7/filebeat/beater/channels.go:133 +0xa7\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*cursorPublisher).forward(0xc000c113e0, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0})\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/publish.go:81 +0x75\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*cursorPublisher).Publish(0x607a9eb28aa8?, {{0xc2321ca01217e269, 0x2474b34, 0x607aa457b340}, 0x0, 0xc000c7ede0, {0x0, 0x0}, 0x0}, {0x0, ...})\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/publish.go:68 +0x109\ngithub.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1()\n\tgithub.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:514 +0x1ead\ngithub.com/elastic/beats/v7/x-pack/filebeat/input/cel.periodically({0x607aa093f508, 0xc000c00460}, 0xdf8475800, 0xc000c57658)\n\tgithub.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:580 +0x2e\ngithub.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run({_}, {0xc000bdb380, {0xc000735120, 0x1a}, {0xc001105850, 0x10}, {0x607a9eb246cb, 0x3}, {{0x607a9eb2e48b, 0x8}, ...}, ...}, ...)\n\tgithub.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:240 +0xa0b\ngithub.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.Run({_}, {0xc000bdb380, {0xc000735120, 0x1a}, {0xc001105850, 0x10}, {0x607a9eb246cb, 0x3}, {{0x607a9eb2e48b, 0x8}, ...}, ...}, ...)\n\tgithub.com/elastic/beats/v7/x-pack/filebeat/input/cel/input.go:122 +0x132\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).runSource(_, {0xc000bdb380, {0xc000735120, 0x1a}, {0xc001105850, 0x10}, {0x607a9eb246cb, 0x3}, {{0x607a9eb2e48b, 0x8}, ...}, ...}, ...)\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:196 +0x479\ngithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor.(*managedInput).Run.func1()\n\tgithub.com/elastic/beats/v7/filebeat/input/v2/input-cursor/input.go:151 +0x2f2\ngithub.com/elastic/go-concert/unison.(*MultiErrGroup).Go.func1()\n\tgithub.com/elastic/go-concert@v0.3.0/unison/multierrgroup.go:42 +0x66\ncreated by github.com/elastic/go-concert/unison.(*MultiErrGroup).Go in goroutine 104\n\tgithub.com/elastic/go-concert@v0.3.0/unison/multierrgroup.go:40 +0x76\n","service.name":"filebeat","id":"448BD05089734E53","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-10-09T20:12:16.303+0200","log.logger":"input.cel.metric_registry","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/monitoring/inputmon.CancelMetricsRegistry","file.name":"inputmon/input.go","file.line":198},"message":"unregistering","service.name":"filebeat","id":"448BD05089734E53","registry_id":"448BD05089734E53","input_id":"448BD05089734E53","input_type":"cel","ecs.version":"1.6.0"}
```

After:
```json
{"log.level":"info","@timestamp":"2025-10-09T20:13:34.645+0200","log.logger":"input.cel.metric_registry","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/monitoring/inputmon.NewMetricsRegistry","file.name":"inputmon/input.go","file.line":182},"message":"registering","service.name":"filebeat","id":"448BD05089734E53","registry_id":"448BD05089734E53","input_id":"448BD05089734E53","input_type":"cel","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-10-09T20:13:34.645+0200","log.logger":"input.cel.metric_registry","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/monitoring/inputmon.NewMetricsRegistry","file.name":"inputmon/input.go","file.line":182},"message":"registering","service.name":"filebeat","id":"448BD05089734E53","input_source":"NOT_USED","registry_id":"448BD05089734E53::NOT_USED","input_id":"448BD05089734E53::NOT_USED","input_type":"cel","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-10-09T20:13:34.646+0200","log.logger":"input.cel","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1","file.name":"cel/input.go","file.line":241},"message":"process periodic request","service.name":"filebeat","id":"448BD05089734E53","input_source":"NOT_USED","input_url":"NOT_USED","ecs.version":"1.6.0"}
{
  "@timestamp": "2025-10-09T18:13:34.646Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "9.3.0"
  },
  "okta": {
    "profile": {
      "mobilePhone": null
    }
  },
  "input": {
    "type": "cel"
  },
  "error": {
    "message": "Failed to replace fields in processor: value for key: okta.profile.mobilePhone is not a string: <nil>"
  },
  "ecs": {
    "version": "8.0.0"
  },
  "host": {
    "name": "laptop"
  },
  "agent": {
    "name": "laptop",
    "type": "filebeat",
    "version": "9.3.0",
    "ephemeral_id": "c555ca4d-f5fd-48b3-b576-8ec6c875c6a3",
    "id": "edc593f4-2c3c-4d6a-b2dc-c10b6a80fbf0"
  }
}
{
  "@timestamp": "2025-10-09T18:13:34.646Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "9.3.0"
  },
  "agent": {
    "ephemeral_id": "c555ca4d-f5fd-48b3-b576-8ec6c875c6a3",
    "id": "edc593f4-2c3c-4d6a-b2dc-c10b6a80fbf0",
    "name": "laptop",
    "type": "filebeat",
    "version": "9.3.0"
  },
  "ecs": {
    "version": "8.0.0"
  },
  "host": {
    "name": "laptop"
  },
  "okta": {
    "profile": {
      "mobilePhone": "XXX-XXX-XXXXX"
    }
  },
  "input": {
    "type": "cel"
  }
}
{
  "@timestamp": "2025-10-09T18:13:34.646Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "9.3.0"
  },
  "error": {
    "message": "Failed to replace fields in processor: value for key: okta.profile.mobilePhone is not a string: 5.5555555555e+10"
  },
  "ecs": {
    "version": "8.0.0"
  },
  "host": {
    "name": "laptop"
  },
  "agent": {
    "ephemeral_id": "c555ca4d-f5fd-48b3-b576-8ec6c875c6a3",
    "id": "edc593f4-2c3c-4d6a-b2dc-c10b6a80fbf0",
    "name": "laptop",
    "type": "filebeat",
    "version": "9.3.0"
  },
  "okta": {
    "profile": {
      "mobilePhone": 5.5555555555e+10
    }
  },
  "input": {
    "type": "cel"
  }
}
```

## Related issues

- Closes https://github.com/elastic/beats/issues/42308

### CODE REVIEW

File: libbeat/processors/actions/replace.go [hunk 1]
```diff
@@ -115,10 +115,15 @@ func (f *replaceString) replaceField(field string, pattern *regexp.Regexp, repla
 		return fmt.Errorf("could not fetch value for key: %s, Error: %w", field, err)
 	}
 
-	updatedString := pattern.ReplaceAllString(currentValue.(string), replacement)
+	currentValueString, ok := currentValue.(string)
+	if !ok {
+		return fmt.Errorf("value for key: %s is not a string: %v", field, currentValue)
```
Comment (AndersonQ) [inline libbeat/processors/actions/replace.go]: [Suggestion]
I think the error could be a bit more clear. At first looking at the tests I was not sure what was what. Perhaps something like:


```suggestion
		return fmt.Errorf("key '%s' expected type string, but got %T with value %v", field, currentValue, currentValue)
```

**Comment by AndersonQ** [comment]
I left just a suggestion, feel free to take it or not.

**Comment by rdner** [comment]
This [documentation change](https://github.com/elastic/beats/pull/47016) broke the CI checks,  I'm currently figuring this out.
