### PR TITLE
[Journalbeat] Improve parsing of syslog.pid in journalbeat to strip the username when present

### LINKED ISSUE #15849: Journalbeat: parse entries for procs identified by PID and user
**Describe the enhancement:**
For some processes, the journal will identify the instance by process **and user**. Parsing these lines fails currently. The enhancement would be about handling the user part; for instance ignoring it.

Tried on master (33f7112037d).

**Describe a specific use case for the enhancement or feature:**
Example of such a line:
`Jan 26 22:11:06 muppet vncserver-x11[573,root]: AgentInitCheck: agent comms failure`

Logged failure:
`{"type":"mapper_parsing_exception","reason":"failed to parse field [syslog.pid] of type [long] in document with id 'nlqj428BvnVtNfGL9fwO'. Preview of field'
s value: '573,root'","caused_by":{"type":"illegal_argument_exception","reason":"For input string: \"573,root\""}`

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes an issue where syslog.pid is reported as an integer followed by the username.

## Why is it important?

In some cases journald reports the syslog.pid with the user that started the pid following it. This strips the username and only sends the pid in the event.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- ~~[ ] I have made corresponding change to the default configuration files~~
- [X] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

I was unable to reproduce this issue with journald on Ubuntu 19.10. But was able to reproduce the failure using a unit test, so best way to test is just by running the unit tests.

## Related issues

- Closes #15849

### CODE REVIEW

File: journalbeat/reader/journal.go [hunk 1]
```diff
@@ -288,8 +288,14 @@ func (r *Reader) convertNamedField(fc fieldConversion, value string) interface{}
 	if fc.isInteger {
 		v, err := strconv.ParseInt(value, 10, 64)
 		if err != nil {
-			r.logger.Debugf("Failed to convert field: %s \"%v\" to int: %v", fc.name, value, err)
-			return value
+			// Failed to convert to integer, try to strip ',\w*' from the
+			// end of of the value and try again.
+			s := strings.Split(value, ",")
```
Comment (ycombinator) [inline journalbeat/reader/journal.go]: Any reason not to try and run this split always before the `strconv.ParseInt(...)`, so basically right inside the `if fc.isInteger` block? Are you doing this lazily as a performance optimization?

Comment (blakerouse) [reply journalbeat/reader/journal.go]: Yes doing it lazily for performance because even on my system I could not get this case to occur. I don't know ifs its an older systemd or what that appends the username to the PID. I thought it would be best to only do the split in the case that converting to an integer failed.

Comment (ycombinator) [reply journalbeat/reader/journal.go]: Cool, makes sense then. Maybe add a comment here about that?

Comment (blakerouse) [reply journalbeat/reader/journal.go]: Okay will add a comment.

**Comment by blakerouse** [comment]
@jsoriano Being new to this I assume you mean marking `syslog.pid` as not being an integer? Then change the mapping that is passed to elasticsearch?

What about the chance (if it exists) that some events have `syslog.pid` without the username appended then some following events do have username append? Honestly thats probably not even a possibility, just a thought.

**Comment by jsoriano** [comment]
> @jsoriano Being new to this I assume you mean marking `syslog.pid` as not being an integer? Then change the mapping that is passed to elasticsearch?
> 

Yes, I mean to configure the field as keyword, and not parse it in beats, just send is as is given by journald.

> What about the chance (if it exists) that some events have `syslog.pid` without the username appended then some following events do have username append? Honestly thats probably not even a possibility, just a thought.

This shouldn't be a problem, if the mapping is configured as keyword everything send in this field would be stored as keyword, even if they are normal numeric pids.
