### PR TITLE
Do not update event in parallel

### LINKED ISSUE #1410: Filebeat Log Collection Halting : ERR Fail to convert the event to JSON: reflect: call of reflect.Value.IsNil on zero Value
I am seeing that log collection is halting periodically when sending Datastax Enterprise Cassandra logs to logstash. Issue was originally seen in version 1.1.0 and 1.2.1 with this error:

> ERR Fail to convert the event to JSON: reflect: call of reflect.Value.IsNil on zero Value

Installing a 5.0.0 nightly build didn't resolve the problem or provide any additional output. Indeed, the service tends to die silently...

 Additional information and background can be found here (https://discuss.elastic.co/t/filebeat-1-1-0-log-collection-halting/47130/15)

- Version: 1.1.0, 1.2.1, 5.0.0 (currently using 5.0.0 nightly)
- Operating System: Ubuntu 14.04
- Steps to Reproduce: I have attached a sample sanitised log from the server and filebeat shipper.

[sample_logs.tar.gz](https://github.com/elastic/beats/files/223388/sample_logs.tar.gz)

### PR DESCRIPTION
**Pull request by urso**
logstash output used to add metadata to an event. With potentially having
multiple outputs configured this is some bad practice. Instead the logstash
output plugin will add '@metadata' to the event when encoding and only if
'@metadata' is not already present in event

Resolves #1410

### CODE REVIEW

File: libbeat/outputs/logstash/protocol.go [hunk 1]
```diff
@@ -285,6 +295,49 @@ func (p *protocol) serializeDataFrame(
...
+
+		buf.WriteString(`"@metadata":{"type":`)
+		tmp, err := json.Marshal(typ)
+		if err != nil {
+			return nil, err
+		}
+		buf.Write(tmp)
+
+		buf.WriteString(`,"beat":`)
+		buf.Write(beat)
```
Comment (tsg) [inline libbeat/outputs/logstash/protocol.go]: Shouldn't this also be passed through `json.Marshal` or otherwise escaped? We have to be careful with JSON injection if we're doing this by hand.

File: libbeat/outputs/logstash/protocol.go [hunk 2]
```diff
@@ -285,6 +295,49 @@ func (p *protocol) serializeDataFrame(
 	return nil
 }
 
+func serializeEvent(event common.MapStr, beat []byte) ([]byte, error) {
```
Comment (tsg) [inline libbeat/outputs/logstash/protocol.go]: Some unit tests for this function would be good.

**Comment by tsg** [comment]
This looks to me like a good solution for the bug we have now, I guess long term we'll have a proper Event type and we can add locking or immutability to it, right?

File: libbeat/outputs/logstash/protocol.go (hunk 1 above)
Comment (urso) [inline libbeat/outputs/logstash/protocol.go]: json.Marshal is done [line 62](https://github.com/elastic/beats/pull/1428/files#diff-27db9f6cc38fb36ab0f23d9a8664c6bbR62). Didn't want to marshal over and over again

File: libbeat/outputs/logstash/protocol.go (hunk 2 above)
Comment (urso) [inline libbeat/outputs/logstash/protocol.go]: it's tested (block-box testing sendEvents), as we've got some logstash unit tests forwarding events via sendEvents with server part decoding json messages for validation.

**Comment by tsg** [comment]
LGTM. Can you add a changelog item?

**Comment by urso** [comment]
> I guess long term we'll have a proper Event type and we can add locking or immutability to it, right?

That's exactly what I have had in mind when doing the fix.
