### PR TITLE
S3 input: try to detect GZIPped objects

### LINKED ISSUE #18283: Decompress S3 files without ".gz" extension
**Describe a specific use case for the enhancement or feature:**
Some files automatically generated by AWS are gzip compressed but named without a `.gz` extension. 

**Describe the enhancement:**
Support for gzipped files in S3 input has been introduced in 7.5.0 (https://github.com/elastic/beats/pull/13980) but as it relies on the `.gz` extension of the files, the S3 input doesn't decompress the files with a `.gz` extension. The request is to be able to decompress independently of the naming.

### LINKED ISSUE #18696: Fails processing jsonl+gzip when using S3 Input plugin
When using Filebeat with the [S3 input plugin](https://www.elastic.co/guide/en/beats/filebeat/7.7/filebeat-input-s3.html) (beta), Filebeat will fail processing files that contain JSON lines and are GZIP-compressed. This is the output format of [AWS GuardDuty with S3 export enabled](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_exportfindings.html), which means that Filebeat is unable to process logs as written by AWS GuardDuty. The issue occurs specifically when the object contains JSON lines, is GZIP-compressed, and has the following metadata on the S3 object:

```
Content-Encoding: gzip
Content-Type: application/json
```

_Note: I originally posted this as a [thread on the discussion forum](https://discuss.elastic.co/t/gzip-invalid-header-with-filebeat-s3-input-and-guardduty-logs/233626), but now I am confident it is a bug in Filebeat so I'm creating an issue here._

### Actual Results

When using Filebeat 7.6.2 I get these error messages. In this case it seems that Filebeat is attempting to decompress the GZIP stream, but the stream has already been automatically decompressed by the transport in aws-sdk-go based on the object Metadata.

```
2020-05-20T22:42:27.973Z	ERROR	[s3]	s3/input.go:447	gzip.NewReader failed: gzip: invalid header
2020-05-20T22:42:27.974Z	ERROR	[s3]	s3/input.go:386	createEventsFromS3Info failed for AWSLogs/123456789123/GuardDuty/ca-central-1/2020/05/15/659b5608-a71c-3b42-8979-f851e61d9098.jsonl.gz: gzip.NewReader failed: gzip: invalid header
```

And when using Filebeat 7.7.0 I get slightly different error messages. This seems to stem from the fact that GuardDuty is incorrectly assigning the `application/json` MIME type to files that actually contain JSON lines/newline-delimited JSON.

```
2020-05-21T19:41:28.122Z	ERROR	[s3]	s3/input.go:434	expand_event_list_from_field parameter is missing in config for application/json content-type file
2020-05-21T19:41:28.122Z	ERROR	[s3]	s3/input.go:387	createEventsFromS3Info failed for AWSLogs/123456789123/GuardDuty/ca-central-1/2020/05/14/8b55ad23-fe05-3f4e-8ff7-d61365cb2ad3.jsonl.gz: expand_event_list_from_field parameter is missing in config for application/json content-type file
```

### Expected Results

Presumably GuardDuty should be using `application/json-seq` or `application/jsonstream` or `application/x-json-stream` or `application/x-ndjson` or `application/x-jsonlines` but there doesn't seem to be a standard there. So it seems like Filebeat should be able to handle cases where JSON-lines/NDJson files are saved with the `application/json` MIME type, perhaps with automatic detection or a configuration override.

The S3 input plugin should also be careful to not attempt GZIP decompression twice (once automatic in the transport layer, and once explicitly in the s3 input code).

### Additional information

- I'm testing Filebeat inside a docker container based on [ubuntu:18.04](https://hub.docker.com/layers/ubuntu/library/ubuntu/18.04/images/sha256-15db3648b32edb76770d0e0297099ce7bfb5f14a3eeaa19d252c82dcb6d155d9?context=explore)
- I'm downloading Filebeat directly from artifacts.elastic.co and using the dpkg install method

### My Filebeat Configuration

```
filebeat.inputs:
  - type: s3
    enabled: true
    queue_url: https://sqs.ca-central-1.amazonaws.com/123456789123/awslogs-guardduty

processors:
  - decode_json_fields:
      fields: ['message']
      target: "aws.guardduty"
  - timestamp:
      field: "aws.guardduty.updatedAt"
      layouts:
        - '2006-01-02T15:04:05Z'
  - add_fields:
      target: "event"
      fields:
        dataset: "aws.guardduty"
```

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR enhances the S3 input to try harder to automatically detect GZIPped objects.

## Why is it important?

Sometimes objects returned by the S3 API are gzipped but don't come with proper headers indicating their gzipped nature. So we try different ways to auto-detect if the object is gzipped.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~I have made corresponding changes to the documentation~
- [ ] ~I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

1. Follow the instructions in https://www.elastic.co/blog/getting-aws-logs-from-s3-using-filebeat-and-the-elastic-stack to setup an S3 bucket and SQS queue and configure Filebeat. When configuring Filebeat use the `console` output for easy debugging.

2. Create a sample log file.
   ```
   cat <<EOF >sample.log
   May 28 03:00:52 Shaunaks-MacBook-Pro-Work syslogd[119]: ASL Sender Statistics
   May 28 03:03:29 Shaunaks-MacBook-Pro-Work VTDecoderXPCService[57953]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
   May 28 03:03:29 Shaunaks-MacBook-Pro-Work VTDecoderXPCService[57953]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
   May 28 03:03:53 Shaunaks-MacBook-Pro-Work VTDecoderXPCService[57953]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated; set a breakpoint on _dispatch_bug_deprecated to debug
   May 28 03:03:53 Shaunaks-MacBook-Pro-Work VTDecoderXPCService[57953]: DEPRECATED USE in libdispatch client: Changing target queue hierarchy after xpc connection was activated; set a breakpoint on _dispatch_bug_deprecated to debug
   EOF
   ```

3. Gzip the sample log file while keeping the original around.
   ```
   gzip --keep sample.log
   ```

4. Make a copy of the gzipped file, but remove the gzip extension to try and "fool" our S3 input.
   ```
   cp sample.log.gz sneaky.log
   ```

5. Start Filebeat
   ```
   filebeat -e
   ```

6. One by one, upload the 3 files to your S3 bucket. After each upload, check the Filebeat log to make sure there are no errors. Also make sure that the S3 input successfully generates the expected events.

## Related issues

- Resolves elastic/beats#18283
- Resolves elastic/beats#18696

### CODE REVIEW

File: x-pack/filebeat/input/s3/input.go [hunk 1]
```diff
@@ -667,3 +674,22 @@ func (c *s3Context) Inc() {
...
 }
+
+// isStreamGzipped determines whether the given stream of bytes (encapsulated in a buffered reader)
+// represents gzipped content or not. A buffered reader is used so the function can peek into the byte
+// stream without consuming it. This makes it convenient for code executed after this function call
+// to consume the stream if it wants.
+func isStreamGzipped(r *bufio.Reader) (bool, error) {
+	// Why 512? See https://godoc.org/net/http#DetectContentType
+	buf, err := r.Peek(512)
+	if err != nil && err != io.EOF {
```
Comment (jsoriano) [inline x-pack/filebeat/input/s3/input.go:685]: Nit. Do we have a test case that covers reading an empty object (or smaller than 512 bytes)? If not, could you please add one?

File: x-pack/filebeat/input/s3/input.go [hunk 2]
```diff
@@ -436,7 +437,25 @@ func (p *s3Input) createEventsFromS3Info(svc s3iface.ClientAPI, info s3Info, s3C
...
+	}
+
+	if isS3ObjGzipped {
+		gzipReader, err := gzip.NewReader(reader)
+		if err != nil {
+			err = errors.Wrap(err, "gzip.NewReader failed")
+			p.logger.Error(err)
+			return err
+		}
+		reader = bufio.NewReader(gzipReader)
```
Comment (jsoriano) [inline x-pack/filebeat/input/s3/input.go:454]: Is there a reason to instantiate another reader? Could we use the `gzipReader` directly?
```suggestion
		reader = gzipReader
```

File: x-pack/filebeat/input/s3/input.go [hunk 3]
```diff
@@ -436,7 +437,25 @@ func (p *s3Input) createEventsFromS3Info(svc s3iface.ClientAPI, info s3Info, s3C
...
+		gzipReader.Close()
```
Comment (jsoriano) [inline x-pack/filebeat/input/s3/input.go:455]: Interesting that `reader` as `bufio.NewReader(gzipReader)` continues working after closing the `gzipReader`.

File: x-pack/filebeat/input/s3/input.go (hunk 1 above)
Comment (ycombinator) [reply x-pack/filebeat/input/s3/input.go:685]: Added test case for empty byte slice.

File: x-pack/filebeat/input/s3/input.go (hunk 2 above)
Comment (ycombinator) [reply x-pack/filebeat/input/s3/input.go:454]: Yeah, I want this too. I tried it already but it doesn't work because further down we use `reader.ReadString`, which is a method on `bufio.Reader`. And `gzipReader` does not have that method. So we need to wrap it back in `bufio.Reader`.

File: x-pack/filebeat/input/s3/input.go (hunk 3 above)
Comment (ycombinator) [reply x-pack/filebeat/input/s3/input.go:455]: Yes, I found this interesting as well. 🤔
