### PR TITLE
[filebeat] Fix httpjson page number initialization and docs

### LINKED ISSUE #32364: Filebeat google_workspace module uses same 'startTime' url param forever when response is paginated.
Our Google workspace logs ingestion project suffers serous performance issue using Filebeat 8.3.2  google_workspace module to pull Google Drive logs into our ElasticSearch cluster.

Our Drive logs has a run rate of 500-600 events/s and can easily get paginated since Google Reports API has max page size of 1000. Once paginated, the requests for the intervals thereafter all use the same startTime because of the recent [pagination bug fix](https://github.com/elastic/beats/commit/5f8c74bd9998dc4bcc490da6d1db074b8ea8f453). 

Captured all the 'RawQuery' of all requests in Debug mode:
`"@timestamp":"2022-07-14T19:20:00.707Z","log.logger":"input.httpjson-cursor","log.origin":{"file.name":"httpjson/response.go","file.line":125},"message":"last received page: &httpjson.response{page:30, url:url.URL{Scheme:\"https\", Opaque:\"\", User:(*url.Userinfo)(nil), Host:\"www.googleapis.com\", Path:\"/admin/reports/v1/activity/users/all/applications/drive\", RawPath:\"\", ForceQuery:false, RawQuery:\"pageToken=A%3A1657826281668000%3A2353685954652725353%3A777491262838%3AC040ao83r&startTime=2022-07-14T19%3A17%3A57Z\"
`
`
"@timestamp":"2022-07-14T19:20:01.932Z","log.logger":"input.httpjson-cursor","log.origin":{"file.name":"httpjson/response.go","file.line":125},"message":"last received page: &httpjson.response{page:31, url:url.URL{Scheme:\"https\", Opaque:\"\", User:(*url.Userinfo)(nil), Host:\"www.googleapis.com\", Path:\"/admin/reports/v1/activity/users/all/applications/drive\", RawPath:\"\", ForceQuery:false, RawQuery:\"pageToken=A%3A1657826279219000%3A2727150340132871807%3A777491262838%3AC040ao83r&startTime=2022-07-14T19%3A17%3A57Z\"
`
`
"@timestamp":"2022-07-14T19:20:03.322Z","log.logger":"input.httpjson-cursor","log.origin":{"file.name":"httpjson/response.go","file.line":125},"message":"last received page: &httpjson.response{page:1, url:url.URL{Scheme:\"https\", Opaque:\"\", User:(*url.Userinfo)(nil), Host:\"www.googleapis.com\", Path:\"/admin/reports/v1/activity/users/all/applications/drive\", RawPath:\"\", ForceQuery:false, RawQuery:\"startTime=2022-07-14T19%3A17%3A57Z\"
`
`
"@timestamp":"2022-07-14T19:20:04.843Z","log.logger":"input.httpjson-cursor","log.origin":{"file.name":"httpjson/response.go","file.line":125},"message":"last received page: &httpjson.response{page:2, url:url.URL{Scheme:\"https\", Opaque:\"\", User:(*url.Userinfo)(nil), Host:\"www.googleapis.com\", Path:\"/admin/reports/v1/activity/users/all/applications/drive\", RawPath:\"\", ForceQuery:false, RawQuery:\"pageToken=A%3A1657826389459000%3A1568710631165131716%3A777491262838%3AC040ao83r&startTime=2022-07-14T19%3A17%3A57Z\"
`
`
"@timestamp":"2022-07-14T19:20:06.274Z","log.logger":"input.httpjson-cursor","log.origin":{"file.name":"httpjson/response.go","file.line":125},"message":"last received page: &httpjson.response{page:3, url:url.URL{Scheme:\"https\", Opaque:\"\", User:(*url.Userinfo)(nil), Host:\"www.googleapis.com\", Path:\"/admin/reports/v1/activity/users/all/applications/drive\", RawPath:\"\", ForceQuery:false, RawQuery:\"pageToken=A%3A1657826388178000%3A230205037924502923%3A777491262838%3AC040ao83r&startTime=2022-07-14T19%3A17%3A57Z\"
`
`
"@timestamp":"2022-07-14T19:20:07.872Z","log.logger":"input.httpjson-cursor","log.origin":{"file.name":"httpjson/response.go","file.line":125},"message":"last received page: &httpjson.response{page:4, url:url.URL{Scheme:\"https\", Opaque:\"\", User:(*url.Userinfo)(nil), Host:\"www.googleapis.com\", Path:\"/admin/reports/v1/activity/users/all/applications/drive\", RawPath:\"\", ForceQuery:false, RawQuery:\"pageToken=A%3A1657826387074000%3A4365156032944158179%3A777491262838%3AC040ao83r&startTime=2022-07-14T19%3A17%3A57Z\"
`
....................
`
"@timestamp":"2022-07-14T19:20:27.079Z","log.logger":"input.httpjson-cursor","log.origin":{"file.name":"httpjson/response.go","file.line":125},"message":"last received page: &httpjson.response{page:16, url:url.URL{Scheme:\"https\", Opaque:\"\", User:(*url.Userinfo)(nil), Host:\"www.googleapis.com\", Path:\"/admin/reports/v1/activity/users/all/applications/drive\", RawPath:\"\", ForceQuery:false, RawQuery:\"pageToken=A%3A1657826369819000%3A-8103844197655827342%3A777491262838%3AC040ao83r&startTime=2022-07-14T19%3A17%3A57Z\"
`

### PR DESCRIPTION
**Pull request by marc-gr**
## What does this PR do?

Fixes an issue with the page number of `.last_response.page` that was making page numbers inconsistent between intervals.

First interval page numbers would go as: 0,1,2..., Subsequent calls would always be 1,2,3... instead, which caused issues when using conditions based on this value for some configurations.

This sets the defined behavior as 0,1,2... for all intervals and documents it as such, since is the assumption that was made in all affected integrations.

## Why is it important?

Fixes pagination errors for Google Workspace integrations and others.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #32364

### CODE REVIEW

File: x-pack/filebeat/input/httpjson/pagination.go [hunk 1]
```diff
@@ -103,6 +103,7 @@ func (p *pagination) newPageIterator(stdCtx context.Context, trCtx *transformCon
 		trCtx:      trCtx,
 		resp:       resp,
 		isFirst:    true,
+		n:          -1, // the first page needs to be 0 for every interval
```
Comment (efd6) [inline x-pack/filebeat/input/httpjson/pagination.go:106]: If `pageIterator.getPage` is rearranged slightly, this comment and assignment becomes unnecessary
```
func (iter *pageIterator) getPage() (*response, error) {
	bodyBytes, err := ioutil.ReadAll(iter.resp.Body)
	if err != nil {
		return nil, err
	}
	iter.resp.Body.Close()

	var r response
	r.header = iter.resp.Header
	r.url = *iter.resp.Request.URL
	r.page = iter.n
	iter.n++

	if len(bodyBytes) > 0 {
		if iter.pagination.decoder != nil {
			err = iter.pagination.decoder(bodyBytes, &r)
		} else {
			err = decode(iter.resp.Header.Get("Content-Type"), bodyBytes, &r)
		}
		if err != nil {
			return nil, err
		}
	}

	return &r, nil
}
```

Comment (marc-gr) [reply x-pack/filebeat/input/httpjson/pagination.go:106]: Good catch, will do that but will keep the comment in the function just in case someone moves a couple of lines in the future.
