### PR TITLE
Fix BeatV2Manager to configure inputs and set log level

### LINKED ISSUE #34046: Add support for dynamically changing the Beat log level when running under agent
Follow up from an agent change in https://github.com/elastic/elastic-agent/issues/1896 where the agent will no longer restart itself or the Beats it manages when the agent log level is changed.

The Beats should respect the log level requested in the UnitExpected gRPC message by changing their log level dynamically when an update is received: https://github.com/elastic/elastic-agent-client/blob/15881a8e64ef95f32f688c933319cd926ff500b0/elastic-agent-client.proto#L280

```protobuf
    // Log level of the unit.
    UnitLogLevel log_level = 6;
```

The ability to dynamically change the level of the `logp` logger used in Beats was added in https://github.com/elastic/elastic-agent-libs/pull/82, with a new atomic `SetLevel` function that can be used for this purpose as it was in agent.

### LINKED ISSUE #34048: BeatsV2Manager will restart the entire beat with the removal of a single unit
Looking at the `BeatV2Manager` it is clear that it is not implemented correctly to work with the way the Elastic Agent V2 protocol is designed. It has a concept of a main unit which is not something that the Elastic Agent defines, it is possible at any time for a unit to be added or removed during the life of the component.

Example of this is say when running to monitor kubernetes containers:

1. Component starts with 1 unit for container A
2. Another unit is added for container B
3. Container A is stopped and its removed so unit from 1 is removed

### LINKED ISSUE #34093: Injection of global processors broke the correct ordering of processors
The following change in https://github.com/elastic/beats/commit/6c13c6764e30cacb4aa89432d6256fed94a87632 broke the expected ordering of processors for the Elastic Agent filestream monitoring. Which completely broke the Elastic Agents ability to ship logs https://github.com/elastic/elastic-agent/issues/1975.

The order of processors is important and the following should be enforced:

1. stream processors
2. agentInfo processors
3. global processors
4. stream specific processors

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

This refactors the `BeatV2Manager` so it works correctly with the Elastic Agent V2 model of components/units. The log level is now computed from the defined units and the log level is now updated with the `logp.SetLevel`. 

## Why is it important?

Previously the `BeatV2Manager` would act incorrectly when a new unit was added to the beat from the Elastic Agent replacing the already existing unit with the new unit configuration instead of merging the configuration so the beat would operating with 2 inputs. Previous the log level was not set-able by the V2 control protocol, this now works.
## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #34048 
- Closes #34046
- Closes https://github.com/elastic/elastic-agent/issues/1913
- Closes #34093

### CODE REVIEW

**Comment by blakerouse** [comment]
I am keeping this in draft at the moment unit I get the unit tests done, but I have tested this manually with the Elastic Agent and it is working correctly. Still not comfortable to land this until I have unit tests to cover it. Wanted to get it up early so others can review and test it as well.

File: x-pack/libbeat/management/managerV2.go [hunk 1]
```diff
@@ -311,95 +359,162 @@ func (cm *BeatV2Manager) stopBeat() {
...
+	payload := cm.payload
+	cm.mx.Unlock()
+	for _, unit := range units {
+		state, _, _ := unit.Expected()
+		if state == client.UnitStateStopped {
+			// unit is expected to be stopping (don't adjust the state as the state is now managed by the
+			// `reload` method and will be marked stopped in that code path)
+			continue
+		}
+		err := unit.UpdateState(status, message, payload)
```
Comment (fearful-symmetry) [inline x-pack/libbeat/management/managerV2.go:452]: Not sure why we're manually looping over the unit `UpdateState` here? Is there a reason why we just can't call the global `UpdateStatus` or something similar?

File: x-pack/libbeat/management/managerV2.go [hunk 2]
```diff
@@ -251,38 +315,29 @@ func (cm *BeatV2Manager) unitListen() {
...
-					go cm.handleUnitReload(change.Unit)
-				}
-
+				cm.modifyUnit(change.Unit)
+				cm.triggerReload()
 			case client.UnitChangedRemoved:
-				cm.logger.Debugf("Got unit removed: %s", change.Unit.ID())
 				cm.deleteUnit(change.Unit)
 			}
+		case <-cm.reloadCh:
```
Comment (fearful-symmetry) [inline x-pack/libbeat/management/managerV2.go:333]: I'm not sure why there's so much logic involved in the reloading process? `triggerReload()` and `reload()` are both only called in this for block, it might just be simpler to call `reload()` in a goroutine or something? Also, why is `reload()` getting its own map of the units and not just using `cm.units`?

**Review by fearful-symmetry — COMMENTED** [review]
A few comments/questions, mostly about overall logic.

File: x-pack/libbeat/management/managerV2.go [hunk 3]
```diff
@@ -23,6 +25,11 @@ import (
 	"github.com/elastic/elastic-agent-libs/logp"
 )
 
+type unitKey struct {
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:28]: Only the Type/ID is unique. It is possible that an input ID and and output ID could be the same. I will add a comment.

File: x-pack/libbeat/management/managerV2.go [hunk 4]
```diff
@@ -31,15 +38,20 @@ type BeatV2Manager struct {
 
 	logger *logp.Logger
 
-	// Track individual units given to us by the V2 API
-	unitsMut sync.Mutex
-	units    map[string]*client.Unit
-	mainUnit string
+	// track individual units given to us by the V2 API
+	mx      sync.Mutex
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:42]: Yeah I can move it. I originally have multiple mutex for different parts but then I would still need to grab the unitsMx so I just changed it to a single mutex because it was safer than causing some deadlock in lock ordering.

File: x-pack/libbeat/management/managerV2.go [hunk 5]
```diff
@@ -158,69 +171,120 @@ func (cm *BeatV2Manager) CheckRawConfig(_ *conf.C) error {
...
-	if exists {
-		_ = stateUnit.UpdateState(client.UnitStateHealthy, fmt.Sprintf("Registering action %s for main unit with ID %s", cm.mainUnit, action.Name()), nil)
-		cm.units[cm.mainUnit].RegisterAction(action)
-	} else {
-		cm.logger.Warnf("Cannot register action %s, no main unit found", action.Name())
+	cm.mx.Lock()
+	defer cm.mx.Unlock()
+
+	cm.actions = append(cm.actions, action)
+	for _, unit := range cm.units {
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:178]: Technically they shouldn't be registered in every unit, it really should be a specific unit thing. But the problem is that beats doesn't pass the unit down to the implementation to be able to make that type of registration and be specific.

So the actions must be registered on every unit that way the action will actually be called. There is no such thing as a main unit or anything like that, so all must get the action.

File: x-pack/libbeat/management/managerV2.go (hunk 2 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:333]: This is because performing `reload` might result in the config logic of the beat to call `UpdateStatus` which will then grab the mutex for the units.

So to ensure that a dead lock doesn't occur we ensure that the actual reload logic is performed in the main loop of the manager, but not in a path that would hold that mutex. So that is why a copy is sent to the reload function. Each `client.Unit` has an internal lock for state so it is also save to have a pointer to the same unit.

File: x-pack/libbeat/management/managerV2.go (hunk 1 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:452]: The global `UpdateStatus` will grab the mutex for units, to prevent that we call this logic on the units that reload just performed. We also would not want to update the status of units that might have been added to the `cm.units` that is different than the actual units that are being processed in the reload (because they where passed in).

File: x-pack/libbeat/management/managerV2.go (hunk 2 above)
Comment (fearful-symmetry) [reply x-pack/libbeat/management/managerV2.go:333]: When you mention a deadlock starting with `UpdateStatus` I assume you mean the `Reload()` call blocking while the beat waits for `UpdateStatus`? 

I wonder if we can do something like have a `addUnit()` return a new copy of the unit map that's sent to `reload()` so we can avoid the extra `reloadCh`? If not, can you at least add a comment explaining the loop, was a tad confusing at first.

File: x-pack/libbeat/management/managerV2.go [hunk 6]
```diff
@@ -311,95 +359,162 @@ func (cm *BeatV2Manager) stopBeat() {
...
+	// any error during reload changes the whole state of the beat to failed
+	if len(errs) > 0 {
+		cm.status = lbmanagement.Failed
+		cm.message = fmt.Sprintf("%s", errs)
+	}
+
+	// now update the statuses of all units
+	cm.mx.Lock()
+	status := getUnitState(cm.status)
+	message := cm.message
```
Comment (fearful-symmetry) [inline x-pack/libbeat/management/managerV2.go:442]: What's the reasoning behind using the global message? Seems like we should have a status message specifically mentioning the reload operation?

File: x-pack/libbeat/management/managerV2.go (hunk 2 above)
Comment (cmacknz) [reply x-pack/libbeat/management/managerV2.go:333]: Can you add a comment explaining the potential for deadlock here so it's obvious the next time we read this code?

Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:333]: I have added a comment as well as add some debounce to consolidate unit changes into a single reload. It makes it simpler to understand as well.

File: x-pack/libbeat/management/managerV2.go (hunk 6 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:442]: This is basically setting the units to Healthy, or what ever beats has set with the `UpdateStatus` for the current state of the beat. The state is global because beats doesn't have a way of passing each unit to each running input and have it handle its own state.

File: x-pack/libbeat/management/managerV2.go [hunk 7]
```diff
@@ -158,69 +171,120 @@ func (cm *BeatV2Manager) CheckRawConfig(_ *conf.C) error {
...
-// the purpose of this is to just grab the first input-type unit we get and set it as the "main" unit
-func (cm *BeatV2Manager) setMainUnitValue(unit *client.Unit) {
-	cm.unitsMut.Lock()
-	defer cm.unitsMut.Unlock()
-	if cm.mainUnit == "" {
-		cm.logger.Debugf("Set main input unit to ID %s", unit.ID())
-		cm.mainUnit = unit.ID()
+func (cm *BeatV2Manager) modifyUnit(unit *client.Unit) {
+	// `unit` is already in `cm.units` no need to add it to the map again
+	// but the lock still needs to be help so reload can be triggered
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:268]: Fixed

**Comment by blakerouse** [comment]
Okay I think this is ready to be merged. I have added unit tests, answered all questions, updated comments, an added debounce to unit changes. I also merged https://github.com/elastic/beats/pull/34049 into this PR so its already present and ready to go once this lands.

File: x-pack/libbeat/management/managerV2.go [hunk 8]
```diff
@@ -31,26 +42,33 @@ type BeatV2Manager struct {
...
-	mainUnit string
+	// track individual units given to us by the V2 API
+	mx      sync.Mutex
+	units   map[unitKey]*client.Unit
+	actions []client.Action
 
-	// This satisfies the SetPayload() function, and will pass along this value to the UpdateStatus()
-	// call whenever a config is re-registered
+	// status is reported as a whole for every unit sent to this component
+	// hopefully this can be improved in the future to be seperated per unit
```
Comment (cmacknz) [inline x-pack/libbeat/management/managerV2.go:51]:
```suggestion
	// hopefully this can be improved in the future to be separated per unit
```

File: x-pack/libbeat/management/managerV2.go [hunk 9]
```diff
@@ -23,6 +27,13 @@ import (
 	"github.com/elastic/elastic-agent-libs/logp"
 )
 
+// unitKey is used to identify a unique unit in a map
+// the `ID` of a unit in itself is not unique without its type, only `Type` + `ID` is unique
+type unitKey struct {
+	Type client.UnitType
+	ID   string
```
Comment (cmacknz) [inline x-pack/libbeat/management/managerV2.go:34]: Is there anything on the agent side enforcing that this tuple is unique per unit?

Trying to trace where this is coming from and I see this on the agent side: https://github.com/elastic/elastic-agent/blob/7e376c3eec28d0bbd9064930042a2225e9a29dbc/pkg/component/component.go#L235-L241

```go
				units = append(units, Unit{
					ID:       fmt.Sprintf("%s-%s-%s", inputType, outputName, input.id),
					Type:     client.UnitTypeInput,
					LogLevel: input.logLevel,
					Config:   cfg,
					Err:      cfgErr,
				})
```

The uniqueness is coming from the `input.id` primarily, which I see parsed out of the agent policy with a uniqueness check so it seems to be there: https://github.com/elastic/elastic-agent/blob/7e376c3eec28d0bbd9064930042a2225e9a29dbc/pkg/component/component.go#L511-L522

```go
		idRaw, ok := input[idKey]
		if !ok {
			// no ID; fallback to type
			idRaw = t
		}
		id, ok := idRaw.(string)
		if !ok {
			return nil, fmt.Errorf("invalid 'inputs.%d.id', expected a string not a %T", idx, idRaw)
		}
		if hasDuplicate(outputsMap, id) {
			return nil, fmt.Errorf("invalid 'inputs.%d.id', has a duplicate id %q (id is required to be unique)", idx, id)
		}
```

Was this uniqueness check there before? Does it work with standalone agent policies that omit the ID field? We don't seem to document the need for it in our standalone agent docs so likely we will encounter agent policies with missing input IDs in the wild, possibly lots of them.

File: x-pack/libbeat/management/managerV2.go [hunk 10]
```diff
@@ -251,38 +330,32 @@ func (cm *BeatV2Manager) unitListen() {
...
 			// A unit add and a unit change, since either way we can't do much more than call the reloader
 			case client.UnitChangedAdded:
-				// At this point we also get a log level, however I'm not sure the beats core logger provides a
-				// clean way to "just" change the log level, without resetting the whole log config
-				state, _, _ := change.Unit.Expected()
-				cm.logger.Debugf("Got unit added: %s, type: %s expected state: %s", change.Unit.ID(), change.Unit.Type(), state.String())
-				go cm.handleUnitReload(change.Unit)
-
+				cm.addUnit(change.Unit)
+				t.Reset(changeDebounce)
```
Comment (cmacknz) [inline x-pack/libbeat/management/managerV2.go:341]: Can the timer be running here? If it isn't stopped the timer documentation says this isn't the correct way to handle this: https://pkg.go.dev/time#Timer.Reset

> For a Timer created with NewTimer, Reset should be invoked only on stopped or expired timers with drained channels.
> 
> If a program has already received a value from t.C, the timer is known to have expired and the channel drained, so t.Reset can be used directly. If a program has not yet received a value from t.C, however, the timer must be stopped and—if Stop reports that the timer expired before being stopped—the channel explicitly drained:
> 
> if !t.Stop() {
> 	<-t.C
> }
> t.Reset(d)
> This should not be done concurrent to other receives from the Timer's channel.

File: x-pack/libbeat/management/managerV2.go [hunk 11]
```diff
@@ -311,95 +377,156 @@ func (cm *BeatV2Manager) stopBeat() {
...
-	_ = unit.UpdateState(client.UnitStateConfiguring, "reloading output component", nil)
-	cm.lastOutputCfg = reloadConfig
-	err = output.Reload(reloadConfig)
-	if err != nil {
-		errString := fmt.Errorf("Failed to reload component: %w", err)
-		_ = unit.UpdateState(client.UnitStateFailed, errString.Error(), nil)
-		return
+	if unit == nil {
+		// output is being stopped
+		err := output.Reload(nil)
```
Comment (cmacknz) [inline x-pack/libbeat/management/managerV2.go:471]: Is there any reason why this change doesn't also trigger the Beat to restart? I'm not sure this will be any better behaved, in fact I'm not sure of the behaviour of removing the output in a Beat in general.

File: x-pack/libbeat/management/config.go [hunk 12]
```diff
@@ -11,8 +11,9 @@ import (
 
 // Config for central management
 type Config struct {
-	Enabled   bool                    `config:"enabled" yaml:"enabled"`
-	Blacklist ConfigBlacklistSettings `config:"blacklist" yaml:"blacklist"`
+	Enabled       bool                    `config:"enabled" yaml:"enabled"`
+	Blacklist     ConfigBlacklistSettings `config:"blacklist" yaml:"blacklist"`
+	OutputRestart bool                    `config:"output_restart" yaml:"output_restart"`
```
Comment (cmacknz) [inline x-pack/libbeat/management/config.go:16]: nit: We used `restart_on_output_change` as the configuration and yaml name here in https://github.com/elastic/beats/pull/34049/files so that it would match exactly with the parameter name in the [v1 spec files](https://github.com/elastic/elastic-agent/blob/1fa24b7a28c0e9e30647f17d945a03168055bde5/internal/spec/filebeat.yml#L12).

I also think `restart_on_output_change` more obviously describes what this does if you read it by itself on the spec file side.

File: x-pack/libbeat/management/managerV2_test.go [hunk 13]
```diff
@@ -0,0 +1,177 @@
...
+	m, err := NewV2AgentManagerWithClient(&Config{
+		Enabled: true,
+	}, r, client)
+	require.NoError(t, err)
+
+	err = m.Start()
+	require.NoError(t, err)
+	defer m.Stop()
+
+	require.Eventually(t, func() bool {
```
Comment (cmacknz) [inline x-pack/libbeat/management/managerV2_test.go:116]: I think this would be a better test if we also transitioned some or all of the units expected states to stopped to ensure they are removed correctly.

It would also be nice to try to cover the logic to restart on output change but you'd have to mock out the actual stop/shutdown.

File: x-pack/libbeat/management/managerV2_test.go [hunk 14]
```diff
@@ -0,0 +1,177 @@
...
+						Id: "system/metrics-system.filesystem-default-system-1",
+						Source: requireNewStruct(t, map[string]interface{}{
+							"metricsets": []interface{}{"filesystem"},
+							"period":     "1m",
+						}),
+					},
+				},
+			},
+			State:    proto.State_HEALTHY,
+			LogLevel: proto.UnitLogLevel_INFO,
```
Comment (cmacknz) [inline x-pack/libbeat/management/managerV2_test.go:58]: If you used a lower log level for one of these units you could trivially test the log level adjustment with a call to [logp.GetLevel](GetLevel).

**Review by cmacknz — COMMENTED** [review]
A few new questions, but generally this looks good to me.

We will need a matching change to the Beat spec files to:
1. Enable the output_restart/restart_on_output_change option for each Beat.
2. Restore the default log level to INFO.

**Comment by cmacknz** [comment]
@axw and @oren-zohar you will want to make sure you pick up this change to libbeat in APM server and Cloudbeat when it merges. The major highlights of what this addresses are:

1. Allow changing the log level of the `logp` logger dynamically in response to configuration changes from the Elastic agent. The previous behaviour where the agent know to restart Beats when the log level changed has been removed.
2. Fixes several potential bugs in how input configurations are reloaded dynamically, including avoiding a situation where a Beat with multiple units would incorrectly shut down when only one of them was removed.
3. Restores an old work around for dynamic output configuration reloads not working in libbeat, by automatically restarting the Beat to have the change take effect. See https://github.com/elastic/elastic-agent/issues/1913. This does not apply to APM server.

File: x-pack/libbeat/management/managerV2.go (hunk 9 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:34]: ID is a required value on standalone agents now, so they will error and then they will need to modify the `elastic-agent.yml` to set an `id` on the input definition.

The Elastic Agent does enforce that a Type/ID is unique.

File: x-pack/libbeat/management/managerV2.go (hunk 11 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:471]: Because if the output is now nil, that means beats is stopping. We would not want it to just be stopped here, once all the units have reported stopped the Elastic Agent will stop the beat.

File: x-pack/libbeat/management/config.go (hunk 12 above)
Comment (blakerouse) [reply x-pack/libbeat/management/config.go:16]: I updated to use the same flag name `restart_on_output_change`.

File: x-pack/libbeat/management/managerV2.go (hunk 11 above)
Comment (cmacknz) [reply x-pack/libbeat/management/managerV2.go:471]: Makes sense, probably worth adding a clarify this.

File: x-pack/libbeat/management/managerV2_test.go (hunk 13 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2_test.go:193]: I added more to the test to check for, state changes, log level changes, and stopping and removal of units.

File: x-pack/libbeat/management/managerV2_test.go (hunk 14 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2_test.go]: Added to the test to cover this.

File: x-pack/libbeat/management/managerV2.go (hunk 10 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:342]: I looked into this and it seems the way I have it in the code is correct. The reason it is correct is because the `<-t.C` is handled in the select in the same goroutine. It that was not the case it would be a problem.

By using the code as you commented above doesn't work because the `<-t.C` would then occur in multiple places and 2 places cannot read from that channel or it will cause the one that doesn't get the message from the channel to block.

Many instances of golang code use the `t.Reset` like I do in the select and seems to work as expected in the code.

**Review by cmacknz — APPROVED** [review]
Looks good, thanks for the extra testing!

File: x-pack/libbeat/management/generate.go [hunk 15]
```diff
@@ -78,15 +78,33 @@ func CreateInputsFromStreams(raw *proto.UnitExpectedConfig, inputType string, ag
...
+			return nil, fmt.Errorf("Error injecting stream processors: %w", err)
 		}
-		streamSource = injectGlobalProcesssors(raw, streamSource)
+
+		// now the order of the processors on this input is as follows
+		// 1. stream processors
+		// 2. agentInfo processors
+		// 3. global processors
+		// 4. stream specific processors
+
```
Comment (cmacknz) [inline x-pack/libbeat/management/generate.go:107]: The order here doesn't quite line up with the order of the comments above, which is

1. Global processors
2. agentInfo processors
3. Stream processors

Comment (blakerouse) [reply x-pack/libbeat/management/generate.go:107]: It is using prepend not append. So it prepends to the array each time so the order is reversed when reading the code. Operating this way allows the processors defined on the stream to always be last.

It is definitely working as the code comment says and it is working under the Elastic Agent correctly.

Comment (cmacknz) [reply x-pack/libbeat/management/generate.go:107]: Yeah was just going to comment that I don't think I read the prepend operations correctly.

**Comment by cmacknz** [comment]
@axw and @oren-zohar reminder ping now that this has merged that you will want to pick up this change in libbeat on both main and 8.6. 

You will also want to ensure that the elastic-agent-client version is bumped to https://github.com/elastic/elastic-agent-client/releases/tag/v7.0.3 in your go.mod files if the libbeat update does not do this automatically.

**Comment by axw** [comment]
Thanks @cmacknz, apm-server main and 8.6 are both updated, and I've confirmed that elastic-agent-client was bumped to 7.0.3.

**Comment by oren-zohar** [comment]
Thanks @cmacknz @blakerouse, cloudbeat was updated and I can confirm this fix works as expected :rocket:
