### PR TITLE
Fix loading processors from autodiscover hints

### LINKED ISSUE #16343: [Filebeat] Autodiscovery logs.processors does not convert string into a MapStr
When using labels on Docker or annotations on Kubernetes to add processors to a container the runner fails to be created because the value of the annotation name is not converted from a `string` to a `common.MapStr` before passing the information to the runner.

Use the follow configuration:

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.console:
  pretty: true
```

Start the container:

`docker run -l 'co.elastic.logs/processors.add_fields={"fields":{"foo":"bar"}}' busybox echo hello`

Errors with:

`Error creating runner from config: can not convert 'string' into 'object' accessing 'processors.0.add_fields'`

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes an issue where processors from autodiscover hints where not convered into a `common.MapStr`.

## Why is it important?

Allows processors to be defined in autodiscover hints.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [X] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [X] Converts `string` to `common.MapStr`

## How to test this PR locally

Run filebeat with:

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.console:
  pretty: true
```

Start container with processor:

`docker run -l 'co.elastic.logs/processors.add_fields={"fields":{"foo":"bar"}}' busybox echo hello`

Check that filebeat was able to start logging it the container with the fields added.

## Related issues

- Closes #16343

### CODE REVIEW

File: libbeat/autodiscover/builder/helper.go [hunk 1]
```diff
@@ -86,7 +86,20 @@ func GetHintAsList(hints common.MapStr, key, config string) []string {
...
 // GetProcessors gets processor definitions from the hints and returns a list of configs as a MapStr
 func GetProcessors(hints common.MapStr, key string) []common.MapStr {
-	return GetConfigs(hints, key, "processors")
+	processors := GetConfigs(hints, key, "processors")
+	for _, proc := range processors {
+		for key, value := range proc {
+			if str, ok := value.(string); ok {
+				cfg := common.MapStr{}
+				if err := json.Unmarshal([]byte(str), &cfg); err != nil {
+					logp.Debug("autodiscover.builder", "unable to unmarshal json due to error: %v", err)
```
Comment (kaiyan-sheng) [inline libbeat/autodiscover/builder/helper.go]: Does this need to be logp.Debugf?

Comment (blakerouse) [reply libbeat/autodiscover/builder/helper.go]: Checked the code, seems `logp.Debug` is correct. It accepts parameters for the format string.
