### PR TITLE
Fix MongoDB dbstats fields mapping

### LINKED ISSUE #3989: Some MongoDB fields are wrong
Some mongodb fields do not match their field definition, we will need to update it. See:

https://github.com/elastic/beats/blob/master/metricbeat/module/mongodb/dbstats/data.go#L12 and
https://github.com/elastic/beats/blob/5.3/metricbeat/module/mongodb/dbstats/_meta/fields.yml#L7

`.bytes` is appended to fields definition but not reported by the code. We should review all the fields in this module, as I see others affected too.

This was detected in this thread: https://discuss.elastic.co/t/cannot-index-event-avg-obj-size/81941/1

### PR DESCRIPTION
**Pull request by exekias**
Fix mongodb dbstats mapping to avoid errors like this:

```
WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"object mapping for [mongodb.dbstats.avg_obj_size] tried to parse field [avg_obj_size] as object, but found a concrete value"}
```

closes #3989

### CODE REVIEW

File: metricbeat/module/mongodb/dbstats/data.go [hunk 1]
```diff
@@ -6,27 +6,27 @@ import (
...
-	"avg_obj_size": c.Int("avgObjSize"),
-	"data_size":    c.Int("dataSize"),
-	"storage_size": c.Int("storageSize"),
-	"num_extents":  c.Int("numExtents"),
-	"indexes":      c.Int("indexes"),
-	"index_size":   c.Int("indexSize"),
+	"db":                 c.Str("db"),
+	"collections":        c.Int("collections"),
+	"objects":            c.Int("objects"),
+	"avg_obj_size.bytes": c.Int("avgObjSize"),
```
Comment (ruflin) [inline metricbeat/module/mongodb/dbstats/data.go]: This will make it incompatible with elasticsearch 2.x. You must use `s.Object{ ... } ` to add the nesting.

Comment (exekias) [inline metricbeat/module/mongodb/dbstats/data.go]: Ah, didn't know that one, thanks!

**Comment by monicasarbu** [comment]
@exekias Some tests are failing. Can you please have a look?

File: metricbeat/module/mongodb/dbstats/data.go [hunk 2]
```diff
@@ -6,27 +6,39 @@ import (
...
 	"data_file_version": c.Dict("dataFileVersion", s.Schema{
 		"major": c.Int("major"),
 		"minor": c.Int("minor"),
 	}, c.DictOptional),
 	// mmapv1 only
 	"extent_free_list": c.Dict("extentFreeList", s.Schema{
-		"num":  c.Int("num"),
-		"size": c.Int("size"),
+		"num":        c.Int("num"),
+		"size.bytes": c.Int("size"),
```
Comment (ruflin) [inline metricbeat/module/mongodb/dbstats/data.go]: Still one with `.bytes`

File: metricbeat/module/mongodb/dbstats/dbstats_integration_test.go [hunk 3]
```diff
@@ -30,13 +30,13 @@ func TestFetch(t *testing.T) {
 		objects := event["objects"].(int64)
 		assert.True(t, objects > 0)
 
-		avgObjSize := event["avg_obj_size"].(int64)
+		avgObjSize := event["avg_obj_size.bytes"].(int64)
```
Comment (ruflin) [inline metricbeat/module/mongodb/dbstats/dbstats_integration_test.go]: I assume that is not going to work, as it is a nested object.

File: metricbeat/module/mongodb/dbstats/_meta/data.json [hunk 4]
```diff
@@ -12,15 +12,15 @@
     },
     "mongodb": {
         "dbstats": {
-            "avg_obj_size": 59,
+            "avg_obj_size.bytes": 59,
```
Comment (ruflin) [inline metricbeat/module/mongodb/dbstats/_meta/data.json]: You should update this one with `make generation-json`.

**Comment by ashwinboinala** [comment]
@ruflin How do I make this changes to my existing metric beat installation, please advise.

**Comment by ruflin** [comment]
@ashwinboinala There are two options. Either you adjust the mapping manually and overwrite the one you have or you switch to the nightly build found here and let metricbeat overwrite your template: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=metricbeat/

@exekias Should we backport this to 5.x?

**Comment by exekias** [comment]
@ruflin uhm probably yes, let me open a PR

**Comment by ashwinboinala** [comment]
@ruflin thanks for your response.
I found another issue with mongo module, below is my connection string. 
hosts: ["mongodb://username:password@servername:27017/dbname"]
In the dashboard, I see hostname as username:password which is metric.hostname
Is it expected behavior or am I doing anything wrong, below is my metricbeat config.
Please advise
- module: mongodb
  metricsets: ["dbstats", "status"]
  enabled: true
  period: 10s
  hosts: ["mongodb://username:password@servername:27017/dbname"]

-Ashwin

**Comment by ruflin** [comment]
@ashwinboinala This is not expected. It sounds like something does not work well with the host parser. Could you open a new Github issue for it?
