### PR TITLE
Fix handling of @timestamp and type from the JSON decoder

### LINKED ISSUE #1378: filebeat panic with json overwrite_keys and elasticsearch output
I'm testing the new json support in filebeat 5.0.0-alpha1. I'm having an issue sending json output to elasticsearch with the overwrite_keys option. If overwrite_keys is enabled, the filebeat process crashes. Debug output indicates "panic: interface conversion: interface is string, not common.Time". The source timestamp in my test log entry is "2016-04-05T18:47:18.444Z", which seems to be in the proper format. Both logstash and local file outputs work as expected under the same conditions with the same log. If I disable overwrite_keys, logs are properly sent to elasticsearch and the filebeat process continues to run.

Version: filebeat 5.0.0-alpha1
Operating System: Centos 6.7 64-bit

Steps to Reproduce:

      json:
        message_key: msg
        keys_under_root: true
        overwrite_keys: true

Log entry:
`
```
{"@timestamp":"2016-04-05T18:47:18.444Z","level":"INFO","logger":"iapi.logger","thread":"JobCourier4","appInfo":{"appname":"SessionManager","appid":"Pooler","host":"demohost.mydomain.com","ip":"192.168.128.113","pid":13982},"userFields":{"ApplicationId":"PROFAPP_001","RequestTrackingId":"RetrieveTBProfileToken-6066477"},"source":"DataAccess\/FetchActiveSessionToken.process","msg":"FetchActiveSessionToken process ended"}`
```
debug message: 

```
2016/04/12 20:44:32.702501 prospector.go:86: INFO Starting prospector of type: log
2016/04/12 20:44:32.702505 prospector.go:94: INFO Run prospector
2016/04/12 20:44:32.702509 prospector_log.go:46: DBG  Start next scan
2016/04/12 20:44:32.702526 prospector_log.go:79: DBG  scan path /var/log/tibco/*/iapi-logs/*-watch.log
2016/04/12 20:44:32.702568 prospector_log.go:92: DBG  Check file for harvesting: /var/log/tibco/pooler/iapi-logs/One-iapi-watch.log
2016/04/12 20:44:32.702577 prospector_log.go:213: DBG  Update existing file for harvesting: /var/log/tibco/pooler/iapi-logs/One-iapi-watch.log
2016/04/12 20:44:32.702581 prospector_log.go:243: DBG  Not harvesting, file didn't change: /var/log/tibco/pooler/iapi-logs/One-iapi-watch.log
2016/04/12 20:44:33.702677 reader.go:138: DBG  End of file reached: /var/log/tibco/pooler/iapi-logs/One-iapi-watch.log; Backoff now.
2016/04/12 20:44:35.702881 reader.go:138: DBG  End of file reached: /var/log/tibco/pooler/iapi-logs/One-iapi-watch.log; Backoff now.
2016/04/12 20:44:37.702454 spooler.go:132: DBG  Flushing spooler because of timeout. Events flushed: 1
2016/04/12 20:44:37.702897 client.go:193: DBG  Publish: {
  "@timestamp": "2016-04-05T18:47:18.444Z",
  "appInfo": {
    "appid": "Pooler",
    "appname": "SessionManager",
    "host": "demohost.mydomain.com",
    "ip": "192.168.128.113",
    "pid": 13982
  },
  "beat": {
    "hostname": "localhost.localdomain",
    "name": "localhost.localdomain"
  },
  "input_type": "log",
  "level": "INFO",
  "logger": "iapi.logger",
  "msg": "FetchActiveSessionToken process ended",
  "offset": 0,
  "source": "DataAccess/FetchActiveSessionToken.process",
  "thread": "JobCourier4",
  "type": "log",
  "userFields": {
    "ApplicationId": "PROFAPP_001",
    "RequestTrackingId": "RetrieveTBProfileToken-6066477"
  }
}
2016/04/12 20:44:37.702940 output.go:107: DBG  output worker: publish 1 events
2016/04/12 20:44:37.705989 output.go:107: DBG  output worker: publish 1 events
panic: interface conversion: interface is string, not common.Time


goroutine 12 [running]:
panic(0x9bbec0, 0xc82019cb00)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/elastic/beats/libbeat/outputs/elasticsearch.getIndex(0xc8201ae5a0, 0xc82014a180, 0x4, 0x0, 0x0)
        /go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:195 +0xd9
github.com/elastic/beats/libbeat/outputs/elasticsearch.eventBulkMeta(0xc82014a180, 0x4, 0xc8201ae5a0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:180 +0x58
github.com/elastic/beats/libbeat/outputs/elasticsearch.bulkEncodePublishRequest(0xc82011ec80, 0xc82014a180, 0x4, 0xc8200221c8, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:166 +0xe0
github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Client).PublishEvents(0xc82007e1c0, 0xc8200221c8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:127 +0x2f1
github.com/elastic/beats/libbeat/outputs/mode.(*SingleConnectionMode).PublishEvents.func1(0xc82010b200)
        /go/src/github.com/elastic/beats/libbeat/outputs/mode/single.go:76 +0x9c
github.com/elastic/beats/libbeat/outputs/mode.(*SingleConnectionMode).publish(0xc82010b200, 0x7ff8af234e58, 0xc820159980, 0x1, 0xc820239b40, 0x0, 0x0)
        /go/src/github.com/elastic/beats/libbeat/outputs/mode/single.go:131 +0x319
github.com/elastic/beats/libbeat/outputs/mode.(*SingleConnectionMode).PublishEvents(0xc82010b200, 0x7ff8af234e58, 0xc820159980, 0x1, 0xc8200221c8, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/elastic/beats/libbeat/outputs/mode/single.go:86 +0x75
github.com/elastic/beats/libbeat/outputs/elasticsearch.(*elasticsearchOutput).BulkPublish(0xc820156120, 0x7ff8af234e58, 0xc820159980, 0x1, 0xc8200221c8, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/output.go:220 +0x94
github.com/elastic/beats/libbeat/publisher.(*outputWorker).sendBulk(0xc820013630, 0xc820239d40, 0xc8200221c8, 0x1, 0x1)
        /go/src/github.com/elastic/beats/libbeat/publisher/output.go:110 +0x190
github.com/elastic/beats/libbeat/publisher.(*outputWorker).onBulk(0xc820013630, 0xc820239d40, 0xc8200221c8, 0x1, 0x1)
        /go/src/github.com/elastic/beats/libbeat/publisher/output.go:86 +0x39d
github.com/elastic/beats/libbeat/publisher.(*outputWorker).onMessage(0xc820013630, 0xffffffffffff0101, 0x7ff8af234e58, 0xc820159980, 0x0, 0xc8200221c8, 0x1, 0x1)
        /go/src/github.com/elastic/beats/libbeat/publisher/output.go:69 +0x79
github.com/elastic/beats/libbeat/publisher.(*messageWorker).onEvent(0xc820013630, 0xc820150101, 0x7ff8af234e58, 0xc820159980, 0x0, 0xc8200221c8, 0x1, 0x1)
        /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:74 +0xb2
github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc820013630)
        /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:60 +0x34c
created by github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
        /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:48 +0x126`
```

### PR DESCRIPTION
**Pull request by tsg**
If `json.keys_under_root` and `json.overwrite_keys` are set, and the keys
`@timestamp` or `type` show up in the decoded JSON, they can cause issues because
the Elasticsearch output makes some assumptions about them: @timestamp has to
be of type `common.Time` and `type` has to be of type `string`.

The fix attempts to make use of the `@timestamp` and `type` from the JSON, but if
parsing fails or the resulting values are invalid, the fields are not overwritten
and an error key is added to help with troubleshooting.

Fixes #1378.

Also hardens the `getIndex` call in libbeat, to protect against wrong types there
as well.

### CODE REVIEW

File: filebeat/input/file.go [hunk 1]
```diff
@@ -72,7 +77,37 @@ func mergeJSONFields(f *FileEvent, event common.MapStr) {
...
+						continue
+					}
+					if len(vstr) == 0 || vstr[0] == '_' {
+						logp.Err("JSON: Won't overwrite type because value is empty or starts with an underscore")
+						event[jsonErrorKey] = fmt.Sprintf("type not overwritten (invalid value [%s])", vstr)
+						continue
+					}
+					event[k] = vstr
+				} else {
+					event[k] = v
```
Comment (urso) [inline filebeat/input/file.go]: what if k == jsonErrorKey?

File: filebeat/input/file_test.go [hunk 2]
```diff
@@ -177,6 +180,92 @@ func TestFileEventToMapStrJSON(t *testing.T) {
 				"type": "test_type",
 			},
 		},
+		{
+			// when @timestamp is in JSON and overwrite_keys is true, parse it
```
Comment (urso) [inline filebeat/input/file_test.go]: it's often helpful to either print the event or have a test name to be printed in test loop via t.Log in case some test fails.

File: filebeat/input/file.go [hunk 3]
```diff
@@ -72,7 +77,37 @@ func mergeJSONFields(f *FileEvent, event common.MapStr) {
 	if f.JSONConfig.KeysUnderRoot {
 		for k, v := range f.JSONFields {
 			if f.JSONConfig.OverwriteKeys {
-				event[k] = v
+				if k == "@timestamp" {
```
Comment (urso) [inline filebeat/input/file.go]: instead of relying on '@timestamp' only, we can make the timestamp to be parsed configurable.

File: filebeat/input/file.go [hunk 4]
```diff
@@ -72,7 +77,37 @@ func mergeJSONFields(f *FileEvent, event common.MapStr) {
...
+					vstr, ok := v.(string)
+					if !ok {
+						logp.Err("JSON: Won't overwrite @timestamp because value is not string")
+						event[jsonErrorKey] = "@timestamp not overwritten (not string)"
+						continue
+					}
+					// @timestamp must be of time common.Time
+					ts, err := common.ParseTime(vstr)
```
Comment (urso) [inline filebeat/input/file.go]: how flexible is ParseTime in time format?

File: filebeat/tests/system/test_json.py [hunk 5]
```diff
@@ -166,3 +166,75 @@ def test_config_no_msg_key_multiline(self):
...
+        assert len(output) == 3
+        assert output[0]["@timestamp"] == "2016-04-05T18:47:18.444Z"
+
+        assert output[1]["@timestamp"] != "invalid"
+        assert output[1]["json_error"] == \
+            "@timestamp not overwritten (parse error on invalid)"
+
+        assert isinstance(output[2]["@timestamp"], basestring)
+        assert output[2]["json_error"] == \
+            "@timestamp not overwritten (not string)"
```
Comment (urso) [inline filebeat/tests/system/test_json.py]: we should always check for type

File: filebeat/tests/system/test_json.py [hunk 6]
```diff
@@ -166,3 +166,75 @@ def test_config_no_msg_key_multiline(self):
...
+
+        proc = self.start_beat()
+        self.wait_until(
+            lambda: self.output_has(lines=3),
+            max_timeout=10)
+        proc.check_kill_and_wait()
+
+        output = self.read_output()
+        assert len(output) == 3
+        assert output[0]["type"] == "test"
```
Comment (urso) [inline filebeat/tests/system/test_json.py]: always check for '@timestamp' present.

File: filebeat/input/file.go (hunk 1 above)
Comment (tsg) [inline filebeat/input/file.go]: Then it gets overwritten. IMHO that's fine, because `keys_under_root` is not the default and we usually recommend people not to use it. When people use it, it's implied that "I'm aware that everything can get overwritten".

File: filebeat/input/file.go (hunk 3 above)
Comment (tsg) [inline filebeat/input/file.go]: I was thinking to wait until this is requested to avoid adding too many settings. I might reconsider.

File: filebeat/input/file.go (hunk 4 above)
Comment (tsg) [inline filebeat/input/file.go]: Same as above, didn't meant for this to be super configurable for now, to force people to use things like Logstash and Elasticsearch ingest node to parsing and such. The main goal was to make sure we don't panic, which was the case in the bug report.

File: filebeat/input/file.go (hunk 3 above)
Comment (urso) [inline filebeat/input/file.go]: fair enough

File: filebeat/input/file_test.go (hunk 2 above)
Comment (tsg) [inline filebeat/input/file_test.go]: Good tip, thanks!

**Comment by tsg** [comment]
Comments addressed.

File: filebeat/input/file.go [hunk 7]
```diff
@@ -72,7 +77,37 @@ func mergeJSONFields(f *FileEvent, event common.MapStr) {
...
+					if err != nil {
+						logp.Err("JSON: Won't overwrite @timestamp because of parsing error: %v", err)
+						event[jsonErrorKey] = fmt.Sprintf("@timestamp not overwritten (parse error on %s)", vstr)
```
Comment (andrewkroh) [inline filebeat/input/file.go]: I think it would be better to include the error and the value. Probably the error already includes the failed value.
