### PR TITLE
[Elastic Agent] Reduce log level for listener cleanup to debug

### LINKED ISSUE #25131: [Elastic Agent] Enroll fleet-server, socket cannot be removed
* Platform: OS X
* Branch: master

I enrolled an Elastic Agent with a fleet-server with the following command:

```
sudo ./elastic-agent enroll --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL215LWZsZWV0LXNlcnZlci10b2tlbjpZVEF2MnFVdVFlV2RYWTc5R2RKVjV3 --fleet-server-es=http://elastic:changeme@localhost:9200/
```

This lead to the following output:

```
The Elastic Agent is currently in BETA and should not be used in production

2021-04-18T20:27:56.535+0200	INFO	cmd/enroll_cmd.go:291	Generating self-signed certificate for Fleet Server
2021-04-18T20:27:56.874+0200	INFO	cmd/enroll_cmd.go:440	Spawning Elastic Agent daemon as a subprocess to complete bootstrap process.
2021-04-18T20:27:57.017+0200	WARN	cmd/run.go:133	Artifact has been build with security disabled. Elastic Agent will not verify signatures of used artifacts.
2021-04-18T20:27:57.019+0200	INFO	warn/warn.go:18	The Elastic Agent is currently in BETA and should not be used in production
2021-04-18T20:27:57.019+0200	INFO	application/application.go:68	Detecting execution mode
2021-04-18T20:27:57.019+0200	INFO	application/application.go:89	Agent is in Fleet Server bootstrap mode
2021-04-18T20:27:57.121+0200	INFO	[api]	api/server.go:62	Starting stats endpoint
2021-04-18T20:27:57.121+0200	INFO	application/fleet_server_bootstrap.go:124	Agent is starting
2021-04-18T20:27:57.122+0200	INFO	[api]	api/server.go:64	Metrics endpoint listening on: /tmp/elastic-agent/46581af1d46322e7d8fdb05e4fcbeece7bc4b957f83a5a6ea8e1874c93d4e1b8.sock (configured: unix:///tmp/elastic-agent/46581af1d46322e7d8fdb05e4fcbeece7bc4b957f83a5a6ea8e1874c93d4e1b8.sock)
2021-04-18T20:27:57.129+0200	INFO	application/fleet_server_bootstrap.go:134	Agent is stopped
2021-04-18T20:27:57.882+0200	INFO	cmd/enroll_cmd.go:582	Waiting for Elastic Agent to start Fleet Server
2021-04-18T20:27:58.165+0200	INFO	stateresolver/stateresolver.go:48	New State ID is aDKt5uTm
2021-04-18T20:27:58.165+0200	INFO	stateresolver/stateresolver.go:49	Converging state requires execution of 1 step(s)
2021-04-18T20:28:00.800+0200	INFO	operation/operation_fetch.go:75	operation 'operation-fetch' downloaded fleet-server.8.0.0-SNAPSHOT into /Users/ruflin/Dev/gopath/src/github.com/elastic/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64/data/elastic-agent-e1e6d3/downloads/fleet-server-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz
2021-04-18T20:28:01.100+0200	INFO	log/reporter.go:40	2021-04-18T20:28:01+02:00: type: 'STATE': sub_type: 'STARTING' message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to STARTING: Starting
2021-04-18T20:28:01.190+0200	INFO	stateresolver/stateresolver.go:66	Updating internal state
2021-04-18T20:28:01.894+0200	INFO	cmd/enroll_cmd.go:622	Fleet Server - Starting
2021-04-18T20:28:03.627+0200	INFO	log/reporter.go:40	2021-04-18T20:28:03+02:00: type: 'STATE': sub_type: 'RUNNING' message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to DEGRADED: Running on default policy with Fleet Server integration; missing config fleet.agent.id
2021-04-18T20:28:03.627+0200	WARN	status/reporter.go:236	Elastic Agent status changed to: 'degraded'
2021-04-18T20:28:03.901+0200	INFO	cmd/enroll_cmd.go:596	Fleet Server - Running on default policy with Fleet Server integration; missing config fleet.agent.id
2021-04-18T20:28:06.635+0200	INFO	cmd/enroll_cmd.go:197	Elastic Agent has been enrolled; start Elastic Agent
2021-04-18T20:28:06.636+0200	INFO	cmd/run.go:189	Shutting down Elastic Agent and sending last events...
2021-04-18T20:28:06.636+0200	INFO	operation/operator.go:191	waiting for installer of pipeline 'default' to finish
2021-04-18T20:28:06.638+0200	INFO	process/app.go:174	Signaling application to stop because of shutdown: fleet-server--8.0.0-SNAPSHOT
2021-04-18T20:28:07.138+0200	INFO	status/reporter.go:236	Elastic Agent status changed to: 'online'
2021-04-18T20:28:07.138+0200	INFO	log/reporter.go:40	2021-04-18T20:28:07+02:00: type: 'STATE': sub_type: 'STOPPED' message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to STOPPED: Stopped
2021-04-18T20:28:07.138+0200	INFO	cmd/run.go:197	Shutting down completed.
2021-04-18T20:28:07.138+0200	INFO	[api]	api/server.go:66	Stats endpoint (/tmp/elastic-agent/46581af1d46322e7d8fdb05e4fcbeece7bc4b957f83a5a6ea8e1874c93d4e1b8.sock) finished: accept unix /tmp/elastic-agent/46581af1d46322e7d8fdb05e4fcbeece7bc4b957f83a5a6ea8e1874c93d4e1b8.sock: use of closed network connection
2021-04-18T20:28:07.139+0200	ERROR	[control]	server/listener.go:52	Failed to cleanup /tmp/elastic-agent/ccffa3add3551d6b03b626c97dc50bd6d48b1b98ce74749bae839cb1baaa310b.sock: remove /tmp/elastic-agent/ccffa3add3551d6b03b626
```

In the log I stumbled over to parts:

There is an ERROR output for the socket removal but everything seems to be successful:

```
ERROR	[control]	server/listener.go:52	Failed to cleanup /tmp/elastic-agent/ccffa3add3551d6b03b626c97dc50bd6d48b1b98ce74749bae839cb1baaa310b.sock: remove /tmp/elastic-agent/ccffa3add3551d6b03b626
```

The second part is around a missing config fleet.agent.id in the policy:

```
2021-04-18T20:28:03.627+0200	INFO	log/reporter.go:40	2021-04-18T20:28:03+02:00: type: 'STATE': sub_type: 'RUNNING' message: Application: fleet-server--8.0.0-SNAPSHOT[]: State changed to DEGRADED: Running on default policy with Fleet Server integration; missing config fleet.agent.id
```

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Cleans up the log message when removing the listener socket fails.

## Why is it important?

So its not reported or confusing to users, its okay if it fails.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #25131

### CODE REVIEW

File: x-pack/elastic-agent/pkg/agent/control/server/listener.go [hunk 1]
```diff
@@ -48,7 +45,7 @@ func createListener(log *logger.Logger) (net.Listener, error) {
 
 func cleanupListener(log *logger.Logger) {
 	path := strings.TrimPrefix(control.Address(), "unix://")
-	if err := os.Remove(path); err != nil {
-		log.Errorf("%s", errors.New(err, fmt.Sprintf("Failed to cleanup %s", path), errors.TypeFilesystem, errors.M("path", path)))
+	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
+		log.Debug("%s", errors.New(err, fmt.Sprintf("Failed to cleanup %s", path), errors.TypeFilesystem, errors.M("path", path)))
```
Comment (ruflin) [inline x-pack/elastic-agent/pkg/agent/control/server/listener.go:49]: In which scenarios does the file not exists so the cleanup fails?

Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/control/server/listener.go:49]: I believe the case is when the temp directory is removed before the actually socket. So that cause it to fail on the removal.

Comment (ruflin) [reply x-pack/elastic-agent/pkg/agent/control/server/listener.go:49]: But what removes the temp directory? BTW, don't want to block this PR on this but would be good to understand why it happens.

**Review by ruflin — APPROVED** [review]
