### PR TITLE
Force ECS options in filebeat pipelines when filebeat version is over 7.0 and ES version is 6.7.X

### LINKED ISSUE #10655: [Filebeat] user_agent field errors with Filebeat 7 and Elasticsearch 6
The Suricata modules's ingest pipeline fails due to changes (https://github.com/elastic/elasticsearch/issues/37329) in the `user_agent` processor in ES ingest node. I suspect other modules are affected by this problem.

- `{"type":"mapper_parsing_exception","reason":"object mapping for [user_agent.os] tried to parse field [os] as object, but found a concrete value"}`
- `{"type":"mapper_parsing_exception","reason":"object mapping for [user_agent.device] tried to parse field [device] as object, but found a concrete value"}`

In order to make the ES 6.x user_agent processor's output compatible with the Filebeat template we need to add some renames/sets after the `user_agent` in the pipeline.

### PR DESCRIPTION
**Pull request by jsoriano**
When using the `user_agent` processor to ingest data from Filebeat 7.0
into Elasticsearch 6.X conflicts appear with ECS user_agent fields, this can
be solved by setting `ecs: true` when pipelines are being loaded into 
Elasticsearch 6.7.0.

For minor versions where `ecs`  option is not available, pipelines will fail
to load.

Fix #10655

### CODE REVIEW

File: filebeat/fileset/pipelines.go [hunk 1]
```diff
@@ -129,6 +135,37 @@ func loadPipeline(esClient PipelineLoader, pipelineID string, content map[string
 	return nil
 }
 
+// setEcsProcessors sets required ECS options in processors when filebeat version is 7.0.X
```
Comment (andrewkroh) [inline filebeat/fileset/pipelines.go]: I'd say `is >=7.0.0` (assuming that's accurate).

Comment (andrewkroh) [reply filebeat/fileset/pipelines.go]: `s/setEcsProcessors /setECSProcessors/`

File: filebeat/fileset/pipelines.go [hunk 2]
```diff
@@ -129,6 +135,37 @@ func loadPipeline(esClient PipelineLoader, pipelineID string, content map[string
...
+// and ES is 6.7.X to ease migration to ECS
```
Comment (andrewkroh) [inline filebeat/fileset/pipelines.go]: Add a period to close out the sentence, please.

File: filebeat/fileset/pipelines.go [hunk 3]
```diff
@@ -129,6 +135,37 @@ func loadPipeline(esClient PipelineLoader, pipelineID string, content map[string
...
+func setEcsProcessors(esVersion common.Version, pipelineID string, content map[string]interface{}) error {
+	ecsVersion := common.MustNewVersion("7.0.0")
+	if !esVersion.LessThan(ecsVersion) {
+		return nil
+	}
+
+	processors, ok := content["processors"].([]interface{})
+	if !ok {
+		logp.Debug("modules", "Pipeline '%s' without processors: %+v", pipelineID, content)
```
Comment (andrewkroh) [inline filebeat/fileset/pipelines.go]: This log message isn't always accurate. Let's split the the checks for whether the key exists and if the type is `[]interface{}`. I'd say if `processors` does not exist then just `return nil` (that's Elasticsearch's problem and it will validate the pipeline). But if it does exist and it's not a `[]interface{}` then that's an error we are forced to handle because we need to iterate over the contents.

File: filebeat/fileset/pipelines.go [hunk 4]
```diff
@@ -129,6 +135,37 @@ func loadPipeline(esClient PipelineLoader, pipelineID string, content map[string
...
+
+	minUserAgentVersion := common.MustNewVersion("6.7.0")
+	for _, p := range processors {
+		processor, ok := p.(map[string]interface{})
+		if !ok {
+			continue
+		}
+		if options, ok := processor["user_agent"].(map[string]interface{}); ok {
+			if esVersion.LessThan(minUserAgentVersion) {
+				return fmt.Errorf("user_agent processor requires option `ecs: true`, available in Elasticsearch %v", minUserAgentVersion)
```
Comment (andrewkroh) [inline filebeat/fileset/pipelines.go]: I propose including the user's ES version like `fmt.Errorf("user_agent processor requires option 'ecs: true', but Elasticsearch %v does not support this option (Elasticsearch %v or newer is required)", esVersion, minUserAgentVersion)`.

**Comment by jsoriano** [comment]
@andrewkroh suggestions added. Thanks for the review!

**Comment by ruflin** [comment]
@jsoriano If someone upgrades Elasticsearch from 6.7 to 7.0 and keeps Filebeat 6.7, this means the user has to overwrite the ingest pipelines?

**Comment by ruflin** [comment]
@jsoriano One more question: I can't see a backport label on this one. Should this also go into 7.0?

**Comment by jsoriano** [comment]
> @jsoriano If someone upgrades Elasticsearch from 6.7 to 7.0 and keeps Filebeat 6.7, this means the user has to overwrite the ingest pipelines?

@ruflin I think this is only a problem if Filebeat 7.0 is used.

> @jsoriano One more question: I can't see a backport label on this one. Should this also go into 7.0?

It was backported on #10930

**Comment by ruflin** [comment]
FB version: Right, an we recommend to upgrade ES first so we should be good. Probably we should still leave a not about it somewhere.

Backport: 👍

**Comment by andrewkroh** [comment]
I believe this PR is also necessary in the 6.7 branch to allow all modules that use `user_agent` to work with Elasticsearch <=6.6. Additionally, we need to remove the `ecs: false` from the modules and let this PR dynamically add the `ecs` tag as necessary based on the version.

@tsg said he saw, `"processor [user_agent] doesn't support one or more provided configuration parameters [ecs]"` when using Filebeat 6.7 with ES 6.6.
