### PR TITLE
Move HTTP calls to Kibana from New() to Fetch()

### LINKED ISSUE #15258: Metricbeat 7.5.1 with kibana-xpack enabled , fails to start if Kibana is unavailable upon start
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
       Metricbeat : 7.5.1
- Operating System: 
    Redhat linux 7.6
- Discuss Forum URL:
- Steps to Reproduce: 
      Follow documentation to enable kibana-xpack.yml module in metricbeat
     configure kibana-xpack.yml to point at local kibana instance , with credentials
    stop kibana
    start metricbeat
   check status of metricbeat , it is failed
   try launch metricbeat manually , attached error screenshot

  now start kibana
  start metricbeat
  verify all is ok

image

### PR DESCRIPTION
**Pull request by ycombinator**
Resolves #15258.

This PR makes the `kibana/stats` metricset resilient to Kibana's unavailability. 

Before this PR, if Kibana was not already running when Metricbeat was started up with the `kibana-xpack` module enabled, Metricbeat would immediately exit with an error since Kibana was unreachable. 

With this PR, Metricbeat will keep running and retrying to reach Kibana periodically. This also allows Kibana to go away temporarily (say, for an upgrade) and keeps Metricbeat running.

### Testing this PR

1. Build Metricbeat with this PR.
   ```
   cd $GOPATH/src/github.com/elastic/beats/metricbeat
   mage build
   ```

2. Enable the `kibana-xpack` module.
   ```
   ./metricbeat modules enable kibana-xpack
   ```

3. Start up Metricbeat (**without** starting up Kibana).
   ```
   ./metricbeat -e
   ```

4. Note that there are errors in the Metricbeat log about it not being able to connect to Kibana's stats API. But also ensure that Metricbeat keeps running.

5. Start up Kibana.

6. Check the Metricbeat log again. Ensure that eventually (< 1 minute), the connection errors go away. You may see 503 errors now; this is expected when Kibana is starting up. Ensure that eventually (< 2 minutes), the 503 errors go away as well.

7. Ensure that a `.monitoring-kibana-*-mb-*` index for today's date exists. Ensure that it contains recent (`timestamp` within last 20 seconds) documents of `type:kibana_stats`.

8. Stop Kibana.

9. Repeat steps 4-7.

### CODE REVIEW

File: metricbeat/module/kibana/stats/stats.go [hunk 1]
```diff
@@ -67,46 +67,70 @@ func New(base mb.BaseMetricSet) (mb.MetricSet, error) {
...
 	}
 
-	kibanaVersion, err := kibana.GetVersion(statsHTTP, statsPath)
+	now := time.Now()
+
+	err = m.fetchStats(r, now)
 	if err != nil {
-		return nil, err
+		if m.XPackEnabled {
+			m.Logger().Error(err)
```
Comment (ph) [inline metricbeat/module/kibana/stats/stats.go]: @ycombinator Do you really need to have a special handling of erros when xpack is enabled? My understanding is that the error will be returned by the `Fetch()` method and will be logged upstream?

Comment (ycombinator) [reply metricbeat/module/kibana/stats/stats.go]: Yes, this change was specifically made in https://github.com/elastic/beats/pull/12265.

In fact, I'm glad you brought this up — I need to add this same special handling around https://github.com/elastic/beats/pull/15270/files#diff-8710596f0decaae3ca552cedea1eb0a0R81 too!

Comment (ph) [reply metricbeat/module/kibana/stats/stats.go]: Oh good story about the different indices :)

**Comment by ycombinator** [comment]
CI failure is related to this PR:

```
command [go test -cover -coverprofile /tmp/gotestcover-694775026 github.com/elastic/beats/metricbeat/module/kibana/stats]: exit status 1
--- FAIL: TestFetchUsage (0.00s)
    stats_test.go:57: 
        	Error Trace:	stats_test.go:57
        	            				server.go:2007
        	            				server.go:2802
        	            				server.go:1890
        	            				asm_amd64.s:1357
        	Error:      	Not equal: 
        	            	expected: "true"
        	            	actual  : "false"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-true
        	            	+false
        	Test:       	TestFetchUsage
FAIL
coverage: 72.3% of statements
FAIL	github.com/elastic/beats/metricbeat/module/kibana/stats	0.009s
```

Investigating.
