### PR TITLE
x-pack/filebeat/input/awss3 ; Fix nil hit panic when a getter is invoked on input metric

### LINKED ISSUE #36077: [filebeat][awss3][automation] Panic in integration test while polling input metrics for SQS
While working on a fix  - #36054 for the skipped integration tests for `awss3` input integration test , it has been found that 

- [x] There is a panic error when trying to poll `sqsMessagesWaiting` metric

https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-36054/21/consoleText
```
[2023-07-14T13:46:26.042Z] {"log.level":"info","@timestamp":"2023-07-14T13:46:25.818Z","log.logger":"metric_registry","log.origin":{"file.name":"inputmon/input.go","file.line":70},"message":"unregistering","input_type":"aws-s3","id":"test_id","key":"test_id","uuid":"d281d8ad-006a-42e6-8a19-8fcae03d7b2c","ecs.version":"1.6.0"}
[2023-07-14T13:46:26.042Z] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[2023-07-14T13:46:26.042Z] 	panic: runtime error: invalid memory address or nil pointer dereference
[2023-07-14T13:46:26.042Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x33e69fb]
[2023-07-14T13:46:26.042Z] 
[2023-07-14T13:46:26.042Z] goroutine 248962 [running]:
[2023-07-14T13:46:26.042Z] testing.tRunner.func1.2({0x3755600, 0x564e4b0})
[2023-07-14T13:46:26.042Z] 	/var/lib/jenkins/workspace/PR-36054-22-6fc08257-c6b0-4bbe-ac34-b86205d2a2e8/.gvm/versions/go1.19.10.linux.amd64/src/testing/testing.go:1396 +0x24e
[2023-07-14T13:46:26.042Z] testing.tRunner.func1()
[2023-07-14T13:46:26.042Z] 	/var/lib/jenkins/workspace/PR-36054-22-6fc08257-c6b0-4bbe-ac34-b86205d2a2e8/.gvm/versions/go1.19.10.linux.amd64/src/testing/testing.go:1399 +0x39f
[2023-07-14T13:46:26.042Z] panic({0x3755600, 0x564e4b0})
[2023-07-14T13:46:26.042Z] 	/var/lib/jenkins/workspace/PR-36054-22-6fc08257-c6b0-4bbe-ac34-b86205d2a2e8/.gvm/versions/go1.19.10.linux.amd64/src/runtime/panic.go:884 +0x212
[2023-07-14T13:46:26.042Z] github.com/elastic/elastic-agent-libs/monitoring.(*Int).Get(...)
[2023-07-14T13:46:26.042Z] 	/var/lib/jenkins/workspace/PR-36054-22-6fc08257-c6b0-4bbe-ac34-b86205d2a2e8/pkg/mod/github.com/elastic/elastic-agent-libs@v0.3.9/monitoring/metrics.go:64
[2023-07-14T13:46:26.042Z] github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.TestInputRunSNS(0xc000fc8b60)
[2023-07-14T13:46:26.042Z] 	/var/lib/jenkins/workspace/PR-36054-22-6fc08257-c6b0-4bbe-ac34-b86205d2a2e8/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/input_integration_test.go:430 +0x5bb
[2023-07-14T13:46:26.042Z] testing.tRunner(0xc000fc8b60, 0x3ce7058)
[2023-07-14T13:46:26.042Z] 	/var/lib/jenkins/workspace/PR-36054-22-6fc08257-c6b0-4bbe-ac34-b86205d2a2e8/.gvm/versions/go1.19.10.linux.amd64/src/testing/testing.go:1446 +0x10b
[2023-07-14T13:46:26.042Z] created by testing.(*T).Run
[2023-07-14T13:46:26.042Z] 	/var/lib/jenkins/workspace/PR-36054-22-6fc08257-c6b0-4bbe-ac34-b86205d2a2e8/.gvm/versions/go1.19.10.linux.amd64/src/testing/testing.go:1493 +0x35f
[2023-07-14T13:46:26.042Z] 
[2023-07-14T13:46:26.042Z] DONE 1213 tests, 13 skipped, 2 failures in 151.809s
[2023-07-14T13:46:29.754Z] Error: failed to execute go: exit status 1
```

- [x] When polling `sqsWorkerUtilization` metric , the value is always `0`.

https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-36054/22/consoleText

```
[2023-07-14T13:46:26.037Z] {"log.level":"info","@timestamp":"2023-07-14T13:45:52.963Z","log.logger":"metric_registry","log.origin":{"file.name":"inputmon/input.go","file.line":70},"message":"unregistering","input_type":"aws-s3","id":"test_id","key":"test_id","uuid":"1dd685c1-ea08-4288-8966-b209e8061e42","ecs.version":"1.6.0"}
[2023-07-14T13:46:26.037Z]     input_integration_test.go:196: 
[2023-07-14T13:46:26.037Z]         	Error Trace:	/var/lib/jenkins/workspace/PR-36054-22-6fc08257-c6b0-4bbe-ac34-b86205d2a2e8/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/input_integration_test.go:196
[2023-07-14T13:46:26.037Z]         	Error:      	"0" is not greater than "0"
[2023-07-14T13:46:26.037Z]         	Test:       	TestInputRunSQS
```

### PR DESCRIPTION
**Pull request by bhapas**
## What does this PR do?

This PR fixes the panic mentioned in https://github.com/elastic/beats/issues/36077. If an input metrics is not initialised but when a `Get` is invoked on the metric to pull data , then a nil pointer panic is caused.

## Why is it important?

To avoid nil pointer panics when metric getters are invoked

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
~- [ ] I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Without this PR , when `go test -tags aws,integration -run TestInputRunSQS -v` is run from `x-pack/filebeat/input/awss3` then a nil pointer panic is caused and this PR fixes it.

## Related issues

- Closes #36077

### CODE REVIEW

**Comment by bhapas** [comment]
Pinging @elastic/obs-cloud-monitoring as a codeowner

File: x-pack/filebeat/input/awss3/metrics.go [hunk 1]
```diff
@@ -174,6 +174,7 @@ func newInputMetrics(id string, optionalParent *monitoring.Registry, maxWorkers
 		sqsMessagesInflight:                 monitoring.NewUint(reg, "sqs_messages_inflight_gauge"),
 		sqsMessagesReturnedTotal:            monitoring.NewUint(reg, "sqs_messages_returned_total"),
 		sqsMessagesDeletedTotal:             monitoring.NewUint(reg, "sqs_messages_deleted_total"),
+		sqsMessagesWaiting:                  monitoring.NewInt(reg, "sqs_messages_waiting_gauge"),
```
Comment (andrewkroh) [inline x-pack/filebeat/input/awss3/metrics.go:177]: The value is initialized upon first use such that the metric is unreported when it cannot be collected (usually due to lack of SQS permissions). If we initialize it from the start then let also apply these changes:

- Initialize the `sqs_messages_waiting_gauge` value to `-1` so that we can distinguish between and no messages waiting (`0`) and never collected / error collecting (`-1`).
- Remove `setSQSMessagesWaiting()` which does lazy init.

Comment (bhapas) [reply x-pack/filebeat/input/awss3/metrics.go:165]: @andrewkroh 

> Initialize the sqs_messages_waiting_gauge value to -1 so that we can distinguish between and no messages waiting (0) and never collected / error collecting (-1).

Today, the value of `sqs_messages_waiting_gauge` is set every minute in a [pollSQSWaitingMetric](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/input.go#L431) function. Do we want to initialize the value to `0` once we receive messages successfully in `SQSReceiver` [somewhere here](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/sqs.go#L81) and before we start processing go routines for each SQS Message ?

File: x-pack/filebeat/input/awss3/sqs.go [hunk 2]
```diff
@@ -79,7 +79,11 @@ func (r *sqsReader) Receive(ctx context.Context) error {
 		// Process each SQS message asynchronously with a goroutine.
 		r.log.Debugf("Received %v SQS messages.", len(msgs))
 		r.metrics.sqsMessagesReceivedTotal.Add(uint64(len(msgs)))
+		// Initialize the sqs_message_waiting_guage to 0 to indicate that that SQS messages are received.
```
Comment (bhapas) [inline x-pack/filebeat/input/awss3/sqs.go:82]: Will fix this

File: x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc [hunk 3]
```diff
@@ -797,7 +797,7 @@ observe the activity of the input.
 | `sqs_messages_inflight_gauge`             | Number of SQS messages inflight (gauge).
 | `sqs_messages_returned_total`             | Number of SQS message returned to queue (happens on errors implicitly after visibility timeout passes).
 | `sqs_messages_deleted_total`              | Number of SQS messages deleted.
-| `sqs_messages_waiting_gauge`              | Number of SQS messages waiting in the SQS queue (gauge). The value is refreshed every minute via data from GetQueueAttributes.
+| `sqs_messages_waiting_gauge`              | Number of SQS messages waiting in the SQS queue (gauge). The value is refreshed every minute via data from GetQueueAttributes. A value of (0) indicates `no messages waiting` but a value 0f (-1) indicates `metrics not collected/error collecting metrics `
```
Comment (kaiyan-sheng) [inline x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc:800]:
```suggestion
| `sqs_messages_waiting_gauge`              | Number of SQS messages waiting in the SQS queue (gauge). The value is refreshed every minute via data from GetQueueAttributes. A value of (0) indicates `no message waiting` but a value of (-1) indicates `metrics not collected/error collecting metrics `
```

Comment (andrewkroh) [inline x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc:800]:
```suggestion
| `sqs_messages_waiting_gauge`              | Number of SQS messages waiting in the SQS queue (gauge). The value is refreshed every minute via data from https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html<GetQueueAttributes>. A value of `-1` indicates the metric is uninitialized or could not be collected due to an error.
```

Maybe explaining the meaning of 0 in this context is unnecessary.

File: x-pack/filebeat/input/awss3/sqs.go [hunk 4]
```diff
@@ -79,7 +79,11 @@ func (r *sqsReader) Receive(ctx context.Context) error {
...
+		// PollSqsWaitingMetric shall reassign the value if there are messages waiting or if there is an error in processing the messages.
+		r.metrics.sqsMessagesWaiting.Set(int64(0))
```
Comment (andrewkroh) [inline x-pack/filebeat/input/awss3/sqs.go:84]: Why is this change necessary? I see the comment, but I don't understand why we need "to indicate that that SQS messages are received" via this metric. That gives the metric more that one purpose.

File: x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc (hunk 3 above)
Comment (bhapas) [reply x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc:800]: Updated to https://github.com/elastic/beats/pull/36101#discussion_r1268545974

File: x-pack/filebeat/input/awss3/sqs.go (hunk 4 above)
Comment (bhapas) [reply x-pack/filebeat/input/awss3/sqs.go:84]: I think the comment is mis-phrased. The scenario I thought was
- `sqs_message_waiting_gauge` is initialized with a value of `-1`
- [PollSqsWaitingMetric](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/input.go#L411) function checks and updates this metric every minute , but if the SQS messages are received and processed in less than a minute, then this metric is never updated? Then if this metric is polled, the value will be returned as `-1` which gives wrong interpretation. So , this line would set a value to `0` if the SQS messages are successfully received and the next step would be to invoke individual `go routines` to process each SQS message.

Do you think there could be a better way to achieve this?

Comment (bhapas) [reply x-pack/filebeat/input/awss3/sqs.go:84]: I think, this can be moved to [PollSqsWaitingMetric](https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/input.go#L411) function to initialize the value to `0` just at the start of `one minute` time interval.

**Review by kaiyan-sheng — APPROVED** [review]
This looks good to me but I'd like to get @andrewkroh 's approval on this before merging. Thanks!

File: x-pack/filebeat/input/awss3/input.go [hunk 5]
```diff
@@ -411,6 +411,10 @@ func getProviderFromDomain(endpoint string, ProviderOverride string) string {
 func pollSqsWaitingMetric(ctx context.Context, receiver *sqsReader) {
 	t := time.NewTicker(time.Minute)
 	defer t.Stop()
+	// Initialize the metric to 0 at the start of the one minute time interval to avoid
+	// giving misleading metric value -1 even though SQS messages are processed.
+	// The value will be updated every minute
+	receiver.metrics.sqsMessagesWaiting.Set(int64(0))
```
Comment (andrewkroh) [inline x-pack/filebeat/input/awss3/input.go:417]: I think this is more misleading to report 0. We now have documented that "-1 indicates the metric is uninitialized". And uninitialized is the state that it is in until the timer executes the first time. So reporting -1 is correct. Reporting 0 means it observed the SQS queue ApproximateMessageCount to be zero, but that's not what happened.

If you want this metric to be initialized earlier then I would refactor this to execute the first `GetQueueAttributes` request before starting the timer.

**Review by andrewkroh — APPROVED** [review]
