### PR TITLE
[x-pack][metricbeat][iis] improve error handling on pdh counters in application_pool data stream

### LINKED ISSUE #41596: [IIS] [application_pool] Element Not Found for Application Pools with 'No Managed Code'
Application pools configured with "No Managed Code" are for applications that do not use .NET's CLR (Common Language Runtime), such as PHP or native applications. 

In this case, the .NET CLR counters such as Exceptions will not be associated with the w3wp process because those counters are specific to managed code environments. This leads to errors being thrown in the logs by metricbeat.

The goal of this issue is to bypass errors for those specific environments, specifically for counters, such as:
```
Element not found.failed to expand counter path (query= "%v")\.NET CLR Exceptions(w3wp*)\# of Finallys / sec
Element not found.failed to expand counter path (query= "%v")\.NET CLR Exceptions(w3wp*)\# of Exceps Thrown / sec
Element not found.failed to expand counter path (query= "%v")\.NET CLR Exceptions(w3wp*)\# of Exceps Thrown
Element not found.failed to expand counter path (query= "%v")\.NET CLR Exceptions(w3wp*)\# of Filters / sec
Element not found.failed to expand counter path (query= "%v")\.NET CLR Exceptions(w3wp*)\Throw To Catch Depth / sec
```

### PR DESCRIPTION
**Pull request by stefans-elastic**
## Proposed commit message

The error occurs [initAppPools](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/iis/application_pool/reader.go#L104) > calls [GetCounterPaths](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/iis/application_pool/reader.go#L117) > calls [ExpandWildCardPath](https://github.com/elastic/beats/blob/main/metricbeat/helper/windows/pdh/pdh_query_windows.go#L113) > calls [PdhExpandWildCardPath](https://github.com/elastic/beats/blob/main/metricbeat/helper/windows/pdh/pdh_query_windows.go#L227) which returns no data and no error > `PdhExpandWildCardPath`returns `PdhErrno(syscall.ERROR_NOT_FOUND)` error [here](https://github.com/elastic/beats/blob/main/metricbeat/helper/windows/pdh/pdh_query_windows.go#L249) > the error returns all the way back to `initAppPools` and since the error type isn't part of this [condition](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/iis/application_pool/reader.go#L119) an error log appears (logged [here](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/iis/application_pool/reader.go#L123)).

On why PDH's function returns no data and no error - I didn't find a coverage of this behavior in the [docs](https://learn.microsoft.com/en-us/windows/win32/api/pdh/nf-pdh-pdhexpandwildcardpathw). My guess is that object/counter exists but has no data in it (for w3wp process).
The fix I suggest is simply adding a check for `PdhErrno(syscall.ERROR_NOT_FOUND)` error in this [condition](https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/iis/application_pool/reader.go#L119) which prevents those errors causing unnecessary error level log entries.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #41596

## Screenshots

Before the change (`Element not found.failed to expand counter path` errors show up in the logs)
Screenshot 2025-01-09 at 2 14 55 PM

After the change (NO `Element not found.failed to expand counter path` errors show up in the logs)
Screenshot 2025-01-09 at 2 03 47 PM

### CODE REVIEW

**Comment by shmsr** [comment]
```diff
diff --git a/x-pack/metricbeat/module/iis/application_pool/reader.go b/x-pack/metricbeat/module/iis/application_pool/reader.go
index 61522ba128..e11e1381f0 100644
--- a/x-pack/metricbeat/module/iis/application_pool/reader.go
+++ b/x-pack/metricbeat/module/iis/application_pool/reader.go
@@ -10,6 +10,7 @@ import (
 	"errors"
 	"fmt"
 	"strings"
+	"syscall"
 
 	"github.com/elastic/beats/v7/metricbeat/helper/windows/pdh"
 	"github.com/elastic/elastic-agent-libs/mapstr"
@@ -111,16 +112,26 @@ func (r *Reader) initAppPools() error {
 		r.log.Info("no running application pools found")
 		return nil
 	}
+
+	isPDHError := func(err error) bool {
+		return errors.Is(err, pdh.PdhErrno(syscall.ERROR_NOT_FOUND)) ||
+			errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTER) ||
+			errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTERNAME) ||
+			errors.Is(err, pdh.PDH_CSTATUS_NO_INSTANCE) ||
+			errors.Is(err, pdh.PDH_CSTATUS_NO_OBJECT)
+	}
+
 	var newQueries []string
 	r.workerProcesses = make(map[string]string)
 	for key, value := range appPoolCounters {
 		childQueries, err := r.query.GetCounterPaths(value)
 		if err != nil {
-			if errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTER) || errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTERNAME) || errors.Is(err, pdh.PDH_CSTATUS_NO_INSTANCE) || errors.Is(err, pdh.PDH_CSTATUS_NO_OBJECT) {
+			if isPDHError(err) {
 				r.log.Infow("Ignoring non existent counter", "error", err,
-					logp.Namespace("application pool"), "query", value)
+					logp.Namespace("application pool"), "query", value,
+				)
 			} else {
-				r.log.Error(err, `failed to expand counter path (query= "%v")`, value)
+				r.log.Errorf(`failed to expand counter path (query= "%v"): %w`, value, err)
 			}
 			continue
 		}
```

Your changes look but I do have some suggestion to make the change more readable. Also, the log "failed to expand counter path" has a bug. I have fixed it, so could you please make that change as well?

**Comment by shmsr** [comment]
^ Just one comment; rest looks good.

**Comment by stefans-elastic** [comment]
> ^ Just one comment; rest looks good.

thanks for review @shmsr!  I've added suggested changes

File: x-pack/metricbeat/module/iis/application_pool/reader.go [hunk 1]
```diff
@@ -111,16 +112,24 @@ func (r *Reader) initAppPools() error {
 		r.log.Info("no running application pools found")
 		return nil
 	}
+	isPDHError := func(err error) bool {
+		return errors.Is(err, pdh.PdhErrno(syscall.ERROR_NOT_FOUND)) ||
+			errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTER) ||
+			errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTERNAME) ||
+			errors.Is(err, pdh.PDH_CSTATUS_NO_INSTANCE) ||
+			errors.Is(err, pdh.PDH_CSTATUS_NO_OBJECT)
+	}
```
Comment (lucian-ioan) [inline x-pack/metricbeat/module/iis/application_pool/reader.go:121]: I think a description would be useful here for future devs looking at this code, for example:

    // Helper function to identify known PDH errors, such as missing counters or instances.
    // These errors are expected in certain cases (e.g., "No Managed Code" environments).

File: x-pack/metricbeat/module/iis/application_pool/reader.go [hunk 2]
```diff
@@ -111,16 +112,24 @@ func (r *Reader) initAppPools() error {
...
-			if errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTER) || errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTERNAME) || errors.Is(err, pdh.PDH_CSTATUS_NO_INSTANCE) || errors.Is(err, pdh.PDH_CSTATUS_NO_OBJECT) {
+			if isPDHError(err) {
 				r.log.Infow("Ignoring non existent counter", "error", err,
-					logp.Namespace("application pool"), "query", value)
+					logp.Namespace("application pool"), "query", value,
+				)
 			} else {
-				r.log.Error(err, `failed to expand counter path (query= "%v")`, value)
+				r.log.Errorf(`failed to expand counter path (query= "%v"): %w`, value, err)
 			}
```
Comment (lucian-ioan) [inline x-pack/metricbeat/module/iis/application_pool/reader.go:133]: // Handle known PDH errors as informational (e.g., missing counters).

File: x-pack/metricbeat/module/iis/application_pool/reader.go [hunk 3]
```diff
@@ -111,16 +112,24 @@ func (r *Reader) initAppPools() error {
...
 		if err != nil {
-			if errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTER) || errors.Is(err, pdh.PDH_CSTATUS_NO_COUNTERNAME) || errors.Is(err, pdh.PDH_CSTATUS_NO_INSTANCE) || errors.Is(err, pdh.PDH_CSTATUS_NO_OBJECT) {
+			if isPDHError(err) {
 				r.log.Infow("Ignoring non existent counter", "error", err,
-					logp.Namespace("application pool"), "query", value)
+					logp.Namespace("application pool"), "query", value,
+				)
 			} else {
-				r.log.Error(err, `failed to expand counter path (query= "%v")`, value)
+				r.log.Errorf(`failed to expand counter path (query= "%v"): %w`, value, err)
```
Comment (lucian-ioan) [inline x-pack/metricbeat/module/iis/application_pool/reader.go:132]: Same for this logic:

   ` // Helper function to identify known PDH errors, such as missing counters or instances.`

**Review by lucian-ioan — APPROVED** [review]
LGTM, I'd comment code changes but it's up to you.

**Comment by shmsr** [comment]
> > ^ Just one comment; rest looks good.
> 
> thanks for review @shmsr! I've added suggested changes

Sorry missed this. I'll approve but yes +1 to Lucian's comments.

**Review by shmsr — APPROVED** [review]

File: x-pack/metricbeat/module/iis/application_pool/reader.go (hunk 3 above)
Comment (stefans-elastic) [reply x-pack/metricbeat/module/iis/application_pool/reader.go:135]: added the comment

File: x-pack/metricbeat/module/iis/application_pool/reader.go (hunk 1 above)
Comment (stefans-elastic) [reply x-pack/metricbeat/module/iis/application_pool/reader.go:123]: added the comment
