### PR TITLE
libbeat/filebeat/metricbeat: fix typos in runtime errors, configs, and field descriptions

### LINKED ISSUE #49189: [text-auditor] Fix multiple user-facing typos in runtime errors and documentation
## Text Improvements

The following user-facing text issues were found in the repository. Each is a low-effort fix.

### 1. Typo in config validation error message

**File:** `libbeat/cmd/instance/beat.go` (line 159)  
**Current text:** `'restart_on_cert_change.period' must be equal or greather than 1s`  
**Suggested fix:** `'restart_on_cert_change.period' must be equal or greater than 1s`  
**Why:** Clear spelling error in a user-visible validation error.

### 2. Typo in runtime error message

**File:** `libbeat/cmd/instance/beat.go` (line 1008)  
**Current text:** `beat meta file failed to encode vaules: %w`  
**Suggested fix:** `beat meta file failed to encode values: %w`  
**Why:** Clear spelling error in a propagated runtime error.

### 3. Typo in setup warning text

**File:** `libbeat/idxmgmt/index_support.go` (line 221)  
**Current text:** `Loading template with ILM settings whithout loading ILM policy can lead to issues and is not recommended. Check your configuration.`  
**Suggested fix:** `Loading template with ILM settings without loading ILM policy can lead to issues and is not recommended. Check your configuration.`  
**Why:** Clear spelling error in user-facing warning output.

### 4. Typo in Filebeat input reference comment

**File:** `filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl` (line 349)  
**Current text:** `You can filter messsages in the parsers pipeline.`  
**Suggested fix:** `You can filter messages in the parsers pipeline.`  
**Why:** Clear spelling error in user-facing configuration docs.

### 5. Typo in Kafka output Kerberos description

**File:** `libbeat/_meta/config/output-kafka.reference.yml.tmpl` (line 152)  
**Current text:** `Service principal name is contructed from`  
**Suggested fix:** `Service principal name is constructed from`  
**Why:** Clear spelling error in user-facing configuration docs.

### 6. Typo in top-level README beat description

**File:** `README.md` (line 27)  
**Current text:** `Runs Osquery and manages interraction with it.`  
**Suggested fix:** `Runs Osquery and manages interaction with it.`  
**Why:** Clear spelling error in primary user-facing documentation.

### 7. Multiple clear typos/grammar errors in autodiscover README

**File:** `libbeat/autodiscover/README.md` (lines 181, 184)  
**Current text:**
- `Wether hints are enabled or not ...`
- `... as if they where set explicitly in the metricbeat configureation ...`

**Suggested fix:**
- `Whether hints are enabled or not ...`
- `... as if they were set explicitly in the Metricbeat configuration ...`

**Why:** Unambiguous spelling and grammar errors in user-facing docs.

## Suggested Actions

- [ ] Fix `greather` -> `greater` in `libbeat/cmd/instance/beat.go`.
- [ ] Fix `vaules` -> `values` in `libbeat/cmd/instance/beat.go`.
- [ ] Fix `whithout` -> `without` in `libbeat/idxmgmt/index_support.go`.
- [ ] Fix `messsages` -> `messages` in `filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl`.
- [ ] Fix `contructed` -> `constructed` in `libbeat/_meta/config/output-kafka.reference.yml.tmpl`.
- [ ] Fix `interraction` -> `interaction` in `README.md`.
- [ ] Fix `Wether/where/configureation` (and capitalization of `Metricbeat`) in `libbeat/autodiscover/README.md`.

---
[What is this?](https://ela.st/github-ai-tools) | [From workflow: Text Auditor](https://github.com/elastic/beats/actions/runs/22578176237)

Give us feedback! React with 🚀 if perfect, 👍 if helpful, 👎 if not.
> - [x] expires  on Mar 9, 2026, 1:39 PM UTC

### LINKED ISSUE #49404: [text-auditor] Fix three clear user-facing runtime typo messages
## Text Improvements

The following user-facing text issues were found in the repository. Each is a low-effort fix.

### 1. Typo in datetime format parse error

**File:** `libbeat/common/dtfmt/fmt.go` (line 245)  
**Current text:** `unsupport format '%c'`  
**Suggested fix:** `unsupported format '%c'`  
**Why:** Clear typo in an error returned to users when an unsupported token is used.

### 2. Typo in filestream registry read error log

**File:** `filebeat/input/filestream/internal/input-logfile/store.go` (line 873)  
**Current text:** `Failed to read regisry state for '%v', cursor state will be ignored. Error was: %+v`  
**Suggested fix:** `Failed to read registry state for '%v', cursor state will be ignored. Error was: %+v`  
**Why:** Clear typo in operational error output shown to operators.

### 3. Typo in enum string surfaced in invalid-type errors

**File:** `x-pack/filebeat/processors/aws_vpcflow/types.go` (line 37)  
**Current text:** `invaild(%d)`  
**Suggested fix:** `invalid(%d)`  
**Why:** Clear typo in `String()` output used by the user-facing error `invalid data type: %v`.

## Completeness Check

Searched for each typo family and verified all in-scope occurrences:

- `unsupport format` → `libbeat/common/dtfmt/fmt.go:245`
- `regisry` → `filebeat/input/filestream/internal/input-logfile/store.go:873` (plus one internal comment typo in `libbeat/statestore/backend/memlog/memlog.go:47`, omitted from issue scope as non-user-facing comment)
- `invaild\(` → `x-pack/filebeat/processors/aws_vpcflow/types.go:37`

## Suggested Actions

- [ ] Update `unsupport` to `unsupported` in `libbeat/common/dtfmt/fmt.go`.
- [ ] Update `regisry` to `registry` in `filebeat/input/filestream/internal/input-logfile/store.go`.
- [ ] Update `invaild` to `invalid` in `x-pack/filebeat/processors/aws_vpcflow/types.go` and keep error output consistent.

---
[What is this?](https://ela.st/github-ai-tools) | [From workflow: Text Auditor](https://github.com/elastic/beats/actions/runs/22955102512)

Give us feedback! React with 🚀 if perfect, 👍 if helpful, 👎 if not.
> - [x] expires  on Mar 18, 2026, 1:43 PM UTC

### PR DESCRIPTION
**Pull request by strawgate**
## Summary

Fix ~30 spelling and grammar typos across elastic-agent-data-plane owned files. All changes are purely cosmetic text corrections with no functional impact.

**libbeat:**
- `libbeat/cmd/instance/beat.go`: `greather` → `greater`, `vaules` → `values` (runtime error messages)
- `libbeat/idxmgmt/index_support.go`: `whithout` → `without` (log warning)
- `libbeat/cmd/completion.go`: `bash and zsh only by the moment` → `for now` (CLI help text)
- `libbeat/autodiscover/README.md`: `Wether`, wrong `where`, `configureation`
- `libbeat/_meta/config/output-kafka.reference.yml.tmpl`: `contructed` → `constructed`
- `libbeat/common/dtfmt/fmt.go`: `unsupport format` → `unsupported format` (error string)
- `x-pack/libbeat/processors/add_nomad_metadata/docs/`: `Avaliable` → `Available`

**filebeat:**
- `filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl`: `messsages`, `not file` → `no file`
- `filebeat/processor/add_kubernetes_metadata/matchers.go`: `uid` → `UID`, `contains` → `contain`
- `filebeat/input/filestream/internal/input-logfile/store.go`: `regisry` → `registry`
- `x-pack/filebeat/processors/aws_vpcflow/types.go`: `invaild` → `invalid`

**metricbeat/module/system:**
- `core/_meta/fields.yml`: `availabe` → `available` (×5), `might might` → `might`
- `process/_meta/fields.yml`: `threshhold` → `threshold` (×6)
- `diskio/_meta/fields.yml`: duplicate `of of`

**Other:**
- `README.md`: `interraction` → `interaction`
- `testing/environments/README.md`: `an` → `and`, `ony our` → `on your`, `an other` → `another`
- `docs/reference/*/configuration-ssl.md`: `normaly` → `normally`
- `docs/reference/*/add-nomad-metadata.md`: `Avaliable` → `Available`
- `docs/reference/filebeat/filebeat-input-*.md`: `Ukranian` → `Ukrainian`

Closes #49189
Closes #49404
Closes partial #49470
Closes partial #49496
Closes partial #49352

## Test plan
- [ ] Verify runtime error message fixes in beat.go and index_support.go
- [ ] Verify CLI help text fix in completion.go
- [ ] Verify field description fixes in system module
- [ ] Run `mage update` and confirm no unexpected diffs

### CODE REVIEW

**Comment by vishaangelova** [comment]
This needs to be backported to 9.3 for the docs changes to be published to the docs site (we publish from the latest minor branch).

File: filebeat/processor/add_kubernetes_metadata/matchers.go [hunk 1]
```diff
@@ -88,7 +88,10 @@ func (f *LogPathMatcher) MetadataIndex(event mapstr.M) string {
 		return ""
 	}
 
-	source := value.(string)
+	source, ok := value.(string)
+	if !ok {
+		return ""
```
Comment (strawgate) [inline filebeat/processor/add_kubernetes_metadata/matchers.go:94]: this feels like it needs a log message

Comment (strawgate) [reply filebeat/processor/add_kubernetes_metadata/matchers.go:94]: i assume we need to do this because we're touching the file and so we need to make the linter happy

File: libbeat/cmd/completion.go [hunk 2]
```diff
@@ -29,22 +28,28 @@ import (
...
+				}
 			case "zsh":
-				rootCmd.GenZshCompletion(os.Stdout)
+				if err := rootCmd.GenZshCompletion(os.Stdout); err != nil {
+					cmd.PrintErrf("Error generating zsh completion: %s\n", err)
+					os.Exit(1)
+				}
 			default:
-				fmt.Printf("Unknown shell %s, only bash and zsh are available\n", args[0])
+				cmd.PrintErrf("Unknown shell %s, only bash and zsh are available\n", args[0])
```
Comment (strawgate) [inline libbeat/cmd/completion.go]: let's not make this change

**Review by pierrehilbert — APPROVED** [review]
