### PR TITLE
x-pack/filebeat/input/cel: log unpublished event count and exit publish loop on context cancellation

### LINKED ISSUE #47717: [filebeat] CEL input - reduce log error volume on shutdown
During a graceful shutdown of the CEL input it can flood the log file with 100k+ errors in a matter of a few seconds.

When the publishing fails due to `context cancelled` then no further publish calls will succeed. To avoid the log noise, the input could begin its shutdown at this stage and skip logging additional errors. It should log the count of pending events that have been discarded.

```json
{
  "error": {
    "message": "context canceled"
  },
  "event": {
    "agent_id_status": "auth_metadata_missing",
    "dataset": "agentless.log",
    "ingested": "2025-11-19T08:14:09Z"
  },
  "id": "cel-mimecast.siem_logs-7756f6de-0f81-4193-b543-c694ed8981dc",
  "input_source": "https://api.services.mimecast.com",
  "log.level": "error",
  "log.origin": {
    "file.line": 550,
    "file.name": "cel/input.go",
    "function": "github.com/elastic/beats/v7/x-pack/filebeat/input/cel.input.run.func1"
  },
  "message": "error publishing event"
}
```

https://github.com/elastic/beats/blob/65e1f2d24901a3f3f67d1c1de64ddb3d146c0b3f/x-pack/filebeat/input/cel/input.go#L544-L558

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

See title.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works. Where relevant, I have used the [`stresstest.sh`](https://github.com/elastic/beats/blob/main/script/stresstest.sh) script to run them under stress conditions and race detector to verify their stability.
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent-changelog-tool/blob/main/docs/usage.md).

## Author's Checklist

- [ ]

## Related issues

- Closes #47717

### CODE REVIEW

File: x-pack/filebeat/input/cel/input.go [hunk 1]
```diff
@@ -541,6 +541,25 @@ func (i input) run(env v2.Context, src *source, cursor map[string]interface{}, p
...
+					// Don't update status, since we are about to pass
+					// through the Running state and then fall through
+					// to the input exit with a change to Stopped.
+					break
+				default:
+					// This should never happen.
+					log.Warnw("failed with unpublished events", "error", err, "unpublished", len(events)-i)
+					health.UpdateStatus(status.Degraded, "error publishing events: "+err.Error())
+					isDegraded = true
+					break
```
Comment (ShourieG) [inline x-pack/filebeat/input/cel/input.go]: I had one question here, in the default case it signals something critical or unexpected, so why are we breaking and going back to sleep instead of returning and stopping the input as a whole ? Should we even expect recoverability in this scenario ?

Comment (efd6) [reply x-pack/filebeat/input/cel/input.go]: Not exactly what you're asking, but thanks for point this out. The breaks should be for the loop, not the switch (also identified by staticcheck). Fixing this mitigates the concern, though…

The default should never happen (as noted in the comment). The only way that it can happen is if there is a change in the contexts are cancelled elsewhere by use of [`context.CancelWithCause`](https://pkg.go.dev/context#WithCancelCause). I would hope that if this happens, it would be widely advertised. Though, even if it doesn't it would be caught at L584 in the `ctx.Err()` check, and then exited at the bottom of the function.
