### PR TITLE
Calculate memory.working_set.limit.pct for pod and container metricset

### LINKED ISSUE #25657: Metricbeat 7.12.1 kubernetes.container.memory.usage.limit.pct is calculated incorrectly
Hi,

Metricbeat is providing the kubernetes.container.memory.usage.limit.pct value by obtaining the memory.max_usage_in_bytes (which can be divined by setting a resource memory limit in the kubernetes deployment) and dividing it by the kubernetes.container.memory.usage.bytes.

While kubernetes is OOM killing containers based on the kubernetes.container.memory.workingset.bytes. Meaning that the kubernetes.container.memory.usage.limit.pct currently is not a good value to have alerting on, since the kubernetes.container.memory.usage.bytes is higher than the kubernetes.container.memory.workingset.bytes and giving false positives that the container is almost OOM killed, while in reality it is still okay, until the kubernetes.container.memory.workingset.bytes is reaching the resource memory limit.

Is it possible to adjust the kubernetes.container.memory.usage.limit.pct based on the kubernetes.container.memory.workingset.bytes?

### PR DESCRIPTION
**Pull request by MichaelKatsoulis**
## What does this PR do?

This PR calculates and adds `memory.working_set.limit.pct` for kubernetes pod metricset and `memory.workingset.limit.pct` for kubernetes container metricset.
The value is calculated as the division of `workingset_bytes/memory_limit`.

## Why is it important?

The fields `kubernetes.container.memory.usage.limit.pct` and `kubernetes.container.memory.usage.node.pct` are useful fields that show  the total allocated memory for the container/pod divided with either the limit set by user or the node's total memory.

But the total allocated memory also includes buffer and cache bytes which are not actively used and so they are available by other processes. It is useful to provide the `workingset_bytes` of the container/pod divided with the container's limit as a value that shows the actual usage percentage of a container/pod.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Run metricbeat on Kubernetes with `container` or `pod` metricset enabled and watch the values being populated.

## Related issues

- Closes https://github.com/elastic/enhancements/issues/13999
- Closes #25657

## Screenshots

workingset limit

### CODE REVIEW

File: metricbeat/module/kubernetes/pod/data.go [hunk 1]
```diff
@@ -128,6 +128,8 @@ func eventMapping(content []byte, perfMetrics *util.PerfMetricsCache) ([]common.
 			}
 			if memLimit > 0 {
 				podEvent.Put("memory.usage.limit.pct", float64(usageMem)/memLimit)
+				podEvent.Put("memory.working_set.limit.pct", float64(workingSet)/memLimit)
```
Comment (tetianakravchenko) [inline metricbeat/module/kubernetes/pod/data.go:131]: what is the reason that for pod it is `working_set`, but for container `workingset`?

Comment (tetianakravchenko) [reply metricbeat/module/kubernetes/pod/data.go:131]: ok, I see - it is defined in `_meta/fields` - https://github.com/elastic/beats/pull/29547/files#diff-5fcfa3afa9fada7a95134f06d96a95a70c9a6002dc74bb000f8c5848bd87bb2fR89

**Review by tetianakravchenko — APPROVED** [review]

File: metricbeat/module/kubernetes/pod/data.go (hunk 1 above)
Comment (MichaelKatsoulis) [reply metricbeat/module/kubernetes/pod/data.go:131]: In `container` [fields](https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/container/_meta/fields.yml#L121) the field group is `workingset `  while in `pod` [fields](https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/pod/_meta/fields.yml#L89)  it is `working_set `.

This may have happened by mistake but now if I fix this it will a breaking change. So I had to follow this naming.

**Review by ChrsMark — COMMENTED** [review]
Lgtm. I see that we have an "inconsistency" in the naming and it is `workinset` in `container` metricset while it is `working_set` in `pod` metricset. In any case we cannot do much here without introducing a breaking change 😞 .

@MichaelKatsoulis do you also plan to add it in the package too?

Also @MichaelKatsoulis what do you think about closing https://github.com/elastic/beats/issues/25657 too after this one is merged?

**Comment by MichaelKatsoulis** [comment]
> Lgtm. I see that we have an "inconsistency" in the naming and it is `workinset` in `container` metricset while it is `working_set` in `pod` metricset. In any case we cannot do much here without introducing a breaking change 😞 .

:(

> @MichaelKatsoulis do you also plan to add it in the package too?

I will open a PR for this as well.

> Also @MichaelKatsoulis what do you think about closing #25657 too after this one is merged?

Yes I agree.
