### PR TITLE
prospector: cache resolved glob patterns during init

### LINKED ISSUE #4182: Filebeat - Error in load states when enable the recursive glob
Please help to check the problem.
Version: master
Operating System: SUSE11
Steps to Reproduce: 
1. enable the recursive glob.
2. use ** in the path as /home/cmp/**/*.log
3. start the main_test, and it will collect the log
4. restart the filebeat, when it load the exist states, it will drop the actually marched source.
<pre><code>		match, err = filepath.Match(glob, filePath)
		if err != nil {
			logp.Debug("prospector", "Error matching glob: %s", err)
			continue
		}</code></pre>
The glob is /home/cmp/**/*.log, if the filePath is /home/cmp/a/b/c.log, the match will be *false*. Then the source will be dropped, which is an unexpected behavior.
Then the filebeat will collect the log from beginning, which is duplicately.

### PR DESCRIPTION
**Pull request by 7AC**
Before this change recursive glob patterns were resolved only at runtime, so everytime filebeat restarted it would try to recover its previous state without expanding the patterns first. With this change we expand the patterns once and for all during init, fixing both the start and the restart case.

Resolves #4182

### CODE REVIEW

File: filebeat/prospector/prospector_log.go [hunk 1]
```diff
@@ -42,12 +43,33 @@ func NewLog(p *Prospector) (*Log, error) {
 	return prospectorer, nil
 }
 
+func (l *Log) resolvePaths() error {
+	if l.paths != nil {
```
Comment (andrewkroh) [inline filebeat/prospector/prospector_log.go]: I would avoid making a distinction between non-nil and zero length slices. This can lead to subtle programming mistakes. I would check for `len(l.paths) > 0`

File: filebeat/prospector/prospector_log.go [hunk 2]
```diff
@@ -42,12 +43,33 @@ func NewLog(p *Prospector) (*Log, error) {
...
+		return nil
+	}
+	if !l.config.recursiveGlob {
+		l.paths = l.config.Paths
+		return nil
+	}
+	l.paths = []string{}
```
Comment (andrewkroh) [inline filebeat/prospector/prospector_log.go]: This is unnecessary if you check the `len()` of the slice above, rather than for non-nil.

File: filebeat/prospector/prospector_log.go (hunk 1 above)
Comment (7AC) [inline filebeat/prospector/prospector_log.go]: thanks, yeah I prefer that too

File: filebeat/prospector/prospector_log.go (hunk 2 above)
Comment (7AC) [inline filebeat/prospector/prospector_log.go]: 👍

**Comment by ruflin** [comment]
@7AC I didn't check the PR yet but I strongly recommend to add some system test to it to check if everything goes well during restart. I remember doing the first implementation without the "extra glob" was a bit tricky, especially on windows. We must make sure the right paths are picked up again.

File: filebeat/prospector/config.go [hunk 3]
```diff
@@ -53,3 +55,25 @@ func (config *prospectorConfig) Validate() error {
 
 	return nil
 }
+
+func (config *prospectorConfig) resolvePaths() error {
+	var paths []string
+	if !config.recursiveGlob {
```
Comment (ruflin) [inline filebeat/prospector/config.go]: The reason this is not working is that `recursiveGlob` is a private variable and golang can only extract values in global variables. You must set it to `RecursiveGlob` in prospectorConfig.

Comment (7AC) [inline filebeat/prospector/config.go]: 👍

File: filebeat/tests/system/test_prospector.py [hunk 4]
```diff
@@ -678,3 +680,48 @@ def test_prospector_filter_includefields(self):
...
+        with open(testfile_path, 'w') as testfile:
+            testfile.write("entry1\n")
+
+        self.wait_until(
+            lambda: self.output_has_message("entry1"),
+            max_timeout=10,
+            name="output contains 'entry1'")
+
+        # Wait a momemt to make sure registry is completely written
+        time.sleep(1)
```
Comment (ruflin) [inline filebeat/tests/system/test_prospector.py]: Sleep is very flaky with these kind of things. We normally rely on the log_contains messages here. Check some other tests for it.

File: filebeat/tests/system/test_registrar.py [hunk 5]
```diff
@@ -1396,3 +1398,8 @@ def test_registrar_files_with_prospector_level_processors(self):
                 "inode": stat.st_ino,
                 "device": stat.st_dev,
             }, file_state_os)
+
+
+if __name__ == '__main__':
```
Comment (ruflin) [inline filebeat/tests/system/test_registrar.py]: With this addition, can you directly "run" the file without prepending it with nosetests?

File: libbeat/tests/system/beat/beat.py [hunk 6]
```diff
@@ -350,6 +353,16 @@ def output_has(self, lines, output_file=None):
         except IOError:
             return False
 
+    def output_has_message(self, message, output_file=None):
```
Comment (ruflin) [inline libbeat/tests/system/beat/beat.py]: That will become handy in other tests too.

File: filebeat/tests/system/test_prospector.py (hunk 4 above)
Comment (7AC) [inline filebeat/tests/system/test_prospector.py]: It's copy/paste from `test_registrar.py` (had the same observation btw :) I don't think I need it here anyways I'll remove it

File: filebeat/tests/system/test_registrar.py (hunk 5 above)
Comment (7AC) [inline filebeat/tests/system/test_registrar.py]: yep, just need to `pip install` a couple of things

File: libbeat/tests/system/beat/beat.py (hunk 6 above)
Comment (7AC) [inline libbeat/tests/system/beat/beat.py]: Yeah, I tried working with the existing APIs but checking the length wasn't enough since when I restart I want to check for the different message to show up (length still 1)

File: filebeat/tests/system/test_prospector.py [hunk 7]
```diff
@@ -678,3 +680,45 @@ def test_prospector_filter_includefields(self):
...
+        with open(testfile_path, 'a') as testfile:
+            testfile.write("entry2\n")
+
+        filebeat = self.start_beat(output="filebeat2.log")
+
+        self.wait_until(
+            lambda: self.output_has_message("entry2"),
+            max_timeout=10,
+            name="output contains 'entry2'")
+
```
Comment (ruflin) [inline filebeat/tests/system/test_prospector.py]: filebeat must be stopped again here.

File: CHANGELOG.asciidoc [hunk 8]
```diff
@@ -31,6 +31,7 @@ https://github.com/elastic/beats/compare/v6.0.0-alpha1...master[Check the HEAD d
 - Fix importing the dashboards when the limit for max open files is too low. {issue}4244[4244]
 
 *Filebeat*
+- Make recursive glob resolution work across restarts. {pull}4269[4269]
```
Comment (ruflin) [inline CHANGELOG.asciidoc]: Should this be "make recursive glob working"? Not sure it was working before?

File: filebeat/tests/system/test_prospector.py (hunk 7 above)
Comment (7AC) [inline filebeat/tests/system/test_prospector.py]: done

File: CHANGELOG.asciidoc (hunk 8 above)
Comment (7AC) [inline CHANGELOG.asciidoc]: I rephrased it
