### PR TITLE
Fix permissions of generated Filebeat filesets

### LINKED ISSUE #6856: Fix file permissions of generated files by module and fileset generator
Right now thanks to permission problems snapshot builds fail every time a generated module is merged to upstream.

The current permission is 755. This has to be set to 644.

### PR DESCRIPTION
**Pull request by kvch**
Closes #6856

### CODE REVIEW

File: filebeat/scripts/generator/generator.go [hunk 1]
```diff
@@ -70,7 +70,8 @@ func copyTemplate(template, dest string, replace map[string]string) error {
 	if err != nil {
 		return fmt.Errorf("cannot copy template: %v", err)
 	}
-	return nil
+
+	return os.Chmod(dest, 0644)
```
Comment (andrewkroh) [inline filebeat/scripts/generator/generator.go]: `0644` should be passed to the `ioutil.WriteFile` rather than doing this in a separate syscall.

On a side note, it looks like this file is is incorrectly using `os.ModePerm`. Generally this value is used as a mask with mode bits to isolate the permission bits (e.g. `perm = fileinfo.Mode() & os.ModePerm`). Writing a file with `0777` should almost never be done for security reasons. In most cases if you are creating a file without any sensitive data use `0644` and if it's a dir use `0755`.

**Comment by ruflin** [comment]
@kvch If it's also a problem in master, I would suggest to open it against master and then do the backport with out backport scripts.

**Comment by kvch** [comment]
I meant if the developer changelog is the correct changelog to put this entry.
But you are right, this should be backported.

**Comment by ruflin** [comment]
@kvch Argh, sorry. I was looking at an other PR against 6.2 and saw this comment and thought I'm still in the same PR. Ignore my comment.

+1 on where you added it.
