### PR TITLE
Fix decode_cef handling of escaped LF and CR

### LINKED ISSUE #16995: Filebeat decode_cef parser error with \n\r chars in message
The filebeat decode_cef function doesn't skip the new lines chars if are present into message field.

es.
`event.original: "CEF:0|Trend Micro|Deep Security Manager|12.0.393|771|Contact by Unrecognized Client|6|src=10.41.128.199 suser=System msg=A connection to Deep Security Manager was initiated by a client not identifiable as a managed computer: 10.41.130.142:63944. Either the client is not a computer managed by Deep Security, or a secure communication channel could not be established.\n\nAgent GUID or virtual ID did not map to any Hosts. The following endpoint information was provided.\r\n\r\nHTTP Headers:\r\nx-dsa-time: 1584092734\r\ncontent-length: 202\r\nx-dsa-capabilities: 1092777293\r\nx-dsm-minimum-dsm-version: 9.5.0\r\ncontent-encoding: deflate\r\nx-dsm-notifications: GetInterfaces\r\ncontent-type: text/plain; charset\="UTF-8"\r\nplatform: Windows;10;0;14393;;x86_64;400;3\r\nx-dsa-listenport: 4118\r\nuser-agent: Trend Micro Deep Security Agent (10.0.0.2888)\r\n\r\nHost Info:\r\nhostname: test02.local\r\nbios-uuid: 44164530-FAF8-734C-81DF-1D5AC071065B\r\ndomain: LOCAL\r\nhostname-nb: TEST02\r\nhostname-id: {b70482c0-b44c-4221-96df-4dc55f04177e}\r\nhostname-canonical: local/LOCAL-Dienste/TGW/TEST02\r\n TrendMicroDsTenant=Primary TrendMicroDsTenantId=0" , 
error.message: "malformed value for msg at pos 369"
`

For confirmed bugs, please report:
- Version: 7.5.X
- Operating System: Windows Server 2019
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-7-4-decode-cef-getting-error-malformed-value/202469 
- Steps to Reproduce: 
when a device send a message with \n or \r chars the decode function rise-up 'malformed value for xx at pos xxx'

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

Escaped LF and CR were not handled inside of CEF extension value.
Those characters are now accepted and replaced with their unescaped
equivalents.

Fixes #16995

## Why is it important?

CEF decoding was broken by presence of `\n` or `\r` in extension values.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #16995

### CODE REVIEW

File: x-pack/filebeat/processors/decode_cef/cef/parser.go [hunk 1]
```diff
@@ -611,364 +686,576 @@ func (e *Event) unpack(data string) error {
...
 
 		recoveredErrs = append(recoveredErrs, fmt.Errorf("malformed value for %s at pos %d", extKey, p+1))
 		(p)--
-		cs = 28
+		cs = 33
 		goto _again
-	f17:
-//line cef.rl:87
+
+		goto _again
```
Comment (efd6) [inline x-pack/filebeat/processors/decode_cef/cef/parser.go:1060]: Duplicate `goto`.

File: x-pack/filebeat/processors/decode_cef/cef/parser.go [hunk 2]
```diff
@@ -611,364 +686,576 @@ func (e *Event) unpack(data string) error {
...
+//line cef.rl:99
 
 		extKey, extValueStart, extValueEnd = "", 0, 0
 		// Resume processing at p, the start of the next extension key.
 		p = mark
-		cs = 24
+		cs = 29
+		goto _again
+
 		goto _again
```
Comment (efd6) [inline x-pack/filebeat/processors/decode_cef/cef/parser.go:1070]: Duplicate `goto`.

**Review by efd6 — APPROVED** [review]
