### PR TITLE
[metricbeat] [meraki] Ignore 400 error for unsupported per-device licensing

### LINKED ISSUE #42395: [metricbeat] [meraki] `getDeviceLicenses` fails for organizations that do not support per-device licensing
When running the Cisco Meraki Metrics module, the following error message is observed and data is not reported:

```
[elastic_agent][warn] Unit state changed meraki/metrics-default-meraki/metrics-cisco_meraki_metrics-6f0c5cc9-d9da-4dbd-ae6a-df27f4693fe6 (HEALTHY->DEGRADED): Error fetching data for metricset meraki.device_health: getDeviceLicenses failed; GetOrganizationLicenses failed; [400] {"errors":["Organization with ID XXXXXX does not support per-device licensing"]}. error with operation GetOrganizationLicenses
```

We should handle client errors properly and not error out of the collection loop for this case.

### PR DESCRIPTION
**Pull request by ghost**
## Overview

We should continue collecting metrics even if the `getDeviceLicenses` function errors with 400 status code.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #42395

### CODE REVIEW

**Review by ishleenk17 — APPROVED** [review]
Looks good!

File: x-pack/metricbeat/module/meraki/device_health/devices.go [hunk 1]
```diff
@@ -150,6 +150,10 @@ func getDeviceChannelUtilization(client *meraki.Client, devices map[Serial]*Devi
 func getDeviceLicenses(client *meraki.Client, organizationID string, devices map[Serial]*Device) error {
 	val, res, err := client.Organizations.GetOrganizationLicenses(organizationID, &meraki.GetOrganizationLicensesQueryParams{})
 	if err != nil {
+		// Ignore 400 error for per-device licensing not supported
+		if res.StatusCode() == 400 {
```
Comment (stefans-elastic) [inline x-pack/metricbeat/module/meraki/device_health/devices.go:154]: Shouldn't we check for any 4xx error and not just 400?

Comment (gpop63) [reply x-pack/metricbeat/module/meraki/device_health/devices.go:154]: Not sure if we should skip all 4xx error codes, 404 for example could mean the organization was not found meaning the org ID provided in the config is wrong.

Comment (stefans-elastic) [reply x-pack/metricbeat/module/meraki/device_health/devices.go:154]: right. but it also can be something different. I mean I'm pretty sure that even 400 can be returned in multiple cases (something else can be invalid, might not be related to licensing not being supported, right?)

**Comment by gpop63** [comment]
@elastic/elastic-agent-data-plane could someone please review this PR?

File: x-pack/metricbeat/module/meraki/device_health/devices.go (hunk 1 above)
Comment (mauri870) [reply x-pack/metricbeat/module/meraki/device_health/devices.go:154]: Ignoring any 400 error seems too broad. Isn't it better to just read the response body and assert that `status is 400 AND body contains "does not support per-device licensing"`? I understand that this could be the only possible 400 response for this endpoint and we can skip the check, but that does not guarantee that other 400 errors can be returned by this endpoint in the future. I would rather be future proof.

**Review by stefans-elastic — APPROVED** [review]

**Review by mauri870 — APPROVED** [review]
Thanks.

**Review by tommyers-elastic — APPROVED** [review]
LGTM
