### PR TITLE
Winlogbeat: Fix compatibility problems with newer OS versions in CI

### LINKED ISSUE #19798: [Winlogbeat] in windows-2008-r2 got some flakiness tests for test.TestSysmon/wineventlog.TestFormatMessage
## Flaky Test

* **Test Name:**  test.TestSysmon/** and wineventlog.TestFormatMessage/**
* **Link:** 
  * https://github.com/elastic/beats/blob/57c42808d0c46c48f22c2ac63a06197b031d8559/x-pack/winlogbeat/module/sysmon/test/sysmon_windows_test.go#L25
  * https://github.com/elastic/beats/blob/57c42808d0c46c48f22c2ac63a06197b031d8559/winlogbeat/sys/wineventlog/format_message_test.go#L29
* **Branch:** https://github.com/elastic/beats/pull/19791
* **Artifact Link:** https://gist.github.com/v1v/d0f532f973aab94fedaf9cc76488a2b1
* **Notes:** 
https://beats-ci.elastic.co/job/Beats/job/beats-windows-mbp/job/PR-19791/1/execution/node/1350/log/ and https://beats-ci.elastic.co/job/Beats/job/beats-windows-mbp/job/PR-19791/1/execution/node/1202/log/ <-- these might not be accessible in the future, therefore access the `artifact link`

#### winlogbeat

```
15:43:26  C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\winlogbeat>mage  build unitTest 
15:44:05  >> build: Building winlogbeat
15:44:51  Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\winlogbeat\build\fields\fields.common.yml
15:44:51  Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\winlogbeat\build\fields\fields.all.yml
15:44:51  Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\winlogbeat\build\fields\fields.yml
15:44:51  >> go test: Unit Testing
15:49:43  FAILURES:
15:49:43  Package: github.com/elastic/beats/v7/winlogbeat/sys/wineventlog
15:49:43  Test:    TestFormatMessage
15:49:43  ----
15:49:43  Package: github.com/elastic/beats/v7/winlogbeat/sys/wineventlog
15:49:43  Test:    TestFormatMessage/getMessageStringFromHandle
15:49:43  ----
15:49:43  Package: github.com/elastic/beats/v7/winlogbeat/sys/wineventlog
15:49:43  Test:    TestFormatMessage/getMessageStringFromHandle/custom_values
15:49:43      TestFormatMessage/getMessageStringFromHandle/custom_values: format_message_test.go:78: 
15:49:43  ----
15:49:43  SUMMARY:
15:49:43    Fail:     3
15:49:43    Skip:     1
15:49:43    Pass:     145
15:49:43    Packages: 9
15:49:43    Duration: 4m49.6826172s
15:49:43    Coverage Report: C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.html
15:49:43    JUnit Report:    C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.xml
15:49:43    Output File:     C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.out
15:49:43  >> go test: Unit Test Failed
15:49:43  Error: go test failed: 3 test failures
```

#### x-pack\winlogbeat

```
15:42:24  C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\x-pack\winlogbeat>mage  build unitTest 
15:43:03  >> build: Building winlogbeat
15:43:59  Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\x-pack\winlogbeat\build\fields\fields.all.yml
15:43:59  Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19791\src\github.com\elastic\beats\x-pack\winlogbeat\build\fields\fields.yml
15:43:59  >> go test: Unit Testing
15:46:06  FAILURES:
15:46:06  Package: github.com/elastic/beats/v7/x-pack/winlogbeat/module/sysmon/test
15:46:06  Test:    TestSysmon
15:46:06  ----
15:46:06  Package: github.com/elastic/beats/v7/x-pack/winlogbeat/module/sysmon/test
15:46:06  Test:    TestSysmon/sysmon-10.2-dns.evtx
15:46:06      TestSysmon/sysmon-10.2-dns.evtx: testing_windows.go:70: Expected and actual are different:
15:46:06          --- Expected
15:46:06          +++ Actual
15:46:06          @@ -74,6 +74,3 @@
15:46:06               "user": {
15:46:06          -      "domain": "NT AUTHORITY",
15:46:06          -      "identifier": "S-1-5-18",
15:46:06          -      "name": "SYSTEM",
15:46:06          -      "type": "Well Known Group"
15:46:06          +      "identifier": "S-1-5-18"
15:46:06               },
...
```

### LINKED ISSUE #19829: [Winlogbeat][windows-7-32][windows-7-64] got some failed tests for test.TestSysmon/eventlog/TestWindowsEventLogAPIExperimental/wineventlog.TestFormatMessage
## Flaky Test

* **Test Name:**  test.TestSysmon/** , eventlog/TestWindowsEventLogAPIExperimental/** and wineventlog.TestFormatMessage/**
* **Link:** 
  * https://github.com/elastic/beats/blob/57c42808d0c46c48f22c2ac63a06197b031d8559/x-pack/winlogbeat/module/sysmon/test/sysmon_windows_test.go#L25
  * https://github.com/elastic/beats/blob/57c42808d0c46c48f22c2ac63a06197b031d8559/winlogbeat/sys/wineventlog/format_message_test.go#L29
  * https://github.com/elastic/beats/blob/f91c96f672ba88edc668fe3d44249e46a3e9d2ec/winlogbeat/eventlog/wineventlog_test.go#L42
* **Branch:** https://github.com/elastic/beats/pull/19797
* **Artifact Link:** https://gist.github.com/v1v/717700081c9fd5030c02cdf518f8becc for winlogbeat and https://gist.github.com/v1v/982a644523fc62fdbd714fe30e00934e for x-pack/winlogbeat 

#### winlogbeat

```
[2020-07-09T17:25:27.428Z] FAILURES:
[2020-07-09T17:25:27.428Z] Package: github.com/elastic/beats/v7/winlogbeat/eventlog
[2020-07-09T17:25:27.428Z] Test:    TestWindowsEventLogAPIExperimental
[2020-07-09T17:25:27.428Z] ----
[2020-07-09T17:25:27.428Z] Package: github.com/elastic/beats/v7/winlogbeat/eventlog
[2020-07-09T17:25:27.428Z] Test:    TestWindowsEventLogAPIExperimental/batch_read_size_config
[2020-07-09T17:25:27.428Z] panic: interface conversion: interface {} is uint16, not wineventlog.hexInt64
[2020-07-09T17:25:27.428Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/testing/testing.go:940 +0x27c
[2020-07-09T17:25:27.428Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/testing/testing.go:943 +0x349
[2020-07-09T17:25:27.428Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/runtime/panic.go:969 +0x119
[2020-07-09T17:25:27.428Z] C:/Users/jenkins/workspace/Beats_beats-windows-mbp_PR-19797/src/github.com/elastic/beats/winlogbeat/sys/wineventlog/renderer.go:211 +0x7d0
[2020-07-09T17:25:27.428Z] C:/Users/jenkins/workspace/Beats_beats-windows-mbp_PR-19797/src/github.com/elastic/beats/winlogbeat/sys/wineventlog/renderer.go:99 +0x47
[2020-07-09T17:25:27.429Z] C:/Users/jenkins/workspace/Beats_beats-windows-mbp_PR-19797/src/github.com/elastic/beats/winlogbeat/eventlog/wineventlog_expirimental.go:191 +0x9e
[2020-07-09T17:25:27.429Z] C:/Users/jenkins/workspace/Beats_beats-windows-mbp_PR-19797/src/github.com/elastic/beats/winlogbeat/eventlog/wineventlog_expirimental.go:160 +0xda
[2020-07-09T17:25:27.429Z] C:/Users/jenkins/workspace/Beats_beats-windows-mbp_PR-19797/src/github.com/elastic/beats/winlogbeat/eventlog/wineventlog_test.go:71 +0x113
[2020-07-09T17:25:27.429Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/testing/testing.go:991 +0xb4
[2020-07-09T17:25:27.429Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/testing/testing.go:1042 +0x2ad
[2020-07-09T17:25:27.429Z] ----
[2020-07-09T17:25:27.429Z] Package: github.com/elastic/beats/v7/winlogbeat/sys/wineventlog
[2020-07-09T17:25:27.429Z] Test:    TestFormatMessage
[2020-07-09T17:25:27.429Z] ----
[2020-07-09T17:25:27.429Z] Package: github.com/elastic/beats/v7/winlogbeat/sys/wineventlog
[2020-07-09T17:25:27.429Z] Test:    TestFormatMessage/getMessageStringFromHandle
[2020-07-09T17:25:27.429Z] ----
[2020-07-09T17:25:27.429Z] Package: github.com/elastic/beats/v7/winlogbeat/sys/wineventlog
[2020-07-09T17:25:27.429Z] Test:    TestFormatMessage/getMessageStringFromHandle/custom_values
[2020-07-09T17:25:27.429Z]     TestFormatMessage/getMessageStringFromHandle/custom_values: format_message_test.go:63: failed in EvtFormatMessage: Not enough storage is available to complete this operation.
[2020-07-09T17:25:27.429Z] ----
[2020-07-09T17:25:27.429Z] Package: github.com/elastic/beats/v7/winlogbeat/sys/wineventlog
[2020-07-09T17:25:27.429Z] Test:    TestFormatMessage/getMessageStringFromMessageID
[2020-07-09T17:25:27.429Z] panic: interface conversion: interface {} is nil, not uint32
[2020-07-09T17:25:27.429Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/testing/testing.go:940 +0x27c
[2020-07-09T17:25:27.429Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/testing/testing.go:943 +0x349
[2020-07-09T17:25:27.429Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/runtime/panic.go:969 +0x119
[2020-07-09T17:25:27.429Z] C:/Users/jenkins/workspace/Beats_beats-windows-mbp_PR-19797/src/github.com/elastic/beats/winlogbeat/sys/wineventlog/publisher_metadata.go:595 +0xf4
[2020-07-09T17:25:27.429Z] C:/Users/jenkins/workspace/Beats_beats-windows-mbp_PR-19797/src/github.com/elastic/beats/winlogbeat/sys/wineventlog/publisher_metadata.go:615 +0x3f
[2020-07-09T17:25:27.429Z] C:/Users/jenkins/workspace/Beats_beats-windows-mbp_PR-19797/src/github.com/elastic/beats/winlogbeat/sys/wineventlog/format_message_test.go:92 +0xd7
[2020-07-09T17:25:27.429Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/testing/testing.go:991 +0xb4
[2020-07-09T17:25:27.429Z] C:/Windows/system32/config/systemprofile/.gvm/versions/go1.14.4.windows.386/src/testing/testing.go:1042 +0x2ad
[2020-07-09T17:25:27.429Z] ----
[2020-07-09T17:25:27.429Z] SUMMARY:
[2020-07-09T17:25:27.429Z]   Fail:     6
[2020-07-09T17:25:27.429Z]   Skip:     1
[2020-07-09T17:25:27.429Z]   Pass:     42
[2020-07-09T17:25:27.429Z]   Packages: 9
[2020-07-09T17:25:27.429Z]   Duration: 1m23.3935547s
[2020-07-09T17:25:27.429Z]   Coverage Report: C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.html
[2020-07-09T17:25:27.429Z]   JUnit Report:    C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.xml
[2020-07-09T17:25:27.429Z]   Output File:     C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.out
[2020-07-09T17:25:27.429Z] >> go test: Unit Test Failed
```

#### x-pack\winlogbeat

```
[2020-07-09T17:20:44.510Z] C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\x-pack\winlogbeat>mage  build unitTest 
[2020-07-09T17:22:06.745Z] >> build: Building winlogbeat
[2020-07-09T17:23:43.312Z] Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\x-pack\winlogbeat\build\fields\fields.yml
[2020-07-09T17:23:43.312Z] Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\x-pack\winlogbeat\build\fields\fields.all.yml
[2020-07-09T17:23:43.312Z] >> go test: Unit Testing
[2020-07-09T17:24:51.156Z] FAILURES:
[2020-07-09T17:24:51.156Z] Package: github.com/elastic/beats/v7/x-pack/winlogbeat/module/sysmon/test
[2020-07-09T17:24:51.156Z] Test:    TestSysmon
[2020-07-09T17:24:51.156Z] ----
[2020-07-09T17:24:51.156Z] Package: github.com/elastic/beats/v7/x-pack/winlogbeat/module/sysmon/test
[2020-07-09T17:24:51.156Z] Test:    TestSysmon/sysmon-10.2-dns.evtx
[2020-07-09T17:24:51.156Z]     TestSysmon/sysmon-10.2-dns.evtx: testing_windows.go:70: Expected and actual are different:
[2020-07-09T17:24:51.156Z]         --- Expected
[2020-07-09T17:24:51.156Z]         +++ Actual
[2020-07-09T17:24:51.156Z]         @@ -74,6 +74,3 @@
[2020-07-09T17:24:51.156Z]              "user": {
[2020-07-09T17:24:51.156Z]         -      "domain": "NT AUTHORITY",
[2020-07-09T17:24:51.156Z]         -      "identifier": "S-1-5-18",
[2020-07-09T17:24:51.156Z]         -      "name": "SYSTEM",
[2020-07-09T17:24:51.156Z]         -      "type": "Well Known Group"
[2020-07-09T17:24:51.156Z]         +      "identifier": "S-1-5-18"
[2020-07-09T17:24:51.156Z]              },
...
[2020-07-09T17:24:51.180Z] ----
[2020-07-09T17:24:51.180Z] SUMMARY:
[2020-07-09T17:24:51.180Z]   Fail:     5
[2020-07-09T17:24:51.180Z]   Skip:     0
[2020-07-09T17:24:51.180Z]   Pass:     85
[2020-07-09T17:24:51.180Z]   Packages: 2
[2020-07-09T17:24:51.180Z]   Duration: 1m6.4873047s
[2020-07-09T17:24:51.180Z]   Coverage Report: C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\x-pack\winlogbeat\build\TEST-go-unit.html
[2020-07-09T17:24:51.180Z]   JUnit Report:    C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\x-pack\winlogbeat\build\TEST-go-unit.xml
[2020-07-09T17:24:51.180Z]   Output File:     C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19797\src\github.com\elastic\beats\x-pack\winlogbeat\build\TEST-go-unit.out
[2020-07-09T17:24:51.180Z] >> go test: Unit Test Failed
[2020-07-09T17:24:51.180Z] Error: go test failed: 5 test failures
```

## Issues

Some of the test failures were already reported in https://github.com/elastic/beats/issues/19798, so it seems there are a few more for Windows7.

### LINKED ISSUE #22046: [Winlogbeat] in windows-10 got tests failures for TestWindowsEventLogAPI/TestFormatMessage/TestWindowsEventLogAPIExperimental
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestWindowsEventLogAPI – eventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestWindowsEventLogAPI/batch_read_size_config – eventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestWindowsEventLogAPI/large_batch_read – eventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestWindowsEventLogAPIExperimental – eventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestWindowsEventLogAPIExperimental/batch_read_size_config – eventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestWindowsEventLogAPIExperimental/large_batch_read – eventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestFormatMessage – wineventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestFormatMessage/getMessageStringFromHandle – wineventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestFormatMessage/getMessageStringFromHandle/no_metadata – wineventlog
- Name: Build&Test / winlogbeat-windows-10-windows-10 / TestFormatMessage/getEventXML – wineventlog

See [build](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-19804/detail/PR-19804/9/tests/)

Build/Test artifacts -> https://console.cloud.google.com/storage/beats-ci-temp/Beats/beats/PR-19804-9/test-build-artifacts-winlogbeat-windows-10-windows-10.tgz

### LINKED ISSUE #22302: [Winlogbeat][windows-7-64] got some failed tests for TestEventIterator
## Failed Test

* **Test Name:**  `TestEventIterator`
* **Link:** https://github.com/elastic/beats/blob/b18b333022052d22bb515af99b926c6f58d145d4/winlogbeat/sys/wineventlog/iterator_test.go#L33
* **Branch:** https://github.com/elastic/beats/pull/19803
* **Artifact Link:** https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-19803/runs/5/steps/5170/log/. or [gists](https://gist.github.com/v1v/d3e8e5f56b2b5a4af0a073af33913fcc) if the build has been removed

### Stack Trace

```
[2020-10-29T16:50:51.835Z] 
[2020-10-29T16:50:51.835Z] C:\Users\jenkins\workspace\Beats_beats_PR-19803\src\github.com\elastic\beats\winlogbeat>mage build unitTest 
[2020-10-29T16:51:13.774Z] >> build: Building winlogbeat
[2020-10-29T16:52:21.550Z] Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats_PR-19803\src\github.com\elastic\beats\winlogbeat\build\fields\fields.all.yml
[2020-10-29T16:52:21.550Z] Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats_PR-19803\src\github.com\elastic\beats\winlogbeat\build\fields\fields.common.yml
[2020-10-29T16:52:21.550Z] Generated fields.yml for winlogbeat to C:\Users\jenkins\workspace\Beats_beats_PR-19803\src\github.com\elastic\beats\winlogbeat\build\fields\fields.yml
[2020-10-29T16:52:21.550Z] >> go test: Unit Testing
[2020-10-29T16:54:28.013Z] FAILURES:
...
[2020-10-29T16:54:28.013Z] ----
[2020-10-29T16:54:28.013Z] Package: github.com/elastic/beats/v7/winlogbeat/sys/wineventlog
[2020-10-29T16:54:28.013Z] Test:    TestEventIterator
[2020-10-29T16:54:28.013Z]     iterator_test.go:42: Access is denied.
[2020-10-29T16:54:28.013Z] ----
[2020-10-29T16:54:28.013Z] SUMMARY:
[2020-10-29T16:54:28.013Z]   Fail:     4
[2020-10-29T16:54:28.013Z]   Skip:     1
[2020-10-29T16:54:28.013Z]   Pass:     130
[2020-10-29T16:54:28.013Z]   Packages: 8
[2020-10-29T16:54:28.013Z]   Duration: 2m7.6484375s
[2020-10-29T16:54:28.013Z]   Coverage Report: C:\Users\jenkins\workspace\Beats_beats_PR-19803\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.html
[2020-10-29T16:54:28.013Z]   JUnit Report:    C:\Users\jenkins\workspace\Beats_beats_PR-19803\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.xml
[2020-10-29T16:54:28.013Z]   Output File:     C:\Users\jenkins\workspace\Beats_beats_PR-19803\src\github.com\elastic\beats\winlogbeat\build\TEST-go-unit.out
[2020-10-29T16:54:28.013Z] >> go test: Unit Test Failed
[2020-10-29T16:54:28.013Z] Error: go test failed: 4 test failures
script returned exit code 1
```

### PR DESCRIPTION
**Pull request by adriansr**
This PR includes a collection of fixes for different issues found in Winlogbeat after enabling CI testing for previously untested versions of Windows.

Two bugs have been fixed (only affected 32bit binaries):
- Bad EVT_VARIANT struct definition, caused errors formatting events.
    The first field of the structure, a union, didn't have the right size when compiled for 32-bits, causing "invalid argument" errors when the struct was passed to an API. Also, some EVT_VARIANT types weren't being handled properly.

- Failed to seek to a saved state in an `.evtx` file.
    This is caused by a helper tool in Go (mkwinsyscall) not generating correct syscall calls under GOARCH=386 (or any 32-bit arch). This only affects functions that receive a 64-bit parameter, in the case of Beats, only EvtSeek is affected. ([Bug report](https://github.com/golang/go/issues/42373)).

The rest are changes to tests due to inconsistent behaviors of different Windows versions:

- Remove formatting assertion in TestFormatMessage
    Under most Windows versions, GUID values cannot be substituted with string values. However, this is not the case under at least Win7 32bit. Just disable the testing assertion as it has no impact.

- Disable TestFormatMessage/no_metadata tests
    Under Windows 10, event formatting is not failing with an error even though not metadata is being passed.

- Check for errors on publishing events to an event log
    Under Windows 7 and Windows 10, writes to a newly created event log fail occasionally. It seems that there is a delay between when an event log is created and publishing events to it is allowed.

- Sysmon: Ignore winlog.user.* fields during test
    For some reason, the following fields:
    - winlog.user.type
    - winlog.user.name
    - winlog.user.domain

   are not populated by the Sysmon module under Windows 7 32-bit. I couldn't reproduce outside of CI, where it's failing to lookup SID `S-1-5-18`.

Fixes #19798
Fixes #19829
Fixes #22046
Fixes #22302

### CODE REVIEW

**Comment by adriansr** [comment]
jenkins, test this

File: winlogbeat/eventlog/wineventlog_test.go [hunk 1]
```diff
@@ -167,6 +166,20 @@ func createLog(t testing.TB, messageFiles ...string) (log *eventlog.Log, tearDow
 	return log, tearDown
 }
 
+func safeWriteEvent(t testing.TB, log *eventlog.Log, etype uint16, eid uint32, msgs []string) {
+	deadline := time.Now().Add(time.Second * 10)
+	for {
+		err := log.Report(etype, eid, msgs)
```
Comment (andrewkroh) [inline winlogbeat/eventlog/wineventlog_test.go:172]: Curious what the story is behind this. What kind of temporary errors were you seeing?

**Review by andrewkroh — APPROVED** [review]
LGTM. Thank you for tackling this.

File: winlogbeat/eventlog/wineventlog_test.go (hunk 1 above)
Comment (adriansr) [reply winlogbeat/eventlog/wineventlog_test.go:172]: You get an `access denied` error if the events are published too shortly after creating the event log
