### PR TITLE
[Metricbeat] [Prometheus] Add proper error handling for query dataset when the auth/ssl is misconfigured

### LINKED ISSUE #44446: [Metricbeat] [Prometheus] Add proper error handling for query dataset when the auth/ssl is misconfigured
**Describe the enhancement:**

Improve error handling for the query submodule of Metricbeat's prometheus module: https://github.com/elastic/beats/blob/main/metricbeat/module/prometheus/query/query.go#L86

**Describe a specific use case for the enhancement or feature:**

When adding username, password, and SSL support to the `query` dataset (which is already implemented in the `collector` dataset) (see PR https://github.com/elastic/integrations/pull/13969), the error messages in Metricbeat are ambiguous.
For example, when username or password is wrong, we have the following error messages:

For Collector (good and understandable):

Image

For Query (obscure):

Image

### PR DESCRIPTION
**Pull request by mykola-elastic**
## Proposed commit message

[Metricbeat] [Prometheus] Query dataset: make understandable error messages in case for http error codes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

No impact

## Author's Checklist

- [ ]

## How to test this PR locally

My test environment:
- Metricbeat built locally
- Prometheus running in docker, configured to listen on HTTPS with local self-signed certs
- Cloud deployment of Elastic stack

## Related issues

- Closes #44446
- Relates https://github.com/elastic/integrations/issues/13751
- Relates https://github.com/elastic/integrations/pull/13969

### When running Metricbeat with wrong Prometheus' username and password the error message looks like that now:

Screenshot 2025-05-26 at 15 58 40

and the debug message to the logs

```
{"log.level":"debug","@timestamp":"2025-05-26T16:07:31.937+0300","log.logger":"prometheus.query","log.origin":{"function":"github.com/elastic/beats/v7/metricbeat/module/prometheus/query.(*MetricSet).Fetch","file.name":"query/query.go","file.line":101},"message":"error received from prometheus endpoint: Unauthorized\n","service.name":"metricbeat","ecs.version":"1.6.0"}
```

### When the protocol is HTTP but the Prometheus is configured to use HTTPS:

Screenshot 2025-05-26 at 16 01 44

and the debug message to the logs:

```
{"log.level":"debug","@timestamp":"2025-05-26T16:06:09.560+0300","log.logger":"prometheus.query","log.origin":{"function":"github.com/elastic/beats/v7/metricbeat/module/prometheus/query.(*MetricSet).Fetch","file.name":"query/query.go","file.line":101},"message":"error received from prometheus endpoint: Client sent an HTTP request to an HTTPS server.\n","service.name":"metricbeat","ecs.version":"1.6.0"}
```

Which is now the same behavior as of `collector` submodule

### CODE REVIEW

**Review by stefans-elastic — APPROVED** [review]

File: metricbeat/module/prometheus/query/query.go [hunk 1]
```diff
@@ -97,6 +97,12 @@ func (m *MetricSet) Fetch(reporter mb.ReporterV2) error {
 			return err
 		}
 
+		if response.StatusCode > 399 {
+			m.Logger().Debug("error received from prometheus endpoint: ", string(body))
+			reporter.Error(fmt.Errorf("unexpected status code %d from server", response.StatusCode))
+			continue
+		}
```
Comment (ishleenk17) [inline metricbeat/module/prometheus/query/query.go:104]: Previously we used to get message about which endpoint failed to give response, in host:query format.
From where was that fetched ? And would that no longer be part of the error handling?

Comment (mykola-elastic) [reply metricbeat/module/prometheus/query/query.go:104]: @ishleenk17 Thanks, that's a good point! I've updated the code. Now the debug message looks like this: `beats/metricbeat/module/prometheus/query/logger.go:146: 2025-05-28T10:03:11.762+0300   DEBUG   prometheus.query    logp/logger.go:201      error received from prometheus endpoint http://127.0.0.1:61389/api/v1/query?query=some: Client sent an HTTP request to an HTTPS server.`

And I added the same info to the `reporter.Error` as well
