### PR TITLE
Fix input reload under Elastic-Agent

### LINKED ISSUE #33653: Input reload not working as expected under Elastic-Agent
- Version: 8.6.0/main (confirmed before the V2 merge https://github.com/elastic/beats/pull/33630)
- Operating System: All (tested on Linux)

# Description

When there is a policy change on Elastic-Agent, it will send the new configuration to Filebeat witch will trigger the input reload code path that stops the necessary inputs and starts the new ones.
https://github.com/elastic/beats/blob/3e928b702b660d5cf31e8f3090c57f2feb541338/libbeat/cfgfile/list.go#L84-L119

The inputs are correctly stopped, the harvesters/reader is also correctly shutdown before new inputs are started which will set the harvester status to 'finalised'. However if there are still events in the publishing pipeline that belong to that input as soon as they're acked the harvester status will be set back to 'not finalised'. If the one of the new inputs will harvest the same file (which is common on a policy update, e.g:  when adding a new integration to the policy, the 'old ones' will have their inputs stopped/started) this will lead to the following error when starting the new input:
```
{"log.level":"info","@timestamp":"2022-11-09T18:55:33.554+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":162},"message":"Status change to Failed: 1 error occurred:\n\t* 1 error: Error creating runner from config: Can only start an input when all related states are finished: {Id: native::149908-33, Finished: false, Fileinfo: &{flog.log 7722175 420 {729849109 63803613311 0x55d878467f20} {33 149908 1 33188 1000 1000 0 0 7722175 4096 15088 {1668016405 809851333} {1668016511 729849109} {1668016511 729849109} [0 0 0]}}, Source: /tmp/flog.log, Offset: 7724092, Timestamp: 2022-11-09 18:55:32.698690878 +0100 CET m=+20.865936562, TTL: -1ns, Type: log, Meta: map[], FileStateOS: 149908-33}\n\n","service.name":"filebeat","ecs.version":"1.6.0"}
```

On an ideal world we'd flush the publishing pipeline before trying to start new inputs, that will make all harvesters states consisten.

Another option is for the Elastic-Agent to re-start Filebeat on every policy change.

### PR DESCRIPTION
**Pull request by belimawr**
## What does this PR do?

This PR fixes the input reload issue under Elastic-Agent by creating an infinity retry logic in the ManagerV2. This is exactly the same logic used by the configuration reload on a standalone Beat.

Now if when reloading inputs, there is at least one `common.ErrInputNotFinished` a `forceReload` flag is set to true and the debounce timer is started. This process will repeat untill no `common.ErrInputNotFinished` is returned.

The `changeDebounce` period is increased to 1s and the `forceReloadDebounce` period is set to `10 x changeDebounce`.

## Why is it important?

Fixes https://github.com/elastic/beats/issues/33653
Closes https://github.com/elastic/beats/issues/35178

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist
- [ ] Manual testing under Elastic-Agent on Kubernetes
- [x] Use the `errors` package API instead of type conversion
- [x] Improve "How to test this PR locally" section

### 1. Create the policies
You will need two polices, they can either be a policy managed by Fleet or policies used with a standalone Elastic-Agent.

1. Create a policy with a single integration, the [Custom Logs](https://docs.elastic.co/integrations/log) integration and configure it to read a single log file, e.g: `/tmp/flog.log`
2. Duplicate this integration on Fleet UI

Now you have two identical policies that will ingest the same file. For a standalone Elastic-Agent setup, you can just copy those policies. This effectively mimics the behaviour of having two different policies with the [System integration](https://docs.elastic.co/integrations/system) collecting logs.

Here is an example of a simple policy that will also send the Elastic-Agent logs to ES. If using standalone mode make sure to have 3 files: two different policies (you only need to change the IDs and the `elastic-agent.yml` that is the running configuration for the Elastic-Agent.

<details>
<summary>elastic-agent.yml</summary>

```yaml
id: 63ec76c0-e355-11ed-9305-056caabbcc7c
revision: 42
outputs:
  default:
    type: elasticsearch
    hosts:
      - >-
        https://my-cloud.gcp.elastic-cloud.com:443
agent:
  download:
    sourceURI: 'https://artifacts.elastic.co/downloads/'
  monitoring:
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: false
inputs:
  - id: logfile-logs-76aab6f0-ed55-11ed-9305-056c5b7bdf7c
    name: log-1
    revision: 1
    type: logfile
    use_output: default
    meta:
      package:
        name: log
        version: 2.0.0
    data_stream:
      namespace: default
    package_policy_id: 76aab6f0-ed55-11ed-9305-056c5b7bdf7c
    streams:
      - id: logfile-log.logs-76aab6f0-ed55-11ed-9305-056c5b7bdf7c
        data_stream:
          dataset: generic
        paths:
          - /tmp/flog.log
``` 

 </details>

### 2. Deploy the Elastic-Agent
Deploy the Elastic-Agent on your test system (VM is highly recommended).
The easiest way to do this is to follow the steps on Feet to add a new Agent and instead of running `sudo ./elastic-agent install...`, you can run `./elastic-agent enroll...`, like this:
```
./elastic-agent install --url=https://my-cloud.fleet.gcp.elastic-cloud.com:443 --enrollment-token=<my enrollment token>
```
Then you can start the Elastic-Agent in the background by running:
```
./elastic-agent &
```

If using Fleet, go to the Agent logs and set the log level to `debug`.

### 3. Create a log file and keep adding data to it
My preferred way to do so is to use [flog](https://github.com/mingrammer/flog). Make sure to run it in the background or on another terminal/session.
```
flog -d 1 -s 1 -l > /tmp/flog.log &
```

### 4. Validate that you're getting both Elastic-Agent logs 
Go to Kibana and make sure you have both log file `/tmp/flog.log` and Elastic-Agent logs are being ingested.

## 5. Change the policy
If using Fleet, then change the policy on Fleet UI, if using a standalone Elastic-Agent copy the other policy over the `elastic-agent.yml`, the Elastic-Agent will automatically detect the change and propagate the new policy.

You will have to change the policy a few times until the issue happens, on my tests it usually happens on the first try.

## 6. Make sure the Agent is always health
If this PR works, the Elastic-Agent will **not** go to a unhealthy state, and you will see logs like those:
```
{"log.level":"debug","@timestamp":"2023-05-02T17:48:38.926+0200","log.logger":"centralmgmt.V2-manager","log.origin":{"file.name":"management/managerV2.go","file.line":693},"message":"file '/tmp/foo.log' is not finished, will retry starting the input soon","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-05-02T17:48:38.926+0200","log.logger":"centralmgmt.V2-manager","log.origin":{"file.name":"management/managerV2.go","file.line":695},"message":"ForceReload set to TRUE","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-05-02T17:48:48.926+0200","log.logger":"centralmgmt.V2-manager","log.origin":{"file.name":"management/managerV2.go","file.line":608},"message":"Skipped reloading output; configuration didn't change","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-05-02T17:48:48.926+0200","log.logger":"centralmgmt.V2-manager","log.origin":{"file.name":"management/managerV2.go","file.line":668},"message":"Reloading Beats inputs because forceReload is true. Set log level to debug to get more information about which inputs are causing this.","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-05-02T17:48:48.926+0200","log.logger":"centralmgmt.V2-manager","log.origin":{"file.name":"management/managerV2.go","file.line":710},"message":"ForceReload set to FALSE","ecs.version":"1.6.0"}
```

Also you **must not** see logs like those:
```
{"log.level":"info","@timestamp":"2022-11-09T18:55:33.554+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":162},"message":"Status change to Failed: 1 error occurred:\n\t* 1 error: Error creating runner from config: Can only start an input when all related states are finished: {Id: native::149908-33, Finished: false, Fileinfo: &{flog.log 7722175 420 {729849109 63803613311 0x55d878467f20} {33 149908 1 33188 1000 1000 0 0 7722175 4096 15088 {1668016405 809851333} {1668016511 729849109} {1668016511 729849109} [0 0 0]}}, Source: /tmp/flog.log, Offset: 7724092, Timestamp: 2022-11-09 18:55:32.698690878 +0100 CET m=+20.865936562, TTL: -1ns, Type: log, Meta: map[], FileStateOS: 149908-33}\n\n","service.name":"filebeat","ecs.version":"1.6.0"}
```

- Create an Elastic-Agent policy with a single 'Custom Logs' (log input)
- Duplicate this policy. Either on Fleet UI or if using standalone Agent, copy the file and change all IDs (policy, input, etc)
- Deploy the Elastic-Agent
- Keep changing between the policies (for standalone keep copying the policies over the `elastic-agent.yml`, it reloads the file automatically
- The Elastic-Agent should never be unhealthy.

## Related issues

- Closes #33653
- Will be tested by #35178

~~## Use cases~~
~~## Screenshots~~
~~## Logs~~

### CODE REVIEW

File: x-pack/libbeat/management/managerV2.go [hunk 1]
```diff
@@ -49,9 +53,11 @@ type BeatV2Manager struct {
...
 
 	// track individual units given to us by the V2 API
-	mx      sync.Mutex
-	units   map[unitKey]*client.Unit
-	actions []client.Action
+	mx          sync.Mutex
+	units       map[unitKey]*client.Unit
+	actions     []client.Action
+	forceReload atomic.Bool
+	reloadLock  sync.Mutex
```
Comment (belimawr) [inline x-pack/libbeat/management/managerV2.go:60]: I'm being very conservative here. I still need to check/understand if this is needed.

File: x-pack/libbeat/management/managerV2.go [hunk 2]
```diff
@@ -439,6 +451,10 @@ func (cm *BeatV2Manager) unitListen() {
 			}
 			cm.mx.Unlock()
 			cm.reload(units)
+			if cm.forceReload.Load() {
+				// Restart the debounce timer so we try to reload the inputs.
+				t.Reset(forceReloadDebounce)
```
Comment (AndersonQ) [inline x-pack/libbeat/management/managerV2.go:456]: It'll slow down the rate the beats apply any new config it received from the agent. I The question is more, do we want it taking up to 10s to apply any new config?

Comment (belimawr) [reply x-pack/libbeat/management/managerV2.go:456]: My main point here is to actually slow down the rate config changes are applied. There are some cases like Elastic-Agent + Kubernetes autodiscovery that we get a storm of updates that either conflict or lead to odd race conditions because not all inputs start running before the next call to reload.

> The question is more, do we want it taking up to 10s to apply any new config?

I would rephrase that even further: Given that those configuration changes are happening on Kibana, then need to be propagated to Fleet/Elastic-Agents, is it even noticeable a 10s delay to apply the changes/retry on failures?

I used 10s here as it is the default for the standalone config reload that works rather well.

**Comment by cmacknz** [comment]
Let's get the test in https://github.com/elastic/beats/issues/35178#issuecomment-1531844715 implemented before we merge this to make sure we have truly solved the problem with a real instance of Filebeat.

The code changed here has a history of unexpected bugs, so get us much automated testing added here as we can.

File: x-pack/libbeat/management/managerV2.go [hunk 3]
```diff
@@ -642,15 +659,57 @@ func (cm *BeatV2Manager) reloadInputs(inputUnits []*client.Unit) error {
...
+				// A Log input is only marked as finished when all events it
+				// produceds are acked by the acker so when we see this error,
+				// we just retry until the new input can be started.
+				// This is the same logic used by the standalone configuration file
+				// reloader implemented on libbeat/cfgfile/reload.go
+				inputNotFinishedErr := &common.ErrInputNotFinished{}
+				if ok := errors.As(causeErr, &inputNotFinishedErr); ok {
+					cm.logger.Debugf("file '%s' is not finished, will retry starting the input soon", inputNotFinishedErr.File)
+					cm.forceReload.Store(true)
+					cm.logger.Debug("ForceReload set to TRUE")
```
Comment (blakerouse) [inline x-pack/libbeat/management/managerV2.go:695]: Do you need this extra log line? Isn't it clear from the log line before the `.Store(true)` that is what had happened.

File: x-pack/libbeat/management/managerV2.go [hunk 4]
```diff
@@ -618,6 +633,8 @@ func (cm *BeatV2Manager) reloadOutput(unit *client.Unit) error {
 }
 
 func (cm *BeatV2Manager) reloadInputs(inputUnits []*client.Unit) error {
+	cm.reloadLock.Lock()
+	defer cm.reloadLock.Unlock()
```
Comment (blakerouse) [inline x-pack/libbeat/management/managerV2.go:637]: Why do you need this if you are using an atomic? I also question if an atomic is even needed, isn't `reloadInputs` call from a single goroutine and it blocks until complete. So how can it be executed at the same time?

**Review by blakerouse — CHANGES_REQUESTED** [review]

File: x-pack/libbeat/management/managerV2.go (hunk 2 above)
Comment (belimawr) [reply x-pack/libbeat/management/managerV2.go:455]: Yes, 10s is only for when there is an error.

File: x-pack/libbeat/management/managerV2.go (hunk 4 above)
Comment (belimawr) [reply x-pack/libbeat/management/managerV2.go:637]: You're right, I'll remove it.

File: x-pack/libbeat/management/managerV2.go (hunk 3 above)
Comment (belimawr) [reply x-pack/libbeat/management/managerV2.go:695]: It pretty much is, I decided to be a quite verbose here to help understand why inputs are not starting even though Filebeat is still reporting health. Also I wanted a matching line for 
https://github.com/elastic/beats/blob/0b36d196a4afcce7b0d3bef63eea1b3b7d962b3e/x-pack/libbeat/management/managerV2.go#L710

So the state changes of `cm.forceReload` are very clear in the logs.

**Comment by belimawr** [comment]
@blakerouse I've addressed your comments on https://github.com/elastic/beats/pull/35250/commits/71bd239548c9761c18e0085248c7e13b728ff05c

File: x-pack/libbeat/management/input_reload_test.go [hunk 5]
```diff
@@ -0,0 +1,213 @@
...
+	"google.golang.org/grpc"
+	"google.golang.org/grpc/credentials/insecure"
+
+	"github.com/elastic/beats/v7/libbeat/common"
+	"github.com/elastic/beats/v7/libbeat/common/reload"
+	"github.com/elastic/elastic-agent-client/v7/pkg/client"
+	"github.com/elastic/elastic-agent-client/v7/pkg/proto"
+)
+
+func TestInputReload(t *testing.T) {
```
Comment (cmacknz) [inline x-pack/libbeat/management/input_reload_test.go:24]: This test takes 10s to run? Can we speed it up? I assume we are just using the default reload timeout.

```
 gotest ./x-pack/libbeat/management/... -run TestInputReload -v
=== RUN   TestInputReload
--- PASS: TestInputReload (11.10s)
PASS
ok      github.com/elastic/beats/v7/x-pack/libbeat/management   11.309s
```

File: x-pack/libbeat/management/managerV2.go [hunk 6]
```diff
@@ -642,15 +655,57 @@ func (cm *BeatV2Manager) reloadInputs(inputUnits []*client.Unit) error {
...
+	if !didChange(cm.lastInputCfgs, inputCfgs) && !cm.forceReload {
 		cm.logger.Debug("Skipped reloading input units; configuration didn't change")
 		return nil
 	}
 
-	err := obj.Reload(inputBeatCfgs)
-	if err != nil {
-		return fmt.Errorf("failed to reloading inputs: %w", err)
+	if cm.forceReload {
+		cm.logger.Info("Reloading Beats inputs because forceReload is true. " +
```
[the remark this answers is not in the document]
Comment (belimawr) [reply x-pack/libbeat/management/managerV2.go:702]: No, unfortunately there isn't. Currently there is no way to correlate an input/unit with the error returned by `obj.Reload`.

What we can currently do is to get the name of the file(s) affected, the ones that are not 'finished' yet. This is all part of Filebeat's normal operation, so we'd have to use level info, which can be too verbose depending on the rate inputs are being reloaded/added.

File: x-pack/libbeat/management/managerV2.go (hunk 3 above)
Comment (blakerouse) [reply x-pack/libbeat/management/managerV2.go:729]: Okay.

File: filebeat/input/log/input.go [hunk 7]
```diff
@@ -93,7 +93,9 @@ func NewInput(
 	cleanupNeeded := true
 	cleanupIfNeeded := func(f func() error) {
 		if cleanupNeeded {
-			f()
+			if err := f(); err != nil {
+				logp.L().Named("input.log").Errorf("clean up function retruned an error: %w", err)
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply filebeat/input/log/input.go:97]: You going to merge this suggession? Just a misspelling.

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 8]
```diff
@@ -0,0 +1,141 @@
...
+	b.t.Cleanup(func() {
+		pid := b.Cmd.Process.Pid
+		if err := b.Cmd.Process.Kill(); err != nil {
+			b.t.Fatalf("could not stop process with PID: %d, err: %s", pid, err)
+		}
+	})
+}
+
+// LogContains looks for s as a sub string of every log line,
+// if it's not found until timeout is reached, the test fails
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/framework_test.go:68]: timeout? did you change it and forgot to change the doc?

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 9]
```diff
@@ -0,0 +1,141 @@
...
+	defer func() {
+		if err := logFile.Close(); err != nil {
+			// That's not quite a test error, but it can impact
+			// next executions of LogContains, so treat it as an error
+			b.t.Errorf("could not close log file: %s", err)
+		}
+	}()
+	scanner := bufio.NewScanner(logFile)
+
+	// TODO(Tiago) Remove this very verbose debugging code
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/framework_test.go:80]: have you done that?

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 10]
```diff
@@ -0,0 +1,141 @@
...
+	}
+
+	return false
+}
+
+// openLogFile opens the log file for reading and returns it.
+// It also registers a cleanup function to close the file
+// when the test ends.
+func (b *BeatProc) openLogFile() *os.File {
+	t := b.t
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/framework_test.go:106]: [Suggestion]
mark it as a helper
```suggestion
	t := b.t
	t.Helper()
```

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 11]
```diff
@@ -0,0 +1,141 @@
...
+		t.Fatalf("there must be only one log file for %s, found: %d",
+			glob, len(files))
+	}
+
+	f, err := os.Open(files[0])
+	if err != nil {
+		t.Fatalf("could not open log file '%s': %s", files[0], err)
+	}
+
+	t.Logf("file: '%s' successfully opened", files[0])
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/framework_test.go:139]: Debug log? Is it really needed?

File: x-pack/libbeat/management/test_utils.go [hunk 12]
```diff
@@ -0,0 +1,37 @@
...
+// you may not use this file except in compliance with the Elastic License.
+
+package management
+
+import (
+	"github.com/elastic/elastic-agent-client/v7/pkg/client"
+	"github.com/elastic/elastic-agent-client/v7/pkg/proto"
+)
+
+// DoesStateMatch retkurns true if the observed state matches
```
Comment (AndersonQ) [inline x-pack/libbeat/management/test_utils.go:12]: Typo
```suggestion
// DoesStateMatch returns true if the observed state matches
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 13]
```diff
@@ -0,0 +1,269 @@
...
+	"google.golang.org/protobuf/types/known/structpb"
+
+	"github.com/elastic/beats/v7/x-pack/libbeat/management"
+	"github.com/elastic/elastic-agent-client/v7/pkg/client/mock"
+	"github.com/elastic/elastic-agent-client/v7/pkg/proto"
+)
+
+// TestInputReloadUnderElasticAgent will start a Filebeat and cause the input
+// reload issue described on https://github.com/elastic/beats/issues/33653
+// to happen, then it will check to logs to ensure the fix is working.
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/input_reload_test.go:26]: Typo?
```suggestion
// to happen, then it will check the logs to ensure the fix is working.
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 14]
```diff
@@ -0,0 +1,269 @@
...
+// all other supporting files will be kept on build/integration-tests.
+//
+// Run the tests wit -v flag to print the temporary folder used.
+func TestInputReloadUnderElasticAgent(t *testing.T) {
+	// We create our own temp dir so the files can be persisted
+	// in case the test fails. This will help debugging issues on CI
+	//
+	// testFailed will be set to 'false' as the very last thing on this test,
+	// it allows us to use t.CleanUp to remove the temporary files
+	testFailed := true
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/input_reload_test.go:38]: [NIT]
You could use `testSucceeded`, it'd be more straight forward.

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 15]
```diff
@@ -0,0 +1,269 @@
...
+		tempDir,
+	)
+
+	p.Start()
+
+	// logger: centralmgmt
+	// logger: centralmgmt.V2-manager
+	// logger: centralmgmt.V2-manager
+	// logger: centralmgmt.V2-manager
+	// logger: centralmgmt.V2-manager
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/input_reload_test.go:208]: Are those needed?

File: x-pack/libbeat/management/input_reload_test.go [hunk 16]
```diff
@@ -0,0 +1,219 @@
...
+	// Uncomment this line to see the debug logs for this test
```
Comment (AndersonQ) [inline x-pack/libbeat/management/input_reload_test.go:25]: [Suggestion]
```suggestion
	// Uncomment the line below to see the debug logs for this test
```

File: x-pack/libbeat/management/input_reload_test.go [hunk 17]
```diff
@@ -0,0 +1,219 @@
...
+	)
+	require.NoError(t, err)
+
+	mm := m.(*BeatV2Manager)
+
+	err = m.Start()
+	require.NoError(t, err)
+	defer m.Stop()
+
+	forceReloadState := []bool{false, true, false}
```
Comment (AndersonQ) [inline x-pack/libbeat/management/input_reload_test.go:160]: [Suggestion]
As it's a slice, use the plural to reflect that
```suggestion
	forceReloadStates := []bool{false, true, false}
```

**Review by AndersonQ — COMMENTED** [review]
It seems you still have to do come clean up, so I'll wait your reply before approving

File: x-pack/filebeat/tests/integration/framework_test.go (hunk 9 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/framework_test.go:80]: I will once the CI is happy.

File: x-pack/filebeat/tests/integration/framework_test.go (hunk 10 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/framework_test.go:106]: I did not make it a helper on purpose, because it's failing on an error, I want the error message to show the actual code line that broke so it's easier to debug.

File: x-pack/filebeat/tests/integration/framework_test.go (hunk 11 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/framework_test.go:139]: Until CI is happy, yes.

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 14 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:38]: It makes sense, thanks!

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 15 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:208]: I'll clean this up once CI is happy. Those are the loggers of every log line I'm looking for.

File: filebeat/input/log/input.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (belimawr) [reply filebeat/input/log/input.go:97]: Yes, I will. CI is not happy so I was delaying merging this change to avoid interrupting my running jobs.

Sorry, I should have mentioned that as soon as I saw your comment.

**Comment by jlind23** [comment]
@belimawr please don't care about SonarCloud Code Analysis Failing after 3m — Quality Gate failed

**Comment by belimawr** [comment]
@AndersonQ, @blakerouse the PR is finally ready for final review. Some tests failed due to Jenkins hiccup, but they were passing in the past and finally my integration tests are passing :pray: 

Reading a log file is harder than it looks :exploding_head: :rofl:

**Comment by belimawr** [comment]
@blakerouse could you take a final look at it? CI is finally green!

**Comment by pierrehilbert** [comment]
With the remaining timing before 8.8.0 release, we should wait for the 8.8.1 to have more time to test it before releasing this bug fix.

File: filebeat/input/log/input.go [hunk 18]
```diff
@@ -93,7 +93,9 @@ func NewInput(
 	cleanupNeeded := true
 	cleanupIfNeeded := func(f func() error) {
 		if cleanupNeeded {
-			f()
+			if err := f(); err != nil {
+				logp.L().Named("input.log").Errorf("clean up function returned an error: %w", err)
+			}
```
Comment (AndersonQ) [inline filebeat/input/log/input.go:98]: :+1:

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 19]
```diff
@@ -0,0 +1,138 @@
...
+	Binary  string
+	Args    []string
+	Cmd     *exec.Cmd
+	t       *testing.T
+	tempDir string
+}
+
+// NewBeat createa a new Beat process from the system tests binary.
+// It sets some requried options like the home path, logging, etc.
+func NewBeat(t *testing.T, binary string, args []string, tempDir string) BeatProc {
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/framework_test.go:33]: [NIT]

YOu could have `args` as a variadic argument

```suggestion
func NewBeat(t *testing.T, binary string, tempDir string, args ...string) BeatProc {
```

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 20]
```diff
@@ -0,0 +1,138 @@
...
+	require.Eventually(t, func() bool {
+		files, err = filepath.Glob(glob)
+		if err != nil {
+			t.Fatalf("could not expand log file glob: %s", err)
+		}
+		if len(files) == 1 {
+			return true
+		}
+
+		return false
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/framework_test.go:120]: [Suggestion]
```suggestion
		return len(files) == 1
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 21]
```diff
@@ -0,0 +1,286 @@
...
+							}),
+						},
+					},
+				},
+			},
+		},
+	}
+
+	// Once the desired state is reached (aka Filebeat finished applying
+	// the policy changes) we still want for a little bit before sending
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/input_reload_test.go:155]: Typo?
```suggestion
	// the policy changes) we still wait for a little bit before sending
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 22]
```diff
@@ -0,0 +1,286 @@
...
+
+	require.Eventually(t, func() bool {
+		return filebeat.LogContains("Reloading Beats inputs because forceReload is true")
+	}, 5*time.Minute, 100*time.Millisecond,
+		"String 'Reloading Beats inputs because forceReload is true' not found on Filebeat logs")
+
+	require.Eventually(t, func() bool {
+		return filebeat.LogContains("ForceReload set to FALSE")
+	}, 5*time.Minute, 100*time.Millisecond,
+		"String 'ForceReload set to FALSE' not found on Filebeat logs")
```
Comment (AndersonQ) [inline x-pack/filebeat/tests/integration/input_reload_test.go:243]: Those are good cases to check the deadline for the tests and set the timeout to something smaller than that. It'd be a lot easier to understand why the test failed if we have the actual error, not the global timeout reached.

Comment (AndersonQ) [reply x-pack/filebeat/tests/integration/input_reload_test.go:243]: Do you think it really needs a 5 min timeout?

**Review by AndersonQ — APPROVED** [review]
I left some suggestions, but I don't see any blockers

**Review by AndersonQ — APPROVED** [review]

**Comment by belimawr** [comment]
@blakerouse could you take another look at this PR? Your approval is the only thing missing for me to merge it.

**Comment by belimawr** [comment]
> @belimawr I have a general question about the implementation: do we stop the ingestion/pipeline if we receive a new configuration update?

No we do not stop the publishing pipeline. As far as I know it is not possible to stop the publishing pipeline. When there is an output change we restart the Beat, which effectively stops the pipeline in a manner that is consistent with what is stored in the registry.

What we do stop  is the ingestion. The input is correctly stopped, so we only need to wait until all events from that input/file to be acked, then we can start a new input on the same file. This all is regarding the `log` input.

> It sounds like if we just keep retrying to apply the new configuration without stopping ingestion we risk to keep having some events (created again and again) in the pipeline that reference the harvester and we can get stuck forever in these retry attempts.
> 
> Is my concern valid?

That does not happen because the input (and the harvester) are not running any more. The harvester status is still set as `active` because there are events on the pipeline from that file (or harvester), but no ingestion is running any more.

File: Jenkinsfile [hunk 23]
```diff
@@ -707,7 +707,7 @@ def withBeatsEnv(Map args = [:], Closure body) {
           error("Error '${err.toString()}'")
         } finally {
           if (archive) {
-            archiveArtifacts(allowEmptyArchive: true, artifacts: "${directory}/build/system-tests/docker-logs/TEST-docker-compose-*.log")
+            archiveArtifacts(allowEmptyArchive: true, artifacts: "${directory}/build/system-tests/docker-logs/TEST-docker-compose-*.log, ${directory}/build/integration-tests/**/**")
```
Comment (rdner) [inline Jenkinsfile:710]: Was it just for debugging or we still need it?

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 24]
```diff
@@ -0,0 +1,135 @@
+// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
+// or more contributor license agreements. Licensed under the Elastic License;
+// you may not use this file except in compliance with the Elastic License.
+
+//go:build integration
+
+package integration
```
[the remark this answers is not in the document]
Comment (rdner) [reply x-pack/filebeat/tests/integration/framework_test.go:7]: Is there a particular reason to put it under the `x-pack` path?

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 25]
```diff
@@ -0,0 +1,136 @@
...
+type BeatProc struct {
+	Binary  string
+	Args    []string
+	Cmd     *exec.Cmd
+	t       *testing.T
+	tempDir string
+}
+
+// NewBeat createa a new Beat process from the system tests binary.
+// It sets some requried options like the home path, logging, etc.
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/framework_test.go:32]:
```suggestion
// It sets some required options like the home path, logging, etc.
```

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 26]
```diff
@@ -0,0 +1,136 @@
...
+// `tempDir` will be used a home a logs directory for the Beat
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/framework_test.go:33]: Not sure I got it right, here is my take:

```suggestion
// `tempDir` will be used as a home and a logs directory for the Beat
```

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 27]
```diff
@@ -0,0 +1,136 @@
...
+	}
+	return p
+}
+
+// Start starts the Beat process
+func (b *BeatProc) Start() {
+	t := b.t
+	fullPath, err := filepath.Abs(b.Binary)
+	if err != nil {
+		t.Fatalf("could got get full path from %q, err: %s", b.Binary, err)
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/framework_test.go:56]:
```suggestion
		t.Fatalf("could not get full path from %q, err: %s", b.Binary, err)
```

File: x-pack/filebeat/tests/integration/framework_test.go [hunk 28]
```diff
@@ -0,0 +1,136 @@
...
+	}
+	t.Cleanup(func() {
+		pid := b.Cmd.Process.Pid
+		if err := b.Cmd.Process.Kill(); err != nil {
+			t.Fatalf("could not stop process with PID: %d, err: %s", pid, err)
+		}
+	})
+}
+
+// LogContains looks for s as a sub string of every log line,
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/framework_test.go:71]:
```suggestion
// LogContains looks for `s` as a substring of every log line,
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 29]
```diff
@@ -0,0 +1,336 @@
...
+	"github.com/stretchr/testify/require"
+	"google.golang.org/protobuf/types/known/structpb"
+
+	"github.com/elastic/beats/v7/x-pack/libbeat/management"
+	"github.com/elastic/elastic-agent-client/v7/pkg/client/mock"
+	"github.com/elastic/elastic-agent-client/v7/pkg/proto"
+)
+
+// TestInputReloadUnderElasticAgent will start a Filebeat and cause the input
+// reload issue described on https://github.com/elastic/beats/issues/33653
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/input_reload_test.go:27]: I would prefer to have a short issue description here in the comments instead of a link to the Github issue.

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 30]
```diff
@@ -0,0 +1,336 @@
...
+// to happen, then it will check the logs to ensure the fix is working.
+//
+// In case of a test failure the directory with Filebeat logs and
+// all other supporting files will be kept on build/integration-tests.
+//
+// Run the tests wit -v flag to print the temporary folder used.
+func TestInputReloadUnderElasticAgent(t *testing.T) {
+	// First things first, ensure ES is running and we can connect to it.
+	// If ES is not running, the test will timeout and the only way to know
+	// what caused is to go through Filebeat's logs
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/input_reload_test.go:37]:
```suggestion
	// what caused it is to go through Filebeat's logs
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 31]
```diff
@@ -0,0 +1,336 @@
...
+	if err := os.MkdirAll(tempDir, 0766); err != nil {
+		t.Fatalf("cannot create tmp dir: %s, msg: %s", err, err.Error())
+	}
+	t.Logf("Temporary directory: %s", tempDir)
+	t.Cleanup(func() {
+		if testSucceeded {
+			if err := os.RemoveAll(tempDir); err != nil {
+				t.Fatalf("could not remove temp dir '%s': %s", tempDir, err)
+			}
+			t.Logf("Temprary directory '%s' removed", tempDir)
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/input_reload_test.go:62]:
```suggestion
			t.Logf("Temporary directory '%s' removed", tempDir)
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 32]
```diff
@@ -0,0 +1,336 @@
...
+				waiting = false
+				return
+			}
+			return
+		}
+		waiting = true
+		when = time.Now().Add(10 * time.Second)
+	}
+	server := &mock.StubServerV2{
+		// The Beat will call the checkin function multiple times:
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/input_reload_test.go:185]:
```suggestion
		// The Beat will call the check-in function multiple times:
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 33]
```diff
@@ -0,0 +1,336 @@
...
+		// - At least once at startup
+		// - At every state change (starting, configuring, healthy, etc)
+		// for every Unit.
+		//
+		// Because of that we can't rely on the number of times it is called
+		// we need some sort of state machine to handle when to send the next
+		// policy and when to just re-send the current one.
+		//
+		// If the Elastic-Agent wants the Beat to keep running the same policy,
+		// it will just keep re-sending it every time the Beat calls the checkin
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/input_reload_test.go:195]:
```suggestion
		// it will just keep re-sending it every time the Beat calls the check-in
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 34]
```diff
@@ -0,0 +1,286 @@
...
+				if state := unit.GetState(); !(state == proto.State_HEALTHY || state != proto.State_CONFIGURING || state == proto.State_STARTING) {
+					t.Fatalf("Unit '%s' is not healthy, state: %s", unit.GetId(), unit.GetState().String())
+				}
+			}
+			return &proto.CheckinExpected{
+				Units: units[idx],
+			}
+		},
+		ActionImpl: func(response *proto.ActionResponse) error { return nil },
+		// ActionsChan: make(chan *mock.PerformAction, 100),
```
[the remark this answers is not in the document]
Comment (rdner) [reply x-pack/filebeat/tests/integration/input_reload_test.go:211]: why is marked as resolved? the line is still there.

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 35]
```diff
@@ -0,0 +1,336 @@
...
+		"-E", fmt.Sprintf(`management.insecure_grpc_url_for_testing="localhost:%d"`, server.Port),
+		"-E", "management.enabled=true",
+	)
+
+	filebeat.Start()
+
+	// waitDeadlineOr5Mins looks at the test deadline
+	// and returns a reasonable value of waiting for a
+	// condition to be met. The possible values are:
+	// - if no test deadline is set, return 5 minuets
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/input_reload_test.go:230]:
```suggestion
	// - if no test deadline is set, return 5 minutes
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 36]
```diff
@@ -0,0 +1,336 @@
...
+		return filebeat.LogContains("Reloading Beats inputs because forceReload is true")
+	}, waitDeadlineOr5Min(), 100*time.Millisecond,
+		"String 'Reloading Beats inputs because forceReload is true' not found on Filebeat logs")
+
+	require.Eventually(t, func() bool {
+		return filebeat.LogContains("ForceReload set to FALSE")
+	}, waitDeadlineOr5Min(), 100*time.Millisecond,
+		"String 'ForceReload set to FALSE' not found on Filebeat logs")
+
+	// Set it to true, so the temporaty directory is removed
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/input_reload_test.go:272]:
```suggestion
	// Set it to true, so the temporary directory is removed
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 37]
```diff
@@ -0,0 +1,336 @@
...
+	str, err := structpb.NewStruct(v)
+	if err != nil {
+		require.NoError(t, err)
+	}
+	return str
+}
+
+// generateLogFile generates a log file by appending the current
+// time to it every second.
+func generateLogFile(t *testing.T, fullPath string) {
```
Comment (rdner) [inline x-pack/filebeat/tests/integration/input_reload_test.go:286]: Can we at least accept a context as an argument so we can stop the go routine if we want to?

File: x-pack/libbeat/management/input_reload_test.go [hunk 38]
```diff
@@ -0,0 +1,219 @@
...
+
+	mm := m.(*BeatV2Manager)
+
+	err = m.Start()
+	require.NoError(t, err)
+	defer m.Stop()
+
+	forceReloadStates := []bool{false, true, false}
+	forceReloadStateIdx := 0
+	forceReloadLastState := true // starts on true so the first iteratiction is already a change
```
Comment (rdner) [inline x-pack/libbeat/management/input_reload_test.go:162]: not sure if it's `interaction` or `iteration`.

```suggestion
	forceReloadLastState := true // starts on true so the first iteration is already a change
```

File: x-pack/libbeat/management/input_reload_test.go [hunk 39]
```diff
@@ -0,0 +1,219 @@
...
+
+	eventuallyCheck := func() bool {
+		forceReload := mm.forceReload
+		// That detects a state change, we only count/advance steps
+		// on state changes
+		if forceReload != forceReloadLastState {
+			forceReloadLastState = forceReload
+			if forceReload == forceReloadStates[forceReloadStateIdx] {
+				// Setp to the next state
```
Comment (rdner) [inline x-pack/libbeat/management/input_reload_test.go:171]:
```suggestion
				// Set to the next state
```

File: x-pack/libbeat/management/managerV2.go [hunk 40]
```diff
@@ -642,15 +693,62 @@ func (cm *BeatV2Manager) reloadInputs(inputUnits []*client.Unit) error {
...
+			}
+		}
+
+		if len(realErrors) != 0 {
+			return fmt.Errorf("failed to reload inputs: %w", realErrors.Err())
+		}
+	} else {
+		// If there was no error reloading input and forceReload was
+		// true, then set it to false. This prevents unnecessary logging
+		// and make it clear this was the monent when the input reload
```
Comment (rdner) [inline x-pack/libbeat/management/managerV2.go:744]:
```suggestion
		// and makes it clear this was the moment when the input reload
```

**Review by rdner — CHANGES_REQUESTED** [review]
Mostly typos, I strongly suggest to install a spell checker ;)

**Comment by belimawr** [comment]
> Mostly typos, I strongly suggest to install a spell checker ;)

I have one, but I need to properly configure it. You also use Emacs, right? Which one do you use/how do you configure it? I started using `flyspell` but I believe I haven't setup the proper hooks yet :/

File: x-pack/filebeat/tests/integration/framework_test.go (hunk 24 above)
[the remark this answers is not in the document]
Comment (belimawr) [reply x-pack/filebeat/tests/integration/framework_test.go:7]: Yes, all Elastic-Agent related code is here, which includes the manager who will interact with this "framework". Even it it is outside `x-pack`, it will require `x-pack` code to work/be used.

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 34 above)
[the remark this answers is not in the document]
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:211]: I was pretty sure I had removed it when I marked it as resolved. Maybe I added it to the changes batch, resolved it, did something else and it ended up not being commited.

Thanks for spotting it!

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 37 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:286]: We should not leak that, thanks!

I'll implementing something using `t.Cleanup` so the caller does not need to worry about any cleanup.

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 32 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:185]: I'm sure I had added that to the batch...

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 29 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go]: Done on efd1811910

File: Jenkinsfile (hunk 23 above)
Comment (belimawr) [reply Jenkinsfile:710]: If this test ever fails on CI that will be needed. I believe we should keep it there. Nobody investigating a test failure will remember to re-enable that, run it again then disable it.

I'm trying to make it as easy as possible to find and fix anything that could make this test fail.

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 37 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:291]: Done on 49f314d79f.

**Review by blakerouse — APPROVED** [review]
Looks good!

**Review by AndersonQ — APPROVED** [review]

File: Jenkinsfile (hunk 23 above)
Comment (cmacknz) [reply Jenkinsfile:710]: Do the tests output the junit test report that CI uses to generate the test report? The unit tests do this, there probably isn't a reason the integration tests here couldn't either.

This is all controlled through the mage Go Test wrapper so if you are using that you are set.

https://github.com/belimawr/beats/blob/d36f48672653082fd5a8e27795726fb87c733be2/dev-tools/mage/gotest.go#L211

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 41]
```diff
@@ -0,0 +1,354 @@
...
+func ensureESIsRunning(t *testing.T) {
+	t.Helper()
+	ctx, cancel := context.WithDeadline(context.Background(), time.Now().Add(500*time.Second))
+	defer cancel()
+	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "http://localhost:9200", nil)
+	if err != nil {
+		t.Fatalf("cannot create request to ensure ES is running: %s", err)
+	}
+
+	req.SetBasicAuth("admin", "testing")
```
Comment (cmacknz) [inline x-pack/filebeat/tests/integration/input_reload_test.go:342]: These should be set by environment variables:

https://github.com/elastic/beats/blob/d36f48672653082fd5a8e27795726fb87c733be2/dev-tools/mage/integtest_docker.go#L183-L189

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 42]
```diff
@@ -0,0 +1,354 @@
...
+		if waiting {
+			if time.Now().After(when) {
+				idx = (idx + 1) % len(units)
+				waiting = false
+				return
+			}
+			return
+		}
+		waiting = true
+		when = time.Now().Add(10 * time.Second)
```
Comment (cmacknz) [inline x-pack/filebeat/tests/integration/input_reload_test.go:188]: Why 10 seconds? Can this be faster? Will this test be flaky?

File: x-pack/filebeat/tests/integration/framework_test.go (hunk 24 above)
[the remark this answers is not in the document]
Comment (cmacknz) [reply x-pack/filebeat/tests/integration/framework_test.go:7]: This file doesn't look like it depends on anything that is x-pack licensed, but the test itself definitely does.

[the remark this answers is not in the document]
Comment (cmacknz) [reply x-pack/filebeat/tests/integration/framework_test.go:7]: Consider moving this to an Apache license out of the x-pack directory so it can be reused by the OSS parts of Beats.

File: x-pack/libbeat/management/managerV2.go [hunk 43]
```diff
@@ -642,15 +693,62 @@ func (cm *BeatV2Manager) reloadInputs(inputUnits []*client.Unit) error {
...
+		if errors.As(err, &merror) {
+			for _, err := range merror.Errors {
+				causeErr := cause(err)
+				// A Log input is only marked as finished when all events it
+				// produceds are acked by the acker so when we see this error,
+				// we just retry until the new input can be started.
+				// This is the same logic used by the standalone configuration file
+				// reloader implemented on libbeat/cfgfile/reload.go
+				inputNotFinishedErr := &common.ErrInputNotFinished{}
+				if ok := errors.As(causeErr, &inputNotFinishedErr); ok {
```
Comment (cmacknz) [inline x-pack/libbeat/management/managerV2.go:726]: Consider reporting the affected unit as CONFIGURING instead of HEALTHY while this happens. We'll be able to see the state transitions in the agent logs, and CONFIGURING will map back Healthy in the Fleet UI.

File: x-pack/libbeat/management/managerV2.go [hunk 44]
```diff
@@ -773,3 +871,32 @@ func didChange(previous map[string]*proto.UnitExpectedConfig, latest map[string]
...
+//
+//	type causer interface {
+//	       Cause() error
+//	}
+//
+// If the error does not implement Cause, the original error will
+// be returned. If the error is nil, nil will be returned without further
+// investigation.
+// Source: https://github.com/pkg/errors/blob/614d223910a179a466c1767a985424175c39b465/errors.go#L264-L288
+func cause(err error) error {
```
Comment (cmacknz) [inline x-pack/libbeat/management/managerV2.go:887]: I don't think you need this, all uses of `Cause` were removed from Beats in https://github.com/elastic/beats/pull/31772

Comment (cmacknz) [reply x-pack/libbeat/management/managerV2.go:887]: > The Cause() function from github.com/pkg/errors is not compatible with the standard library's new error wrapping functionality.

> Specifically, Cause() will not call Unwrap() on a standard library wrapped error. Contrastingly, errors created or wrapped by github.com/pkg/errors implement Unwrap() (for example see [the source](https://github.com/pkg/errors/blob/5dd12d0cfe7f152f80558d591504ce685299311e/errors.go#L248)) and are compatible with the standard library.

File: x-pack/libbeat/management/managerV2.go (hunk 43 above)
Comment (cmacknz) [reply x-pack/libbeat/management/managerV2.go:726]: You can actually report the configuring state with a message, so you could include the files we are waiting on in that message. This will go directly to Fleet.

Comment (cmacknz) [reply x-pack/libbeat/management/managerV2.go:726]: I suppose the issue you'll have with this is that you can't map the error back to a unit ID. We should probably fix this. I would file a followup issue to do this.

**Comment by cmacknz** [comment]
Was able to successfully run the new integration test 👍

File: x-pack/libbeat/management/managerV2.go (hunk 43 above)
Comment (cmacknz) [reply x-pack/libbeat/management/managerV2.go:726]: Agreed, not a blocker we can iterate on this in future PRs.

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 41 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:342]: Done on a98f0a9cef

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 42 above)
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:188]: Unfortunately not. On my machine the tests take 40s to run. It's not super long for an integration tests. Even if I reduce this constant to 500ms it still takes 40s (the first run is the current 10s wait, the second is a 500ms wait):
```
tiago@millennium-falcon beats/x-pack/filebeat/tests/integration  v1.19.6  fix-input-reload-under-agent [$!] % go test -tags=integration -v ./...
=== RUN   TestInputReloadUnderElasticAgent                                                                      
    input_reload_test.go:62: Temporary directory: /home/tiago/devel/beats/x-pack/filebeat/build/integration-tests/TestInputReloadUnderElasticAgent-1685462672
    input_reload_test.go:68: Temporary directory '/home/tiago/devel/beats/x-pack/filebeat/build/integration-tests/TestInputReloadUnderElasticAgent-1685462672' removed
--- PASS: TestInputReloadUnderElasticAgent (40.37s)
PASS
ok      github.com/elastic/beats/v7/x-pack/filebeat/tests/integration   40.565s
tiago@millennium-falcon beats/x-pack/filebeat/tests/integration  v1.19.6  fix-input-reload-under-agent [$] % go test -tags=integration -v ./...
=== RUN   TestInputReloadUnderElasticAgent
    input_reload_test.go:62: Temporary directory: /home/tiago/devel/beats/x-pack/filebeat/build/integration-tests/TestInputReloadUnderElasticAgent-1685462799
    input_reload_test.go:68: Temporary directory '/home/tiago/devel/beats/x-pack/filebeat/build/integration-tests/TestInputReloadUnderElasticAgent-1685462799' removed
--- PASS: TestInputReloadUnderElasticAgent (40.37s)
PASS
ok      github.com/elastic/beats/v7/x-pack/filebeat/tests/integration   40.588s
tiago@millennium-falcon beats/x-pack/filebeat/tests/integration  v1.19.6  fix-input-reload-under-agent [$!] % 
```

File: x-pack/filebeat/tests/integration/input_reload_test.go [hunk 45]
```diff
@@ -0,0 +1,354 @@
...
+			if final <= 0 {
+				return left
+			}
+			return final
+		}
+		return 5 * time.Minute
+	}
+
+	require.Eventually(t, func() bool {
+		return filebeat.LogContains("Can only start an input when all related states are finished")
```
[the remark this answers is not in the document]
Comment (belimawr) [reply x-pack/filebeat/tests/integration/input_reload_test.go:253]: The fix does not report the state as unhealthy, any more. In fact it reports as healthy, but keeps retrying to start the input until it succeeds. 

For this fix to be able to affect the state of a unit we need to be able to correlate Filebeat (well, Beats) inputs to Elastic-Agent Units, which at the moment is not possible.

1 and 2 are done here: https://github.com/elastic/beats/blob/d36f48672653082fd5a8e27795726fb87c733be2/x-pack/filebeat/tests/integration/input_reload_test.go#L203-L215

Unit states can only be:
- HEALTHY
- CONFIGURING
- STARTING

`management.DoesStateMatch` checks the ID and state among other things.

File: x-pack/libbeat/management/managerV2.go (hunk 44 above)
Comment (belimawr) [reply x-pack/libbeat/management/managerV2.go:887]: Done on 8eece56ece

File: Jenkinsfile (hunk 23 above)
Comment (belimawr) [reply Jenkinsfile:710]: I don't get how it could help. What I am trying to do here is to make the logs from  the Filebeat test binary available to download on CI, so if the test fails we can see why Filebeat failed/did not behave as expected.

**Comment by belimawr** [comment]
@rdner, @cmacknz I addressed/responded all your comments, could you re-review?

**Review by rdner — COMMENTED** [review]
A couple of more typos.

**Review by rdner — APPROVED** [review]

File: x-pack/filebeat/tests/integration/input_reload_test.go (hunk 45 above)
[the remark this answers is not in the document]
Comment (cmacknz) [reply x-pack/filebeat/tests/integration/input_reload_test.go:253]: Thanks I'll create a follow up issue for letting link unit IDs to inputs.

**Comment by cmacknz** [comment]
@belimawr let's backport to 8.8 so this can be released in v8.8.1.
