### PR TITLE
[Metricbeat] Add GCP CloudSQL region filter

### LINKED ISSUE #32906: [GCP Module] Region filtering support for cloudsql metricset
**Describe the enhancement:**

Running the following configuration will throw an error because the filter looks for zone and clousdql exposes region.

```
- module: gcp
  metricsets:
    - metrics
  region: "us-"
  project_id: "<project id>"
  credentials_file_path: "/usr/share/metricbeat/config/pkey.json"
  period: 300s
  metrics:
    - service: cloudsql
      metric_types:
        - "database/cpu/utilization"
```
The error :

> Could not read time series value: [cloudsql.googleapis.com/database/cpu/utilization](http://cloudsql.googleapis.com/database/cpu/utilization): rpc error: code = InvalidArgument desc = The supplied filter does not specify a valid combination of metric and monitored resource descriptors. The query will not return any time series.

Removing the region property fixes the issue, but we can no longer filter by project regions.

**Describe a specific use case for the enhancement or feature:**

Filtering by project region.

From @endorama 

> To support filtering by region we need to add a dedicated gcp metricset and integration data stream.

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Adds GCP `cloudsql` region filter.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #32906

### CODE REVIEW

File: x-pack/metricbeat/module/gcp/metrics/metrics_requester.go [hunk 1]
```diff
@@ -152,7 +157,7 @@ func (r *metricsRequester) getFilterForMetric(serviceName, m string) string {
 			// }
 
 			region := strings.TrimSuffix(r.config.Region, "*")
-			f = fmt.Sprintf(`%s AND resource.labels.zone = starts_with("%s")`, f, region)
+			f = fmt.Sprintf(`%s AND resource.labels.region = starts_with("%s")`, f, region)
```
Comment (endorama) [inline x-pack/metricbeat/module/gcp/metrics/metrics_requester.go:160]: Please do not include this change here, as it's not related to CloudSQL. This change is also a breaking change, so we need to take another approach.
I would add a comment, so we can remove this in the future: `FIXME: this is using zone but should use region. This is a breaking change.`

File: CHANGELOG.next.asciidoc [hunk 2]
```diff
@@ -86,6 +86,9 @@ https://github.com/elastic/beats/compare/v8.2.0\...main[Check the HEAD diff]
 - Fix GCP storage field naming {pull}32806[32806]
 - in module/windows/perfmon, changed collection method of the second counter value required to create a displayable value {pull}32305[32305]
 - Fix and improve AWS metric period calculation to avoid zero-length intervals {pull}32724[32724]
+- Add GCP CloudSQL region filter {pull}32943[32943]
+- Add network name to data.json {pull}32986[32986]
+- Add missing cluster metadata to k8s module metricsets {pull}32979[32979]
```
Comment (endorama) [inline CHANGELOG.next.asciidoc:91]:
```suggestion
- Add GCP CloudSQL region filter {pull}32943[32943]
```

File: x-pack/metricbeat/module/gcp/metrics/metrics_requester.go [hunk 3]
```diff
@@ -198,6 +211,7 @@ func (r *metricsRequester) getFilterForMetric(serviceName, m string) string {
 
 		switch {
 		case r.config.Region != "":
+			// FIXME: using resource.labels.zone but should use region.
```
Comment (endorama) [inline x-pack/metricbeat/module/gcp/metrics/metrics_requester.go:214]: I though about this, let's remove it from here and do it for good separately. I'll open an issue to discuss how to address this.
```suggestion
```

**Review by endorama — CHANGES_REQUESTED** [review]
2 minor changes required then this can be merged

**Review by endorama — APPROVED** [review]
