### PR TITLE
Testcase and Fix for Issue 1528

### LINKED ISSUE #1528: filebeat 1.2.2 reships rotated log files upon restart due to lost offset
We just updated from filebeat 1.1.2 to 1.2.2 to resolve #1281 in our environment. This has revealed a new issue.

We are experiencing the problem on a local ext4 file system on Ubuntu 14.04 running in AWS EC2 and also running in Virtualbox 5.

I have created a bash script which reproduces the issue and published it as a gist, including a log of the output:
https://gist.github.com/jstangroome/0774df94b46aa288b0855f533c67d152

Essentially when filebeat exits, the registry is recorded with the entry for the fully-shipped and recently-rotated log file not having an offset specified.

When filebeat is started again, the missing offset value is treated effectively the same as `"offset": 0` and the log file's contents are reshipped. Because the file was rotated recently, it is still new enough that `ignore_older` directives won't exclude it.

/cc @ruflin

### PR DESCRIPTION
**Pull request by ruflin**
Following changes were made
* All state information is fetched in advance for later comparison to prevent race conditions
* State is also written to registrar file if offset is 0, same for path
* Test case to validate fix added

Closes #1528

### CODE REVIEW

File: filebeat/crawler/prospector.go [hunk 1]
```diff
@@ -400,15 +422,16 @@ func (p *Prospector) checkExistingFile(newinfo *harvester.FileStat, newFile *inp
 
 		if previousFile, err := p.getPreviousFile(file, newinfo.Fileinfo); err == nil {
 			// This file was renamed from another file we know - link the same harvester channel as the old file
-			logp.Debug("prospector", "File rename was detected: %s -> %s", previousFile, file)
+			logp.Debug("prospector", "File rename was detected, existing file: %s -> %s", previousFile, file)
```
Comment (tsg) [inline filebeat/crawler/prospector.go]: The new wording might be confusing, I actually found the old one pretty clear.

Comment (ruflin) [inline filebeat/crawler/prospector.go]: The problem is, that we had two cases with the same log message.
