### PR TITLE
[Elastic Agent] Add verification check when updating communication to Kibana.

### LINKED ISSUE #24485: [Elastic Agent] Updating policy with updated Kibana should ensure communication is possible before updating the fleet configuration
At the moment Elastic Agent updates its `fleet.yml` with the Kibana connection information from the policy. Elastic Agent currently doesn't verify that it can actually communicate with the new connection information before setting that as the new client and writing it to the `fleet.yml`.

If Elastic Agent cannot communicate back to Kibana with that information, then the policy should fail and should not be ACK'd.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Adds a verification check when updating how the Elastic Agent communicates with Kibana. Ensures that the Elastic Agent reports Failed when an error occurs dispatching action.

## Why is it important?

Currently if the user has the global Kibana connection information wrong in the policies Elastic Agent will update the client and then fail to checkin. This ensures that before updating to a new client that the new client can actually communicate with Kibana. In the case that it cannot communicate it updates the Elastic Agent as failed and reports back to the original client that the action of updating the policy failed.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #24485

### CODE REVIEW

**Review by michalpristas — APPROVED** [review]
this is a good catch.

File: x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change.go [hunk 1]
```diff
@@ -99,6 +100,14 @@ func (h *handlerPolicyChange) handleKibanaHosts(c *config.Config) (err error) {
 			err, "fail to create API client with updated hosts",
 			errors.TypeNetwork, errors.M("hosts", h.config.Fleet.Kibana.Hosts))
 	}
+	ctx, cancel := context.WithTimeout(ctx, 15*time.Second)
```
Comment (michalpristas) [inline x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change.go:103]: maybe we can use const or some config value, if you like

Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change.go]: added const for now
