### PR TITLE
Bring back support for really old Docker versions

### LINKED ISSUE #7542: [Auditbeat] Retain compatibility with older Docker server versions
Auditbeat version -> 6.3.1

My auditbeat.yml uses the `add_docker_metadata` processor.

Running `auditbeat test config --strict.perms=false -c auditbeat.yml` is giving me `Exiting: error initializing publisher: error initializing processors: Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)` on this box.

I believe that Auditbeat 6.3.1 was deployed on this box when this error message occured. After downgrading Auditbeat to version 6.3.0, things are working fine on this box.

Box details,

```
$ uname -a
Linux ip-172-23-180-123 4.4.0-1048-aws #57-Ubuntu... x86_64 x86_64 x86_64 GNU/Linux

$ dpkg -l | grep docker
hi  docker-engine                    1.11.2-0~xenial...

$ docker --version
Docker version 1.11.2, build b9f10c9
```

This is an Ubuntu 16.04.3 LTS 64-bit box (UPDATED!).

Please let me know if more details are required to reproduce/debug this issue.

### PR DESCRIPTION
**Pull request by exekias**
Introducing API version negotiation (#7165) brough support for new
Docker versions, but broke support for versions in EOL.

This change puts old API version (1.22) back on the default fallback,
plus introduces version hardcoding through `DOCKER_API_VERSION`
environment variable.

I added some integration tests to check things are working.

Fixes #7542

### CODE REVIEW

File: libbeat/common/docker/client.go [hunk 1]
```diff
@@ -28,31 +29,35 @@ import (
...
 	if err != nil {
-		logp.Debug("docker", "Failed to perform ping: %s", err)
+		return c, err
 	}
 
-	// try the latest version before versioning headers existed
-	if ping.APIVersion == "" {
-		ping.APIVersion = "1.24"
-	}
+	if os.Getenv("DOCKER_API_VERSION") == "" {
```
Comment (ruflin) [inline libbeat/common/docker/client.go]: Is `DOCKER_API_VERSION` set by default? If not it seems this code is always called also for a  newer version?

Comment (exekias) [reply libbeat/common/docker/client.go]: DOCKER_API_VERSION is used to hardcode client API version. If it's unset (which is common), beats should negotiate client API version to ensure we use one compatible with the server

**Comment by ruflin** [comment]
I think we will also need some docs around this to explain users they can use `DOCKER_API_VERSION` to set old versions or their own.
