### PR TITLE
[Ingest Manager] Make installer atomic on windows

### LINKED ISSUE #24180: [Win-10-2016-ltsb specific]: Agent's Metricbeat process not running (so no Activity logs under Logs tab for Metricbeat), may relate to Endpoint or Linux / Windows Integrations
**Kibana version:** 7.12.0 Snapshot Kibana Cloud environment

**Host OS and Browser version:** Windows 10, All

**Preconditions:**
1. 7.12.0 Snapshot Kibana cloud environment should be available.

**Build Details:**
```
Artifact link: https://snapshots.elastic.co/7.12.0-999aaf18/downloads/beats/elastic-agent/elastic-agent-7.12.0-SNAPSHOT-windows-x86_64.zip
Build: 38956
Commit: 00f7be3e485a4ec7788675ccd3d302eb6b92dc50
```
2. Default policy must have System and Endpoint Security.

**Steps to reproduce:**
1. Login to Kibana Cloud environment.
2. Navigate to Fleet>Agents tab.
3. Enroll agent with default policy having System and Endpoint Security.
4. Observe "Unhealthy" status of agent.
5. Navigate to agent Logs tab. 
6. Observe no Activity Logs.
7. Navigate to Data Streams tab.
8. Observe no Data under Data Streams tab.

**Expected Result:**
Activity logs should stream on enrolling agent with policy having System and Endpoint Security.

**Screenshots:**
sys and es

**Note:**
It is working fine with MAC and Linux .tar agents.

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

PR fixes issue on windows when on restart while installing beats we end up with partial data. 
awaitable installler was introduced which forces app wait for installer finish its job 

and 

sync is forced for windows after rename is called during install. 

## Why is it important?

Fixes #24180

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

File: x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go [hunk 1]
```diff
@@ -120,6 +120,11 @@ func (i *Installer) unzip(artifactPath string) error {
 	}
 
 	for _, f := range r.File {
+		// if we were cancelled in between
+		if err := ctx.Err(); err != nil {
+			return err
```
Comment (blakerouse) [inline x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go:125]: Won't this still leave it broken? If the context is cancelled, then this will stop extracting.

File: x-pack/elastic-agent/pkg/artifact/install/awaitable/awaitable_installer.go [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+func (i *Installer) Wait() {
+	i.wg.Wait()
+}
+
+// Install performs installation of program in a specific version.
+func (i *Installer) Install(ctx context.Context, spec program.Spec, version, installDir string) error {
+	i.wg.Add(1)
+	defer i.wg.Done()
+
+	return i.installer.Install(ctx, spec, version, installDir)
```
Comment (blakerouse) [inline x-pack/elastic-agent/pkg/artifact/install/awaitable/awaitable_installer.go:48]: Because of the context cancelling won't this still leave it in a bad state? Because if the context is cancelled then the waitgroup would still be marked with `Done()` and the `Wait()` would not actually wait for this to finish.

**Review by blakerouse — COMMENTED** [review]
Maybe I don't understand how this fixes it, but see my inline comments on what I think this is doing.

I also wonder if all this ensuring that its fully extracted before shutdown is really even worth it. I think we should just think about always extracting before executing the program.

That would ensure:

* Elastic Agent is always running what it expects (because the binary was not replaced in the directory)
* Because of the point above the window of time to inject a bad binary from extract to starting the program is a extremely small window. (currently because we don't re-extract the binary can be changed as we only check the .asc and .sha512 of the compessed artifact vs the binary itself).

File: x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go (hunk 1 above)
Comment (michalpristas) [reply x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go:125]: this will propagate error and prevent install to continue

File: x-pack/elastic-agent/pkg/artifact/install/awaitable/awaitable_installer.go (hunk 2 above)
Comment (michalpristas) [reply x-pack/elastic-agent/pkg/artifact/install/awaitable/awaitable_installer.go:48]: when the context is cancelled we should finish install and return error here, then wg should be mark with done.
if context is not cancelled this should work as usuuall. 
please elaborate a bit more, i'm not seeing what you see atm

File: x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go (hunk 1 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go:125]: This will prevent all of the files in the zip file from being extracted. So that mean that if a SIGTERM occurs it will cancel the context. When the context is cancelled and its in this loop then only part of the zip file will be extracted.

What happens when this returns a `context.Cancelled`? Does the zip installer then remove the directory because the context was cancelled during the extraction? If that is the case, then this is okay. If it accepts `context.Cancelled` as an acceptable error, or does not remove the directory then it would still be left in a bad state.

**Comment by michalpristas** [comment]
@blakerouse there are 2 things happening now at this PR
first one is proper cancellation of the task which does not ensure it is fully unpacked but otherwise, it ensures task is cancelled as soon as we know about cancellation and artifact is removed by atomic installer (because error is propagated during unpack and atomic removes on error). for this we're awaiting.

how it works atm:
- installer unpacking
- shutdown is proposed
- installer unpacking
- operator shutdown is called, context cancelled, operator stopped
- installer still installing because it;s not even aware it should stop
- agent shuts down
- installer interupted

how this pr changes the flow
- installer unpacking
- shutdown proposed
- installer unpacking
- operator shutdown called, context cancelled, wait for installer
- `zip` installed registers cancelled context, exits loop with err
- `atomic` installer sees error, cleans up
- `awaitable` installer returns done when cleanup done
- `operator` shutdown continues
-  agent exits

the second one is sync of FS operations in Install dir
with unpack we sync file by file
but with remove we need to sync entire directory because when agent exits close to remove, it gets corrupted.
this is done in atomic installer and agent using await makes sure it runs ok before exiting agent

File: x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go (hunk 1 above)
Comment (michalpristas) [reply x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go:125]: yes that's the case, atomic installer removes the extracted files because error was returned

**Review by blakerouse — APPROVED** [review]
Thank you for taking the time to explain how this is working. I just wanted to be sure that it worked as you where expecting. Glad to hear it is.

**Comment by michalpristas** [comment]
finding out whether test failures are related

**Comment by EricDavisX** [comment]
Hi - @dikshachauhan-qasource used an early version of the artifact from our GCP Observability builds and tried out the PR against current 8.0 master cloud build, and reports they did not see the problem (so that is good, if not a 100% definitive confirmation):  Her words:

Policies used separately:
1. default having only system
2. new policy having all core 4 integrations [ system, linux, windows, Endpoint]

It may not fix all of the e2e-testing failures but may be worthwhile to push in and iterate over.  @michalpristas thanks.
