### PR TITLE
auditbeat/module/file_integrity: remove garbled PE executable test file

### LINKED ISSUE #35705: TestExeObjParser/executableObject_pe_garble can fail on Windows
## :broken_heart: Tests Failed

> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[Pipeline View](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F8.8/detail/8.8/85//pipeline) [Test View](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F8.8/detail/8.8/85//tests) [Changes](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F8.8/detail/8.8/85//changes) [Artifacts](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F8.8/detail/8.8/85//artifacts) [preview](http://beats_null.docs-preview.app.elstc.co/diff)  [preview](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-06-06T16:55:40.954Z&rangeTo=2023-06-06T17:15:40.954Z&transactionName=BUILD+Beats%2Fbeats%2F8.8&transactionType=job&latencyAggregationType=avg&traceId=a5b6cc25bea6136133bd8d6625ee9616&transactionId=13bf1fdc6c523da7)

<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Start Time: 2023-06-06T17:05:40.954+0000

* Duration: 138 min 56 sec

#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 2  |
| Passed       | 60080  |
| Skipped      | 5953 |
| Total        | 66035   |

</p>
</details>

  ### Test errors [](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F8.8/detail/8.8/85//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `ExtendedWin / auditbeat-windows-10-windows-10 / TestExeObjParser/executableObject_pe_garble – github.com/elastic/beats/v7/auditbeat/module/file_integrity`

<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestExeObjParser/executableObject_pe_garble
    exeobjparser_test.go:46: unexpected error calling exeObjParser.Parse: open ./testdata/garble_pe_executable: The system cannot find the file specified.
    exeobjparser_test.go:72: unexpected error for garble_pe pe.import_hash: got:key not found want:<nil>
    exeobjparser_test.go:72: unexpected error for garble_pe pe.imphash: got:key not found want:<nil>
    exeobjparser_test.go:72: unexpected error for garble_pe pe.imports: got:key not found want:<nil>
    exeobjparser_test.go:72: unexpected error for garble_pe pe.imports_names_entropy: got:key not found want:<nil>
    exeobjparser_test.go:72: unexpected error for garble_pe pe.imports_names_var_entropy: got:key not found want:<nil>
    exeobjparser_test.go:72: unexpected error for garble_pe pe.go_import_hash: got:key not found want:<nil>
    exeobjparser_test.go:72: unexpected error for garble_pe pe.go_stripped: got:key not found want:<nil>
    exeobjparser_test.go:72: unexpected error for garble_pe pe.sections: got:key not found want:<nil>
    --- FAIL: TestExeObjParser/executableObject_pe_garble (0.00s)
 
 ```
</p></details>
</ul>
    
##### `ExtendedWin / auditbeat-windows-10-windows-10 / TestExeObjParser – github.com/elastic/beats/v7/auditbeat/module/file_integrity`

<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestExeObjParser
--- FAIL: TestExeObjParser (0.06s)
 
 ```
</p></details>
</ul>
    
</p></details>

### Steps errors [](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F8.8/detail/8.8/85//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
##### `filebeat-arm-ubuntu-2204-aarch64 - mage build unitTest`
<ul>
<li>Took 12 min 8 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/8.8/runs/85/steps/23241/log/?start=0">here</a></li>
<li>Description: <code>mage build unitTest</code></l1>
</ul>
  
  
  
  
##### `auditbeat-windows-10-windows-10 - mage build unitTest`
<ul>
<li>Took 3 min 21 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/8.8/runs/85/steps/33110/log/?start=0">here</a></li>
<li>Description: <code>mage build unitTest</code></l1>
</ul>
  
  
  
  
##### `auditbeat-windows-10-windows-10 - mage build unitTest`
<ul>
<li>Took 3 min 52 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/8.8/runs/85/steps/35273/log/?start=0">here</a></li>
<li>Description: <code>mage build unitTest</code></l1>
</ul>
  
  
  
  
##### `auditbeat-windows-10-windows-10 - mage build unitTest`
<ul>
<li>Took 1 min 50 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/8.8/runs/85/steps/36072/log/?start=0">here</a></li>
<li>Description: <code>mage build unitTest</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/8.8/runs/85/steps/36247/log/?start=0">here</a></li>
<li>Description: <code>Error "hudson.AbortException: script returned exit code 1"</code></l1>
</ul>
  
  </p>
  </details>

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This file is detected by some malware detection systems as malicious likely due to the source obfuscation that garble does to it. The testing of the underlying library already tests the infrastucture, so removing the test here does not harm coverage.

The executable itself is a garble built compilation of the file at https://github.com/elastic/toutoumomoma/blob/dev/testdata/main.go. In that repository the executable is built on the fly during testing rather than being retained as an asset.

## Why is it important?

Impacts on UX.

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Fixes #35705

### CODE REVIEW

File: auditbeat/module/file_integrity/exeobjparser_test.go [hunk 1]
```diff
@@ -40,6 +40,10 @@ func TestExeObjParser(t *testing.T) {
 
 			key := fmt.Sprintf("%s_%s", builder, format)
 			t.Run(fmt.Sprintf("executableObject_%s_%s", format, builder), func(t *testing.T) {
+				if builder == "garble" && format == "pe" {
+					t.Skip("skipping test on garbled PE file: see https://github.com/elastic/beats/issues/35705")
```
Comment (ebeahan) [inline auditbeat/module/file_integrity/exeobjparser_test.go:44]: I'm not familiar with the testing framework, so maybe this question has an obvious answer:

If we're removing the test entirely, is it still necessary to mark it as skipped?

Comment (efd6) [reply auditbeat/module/file_integrity/exeobjparser_test.go:44]: We're iterating over [elf, macho, pe]×[go, garble]. The only way to remove a single element of a 3×2 is by an exception like this. We could just continue before the `Run` call, but I think leaving information about why we are doing this is useful.

**Review by ebeahan — APPROVED** [review]
LGTM
