### PR TITLE
[metricbeat] [auditbeat] Add formatted index option to metricbeat / auditbeat modules

### LINKED ISSUE #14923: [metricbeat] Allow inputs to specify output index
This is a sub-issue of the larger meta-issue elastic/beats#13255 (broken out for project tracking): to allow metricbeat inputs to set a custom output index, similar to what elastic/beats#14010 did for filebeat.

### PR DESCRIPTION
**Pull request by faec**
Resolves #14923 and #15065.

Adds an `index` formatted string option to all metricbeat modules that, when present, specifies the (elasticsearch) output index for events from that module.

### CODE REVIEW

File: metricbeat/mb/module/connector.go [hunk 1]
```diff
@@ -73,3 +80,28 @@ func (c *Connector) Connect() (beat.Client, error) {
...
+		procs.AddProcessor(indexProcessor)
+	}
+
+	userProcs, err := processors.New(config.Processors)
+	if err != nil {
+		return nil, err
+	}
+	procs.AddProcessors(*userProcs)
+
+	return procs, nil
```
Comment (ycombinator) [inline metricbeat/mb/module/connector.go]: Nit: I quite liked the comments you had in the Filebeat implementation, numbering the processor additions and also noting that ordering was significant.

Comment (faec) [reply metricbeat/mb/module/connector.go]: Ah, I removed it because metricbeat processor config is simpler (only one configurable processor source), but you're right, an indication of intent here is good so I re-added a comment :-)

File: metricbeat/mb/module/connector.go [hunk 2]
```diff
@@ -36,20 +38,25 @@ type Connector struct {
...
 
 	// KeepNull determines whether published events will keep null values or omit them.
 	KeepNull bool `config:"keep_null"`
 
 	common.EventMetadata `config:",inline"` // Fields and tags to add to events.
 }
 
-func NewConnector(pipeline beat.Pipeline, c *common.Config, dynFields *common.MapStrPointer) (*Connector, error) {
+func NewConnector(
+	beatInfo beat.Info, pipeline beat.Pipeline,
```
Comment (ycombinator) [inline metricbeat/mb/module/connector.go]: I've been torn about this sort of change in one of my PRs as well. Basically, we're now passing an extra `beat.Info` parameter to this function. Looking at the calls to this constructor, they now look like this:

```
module.NewConnector(b.Info, b.Publisher, ...)
```

where `b` is of type `*beat.Beat`. 

I wonder if should just make this constructor take `b *beat.Beat` instead of `beatInfo beat.Info, pipeline beat.Pipeline`. I could go either way on this. WDYT?

Comment (faec) [reply metricbeat/mb/module/connector.go]: My usual preference is to pass the simpler information, both to reduce contextual load (a `BeatInfo` parameter implies a lot more about the function's behavior than a broadly-scoped container that could be affecting many things in non-obvious ways) and because it's easy to refactor to `beat.Beat` in the future if we ever really need to, but hard to take it back once it's in the API and people start depending on that field in unexpected ways :-)

Comment (ycombinator) [reply metricbeat/mb/module/connector.go]: Yup, that's fair. I think my concern of adding more arguments is not as strong in comparison, at least not at this point, where the function would be taking in only 4 arguments. If that number ever grows to be really unwieldy, we can revist.

+1 for keeping this change as-is.

**Comment by faec** [comment]
All remaining test failures are Jenkins timeouts that are also happening at head; Travis is green, so going ahead with merge.
