### PR TITLE
ignore prometheus parsing errors

### LINKED ISSUE #37198: Missing datasets that are relying on kube-state-metrics in case custom resource state metrics are enabled
Missing some datasets in case custom resource state metrics are enabled https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md

How to reproduce:
0. Other versions > 8.7 likely have the same issue
```
elastic-package-0.89.2 stack up -d -v --version 8.7.1
```
1. install cert-manager:
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.4/cert-manager.yaml

2. create a testing issuer:
```
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
``` 
apply above.
3. edit the KSM setup:
```
args:
  - --custom-resource-state-config
  - |
    spec:
      resources:
        - groupVersionKind:
            group: cert-manager.io
            version: "v1"
            kind: Issuer
          metrics:
            - name: certman_issuers_info
              each:
                type: Info
                info:
                  path: [status]
                  labelsFromPath:
                    ref: []
  - --custom-resource-state-only=true # optional to report only custom metrics
```
4. edit KMS cluster role:
```
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
```

5. deploy metricbeat

The issue: out of all state_* datasets - there are only 2 available (deployment, daemonset and cronjob - but in this setup I do not have cronjob installed)
Screenshot 2023-11-24 at 15 29 08

### PR DESCRIPTION
**Pull request by gsantoro**
## Proposed commit message
Ignore parser errors from unsupported metrics types on Prometheus client and continue parsing until EOF is reached.

For example Prometheus client with default `text/plain` format doesn't support `info` metrics and it will generate an error at https://github.com/prometheus/prometheus/blob/965e603fa792bca0900ac76eb45ae84c81af1cdf/model/textparse/promparse.go#L319.

Currently that error breaks the parsing and it ignores any remaining metrics in the list. With this change instead we will correctly parse all the supported metrics types and ignore the unsupported ones.

Metrics of type `info` are correctly supported by OpenMetrics format. KSM supports OpenMetrics text format as well but in Beats the helper is hardcoded to use only plain text format at https://github.com/elastic/beats/blob/8b18c3645fe3aa97c717bbd33e5762fd44ea07ab/metricbeat/helper/prometheus/prometheus.go#L34.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

See related issue #37198 on how to test these changes

## Related issues

- Closes #37198

### CODE REVIEW

**Comment by gsantoro** [comment]
This PR is supposed to replace entirely https://github.com/elastic/beats/pull/37357 which was created by mistake from the wrong git branch

File: metricbeat/helper/prometheus/textparse.go [hunk 1]
```diff
@@ -496,8 +498,15 @@ func ParseMetricFamilies(b []byte, contentType string, ts time.Time) ([]*MetricF
 		)
 		if et, err = parser.Next(); err != nil {
 			// TODO: log here
-			// if errors.Is(err, io.EOF) {}
-			break
+			if errors.Is(err, io.EOF) {
```
Comment (gizas) [inline metricbeat/helper/prometheus/textparse.go:501]: I add here the comment from Tania. I agree is important because now we dont know 
Import 	"github.com/elastic/elastic-agent-libs/logp"

Possible suggestion:
```
if et, err = parser.Next(); err != nil {
			if errors.Is(err, io.EOF) {
				log.Errorf("EOF is reached: %v ", err)
				break
			}
			log.Debugf("Parse Prometheus Family error : %v ", err)	
			break
		}
```

Comment (gsantoro) [reply metricbeat/helper/prometheus/textparse.go:502]: thanks for the suggestion. 

I am a bit skeptic about using a global logger and I thought we had to pass prometheus logger to the ParseMetricFamilies instead.

I tested both solutions. They both work, I think it is about styling. The current changes use Kubernetes logger since that's the only other logger globally available.

if we wanted to use Prometheus logger there a few more changes required in both the code and the tests.

**Comment by gsantoro** [comment]
Sample log entry formatted for readability

```json
{
  "log.level": "debug",
  "@timestamp": "2023-12-12T10:50:03.576Z",
  "log.logger": "kubernetes",
  "log.origin":
    {
      "function": "github.com/elastic/beats/v7/metricbeat/helper/prometheus.ParseMetricFamilies",
      "file.name": "prometheus/textparse.go",
      "file.line": 506,
    },
  "message": 'Ignored Parsing error from Prometheus : invalid metric type "info" ',
  "service.name": "metricbeat",
  "ecs.version": "1.6.0",
}
```

File: metricbeat/helper/prometheus/textparse.go (hunk 1 above)
Comment (gizas) [reply metricbeat/helper/prometheus/textparse.go:503]: Sorry got confused with what is global and prometheus logger. 

Currently I see that  `ParseMetricFamilies` is calle from GetStateMetricsFamilies which is used from state metricsets here :https://github.com/elastic/beats/blob/main/metricbeat/helper/kubernetes/state_metricset.go#L115

So if we pass the error back to the state_metricset.go in abolve logger this would be able to log it. Is not it? Just to make sure that we return it in ParseMetricFamilies

Do you agree Giuseppe? Then in this case we dont want to add a new logger

Comment (gizas) [reply metricbeat/helper/prometheus/textparse.go:513]: Thank you @gsantoro ! Now I think I got it. We need to return "invalid metric type" message back.

Because we already have prometheus logger, I guess is preferrable to pass it from caller function and create another one

**Comment by gsantoro** [comment]
Reusing the same prometheus logger I get this debug log

```
{
  "log.level": "debug",
  "@timestamp": "2023-12-13T15:52:40.083Z",
  "log.logger": "kubernetes.state_cronjob",
  "log.origin":
    {
      "function": "github.com/elastic/beats/v7/metricbeat/helper/prometheus.ParseMetricFamilies",
      "file.name": "prometheus/textparse.go",
      "file.line": 503,
    },
  "message": 'Ignored invalid metric type : invalid metric type "info" ',
  "service.name": "metricbeat",
  "ecs.version": "1.6.0",
}
```

to notice that the log.logger is different now. it returns the base.Logger() as the prometheus logger.

**Review by gizas — APPROVED** [review]

File: metricbeat/helper/prometheus/textparse.go (hunk 1 above)
Comment (tetianakravchenko) [reply metricbeat/helper/prometheus/textparse.go:513]: Thank you for adding logging!
Can you please also add a test for this use case? That `info` is skipped but rest of metrics are parsed correctly for `ContentTypeTextFormat`

**Review by tetianakravchenko — APPROVED** [review]

**Review by fearful-symmetry — APPROVED** [review]

**Review by ycombinator — APPROVED** [review]
