### PR TITLE
[Elastic Agent] Set permissions during installation

### LINKED ISSUE #26213: Elastic Agent service fails to start on windows with default installation
For confirmed bugs, please report:
- Version: 7.13
- Operating System: Windows Server 2008 R2 Standard and Windows 10
- Steps to Reproduce: 

These are the steps I followed in Windows 10:
 - Download the agent
 - Run the enroll command
 - The agent will enroll successfully and stay in an "updating" state, it won't move from there
```
C:\Users\XXXX\Downloads\elastic-agent-7.13.0-windows-x86_64>.\elastic-agent.exe install -f --url=https://6b744b5715d84795bd1e89dc17bbe068.fleet.eu-west-1.aws.found.io:443 --enrollment-token=TUVqNXRIa0J4TENCejVWcXdqcG86VTZaYUVTdWpSX3ExbUFXeTlPT2IzZw==
The Elastic Agent is currently in BETA and should not be used in production

2021-05-29T05:04:41.693+0200    INFO    cmd/enroll_cmd.go:201   Elastic Agent might not be running; unable to trigger restart
2021-05-29T05:04:41.701+0200    INFO    cmd/enroll_cmd.go:203   Successfully triggered restart on running Elastic Agent.
Successfully enrolled the Elastic Agent.
Elastic Agent has been successfully installed.
```
- If I go to services, the service has been installed but it's not running.
- If I try to run it it will terminate unexpectedly with error 1067

There are no logs in the agent's folder with the exception of a new elastic-agent-<TIMESTAMP> file which is created every time I try to start the service, that only contains this line:
```
 2021-05-29T05:10:45.146+0200	ERROR	cmd/watch.go:61	failed to load markeropen C:\Program Files\Elastic\Agent\data\.update-marker: El sistema no puede encontrar el archivo especificado.
```

If I run the agent from the command line it works correctly and the status in Kibana changes to healthy

```
2021-05-29T05:14:47.263+0200	INFO	warn/warn.go:18	The Elastic Agent is currently in BETA and should not be used in production
2021-05-29T05:14:47.281+0200	INFO	application/application.go:68	Detecting execution mode
2021-05-29T05:14:47.287+0200	INFO	application/application.go:93	Agent is managed by Fleet
2021-05-29T05:14:47.289+0200	INFO	capabilities/capabilities.go:59	capabilities file not found in C:\Program Files\Elastic\Agent\capabilities.yml
2021-05-29T05:14:48.085+0200	INFO	[composable]	composable/controller.go:46	EXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production
2021-05-29T05:14:48.225+0200	INFO	[composable.providers.docker]	docker/docker.go:43	Docker provider skipped, unable to connect: protocol not available
2021-05-29T05:14:48.233+0200	INFO	[api]	api/server.go:62	Starting stats endpoint
2021-05-29T05:14:48.233+0200	INFO	application/managed_mode.go:291	Agent is starting
2021-05-29T05:14:48.233+0200	INFO	[api]	api/server.go:64	Metrics endpoint listening on: \\.\pipe\elastic-agent (configured: npipe:///elastic-agent)
2021-05-29T05:14:48.345+0200	WARN	application/managed_mode.go:304	failed to ack update open C:\Program Files\Elastic\Agent\data\.update-marker: El sistema no puede encontrar el archivo especificado.
2021-05-29T05:14:50.299+0200	INFO	stateresolver/stateresolver.go:48	New State ID is VoHXoJOY
2021-05-29T05:14:50.299+0200	INFO	stateresolver/stateresolver.go:49	Converging state requires execution of 3 step(s)
2021-05-29T05:14:55.086+0200	INFO	cmd/run.go:189	Shutting down Elastic Agent and sending last events...
2021-05-29T05:14:55.086+0200	INFO	operation/operator.go:191	waiting for installer of pipeline 'default' to finish
2021-05-29T05:15:03.393+0200	ERROR	status/reporter.go:236	Elastic Agent status changed to: 'error'
2021-05-29T05:15:03.393+0200	ERROR	fleet/fleet_gateway.go:180	failed to dispatch actions, error: operator: failed to execute step sc-run, error: context canceled: context canceled
2021-05-29T05:15:03.393+0200	INFO	process/app.go:176	Signaling application to stop because of shutdown: filebeat--7.13.0
2021-05-29T05:15:03.405+0200	INFO	application/managed_mode.go:320	Agent is stopped
2021-05-29T05:15:03.406+0200	INFO	cmd/run.go:197	Shutting down completed.
2021-05-29T05:15:03.415+0200	INFO	[api]	api/server.go:66	Stats endpoint (\\.\pipe\elastic-agent) finished: use of closed network connection
```

I found a WA which is going to the service, click on properties and instead of using the local account, add the credentials for the Administrator user, the service will start and work as expected.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

The `install` command now sets the correct permissions for the installation directory on all platforms.

## Why is it important?

So the started Elastic Agent that is running as a system level service has the required permissions to run correctly and to ensure that only those with the correct level of permissions can access those files.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #26213

### CODE REVIEW

File: x-pack/elastic-agent/pkg/agent/install/perms_windows.go [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+	if err != nil {
+		return err
+	}
+	administratorsSID, err := windows.StringToSid("S-1-5-32-544")
+	if err != nil {
+		return err
+	}
+	return acl.Apply(
+		path, true, inherit,
+		acl.GrantSid(0xF10F0000, systemSID), // full control of all acl's
```
Comment (michel-laterman) [inline x-pack/elastic-agent/pkg/agent/install/perms_windows.go:49]: What is `0xF10F0000`?

Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/install/perms_windows.go:49]: That is the hex needed for the "full control of all acl's".

Comment (michalpristas) [reply x-pack/elastic-agent/pkg/agent/install/perms_windows.go:49]: Can you left a comment describing Windows cryptic ways of specifying things

**Review by michalpristas — APPROVED** [review]
Change looks good it would be nice if somebody with env where problem occurred could test it before merge

**Comment by blakerouse** [comment]
@alvarolobato Anyway you could give this a test to see if it fixes the issue for you?

**Comment by alvarolobato** [comment]
@blakerouse  I gave it a try but this only generates 8.0 artifacts which are not working with my cloud deployment on 7.13, is there a config option to make the agent ignore the fleet server version? or do I need to manually run a 8.0 fleet server to test this?

```
2021-07-07T18:30:33.671+0100    INFO    cmd/enroll_cmd.go:414   Starting enrollment to URL: https://xxxxxxxxxxx.fleet.eu-west-1.aws.found.io:443/
Error: fail to enroll: fail to execute request to fleet-server: status code: 400, fleet-server returned an error: UnsupportedVersion, message: version is not supported
Error: enroll command failed with exit code: 1
```

**Comment by blakerouse** [comment]
@alvarolobato There is no way to override the version check.

You will need to manually run the whole stack with 8.0.0, or you could normally spin up an 8.0.0-SNAPSHOT in the cloud (but I believe it is broken until a new SNAPSHOT is built).

**Comment by alvarolobato** [comment]
@blakerouse ok, I'll start an 8 snapshot once it's working, I'll give it a try.

Not sure if that error is helpful.

**Comment by blakerouse** [comment]
@alvarolobato Any way you could setup a local stack and try this? 8.0.0-SNAPSHOT still seems broken in Cloud, but running it locally with a docker-compose works. I want to get this in soon as I think it needs to be in 7.14, but don't want it in to late if any issue pop up from the change.

**Comment by alvarolobato** [comment]
@blakerouse cloud is working, I was just able to test this and it's still failing. This is what I'm getting on the logs:
```
{"log.level":"error","@timestamp":"2021-07-14T14:55:49.762Z","log.logger":"control","log.origin":{"file.name":"server/server.go","file.line":63},"message":"unable to create listener: failed to lookup Administrators group: Não foi efectuado qualquer mapeamento entre nomes de contas e IDs de segurança.","ecs.version":"1.6.0"}
```

[agent-perms.csv](https://github.com/elastic/beats/files/6817006/agent-perms.csv)

**Comment by alvarolobato** [comment]
These are the logs if I start as Administrator:

```
{"log.level":"info","@timestamp":"2021-07-14T15:01:25.793Z","log.origin":{"file.name":"warn/warn.go","file.line":18},"message":"The Elastic Agent is currently in BETA and should not be used in production","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:25.794Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:25.796Z","log.origin":{"file.name":"application/application.go","file.line":93},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:25.797Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:26.795Z","log.logger":"composable","log.origin":{"file.name":"composable/controller.go","file.line":46},"message":"EXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:26.928Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:26.931Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:26.931Z","log.origin":{"file.name":"application/managed_mode.go","file.line":290},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:26.931Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: \\\\.\\pipe\\elastic-agent (configured: npipe:///elastic-agent)","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2021-07-14T15:01:27.033Z","log.origin":{"file.name":"application/managed_mode.go","file.line":303},"message":"failed to ack update open C:\\Program Files\\Elastic\\Agent\\data\\.update-marker: O sistema não conseguiu localizar o ficheiro especificado.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:30.517Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is n-fHYPrR","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:30.517Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-14T15:01:32.396Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-14T15:01:32.396Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-14T16:01:32+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[caef0447-4c22-4f5f-8645-f6777711eebe]: State changed to FAILED: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-e22bb5\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-e22bb5\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-14T15:01:32.397Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-verify failed, err: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-e22bb5\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-e22bb5\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-14T15:01:32.397Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-e22bb5\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-e22bb5\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-e22bb5\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-e22bb5\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:34.995Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is n-fHYPrR","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-14T15:01:34.995Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
```

**Comment by blakerouse** [comment]
@alvarolobato Based on the logs you provided, it seems that it is running. Installing as an Administrator is required. Other than the log message, are you seeing the Elastic Agent stop running?

**Comment by alvarolobato** [comment]
@blakerouse I installed as administrator, but when I run the service as system it dies and the logs are the first ones I shared.
If I change the service to user the administrator account it will run and show the second log file I shared.

So it's not working as expected, it should run properly with the system account.

**Comment by blakerouse** [comment]
@alvarolobato Thanks for explaining I was confused.

Being I can't reproduce the behavior that you are seeing it is hard to know what is heppening. I will see if I can figure out why the listener cannot be created.

**Comment by alvarolobato** [comment]
@blakerouse let me know if there's anything I can do to help with testing.

**Comment by blakerouse** [comment]
Looking at the permission file you provided (which is very helpful, thank you!) I see the issue. The issue is that being your Windows is not en_US the Administrator account name is different. Elastic Agent does some look ups based on the `Administrator` and `Administrators` group name, and in your case it is actually `Administradores`

**Comment by alvarolobato** [comment]
@blakerouse but there should be a way to lookup in a language independent way, I don't believe software will need take that into account.


For file names the common files have also a localized name, but the english name usually works.

**Comment by alvarolobato** [comment]
Just saw your push. I'll wait for the build and test again.

**Comment by blakerouse** [comment]
@alvarolobato Build should be ready if you can give it a try.

**Comment by alvarolobato** [comment]
@blakerouse IT WORKS!!!!!!

```
{"log.level":"info","@timestamp":"2021-07-15T13:48:04.733Z","log.origin":{"file.name":"warn/warn.go","file.line":18},"message":"The Elastic Agent is currently in BETA and should not be used in production","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T13:48:04.735Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T13:48:04.736Z","log.origin":{"file.name":"application/application.go","file.line":77},"message":"Agent is managed locally","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T13:48:04.737Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T13:48:05.677Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
```

**Comment by alvarolobato** [comment]
@blakerouse  false alarm, it died again :-( let me gather all the information. And double check.

**Comment by alvarolobato** [comment]
This is the log and permission file.
```
{"log.level":"info","@timestamp":"2021-07-15T13:53:01.930Z","log.origin":{"file.name":"warn/warn.go","file.line":18},"message":"The Elastic Agent is currently in BETA and should not be used in production","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T13:53:01.933Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T13:53:01.936Z","log.origin":{"file.name":"application/application.go","file.line":93},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T13:53:01.936Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T13:53:02.352Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
```

[agent-perms.csv](https://github.com/elastic/beats/files/6823635/agent-perms.csv)

**Comment by alvarolobato** [comment]
This is the log running again as administrator with this version

```
{"log.level":"info","@timestamp":"2021-07-15T14:02:47.966Z","log.origin":{"file.name":"warn/warn.go","file.line":18},"message":"The Elastic Agent is currently in BETA and should not be used in production","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:47.967Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:47.969Z","log.origin":{"file.name":"application/application.go","file.line":93},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:47.969Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:48.524Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:48.526Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:48.526Z","log.origin":{"file.name":"application/managed_mode.go","file.line":290},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:48.526Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: \\\\.\\pipe\\elastic-agent (configured: npipe:///elastic-agent)","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2021-07-15T14:02:48.630Z","log.origin":{"file.name":"application/managed_mode.go","file.line":303},"message":"failed to ack update open C:\\Program Files\\Elastic\\Agent\\data\\.update-marker: O sistema não conseguiu localizar o ficheiro especificado.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:52.159Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is og1TyYr_","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:52.160Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-15T14:02:54.062Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-15T14:02:54.062Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-verify failed, err: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-15T14:02:54.063Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-15T14:02:54.063Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-15T15:02:54+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to FAILED: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:56.536Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is og1TyYr_","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:02:56.536Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:03:01.876Z","log.origin":{"file.name":"operation/operation_fetch.go","file.line":75},"message":"downloaded binary 'filebeat.8.0.0-SNAPSHOT' into 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip' as part of operation 'operation-fetch'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:03:09.565Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:03:09+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:03:10.852Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:03:10+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:03:11.351Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:03:11+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-15T14:03:11.403Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-15T15:03:11+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to FAILED: operation 'operation-verify' failed to verify metricbeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-15T14:03:11.403Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-verify failed, err: operation 'operation-verify' failed to verify metricbeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-15T14:03:11.404Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'operation-verify' failed to verify metricbeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n: operation 'operation-verify' failed to verify metricbeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-5f65a3\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:03:13.468Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is og1TyYr_","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:03:13.468Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:03:14.740Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for filebeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:03:14.740Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-start' skipped for filebeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
```

**Comment by alvarolobato** [comment]
After running as admin, I tried again with the local account and the log is a bit different:
```
{"log.level":"info","@timestamp":"2021-07-15T14:04:12.560Z","log.origin":{"file.name":"warn/warn.go","file.line":18},"message":"The Elastic Agent is currently in BETA and should not be used in production","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:12.562Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:12.564Z","log.origin":{"file.name":"application/application.go","file.line":93},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:12.564Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:12.912Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:12.916Z","log.origin":{"file.name":"store/state_store.go","file.line":327},"message":"restoring current policy from disk","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:13.737Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is R7CH5TmL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:13.737Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:15.054Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for filebeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:15.398Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:15+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:15.809Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:15+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:15.810Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:15+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:15.810Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:15+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:16.752Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for metricbeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:17.225Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:17+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:18.070Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:18+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:18.073Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:18+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:18.073Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:18+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:18.465Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for filebeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:19.097Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:19+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:19.448Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:19+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:19.449Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:19+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:19.450Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:19+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:20.399Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for metricbeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:21.196Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:21+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:21.207Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":66},"message":"Updating internal state","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:21.226Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is qRAQ5ssd","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:21.226Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:22.025Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:22+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:22.027Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:22+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-15T14:04:22.027Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-15T15:04:22+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[4be223b4-aeda-4de4-824c-d4673cdab529]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
```

and permissions:
[agent-perms.csv](https://github.com/elastic/beats/files/6823685/agent-perms.csv)

**Comment by blakerouse** [comment]
@alvarolobato Seems like it crashes and is not logging why it failed on the one run as SYSTEM. Comparing to the one run as Administrator seems like maybe the `Start stats endpoint` is crashing.

Could you try to use https://github.com/mkellerman/Invoke-CommandAs and run from inside the installed directory the `elastic-agent run` command. Maybe running with `-AsSystem` it can expose why it is crashing.

**Comment by alvarolobato** [comment]
@blakerouse 
Ok, maybe this error message helps, this is how it crashed:
```
C:\Program Files\Elastic\Agent>elastic-agent.exe
could not start the HTTP server for the API: cannot generate security descriptor for the named pipe: failed to lookup Administrators group: Não foi efectuado qualquer mapeamento entre nomes de contas e IDs de segurança.�
```

it looks like it's looking for a group by name instead of GUID

**Comment by blakerouse** [comment]
@alvarolobato Okay. That one is a little deeper in libbeat, so I will let you know once I have another fix for you.

**Comment by blakerouse** [comment]
@alvarolobato Can you give it another try? Thanks for the continued help!

**Comment by alvarolobato** [comment]
We are one step closer, the elastic agent service now runs, but it fails to install endpoint and I'm not getting any metrics or logs, these are the logs:

```
{"log.level":"info","@timestamp":"2021-07-16T17:17:43.756Z","log.origin":{"file.name":"warn/warn.go","file.line":18},"message":"The Elastic Agent is currently in BETA and should not be used in production","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:43.757Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:43.759Z","log.origin":{"file.name":"application/application.go","file.line":93},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:43.759Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:44.164Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:44.166Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:44.166Z","log.origin":{"file.name":"application/managed_mode.go","file.line":290},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:44.166Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: \\\\.\\pipe\\elastic-agent (configured: npipe:///elastic-agent)","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2021-07-16T17:17:44.268Z","log.origin":{"file.name":"application/managed_mode.go","file.line":303},"message":"failed to ack update open C:\\Program Files\\Elastic\\Agent\\data\\.update-marker: O sistema não conseguiu localizar o ficheiro especificado.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:47.826Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is u7Qazz5l","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:47.826Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:17:49.706Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:17:49.706Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-16T18:17:49+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to FAILED: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:17:49.706Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-verify failed, err: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:17:49.707Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n: operation 'operation-verify' failed to verify filebeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:52.446Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is u7Qazz5l","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:17:52.447Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:06.642Z","log.origin":{"file.name":"operation/operation_fetch.go","file.line":75},"message":"downloaded binary 'filebeat.8.0.0-SNAPSHOT' into 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\filebeat-8.0.0-SNAPSHOT-windows-x86_64.zip' as part of operation 'operation-fetch'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:11.377Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:11+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:11.694Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:11+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:11.695Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:11+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:11.695Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:11+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:18:12.851Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-16T18:18:12+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to FAILED: operation 'operation-verify' failed to verify metricbeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:18:12.851Z","log.origin":{"file.name":"operation/operation_retryable.go","file.line":85},"message":"operation operation-verify failed, err: operation 'operation-verify' failed to verify metricbeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:18:12.852Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'operation-verify' failed to verify metricbeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n: operation 'operation-verify' failed to verify metricbeat.8.0.0-SNAPSHOT: 3 errors occurred:\n\t* fetching asc file from 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc': open C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: O sistema não conseguiu localizar o ficheiro especificado.\n\t* check detached signature: openpgp: invalid signature: hash tag doesn't match\n\t* fetching asc file from https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc: call to 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip.asc' returned unsuccessful status code: 404\n\n","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:14.971Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is u7Qazz5l","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:14.971Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:16.175Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for filebeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:16.175Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-start' skipped for filebeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:26.556Z","log.origin":{"file.name":"operation/operation_fetch.go","file.line":75},"message":"downloaded binary 'metricbeat.8.0.0-SNAPSHOT' into 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\metricbeat-8.0.0-SNAPSHOT-windows-x86_64.zip' as part of operation 'operation-fetch'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:31.903Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:31+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:32.840Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for filebeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:33.522Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:33+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:34.789Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for metricbeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:35.110Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:35+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:35.113Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:35+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:35.113Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:35+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:35.123Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:35+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:35.124Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:35+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:35.124Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:35+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:35.702Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:35+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:35.721Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":66},"message":"Updating internal state","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:36.406Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'online'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:36.509Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:36+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:36.510Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:36+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:18:36.511Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:18:36+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2021-07-16T17:19:14.041Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'degraded'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:19:14.041Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:19:14+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to DEGRADED: Missed last check-in - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:19:34.042Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:19:34+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to DEGRADED: Missed last check-in - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:19:34.042Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:19:34+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to DEGRADED: Missed last check-in - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:19:39.042Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-16T18:19:39+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to DEGRADED: Missed last check-in - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:20:14.046Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:20:14.046Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-16T18:20:14+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to FAILED: Missed two check-ins - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:20:28.834Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:20:28.834Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:20:34.048Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-16T18:20:34+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to FAILED: Missed two check-ins - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:20:34.051Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-16T18:20:34+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to FAILED: Missed two check-ins - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:20:35.832Z","log.origin":{"file.name":"operation/operation_fetch.go","file.line":75},"message":"downloaded binary 'endpoint-security.8.0.0-SNAPSHOT' into 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-a2b6db\\downloads\\endpoint-security-8.0.0-SNAPSHOT-windows-x86_64.zip' as part of operation 'operation-fetch'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:20:39.052Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-16T18:20:39+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to FAILED: Missed two check-ins - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:20:53.214Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:20:53.214Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-16T18:20:53+01:00 - message: Application: endpoint-security--8.0.0-SNAPSHOT[d7ec58f2-d702-48e0-8e40-dc4d6a51e320]: State changed to FAILED: operation 'Exec' failed (return code: 1): (command had no output) - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:20:56.434Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:20:56.434Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:20:59.903Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:02.394Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:02.395Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:21:05.504Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:07.992Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:07.992Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:21:11.381Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:13.907Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:13.907Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:21:17.056Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:19.604Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:19.604Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:21:23.410Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:25.890Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:25.890Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:21:29.341Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:31.207Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:31.207Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:21:34.423Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:36.593Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:36.593Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:21:39.632Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:47.941Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:47.941Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:21:51.160Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:53.236Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:21:53.236Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:05.263Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:07.772Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:07.772Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:11.253Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:13.680Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:13.680Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:17.272Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:19.478Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:19.478Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:22.752Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:24.920Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:24.920Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:28.094Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:30.328Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:30.328Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:33.570Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:35.980Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:35.980Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:39.176Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:41.507Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:41.507Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:44.869Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:46.994Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:46.994Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:50.459Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:52.834Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:52.834Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:22:55.943Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:58.193Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:22:58.193Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:01.364Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:03.710Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:03.710Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:16.259Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:18.637Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:18.637Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:21.859Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:24.046Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:24.046Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:27.228Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:29.488Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:29.488Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:32.797Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:34.946Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:34.946Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:38.048Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:40.391Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:40.391Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:43.661Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:45.884Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:45.884Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:49.116Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:51.585Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:51.585Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:23:54.762Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:57.167Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:23:57.168Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:00.422Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:02.590Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:02.590Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:05.885Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:08.228Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:08.228Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:11.531Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:13.607Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:13.608Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:25.680Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:28.813Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:28.813Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:32.043Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:34.140Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:34.140Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:37.390Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:39.658Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:39.658Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:42.892Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:45.436Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:45.436Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:48.832Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:51.127Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:51.127Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:54.454Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:56.535Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:24:56.535Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:24:59.814Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:01.924Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:01.924Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:05.195Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:07.440Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:07.440Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:10.646Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:13.032Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:13.032Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:16.250Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:18.935Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:18.935Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:21.817Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:24.265Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:24.265Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:36.179Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:38.699Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:38.699Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:42.035Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:44.244Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:44.245Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:47.360Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:49.627Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:49.628Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:52.726Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:55.208Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:25:55.208Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:25:58.292Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:00.720Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:00.721Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:03.606Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:06.053Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:06.053Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:09.336Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:11.684Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:11.684Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:14.882Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:17.422Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:17.422Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:20.408Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:22.583Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:22.583Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:25.573Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:27.617Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:27.617Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:30.662Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:32.862Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is Y6lymp1G","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:32.862Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:36.061Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:38.664Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:38.664Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:50.234Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:52.424Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:52.424Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:26:55.562Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:57.985Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:26:57.985Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:27:00.958Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:03.148Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:03.148Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:27:06.431Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:08.793Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:08.793Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:27:11.957Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:14.062Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:14.062Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:27:17.137Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:22.414Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:22.414Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:27:25.596Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:31.015Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:31.015Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:27:34.242Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:39.748Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:39.748Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:27:43.129Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:45.701Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:45.701Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:27:48.805Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:51.104Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:27:51.105Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:28:01.825Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:04.050Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:04.050Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:28:07.316Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:09.499Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:09.499Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:28:12.815Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:15.010Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:15.010Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:28:18.042Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:20.474Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:20.474Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-16T17:28:23.614Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:25.966Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is 4ZJajUew","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-16T17:28:25.966Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
```

[agent-perms.csv](https://github.com/elastic/beats/files/6832441/agent-perms.csv)

**Comment by blakerouse** [comment]
@alvarolobato Does everything work without running Endpoint Security? I would like to divide the issue of Endpoint Security into a separate bug. Hoping to hear that everything works without Endpoint Security enabled, so this can be merged.

To check on why it's not working, it looks like Elastic Agent is calling the commands to Endpoint Security and they are failing almost instantly. Using the https://github.com/mkellerman/Invoke-CommandAs you can navigate into the `C:\Program Files\Elastic\Agent\data\elastic-agent-${version}\install\endpoint-security-8.0.0-windows-x86_64\`. Elastic Agent runs the following commands in-order to install Endpoint Security.

1. `endpoint-security.exe verify --log stderr`
2. `endpoint-security.exe install --log stderr --upgrade --resources endpoint-security-resources.zip`

**Comment by alvarolobato** [comment]
@blakerouse I'm not getting any metrics or logs either.
I'll test what you are asking in a few hours, but metricbeat is not shipping anything either.

**Comment by blakerouse** [comment]
@alvarolobato If you can provide the contents of the `elastic-agent-${version}\logs` I can take a look into why the beats are not working.

**Comment by alvarolobato** [comment]
Here goes, at some point the cluster was killed, so you'll see that there.

BTW I also have 6000 folder in C:\Program Files\Elastic\Agent\data\tmp with the name elastic-agent-install-xxxx, all empty
[filebeat_monitor-json.txt](https://github.com/elastic/beats/files/6841208/filebeat_monitor-json.txt)
[filebeat-json.txt](https://github.com/elastic/beats/files/6841210/filebeat-json.txt)
[metricbeat-json.txt](https://github.com/elastic/beats/files/6841212/metricbeat-json.txt)
[metricbeat_monitor-json.txt](https://github.com/elastic/beats/files/6841213/metricbeat_monitor-json.txt)
[elastic-agent-json.log-20210716181743.txt](https://github.com/elastic/beats/files/6841215/elastic-agent-json.log-20210716181743.txt)

**Comment by blakerouse** [comment]
@alvarolobato `"Exiting: could not start the HTTP server for the API: cannot generate security descriptor for the named pipe: failed to lookup Administrators group: Não foi efectuado qualquer mapeamento entre nomes de contas e IDs de segurança."` Seems metricbeat/filebeat all have any issue with the lookup for `Administrators` group. That is because the issue is down in libbeat, but I made the change to just work with Elastic Agent.

I will need to actually modify libbeat in this PR to get this to work on your version of Windows.

**Comment by alvarolobato** [comment]
@blakerouse if you think this is an outlier because of the language of windows, I'm ok with deprioritizing this, I don't want us to go down the rabithole of all this if this is an odd outlier.

**Comment by blakerouse** [comment]
@alvarolobato This is an outlier because of the language of Windows. But I think we do need to fix this or it will cause a support headache for us when others using different languages of Windows hit this issue.

I just pushed a new change that I think will actually fix this issue, at least for filebeat and metricebeat.

**Comment by alvarolobato** [comment]
@blakerouse sounds good. Is there a way to test it?, because by default agent will download filebeat and metricbeat right?

**Comment by blakerouse** [comment]
@alvarolobato Can you test again? Finally got a good build.

**Comment by alvarolobato** [comment]
@blakerouse getting similar results, I did the installation twice to make sure I didn't make any mistake and still have a similar issue.
[elastic-agent-json.log-20210722121148.txt](https://github.com/elastic/beats/files/6861791/elastic-agent-json.log-20210722121148.txt)
[elastic-agent-json.log-20210722121151.txt](https://github.com/elastic/beats/files/6861792/elastic-agent-json.log-20210722121151.txt)
[filebeat_monitor-json.log-2021-07-22-12-1.txt](https://github.com/elastic/beats/files/6861793/filebeat_monitor-json.log-2021-07-22-12-1.txt)
[filebeat_monitor-json.log-2021-07-22-12-2.txt](https://github.com/elastic/beats/files/6861794/filebeat_monitor-json.log-2021-07-22-12-2.txt)
[filebeat_monitor-json.log-2021-07-22-12-3.txt](https://github.com/elastic/beats/files/6861795/filebeat_monitor-json.log-2021-07-22-12-3.txt)
[filebeat_monitor-json.log.txt](https://github.com/elastic/beats/files/6861796/filebeat_monitor-json.log.txt)
[filebeat-json.log-2021-07-22-12-1.txt](https://github.com/elastic/beats/files/6861797/filebeat-json.log-2021-07-22-12-1.txt)
[filebeat-json.log-2021-07-22-12-2.txt](https://github.com/elastic/beats/files/6861798/filebeat-json.log-2021-07-22-12-2.txt)
[filebeat-json.log-2021-07-22-12-3.txt](https://github.com/elastic/beats/files/6861799/filebeat-json.log-2021-07-22-12-3.txt)
[filebeat-json.log.txt](https://github.com/elastic/beats/files/6861800/filebeat-json.log.txt)
[metricbeat_monitor-json.log-2021-07-22-12-1.txt](https://github.com/elastic/beats/files/6861801/metricbeat_monitor-json.log-2021-07-22-12-1.txt)
[metricbeat_monitor-json.log-2021-07-22-12-2.txt](https://github.com/elastic/beats/files/6861802/metricbeat_monitor-json.log-2021-07-22-12-2.txt)
[metricbeat_monitor-json.log-2021-07-22-12-3.txt](https://github.com/elastic/beats/files/6861803/metricbeat_monitor-json.log-2021-07-22-12-3.txt)
[metricbeat_monitor-json.log.txt](https://github.com/elastic/beats/files/6861804/metricbeat_monitor-json.log.txt)
[metricbeat-json.log-2021-07-22-12-1.txt](https://github.com/elastic/beats/files/6861805/metricbeat-json.log-2021-07-22-12-1.txt)
[metricbeat-json.log-2021-07-22-12-2.txt](https://github.com/elastic/beats/files/6861806/metricbeat-json.log-2021-07-22-12-2.txt)
[metricbeat-json.log-2021-07-22-12-3.txt](https://github.com/elastic/beats/files/6861807/metricbeat-json.log-2021-07-22-12-3.txt)
[metricbeat-json.log.txt](https://github.com/elastic/beats/files/6861808/metricbeat-json.log.txt)

**Comment by blakerouse** [comment]
@alvarolobato I wonder if the build you are using is the correct one, like maybe the build was not published correctly or something?

Because just grep-ing through all the code based for `failed to lookup` shows no results in my branch. That makes me think the filebeat and metricbeat that is being used on your system is not the one built from this PR.

**Comment by blakerouse** [comment]
Is this the one your using https://storage.googleapis.com/beats-ci-artifacts/pull-requests/pr-26665/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip ?

**Comment by alvarolobato** [comment]
@blakerouse  I thought exactly the same, it's very strange. This is the exact URL I used, copied from the browser: https://storage.googleapis.com/beats-ci-artifacts/pull-requests/pr-26665/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip

Also the build is different from the previous one, it has 13KB more than before and build dates are 2021-07-21 at 14:03:10 (don't know the timezone) so it matches with your PR.

Can you launch the job again and see if not all the changes are in?

**Comment by blakerouse** [comment]
@alvarolobato Here is latest link that shows created time of `Jul 22, 2021, 10:30:41 AM`

https://storage.googleapis.com/beats-ci-artifacts/pull-requests/pr-26665/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip

**Comment by alvarolobato** [comment]
@blakerouse filebeat and metricbeat are working now and reporting data, the file was different from the previous one, that's odd.

Endpoint still failing, but I guess you want to split this and give it to security.

```
{"log.level":"info","@timestamp":"2021-07-22T16:26:37.489Z","log.origin":{"file.name":"cmd/run.go","file.line":133},"message":"Artifact has been built with security disabled. Elastic Agent will not verify signatures of the artifacts.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:39.749Z","log.origin":{"file.name":"application/application.go","file.line":66},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2021-07-22T16:26:39.753Z","log.logger":"cfgwarn","log.origin":{"file.name":"tlscommon/config.go","file.line":100},"message":"DEPRECATED: Treating the CommonName field on X.509 certificates as a host name when no Subject Alternative Names are present is going to be removed. Please update your certificates if needed. Will be removed in version: 8.0.0","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:39.753Z","log.origin":{"file.name":"application/application.go","file.line":91},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:39.754Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:40.387Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:40.390Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:40.390Z","log.origin":{"file.name":"application/managed_mode.go","file.line":290},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:40.390Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: \\\\.\\pipe\\elastic-agent (configured: npipe:///elastic-agent)","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2021-07-22T16:26:40.491Z","log.origin":{"file.name":"application/managed_mode.go","file.line":303},"message":"failed to ack update open C:\\Program Files\\Elastic\\Agent\\data\\.update-marker: O sistema não conseguiu localizar o ficheiro especificado.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:43.792Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is GsX8yolV","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:43.792Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 3 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:48.375Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-22T17:26:48+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:50.277Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-22T17:26:50+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:52.420Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-22T17:26:52+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:52.794Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for filebeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:53.081Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-22T17:26:53+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:53.418Z","log.origin":{"file.name":"operation/operator.go","file.line":259},"message":"operation 'operation-install' skipped for metricbeat.8.0.0-SNAPSHOT","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:53.966Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-22T17:26:53+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:53.981Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":66},"message":"Updating internal state","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:54.802Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-22T17:26:54+01:00 - message: Application: filebeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:54.866Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-22T17:26:54+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:26:56.268Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2021-07-22T17:26:56+01:00 - message: Application: metricbeat--8.0.0-SNAPSHOT--36643631373035623733363936343635[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:15.620Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:15.621Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:18.190Z","log.origin":{"file.name":"operation/operation_fetch.go","file.line":75},"message":"downloaded binary 'endpoint-security.8.0.0-SNAPSHOT' into 'C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-93b14a\\downloads\\endpoint-security-8.0.0-SNAPSHOT-windows-x86_64.zip' as part of operation 'operation-fetch'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:29:34.589Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'error'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:29:34.590Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2021-07-22T17:29:34+01:00 - message: Application: endpoint-security--8.0.0-SNAPSHOT[9174d0a3-d3c7-4417-9da8-ddd19108e974]: State changed to FAILED: operation 'Exec' failed (return code: 1): (command had no output) - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:29:34.590Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:36.673Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:36.673Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:29:39.538Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:41.855Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:41.855Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:29:44.530Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:46.901Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:46.902Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:29:49.670Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:51.887Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:51.888Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:29:54.561Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:56.891Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:29:56.892Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:29:59.570Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:02.081Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:02.082Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:04.676Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:07.124Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:07.124Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:09.933Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:12.161Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:12.161Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:14.871Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:17.148Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:17.148Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:19.872Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:22.429Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:22.429Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:25.183Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:27.674Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:27.674Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:30.364Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:32.922Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:32.923Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:35.657Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:37.932Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:37.932Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:50.416Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:52.822Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:52.823Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:30:55.644Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:58.145Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:30:58.145Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:31:00.891Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:03.058Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:03.058Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:31:06.016Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:08.087Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:08.087Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:31:10.719Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:12.987Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:12.987Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:31:15.754Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:18.225Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:18.226Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:31:21.046Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:23.376Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:23.377Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:31:25.773Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:28.270Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:28.271Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2021-07-22T16:31:30.950Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":180},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: operation 'Exec' failed (return code: 1): (command had no output): operation 'Exec' failed (return code: 1): (command had no output)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:33.227Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is B65qeITL","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2021-07-22T16:31:33.227Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 4 step(s)","ecs.version":"1.6.0"}

```

**Comment by blakerouse** [comment]
@alvarolobato Yeah let's split it. I will merge this for Elastic Agent and beats, and then we can work on the issue for Endpoint Security.

**Comment by alvarolobato** [comment]
@blakerouse thanks for all the work put into these painful bugs, I know it's really hard and frustrating when you can't reproduce it yourself.
