### PR TITLE
Fix authentication in HTTP helper

### LINKED ISSUE #11351: HTTP-based metricbeat modules can no longer perform authentication
- Version: `master` / `8.0.0`
- Operating System: Mac OS X
- Steps to Reproduce: 
  1. Setup Elasticsearch with Trial license, Security enabled, and `elastic` user to have password as `abc123`.
  1. Enable Elasticsearch metricbeat module.
     ```
     ./metricbeat modules enable elasticsearch
     ```
  2. Uncomment and set `username` and `password` settings in the Elasticsearch metricbeat module configuration.
     ```
     username: elastic
     password: abc123
     ```
  3. Start Metricbeat.
     ```
     ./metricbeat -e
     ```

You will see a 401 Unauthorized error in the logs. 

Looking at Wireshark, it looks like Metricbeat does not add the `Authorization` header, as one would expect it to with the above configuration:

Screen Shot 2019-03-20 at 12 43 02 PM

I did a similar test with the Kibana Metricbeat module and ended up with the same results: 401 error in the logs and Wireshark showing no `Authorization` header.

### PR DESCRIPTION
**Pull request by jsoriano**
After the refactor done in #11032, baseData was not being passed to the
HTTP helper, so authentication was not working.

Added a test to avoid regressions here.

Fix #11351

### CODE REVIEW

File: metricbeat/helper/http_test.go [hunk 1]
```diff
@@ -113,6 +113,47 @@ func TestConnectTimeout(t *testing.T) {
...
+	assert.Equal(t, http.StatusUnauthorized, response.StatusCode, "response status code")
+
+	// Authorized
+	hostData = mb.HostData{
+		URI:          ts.URL,
+		SanitizedURI: ts.URL,
+		User:         expectedUser,
+		Password:     expectedPassword,
+	}
+	t.Logf("FOO %+v\n", hostData)
```
Comment (ycombinator) [inline metricbeat/helper/http_test.go]: Debugging statement?

Comment (jsoriano) [reply metricbeat/helper/http_test.go]: :man_facepalming:

**Comment by jsoriano** [comment]
jenkins, test this again please
