### PR TITLE
Keep different registry entry per container stream

### LINKED ISSUE #7045: filebeat docker input stores wrong offset
- Version: 6.2.4
- Operating System:  CentOS 7
- Steps to Reproduce: 

I'm running 2 docker inputs (for stdout and stderr) for the same container log file and all working good until the restart of filebeat after which offset gets wrong number of bytes saved, and docker JSON decoding puts the error:
<pre>
2018-05-08T13:50:25.423Z	ERROR	log/harvester.go:243	Read line error: decoding docker JSON: invalid character 'R' looking for beginning of value; File: %!(EXTRA string=/var/lib/docker/containers/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0-json.log)
</pre>

<pre>

2018-05-08T13:50:25.423Z	DEBUG	[harvester]	log/harvester.go:468	Stopping harvester for file: /var/lib/docker/containers/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0-json.log

2018-05-08T13:50:25.423Z	DEBUG	[harvester]	log/harvester.go:478	Closing file: /var/lib/docker/containers/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0-json.log

2018-05-08T13:50:25.423Z	DEBUG	[harvester]	log/harvester.go:348	Update state: /var/lib/docker/containers/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0-json.log, offset: 20350
</pre>

<pre>
# dd if=/var/lib/docker/containers/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0-json.log bs=1 skip=20350 count=100
RV_USER=\"$3\"\\nSERV_PASS=\"$4\"\\nDB_FOLDER=${5-\"mysqldumps\"}\\nPREFIX_LOCAL=${6-\"/home/httpd\"
</pre>
and the error:
<pre>
2018-05-08T13:50:25.423Z	ERROR	log/harvester.go:243	Read line error: decoding docker JSON: invalid character 'R' looking for beginning of value; File: %!(EXTRA string=/var/lib/docker/containers/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0/6a394f8e4332087bce1fb95223aad238dc6bc27c7cebe2f493909a3734c7e0c0-json.log)
</pre>
infinitely repeated.

But when switching input for the same container to "log" error appears one more time and after that all working as expected.

filebeat config:
<pre>
filebeat.autodiscover:
  providers:
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.labels.log_type: test
      config:
      - type: docker
        containers:
          ids:
          - "${data.docker.container.id}"
          stream: stdout
        processors:
         - add_docker_metadata: ~
      - type: docker
        containers:
          ids:
          - "${data.docker.container.id}"
          stream: stderr
        multiline.pattern: '^\['
        multiline.negate: true
        multiline.match: after
        processors:
         - add_docker_metadata: ~
output.logstash:
  hosts:
  - "logstash:5044"

</pre>

### PR DESCRIPTION
**Pull request by exekias**
This PR adds a metadata map to prospectors state. Adding metadata to states allows having a different state per unique metadata for the same file.

This change is used by the `docker` prospector to have different states per stream, as some users configure a container prospector per stream (`stdout` & `stderr`).

Probably fixes #7045

### CODE REVIEW

**Comment by exekias** [comment]
Hound wanted me to rename `Id` field to `ID`, but that would spawn a broader changelog, I don't think it's worth it, as this field wasn't added on this PR.

File: filebeat/input/file/state.go [hunk 1]
```diff
@@ -30,14 +35,16 @@ func NewState(fileInfo os.FileInfo, path string, t string) State {
...
 	}
 }
 
 // ID returns a unique id for the state as a string
 func (s *State) ID() string {
 	// Generate id on first request. This is needed as id is not set when converting back from json
 	if s.Id == "" {
-		s.Id = s.FileStateOS.String()
+		h, _ := hashstructure.Hash(s.Meta, nil)
+		s.Id = s.FileStateOS.String() + fmt.Sprintf("-%d", h)
```
Comment (urso) [inline filebeat/input/file/state.go]: ouch... we optimized ID generation by removing Sprintf and reduce allocations. The ID generation used to be one of the worst offenders in CPU profiles. This change makes it worse again. How about:

```
if s.Meta == nil {
  s.Id = s.FileStateOS.String()
} else {
  hashValue, _ := hashstructure.Hash(s.Meta, nil)
  var hashBuf [17]byte
  hash, _ := strconv.AppendUint(h[:0], hashValue, 16)
  hash = append(hash, '-')

  fileID := s.FileStateOS.String()  

  var b strings.Builder
  b.Grow(len(hash) + len(fileID))
  b.Write(hash)
  b.WriteString(fileID)

  s.Id = b.String()
}
```

This still does execute an extra alloc, but only in the docker case and should be less expensive.

File: filebeat/input/file/state.go [hunk 2]
```diff
@@ -49,5 +56,5 @@ func (s *State) IsEqual(c *State) bool {
 
 // IsEmpty returns true if the state is empty
 func (s *State) IsEmpty() bool {
-	return *s == State{}
+	return reflect.DeepEqual(*s, State{})
```
Comment (urso) [inline filebeat/input/file/state.go]: we need `DeepEqual`?

Comment (urso) [reply filebeat/input/file/state.go]: How about `tmp := *s; tmp.Meta = nil; return tmp == State{} && len(s.Meta) == 0`

File: filebeat/input/file/state.go (hunk 1 above)
Comment (exekias) [reply filebeat/input/file/state.go]: sounds like a good idea, pushing this change

File: filebeat/input/file/state.go (hunk 2 above)
Comment (exekias) [reply filebeat/input/file/state.go]: The compiler still says it cannot compare maps, are your concerns about performance? I could do manual comparison for all fields, or use 2 structs like:

```
type State struct {
   Common
   Meta        map[string]string `json:"meta"`
}
```

then:

```
if len(s.Meta) > 0 { return false }
return *s.Common == Common{}
```

Comment (urso) [reply filebeat/input/file/state.go]: a little performance, but I'd also prefer to keep out `reflect` from most packages.

I wonder if checking for FileStateOS or the timestamp only would be enough. This method is used to determine if we have a valid/usable state or not.

Comment (exekias) [reply filebeat/input/file/state.go]: I don't have enough experience with all the possible situations with the registry so I'll trust you here on what to do :innocent:

Comment (exekias) [reply filebeat/input/file/state.go]: I updated this to use `s.FileStateOS != file.StateOS{} && !s.Timestamp.IsZero()`, also pinging @ruflin for awareness

**Comment by exekias** [comment]
This should be ready for another review, thanks for all the help @urso!

**Comment by exekias** [comment]
jenkins, retest this please

**Comment by exekias** [comment]
jenkins, retest this please

**Comment by exekias** [comment]
jenkins, retest this please

File: filebeat/tests/system/test_registrar.py [hunk 3]
```diff
@@ -1506,3 +1506,58 @@ def test_registrar_files_with_input_level_processors(self):
...
+
+    def test_registrar_meta(self):
+        """
+        Check that multiple entries for the same file are on the registry when they have
+        different meta
+        """
+
+        self.render_config_template(
+            type='docker',
+            input_raw='''
```
Comment (urso) [inline filebeat/tests/system/test_registrar.py]: btw. check out the `textwrap` package. This allows you to indent multiline strings within the code more properly.

**Comment by urso** [comment]
LGTM and filebeat CI is green. Waiting for review from @ruflin

File: filebeat/input/file/state.go [hunk 4]
```diff
@@ -49,5 +72,8 @@ func (s *State) IsEqual(c *State) bool {
 
 // IsEmpty returns true if the state is empty
 func (s *State) IsEmpty() bool {
-	return *s == State{}
+	return s.FileStateOS == file.StateOS{} &&
```
Comment (ruflin) [inline filebeat/input/file/state.go]: Can you share some details here on why not only add s.Meta but also the other chnages?

Comment (exekias) [reply filebeat/input/file/state.go]: As I added a map to the `State` struct, a simple comparison is no longer possible (Go doesn't implement map compare), I had to update the code to do an individual comparison on the struct fields

**Comment by exekias** [comment]
Docker `json-file` format stores both `stderr` and `stdout` in the same file. They use a JSON object per line, with the following schema:

```
{"log":"example line\n","stream":"stdout","time":"2018-04-13T08:38:08.395077018Z"}
{"log":"example line\n","stream":"stderr","time":"2018-04-13T08:38:08.395077018Z"}
```

Our `docker` input can parse that and demultiplex the 2 different streams, as some times you want to do different processing on them (for instance, pass them to 2 different filesets)
