### PR TITLE
[Winlogbeat] Add support for eventID 4688 & 4689

### LINKED ISSUE #14038: Add events 4688 4689 to winlogbeat security module
2 of the most interesting event id's in siem are `4688 `and `4689`, which can be enabled with a gpo and enable us to monitor every command used in your network.

Interesting fields are:

    winlog.event_data.NewProcessName
    winlog.event_data.ParentProcessName
    winlog.event_data.ProcessName

See https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4688

To be able to properly use the data coming from those events, the `process.name` should be parsed from `winlog.event_data.NewProcessName`, as a lot of `winlog.event_data.NewProcessName` contain %USERPROFILE%

I was able to start extracting with the following winlogbeat-security.js 👍 

```
var securitycommand = (function () {
    var path = require("path");
    var processor = require("processor");
    var winlogbeat = require("winlogbeat");

    var addAuthSuccess = new processor.AddFields({
        fields: {
            "event.category": "authentication",
            "event.type": "authentication_success",
        },
        target: "",
    });

    var addAuthFailed = new processor.AddFields({
        fields: {
            "event.category": "authentication",
            "event.type": "authentication_failure",
        },
        target: "",
    });

    var convertAuthentication = new processor.Convert({
        fields: [
            {from: "winlog.event_data.TargetUserSid", to: "user.id"},
            {from: "winlog.event_data.TargetUserName", to: "user.name"},
            {from: "winlog.event_data.TargetDomainName", to: "user.domain"},
            {from: "winlog.event_data.ProcessId", to: "process.pid", type: "long"},
            {from: "winlog.event_data.ProcessName", to: "process.executable"},
            {from: "winlog.event_data.IpAddress", to: "source.ip", type: "ip"},
            {from: "winlog.event_data.IpPort", to: "source.port", type: "long"},
            {from: "winlog.event_data.WorkstationName", to: "source.domain"},
        ],
        mode: "rename",
        ignore_missing: true,
        fail_on_error: false,
    });

    var setProcessNameUsingExe = function(evt) {
        var name = evt.Get("process.name");
        if (name) {
            return;
        }
        var exe = evt.Get("process.executable");
        evt.Put("process.name", path.basename(exe));
    };

    var setProcessNameUsingNewProcessName = function(evt) {
        var processnamefull = evt.Get("winlog.event_data.NewProcessName");
        evt.Put("process.name", path.basename(processnamefull));
    };

    var logonSuccess = new processor.Chain()
        .Add(addAuthSuccess)
        .Add(convertAuthentication)
        .Add(setProcessNameUsingExe)
        .Build();

    var logonFailed = new processor.Chain()
        .Add(addAuthFailed)
        .Add(convertAuthentication)
        .Add(setProcessNameUsingExe)
        .Build();

    var processCreated = new processor.Chain()
        .Add(setProcessNameUsingNewProcessName)
        .Build();
		
    return {
        // 4624 - An account was successfully logged on.
        4624: logonSuccess.Run,

        // 4625 - An account failed to log on.
        4625: logonFailed.Run,

        // 4648 - A logon was attempted using explicit credentials.
        4648: logonSuccess.Run,
		
		// 4688 - A process was created
		4688: processCreated.Run,

        process: function(evt) {
            var event_id = evt.Get("winlog.event_id");
            var processor = this[event_id];
            if (processor === undefined) {
                return;
            }
            processor(evt);
        },
    };
})();

function process(evt) {
    return securitycommand.process(evt);
}
```

Questions that remain are:
-  What to do with `winlog.event_data.ParentProcessName`? (Afaik there is not yet an ECS field for that, see also https://github.com/elastic/ecs/issues/414)
- While we are at it, `winlog.event_data.SubjectUserName` should also be renamed / copied to `user.name`?

### PR DESCRIPTION
**Pull request by leehinman**
- add support for 4688 (Process created)
- add support for 4689 (Process exited)

Fixes #14038

### CODE REVIEW

**Comment by andrewkroh** [comment]
jenkins, test this

File: x-pack/winlogbeat/module/security/config/winlogbeat-security.js [hunk 1]
```diff
@@ -1235,6 +1263,16 @@ var security = (function () {
...
         .Build();
 
+    var event4688 = new processor.Chain()
+        .Add(copySubjectUser)
+	.Add(renameNewProcessFields)
+        .Build();    
+
+    var event4689 = new processor.Chain()
+        .Add(copySubjectUser)
+	.Add(renameCommonAuthFields)
```
Comment (andrewkroh) [inline x-pack/winlogbeat/module/security/config/winlogbeat-security.js]: Looks like there's a mix of tabs and spaces causing an alignment issue.

File: x-pack/winlogbeat/module/security/config/winlogbeat-security.js [hunk 2]
```diff
@@ -1192,6 +1192,34 @@ var security = (function () {
...
+            }
+            var exe = evt.Get("process.executable");
+            evt.Put("process.name", path.basename(exe));
+        })
+	.Add(function(evt) {
+	    var cl = evt.Get("winlog.event_data.CommandLine");
+	    if (!cl) {
+		return;
+	    }
+	    evt.Put("process.args", cl.match(/\S+/g));
```
Comment (andrewkroh) [inline x-pack/winlogbeat/module/security/config/winlogbeat-security.js]: There's a windows function for this that we have exposed as a module. For example see:

https://github.com/elastic/beats/blob/ca81776033889ad59bc3b571e58ea1a90fba4f5e/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js#L245

`process.command_line` is a new field that is being added to ECS (https://github.com/elastic/ecs/pull/599/files#diff-79c5c20c38369780c00142b4bc7bb519R2980). It will contain the raw command line string.

File: x-pack/winlogbeat/module/security/config/winlogbeat-security.js [hunk 3]
```diff
@@ -1192,6 +1192,34 @@ var security = (function () {
         target: "",
     });
 
+    var renameNewProcessFields = new processor.Chain()
+        .Convert({
+            fields: [
+                {from: "winlog.event_data.NewProcessId", to: "process.pid", type: "long"},
+                {from: "winlog.event_data.NewProcessName", to: "process.executable"},
+		{from: "winlog.event_data.ParentProcessName", to: "process.parent.name"},
```
Comment (andrewkroh) [inline x-pack/winlogbeat/module/security/config/winlogbeat-security.js]: Spacing/alignment issue.

Comment (andrewkroh) [reply x-pack/winlogbeat/module/security/config/winlogbeat-security.js]: I think `winlog.event_data.ParentProcessName`  should map to `process.parent.executable`. Then `process.parent.name` should be set to the `basename(process.parent.executable)`.

File: x-pack/winlogbeat/module/security/config/winlogbeat-security.js [hunk 4]
```diff
@@ -1235,6 +1263,16 @@ var security = (function () {
         .Add(addActionDesc)
         .Build();
 
+    var event4688 = new processor.Chain()
+        .Add(copySubjectUser)
+	.Add(renameNewProcessFields)
+        .Build();
```
Comment (andrewkroh) [inline x-pack/winlogbeat/module/security/config/winlogbeat-security.js]: In the sysmon module we add an `event.category` and `event.type` for event ID 1 and 5. To be consistent I'd apply those same values here. We might have to change them in the future when ECS finalizes on a set of categories.

https://github.com/elastic/beats/blob/ca81776033889ad59bc3b571e58ea1a90fba4f5e/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js#L396-L397
https://github.com/elastic/beats/blob/ca81776033889ad59bc3b571e58ea1a90fba4f5e/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js#L491-L492

**Comment by leehinman** [comment]
jenkins, test this

**Comment by strawgate** [comment]
Any chance this will get included in 7.5? This is the missing piece to having uncommon processes in the siem app populated correctly
