### PR TITLE
[Auditbeat][add_session_metadata processor] Fix more potential enrichment failures

### LINKED ISSUE #38955: [Security-Linux Platform Integrations]  Auditbeat missing Session View Process fields
Audibeat is missing process fields for Session View which is causing empty rows Sessions and Events Table.

I was testing the Session View on FE with auditbeat on my [PR](https://github.com/elastic/kibana/pull/179985). I just noticed some auditbeat events did not have Session View Icon. When I expand the event details,  I saw the process.entry_leader.entity_id  field  was missing.

To test  bug
See [Session View Cloud Credentials](https://p.elstc.co/paste/Ci0L3gSA#ASz3bkZps3AsJQyDlHDagExU2LK0-cLTuqc+aq/sf1E)

Steps to Reproduce
1. Go to Discover
2. Choose audibeat dataview
3. Apply fields not process.entry_leader.entity_id : * and event.action : "executed"
4. Click arrow icon and expand document details
image

1. Go to Explore > Hosts > Events or  Explore > Hosts > Sessions

Sessions are also Missing
image
Events are also missing
image

DOD
* For Session View events and sessions, process fields should be populated. Audibeat Index to filter documents that don't have `process.entry_leader.entity_id`  or missing Session View process fields.

### PR DESCRIPTION
**Pull request by mjwolf**
## Proposed commit message

Fix two more cases that could cause unenriched processes in the add_session_metadata processor.

It was possible for auditd events to arrive before the ebpf event added processes to the process DB, now the enrichment will wait for the process to be inserted into the DB, if it's not already before enrichment is run on it. Also stop attempting to enrich failed syscall events, and modifying the DB based on these.

Changes:

* With the ebpf backend, when an event is processed wait for a process to be added to the DB before enriching, if it's not already in the DB before the event is received.
* Do not enrich failed syscall auditd events. Since failed syscalls don't actually cause a process to be created, they should not be enriched, or inserted to the process 
* Remove scrapeAncestors from DB. The intention of this was to fill in missed processes, but now processes should not be missed with epbf, and ineffective with procfs, as the process will most likely already be ended. This was causing DB inconsistancies when run on failed syscall events, and I haven't ever seen any cases where it's helpful now.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

1. Setup Auditbeat with the session view processors and connected to ES/Kibana.
2. Run some commands in a session. Compile commands, such as building Beats, caused many unenriched processes before this fix, so it's good to try that.
3. In Kibana, on the host page, apply this filter `not process.entry_leader.entity_id : * and process.pid: * and not auditd.result: "fail"`
4. There shouldn't be any events shown.

## Related issues

- Closes #38955

### CODE REVIEW

File: x-pack/auditbeat/processors/sessionmd/provider/ebpf_provider/ebpf_provider.go [hunk 1]
```diff
@@ -151,7 +152,80 @@ func NewProvider(ctx context.Context, logger *logp.Logger, db *processdb.DB) (pr
...
+	}
+
+	now := time.Now()
+	if inBackoff {
+		if now.Sub(backoffStart) > backoffDuration {
+			s.logger.Warnf("ended backoff, skipped %d processes", backoffSkipped)
+			inBackoff = false
+			combinedWait = 0 * time.Millisecond
+		} else {
+			backoffSkipped += backoffSkipped
```
Comment (nicholasberlin) [inline x-pack/auditbeat/processors/sessionmd/provider/ebpf_provider/ebpf_provider.go:191]: should this be `+= 1`?

Comment (mjwolf) [reply x-pack/auditbeat/processors/sessionmd/provider/ebpf_provider/ebpf_provider.go]: Yep, thanks!

File: x-pack/auditbeat/processors/sessionmd/add_session_metadata.go [hunk 2]
```diff
@@ -96,13 +96,24 @@ func New(cfg *cfg.C) (beat.Processor, error) {
...
+	pi, err := ev.GetValue(p.config.PIDField)
 	if err != nil {
 		// Do not attempt to enrich events without PID; it's not a supported event
 		return ev, nil //nolint:nilerr // Running on events without PID is expected
 	}
 
-	err = p.provider.UpdateDB(ev)
+	// Do not enrich failed syscalls, as there was no actual process change related to it
+	v, err := ev.GetValue("auditd.result")
+	if err == nil && v == "fail" {
```
Comment (pkoutsovasilis) [inline x-pack/auditbeat/processors/sessionmd/add_session_metadata.go:107]: so we don't care here if `err != nil`?

File: x-pack/auditbeat/processors/sessionmd/processdb/db.go [hunk 3]
```diff
@@ -712,29 +709,6 @@ func getTTYType(major uint16, minor uint16) TTYType {
 	return TTYUnknown
 }
 
-func (db *DB) scrapeAncestors(proc Process) {
```
Comment (pkoutsovasilis) [inline x-pack/auditbeat/processors/sessionmd/processdb/db.go:715]: we don't need `scrapeAncestors` any more?

File: x-pack/auditbeat/processors/sessionmd/add_session_metadata.go (hunk 2 above)
Comment (mjwolf) [reply x-pack/auditbeat/processors/sessionmd/add_session_metadata.go:107]: no, we don't. If this processor were to run on a non-auditd process event, it's fine if the auditd fields don't exist. Ideally this will work on any event that has a PID field (although that probably not exactly true right now)

File: x-pack/auditbeat/processors/sessionmd/processdb/db.go (hunk 3 above)
Comment (mjwolf) [reply x-pack/auditbeat/processors/sessionmd/processdb/db.go:715]: no, it's not needed. I removed this for two reasons:

I thought it would help when I added it, but now I've never seen any evidence that it actually does. The changes I made here fixed all the problems I had with ebpf, and I haven't seen it used at all. When processes are missed with procfs backend the process will have ended before it's scraped, so it never helped.

I think it's better that the enrich function be read-only. It's a bit strange that the enrich function was actually writing to the DB sometimes (and it tripped me up when debugging)

There is still procfs scraping with the ebpf backend, when starting up to fill in processes that started before the processor, but that separate

Comment (pkoutsovasilis) [reply x-pack/auditbeat/processors/sessionmd/processdb/db.go:715]: ok now I see thanks for the explanation @mjwolf

File: x-pack/auditbeat/processors/sessionmd/processdb/db.go [hunk 4]
```diff
@@ -568,6 +566,11 @@ func setSameAsProcess(process *types.Process) {
 	}
 }
 
+func (db *DB) HasProcess(pid uint32) bool {
+	_, ok := db.processes[pid]
```
Comment (pkoutsovasilis) [inline x-pack/auditbeat/processors/sessionmd/processdb/db.go:570]: lock here?

**Review by pkoutsovasilis — APPROVED** [review]
lgtm with 1 nit. Also my brain had a hard time digesting `UpdateDB` for ebpf provider

File: x-pack/auditbeat/processors/sessionmd/processdb/db.go (hunk 4 above)
Comment (mjwolf) [reply x-pack/auditbeat/processors/sessionmd/processdb/db.go:573]: I've added a lock. It was without because this is read-only, but it's still better to have, something else could write at the same time.

**Comment by mjwolf** [comment]
> lgtm with 1 nit. Also my brain had a hard time digesting `UpdateDB` for ebpf provider

I'll look into reworking UpdateDB in the future, I want to keep this PR to bugfixes only
