### PR TITLE
[libbeat/output/kafka]: fix panic on Publish after Close

### LINKED ISSUE #46109: Filebeat panics when attempting to shutdown while using Kafka output
Start filebeat with following configuration 

```
filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/*.log

output.kafka:
  hosts: ["localhost:9092"]
  topic: beats 
```

and then stop it after few seconds. You can observe below panic.

```
^Cpanic: send on closed channel

goroutine 115 [running]:
github.com/elastic/beats/v7/libbeat/outputs/kafka.(*client).Publish(0x140002c8508, {0x14000713ec0?, 0x2?}, {0x1064a00d0, 0x1400064af00})
        github.com/elastic/beats/v7/libbeat/outputs/kafka/client.go:196 +0x2f8
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*netClientWorker).publishBatch(0x14000622140, {0x1064952e0?, 0x140003d6000?}, {0x1064a00d0?, 0x1400064af00?})
        github.com/elastic/beats/v7/libbeat/publisher/pipeline/client_worker.go:170 +0x174
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*netClientWorker).run(0x14000622140, {0x1064952e0, 0x140003d6000})
        github.com/elastic/beats/v7/libbeat/publisher/pipeline/client_worker.go:156 +0xcc
created by github.com/elastic/beats/v7/libbeat/publisher/pipeline.makeClientWorker in goroutine 1
        github.com/elastic/beats/v7/libbeat/publisher/pipeline/client_worker.go:75 +0x1d8
```

### PR DESCRIPTION
**Pull request by AndersonQ**
## Proposed commit message

```
A race condition during client shutdown could cause a panic.

If a `Publish` call was in-flight while the client was closing, the underlying Kafka producer's input channel could be closed before the call finished sending all messages in the batch. The subsequent attempt to send the remaining messages on this closed channel would result in a panic.
```

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

- n/a

## How to test this PR locally

 - try the steps described in the bug #46109: (they did not work for me)
 
 - copy the new test, run it on main, you'll see the panic

## Related issues

- Closes #46109

### CODE REVIEW

File: libbeat/outputs/kafka/client_test.go [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+func (p producerMock) AsyncClose() {
+	close(p.input)
+}
+
+func (p producerMock) Input() chan<- *sarama.ProducerMessage {
+	return p.input
+}
+
+func (p producerMock) Close() error {
+	// TODO implement me
```
Comment (andrzej-stencel) [inline libbeat/outputs/kafka/client_test.go]: Are these TODOs needed?

File: libbeat/outputs/kafka/client.go [hunk 2]
```diff
@@ -193,7 +193,13 @@ func (c *client) Publish(_ context.Context, batch publisher.Batch) error {
 
 		msg.ref = ref
 		msg.initProducerMessage()
-		ch <- &msg.msg
+		select {
+		case <-c.done:
+			c.log.Errorf("output closing, dropping event")
+			ref.done()
+			c.observer.PermanentErrors(1)
```
Comment (andrzej-stencel) [inline libbeat/outputs/kafka/client.go:200]: Please help me understand: shouldn't we shortcut here (`break` out of the `for` loop) to prevent repeating this for the remaining events?

File: libbeat/outputs/kafka/client_test.go (hunk 1 above)
Comment (AndersonQ) [reply libbeat/outputs/kafka/client_test.go]: it was auto-generated, I didn't bother deleting them, but I can. I'll then

File: libbeat/outputs/kafka/client.go (hunk 2 above)
Comment (AndersonQ) [reply libbeat/outputs/kafka/client.go:200]: yeah, it'd speed up things a bit. Let me check if it should log the dropped events and I'll fix it

File: libbeat/outputs/kafka/client_test.go (hunk 1 above)
Comment (AndersonQ) [reply libbeat/outputs/kafka/client_test.go]: done https://github.com/elastic/beats/pull/46446/commits/69ac2c205758ccd9c4a57dd102f2c19eabc76ca6

File: libbeat/outputs/kafka/client.go (hunk 2 above)
Comment (AndersonQ) [reply libbeat/outputs/kafka/client.go:200]: well, let's let the logging of events to another PR.
Here is the change you suggested: https://github.com/elastic/beats/pull/46446/commits/f6a987cdd411d9d0320d7b8a958b9a518851d1e6

Comment (AndersonQ) [reply libbeat/outputs/kafka/client.go:200]: we won't log the event because it won't bring any value, the issue isn't related to the event content

Comment (AndersonQ) [reply libbeat/outputs/kafka/client.go:200]: @andrzej-stencel my bad here. It goes event by event to call `ref.done()` and correctly handle the batch. It will decrease the event counter until 0 and them handle the batch ack/event retry

**Review by khushijain21 — APPROVED** [review]

File: libbeat/outputs/kafka/client.go (hunk 2 above)
Comment (andrzej-stencel) [reply libbeat/outputs/kafka/client.go:200]: Oh OK, thanks for looking into this Anderson!

**Review by andrzej-stencel — APPROVED** [review]
Thanks!
