### PR TITLE
Initialise beat early

### LINKED ISSUE #27755: [Beat Monitoring] Beat name is differ with state
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.13.4
- Operating System: linux
- Discuss Forum URL: [Link](https://discuss.elastic.co/t/beat-monitoring-beat-name-is-differ-with-state/283239)
- Steps to Reproduce: 

**metricbeat.yml**
```
name: "sample"
```
**metricbeat.log**
```
2021-09-03T14:46:12.876+0900    INFO    [publisher]     pipeline/module.go:113  Beat name: sample
```
**curl state**
```
[root@ip-01-02-03-04 15:00:04 metricbeat]# curl 127.0.0.1:5066/state
{"beat":{"name":"ip-01-02-03-04.ap-northeast-2.compute.internal"},"host":{"architecture":"x86_64","containerized":"containerized","hostname":"ip-01-02-03-04.ap-northeast-2.compute.internal","id":"----","os":{"codename":"Karoo","family":"redhat","kernel":"4.14.193-149.317.amzn2.x86_64","name":"Amazon Linux","platform":"amzn","version":"2"}},"management":{"enabled":false},"module":{"count":3,"names":["beat","kibana"]},"monitoring":{"cluster_uuid":"----"},"output":{"batch_size":50,"clients":1,"name":"elasticsearch"},"outputs":{"elasticsearch":{"cluster_uuid":"----"}},"queue":{"name":"mem"},"service":{"id":"----","name":"metricbeat","version":"7.13.4"}}
```
Why differ beat name?
I want change beat name for kibana's monitoring page.

### PR DESCRIPTION
**Pull request by belimawr**
## What does this PR do?

Initialise beat early so all required information for monitoring and
state endpoint are available when the state registry is populated.

## Why is it important?

Fixes #27755

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [x] I have added tests

## How to test this PR locally

On any beat, enable the "HTTP endpoint" by adding this at the end of your beat yaml:
```yml
http:
  enabled: true
  host: 0.0.0.0
  port: 5066
```

Start your beat and make a request to `5066/state`:
```sh
curl 127.0.0.1:5066/state | jq
```

## Related issues

- Closes #27755

### CODE REVIEW

**Review by kvch — APPROVED** [review]

**Comment by kvch** [comment]
Feel free to merge it if the tests are green.

File: libbeat/cmd/instance/beat_integration_test.go [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+func (mb mockbeat) Stop() {
+	close(mb.done)
+}
+
+func TestMonitoringNameFromConfig(t *testing.T) {
+	mockBeat := mockbeat{
+		done:     make(chan struct{}),
+		initDone: make(chan struct{}),
+	}
+	wg := sync.WaitGroup{}
```
Comment (kvch) [inline libbeat/cmd/instance/beat_integration_test.go:83]: Nit: we usually write `var wg sync.WaitGroup` in this codebase.

**Review by kvch — APPROVED** [review]

File: libbeat/cmd/instance/beat_integration_test.go (hunk 1 above)
Comment (belimawr) [reply libbeat/cmd/instance/beat_integration_test.go]: Done on 7ccb3aba12
