### PR TITLE
x-pack/filebeat/input/httpjson: allow elision of set and append failure logging

### LINKED ISSUE #34544: [httpjson] Improve handling of end-of-pagination
When we've reached the end of pages to process, we currently log an error: `<.last_response.body.nextPageToken>: map has no entry for key`. This is a red herring for people that are troubleshooting issues, and we're aware of multiple instances of people mistakenly thinking these error logs were an artifact of the problem they were troubleshooting.

We should handle this expected case gracefully.

### LINKED ISSUE #38291: Elastic Agent shouldn't log httpjson pagination completion as an Agent Error
I am not sure if this should be raised against Elastic Agent or the integration.  Raising it here, but please move as necessary.

The Cisco Secure Endpoint integration (v2.24.2) collects event data via httpjson. The integration throws an error when it hits the last page, and this gets logged in the Elastic Agent error log with something similar to:
`error processing response: template: :1:17: executing "" at <.last_response.body.metadata.links.next>: map has no entry for key "next"
`
This fills up the Elastic Agent dashboard with agent errors, as it is raised every time the Secure Endpoint data is polled (every 2 minutes/default) and the noise makes it more difficult to find actual errors.

I believe that this is occurring because `fail_on_template_error` is set to `true`.

The fail condition prompting this is at
[integrations/packages/cisco_secure_endpoint/data_stream/event/agent/stream/httpjson.yml.hbs at main · elastic/integrations (github.com)](https://github.com/elastic/integrations/blob/main/packages/cisco_secure_endpoint/data_stream/event/agent/stream/httpjson.yml.hbs) line 36-40
```
response.pagination:
- set:
    target: url.value
    value: '[[ .last_response.body.metadata.links.next ]]'
    fail_on_template_error: true
```
I'm not sure how this should be fixed, because AIUI fail_on_template_error: true is the recommended configuration for pagination, but raising an error should maybe be reconsidered?

For confirmed bugs, please report:
- Version:
Cisco Secure Endpoint integration v2.24.2
Elastic Agent v1.18.0
Elastic 8.11.2
- Operating System:
Agent running on Windows Server 2019 Standard
- Discuss Forum URL:
https://discuss.elastic.co/t/elastic-agent-shouldnt-log-httpjson-pagination-completion-as-an-error/353565
- Steps to Reproduce:
This should happen on any run of the Secure Endpoint integration

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

See title.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

In the httpjson package run the following commands. The first should show a set of messages at DEBUG level and none at ERROR level. The second should show no output.
```
go test -run 'TestInput/.*_not_log_fail' -v | grep ignored
```
```
go test -run 'TestInput/.*[^_][^n][^o][^t][^_][^l][^o][^g][^_][^f][^a][^i][^l]$' -v | grep ignored # ¯\_(ツ)_/¯
```

## Related issues

- Closes #34544
- Closes #38291

### CODE REVIEW

File: x-pack/filebeat/input/httpjson/input_test.go [hunk 1]
```diff
@@ -384,6 +384,44 @@ var testCases = []struct {
...
+			"response.split": map[string]interface{}{
+				"target": "body.items",
+				"transforms": []interface{}{
+					map[string]interface{}{
+						"set": map[string]interface{}{
+							"target": "body.page",
+							"value":  "[[.last_response.page]]",
+						},
+					},
+				},
```
Comment (chrisberkhout) [inline x-pack/filebeat/input/httpjson/input_test.go:406]: This split transform don't seem relevant to the test.

Comment (efd6) [reply x-pack/filebeat/input/httpjson/input_test.go:406]: The test here is a direct comparison with the test above. I wanted to make it as close as possible to that with just the change in this behaviour so that they could be compared. The same is true of the other test addition here.

**Review by chrisberkhout — APPROVED** [review]
:+1:
