### PR TITLE
[Elastic Agent] Fix status and inspect command to work inside running container

### LINKED ISSUE #24956: elastic-agent status: elastic-agent-control.sock: connect: no such file or directory
Hi,

I tried to integrate with `elastic-agent status`, but it always fail with:

```
bash-4.2$ ./elastic-agent status
Error: failed to communicate with Elastic Agent daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /usr/share/elastic-agent/data/tmp/elastic-agent-control.sock: connect: no such file or directory"
```

More data:

```
bash-4.2$ find . | egrep ".sock$"
./state/data/tmp/elastic-agent.sock
./state/data/tmp/default/metricbeat/metricbeat.sock
./state/data/tmp/default/filebeat/filebeat.sock
./state/data/tmp/elastic-agent-control.sock
```

Missing `state`?

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes issue where the `status` and `inspect` command did not work. This has to do with how the `container` command must setup the paths so it works correctly in a container.

## Why is it important?

So the `status` and the `inspect` command can work inside of a container, without setting a special environment for it to work.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #24956

### CODE REVIEW

File: x-pack/elastic-agent/pkg/agent/cmd/container.go [hunk 1]
```diff
@@ -662,21 +663,75 @@ func setPaths() error {
...
+}
+
+type containerPaths struct {
+	StatePath  string `config:"state_path" yaml:"state_path"`
+	ConfigPath string `config:"state_path" yaml:"config_path,omitempty"`
+	LogsPath   string `config:"state_path" yaml:"logs_path,omitempty"`
+}
+
+func writeContainerPaths(original, statePath, configPath, logsPath string) error {
+	pathFile := filepath.Join(original, "container-paths.yml")
```
Comment (ruflin) [inline x-pack/elastic-agent/pkg/agent/cmd/container.go:696]: Do we need a new file for this or could we use an existing "state" file?

**Review by ruflin — APPROVED** [review]
LGTM. Did not run it locally but code change makes sense.

Would be nice to also add these kind of things to our e2e test suite or something that is closer to the PR.

File: x-pack/elastic-agent/pkg/agent/cmd/container.go (hunk 1 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/cmd/container.go:696]: It is only specific to running in container mode. Being that Elastic Agent ships with pre-built binaries and the state will normally be mounted from a volume we need to do a lot to ensure that the containers paths are correct.

The code will not know the path of `state.yml` because that is based on the `STATE_PATH` adjusting that location. So we use a unique file to just do this one thing, for the `status` and `inspect` commands. All other commands should either not be used in the container or are used as children of the `container` command itself.
