### PR TITLE
mkdir for extracted dashboard files

### LINKED ISSUE #8051: Cannot load beats dashboards in darwin
- Version:  6.4.0 BC6
- Operating System:  darwin_x_86_64

Please note this is fine on linux and windows

- Steps to Reproduce: 
1. Go to staging and download default distros for ES/Kibana and metricbeat ( I tried it with both metricbeat and packetbeat)
2. Try to install the dashboards using the command in staging
3. Dashboards installation fails with:
```
Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing URL/file: Failed to unzip the archive: /var/folders/74/7821tshd4l36nh47qw_q76r40000gp/T/tmp188011220/beats-dashboards-6.4.0.zip: open /var/folders/74/7821tshd4l36nh47qw_q76r40000gp/T/tmp188011220/beats-dashboards-6.4.0/.build_hash.txt: no such file or directory
```

### PR DESCRIPTION
**Pull request by andrewkroh**
Make the directory that contains the extracted file prior to creating the file. This makes it handle cases where there is not a directory entry inside the zip file.

I also made a fix to close the file handle for the .zip when done.

Fixes #8051

### CODE REVIEW

File: libbeat/dashboards/importer.go [hunk 1]
```diff
@@ -131,6 +131,7 @@ func (imp Importer) unzip(archive, target string) error {
 	if err != nil {
 		return err
 	}
+	defer reader.Close()
```
Comment (ph) [inline libbeat/dashboards/importer.go]: good catch
