### PR TITLE
[Elastic Agent] Handle case where policy doesn't contain Fleet connection information

### LINKED ISSUE #25586: Existing agents do not re-enroll in fleet correctly after 7.12-snapshot to 7.13-snapshot upgrade
**Steps to reproduce:**

1. A 7.12-snapshot deployment was spun in the qa.cld.elstc.co environment with zero apm instance.  
2. I went to Kibana and enabled fleet ( this is pre-fleet-server implementation) and enrolled an agent. 
3. I came back to cloud console and upgraded the deployment to 7.13-snapshot.
4. I went to fleet UI and was asked to set up fleet server. I did that from cloud console
5. Then I re-enrolled the agent. 
5. The agent remained online for few mins but then became offline. 
I saw the following in the agent logs:
_`Could not communicate with Checking API will retry, error: could not decode the response, raw response: Client sent an HTTP request to an HTTPS server`_

6. Agent continues to send data to ES 

**Note This problem isn't reproducible if you start with 7.13 deployment and enroll agents with fleet server.**

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Ensures that the client connection to Fleet Server is only updated if the policy has `fleet.*`.

## Why is it important?

Fixes #25586 because of kibana issue https://github.com/elastic/kibana/issues/100050

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #25586

### CODE REVIEW

**Review by ph — APPROVED** [review]

File: x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go [hunk 1]
```diff
@@ -100,6 +100,14 @@ func (h *PolicyChange) handleFleetServerHosts(ctx context.Context, c *config.Con
 	if len(h.setters) == 0 {
 		return nil
 	}
+	data, err := c.ToMapStr()
+	if err != nil {
+		return errors.New(err, "could not convert the configuration from the policy", errors.TypeConfig)
+	}
+	if _, ok := data["fleet"]; !ok {
+		// no fleet information in the configuration (skip checking client)
```
Comment (ruflin) [inline x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go:108]: Maybe worth a debug log?
