### PR TITLE
tlscommon: fix race condition on TLS hostname validation

### LINKED ISSUE #30240: Filebeat Loadbalance wrong cert validation
We have filebeat v7.17.0 with such output:
```
output.logstash:
  enabled: true
  hosts:
    - es-logs-node1.domain.com:5045
    - es-logs-node2.domain.com:5045
    - es-logs-node3.domain.com:5045
  ssl.certificate_authorities: []
  loadbalance: true
```
Each of those hosts has letsencrypt cert publicly valid only for its single name (No SAN).
In such configuration we see these errors in filebeat logs:
```
2022-02-05T02:01:13.479Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://es-logs-node1.domain.com:5045)): x509: certificate is valid for es-logs-node1.domain.com, not es-logs-node2.domain.com
```
Which is correct because each node only has cert for its name, not all other names in the cluster.
If we switch to `loadbalance: false` - such errors are gone. But we want continue to use `loadbalance`, and this error is very confusing.

Also, checked that there is no such issue on v7.16.3

### LINKED ISSUE #30290: [Heartbeat] Mixup of TLS certificates on multi-monitor configs
Per [this discuss thread](https://discuss.elastic.co/t/multiple-hosts-per-monitor-confuses-certificate-validation-since-7-17-0/296062/6) it appears there are some odd cases in which a monitor with multiple `url` values mixes up the TLS certs between them.

I've had trouble reproducing this, but according @belimawr , one theory is:

> it looks to be a very specific edge case that involves domains with a common suffix and using non-wildcard certificates.

I'm not 100% on that, since setting up the following monitor did not reproduce the issue. I suspect there's perhaps a race in our cert handling and it's more timing related than anything. Given that this seems to happen more on internal domains I wonder if it only affects endpoints that are super fast to respond vs. public websites. The following config works for me, for instance:

```yaml
heartbeat.monitors:
- type: http
  enabled: true
  id: my-monitor
  name: My Monitor
  urls: ["https://discuss.elastic.co", "https://www.elastic.co"]
  schedule: '@every 10s'
```

This apparently is new in 7.17.0, which is strange, because we haven't changed any of this code.

### PR DESCRIPTION
**Pull request by belimawr**
## What does this PR do?

This PR fixes a race condition on hostname/IP validation for TLS
certificates. We were relying on a field on TLSConfig, but this struct
is shared between different hosts. Now we pass the server name as a
parameter, thus avoiding any race condition.

The error seen in the logs looks like this:
```
Get "https://bitbucket.corp.internal/status": x509: certificate is valid for bitbucket.corp.internal, not jira.corp.internal
```
Where both hostnames are used together on a output (like ES, Logstash, etc), a monitor in Heartbeat, etc). See the testing section for a more detailed example.

## Why is it important?

It fixes a bug.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

~~## Author's Checklist~~

## How to test this PR locally
Because it's a race condition, it's tricky to test, however you can setup Heartbit with one monitor checking different hosts that do not share the same TLS certificate, the easiest way is to setup Nginx running on docker and edit your `/etc/hosts` (on Linux or the equivalent for your platform) so you can use hostnames to point to those containers. Here is a sample Heartbeat monitor config:
```yaml
- type: http
  id: now-it-works
  name: It will not break
  enabled: true
  urls:
    - https://bitbucket.corp.internal
    - https://jira.corp.internal
  check.response.status: [200]
  max_redirects: 3
  schedule: '@every 5s'
  ssl:
    certificate_authorities:
      - /home/the-doctor/tardis/rootCA.crt
```

With this fix you should see no TLS validation issues.

## Related issues

- Fixes #30290
- Fixes #30240
- [Discuss thread](https://discuss.elastic.co/t/multiple-hosts-per-monitor-confuses-certificate-validation-since-7-17-0/296062)

~~## Use cases~~
~~## Screenshots~~
~~## Logs~~

## Workaround
To workaround this issue on `7.17.0`, one can set `ssl.verification_mode: certificate` anywhere that accepts SSL configuration and is failing due to this bug.

### CODE REVIEW

**Review by kvch — APPROVED** [review]

File: libbeat/common/transport/tlscommon/tls_config.go [hunk 1]
```diff
@@ -161,7 +154,10 @@ func (c *TLSConfig) BuildServerConfig(host string) *tls.Config {
 	return config
 }
 
-func makeVerifyConnection(cfg *TLSConfig) func(tls.ConnectionState) error {
+// makeVerifyConnection returns a function to verify the TLS conneciton.
```
Comment (cmacknz) [inline libbeat/common/transport/tlscommon/tls_config.go:157]:
```suggestion
// makeVerifyConnection returns a function to verify the TLS connection.
```

**Review by cmacknz — APPROVED** [review]

**Comment by andrewvc** [comment]
Going by the failing tests looks like the behavior has changed for invalid certs, it looks like we're still connecting to the invalid cert despite it being insecure.

**Comment by belimawr** [comment]
> Going by the failing tests looks like the behavior has changed for invalid certs, it looks like we're still connecting to the invalid cert despite it being insecure.

Indeed. My tests worked pretty well (and now I'm wondering how they worked...), but I've been looking into this and my fix is not working for all conditions :/

**Comment by belimawr** [comment]
I reworked the PR from the ground up, there is no point keeping the old commits, hence I force-pushed a clean history to my branch. Let's wait for CI to be green and then re-reviews

**Comment by andrewvc** [comment]
As a note, if as part of this fix heartbeat still gets the TLS cert info and populates `tls.*` in documents with it that's actually an improvement, just so long as it still reports the same errors. We've had occasional feature requests to still populate `tls.*` fields even when the cert expires so that users can better debug things.

I suspect that may be extra effort, and of course we should just focus on fixing things, but I thought I'd mention that if that's somehow easier as you do this work.

**Comment by belimawr** [comment]
> heartbeat still gets the TLS cert info and populates `tls.*` in documents with it that's actually an improvement

I'm not quite sure what you mean here... But I'll probably won't touch any Heartbeat code as the issue is on Libbeat itself.

**Comment by belimawr** [comment]
@cmacknz  @kvch could you review it again? The only thing that have not changed since your last review is the changelog.

File: libbeat/common/transport/tlscommon/tls_config.go [hunk 2]
```diff
@@ -131,13 +131,20 @@ func (c *TLSConfig) BuildModuleClientConfig(host string) *tls.Config {
...
 	}
 
-	config := c.ToConfig()
-	// config.ServerName does not verify IP addresses
-	config.ServerName = host
+	// Make a copy of c, because we're gonna mutate it after
+	// calling ToConfig. ToConfig calls a function that creates
+	// a closure that needs to access cc. A shallow copy is enough
+	// because all slice/pointer fields won't be modified.
+	cc := *c
```
Comment (kvch) [inline libbeat/common/transport/tlscommon/tls_config.go:138]: Great comment.

Comment (cmacknz) [reply libbeat/common/transport/tlscommon/tls_config.go:138]: +1

**Review by cmacknz — APPROVED** [review]

**Comment by maggieghamry** [comment]
@belimawr do you know if this will be back-ported to `7.17.0`, or if it will only be in a future `7.17.1` release?
