### PR TITLE
x-pack/filebeat/processors/decode_cef/cef: allow (*Event).Unpack to attempt to recover extensions

### LINKED ISSUE #30757: [Filebeat] decode_cef - recover from errors in the CEF header
It would be nice if the CEF parser would recover from errors detected in the CEF header and try to resume parsing the CEF extensions. For example the header on this message is incomplete, but the remainder of the CEF extensions are good.

`Feb 11 19:12:22 ec2-54-211-162-22 2022-02-11 19:12:22,962   sentinel -  CEF:0|SentinelOne|Mgmt|activityID=1111111111111111111 activityType=3505 siteId=None siteName=None accountId=1222222222222222222 accountName=foo-bar mdr notificationScope=ACCOUNT`

The expected behavior is that there would be an `error.message` in the event because the message is not valid per the spec, but all of the `cef.extension` values would be present. This is what you get today.

```
  {
    "cef": {
      "device": {
        "product": "Mgmt",
        "vendor": "SentinelOne"
      },
      "version": "0"
    },
    "error": {
      "message": "unexpected end of CEF event"
    },
    "observer": {
      "product": "Mgmt",
      "vendor": "SentinelOne"
    }
  }
```

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This adds a second pass at parsing messages if the original parse operation fails
and there are no extensions found by relaxing the requirements on header syntax.
Because header values may include syntax that looks like the extension key/value
pair syntax, the parsers are separated and under control of the host language.

## Why is it important?

Fixes a bug.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #30757.

### CODE REVIEW

File: x-pack/filebeat/processors/decode_cef/cef/cef_test.go [hunk 1]
```diff
@@ -401,6 +403,26 @@ func TestEventUnpack(t *testing.T) {
 			"key2": UndocumentedField("a"),
 		}, e.Extensions)
 	})
+
+	t.Run("truncatedHeader", func(t *testing.T) {
+		var e Event
+		err := e.Unpack(truncatedHeader)
+		assert.Equal(t, errUnexpectedEndOfEvent, err)
```
Comment (andrewkroh) [inline x-pack/filebeat/processors/decode_cef/cef/cef_test.go:410]: Would it be possible to make this error more descriptive based on the machine state? Like have the error indicate that the header is incomplete.

**Review by andrewkroh — COMMENTED** [review]
I like the reorganization. Had one question.

File: x-pack/filebeat/processors/decode_cef/cef/cef_test.go (hunk 1 above)
Comment (efd6) [reply x-pack/filebeat/processors/decode_cef/cef/cef_test.go]: I have added a second error in the case that there is a failure on the first round and there are no extensions.

**Review by andrewkroh — APPROVED** [review]
LGTM. Before merging, can you please run the decode_cef/cef/fuzz on the changes for a few minutes if you haven't already.

**Comment by efd6** [comment]
This will need some addition logic there are a bunch of crashers.

**Comment by efd6** [comment]
@andrewkroh It's worth taking another look at the ragel since I've needed to make some reasonably large changes (by ragel standards) to the actions, but it's been fuzzing after the fixes for 30 minutes without a crasher.

File: x-pack/filebeat/processors/decode_cef/cef/cef_actions.rl [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+        // A new extension key marks the end of the last extension value.
+        if len(state.key) != 0 && state.valueStart < mark {
+            // We should not be here, but purge the escapes and handle them.
+            e.pushExtension(state.key, replaceEscapes(data[state.valueStart:mark-1], state.valueStart, state.escapes))
+            state.reset()
+        }
+        state.key = data[mark:p]
+    }
+    action extension_value_start {
+        if len(state.escapes) != 0 {
```
Comment (andrewkroh) [inline x-pack/filebeat/processors/decode_cef/cef/cef_actions.rl:61]: Why is this condition based on the number of escapes? Can't we have extensions without escapes?

Comment (efd6) [reply x-pack/filebeat/processors/decode_cef/cef/cef_actions.rl:61]: The issue here that if we have got to this point we have a syntax that is not expected and so have not consumed the escapes. So if there are some to consume, this makes sure we do.

Comment (andrewkroh) [reply x-pack/filebeat/processors/decode_cef/cef/cef_actions.rl:61]: My point is that there may be an "extension" that needs to be consumed which does not contain any escapes. That's why I am questioning the condition being based on len(escapes) rather than something like len(key) && something with the value start/end. Does that make sense?

Comment (efd6) [reply x-pack/filebeat/processors/decode_cef/cef/cef_actions.rl:61]: Those won't be affected by this. This is purely to cope with the cases where things have been set up and not used. I the first pass of the parse, this condition is never triggered because the header state machine prevents this from ever happening, but in the salvage pass, the guarantees don't hold, but also we can't guarantee sensible results, we are just trying to capture as much as possible.

Put another way, if the escape were well formed, it would have been handled by `extension_eof` which is those cases that you describe, guarded by `len(state.key) != 0 && state.valueStart < state.valueEnd`. So this just picks up cases that that failed to identify because they were syntactically broken and did not satisfy the machine before the next extension start.

Does that clarify?

Comment (andrewkroh) [reply x-pack/filebeat/processors/decode_cef/cef/cef_actions.rl:61]: Yes, that’s clear. Thanks. Can you add a short comment there.

**Review by andrewkroh — APPROVED** [review]

**Comment by efd6** [comment]
The coverage tool appears to be choking on this. It shouldn't.

**Comment by efd6** [comment]
The issue looks like golang/go#35781 and that we just did not hit it with the exact number of lines that we had. The options are to:
1. remove the comment and hope that changes in generation or cover behaviour don't resurface the issue.
2. turn off coverage for this package (it this possible per-package?)
3. inhibit line directives being emitted by ragel (not available for Go)
