### PR TITLE
filestream harvest inactive files

### LINKED ISSUE #34342: `harvester_limit` does not work as expected
- Version: `main`, `8.6.0`, probably affects older versions as well
- Operating System: Linux

When `harvester_limit` is set, the limit is respected, but only `harvester_limit` files are ingested, the others are not ingested unless data is appended to them.

The problem seems to be related to two facts:
1. The startHarvester error is ignored according to the TastGroup configuration.
     https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/filebeat/input/filestream/internal/input-logfile/harvester.go#L147
    
    https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/filebeat/input/filestream/internal/input-logfile/input.go#L74

2. The file watcher is unaware of the harvester status and only send the "createEvent" once
    https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/filebeat/input/filestream/fswatch.go#L138-L211

Another thing to notice is lack of any log informing about harvesters not beings started. There is a log entry stating the harvester is starting, but no followup on its success/error.
https://github.com/elastic/beats/blob/69ebd98fc41aa268acd7f99c429a44f2833c8dd3/filebeat/input/filestream/internal/input-logfile/harvester.go#L145

## Workaround
Currently there is no workaround for filestream input, however the [log input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html), even though deprecated, will work as expected when setting `harvester_limit`

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Transfer the responsability to limit the number of concurrent harvests from the `readerGroup.newContext` to the `defaultHarvesterGroup` task group.
The new taskgroup can receive a limit of allowed goroutines to run concurrently, if this limit is reached, any further task sent will wait until it can run. Thus a harverster that would fail to start due to `ErrHarvesterLimitReached` will now wait until it can start.

Filestream, by design, only attempts to harvester a file when a filesystem event happens. When a filestream input is started, it attempts to harvester every file it's configured to harvester. 
However if it fails to start the harvester, as it happens when `harvester_limit` is set to a value lower than the number of files to be harvested, and nothing else happens to the file (data written, file truncated and so on), filestream won't attempt to start the failed harvesters ever again.

## Why is it important?

Filestream should harvester all files it's configured to, regardless if the file changes or not. Right now when `harvester_limit` is set to a smaller value than the number of files to be harvested and any of these files don't change after the failure, filestream doesn't try to harvester the failed files ever again.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #34342

### CODE REVIEW

File: filebeat/input/filestream/internal/task/group.go [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+	"errors"
+	"fmt"
+	"strings"
+	"sync"
+
+	"golang.org/x/sync/semaphore"
+)
+
+type Group struct {
+	limit uint64
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:14]: Nit: I think you can get rid of this field as the functionality we need from it is duplicated by the `sem` field.  If `sem` == `nil`, it's the same as `limit` being `0`.  And otherwise, we will use `sem` anyway to stay within the limit.  I think it's better to have just a single way to achieve the same functionality in the code to make it less confusing and also potentially less error-prone.

File: filebeat/input/filestream/internal/task/group.go [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+
+	sem *semaphore.Weighted
+	wg  *sync.WaitGroup
+
+	errs     []error
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:19]: After reading the definition of the `(p *Group) addErr` method, I realized that this field is a circular buffer, of max size `errSize`, for holding errors.  Might be good to mention that in comment here.  Otherwise, naively, it gives the impression that this `[]error` can grow unbounded.

File: filebeat/input/filestream/internal/task/group.go [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+	errsSize uint64
+	errsNext uint64
+	errsMu   *sync.Mutex
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:22]: Looking at some more of the code that uses `errs` and it's related fields, I'm wondering if it might be a bit cleaner to create a more general-purpose ring buffer type and use it for `errs` here.  That type could provide an `Add(T)` method that could be called from `addErr` and an `IsEmpty() bool` method that could be called from `Stop()`.

File: filebeat/input/filestream/internal/task/group.go (hunk 2 above)
Comment (ycombinator) [reply filebeat/input/filestream/internal/task/group.go:19]: You can ignore this suggestion if you go with https://github.com/elastic/beats/pull/34906/files#r1173188613.

File: filebeat/input/filestream/internal/task/group.go [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+	p.errsMu.Lock()
+	defer p.errsMu.Unlock()
+
+	if p.errs[0] == nil {
+		return nil
+	}
+
+	// TODO: use errors.Join once we update to go1.20
+	buf := &strings.Builder{}
+	buf.WriteString("last errors:")
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:112]: Just clarifying: "last" here means "latest", right?

File: filebeat/input/filestream/internal/task/group.go [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+	p.wg.Wait()
+	p.errsMu.Lock()
+	defer p.errsMu.Unlock()
+
+	if p.errs[0] == nil {
+		return nil
+	}
+
+	// TODO: use errors.Join once we update to go1.20
+	buf := &strings.Builder{}
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:111]: Since we already know the size of `p.errs` here, do we need to use a `strings.Builder`?  Why not preallocate a string array of length `len(p.errs)+1`, populate it with the first item as `"last errors:"` and the remaining items as the error strings, then use `strings.Join` at the end?

File: filebeat/input/filestream/internal/task/group.go [hunk 6]
```diff
@@ -0,0 +1,129 @@
...
+	buf.WriteString("last errors:")
+	for i, err := range p.errs {
+		if err == nil {
+			break
+		}
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:116]: Do we need this nil check, since `addErr` already guards against adding a `nil` error to `p.errs`?  In fact, if we go with the new general-purpose ring buffer type for `p.errs` (see https://github.com/elastic/beats/pull/34906/files#r1173188613) it will provide the necessary abstraction to ensure that the only way new items are added to `p.errs` is through the new type's `Add()` method.  With a `nil` guard in that method, we can establish the invariant that `p.errs` will never contain `nil` items.

File: filebeat/input/filestream/internal/task/group.go [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+
+		if i == 0 {
+			// safe to ignore as strings.Builder.Write does not fail.
+			_, _ = fmt.Fprintf(buf, " %v", err)
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:120]: Nit: Any reason not to use `buf.WriteString` here (and below) as well?

File: filebeat/input/filestream/internal/input-logfile/harvester.go [hunk 8]
```diff
@@ -134,31 +124,53 @@ type defaultHarvesterGroup struct {
...
-	tg           unison.TaskGroup
+	tg           *task.Group
 }
 
-func (hg *defaultHarvesterGroup) Start(ctx input.Context, s Source) {
-	sourceName := hg.identifier.ID(s)
+// Start starts the Harvester for a Source if no Harvester is running for the
+// Source.
+// If the harvester limit has been reached, the harvester will wait until it can
+// be started. Start does not block.
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/input-logfile/harvester.go:133]: ❤️

File: filebeat/input/filestream/internal/input-logfile/harvester.go [hunk 9]
```diff
@@ -134,31 +124,53 @@ type defaultHarvesterGroup struct {
...
 }
 
-// Restart starts the Harvester for a Source if a Harvester is already running it waits for it
-// to shut down for a specified timeout. It does not block.
-func (hg *defaultHarvesterGroup) Restart(ctx input.Context, s Source) {
-	sourceName := hg.identifier.ID(s)
+// Restart starts the Harvester for a Source if a Harvester is already running
+// it waits for it to shut down for a specified timeout. It does not block.
+// If the harvester limit has been reached, the harvester will wait until it can
+// be started. Start does not block.
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/input-logfile/harvester.go:150]:
```suggestion
// be started. Restart does not block.
```

File: filebeat/input/filestream/internal/task/group.go [hunk 10]
```diff
@@ -0,0 +1,129 @@
...
+	errsSize uint64
+	errsNext uint64
+	errsMu   *sync.Mutex
+
+	ctx       context.Context
+	cancelCtx context.CancelFunc
+}
+
+type Goer interface {
+	Go(fn func(context.Context) error) error
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:29]: Please add godoc for this method.  I know it exists on the implementation below but I think some of the semantics (e.g. should not block) would be good to be documented as part of the interface.

File: filebeat/input/filestream/internal/task/group.go [hunk 11]
```diff
@@ -0,0 +1,129 @@
...
+	if err := p.ctx.Err(); err != nil {
+		return fmt.Errorf("task group is closed: %w", err)
+	}
+
+	p.wg.Add(1)
+	go func() {
+		defer p.wg.Done()
+
+		if p.limit != 0 {
+			defer p.sem.Release(1)
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:69]: Should this statement be after the error check for `p.sem.Acquire`?  In other words, if `p.sem.Acquire` returns an error, I don't think the internal weight in `p.sem` is incremented so decrementing it with `p.sem.Release` may not be a good idea?

File: filebeat/input/filestream/internal/input-logfile/input.go [hunk 12]
```diff
@@ -64,15 +64,13 @@ func (inp *managedInput) Run(
...
+		readers:      newReaderGroup(),
 		cleanTimeout: inp.cleanTimeout,
 		harvester:    inp.harvester,
 		store:        groupStore,
 		ackCH:        inp.ackCH,
 		identifier:   inp.sourceIdentifier,
-		tg: unison.TaskGroup{
-			OnQuit: unison.ContinueOnErrors, // harvester should keep running if a single harvester errored
-		},
+		tg:           task.NewGroup(inp.harvesterLimit, 2*inp.harvesterLimit),
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/input-logfile/input.go:73]: Just wondering: is there some logic to choosing `maxErrors`, the 2nd argument to `task.NewGroup`, as `2 x inp.harvesterLimit`?

File: filebeat/input/filestream/internal/task/group.go [hunk 13]
```diff
@@ -0,0 +1,141 @@
...
+
+	var logErr = func(error) {}
+	if log != nil {
+		logErr = func(err error) {
+			var format string
+			if errPrefix == "" {
+				format = "%v"
+			} else {
+				format = errPrefix + ": %v"
+			}
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:65]: Nit: You can define this logic one scope-level higher, so `format` becomes part of the `logErr` function's closure.  That way the logic is not re-evaluated every time `logErr` is called.

File: filebeat/input/filestream/internal/task/group.go [hunk 14]
```diff
@@ -0,0 +1,141 @@
...
+			log.Errorf(format, err)
+		}
+	}
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:68]: Consider extracting the initialization of `logErr` into it's own helper function.  That way you can more easily unit test it, which is probably a good idea since there are four paths through it.

File: filebeat/input/filestream/internal/task/group.go (hunk 2 above)
Comment (ycombinator) [reply filebeat/input/filestream/internal/task/group.go]: Based on our conversation off-PR, you told me you're getting rid of the idea of the ring buffer for errors altogether.  So this thread is now irrelevant.

File: filebeat/input/filestream/internal/task/group.go (hunk 3 above)
Comment (ycombinator) [reply filebeat/input/filestream/internal/task/group.go]: Based on our conversation off-PR, you told me you're getting rid of the idea of the ring buffer for errors altogether.  So this thread is now irrelevant.

File: filebeat/input/filestream/internal/task/group.go (hunk 5 above)
Comment (ycombinator) [reply filebeat/input/filestream/internal/task/group.go]: Based on our conversation off-PR, you told me you're getting rid of the idea of the ring buffer for errors altogether.  So this thread is now irrelevant.

File: filebeat/input/filestream/internal/task/group.go (hunk 6 above)
Comment (ycombinator) [reply filebeat/input/filestream/internal/task/group.go]: Based on our conversation off-PR, you told me you're getting rid of the idea of the ring buffer for errors altogether.  So this thread is now irrelevant.

File: filebeat/input/filestream/internal/task/group.go (hunk 7 above)
Comment (ycombinator) [reply filebeat/input/filestream/internal/task/group.go]: Based on our conversation off-PR, you told me you're getting rid of the idea of the ring buffer for errors altogether.  So this thread is now irrelevant.

File: filebeat/input/filestream/internal/task/group.go [hunk 15]
```diff
@@ -0,0 +1,141 @@
...
+		return fmt.Errorf("task group is closed: %w", err)
+	}
+
+	g.wg.Add(1)
+	go func() {
+		defer g.wg.Done()
+
+		if g.sem != nil {
+			err := g.sem.Acquire(g.ctx, 1)
+			defer g.sem.Release(1)
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/task/group.go:101]: I think this needs to be moved to be right after the `if` block below.  In case `err != nil`, `g.sem.Acquire` will not increment the internal weight in `g.sem` so decrementing it with `p.sem.Release` may not be a good idea when we return from inside the `if` block, right?

File: filebeat/input/filestream/internal/task/group.go (hunk 10 above)
Comment (ycombinator) [reply filebeat/input/filestream/internal/task/group.go]: I see you removed the `Goer` interface altogether.  So this thread is no longer relevant.

File: filebeat/input/filestream/internal/input-logfile/input.go (hunk 12 above)
Comment (ycombinator) [reply filebeat/input/filestream/internal/input-logfile/input.go]: Based on our conversation off-PR, you told me you're getting rid of the idea of the ring buffer for errors altogether. So this thread is now irrelevant.

File: filebeat/input/filestream/internal/input-logfile/harvester_test.go [hunk 16]
```diff
@@ -356,10 +441,23 @@ func blockUntilCancelOnRun(c input.Context, _ Source, _ Cursor, _ Publisher) err
 	return nil
 }
 
+var errHarvester = fmt.Errorf("harvester error")
```
Comment (ycombinator) [inline filebeat/input/filestream/internal/input-logfile/harvester_test.go:444]: Nit
```suggestion
var errHarvester = errors.New("harvester error")
```

**Review by ycombinator — APPROVED** [review]
LGTM.  Nice `TestFilestreamHarvestAllFilesWhenHarvesterLimitExceeded` test too 👍.
