### PR TITLE
fix flaky integration tests

### LINKED ISSUE #36177: Build 1754 for main with status FAILURE - Build&Test / libbeat-goIntegTest / TestTemplateDisabled
## :broken_heart: Tests Failed

> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[Pipeline View](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2Fmain/detail/main/1754//pipeline) [Test View](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2Fmain/detail/main/1754//tests) [Changes](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2Fmain/detail/main/1754//changes) [Artifacts](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2Fmain/detail/main/1754//artifacts) [preview](http://beats_null.docs-preview.app.elstc.co/diff)  [preview](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-07-30T13:47:52.405Z&rangeTo=2023-07-30T14:07:52.405Z&transactionName=BUILD+Beats%2Fbeats%2Fmain&transactionType=job&latencyAggregationType=avg&traceId=835ffdaed1785a063503a591e2d4245a&transactionId=53cddbcb0f3c952c)

<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Start Time: 2023-07-30T13:57:52.405+0000

* Duration: 75 min 24 sec

#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 27592  |
| Skipped      | 2008 |
| Total        | 29601   |

</p>
</details>

  ### Test errors [](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2Fmain/detail/main/1754//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Build&Test / libbeat-goIntegTest / TestTemplateDisabled – github.com/elastic/beats/v7/libbeat/tests/integration`

<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestTemplateDisabled
    template_test.go:296: 
        	Error Trace:	/var/lib/jenkins/workspace/main-1754-c7e2a3ab-fdf4-42c7-944a-9225a9ea572c/src/github.com/elastic/beats/libbeat/tests/integration/framework.go:268
        	            				/var/lib/jenkins/workspace/main-1754-c7e2a3ab-fdf4-42c7-944a-9225a9ea572c/src/github.com/elastic/beats/libbeat/tests/integration/template_test.go:296
        	Error:      	Condition never satisfied
        	Test:       	TestTemplateDisabled
    framework.go:352: Temporary directory saved: /var/lib/jenkins/workspace/main-1754-c7e2a3ab-fdf4-42c7-944a-9225a9ea572c/src/github.com/elastic/beats/libbeat/build/integration-tests/TestTemplateDisabled-1690728364
--- FAIL: TestTemplateDisabled (20.32s)
 
 ```
</p></details>
</ul>
    
</p></details>

### Steps errors [](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2Fmain/detail/main/1754//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
##### `libbeat-goIntegTest - mage goIntegTest`
<ul>
<li>Took 8 min 37 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/main/runs/1754/steps/13190/log/?start=0">here</a></li>
<li>Description: <code>mage goIntegTest</code></l1>
</ul>
  
  
  
  
##### `libbeat-goIntegTest - mage goIntegTest`
<ul>
<li>Took 4 min 14 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/main/runs/1754/steps/18563/log/?start=0">here</a></li>
<li>Description: <code>mage goIntegTest</code></l1>
</ul>
  
  
  
  
##### `libbeat-goIntegTest - mage goIntegTest`
<ul>
<li>Took 4 min 54 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/main/runs/1754/steps/20101/log/?start=0">here</a></li>
<li>Description: <code>mage goIntegTest</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/main/runs/1754/steps/21186/log/?start=0">here</a></li>
<li>Description: <code>Error "hudson.AbortException: script returned exit code 1"</code></l1>
</ul>
  
  </p>
  </details>

### PR DESCRIPTION
**Pull request by leehinman**
## What does this PR do?

fixes flaky TestTemplateDefault and TestTemplateDisabled integration tests

- tests assumed 1 event published, could be multiple
- added LogMatch function to framework to allow use of regexp
- added some more debug info when tests fail, useful in CI where we don't always get the directory contents

## Why is it important?

croissants should be flaky, not tests

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
- [x] I have made my commit title and message explanatory about the purpose and the reason of the change

## How to test this PR locally

```
cd libbeat
mage goIntegTest
```

## Related issues

- Closes #36177

## Example output during failure

```
=== Failed
=== FAIL: libbeat/tests/integration TestTemplateDefault (22.19s)
    template_test.go:226:
        	Error Trace:	/Users/hinman/src/beats/libbeat/tests/integration/template_test.go:226
        	Error:      	Condition never satisfied
        	Test:       	TestTemplateDefault
        	Messages:   	looking for PublishEvents
    framework.go:131: Last 0 bytes of stderr:
    framework.go:137: Last 0 bytes of stdout:
    framework.go:146: Last 2325 bytes of /Users/hinman/src/beats/libbeat/build/integration-tests/TestTemplateDefault-1691078913/mockbeat-20230803.ndjson:
        "log.level":"debug","@timestamp":"2023-08-03T11:08:54.489-0500","log.logger":"elasticsearch","log.origin":{"file.name":"elasticsearch/client.go","file.line":264},"message":"PublishEvents: 2 events have been published to elasticsearch in 16.095375ms.","service.name":"mockbeat","ecs.version":"1.6.0"}
        {"log.level":"debug","@timestamp":"2023-08-03T11:08:54.489-0500","log.logger":"publisher","log.origin":{"file.name":"memqueue/ackloop.go","file.line":81},"message":"ackloop: return ack to broker loop:2","service.name":"mockbeat","ecs.version":"1.6.0"}
        {"log.level":"debug","@timestamp":"2023-08-03T11:08:54.489-0500","log.logger":"publisher","log.origin":{"file.name":"memqueue/ackloop.go","file.line":83},"message":"ackloop:  done send ack","service.name":"mockbeat","ecs.version":"1.6.0"}
        {"log.level":"debug","@timestamp":"2023-08-03T11:08:55.473-0500","log.logger":"processors","log.origin":{"file.name":"processing/processors.go","file.line":213},"message":"Publish event: {\n  \"@timestamp\": \"2023-08-03T16:08:55.472Z\",\n  \"@metadata\": {\n    \"beat\": \"mockbeat\",\n    \"type\": \"_doc\",\n    \"version\": \"9.9.9\"\n  },\n  \"message\": \"Mockbeat is alive!\",\n  \"ecs\": {\n    \"version\": \"8.0.0\"\n  },\n  \"host\": {\n    \"name\": \"elastic2\"\n  },\n  \"agent\": {\n    \"id\": \"0502d227-5202-4b68-940b-d64fbdb04dcb\",\n    \"name\": \"elastic2\",\n    \"type\": \"mockbeat\",\n    \"version\": \"9.9.9\",\n    \"ephemeral_id\": \"5a5a37e4-a9f6-459c-94e8-c5acbcaf668e\"\n  },\n  \"type\": \"mock\"\n}","service.name":"mockbeat","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2023-08-03T11:08:55.562-0500","log.logger":"service","log.origin":{"file.name":"service/service.go","file.line":52},"message":"Received signal \"interrupt\", stopping","service.name":"mockbeat","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2023-08-03T11:08:55.563-0500","log.logger":"mock","log.origin":{"file.name":"mock/mockbeat.go","file.line":82},"message":"Mockbeat Stop","service.name":"mockbeat","ecs.version":"1.6.0"}
        {"log.level":"debug","@timestamp":"2023-08-03T11:08:55.563-0500","log.origin":{"file.name":"numcpu/numcpu.go","file.line":41},"message":"Accurate CPU counts not available on platform, falling back to runtime.NumCPU for metrics","service.name":"mockbeat","ecs.version":"1.6.0"}
    framework.go:421: Temporary directory saved: /Users/hinman/src/beats/libbeat/build/integration-tests/TestTemplateDefault-1691078913
```

### CODE REVIEW

File: libbeat/tests/integration/framework.go [hunk 1]
```diff
@@ -118,6 +119,37 @@ func NewBeat(t *testing.T, beatName, binary string, args ...string) *BeatProc {
...
+			contents, err := os.ReadFile(f)
+			if err != nil {
+				t.Logf("error reading %s: %s", f, err)
+			}
+			maxlen := 2048
+			if len(contents) >= maxlen {
+				t.Logf("Last %d bytes of %s:\n%s", maxlen, f, string(contents[len(contents)-maxlen:]))
+			} else {
+				t.Logf("%s\n%s", string(contents), f)
+			}
```
Comment (rdner) [inline libbeat/tests/integration/framework.go:150]: I'd rather stat the file, seek to `size-maxlen` and read to EOF. In case the files were very large it would impact the test time significantly.

File: libbeat/tests/integration/framework.go [hunk 2]
```diff
@@ -219,6 +251,47 @@ func (b *BeatProc) Stop() {
 	}
 }
 
+// LogMatch tests each line of the logfile to see if contains any
+// match of the provided regular expression.  It will open the log
+// file on every call, read until EOF, then close it.  LogContains
+// will be faster so use that if possible.
+func (b *BeatProc) LogMatch(match string) bool {
+	re := regexp.MustCompile(match)
```
[the remark this answers is not in the document]
Comment (leehinman) [reply libbeat/tests/integration/framework.go:255]: I don't think so, because from the go docs:

```
Helper may be called simultaneously from multiple goroutines
```

And we are seeking in a file and updating offsets, I don't think we want that to happen simultaneously.

File: libbeat/tests/integration/framework.go (hunk 1 above)
Comment (leehinman) [reply libbeat/tests/integration/framework.go]: updated
