### PR TITLE
Fix convert processor conversion of string with leading zeros to integer

### LINKED ISSUE #15513: Filebeat Cisco module parsing sequence numbers with leading 0s as octal
Originally reported in https://discuss.elastic.co/t/cisco-module-arbitrary-parse-error-with-nearly-identical-messages/214884.

When the Filebeat (X-Pack) `cisco/ios` fileset is enabled and it encounters the following log line:

```
Jan 13 18:12:31 RO-ROM-VPN-KYOSA 022084: Jan 13 18:12:35.141 LCY: %SEC-6-IPACCESSLOGP: list 101 denied tcp 120.131.176.111(7133) -> 170.257.123.53(7547), 1 packet  
```

It fails with the following error:

```
GoError: failed in processor.convert: conversion of field [event.sequence] to type [long] failed: unable to convert value [022084]: strconv.ParseInt: parsing "022084": invalid syntax
```

However, parsing succeeds with a very similar line:

```
Jan 13 17:12:30 RO-ROM-VPN-KYOSA 021176: Jan 13 17:12:33.168 LCY: %SEC-6-IPACCESSLOGP: list 101 denied tcp 191.128.99.50(43651) -> 170.257.123.53(9943), 1 packet
```

---

Looking at the Cisco module source code, I believe this is where the failure is coming from:

https://github.com/elastic/beats/blob/43eb364aa32bbd9d8b44685432d4be26eb3a0a62/x-pack/filebeat/module/cisco/ios/config/pipeline.js#L98-L103

Specifically, that bit of code tries to parse the sequence number string as an integer. It sees the leading `0` and tries to parse the string that follows as an octal (base 8) number. Since base 8 numbers can only have digits 0-7 in them, parsing of `022084` fails but parsing of `021176` succeeds.

I think the *intent* here is to parse the sequence number as a decimal (base 10) number.

### PR DESCRIPTION
**Pull request by adriansr**
The conversion failed when for strings with leading zeros and a decimal digit 8 or 9, as the underlying runtime function would try to parse that as an octal number.

This is fixed by only allowing decimal and hex, which in turns makes the processor more aligned to its Elasticsearch counterpart.

Fixes #15513

### CODE REVIEW

File: libbeat/processors/convert/convert.go [hunk 1]
```diff
@@ -403,3 +403,13 @@ func cloneValue(value interface{}) interface{} {
 		return value
 	}
 }
+
+// Helper to interpret a string as either base-10 or base-16.
```
Comment (andrewkroh) [inline libbeat/processors/convert/convert.go]: nit: can you use the `strToInt blah blah` godoc format here.

File: libbeat/processors/convert/convert.go [hunk 2]
```diff
@@ -403,3 +403,13 @@ func cloneValue(value interface{}) interface{} {
...
+func strToInt(v string, bitSize int) (int64, error) {
+	base := 10
+	if strings.IndexAny(v, "xX") != -1 {
```
Comment (leehinman) [inline libbeat/processors/convert/convert.go]: I'm wondering if we should check to see if prefix is "0x"||"0X"? It seems odd that we would assume 0x if we found an x anywhere in the string

File: CHANGELOG.next.asciidoc [hunk 3]
```diff
@@ -151,6 +151,7 @@ https://github.com/elastic/beats/compare/v7.0.0-alpha2...master[Check the HEAD d
 - Fix bug with potential concurrent reads and writes from event.Meta map by Kafka output. {issue}14542[14542] {pull}14568[14568]
 - Fix spooling to disk blocking infinitely if the lock file can not be acquired. {pull}15338[15338]
 - Fix `metricbeat test output` with an ipv6 ES host in the output.hosts. {pull}15368[15368]
+- Fix `convert` processor conversion of string to integer with leading zeros. {issue}15513[15513]
```
Comment (leehinman) [inline CHANGELOG.next.asciidoc]: add pull too?

File: libbeat/processors/convert/convert.go (hunk 2 above)
Comment (adriansr) [reply libbeat/processors/convert/convert.go]: Checking for a 0x prefix will require to also account for an optional -+ sign first, so we will end up duplicating most of the parsing that strconv.ParseInt does.

By just checking for an x and passing it to ParseInt, we are already sure that it's either an hex number or an not a number at all, so ParseInt will take care of that for us.

Comment (andrewkroh) [reply libbeat/processors/convert/convert.go]: I think a more strict check would be clearer.

Comment (andrewkroh) [reply libbeat/processors/convert/convert.go]: @asr That makes sense then. How about just clearing up that comment below to also include `0X` (I was reading that in a very strict sense).

File: libbeat/processors/convert/convert.go [hunk 4]
```diff
@@ -403,3 +403,13 @@ func cloneValue(value interface{}) interface{} {
...
+		// strconv.ParseInt only accepts the '0x' prefix when base is 0.
```
Comment (andrewkroh) [inline libbeat/processors/convert/convert.go]:
```suggestion
		// strconv.ParseInt will accept the '0x' or '0X` prefix only when base is 0.
```

File: libbeat/processors/convert/convert.go (hunk 2 above)
Comment (asr) [reply libbeat/processors/convert/convert.go]: I guess you meant @adriansr.

Comment (andrewkroh) [reply libbeat/processors/convert/convert.go]: @asr I'm sorry. And sorry for all the times I'll probably accidentally do that in the future. 🤦‍♂ `slack handle != github handle`

Comment (adriansr) [reply libbeat/processors/convert/convert.go]: in retrospect it was silly to use strings.IndexAny on the whole string for something so simple, which has a lot of overhead. I've ended up checking for the prefix as you said 😅

File: CHANGELOG.next.asciidoc (hunk 3 above)
Comment (adriansr) [reply CHANGELOG.next.asciidoc]: done

File: libbeat/processors/convert/convert.go (hunk 1 above)
Comment (adriansr) [reply libbeat/processors/convert/convert.go]: done

File: libbeat/processors/convert/convert.go (hunk 4 above)
Comment (adriansr) [reply libbeat/processors/convert/convert.go]: done
