### PR TITLE
Make system process metricset honor cpu_ticks config option

### LINKED ISSUE #3590: Impossible to get "system.process.cpu.total.ticks" field
It seems like there is no way to activate the "system.process.cpu.total.ticks" field with Metricbeat. Tested with version 5.1.2 and 5.2.0, the "cpu_ticks" option doesn't work. It only adds ticks information in "cpu" and "core" modules events.
Either the option should also activate the fields for "process" module, either we need an additional option. 

- Version:  5.1.2 and 5.2.0 
- Operating System: Linux
- Steps to Reproduce: Start Metricbeat with "process" module activated and "cpu_ticks: true" option. Check in Elasticsearch/Kibana the content for "process" events. The "system.process.cpu.total.ticks" field is not present.

### PR DESCRIPTION
**Pull request by andrewkroh**
When `cpu_ticks` is true in the config file, the system process metricset will report the number of “ticks” (actually jiffies on linux) used in user space (`system.process.cpu.user`), system (`system.process.cpu.system`), and total (`system.process.cpu.total.ticks`).

Fixes #3590

### CODE REVIEW

File: metricbeat/module/system/process/helper.go [hunk 1]
```diff
@@ -245,23 +245,17 @@ func (procStats *ProcStats) GetProcessEvent(process *Process, last *Process) com
...
-			"start_time": unixTimeMsToTime(process.Cpu.StartTime),
-		}
-	} else {
-		proc["cpu"] = common.MapStr{
-			"total": common.MapStr{
-				"pct": GetProcCpuPercentage(last, process),
-			},
-			"start_time": unixTimeMsToTime(process.Cpu.StartTime),
-		}
+		proc.Put("cpu.user", process.Cpu.User)
```
Comment (ruflin) [inline metricbeat/module/system/process/helper.go]: nice, that also cleans up the code. It bugs me that we only use `.ticks` for the total but that would be a BC break.

**Comment by ruflin** [comment]
@andrewkroh I added `needs backport` label as I think we should backport it to at least 5.3.

File: metricbeat/module/system/process/helper.go (hunk 1 above)
Comment (andrewkroh) [inline metricbeat/module/system/process/helper.go]: I felt the same way, but didn't want to break BC.

Comment (ruflin) [inline metricbeat/module/system/process/helper.go]: Lets keep it in mind to "potentially" break for 6.0 ;-)
