### PR TITLE
[winlog/winlogbeat] Gracefully handle event channel not found errors

### LINKED ISSUE #30201: [Winlogbeat] Microsoft-Windows-Windows Defender/Operational - The specified channel could not be found.
From what I have observed, it seems that Winlogbeat is having intermittent issues trying to read the "Microsoft-Windows-Windows Defender/Operational" channel. I don't think this is a fault of Winlogbeat but a bug in Windows. However, there may be opportunity for Winlogbeat to gracefully recover and ingest events more robustly.

The first screenshot is when things are working normally and Winlogbeat can read events.

image

The second screenshot is when a new event is created and the events change to having the errors and this is when Winlogbeat can't read them.

image

The only log I see from Winlogbeat without turning on debugging I see this:
2022-02-03T09:10:20.255-0600	WARN	eventlog/wineventlog.go:316	WinEventLog[Microsoft-Windows-Windows Defender/Operational] EventHandles returned error The specified channel could not be found.
2022-02-03T09:10:20.259-0600	WARN	[winlogbeat]	beater/eventlogger.go:167	Read() error.	{"id": "Microsoft-Windows-Windows Defender/Operational", "error": "The specified channel could not be found."}
What is strange is that when I close event viewer and reopen it the error message goes away. However, Winlogbeat won't be able to read from this channel until I stop and restart the service. So whatever is causing the channel to produce that error it is as if Winlogbeat doesn't try and hook into reading the events again. I am not sure if this is something that can be resolved with Winlogbeat or not. Is it possible Winlogbeat can have better error handling with Event Channels when they have these types of issues?
The errors in the Event Viewer on all events are:
The description for Event ID 5007 from source Microsoft-Windows-Windows Defender cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded

For confirmed bugs, please report:
- Version: 7.16.2 - The entire stack, including Winlogbeat
- Operating System: Windows 10 20H2 19042.1466
- Discuss Forum URL: https://elasticstack.slack.com/archives/CNEDGGJQ3/p1643902942786959
- Steps to Reproduce: 

 1. Open event viewer and navigate to Microsoft-Windows-Windows Defender/Operational
 2. See that the logs are working just fine.
 3. Generate and event in Defender such as enabling Period Scanning 
 4. Give it 30 seconds or so and the errors will popup on every log. 
 5. Close event viewer and reopen 
 6. Back to step 1 where the logs look normal and you don't have the publisher error. The side affect here is that Winlogbeat will no longer read from that channel because it has this error and doesn't recover and try to read from the channel again until we restart the Winlogbeat service or the computer. I believe something deeper in the Windows OS is causing this problem since we don't see this on other event channels.
 
 Raw Windows Event Log Text:
 ```
 The description for Event ID 5007 from source Microsoft-Windows-Windows Defender cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer. If the event originated on another computer, the display information had to be saved with the event. The following information was included with the event: 

Microsoft Defender Antivirus 
4.18.2201.8 
HKLM\SOFTWARE\Microsoft\Windows Defender\MpEngine\MpCampRing = 0x4 

The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded
 ```

### PR DESCRIPTION
**Pull request by taylor-swanson**
## What does this PR do?

- Added logic to gracefully handle event channel not found errors. This will only apply to event subscriptions and not reading event files (evtx). If a channel not found error is encountered, either during intial open or during reading, the application will attempt to open a subscription to the event after a short delay.
- Added Channel and IsFile methods to the EventLog interface.
- Added IsChannelNotFound function
- Improved logging through further use of structured logging fields.

## Why is it important?

Filebeat/Winlogbeat must be able to resubscribe to a channel if something occurs to the handle. In some cases, the handle may go invalid for some unknown reason, but in these cases, simply closing the handle and resubscribing corrects the issue.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

This is a mildly difficult one to test, although one of the easier ways is to:

1. Ensure Sysmon is not installed on the system
2. Add `Microsoft-Windows-Sysmon/Operational` as an event log source
3. Start filebeat/winlogbeat, observe "channel not found" errors
4. Install Sysmon. Within a few seconds, filebeat/winlogbeat should be able to subscribe to the channel

What I wasn't able to test is if a valid channel that filebeat/winlogbeat was subscribed to went away, saw the error, reinstalled Sysmon, and watch it re-subscribe (this was the issue in both related cases). 

## Related issues

- Closes #30201 
- Relates elastic/sdh-beats#3039

## Use cases

Needed in cases where the requested channel isn't available yet, or if the channel randomly disappears (which has been reported by customers).

## Logs

filebeat:
```json
{"log.level":"error","@timestamp":"2023-02-21T07:47:38.551-0800","log.logger":"input.winlog","log.origin":{"file.name":"winlog/input.go","file.line":113},"message":"Encountered channel not found error when opening Windows Event Log","service.name":"filebeat","id":"winlog-test","input_source":"winlog-test","eventlog":"winlog-test","channel":"Microsoft-Windows-Sysmon/Operational","error":{"message":"The specified channel could not be found."},"ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-21T07:47:43.857-0800","log.logger":"eventlog","log.origin":{"file.name":"eventlog/wineventlog.go","file.line":375},"message":"WinEventLog[winlog-test] using subscription query=<QueryList>\n  <Query Id=\"0\">\n    <Select Path=\"Microsoft-Windows-Sysmon/Operational\">*</Select>\n  </Query>\n</QueryList>","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-21T07:47:43.857-0800","log.logger":"input.winlog","log.origin":{"file.name":"winlog/input.go","file.line":119},"message":"Windows Event Log opened successfully","service.name":"filebeat","id":"winlog-test","input_source":"winlog-test","eventlog":"winlog-test","channel":"Microsoft-Windows-Sysmon/Operational","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-21T07:47:43.857-0800","log.logger":"eventlog_detail","log.origin":{"file.name":"eventlog/wineventlog.go","file.line":417},"message":"WinEventLog[winlog-test] EventHandles returned 65 handles","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-21T07:47:43.857-0800","log.logger":"eventlog","log.origin":{"file.name":"eventlog/cache.go","file.line":86},"message":"messageFilesCache[winlog-test] size=1","service.name":"filebeat","ecs.version":"1.6.0"}
```

winlogbeat:
```json
{"log.level":"warn","@timestamp":"2023-02-21T08:16:11.411-0800","log.logger":"winlogbeat","log.origin":{"file.name":"beater/eventlogger.go","file.line":143},"message":"Open() encountered channel not found error. Trying again...","service.name":"winlogbeat","id":"Microsoft-Windows-Sysmon/Operational","error":{"message":"The specified channel could not be found."},"channel":"Microsoft-Windows-Sysmon/Operational","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-21T08:16:16.419-0800","log.logger":"eventlog","log.origin":{"file.name":"eventlog/wineventlog.go","file.line":387},"message":"WinEventLog[Microsoft-Windows-Sysmon/Operational] using subscription query=<QueryList>\n  <Query Id=\"0\">\n    <Select Path=\"Microsoft-Windows-Sysmon/Operational\">*</Select>\n  </Query>\n</QueryList>","service.name":"winlogbeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-21T08:16:16.419-0800","log.logger":"winlogbeat","log.origin":{"file.name":"beater/eventlogger.go","file.line":150},"message":"Opened successfully.","service.name":"winlogbeat","id":"Microsoft-Windows-Sysmon/Operational","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-21T08:16:16.423-0800","log.logger":"eventlog_detail","log.origin":{"file.name":"eventlog/wineventlog.go","file.line":429},"message":"WinEventLog[Microsoft-Windows-Sysmon/Operational] EventHandles returned 100 handles","service.name":"winlogbeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-21T08:16:16.423-0800","log.logger":"eventlog","log.origin":{"file.name":"eventlog/cache.go","file.line":86},"message":"messageFilesCache[Microsoft-Windows-Sysmon/Operational] size=1","service.name":"winlogbeat","ecs.version":"1.6.0"}
```

### CODE REVIEW

**Comment by taylor-swanson** [comment]
I was never able to test the scenario where we had a valid channel and then it disappeared briefly before coming back. I'm pretty confident, though, that we can handle that situation based on the error handling added in this PR along with what's already there.

In cases where I did try that scenario, either removing the channel hung due to winlogbeat holding a "lock" on the channel, or winlogbeat still saw the channel even though it was gone (took a reboot to clear it up in that case).

File: filebeat/input/winlog/input.go [hunk 1]
```diff
@@ -104,43 +105,55 @@ runLoop:
 
 		evtCheckpoint := initCheckpoint(log, cursor)
 		openErr := api.Open(evtCheckpoint)
+
 		if eventlog.IsRecoverable(openErr) {
```
Comment (efd6) [inline filebeat/input/winlog/input.go:109]: Could use `switch`.

File: winlogbeat/beater/eventlogger.go [hunk 2]
```diff
@@ -133,12 +134,17 @@ func (e *eventLogger) run(
 runLoop:
 	for stop := false; !stop; {
 		err = api.Open(state)
+
 		if eventlog.IsRecoverable(err) {
```
Comment (efd6) [inline winlogbeat/beater/eventlogger.go:138]: Could use `switch`.

File: winlogbeat/eventlog/wineventlog.go [hunk 3]
```diff
@@ -600,3 +628,112 @@ func (c *winMetaCache) winMeta(provider string) *winevent.WinMeta {
 	c.cache[provider] = winMetaCacheEntry{expire: time.Now().Add(c.ttl), WinMeta: &s.WinMeta}
 	return &s.WinMeta
 }
+
+// incrementMetric increments a value in the specified expvar.Map. The key
```
Comment (efd6) [inline winlogbeat/eventlog/wineventlog.go:632]: Curious why this is moved?

**Review by efd6 — APPROVED** [review]
Looks good. Minor queries before merge.

File: winlogbeat/eventlog/wineventlog.go (hunk 3 above)
Comment (taylor-swanson) [reply winlogbeat/eventlog/wineventlog.go:632]: The linux linter failed because these items were "unused" in that arch, so I had to move them to a windows build-only file.

Comment (efd6) [reply winlogbeat/eventlog/wineventlog.go:632]: OK. Thanks.

File: CHANGELOG.next.asciidoc [hunk 4]
```diff
@@ -92,6 +92,7 @@ https://github.com/elastic/beats/compare/v8.2.0\...main[Check the HEAD diff]
 - Fixing system tests not returning expected content encoding for azure blob storage input. {pull}34412[34412]
 - [Azure Logs] Fix authentication_processing_details parsing in sign-in logs. {issue}34330[34330] {pull}34478[34478]
 - Prevent Elasticsearch from spewing log warnings about redundant wildcard when setting up ingest pipelines. {issue}34249[34249] {pull}34550[34550]
+- Gracefully handle channel not found errors. {issue}30201[30201] {pull}34605[34605]
```
Comment (efd6) [inline CHANGELOG.next.asciidoc:95]: I'd note that this refers to Windows even channels since in the context of filebeat, that may not be obvious.

**Review by efd6 — APPROVED** [review]
Minor nit.

File: CHANGELOG.next.asciidoc (hunk 4 above)
Comment (taylor-swanson) [reply CHANGELOG.next.asciidoc]: Fair point! I'll add a note for that.

**Comment by nicpenning** [comment]
This is awesome, everyone. 

I am very excited to test this once it's available. This has been a pain point for us for quite sometime and it required some extra steps (restarting service, order of operations for upgrades with Sysmon and Wlb, etc) when we realized events were not coming in when they should have been.

**Comment by taylor-swanson** [comment]
@Mergifyio backport 7.17

**Comment by jonnygoogle25** [comment]
Hey @taylor-swanson,

Appreciate your work on this.  I was hoping that the latest version of Winlogbeat 8.7.0 with this fix would correct a problem we see when we upgrade Sysmon but it hasn't.  It's the exact scenario you subscribe in your notes but just to reiterate the issue is basically that when we upgrade Sysmon, Winlogbeat events stop flowing to their destination until we restart the service.  I've tested this going from either Sysmon14.13->14.16 and from Sysmon14.14->14.16.  In looking through Winlogbeat logs I do not ever see a channel not found error, but I do see the following while Sysmon is being upgraded:

{"log.level":"warn","@timestamp":"******","log.origin":{"file.name":"eventlog/wineventlog.go","file.line":470},"message":"WinEventLog[*****] error salvaging message (event id=5 qualifier=0 provider=\"Microsoft-Windows-Sysmon\" created at ***** will be included without a message): failed in EvtFormatMessage: The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded.","service.name":"winlogbeat","ecs.version":"1.6.0"}

Any suggestions or ideas why this might be happening?

**Comment by efd6** [comment]
@jonnygoogle25 Does [this](https://serverfault.com/questions/670269/windows-event-id-4624-repeating-with-resource-not-available) help?

**Comment by taylor-swanson** [comment]
Hey @jonnygoogle25, it seems to me that when Sysmon is upgraded, our handle to the publisher which renders the XML is no longer valid. If restarting Winlogbeat fixes it, then refreshing our handle the channel seems to be all that needs to be done. The trick here would be reliably detecting when that error occurs. If there's an associated Windows error code that accompanies that error, then it should be pretty trivial to catch it.

That error is being produced in a different part of the code, though. The issue I fixed was in the main read loop and was more so checking for errors when reading from the channel. In the situation you encountered, the channel appears to be intact, but had problems rendering the XML. If we could reliably detect the error, then perhaps I can kick back an error up to that main read loop to cause it to resubscribe to the channel.

**Comment by jonnygoogle25** [comment]
That makes sense.  I just tested the process again that breaks everything and I'm not able to find anything in the Windows event log that would help out here, the only consistent indicator is that error I shared in my earlier post from the Winlogbeat log.  Could you not go on that?

@efd6  - thanks for sharing but I think we're having a slightly different issue.  Event viewer shows the descriptions fine after the Sysmon upgrade, it's just that Winlogbeat doesn't pick them up.

**Comment by taylor-swanson** [comment]
We potentially could, but I really dislike matching errors based on strings (not saying we can't but if there's numeric error code that accompanied it, I would just use that instead). Anyways, that'd be an implementation detail to worry about later.

One other question I had, how were you performing the upgrade? When I tried, I had to uninstall the old Sysmon, then install the new. However, the old Sysmon wouldn't uninstall cleanly unless I stopped Winlogbeat (I think maybe because it saw the channel was still used by Winlogbeat).

**Comment by jonnygoogle25** [comment]
We're using chocolatey to install over the existing package.  I'm not certain if it calls an uninstall first, although I suspect it does

**Comment by taylor-swanson** [comment]
@jonnygoogle25, I wrote up a separate issue to track the publisher disabled scenario: https://github.com/elastic/beats/issues/35316

**Comment by GLMONTER** [comment]
When running Winlogbeat as a windows service after this change, the service fails to stop and hangs if a channel that is listed in the config is not found due to a continue. Is this expected behavior?

**Comment by taylor-swanson** [comment]
@GLMONTER, no that was a bug introduced by this change. It was fixed here: https://github.com/elastic/beats/pull/35474. Backports for the fix are targeting both 8.8 and 8.7.
