### PR TITLE
fix #14872: fix incorrectly handle with two-words redis command

### LINKED ISSUE #14872: Packetbeat cannot capture redis command CONFIG GET
- Version: Packetbeat version 7.4.2 (amd64), libbeat 7.4.2 [15075156388b44390301f070960fd8aeac1c9712 built 2019-10-28 19:33:55 +0000 UTC]
- Operating System:  All
- Discuss Forum URL: https://discuss.elastic.co/t/packetbeat-cannot-capture-redis-command-config-get/209917
- Steps to Reproduce:

### PR DESCRIPTION
**Pull request by mazhechao**
Fixes #14872

### CODE REVIEW

File: packetbeat/protos/redis/redis_parse.go [hunk 1]
```diff
@@ -423,7 +424,7 @@ func (p *parser) parseArray(depth int, buf *streambuf.Buffer) (common.NetString,
 	}
 
 	// handle top-level request command
-	if depth == 0 && isRedisCommand(content[0]) {
+	if depth == 0 && (isRedisCommand(content[0]) || isRedisCommand(bytes.Join(content[0:2], []byte(" ")))) {
```
Comment (adriansr) [inline packetbeat/protos/redis/redis_parse.go]: I think this needs a check in the (unlikely?) case that `count < 2`

Comment (mazhechao) [reply packetbeat/protos/redis/redis_parse.go]: Would you explain more details about what to check? I just don't understand what do you mean.

Comment (adriansr) [reply packetbeat/protos/redis/redis_parse.go]: I mean accessing `content[0:2]` can fail if `len(content)` is 1, so you can write
```
 	if depth == 0 && (isRedisCommand(content[0]) || (count > 1 && isRedisCommand(bytes.Join(content[0:2], []byte(" "))))) { 
```

Comment (mazhechao) [reply packetbeat/protos/redis/redis_parse.go]: You are right. I get it.

**Comment by mazhechao** [comment]
@adriansr Would you please review again?

File: packetbeat/protos/redis/redis_parse.go [hunk 2]
```diff
@@ -423,7 +424,7 @@ func (p *parser) parseArray(depth int, buf *streambuf.Buffer) (common.NetString,
 	}
 
 	// handle top-level request command
-	if depth == 0 && isRedisCommand(content[0]) {
+	if depth == 0 && (isRedisCommand(content[0]) || (count > 1 && isRedisCommand(bytes.Join(content[0:2], []byte(" "))))) {
 		p.message.isRequest = true
 		p.message.method = content[0]
 		if len(content) > 1 {
```
Comment (faec) [inline packetbeat/protos/redis/redis_parse.go]: It seems like `p.message.method` and `p.message.path` need to be computed differently as well to handle the two-word case

File: packetbeat/protos/redis/redis_test.go [hunk 3]
```diff
@@ -70,6 +70,24 @@ func TestRedisParser_ArrayRequest(t *testing.T) {
 	assert.Equal(t, len(arrayRequest), msg.size)
 }
 
+var arrayRequest2 = []byte("*3\r\n" +
+        "$6\r\n" +
```
Comment (faec) [inline packetbeat/protos/redis/redis_test.go]: the extra whitespace here is probably what's breaking the linter... can you run `mage fmt update` and re-commit to make sure everything is formatted right?

File: packetbeat/protos/redis/redis_parse.go (hunk 2 above)
Comment (mazhechao) [reply packetbeat/protos/redis/redis_parse.go]: I will have a look and test again.

File: packetbeat/protos/redis/redis_test.go (hunk 3 above)
Comment (mazhechao) [reply packetbeat/protos/redis/redis_test.go]: I get erros, would you please help me?

# command-line-arguments
./magefile.go:153:13: undefined: "github.com/elastic/beats/dev-tools/mage".DefaultIncludeListOptions
./magefile.go:156:39: not enough arguments in call to "github.com/elastic/beats/dev-tools/mage".GenerateIncludeListGo
Error: error compiling magefiles

**Comment by mazhechao** [comment]
@adriansr @faec Would you please review my commits again?
And I don't know how to solve the lint problem, when I run `mage fmt update`, I get some errors
```
\# command-line-arguments
./magefile.go:153:13: undefined: "github.com/elastic/beats/dev-tools/mage".DefaultIncludeListOptions
./magefile.go:156:39: not enough arguments in call to "github.com/elastic/beats/dev-tools/mage".GenerateIncludeListGo
Error: error compiling magefiles 
```

**Comment by adriansr** [comment]
jenkins, test this

**Comment by mazhechao** [comment]
Is this released in v7.7.0, I can't find in the release notes. @adriansr

**Comment by adriansr** [comment]
@mazhechao I don't know why it's not in the release notes, but it made it to 7.7.0

**Comment by mazhechao** [comment]
I think it's better to mention this fix in the release notes. @adriansr
