### PR TITLE
[Agent] Improve the handling of failed applications, fixed crash in FleetManager, report all state changes to Fleet

### LINKED ISSUE #19165: [Agent] Metricbeat crashes with default configuration
### Steps to reproduce
1. Start up ES, Kibana, and EPM using [this `docker-compose.yml`](https://github.com/elastic/integrations/blob/6819dff888019993d7f9cc81391caee6da7deb5c/testing/environments/snapshot.yml).
2. Once the services spin up, visit the Kibana > Ingest Manager > Fleet UI and grab the command to enroll an agent.
3. Download Elastic Agent 8.0.0-SNAPSHOT from https://snapshots.elastic.co/8.0.0-e588f883/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz and install it.
4. Enroll the Agent with the command from Kibana.
5. Run the Agent.

### Observed
Agent logs display repeated messages like this:
```
2020-06-12T08:57:03-07:00 ERROR reporter.go:47  2020-06-12T08:57:03-07:00: type: 'ERROR': sub_type: 'CONFIG' message: Application: metricbeat[5cd0813e-344e-4a38-9301-9a7158bf9d6a]: application 'metricbeat--8.0.0-SNAPSHOT' crashed: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/plugin/app/app.go[214]: unknown error
```

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Improve the logic of the restart loop to be more robust. While debugging #19165 I noticed that sometimes restarting too quickly could result in 2 metricbeats being started at the same time even though one application was only request to start.

This also fixes an issue in the `FleetManager` that was causing `OnConfig` to crash, which was causing the restart loop. Adjusted config issues to only report as Degraded so that metricbeat is not restarted because of a bad config. (I think this should change once the system package or modules are fixed, and once the proper status reporting is implemented in each beat).

Improve the reporting logic to report all state changes of an application to Fleet. If the state changes of an application while its being ran those state changes are also now reported to Fleet. Giving the same visibility of the Agent on the machine as in the Fleet UI.

## Why is it important?

So the same application is not started multiple times and to ensure that restarting of an Agent sub-process works as expected. To prevent metricbeat from crashing using the default system module. To provide better observability of the Agent.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [X] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #19165

### CODE REVIEW

**Comment by blakerouse** [comment]
I have updated this it solve #19165.

File: x-pack/elastic-agent/pkg/agent/operation/operation_config.go [hunk 1]
```diff
@@ -7,6 +7,8 @@ package operation
 import (
 	"context"
 
+	"github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/core/plugin/state"
```
Comment (michalpristas) [inline x-pack/elastic-agent/pkg/agent/operation/operation_config.go:10]: mage fmt should keep things together

File: x-pack/elastic-agent/pkg/agent/operation/operation_install.go [hunk 2]
```diff
@@ -8,7 +8,8 @@ import (
 	"context"
 	"os"
 
-	"github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/errors"
+	"github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/core/plugin/state"
+
```
Comment (michalpristas) [inline x-pack/elastic-agent/pkg/agent/operation/operation_install.go:12]: same everywhere

File: x-pack/elastic-agent/pkg/core/plugin/app/app.go [hunk 3]
```diff
@@ -206,16 +212,35 @@ func (a *Application) waitProc(proc *os.Process) <-chan *os.ProcessState {
...
-			errors.TypeApplicationCrash,
-			errors.M(errors.MetaKeyAppName, a.name),
-			errors.M(errors.MetaKeyAppName, a.id))
-		a.failureReporter(ctx, a.name, crashError)
+func (a *Application) setState(status state.Status, msg string) {
+	if a.state.Status != status || a.state.Message != msg {
+		a.state.Status = status
+		a.state.Message = msg
+		if a.reporter != nil {
+			go a.reporter.OnStateChange(a.id, a.name, a.state)
```
Comment (michalpristas) [inline x-pack/elastic-agent/pkg/core/plugin/app/app.go:239]: what in case of fast change of state changes as goroutines dont have guaranteed order of start this can be tricky

File: x-pack/elastic-agent/pkg/reporter/reporter.go [hunk 4]
```diff
@@ -64,46 +72,10 @@ func (r *Reporter) Close() {
...
-	r.report(ctx, rec)
-}
-
-// OnFatal reports applications fatal event.
-func (r *Reporter) OnFatal(ctx context.Context, application string, err error) {
-	msg := fmt.Sprintf("Application: %s[%s]: %v", application, r.info.AgentID(), err)
-	rec := generateRecord(EventTypeError, EventSubTypeConfig, msg)
-	r.report(ctx, rec)
+// OnStateChange called when state of an application changes.
+func (r *Reporter) OnStateChange(id string, name string, state state.State) {
```
Comment (michalpristas) [inline x-pack/elastic-agent/pkg/reporter/reporter.go:76]: i was passing context down the reporter so we can eventually control timeout of reporting or call it within time sensitive operations correctly without blocking.
passing context as a property serves as a cancellation token for long running loops, which is not present here

Comment (blakerouse) [reply x-pack/elastic-agent/pkg/reporter/reporter.go:76]: Reporter has always been created with a context, but that context was never used. So I used that context, instead of passing the context from the application into the reporter. That way all state changes go to the reporter and are not cancelled unless the entire reporter is cancelled.

File: x-pack/elastic-agent/pkg/agent/operation/operation_config.go (hunk 1 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/operation/operation_config.go:10]: I ran `mage fmt`, it passed lint as well, so it believe this is valid. But I will fix.

File: x-pack/elastic-agent/pkg/agent/operation/operation_install.go (hunk 2 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/agent/operation/operation_install.go:12]: I ran `mage fmt`, it passed lint as well, so it believe this is valid. But I will fix.

File: x-pack/elastic-agent/pkg/core/plugin/app/app.go (hunk 3 above)
Comment (blakerouse) [reply x-pack/elastic-agent/pkg/core/plugin/app/app.go:239]: Because the old `reportCrash` used a go routine, I kept this the same way. But your point is very valid. I think we should change `Reporter` to keep a queue of records to send and send then in a dedicated go routine that way we can ensure the order is consistent.

I can do that in a follow up branch.
