### PR TITLE
Ensure kubernetes caches don't expire if they are being read

### LINKED ISSUE #10658: Pod and container usage percentage is not properly calculated
It has been reported that in some cases pod and/or container uage percentages are not being correctly calculated. This seems related to the retrieval or calculation of container limits.

For example:
* https://discuss.elastic.co/t/kubernetes-module-not-getting-resource-limits/167210

There are also reports in which the percentages seem to be calculated during some periods with the container limits, and some periods with the node limits.

Related issues fixed in the past:
* https://github.com/elastic/beats/issues/9221
* https://github.com/elastic/beats/issues/10081

It is not clear how to reproduce these issues.

### PR DESCRIPTION
**Pull request by jsoriano**
Some metrics in metricbeat kubernetes module are cached during a time,
if they are not updated they are removed. But it is usual to have pods or
containers that are not updated during more time that the expiration cache.
Current implementation was not renovating expiration times for cache
entries so all were eventually removed if updates for them are not received.
Replace it with the cache implementation available in libbeat, but keeping
the existing interface.

Also, use slashes instead of dashes to generate unique container uids.
Dashes can be used by kubernetes names, what could lead to ambiguous
keys for the caches.

Fix #10658

### CODE REVIEW

File: metricbeat/module/kubernetes/util/metrics_cache.go [hunk 1]
```diff
@@ -18,76 +18,84 @@
...
-	defer m.RUnlock()
+	return m.getWithDefault(name, def)
+}
+
+func (m *valueMap) getWithDefault(name string, def float64) float64 {
+	m.Lock()
+	defer m.Unlock()
 	val, ok := m.values[name]
 	if ok {
+		val.renew(m.timeout)
```
Comment (jsoriano) [inline metricbeat/module/kubernetes/util/metrics_cache.go]: This is the main change in this PR, to renew the expiration time when the value is read.

File: metricbeat/module/kubernetes/util/metrics_cache.go [hunk 2]
```diff
@@ -97,26 +106,27 @@ func (m *valueMap) GetWithDefault(name string, def float64) float64 {
...
-				m.Lock()
-				now := now().Unix()
-				for name, val := range m.values {
-					if now > val.expires {
-						delete(m.values, name)
-					}
+func (m *valueMap) startWorkers(ctx context.Context) {
+	go func() {
+		for {
+			var now time.Time
```
Comment (sayden) [inline metricbeat/module/kubernetes/util/metrics_cache.go]: zero-value of `time.Time` is not _now_. I don't remember exactly but I think it was 0-0-1 or 1-1-1970. If you want current time you should use `now := time.Now()`

File: metricbeat/module/kubernetes/util/metrics_cache.go [hunk 3]
```diff
@@ -28,66 +29,74 @@ var PerfMetrics = NewPerfMetricsCache()
 const defaultTimeout = 120 * time.Second
 
 var now = time.Now
-var sleep = time.Sleep
+var after = time.After
```
Comment (sayden) [inline metricbeat/module/kubernetes/util/metrics_cache.go]: You are not serializing access to this global variable

File: metricbeat/module/kubernetes/util/metrics_cache.go (hunk 2 above)
Comment (jsoriano) [reply metricbeat/module/kubernetes/util/metrics_cache.go]: You are right, but it was only the variable definition, the value was set later. I have changed this code in any case.

File: metricbeat/module/kubernetes/util/metrics_cache.go (hunk 3 above)
Comment (jsoriano) [reply metricbeat/module/kubernetes/util/metrics_cache.go]: Yeah, there are some more things to improve around there.

I didn't want to touch this a lot, but at the end I also wanted the race detector to work and it wasn't with these global variables. I moved them to local variables in the caches.

**Comment by jsoriano** [comment]
I have been testing this with master and 6.6.1 and it seems to work.
I have also fixed some issues on tests with the initial version to avoid flakyness and to pass the race detector.

As caches are now, #10658 can still happen if period of container metricset is greater than 120 seconds, fixing this would require to further refactor the global cache. I leave this for future improvements as I don't think many people will have these periods. A quick "fix" would be to increase the default timeout.

**Comment by andrewkroh** [comment]
It only quickly peaked at the cache, but it looks similar to libbeat/common/cache.go ([godoc](https://godoc.org/github.com/elastic/beats/libbeat/common#Cache))which expires elements based on their last access time, has a goroutine to periodically do cleanup, and allows injecting a clock for testing (but injecting the clock isn't exported so you'd need to expose this).

**Comment by jsoriano** [comment]
@andrewkroh oh, this actually looks like what we'd need here, I will give a try to this implementation, thanks!

File: metricbeat/module/kubernetes/util/metrics_cache_test.go [hunk 4]
```diff
@@ -19,45 +19,10 @@ package util
...
-	test.Set("foo", 3.14)
-
-	// Let cleanup do its job
-	sleepCh <- struct{}{}
-	sleepCh <- struct{}{}
-	sleepCh <- struct{}{}
-
-	// Check it expired
-	assert.Equal(t, 0.0, test.Get("foo"))
-}
```
Comment (jsoriano) [inline metricbeat/module/kubernetes/util/metrics_cache_test.go]: Test removed because libbeat cache implementation is used now and it has its own tests for this.
