### PR TITLE
[add_session_metadata processor] Enrich events with user and group names

### LINKED ISSUE #39282: [Auditbeat] Session view showing uid of Linux user initiated the session instead of user name
On using the new processor `add_session_metadata` with auditd module of auditbeat, it appears session viewer is only showing the uid of Linux user initiated the session instead of user name as shown below.

Screenshot 2024-04-29 at 12 45 02 PM

My assumption is that, `add_session_metadata` processor is not setting/adding `process.entry_leader.user.name` field and that leads to above situation. Interesting to note that the event doc already includes another field labeled `user.name`, which accurately displays the user's name.

For whatever reason, root sessions seems to be showing correctly tho.

Screenshot 2024-04-29 at 12 45 36 PM

For confirmed bugs, please report:
- Version: [8.14 BC1](https://staging.elastic.co/8.14.0-a40d088a/summary-8.14.0.html)
- Operating System: Amazon Linux release 2023.4.20240416 (Amazon Linux)
- Discuss Forum URL:
- Steps to Reproduce: Follow the steps mentioned this [PR](https://github.com/elastic/beats/pull/37640) and ssh to instance as ec2-user/any local linux user and verify the session view for the corresponding session in Kibana

### PR DESCRIPTION
**Pull request by mjwolf**
## Proposed commit message

Update the `add_session_metadata` processor to add user and group names to enriched events, rather than just IDs, as it was doing previously.

This also renames the `UpdateDB` function to `SyncDB`. Previously this function was confusing, because it didn't always update the DB. With ebpf, the DB update is done separately. By renaming and updating the func comment, it should be more clear that the function should synchronize the DB so it's ready for enriching events, either by waiting until the DB is updated, or doing the synchronization itself, as it does with procfs backend.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

Adding user and group names will increase event sized very slightly, it shouldn't have an impact on users.

## How to test this PR locally

For process events enriched with the add_session_metadata processor, check that documents have values for these fields: `process.user.name`, `process.group.name`, `process.parent.user.name`, `process.parent.group.name`, `process.session_leader.user.name`, `process.session_leader.group.name`, `process.group_leader.user.name`, `process.group_leader.group.name`, `process.entry_leader.user.name`, `process.entry_leader.group.name`.

## Related issues

- Closes #39282 

## Screenshots

Screenshots showing session view, with user and group names for a process and related processes

Screenshot 2024-05-13 at 2 26 02 PM
Screenshot 2024-05-13 at 2 26 19 PM

### CODE REVIEW

File: x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider.go [hunk 1]
```diff
@@ -40,8 +40,8 @@ func NewProvider(ctx context.Context, logger *logp.Logger, db *processdb.DB, rea
 	}, nil
 }
 
-// UpdateDB will update the process DB with process info from procfs or the event itself
-func (s prvdr) UpdateDB(ev *beat.Event, pid uint32) error {
+// SyncDB will update the process DB with process info from procfs or the event itself
+func (s prvdr) SyncDB(ev *beat.Event, pid uint32) error {
```
Comment (pkoutsovasilis) [inline x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider.go:44]: ❤️

File: x-pack/auditbeat/processors/sessionmd/processdb/names.go [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+	user, err := user.LookupId(id)
+	cval := cval{}
+	if err != nil {
+		cval.name = ""
+		cval.found = false
+	} else {
+		cval.name = user.Username
+		cval.found = true
+	}
+	return cval.name, cval.found
```
Comment (pkoutsovasilis) [inline x-pack/auditbeat/processors/sessionmd/processdb/names.go:53]: If I get this correctly before we return it we should save `cval` in the map right? That said, I think that the cache sure helps with the performance (especially if we are talking about LDAP-based users) but on the other hand it can affect the reliability of the data, e.g.

```
$ sudo useradd jane
$ sudo su jane
$ id
uid=1000(jane) gid=1001(jane) groups=1001(jane)
$ exit
$ sudo usermod -l new_jane jane
$ sudo su new_jane
$ id
uid=1000(new_jane) gid=1001(jane) groups=1001(jane)
```

I just renamed a user but the Id remains the same so better to search for it every-time?!?

File: x-pack/auditbeat/processors/sessionmd/processdb/names.go [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+	group, err := user.LookupGroupId(id)
+	cval := cval{}
+	if err != nil {
+		cval.name = ""
+		cval.found = false
+	} else {
+		cval.name = group.Name
+		cval.found = true
+	}
+	return cval.name, cval.found
```
Comment (pkoutsovasilis) [inline x-pack/auditbeat/processors/sessionmd/processdb/names.go:74]: need to save cval in the groups map before returning right?

**Comment by mjwolf** [comment]
I did some benchmarking on this (with [this](https://github.com/mjwolf/beats/blob/names-profiling/x-pack/auditbeat/processors/sessionmd/processdb/names_test.go)), and I learned a few things

1. The uncached use of `user.LookupId(id)` is faster than my cached version
2. The library has two implementations depending on if CGO is enabled or not, it will either use `getpwnam` syscall or read `/etc/passwd`.
3. Both versions must have some sort of caching lower in the stack, they run much faster than if a file were actually read every time (~70ns/op vs ~5500ns/op for just reading the file)


Here's the benchmark results of 1. My caching code, 2. user.LookupId(id) with CGO disabled, 3. user.LookupId(id) with CGO enabled, 4. Just reading `/etc/passwd`
```
mwolf@fedora:~/git/beats/x-pack/auditbeat/processors/sessionmd/processdb$ CGO_ENABLED=0 go test -gcflags="all=-N -l" -v -bench=. -run=none  -count=5 -benchtime=5s
goos: linux
goarch: arm64
pkg: github.com/elastic/beats/v7/x-pack/auditbeat/processors/sessionmd/processdb
BenchmarkCached
BenchmarkCached-8       60177172               101.4 ns/op
BenchmarkCached-8       60853856               102.9 ns/op
BenchmarkCached-8       59322025               103.3 ns/op
BenchmarkCached-8       60308276               102.6 ns/op
BenchmarkCached-8       60827533               103.1 ns/op
BenchmarkUnCached
BenchmarkUnCached-8     90296116                68.92 ns/op
BenchmarkUnCached-8     87325711                68.64 ns/op
BenchmarkUnCached-8     87732696                69.06 ns/op
BenchmarkUnCached-8     92894774                69.88 ns/op
BenchmarkUnCached-8     75549919                68.36 ns/op
PASS
ok      github.com/elastic/beats/v7/x-pack/auditbeat/processors/sessionmd/processdb     64.974s
mwolf@fedora:~/git/beats/x-pack/auditbeat/processors/sessionmd/processdb$ CGO_ENABLED=1 go test -gcflags="all=-N -l" -v -bench=BenchmarkUnCached -run=none  -count=5 -benchtime=5s
goos: linux
goarch: arm64
pkg: github.com/elastic/beats/v7/x-pack/auditbeat/processors/sessionmd/processdb
BenchmarkUnCached
BenchmarkUnCached-8     87594390                68.83 ns/op
BenchmarkUnCached-8     90117325                66.67 ns/op
BenchmarkUnCached-8     89905770                68.13 ns/op
BenchmarkUnCached-8     90145305                69.15 ns/op
BenchmarkUnCached-8     82918654                68.41 ns/op
PASS
ok      github.com/elastic/beats/v7/x-pack/auditbeat/processors/sessionmd/processdb     30.452s
mwolf@fedora:~/git/beats/x-pack/auditbeat/processors/sessionmd/processdb$ CGO_ENABLED=1 go test -gcflags="all=-N -l" -v -bench=BenchmarkFileRead -run=none  -count=5 -benchtime=5s
goos: linux
goarch: arm64
pkg: github.com/elastic/beats/v7/x-pack/auditbeat/processors/sessionmd/processdb
BenchmarkFileRead
BenchmarkFileRead-8      1000000              5431 ns/op
BenchmarkFileRead-8      1000000              5458 ns/op
BenchmarkFileRead-8      1000000              5484 ns/op
BenchmarkFileRead-8      1000000              5455 ns/op
BenchmarkFileRead-8      1000000              5666 ns/op
PASS
```

File: x-pack/auditbeat/processors/sessionmd/processdb/names.go (hunk 2 above)
Comment (mjwolf) [reply x-pack/auditbeat/processors/sessionmd/processdb/names.go]: I've removed all the caching here, it turns out it has no benefit. I've also tried changing the username as the benchmarking ran, and it returned the new username.

**Review by pkoutsovasilis — APPROVED** [review]
nice findings @mjwolf , LGTM
