### PR TITLE
Don't generate autodiscover config when no port matches host hints

### LINKED ISSUE #8264: [Metricbeat Autodiscover] error parsing URL: empty host
Metricbeat Version used: 6.4.0, 6.6.2

hints-based autodiscover generates incomplete configurations when there are ports defined in the pod spec and hints include hard-coded ports. Some of them must match. If not, errors related to incorrect hosts happen.

> 2019-03-15T11:28:59.316Z	DEBUG	[autodiscover]	autodiscover/autodiscover.go:195	Check failed for config &{{<nil> } <nil> 0xc420681f60}: 3 errors: host parsing failed for etcd-leader: error parsing URL: empty host; host parsing failed for etcd-self: error parsing URL: empty host; host parsing failed for etcd-store: error parsing URL: empty host, won't start runner

`raw` annotations can be used as workaround as mentioned in [this comment](https://github.com/elastic/beats/issues/8264#issuecomment-472669707).

----
Original report:

Hi,

I'm trying to get the Prometheus Collector working with Hints based autodiscovery in Kubernetes.

Unfortunately I always get the following Error:

> ERROR	[autodiscover]	cfgfile/list.go:104	Error creating runner from config: 1 error: 1 error: host parsing failed for prometheus-collector: error parsing URL: empty host

I checked the start event for the host field and it's present.

`Got a start event: map[host:100.123.3.45 port:1234 kubernetes:{"annotations":{"co":{"elastic":{"metrics/hosts":"${data.host}:10254","metrics/metricsets":"collector","metrics/module":"prometheus","metrics/period":"1m"}}}} config:[0xc42001f4a0] start:true], generated configs: [0xc42001f4a0]`

I'm using the following Annotations:
```
      annotations:
        co.elastic.metrics/hosts: ${data.host}:10254
        co.elastic.metrics/metricsets: collector
        co.elastic.metrics/module: prometheus
        co.elastic.metrics/period: 1m
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
```

Any idea why this is happening?

### PR DESCRIPTION
**Pull request by jsoriano**
On metricbeat, when the host autodiscover hint is used, and it includes
the port, one of the exposed ports has to match with the one in the
hint. If not, no configuration should be generated. If it is generated,
it will have empty hosts, what would lead to unexpected errors as the
ones seen in #8264.

Fixes #8264

### CODE REVIEW

File: metricbeat/autodiscover/builder/hints/metrics_test.go [hunk 1]
```diff
@@ -67,6 +67,21 @@ func TestGenerateHints(t *testing.T) {
 			len:    0,
 			result: common.MapStr{},
 		},
+		{
+			message: "Hints without matching port should return nothing",
+			event: bus.Event{
+				"host": "1.2.3.4",
+				"port": 9090,
```
Comment (kaiyan-sheng) [inline metricbeat/autodiscover/builder/hints/metrics_test.go]: What if no port is assigned to this container?

File: metricbeat/autodiscover/builder/hints/metrics.go [hunk 2]
```diff
@@ -175,7 +179,12 @@ func (m *metricHints) getHostsWithPort(hints common.MapStr, port int) []string {
 		}
 	}
 
-	return result
+	if len(thosts) > 0 && len(result) == 0 {
+		logp.Debug("hints.builder", "no hosts selected for port %d with hints: %+v", port, thosts)
```
Comment (kaiyan-sheng) [inline metricbeat/autodiscover/builder/hints/metrics.go]: Should we make the switch to m.logger here instead of logp? 😬not sure if putting them in same pr is good or not.

**Comment by exekias** [comment]
FYI @vjsamuel

**Comment by exekias** [comment]
This makes me wonder, what happens to unexposed ports? those should still be accessible I guess?

**Comment by kaiyan-sheng** [comment]
> This makes me wonder, what happens to unexposed ports? those should still be accessible I guess?

Hehe that's what I asked in the unit test part 😄 we are thinking about the same issue haha

File: metricbeat/autodiscover/builder/hints/metrics.go (hunk 2 above)
Comment (jsoriano) [reply metricbeat/autodiscover/builder/hints/metrics.go]: This module doesn't have a logger yet, I'd leave this for a future change.

File: metricbeat/autodiscover/builder/hints/metrics_test.go (hunk 1 above)
Comment (jsoriano) [reply metricbeat/autodiscover/builder/hints/metrics_test.go]: Then a configuration is returned, the following test cases cover this.

**Comment by jsoriano** [comment]
> This makes me wonder, what happens to unexposed ports? those should still be accessible I guess?

Yes, unexposed ports are in principle accessible too (if they are not protected via CNI and network policies). And generating a config should work in that case. But current code doesn't generate a host if the port in the hint doesn't match with the exposed port, this produces errors. The fix in this PR avoids these buggy configurations without changing the behaviour.

Another option we have to fix this issue would be to remove this check and generate a config in any case, but I guess this check was added to avoid duplicated configs. I will do some tests with this option.

**Comment by jsoriano** [comment]
> Another option we have to fix this issue would be to remove this check and generate a config in any case, but I guess this check was added to avoid duplicated configs. I will do some tests with this option.

No, sorry, this check is needed when multiple hosts are configured in the hint, so only one of them is selected. We shouldn't remove this check while we support multiple hosts in the hint.

We could discuss if we change this hosts annotation to allow a single host only, but this would be a breaking change, so by now I'd go with a fix like the one in this PR.

**Comment by jsoriano** [comment]
Merging this, failures in travis don't seem related.
