### PR TITLE
[Flaky Test] Fix metricbeat/module/system/process TestFetchDegradeOnPartial

### LINKED ISSUE #42809: [Flaky Test] metricbeat/module/system/process TestFetchDegradeOnPartial, TestFetch
## Flaky Test

* **Test Name:** metricbeat/module/system/process TestFetchDegradeOnPartial
* **Link:** https://github.com/elastic/beats/blob/main/metricbeat/module/system/process/process_test.go#L77
* **Branch:** AndersonQ:423225-input-event-report
* **Artifact Link:** https://buildkite.com/organizations/elastic/pipelines/beats-metricbeat/builds/14172/jobs/019522b9-71e7-492e-823e-4932e6516735/artifacts/019522c1-2ad4-414c-9d2e-cd525ced41bc
* **Notes:** Additional details about the test. e.g. theory as to failure cause

It seems on CI the test isn't being able to fetch any event. Perhaps it should run as admin to have more permission or try more times. Run it on a `requere.Eventually` to ensure at least a event is fetched.

The panic is a bug in the test, it does not check if there is any event before accessing it: 
https://github.com/AndersonQ/beats/blob/7a2f8d45744922c25d372482824641b3bde3790b/metricbeat/module/system/process/process_test.go#L80-L81
### Stack Trace

```
2025-02-20 17:01:21 CEST	=== Failed
2025-02-20 17:01:21 CEST	=== FAIL: metricbeat/module/system/process TestFetchDegradeOnPartial (0.13s)
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.764Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 0: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 0: The parameter is incorrect. {0xc000404000}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.764Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 4: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 4: Access is denied. {0xc0004041c0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.764Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 120: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 120: Access is denied. {0xc000404240}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.764Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 376: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 376: Access is denied. {0xc0004042a0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.764Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 520: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 520: Access is denied. {0xc000404340}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.764Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 592: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 592: Access is denied. {0xc0004043a0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.765Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 600: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 600: Access is denied. {0xc000404400}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.766Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 732: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 732: Access is denied. {0xc000404460}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.781Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 3244: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 3244: Access is denied. {0xc0004044e0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.785Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 5236: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 5236: Access is denied. {0xc000404560}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.801Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 0: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 0: The parameter is incorrect. {0xc0004050e0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.801Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 4: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 4: Access is denied. {0xc000405180}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.801Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 120: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 120: Access is denied. {0xc0004051e0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.804Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 376: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 376: Access is denied. {0xc000405240}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.804Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 520: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 520: Access is denied. {0xc0004052a0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.807Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 592: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 592: Access is denied. {0xc000405300}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.808Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 600: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 600: Access is denied. {0xc000405360}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.809Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 732: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 732: Access is denied. {0xc0004053c0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.846Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 3244: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 3244: Access is denied. {0xc000405440}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.852Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidFill","file.name":"process/process.go","file.line":301},"message":"error calling FillMetricsRequiringMoreAccess for pid 5236: %!w(*fmt.wrapError=&{error fetching process args: non fatal error; reporting partial metrics: OpenProcess failed for PID 5236: Access is denied. {0xc0004054c0}})","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.877Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).pidIter","file.name":"process/process.go","file.line":212},"message":"Error fetching PID info for 5764, skipping: GetInfoForPid failed for pid 5764: could not get all information for PID 5764: error fetching name: OpenProcess failed for pid=5764: The parameter is incorrect.\nerror fetching status: OpenProcess failed for pid=5764: The parameter is incorrect.","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	{"log.level":"debug","@timestamp":"2025-02-20T16:01:01.877Z","log.logger":"processes","log.origin":{"function":"github.com/elastic/elastic-agent-system-metrics/metric/system/process.(*Stats).Get","file.name":"process/process.go","file.line":144},"message":"error fetching process metrics: non fatal error; reporting partial metrics: GetInfoForPid failed for pid 5764: could not get all information for PID 5764: error fetching name: OpenProcess failed for pid=5764: The parameter is incorrect.\nerror fetching status: OpenProcess failed for pid=5764: The parameter is incorrect.","ecs.version":"1.6.0"}
2025-02-20 17:01:21 CEST	    process_test.go:77:
2025-02-20 17:01:21 CEST	        	Error Trace:	C:/buildkite-agent/builds/bk-agent-prod-gcp-1740066775103615090/elastic/beats-metricbeat/metricbeat/module/system/process/process_test.go:77
2025-02-20 17:01:21 CEST	        	Error:      	Should NOT be empty, but was []
2025-02-20 17:01:21 CEST	        	Test:       	TestFetchDegradeOnPartial
2025-02-20 17:01:21 CEST	    process_test.go:79: fetched 0 events, showing events[0]:
2025-02-20 17:01:21 CEST	panic: runtime error: index out of range [0] with length 0 [recovered]
2025-02-20 17:01:21 CEST		panic: runtime error: index out of range [0] with length 0
2025-02-20 17:01:21 CEST	
2025-02-20 17:01:21 CEST	goroutine 52 [running]:
2025-02-20 17:01:21 CEST	testing.tRunner.func1.2({0x1ae8f40, 0xc0000f22d0})
2025-02-20 17:01:21 CEST		C:/Users/Buildkite/.go/go-1.22.12/src/testing/testing.go:1631 +0x24a
2025-02-20 17:01:21 CEST	testing.tRunner.func1()
2025-02-20 17:01:21 CEST		C:/Users/Buildkite/.go/go-1.22.12/src/testing/testing.go:1634 +0x377
2025-02-20 17:01:21 CEST	panic({0x1ae8f40?, 0xc0000f22d0?})
2025-02-20 17:01:21 CEST		C:/Users/Buildkite/.go/go-1.22.12/src/runtime/panic.go:770 +0x132
2025-02-20 17:01:21 CEST	github.com/elastic/beats/v7/metricbeat/module/system/process.TestFetchDegradeOnPartial(0xc00012a1a0)
2025-02-20 17:01:21 CEST		C:/buildkite-agent/builds/bk-agent-prod-gcp-1740066775103615090/elastic/beats-metricbeat/metricbeat/module/system/process/process_test.go:81 +0x772
2025-02-20 17:01:21 CEST	testing.tRunner(0xc00012a1a0, 0x1be0428)
2025-02-20 17:01:21 CEST		C:/Users/Buildkite/.go/go-1.22.12/src/testing/testing.go:1689 +0xfb
2025-02-20 17:01:21 CEST	created by testing.(*T).Run in goroutine 1
2025-02-20 17:01:21 CEST		C:/Users/Buildkite/.go/go-1.22.12/src/testing/testing.go:1742 +0x390
2025-02-20 17:01:21 CEST	
2025-02-20 17:01:21 CEST	DONE 945 tests, 39 skipped, 1 failure in 147.088s
2025-02-20 17:01:21 CEST	Error: failed to execute go: exit status 1
```

### PR DESCRIPTION
**Pull request by AndersonQ**
## Proposed commit message

```
fix metricbeat/module/system/process TestFetchDegradeOnPartial

metricbeat/module/system/process TestFetchDegradeOnPartial is not platform specific. 
Therefore it does not need to run on every possible platform.

Skip the test when running on:
 - CI on windows: it runs as admin and no error is returned
 - unix-like as root: it does not return any error
```

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Disruptive User Impact

- N/A

## How to test this PR locally

Run the test several time as root on non-windows or on Windows as admin

```
❯ go test -run TestFetchDegradeOnPartial -count 100 ./metricbeat/module/system/process
ok  	github.com/elastic/beats/v7/metricbeat/module/system/process	43.825s
```

```
=== SKIP: metricbeat/module/system/process TestFetchDegradeOnPartial (0.00s)
2025-03-28 20:13:45 CEST	    process_test.go:62: Skip: CI run on windows. It is run as admin, but the test requires to run as non-admin
```

```
=== SKIP: metricbeat/module/system/process TestFetchDegradeOnPartial (0.00s)
2025-03-28 20:24:16 CEST	    process_test.go:65: Skip: running as root on non-windows, but the test requires to run as non-root
```

## Related issues

- Closes #42809

### CODE REVIEW

File: metricbeat/module/system/process/process_test.go [hunk 1]
```diff
@@ -58,29 +58,26 @@ func TestFetch(t *testing.T) {
...
-			assert.NotErrorIsf(t, err, &mb.PartialMetricsError{}, "Expected non-fatal error, got %v", err)
-		}
-	} else {
-		assert.NotEmpty(t, events)
-
-		events, errs = mbtest.ReportingFetchV2Error(f)
-		for _, err := range errs {
-			assert.ErrorIsf(t, err, process.NonFatalErr{}, "Expected non-fatal error, got %v", err)
-		}
-		require.NotEmpty(t, events)
```
Comment (AndersonQ) [inline metricbeat/module/system/process/process_test.go:79]: @VihasMakwana, you were the original author of this test, right? What was the intention of fetching the metrics again? It's unclear to me what you intended with that.

Comment (VihasMakwana) [reply metricbeat/module/system/process/process_test.go:79]: I was struggling to find the intention behind it and ended up opening https://github.com/elastic/beats/pull/43371 to fix it. We dont need to fetch same metric twice.

It would work for both, root and non-root users.

---

For now, your PR looks good. I'll work on merging mine once I get back on Wednesday.

Just a couple of suggestions:
1. we should `/test` multiple times to make sure the test passes in all scenarios
2. some linting issues.

**Review by VihasMakwana — APPROVED** [review]

File: metricbeat/module/system/process/process_test.go (hunk 1 above)
Comment (AndersonQ) [reply metricbeat/module/system/process/process_test.go:79]: I don't think we'll need your once mine is merged...

Comment (AndersonQ) [reply metricbeat/module/system/process/process_test.go:79]: > 1. we should /test multiple times to make sure the test passes in all scenarios

I did it and it's on the "How to test this PR"

> some linting issues.

It's never happy. It's the logger, there is a workstream fixing the logger. It isn't the scope of this PR.

Comment (VihasMakwana) [reply metricbeat/module/system/process/process_test.go:79]: Oh I see. 
This test case is meant for non-root users. 
For root-users, there will be no errors reported and it is already covered by other test cases.

Comment (VihasMakwana) [reply metricbeat/module/system/process/process_test.go:79]: > I did it and it's on the "How to test this PR"

I'm sorry 😭. I meant commenting `/test` on this PR multiple times, so we can be sure it passed on CI. We have had fare share of tests that run completely fine on local machine but fail on CI.

Comment (AndersonQ) [reply metricbeat/module/system/process/process_test.go:79]: I was testing it with the same setup CI uses, so we should be fine. Worst case, we re-open the issue with new data
