### PR TITLE
Fix filebeat file rotation registrar issue #1281

### LINKED ISSUE #1281: Filebeat 1.1.2 does not record correct inode values of rotated logs on exit
From the discussion at https://discuss.elastic.co/t/filebeat-1-1-2-does-not-record-correct-inode-values-of-rotated-logs-on-exit/45749

I am seeing filebeat re-ship rotated log files when the filebeat service restarts.

We are experiencing the problem on a local ext4 file system on Ubuntu 14.04 running in AWS EC2.

While filebeat remains running, it is correctly processing the files. The problem is that when it persists its state to the registry file, it is persisting the older inode values of the files before they were rotated, not the inodes of the files at those paths at the time filebeat exited.

I have created a basic configuration and bash script which starts filebeat, writes to a log file, rotates it a couple of times (with pauses in between to allow filebeat to notice) and then stops filebeat.

Full repro script, conf, and output log available as a gist:
https://gist.github.com/jstangroome/a1a70306cbd7a9420be15ec2bbe109a0

After filebeat stops, the registry has persisted the wrong inodes for the log files present on disk. As such, when filebeat starts again, an existing log file will appear to be a new file without an existing offset and its contents will be shipped a second time.

My repro script was run on a local ext4 file system on Ubuntu 14.04 running in a Virtualbox VM.

This might be an edge case not handled in https://github.com/elastic/beats/issues/1010

### PR DESCRIPTION
**Pull request by ruflin**
When multiple files were rotated at the same time, the first rotation was overwriting the states for the other rotated files. This happened because the new file directly had new content inside and the state for all the other files was fetched from disk, resetting the changes which were in memory.

The problem is now fixed by not writing the state to disk every time state changes are discovered by the registrar, as it is up to the prospector to decide if these changes are the most recent ones. Now changes get written to disk every time a scan is done. The downside of this solution is that the registrar is also updated, if no changes did happen.

* System test added to verify that issue is fixed
* Closes #1281

### CODE REVIEW

**Comment by tsg** [comment]
There are some test failures which might or might not be related.

**Comment by ruflin** [comment]
Windows errors are definitively related. I need to exclude these tests for windows as I check for the inode specifically. For Jenkins it is strange that the tests were working locally and on travis, but no Jenkins. Will look into it.

File: filebeat/crawler/prospector_log.go [hunk 1]
```diff
@@ -140,6 +140,9 @@ func (p *ProspectorLog) scanGlob(glob string) {
 		// Track the stat data for this file for later comparison to check for
 		// rotation/etc
 		p.prospectorList[h.Path] = *h.Stat
+		// TODO: Registrar now updated also if not changes happened. Improve efficiency here
```
Comment (andrewkroh) [inline filebeat/crawler/prospector_log.go]: `s/not/no/`

File: filebeat/crawler/registrar.go [hunk 2]
```diff
@@ -16,7 +17,8 @@ type Registrar struct {
 	// Path to the Registry File
 	registryFile string
 	// Map with all file paths inside and the corresponding state
-	State map[string]*FileState
+	State      map[string]*FileState
+	stateMutex *sync.Mutex
```
Comment (andrewkroh) [inline filebeat/crawler/registrar.go]: Seem like there is a mismatch in visibility here. The mutex and the data it protects should both be either exported or unexported.

File: filebeat/crawler/registrar.go [hunk 3]
```diff
@@ -209,3 +210,22 @@ func (r *Registrar) getPreviousFile(newFilePath string, newFileInfo os.FileInfo)
...
+	r.stateMutex.Lock()
+	defer r.stateMutex.Unlock()
+	state, exist := r.State[path]
+	return state, exist
+}
+
+func (r *Registrar) getFullState() map[string]*FileState {
+	r.stateMutex.Lock()
+	defer r.stateMutex.Unlock()
+	return r.State
```
Comment (andrewkroh) [inline filebeat/crawler/registrar.go]: The lock is not providing protection here. You would need to make a copy of `r.State` while holding the lock then return the copy. This assumes that the `FileState` objects are treated as immutable (if not then you need to make a deep copy).

File: filebeat/crawler/prospector_log.go (hunk 1 above)
Comment (ruflin) [inline filebeat/crawler/prospector_log.go]: fixed

File: filebeat/crawler/registrar.go (hunk 3 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: Fixed (hopefully)

File: filebeat/crawler/registrar.go (hunk 2 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: I made state private

File: filebeat/crawler/registrar.go [hunk 4]
```diff
@@ -74,7 +77,7 @@ func (r *Registrar) LoadState() {
 		defer existing.Close()
 		logp.Info("Loading registrar data from %s", r.registryFile)
 		decoder := json.NewDecoder(existing)
-		decoder.Decode(&r.State)
+		decoder.Decode(r.getFullState())
```
Comment (andrewkroh) [inline filebeat/crawler/registrar.go]: When you need to write the entire `r.State` you’ll need to acquire the lock here because you can no longer use `r.getFullState()` if it’s returning a copy.

File: filebeat/crawler/crawler.go [hunk 5]
```diff
@@ -56,7 +56,7 @@ func (c *Crawler) Start(prospectorConfigs []config.ProspectorConfig, eventChan c
 		go prospector.Run(&c.wg)
 	}
 
-	logp.Info("All prospectors are initialised and running with %d states to persist", len(c.Registrar.State))
+	//logp.Info("All prospectors are initialised and running with %d states to persist", len(c.Registrar.getFullState()))
```
Comment (urso) [inline filebeat/crawler/crawler.go]: why comment out? have at least debug level?

File: filebeat/crawler/registrar.go [hunk 6]
```diff
@@ -16,7 +17,8 @@ type Registrar struct {
 	// Path to the Registry File
 	registryFile string
 	// Map with all file paths inside and the corresponding state
-	State map[string]*FileState
+	state      map[string]*FileState
+	stateMutex *sync.Mutex
```
Comment (urso) [inline filebeat/crawler/registrar.go]: why pointer to mutex? Zero initialized sync.Mutex is already value. Advantage/Drawback of plain `sync.Mutex` is, it can not be copied (`go vet` will complain)

File: filebeat/crawler/registrar.go (hunk 4 above)
Comment (urso) [inline filebeat/crawler/registrar.go]: Consider fully protecting LoadState by mutex, as internal state is completely overwritten. getFullState() will make decoder.Decode overwrite internal state without holding the mutex

File: filebeat/crawler/registrar.go [hunk 7]
```diff
@@ -91,7 +94,7 @@ func (r *Registrar) Run() {
 			return
 		// Treats new log files to persist with higher priority then new events
 		case state := <-r.Persist:
-			r.State[*state.Source] = state
+			r.setState(*state.Source, state)
```
Comment (urso) [inline filebeat/crawler/registrar.go]: what's the type of 'Source'? Why is it a pointer?

Comment (urso) [inline filebeat/crawler/registrar.go]: is there a potential race between prospector and harvester overwriting the state for same source?

File: filebeat/crawler/prospector_log.go [hunk 8]
```diff
@@ -140,6 +140,9 @@ func (p *ProspectorLog) scanGlob(glob string) {
 		// Track the stat data for this file for later comparison to check for
 		// rotation/etc
 		p.prospectorList[h.Path] = *h.Stat
+		// TODO: Registrar now updated also if no changes happened. Improve efficiency here
+		// Update registrar
+		p.Prospector.registrar.Persist <- h.GetState()
```
Comment (urso) [inline filebeat/crawler/prospector_log.go]: what if we do not start an harvester for said file (e.g. due to ignore_older)?

As we require an active harvester here, maybe have harvester send initial event to registrar with offset 0?

File: filebeat/tests/system/test_registrar.py [hunk 9]
```diff
@@ -194,3 +195,76 @@ def test_rotating_file(self):
...
+    def test_rotating_file_inode(self):
+        """
+        Check that inodes are properly written during file rotation
+        """
+        self.render_config_template(
+            path=os.path.abspath(self.working_dir) + "/log/input*",
+            scan_frequency="1s"
+        )
+
+        if os.name == "nt":
```
Comment (andrewkroh) [inline filebeat/tests/system/test_registrar.py]: I think you need to special case SunOS too. See one of the earlier test cases in this file.

File: filebeat/crawler/registrar.go (hunk 4 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: @urso As Decode will only get a copy, this shouldn't be an issue anymore?

File: filebeat/crawler/crawler.go (hunk 5 above)
Comment (ruflin) [inline filebeat/crawler/crawler.go]: was not intentional. removed.

File: filebeat/crawler/registrar.go (hunk 6 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: Reason is that the official golang examples use a pointer. will remove it :-)

File: filebeat/crawler/registrar.go (hunk 7 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: That is older code. I think it does not matter, but would prefer to change it in a later PR to have as few changes as possible.

File: filebeat/crawler/prospector_log.go (hunk 8 above)
Comment (ruflin) [inline filebeat/crawler/prospector_log.go]: If we reach ignore_older, we don't need to update the state. So this shouldn't be an issue?

File: filebeat/tests/system/test_registrar.py (hunk 9 above)
Comment (ruflin) [inline filebeat/tests/system/test_registrar.py]: Saw this one, but it seems like st_ino inode is also available in SunOS, only st_dev is special.

File: filebeat/crawler/registrar.go (hunk 7 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: @urso I remove the pointer here as I think everything is based on a copy. Source is written in only one place.

**Comment by ruflin** [comment]
@urso @andrewkroh Seems to be finally stable. Will rebase and squash.

File: filebeat/crawler/registrar.go [hunk 10]
```diff
@@ -209,3 +210,34 @@ func (r *Registrar) getPreviousFile(newFilePath string, newFileInfo os.FileInfo)
...
+	state.Source = path
+}
+
+func (r *Registrar) getFullState() map[string]FileState {
+	r.stateMutex.Lock()
+	defer r.stateMutex.Unlock()
+
+	copy := make(map[string]FileState)
+	for k, v := range r.state {
+		copy[k] = *v
```
Comment (urso) [inline filebeat/crawler/registrar.go]: check out definition of FileState. The FileStateOS is not copied (only pointer). Is there a chance the content in FileStateOS can be overwritten when operations are run on this copy?

File: filebeat/crawler/registrar.go (hunk 4 above)
Comment (urso) [inline filebeat/crawler/registrar.go]: with r.getFullState being a copy, where do you store the results of decoder.Decode?

Comment (ruflin) [inline filebeat/crawler/registrar.go]: @urso Agree, changed it back.

Comment (ruflin) [inline filebeat/crawler/registrar.go]: @urso That raises the problem, that we actually don't have any tests that check if continue reading a file is done properly after restart.

File: filebeat/crawler/registrar.go (hunk 10 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: All occurence here except for Decode which happens only once at the begining, should be read only. So this should not be an issue right now, but I should still refactor and decouple it in the future to prevent potential problems.

Comment (andrewkroh) [inline filebeat/crawler/registrar.go]: Even though "Decode" happens once at startup, the method that does it, `LoadState`, is public and could be called at any time. The write operation within `LoadState` should be protected by the mutex.

Comment (ruflin) [inline filebeat/crawler/registrar.go]: Done. Lets see if it breaks something ;-)

File: filebeat/crawler/prospector_log.go (hunk 8 above)
Comment (urso) [inline filebeat/crawler/prospector_log.go]: still I wonder if prospector and harvester race for setting initial state

File: filebeat/harvester/harvester.go [hunk 11]
```diff
@@ -25,7 +26,8 @@ import (
 type Harvester struct {
 	Path               string /* the file path to harvest */
 	Config             *config.HarvesterConfig
-	Offset             int64
+	offset             int64
+	offsetLock         sync.Mutex
```
Comment (urso) [inline filebeat/harvester/harvester.go]: why still required? Due to prospector asking for state in order to forward to registrar?

File: filebeat/crawler/prospector_log.go (hunk 8 above)
Comment (ruflin) [inline filebeat/crawler/prospector_log.go]: Isn't the initial state set by LoadState? In case you are right and harvester and prospector would race for a state, worst case would be that an older state would be set than it actually is, but is overwritten with the correct state the next time state is written. That would be, in case filebeat is shut down at this moment, worst case would be to have some duplicated log lines?

Comment (ruflin) [inline filebeat/crawler/prospector_log.go]: BTW: I'm not happy at all how the state works at the moment, but I will do a heavier refactoring in master later, but want to keep this "backportable".

File: filebeat/harvester/harvester.go (hunk 11 above)
Comment (ruflin) [inline filebeat/harvester/harvester.go]: Yes, I hope to remove this in the future again.

File: filebeat/tests/system/test_prospector.py [hunk 12]
```diff
@@ -177,8 +177,8 @@ def test_exclude_files(self):
     def test_rotating_ignore_older_low_write_rate(self):
         self.render_config_template(
             path=os.path.abspath(self.working_dir) + "/log/*",
-            ignoreOlder="1s",
-            closeOlder="1s",
+            ignoreOlder="10s",
+            closeOlder="2s",
```
Comment (tsg) [inline filebeat/tests/system/test_prospector.py]: Just making sure, are these changes intentional?

Comment (ruflin) [inline filebeat/tests/system/test_prospector.py]: It is intentional, as in a previous version of the change the file was sometimes closed too fast. I will reset it to 1s again as I think with the most recent changes filebeat should be faster again with rotating files. But I renamed the tests to close_older instead of ignore_older as the name is not accurate anymore. It tests close_older. Will push a new commit.

File: CHANGELOG.asciidoc [hunk 13]
```diff
@@ -42,6 +42,7 @@ https://github.com/elastic/beats/compare/v5.0.0-alpha1...master[Check the HEAD d
 *Topbeat*
 
 *Filebeat*
+- Fix filebeat file rotation registrar issue {pull}1281[1281]
```
Comment (urso) [inline CHANGELOG.asciidoc]: Improvements in registrar dealing with file rotation.

File: filebeat/crawler/prospector_log.go [hunk 14]
```diff
@@ -228,6 +228,8 @@ func (p *ProspectorLog) checkExistingFile(h *harvester.Harvester, newFile *input
 
 			// Start a new harvester on the path
 			h.Start()
+			p.Prospector.registrar.Persist <- h.GetState()
```
Comment (urso) [inline filebeat/crawler/prospector_log.go]: while unlikely I always see a race between harvester and prospector in this construct:

1. start harvester
2. have prospector get harvester state (running in parallel)
3. send 'current' harvester state to registrar.

File: filebeat/crawler/registrar.go [hunk 15]
```diff
@@ -39,7 +41,7 @@ func NewRegistrar(registryFile string) (*Registrar, error) {
 func (r *Registrar) Init() error {
 	// Init state
 	r.Persist = make(chan *FileState)
-	r.State = make(map[string]*FileState)
+	r.state = make(map[string]*FileState)
```
Comment (urso) [inline filebeat/crawler/registrar.go]: on I side not, I came to dislike new/make and prefer `map[string]*FileState{}`.

File: filebeat/crawler/registrar.go [hunk 16]
```diff
@@ -138,12 +143,12 @@ func (r *Registrar) writeRegistry() error {
...
 
 	encoder := json.NewEncoder(file)
-	encoder.Encode(r.State)
+	encoder.Encode(r.getFullState())
 
 	// Directly close file because of windows
 	file.Close()
 
-	logp.Info("Registry file updated. %d states written.", len(r.State))
+	logp.Info("Registry file updated. %d states written.", len(r.getFullState()))
```
Comment (urso) [inline filebeat/crawler/registrar.go]: getFullState makes a copy holding a mutex. Consider saving to variable before line 146 and print saved copy here.

File: filebeat/crawler/registrar.go [hunk 17]
```diff
@@ -205,3 +208,34 @@ func (r *Registrar) getPreviousFile(newFilePath string, newFileInfo os.FileInfo)
...
+	return state, exist
+}
+
+func (r *Registrar) updateStateSource(state *FileState, path string) {
+	r.stateMutex.Lock()
+	defer r.stateMutex.Unlock()
+	state.Source = path
+}
+
+func (r *Registrar) getFullState() map[string]FileState {
```
Comment (urso) [inline filebeat/crawler/registrar.go]: naming, how about 'copyState' ?

File: filebeat/harvester/log.go [hunk 18]
```diff
@@ -237,25 +237,52 @@ func (h *Harvester) openFile() (encoding.Encoding, error) {
...
+	}
+
+	return &state
+}
+
+func (h *Harvester) SetOffset(offset int64) {
+	h.offsetLock.Lock()
+	defer h.offsetLock.Unlock()
+
+	h.offset = offset
```
Comment (urso) [inline filebeat/harvester/log.go]: just thinking, but wouldn't atomic.Store/Load be as good as mutex?

File: CHANGELOG.asciidoc (hunk 13 above)
Comment (ruflin) [inline CHANGELOG.asciidoc]: Changed

File: filebeat/tests/system/test_registrar.py [hunk 19]
```diff
@@ -37,6 +40,9 @@ def test_registrar_file_content(self):
                 "Processing 5 events"),
             max_timeout=15)
 
+        # Wait 2s to make sure the state is written once again
+        time.sleep(2)
```
Comment (urso) [inline filebeat/tests/system/test_registrar.py]: wait_until has configurable timeout, no? No need for sleep.

File: filebeat/crawler/prospector_log.go (hunk 14 above)
Comment (ruflin) [inline filebeat/crawler/prospector_log.go]: means it could happen that an old state is reported? Worst case: few lines are sent again?

File: filebeat/crawler/registrar.go (hunk 15 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: Changed. Can you add a note on why?

File: filebeat/crawler/registrar.go (hunk 16 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: Done

File: filebeat/crawler/registrar.go (hunk 17 above)
Comment (ruflin) [inline filebeat/crawler/registrar.go]: `getStateCopy()`

File: filebeat/harvester/log.go (hunk 18 above)
Comment (ruflin) [inline filebeat/harvester/log.go]: Should probably also work. Would it make a difference? If not, would keep it like this for the reason that it seems to working now and that it is hopefully removed anyways in the future ...

File: filebeat/tests/system/test_registrar.py [hunk 20]
```diff
@@ -207,3 +213,158 @@ def test_data_path(self):
...
+        """
+        Check that inodes are properly written during file rotation
+        """
+        self.render_config_template(
+            path=os.path.abspath(self.working_dir) + "/log/input*",
+            scan_frequency="1s"
+        )
+
+        if os.name == "nt":
+            raise SkipTest
```
Comment (urso) [inline filebeat/tests/system/test_registrar.py]: time for a introducing decorator in testsuite `@skip_os("nt")` ?

File: filebeat/crawler/prospector_log.go (hunk 14 above)
Comment (urso) [inline filebeat/crawler/prospector_log.go]: Well, h.GetState returns the state as known to harvester. Not state known to registrar or publisher. h.GetState might be well ahead of registrar as h.GetState() is harvesters internal state into how many bytes have I read. The registrars state on the other hand should be based on: how many bytes have I reported. If publish fails or takes longer, the harvesters state is well ahead of state in registrar. Not sure how likely this scenario is though

File: filebeat/tests/system/test_registrar.py (hunk 19 above)
Comment (ruflin) [inline filebeat/tests/system/test_registrar.py]: This is / was a little bit more complex as I had to make sure state was written again. But with the most recent change to only write state on changes, this is not required anymore. I improved it now by checking for the number of states written before adding line and having it occur more afterwards.

File: filebeat/tests/system/test_registrar.py (hunk 20 above)
Comment (ruflin) [inline filebeat/tests/system/test_registrar.py]: Yes, but not in this PR ;-)

File: filebeat/harvester/log.go (hunk 18 above)
Comment (urso) [inline filebeat/harvester/log.go]: just leave it as is.
