### PR TITLE
Metricbeat - Vsphere module - Fix Error collecting network_names 

### LINKED ISSUE #5961: Metricbeat - Vsphere module - Error collecting network_names
Collecting network_names for virtualmachine generate a log of messages:
[vsphere] error retrieving network from virtual machine: object references must have the same type

Related to #5732

### PR DESCRIPTION
**Pull request by amandahla**
The messages occurs because virtualmachine have "distributed port group" instead of "network". It was already fixed in "host" and now it was made the same in "virtualmachine".

Closes #5961

### CODE REVIEW

File: metricbeat/module/vsphere/virtualmachine/virtualmachine.go [hunk 1]
```diff
@@ -215,8 +215,20 @@ func getNetworkNames(c *vim25.Client, ref types.ManagedObjectReference) ([]strin
 		return nil, errors.Wrap(err, "no networks found")
 	}
 
+	networksRefs := []types.ManagedObjectReference{}
```
Comment (andrewkroh) [inline metricbeat/module/vsphere/virtualmachine/virtualmachine.go]: Use `var networkRefs types.ManagedObjectReferenc` instead. https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices

File: metricbeat/module/vsphere/virtualmachine/virtualmachine.go [hunk 2]
```diff
@@ -215,8 +215,20 @@ func getNetworkNames(c *vim25.Client, ref types.ManagedObjectReference) ([]strin
...
+	for _, obj := range vm.Network {
+		if obj.Type == "Network" {
+			networksRefs = append(networksRefs, obj)
+		}
+	}
+
+	// If only "Distributed port group" was found, for example.
+	if len(networksRefs) == 0 {
+		return nil, errors.Wrap(err, "no networks found")
```
Comment (andrewkroh) [inline metricbeat/module/vsphere/virtualmachine/virtualmachine.go]: I think you want `errors.New` instead of wrap because err == nil here. Same thing with the earlier errors.wrap usage.

**Comment by ruflin** [comment]
Could you add a changelog? I adjusted the title of the PR a bit.

File: metricbeat/module/vsphere/virtualmachine/virtualmachine.go (hunk 1 above)
Comment (amandahla) [reply metricbeat/module/vsphere/virtualmachine/virtualmachine.go]: Changed, thanks for the link!

File: metricbeat/module/vsphere/virtualmachine/virtualmachine.go (hunk 2 above)
Comment (amandahla) [reply metricbeat/module/vsphere/virtualmachine/virtualmachine.go]: Changed!

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@amandahla Could you rebase this PR on master?

**Comment by amandahla** [comment]
@ruflin Sure! Done :)

**Comment by ruflin** [comment]
@amandahla Just wanted to merge this but there is now a conflict in the CHANGELOG :-( Sorry. Can you rebase again?

**Comment by amandahla** [comment]
No problem! :)

**Comment by ruflin** [comment]
jenkins, test it
