### PR TITLE
Report status per unit

### LINKED ISSUE #35874: Errors loading inputs and outputs configured by the Elastic Agent should be reported per unit
Today when we encounter an error loading an input or output configuration send by the Elastic Agent we cannot associate that error with a specific input or integration. Instead we report the entire Beat component process as failed:

https://github.com/elastic/beats/blob/3325ba1caf101f17c2b822ad453a8053c2cad1be/x-pack/libbeat/management/managerV2.go#L627-L631

Instead of failing the entire component, errors should always be reported for the Unit representing the input configuration that failed. This can be done using the [UpdateState](https://github.com/elastic/elastic-agent-client/blob/f1e5cb50b0c8af2d56c0d2a29f29fef2bddcf15d/pkg/client/unit.go#L183) method of the Elastic Agent V2 client.

For outputs this should be straightforward because there is only one output unit today:

https://github.com/elastic/beats/blob/3325ba1caf101f17c2b822ad453a8053c2cad1be/x-pack/libbeat/management/managerV2.go#L591-L610

For inputs we will need to propagate the input unit ID into the Beats object reloaded, because each input configuration is consolidated into a single Beat configuration representing all inputs:

https://github.com/elastic/beats/blob/3325ba1caf101f17c2b822ad453a8053c2cad1be/x-pack/libbeat/management/managerV2.go#L747

Definition of Done:
* All input and output errors are reported using the UpdateState method for the correct configuration Unit over the agent control protocol.
* Input and output errors are associated with the correct units in the output of `elastic-agent status`.
* Input and output errors are associated with the correct inputs and integrations in the Fleet UI (seen https://github.com/elastic/kibana/issues/154634).

### PR DESCRIPTION
**Pull request by belimawr**
## What does this PR do?

This PR updates the ManagerV2 to set status per Unit based on its inputs. If any input on a Unit returns an error when starting the whole Unit is set as failed. If multiple inputs return an error, all errors are reported in the `Message` field.

If the output unit returns an error when starting, only the output Unit is set as failed. All other input unit states are not modified (this was the behaviour before this PR).

## Why is it important?

It allow users to better understand which unit has failed and which ones are working.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.
- [x] I have made my commit title and message explanatory about the purpose and the reason of the change

~~## Author's Checklist~~
## How to test this PR locally
1. Build a development version of the Elastic-Agent
2. Build Filebeat from this PR (from the `x-pack` folder)
3. Replace Filebeat's binary from the Elastic-Agent `components` sub folder by the one you built
4. Run the Elastic-Agent with a standalone policy and two input units, one must contain an error (use the policy below)
5. Run the status command: `./elastic-agent status --output full`
6. Only one input unit must report as `FAILED`.

<details><summary>elastic-agent.yml</summary>
<p>

```yaml
outputs:
  default:
    type: elasticsearch
    hosts:
      - https://localhost:9200
    username: "elastic"
    password: "changeme"
    ssl.verification_mode: none


inputs:
  - type: filestream
    id: input-1
    streams:
      - id: filestream-input-id-stream-block
        data_stream:
          dataset: generic
        paths:
          - /var/log/*.log
  - type: filestream
    id: input-2
    streams:
      - id: filestream-input-id-stream-block
        data_stream:
          dataset: generic
        pathsBroken:
          - /var/log/*.log

agent.monitoring:
  enabled: false
  logs: false
  metrics: false
```

</p>
</details> 

<details><summary>Expected output</summary>
<p>

```
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (DEGRADED) 1 or more components/units in a failed state
   ├─ info
   │  ├─ id: dde03f6c-733d-420b-b9b5-075923d14b9b
   │  ├─ version: 8.10.0
   │  └─ commit: f2e4f71775af532b0e256287829df41b6fd8a962
   └─ filestream-default
      ├─ status: (HEALTHY) Healthy: communicating with pid '1664568'
      ├─ filestream-default
      │  ├─ status: (HEALTHY) Healthy
      │  └─ type: OUTPUT
      ├─ filestream-default-input-1
      │  ├─ status: (HEALTHY) Healthy
      │  └─ type: INPUT
      └─ filestream-default-input-2
         ├─ status: (FAILED) no path is configured accessing config
         └─ type: INPUT
```

</p>
</details> 

## Related issues

- Closes #35874

~~## Use cases~~
~~## Screenshots~~
~~## Logs~~

### CODE REVIEW

**Comment by ycombinator** [comment]
Followed the instructions for testing this PR locally.  

## Before this PR

```
$ sudo elastic-agent status
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (DEGRADED) 1 or more components/units in a failed state
   └─ filestream-default
      ├─ status: (HEALTHY) Healthy: communicating with pid '92195'
      ├─ filestream-default
      │  └─ status: (FAILED) [failed to reload inputs: 1 error: Error creating runner from config: no path is configured accessing config]
      ├─ filestream-default-input-1
      │  └─ status: (FAILED) [failed to reload inputs: 1 error: Error creating runner from config: no path is configured accessing config]
      └─ filestream-default-input-2
         └─ status: (FAILED) [failed to reload inputs: 1 error: Error creating runner from config: no path is configured accessing config]
```

### With this PR

```
$ sudo elastic-agent status
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (DEGRADED) 1 or more components/units in a failed state
   └─ filestream-default
      ├─ status: (HEALTHY) Healthy: communicating with pid '93096'
      └─ filestream-default-input-2
         └─ status: (FAILED) no path is configured accessing config
```

In the output of `elastic-agent status` with this PR, I only saw `filestream-default-input-2`.  Shouldn't `filestream-default-input-1` also be included?

**Comment by ycombinator** [comment]
Thanks @belimawr, I did not run with `--output full` and will try that now.  

But I'm concerned that the output of `./elastic-agent status` before this PR shows both `filestream-default-input-1` and `filestream-default-input-2` whereas, with this PR, the same command's output shows only `filestream-default-input-2`.  This feels like a regression?

**Comment by ycombinator** [comment]
I tried `elastic-agent status --output full` and it looks good (see below)! 

However, I'm still concerned about the potential regression in the output of `elastic-agent status` (see [previous comment](https://github.com/elastic/beats/pull/36183#issuecomment-1660295408)).

## Before this PR

```
$ sudo elastic-agent status --output full
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (DEGRADED) 1 or more components/units in a failed state
   ├─ info
   │  ├─ id: e4197319-ce44-44c5-aff6-50aaa8456999
   │  ├─ version: 8.10.0
   │  └─ commit: b60b8b04c41f67a07958b59d18977ba0229bf233
   └─ filestream-default
      ├─ status: (HEALTHY) Healthy: communicating with pid '27711'
      ├─ filestream-default
      │  ├─ status: (FAILED) [failed to reload inputs: 1 error: Error creating runner from config: no path is configured accessing config]
      │  └─ type: OUTPUT
      ├─ filestream-default-input-1
      │  ├─ status: (FAILED) [failed to reload inputs: 1 error: Error creating runner from config: no path is configured accessing config]
      │  └─ type: INPUT
      └─ filestream-default-input-2
         ├─ status: (FAILED) [failed to reload inputs: 1 error: Error creating runner from config: no path is configured accessing config]
         └─ type: INPUT
```

## With this PR

```
$ sudo elastic-agent status --output full
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (DEGRADED) 1 or more components/units in a failed state
   ├─ info
   │  ├─ id: 627093e4-ad6b-4afd-8a50-a3cfa84d6190
   │  ├─ version: 8.10.0
   │  └─ commit: b60b8b04c41f67a07958b59d18977ba0229bf233
   └─ filestream-default
      ├─ status: (HEALTHY) Healthy: communicating with pid '27494'
      ├─ filestream-default
      │  ├─ status: (HEALTHY) Healthy
      │  └─ type: OUTPUT
      ├─ filestream-default-input-1
      │  ├─ status: (HEALTHY) Healthy
      │  └─ type: INPUT
      └─ filestream-default-input-2
         ├─ status: (FAILED) no path is configured accessing config
         └─ type: INPUT
```

**Comment by pierrehilbert** [comment]
In your last command, you have every input and not only the failing one @ycombinator.
Is it something that is not happening every time?

**Comment by ycombinator** [comment]
> In your last command, you have every input and not only the failing one @ycombinator. Is it something that is not happening every time?

`elastic-agent status --output full` is working as expected and is an improvement with this PR.  It's `elastic-agent status` that I'm concerned about — it feels like a regression to me (see https://github.com/elastic/beats/pull/36183#issuecomment-1660295408).

**Comment by belimawr** [comment]
> ```yaml
> inputs:
>   - type: filestream
>     id: input-1
>     streams:
>       - id: filestream-input-id-stream-block
>         data_stream:
>           dataset: generic
>         paths:
>           - /var/log/*.log
>   - type: filestream
>     id: input-2
>     streams:
>       - id: filestream-input-id-stream-block
>         data_stream:
>           dataset: generic
>         pathsBroken:
>           - /var/log/*.log
> ```

`./elastic-agent status` will only report units that are not healthy, because before this PR the status was reported per Beat, all units of a Beat would be marked as failed together even though not all had failed.

With this PR only the the failed units go into a unhealthy state, hence there is less units reported by `/elastic-agent status` when not all of them have failed.


An important thing to notice is that due to the Beats internals when the output fails to start the Beat will not start any input. Trying to start the log input with a failed output will deadlock, trying to start filestream with a failed output will not return an error but the input will never be fully started.

This behaviour was there before this PR.

If you have a failed output the status command will show this:
```
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (DEGRADED) 1 or more components/units in a failed state
   └─ filestream-default
      ├─ status: (HEALTHY) Healthy: communicating with pid '3196877'
      ├─ filestream-default
      │  └─ status: (FAILED) could not start output: failed to reload output: missing required field accessing 'elasticsearch.hosts'
      ├─ filestream-default-input-1
      │  └─ status: (STARTING) Starting
      └─ filestream-default-input-2
         └─ status: (STARTING) Starting
```

**Comment by ycombinator** [comment]
I see, thanks for clarifying @belimawr.  I missed the fact that the default value of `--output`, which is `human`, was always intended to show only non-healthy details.  In that case, the behavior with this PR for `elastic-agent status` is 👍.  I'll proceed to reviewing the code now...

File: libbeat/cfgfile/list.go [hunk 1]
```diff
@@ -137,6 +137,16 @@ func (r *RunnerList) Reload(configs []*reload.ConfigWithMeta) error {
 			} else {
 				r.logger.Errorf("Error creating runner from config: %s", err)
 			}
+
+			// If InputUnitID is not empty, then we're running under Elastic-Agent
+			// and we need to report the errors per unit.
+			if config.InputUnitID != "" {
```
Comment (ycombinator) [inline libbeat/cfgfile/list.go:143]: Just curious, because I'm not super familiar with this code, why not always report errors per unit, i.e. what is this conditional buying us?

File: libbeat/cfgfile/list.go [hunk 2]
```diff
@@ -226,3 +236,16 @@ func createRunner(factory RunnerFactory, pipeline beat.PipelineConnector, cfg *r
...
 	return factory.Create(pipetool.WithDynamicFields(pipeline, cfg.Meta), c)
 }
+
+type UnitError struct {
+	UnitID string
+	Err    error
+}
+
+func (u UnitError) Error() string {
+	return u.Err.Error()
```
Comment (ycombinator) [inline libbeat/cfgfile/list.go:246]: Would it be helpful to include `u.UnitID` (if it's not empty) in the returned string?

File: x-pack/libbeat/management/managerV2.go [hunk 3]
```diff
@@ -605,59 +621,59 @@ func (cm *BeatV2Manager) reload(units map[unitKey]*client.Unit) {
...
 		_ = unit.UpdateState(client.UnitStateStopped, "Stopped", nil)
 	}
 
-	// any error during reload changes the whole state of the beat to failed
-	if len(errs) > 0 {
-		cm.status = lbmanagement.Failed
-		cm.message = fmt.Sprintf("%s", errs)
-	}
-
 	// now update the statuses of all units
```
Comment (ycombinator) [inline x-pack/libbeat/management/managerV2.go:665]: Not part of this PR but just noticed it during the review.  This should probably say "all inputs" or "all input units".

File: libbeat/cfgfile/list.go (hunk 1 above)
Comment (ycombinator) [reply libbeat/cfgfile/list.go:143]: Or, put differently, in what scenario / code path do we expect `config.InputUnitID` to be empty?

Comment (belimawr) [reply libbeat/cfgfile/list.go:143]: `config.InputUnitID` is empty if it is a standalone Filebeat. Only the Elastic-Agent sets the input unit ID.

My goal here was to keep the behaviour unchanged when running a standalone Filebeat. Maybe I'm being over cautious here, I'll give it some thought.

File: libbeat/cfgfile/list.go (hunk 2 above)
Comment (belimawr) [reply libbeat/cfgfile/list.go:246]: Not realy, a Unit can have multiple inputs, so it's not even a direct mapping also when the error is reported by the Elastic-Agent it is already under the context of an input, so it makes the information redundant and the error text longer.

I created this type only to be able to "bubble up" the error linked to the Unit so the ManagerV2 can properly handle it, I also wanted to keep the final error message untouched.

File: x-pack/libbeat/management/managerV2.go (hunk 3 above)
Comment (belimawr) [reply x-pack/libbeat/management/managerV2.go:665]: I'll rephrase the whole thing, I believe it can be more clear in general.

**Review by ycombinator — APPROVED** [review]
LGTM.
