### PR TITLE
fix(filebeat): prevent CrowdStrike refresh spin loops for short intervals   

### LINKED ISSUE #49158: [bug-hunter] CrowdStrike follower spins refresh loop when server interval is under 5 minutes
## Impact
Filebeat's CrowdStrike streaming input can flood the refresh endpoint with requests when CrowdStrike returns `refreshActiveSessionInterval < 300` seconds. This creates high request volume, noisy failures, and can degrade ingestion stability.

## Reproduction Steps
1. Add this minimal test to `x-pack/filebeat/input/streaming/crowdstrike_refresh_repro_test.go`:
```go
package streaming

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"sync/atomic"
	"testing"
	"time"

	"github.com/elastic/elastic-agent-libs/logp"
	"github.com/elastic/elastic-agent-libs/monitoring"
	"github.com/stretchr/testify/require"
)

func TestFollowSessionRefreshIntervalDoesNotSpinWhenBelowGrace(t *testing.T) {
	var refreshCalls atomic.Int32

	mux := http.NewServeMux()
	server := httptest.NewServer(mux)
	defer server.Close()

	mux.HandleFunc("/discover", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = fmt.Fprintf(w, `{"resources":[{"dataFeedURL":%q,"sessionToken":{"token":"tok","expiration":"2026-01-01T00:00:00Z"},"refreshActiveSessionURL":%q,"refreshActiveSessionInterval":1}]}`,
			server.URL+"/feed", server.URL+"/refresh")
	})
	mux.HandleFunc("/feed", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
	mux.HandleFunc("/refresh", func(w http.ResponseWriter, r *http.Request) {
		refreshCalls.Add(1)
		w.WriteHeader(http.StatusOK)
	})

	logger := logp.NewLogger("test")
	s := &falconHoseStream{
		discoverURL: server.URL + "/discover",
		plainClient: server.Client(),
		status:      noopReporter{},
		processor: processor{
			ns:      "falcon_hose",
			log:     logger,
			metrics: newInputMetrics(monitoring.NewRegistry(), logger),
		},
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	_, err := s.followSession(ctx, server.Client(), map[string]any{"cursor": map[string]any{}})
	require.NoError(t, err)

	time.Sleep(120 * time.Millisecond)
	cancel()
	time.Sleep(20 * time.Millisecond)

	require.Equal(t, int32(0), refreshCalls.Load(), "refresh loop should not run before configured interval")
}
```
2. Run:
```bash
go test ./x-pack/filebeat/input/streaming -run TestFollowSessionRefreshIntervalDoesNotSpinWhenBelowGrace -count=1
```

## Expected vs Actual
**Expected:** No refresh request should be sent within 120ms when interval is 1s.

**Actual:** The refresh goroutine loops immediately and issued >1000 refresh requests in ~120ms.

Observed output:
```text
--- FAIL: TestFollowSessionRefreshIntervalDoesNotSpinWhenBelowGrace (0.14s)
    crowdstrike_refresh_repro_test.go:59:
        Error:          Not equal:
                        expected: 0
                        actual  : 1082
        Messages:       refresh loop should not run before configured interval
```

## Failing Test
See reproduction test above (`crowdstrike_refresh_repro_test.go`).

## Evidence
- `x-pack/filebeat/input/streaming/crowdstrike.go:236-244` computes `refreshAfter := time.Duration(r.RefreshAfter) * time.Second` and waits on `time.After(refreshAfter - grace)` with `grace = 5 * time.Minute`.
- For any server-provided interval `< 5m`, duration becomes negative, so `time.After` fires immediately and repeats in a tight loop.

---
[What is this?](https://ela.st/github-ai-tools) | [From workflow: Bug Hunter](https://github.com/elastic/beats/actions/runs/22469568718)

Give us feedback! React with 🚀 if perfect, 👍 if helpful, 👎 if not.
> - [x] expires  on Mar 6, 2026, 2:09 AM UTC

### PR DESCRIPTION
**Pull request by andrewkroh**
## Proposed commit message

```                                                                                                                                                                                                                                                                                                                                              
In the Filebeat streaming input, fix a CrowdStrike follower bug where
refreshActiveSessionInterval values below the 5-minute grace window produced
negative refresh waits and caused immediate, repeated refresh requests. Refresh
scheduling now computes the next refresh at 90% of the server interval and
applies a 15-second minimum delay for short/invalid values, so the follower
honors server cadence without tight-looping.

Add regression coverage for both scheduling math and loop execution behavior:
- TestRefreshSessionWait validates the 90% scheduling rule and 15-second floor
  across long, short, and invalid intervals.
- TestFollowSessionRefreshDoesNotSpinForShortIntervals verifies the refresh
  loop does not fire early and only refreshes when the timer is triggered,
  without relying on sleep-based timing assertions.

Fixes #49158
```

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent-changelog-tool/blob/main/docs/usage.md).

## Related issues

- Fixes #49158

### CODE REVIEW

File: x-pack/filebeat/input/streaming/crowdstrike_test.go [hunk 1]
```diff
@@ -111,6 +119,111 @@ func TestCrowdstrikeFalconHose(t *testing.T) {
...
+	}
+
+	cancel()
+	select {
+	case <-done:
+	case <-time.After(time.Second):
+		t.Fatal("timed out waiting for refresh loop shutdown")
+	}
+}
+func TestRefreshSessionWait(t *testing.T) {
```
Comment (efd6) [inline x-pack/filebeat/input/streaming/crowdstrike_test.go:188]: `gofumpt`
