### PR TITLE
[filebeat][httpjson][bugfix] - root request pagination now working with chaining

### LINKED ISSUE #32618: [HTTP Json Chain Call] Fix Pagination not working at the root request level when used with chaining
**Describe the enhancement:**
While using the chain call in HTTP JSON input, we cannot use the body of the first call. Also, in pagination, the chain call is not working, only giving the response from the first request, the second call is not happening.

**Describe an enhancement for Pagination in chain call:**
we came across an issue while using the chained calls feature that is introduced in filebeat recently. In our case, we wanted to make an API call that would fetch a paginated list of IDs and we need to iterate through those IDs in order to get their details. However, we were not able to use pagination on chained calls. We are unable to access the body of the first page. 

```
**Example**

First call
{
	items:[
	      Id: 1
              Id: 2
              Id: 3
              Id: 4
              Id: 5]	
        nextLink: “”
}
Chain Call
           Second Call Output_id-1
           Second Call Output_id-2
           Second Call Output_id-3
           Second Call Output_id-4
           Second Call output_id-5
```

In this example, the first call collects all the ids and the second call gives the detail of all the ids. And for the pagination, we have to use the nextLink, that is present in the body of the first call.

In our case, for pagination, we have to use the nextLink that is present in the body of the first call. We saw that there is no way to use the body of the first call. We need to access the body of the first call.

If we are using the last_response element, we shaw it will give the response of the first id of the second call(Output_id-1). In this scenario, we have tested the mock server.

In pagination, we shaw that it will call every time only the first call, the second call did not happen in this pagination section.

Moreover, Pagination and Chained calls are working fine individually, but it fails when combined. 
we are not able to use the body of the first call in pagination. And also when we found that in pagination the chain request is not happening, every they call the first call and give the response of list of IDs.

Found while investigating, we saw that in the https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/httpjson/pagination.go#L141, they iterate the first request every time. In this function, we have to call chain requests in this function.

### PR DESCRIPTION
**Pull request by ShourieG**
## Type of change
- Bug Fix

## What does this PR do?

1)  Each chain request factory now have their own response processor & paginator & individual transform context
2) Fixes root level pagination , when used with chaining 
3) Keeps existing logic, tests intact and does not cause any breaking change.

## Old Behaviour vs New Behaviour and what process was used to fix it
Previously when chaining was used along with pagination at the root request , the pagination client would infinitely loop on the 1st chain chain request and would keep giving the same output over and over. Reasons for this behaviour are as follows :- 

 - The chain steps used the response processor  that belonged to the root request. 
 - The chain steps used the same transform context that belonged to the root request.

**Solution  Step 1 :**  
To fix the above issues , a new instance of a response processor was introduced per chain step & a new transform context
was created for every chain , which only inherited the cursor from the parent transform request. This change resolved the infinite loop issue and also laid the foundation for having pagination per chain step , if it is to be implemented in future. But this revealed another underlying issue : - 
 
- There was no way of processing pagination responses via chaining once the initial response from the root request was 
 processed. This is how the initial code was implemented. Once the initial root request was processed , the response was lost , and the chain steps only executed the uri's created from the id's extracted from that response.  There was no pagination happening any further for that response.
 
**Solution Step 2:**  
- The initial response is cloned and kept for later use .
- Once the chain is executed as usual for the 1st response page, a newly introduced  func: **processRemainingChainEvents** 
  uses the saved initial response and paginates on it.
- Now each pagination response (except the 1st, since it has already been processed) gets encoded into a http response 
  and is passed through each of the chain steps until pagination stops or is terminated.
   
This solution keeps the existing structure and tests intact , while solving this problem.

## Why is it important?

Unblocks many integrations using pagination at the root request level combined with chaining. Also the solution is not the most elegant , but it avoids any breaking changes.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` .

## Author's Checklist
- [x]  Code structure , syntax & comments
- [x]  Code optimization & quality

## Related issues

- Closes #32618 

## Screenshots
Trend Micro Api - calls 
**Page 1 :** 
Screenshot 2022-08-17 at 2 06 10 PM

**Page 2:** 
Screenshot 2022-08-17 at 2 07 00 PM

** Filebeat Output: All 13 results**
Screenshot 2022-08-17 at 2 12 49 PM

## Logs

This is a sample log using the Trend Micro Vision One api - there are a total of 13 events , 10 on the 1st page and 3 on the 2nd page . 

output confirmation for all 13 events :- 

{"log.level":"info","@timestamp":"2022-08-17T14:00:30.712+0530","log.logger":"input.httpjson-stateless","log.origin":{"file.name":"httpjson/request.go","file.line":392},"message":"request finished: 13 events published","service.name":"filebeat","id":"97C59434EFB234D9","input_url":"https://api.in.xdr.trendmicro.com/v3.0/workbench/alerts","ecs.version":"1.6.0"}

### CODE REVIEW

File: x-pack/filebeat/input/httpjson/request.go [hunk 1]
```diff
@@ -424,11 +471,190 @@ func (r *requester) processAndPublishEvents(stdCtx context.Context, trCtx *trans
...
 		trCtx.updateCursor()
+
 		n++
 	}
 	return n
 }
 
+// processAndPublishChainEvents processes and publishes chain events based on response type,
+// this separate func has been introduced , since each chain step now has its own response processor and paginator
+func processAndPublishChainEvents(stdCtx context.Context, trCtx *transformContext, chainRsp *responseProcessor, publisher inputcursor.Publisher, finalResps []*http.Response, publish bool, log *logp.Logger) int {
```
Comment (efd6) [inline x-pack/filebeat/input/httpjson/request.go:482]: The body of this is almost identical to `*requester.processAndPublishEvents`. The common code should be factored out. I would say that there is only a need for one, which takes `events` and `log`. In the case that currently calls `*requester.processAndPublishEvents` then becomes `shinyNewProcessAndPublishEvents(stdCtx, chainTrCtx, events, rf.chainResponseProcessor, publisher, resps, i < len(r.requestFactories), r.log)`, where `events` is made depending on context.

**Review by efd6 — COMMENTED** [review]
Initial review.

It would be helpful if there were a summary of the cause of the old behaviour in the PR description and the appoach that was taken to address the issue. This summary can then be used as the basis for the squash commit message when this is merged.

File: x-pack/filebeat/input/httpjson/request.go [hunk 2]
```diff
@@ -294,19 +306,42 @@ func (r *requester) doRequest(stdCtx context.Context, trCtx *transformContext, p
...
 				continue
 			}
+
+			// if flow of control reaches here , that means there are more than 1 request factories
+			// if a pagination request factory at the root level and a chain step exists , only then we will initialize flags & variables
+			// which are required for chaining with pagination
+			if r.requestFactories[i+1].isChain && r.responseProcessors[i].pagination.requestFactory != nil {
+				isChainExpected = true
+				chainIndex = i + 1
+				resp, err := cloneResponse(httpResp) //nolint:bodyclose // Bad linter! The response body will always be closed by drainBody function.
```
[the remark this answers is not in the document]
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go:316]: acknowledged

File: x-pack/filebeat/input/httpjson/response.go [hunk 3]
```diff
@@ -95,6 +95,38 @@ func newResponseProcessor(config config, pagination *pagination, log *logp.Logge
 	return rps
 }
 
+func newChainResponseProcessor(config chainConfig, pagination *pagination, log *logp.Logger) *responseProcessor {
+	rp := &responseProcessor{
+		pagination: pagination,
```
[the remark this answers is not in the document]
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/response.go:100]: will make these changes

**Comment by ShourieG** [comment]
> It would be helpful if there were a summary of the cause of the old behaviour in the PR description and the appoach that was taken to address the i



> Initial review.
> 
> It would be helpful if there were a summary of the cause of the old behaviour in the PR description and the appoach that was taken to address the issue. This summary can then be used as the basis for the squash commit message when this is merged.

@efd6 have updated the PR with the summary (old behaviour vs new behaviour)

File: x-pack/filebeat/input/httpjson/request.go (hunk 1 above)
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go]: have fixed this

File: x-pack/filebeat/input/httpjson/request.go [hunk 4]
```diff
@@ -358,13 +401,17 @@ func (r *requester) getIdsFromResponses(intermediateResps []*http.Response, repl
...
 		if resp.Body != nil {
 			b, err = io.ReadAll(resp.Body)
 			if err != nil {
 				return nil, fmt.Errorf("error while reading response body: %w", err)
 			}
 		}
+		// gracefully close response
+		err = resp.Body.Close()
+		if err != nil {
+			return nil, fmt.Errorf("error closing response body : %w", err)
```
[the remark this answers is not in the document]
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go]: done

File: x-pack/filebeat/input/httpjson/request.go [hunk 5]
```diff
@@ -294,19 +306,42 @@ func (r *requester) doRequest(stdCtx context.Context, trCtx *transformContext, p
 				n = r.processAndPublishEvents(stdCtx, trCtx, publisher, finalResps, true, i)
 				continue
 			}
+
+			// if flow of control reaches here , that means there are more than 1 request factories
```
[the remark this answers is not in the document]
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go]: done

File: x-pack/filebeat/input/httpjson/request.go [hunk 6]
```diff
@@ -130,48 +131,54 @@ func newRequestFactory(ctx context.Context, config config, log *logp.Logger) ([]
...
+			httpClient, err := newChainHTTPClient(ctx, ch.While.Auth, ch.While.Request, log, policy)
 			if err != nil {
 				return nil, fmt.Errorf("failed in creating chain http client with error : %w", err)
 			}
 			if ch.While.Auth != nil && ch.While.Auth.Basic.isEnabled() {
 				rf.user = ch.While.Auth.Basic.User
 				rf.password = ch.While.Auth.Basic.Password
 			}
+			pagination := newChainPagination(ch, httpClient, log)
+			responseProcessor := newChainResponseProcessor(ch, pagination, log)
```
[the remark this answers is not in the document]
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go]: done

File: x-pack/filebeat/input/httpjson/request.go [hunk 7]
```diff
@@ -130,48 +131,54 @@ func newRequestFactory(ctx context.Context, config config, log *logp.Logger) ([]
...
+			httpClient, err := newChainHTTPClient(ctx, ch.Step.Auth, ch.Step.Request, log)
 			if err != nil {
 				return nil, fmt.Errorf("failed in creating chain http client with error : %w", err)
 			}
 			if ch.Step.Auth != nil && ch.Step.Auth.Basic.isEnabled() {
 				rf.user = ch.Step.Auth.Basic.User
 				rf.password = ch.Step.Auth.Basic.Password
 			}
+			pagination := newChainPagination(ch, httpClient, log)
+			responseProcessor := newChainResponseProcessor(ch, pagination, log)
```
[the remark this answers is not in the document]
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go]: done

File: x-pack/filebeat/input/httpjson/pagination.go [hunk 8]
```diff
@@ -65,6 +65,12 @@ func newPagination(config config, httpClient *httpClient, log *logp.Logger) *pag
 	return pagination
 }
 
+func newChainPagination(config chainConfig, httpClient *httpClient, log *logp.Logger) *pagination {
+	pagination := &pagination{httpClient: httpClient, log: log}
+
+	return pagination
+}
```
[the remark this answers is not in the document]
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/pagination.go:72]: addressed

[the remark this answers is not in the document]
Comment (efd6) [reply x-pack/filebeat/input/httpjson/pagination.go:72]: I don't think we need this, it's only called from one site and doesn't do any validation. I would replace the call with `&pagination{httpClient: httpClient, log: log}`.

File: x-pack/filebeat/input/httpjson/request.go (hunk 1 above)
Comment (efd6) [reply x-pack/filebeat/input/httpjson/request.go]: I'd place the events parameter earlier in the signature since it's the focus of the function (only after the contexts because of the context first convention). To avoid the issue of long code inserted into the caller assign to a var and use that.

File: x-pack/filebeat/input/httpjson/request.go [hunk 9]
```diff
@@ -276,37 +283,65 @@ func (r *requester) doRequest(stdCtx context.Context, trCtx *transformContext, p
...
-			httpResp, err = rf.collectResponse(stdCtx, trCtx, r) //nolint:bodyclose // Bad linter! The response body will always be closed by drainBody function.
+			httpResp, err = rf.collectResponse(stdCtx, trCtx, r)
 			if err != nil {
 				return fmt.Errorf("failed to execute rf.collectResponse: %w", err)
 			}
 			if len(r.requestFactories) == 1 {
-				finalResps = append(finalResps, httpResp) //nolint:bodyclose // Bad linter! The response body will always be closed by drainBody function.
-				n = r.processAndPublishEvents(stdCtx, trCtx, publisher, finalResps, true, i)
+				finalResps = append(finalResps, httpResp)
+				n = processAndPublishEvents(trCtx, publisher, true, r.log, r.responseProcessors[i].startProcessing(stdCtx, trCtx, finalResps))
```
Comment (efd6) [inline x-pack/filebeat/input/httpjson/request.go:305]: With the change noted above.
```suggestion
				events := r.responseProcessors[i].startProcessing(stdCtx, trCtx, finalResps)
				n = processAndPublishEvents(trCtx, events, publisher, true, r.log)
```

File: x-pack/filebeat/input/httpjson/request.go [hunk 10]
```diff
@@ -276,37 +283,65 @@ func (r *requester) doRequest(stdCtx context.Context, trCtx *transformContext, p
...
+			}
+			intermediateResps = append(intermediateResps, httpResp)
 			ids, err = r.getIdsFromResponses(intermediateResps, r.requestFactories[i+1].replace)
 			if err != nil {
 				return err
 			}
-			n = r.processAndPublishEvents(stdCtx, trCtx, publisher, intermediateResps, false, i)
+			// we will only processAndPublishEvents here if chains do not exist, inorder to avoid unnecessary pagination
+			if !isChainExpected {
+				n = processAndPublishEvents(trCtx, publisher, false, r.log, r.responseProcessors[i].startProcessing(stdCtx, trCtx, finalResps))
```
Comment (efd6) [inline x-pack/filebeat/input/httpjson/request.go:328]:
```suggestion
				events := r.responseProcessors[i].startProcessing(stdCtx, trCtx, finalResps)
				n = processAndPublishEvents(trCtx, events, publisher, false, r.log)
```

File: x-pack/filebeat/input/httpjson/request.go [hunk 11]
```diff
@@ -341,11 +376,20 @@ func (r *requester) doRequest(stdCtx context.Context, trCtx *transformContext, p
 				}
 				resps = intermediateResps
 			}
-			n += r.processAndPublishEvents(stdCtx, trCtx, publisher, resps, i < len(r.requestFactories), i)
+
+			if rf.isChain {
+				n += processAndPublishEvents(trCtx, publisher, i < len(r.requestFactories), r.log, rf.chainResponseProcessor.startProcessing(stdCtx, trCtx, resps))
+			} else {
+				n += processAndPublishEvents(trCtx, publisher, i < len(r.requestFactories), r.log, r.responseProcessors[i].startProcessing(stdCtx, trCtx, resps))
+			}
```
Comment (efd6) [inline x-pack/filebeat/input/httpjson/request.go:384]:
```suggestion
			var events chan maybeMsg 
			if rf.isChain {
				events = rf.chainResponseProcessor.startProcessing(stdCtx, trCtx, resps)
			} else {
				events = r.responseProcessors[i].startProcessing(stdCtx, trCtx, resps)
			}
			n += processAndPublishEvents(trCtx, events, publisher, i < len(r.requestFactories), r.log)
```

File: x-pack/filebeat/input/httpjson/pagination.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/pagination.go:72]: @efd6 this was done with the intention that in future when we add support for pagination within chain blocks , we could expand upon the existing method , would like to hear your opinion on that approach.

[the remark this answers is not in the document]
Comment (efd6) [reply x-pack/filebeat/input/httpjson/pagination.go:72]: Until it's needed for doing that, it doesn't really need to be here. There is only one site that it's called at, so it will be easy to add when the time comes.

**Comment by ShourieG** [comment]
@efd6 have updated the PR with all the recommended changes .

File: x-pack/filebeat/input/httpjson/request.go [hunk 12]
```diff
@@ -341,11 +378,22 @@ func (r *requester) doRequest(stdCtx context.Context, trCtx *transformContext, p
...
+			if rf.isChain {
+				events = rf.chainResponseProcessor.startProcessing(stdCtx, trCtx, resps)
+			} else {
+				events = r.responseProcessors[i].startProcessing(stdCtx, trCtx, resps)
+			}
+			n += processAndPublishEvents(trCtx, events, publisher, i < len(r.requestFactories), r.log)
 		}
 	}
 
 	defer httpResp.Body.Close()
```
Comment (efd6) [inline x-pack/filebeat/input/httpjson/request.go:392]: Do you know why this is here? I think it is a relic from before the step processing was added and there was only a single response to deal with. Do you think it is reasonable to remove it? (Probably not in this change).

**Review by efd6 — COMMENTED** [review]
Is there a new test for this?

File: x-pack/filebeat/input/httpjson/request.go (hunk 12 above)
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go:392]: @efd6 Unfortunately there are no tests for the chain requests as a whole , whenever it was written ,  it was done so without tests for the actual request cycle. They will need to be introduced from scratch. As for the **defer httpResp.Body.Close()** , it is definitely an artifact of the past, but sadly the last instance of the response body still remains open so we definitely need to defer this / or close gracefully , hence we cannot remove this atm without changing how the code works.

Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go:392]: **Added tests for this scenario**

Comment (efd6) [reply x-pack/filebeat/input/httpjson/request.go:392]: > the last instance of the response body still remains open so we definitely need to defer this / or close gracefully , hence we cannot remove this atm without changing how the code works.

I don't think this is the case; the body is always a product of `*httpClient.do` which always dumps the body into a `*bytes.Buffer` wrapped in an `io.nopCloser` on success, or closing in the case of a failure during the copy (or it returns an `http.NoBody` if empty). So all the closes of the body after `*httpClient.do` returns are futile. The reason to close a resp is to free the netconn, but that has already happened.

**Review by efd6 — APPROVED** [review]

File: x-pack/filebeat/input/httpjson/request.go (hunk 12 above)
Comment (ShourieG) [reply x-pack/filebeat/input/httpjson/request.go:392]: yea , my bad .. just saw the client.do & the drain body methods in detail and the connections are always released. Then it doesn't matter if **httpResp.Body.Close()** is there or not, we could just remove it.
