### PR TITLE
Fix Winlogbeat escaping CRLF sequences

### LINKED ISSUE #11328: winlogbeat 6.6.2 sends utf-16 control codes (carriage return, line feed, tab)
winlogbeat version 6.6.2 x86_64
OS: Windows 10, Windows Server 2008R2
expected output: for multiline Windows event logs, "message" should have \n or \t
actual output: "message" field contains, e.g.,

 "message" => "Special privileges assigned to new logon.\\u000d\\u000a\\u000d\\u000aSubject:\\u000d\\u000a\\u0009Security ID:\\u0009\\u0009S-1-5-18\\u000d\\u000a\\u0009Account Name:\\u0009\\u0009SYSTEM\\u000d\\u000a\\u0009Account Domain:\\u0009\\u0009NT AUTHORITY\\u000d\\u000a\\u0009Logon ID:\\u0009\\u00090x3E7\\u000d\\u000a\\u000d\\u000aPrivileges:\\u0009\\u0009SeAssignPrimaryTokenPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeTcbPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeSecurityPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeTakeOwnershipPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeLoadDriverPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeBackupPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeRestorePrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeDebugPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeAuditPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeSystemEnvironmentPrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeImpersonatePrivilege\\u000d\\u000a\\u0009\\u0009\\u0009SeDelegateSessionUserImpersonatePrivilege",

=====================

To reproduce:

download any other version of winlogbeat, unzip, copy to c:\program files\winlogbeat, run install ps1 file. start/stop winlogbeat service to ensure everything works. rename winlogbeat to winlogbeat-<version>.

with service stopped, download 6.6.1, unzip, copy to c:\program files\winlogbeat. copy in winlogbeat.yml. start-service winlogbeat.

=====================

relevant winlogbeat.yml config:

```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
  - name: Security
  - name: System
output.logstash:
  hosts: ["192.168.1.9:5044"]
processors:
- add_host_metadata:
    netinfo.enabled: true
```

=====================

192.168.1.9 is a logstash 6.6.x instance (tested with 6.6.1 and 6.6.2). logstash config is:

```
input { beats { port => 5044 } }
filter { }
output { if [event_id] in [4624, 4672] { stdout { codec => rubydebug } } }
```

### PR DESCRIPTION
**Pull request by adriansr**
Previous fix (#11006) made Winlogbeat escape CRLF control characters, which are expected in Windows event logs.

Fixes #11328

### CODE REVIEW

File: winlogbeat/sys/event_test.go [hunk 1]
```diff
@@ -168,21 +169,13 @@ func TestXML(t *testing.T) {
...
-      <Message>じゃあ宇宙カウボーイ。。。%s</Message>
-    </Operation_ClientFailure>
-  </UserData>
-</Event>
-`, "\x1b")
-	_, err := UnmarshalEventXML([]byte(eventXML))
-	if !assert.NoError(t, err) {
-		assert.Equal(t, err.Error(), "XML syntax error on line 6: illegal character code U+001B")
-	}
+	evXML := strings.Replace(allXML, "%1", "&#xD;\n\x1b", -1)
```
Comment (andrewkroh) [inline winlogbeat/sys/event_test.go]: I think including other whitespace characters would be good too since `\t` is used a lot in event logs.

Comment (andrewkroh) [reply winlogbeat/sys/event_test.go]: What was the story with the `\r`? I see you had to use `&#xD;`. Is it because of https://www.w3.org/TR/REC-xml/#sec-line-ends?

File: winlogbeat/tests/system/test_wineventlog.py [hunk 2]
```diff
@@ -388,3 +388,27 @@ def test_processors(self):
...
+Logon ID:  0x3e7
+Logon Process Name:  IKE"""
+        self.write_event_log(msg)
+        evts = self.read_events()
+        self.assertTrue(len(evts), 1)
+        self.assertEqual(unicode(self.api), evts[0]["winlog.api"], evts[0])
+        self.assertNotIn("event.original", evts[0], evts[0])
+        self.assertIn("message", evts[0], evts[0])
+        self.assertNotIn("\\u000a", evts[0]["message"])
+        self.assertEqual(unicode(msg), evts[0]["message"].decode('unicode-escape'), evts[0])
```
Comment (andrewkroh) [inline winlogbeat/tests/system/test_wineventlog.py]: Need to read some python docs before I can fully understand this stuff. But I get the gist.

File: winlogbeat/sys/event_test.go (hunk 1 above)
Comment (adriansr) [reply winlogbeat/sys/event_test.go]: Yep, the XML parser was getting rid of it.

**Comment by adriansr** [comment]
jenkins, test this
