### PR TITLE
[Azure] Sanitize message in case of malformed json

### LINKED ISSUE #34092: [azure-evenhub input] fail to process AppServicePlatformLogs due to unescaped newlines
- Version:  any
- Operating System: any

Some events from the `AppServicePlatformLogs` log category can contain one or more newline characters (`\n`).

Here's an example received export from a Diagnostic Setting to an Event Hub:

```"{\"records\": [{ \"time\": \"2022-12-17T20:21:24.4331338Z\", \n \"resourceId\": \"/SUBSCRIPTIONS/5AEB8557-CAB7-41AC-8603-9F94AD233EFC/RESOURCEGROUPS/GT-WEU-GTP-CORE-DEV-RSG/PROVIDERS/MICROSOFT.WEB/SITES/AppService-Redacted\", \"category\": \"AppServicePlatformLogs\", \"operationName\": \"AutoHealingLogEvent\", \"level\": \"Informational\", \"resultDescription\": \"Worker Process serving application pool 'AppService-Redacted' hit the 'Total Requests' limit.\\n\", \"properties\": {\"message\":\"Worker Process serving application pool 'AppService-Redacted' hit the 'Total Requests' limit.\n\"}}]}"```

The `message` attribute contains a `\n` in this example. 

Then this string is unmarshaled, we get an error:

```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	var mapObject map[string][]interface{}
	message := "{\"records\": [{ \"time\": \"2022-12-17T20:21:24.4331338Z\", \n \"resourceId\": \"/SUBSCRIPTIONS/5AEB8557-CAB7-41AC-8603-9F94AD233EFC/RESOURCEGROUPS/GT-WEU-GTP-CORE-DEV-RSG/PROVIDERS/MICROSOFT.WEB/SITES/AppService-Redacted\", \"category\": \"AppServicePlatformLogs\", \"operationName\": \"AutoHealingLogEvent\", \"level\": \"Informational\", \"resultDescription\": \"Worker Process serving application pool 'AppService-Redacted' hit the 'Total Requests' limit.\\n\", \"properties\": {\"message\":\"Worker Process serving application pool 'AppService-Redacted' hit the 'Total Requests' limit.\n\"}}]}"

	bMessage := []byte(message)
	err := json.Unmarshal(bMessage, &mapObject)
	if err != nil {
		fmt.Println(err)
                return
	}

	fmt.Println(mapObject)
}
```

The result is:

```text
invalid character '\n' in string literal
```

### PR DESCRIPTION
**Pull request by lucianpy**
## What does this PR do?

This PR adds the function `sanitize` which is used in `parseMultipleMessages` to clean up the message string before attempting to unmarshal the JSON.

It also adds the field `SanitizeOptions` which should be added manually for the datastreams that require sanitization in [integrations](https://github.com/elastic/integrations).

## Why is it important? 

As pointed out by @zmoog, some logs from Azure can have issues with [newlines](https://github.com/elastic/beats/issues/34092), while others with [single quotes](https://github.com/elastic/azuremarketplacedev/issues/190).

This can lead to failure in processing the data in [integrations](https://github.com/elastic/integrations) (ex: the pipeline receiving one document with two records).

## Filebeat sample configuration
```
eventhub: ""
connection_string: ""
storage_account: ""
storage_account_key: ""
sanitize_options:
  - NEW_LINES
  - SINGLE_QUOTES
```

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist
- [x] Enhance testing with real world examples

## Related issues
- Closes #34092

### CODE REVIEW

**Comment by lucianpy** [comment]
The function `parseMultipleMessages` in `input.go` does not keep the original order of the json keys. 

Therefore, the expected result has the json keys in different order (sanitization works fine).

File: x-pack/filebeat/input/azureeventhub/config.go [hunk 1]
```diff
@@ -26,6 +26,8 @@ type azureInputConfig struct {
 	SAContainer string `config:"storage_account_container"`
 	// by default the azure public environment is used, to override, users can provide a specific resource manager endpoint
 	OverrideEnvironment string `config:"resource_manager_endpoint"`
+	// option to cleanup the input for known issues which might produce a malformed JSON
+	SanitizeMessage bool `config:"sanitize_message"`
```
Comment (zmoog) [inline x-pack/filebeat/input/azureeventhub/config.go:30]: Can we offer the option of removing new lines or replacing single quotes as two options instead of just one that does both?

Function App logs users are affected only by the single quotes problem; App Service logs users are affected by the new lines problem only. We can enable only the required adjustment in the settings for each integration to lower the risk of side effects.

WDYT?

Comment (lucianpy) [reply x-pack/filebeat/input/azureeventhub/config.go]: @zmoog  Sounds good, just added the initial solution for that (still needs docs and maybe slight touch-ups). 

Let me know if this looks like what you had in mind.

File: x-pack/filebeat/input/azureeventhub/input.go [hunk 2]
```diff
@@ -167,6 +167,12 @@ func (a *azureInput) processEvents(event *eventhub.Event, partitionID string) bo
 func (a *azureInput) parseMultipleMessages(bMessage []byte) []string {
 	var mapObject map[string][]interface{}
 	var messages []string
+	// clean up the message for known issues producing a malformed JSON
+	if a.config.SanitizeOptions != nil {
```
Comment (dmathieu) [inline x-pack/filebeat/input/azureeventhub/input.go:171]: Nit: A `[]string` will never be nil. It will be an empty slice., over which you can loop (it won't do anything, since it's empty). So this condition isn't required.

File: x-pack/filebeat/input/azureeventhub/input.go [hunk 3]
```diff
@@ -167,6 +167,12 @@ func (a *azureInput) processEvents(event *eventhub.Event, partitionID string) bo
...
+		for _, opt := range a.config.SanitizeOptions {
+			bMessage = sanitize(string(bMessage), opt)
```
Comment (dmathieu) [inline x-pack/filebeat/input/azureeventhub/input.go:173]: What if an unknown/invalid opt is passed here?

File: x-pack/filebeat/input/azureeventhub/sanitization.go [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+// +build !aix
+
+package azureeventhub
+
+import "strings"
+
+type sanitizationFunc func(jsonStr string) []byte
+
+func getSanitizationFuncs() map[string]sanitizationFunc {
+	return map[string]sanitizationFunc{
```
Comment (dmathieu) [inline x-pack/filebeat/input/azureeventhub/sanitization.go:15]: Wouldn't a switch/case be more readable here (it would also allow having a default behavior).

File: x-pack/filebeat/input/azureeventhub/sanitization_test.go [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+import (
+	"fmt"
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+
+	"github.com/elastic/elastic-agent-libs/logp"
+)
+
+func TestSanitizeMessage(t *testing.T) {
```
Comment (dmathieu) [inline x-pack/filebeat/input/azureeventhub/sanitization_test.go:19]: While all these tests make sense, they bootstrap a lot of things, when the methods themselves are pretty simple.
How about testing the full-blown setup once, and then testing each individual method directly?
That would allow more fine-tuned testing of those sanitizations, and simplification of those tests.

Also, you could reduce repetition in those full-blown tests by using subtests: https://go.dev/blog/subtests

File: x-pack/filebeat/input/azureeventhub/input.go (hunk 3 above)
Comment (lucianpy) [reply x-pack/filebeat/input/azureeventhub/input.go:173]: My idea is to handle this in the sanitize function. If an unkwown option is passed, it should just return the JSON string as it was.

File: x-pack/filebeat/input/azureeventhub/sanitization.go (hunk 4 above)
Comment (lucianpy) [reply x-pack/filebeat/input/azureeventhub/sanitization.go:15]: Should the default behaviour be for all sanitizations to occur for Azure? What's your opinion on this? @zmoog

**Comment by lucianpy** [comment]
https://github.com/elastic/beats/blob/b06298798e474031e33868cee631933317b11f27/x-pack/filebeat/input/azureeventhub/input.go#L171

Since unmrashalling happens into a map, we technically only need to worry about newlines in between the key:value pairs themselves. Just something to consider.

File: x-pack/filebeat/input/azureeventhub/sanitization.go (hunk 4 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/sanitization.go:15]: 1. The default behavior must be no sanitization; these malformed JSON documents are edge cases.
2. We need to make this option available in the agent template file and on the integration settings page. 

For example, we can turn it on by default for FunctionApp logs but also give the option to turn it off as an escape hatch.

This triggers a question: we will probably release this change with stack version 8.8 and backport it to 8.7.2. How can we make this fix available without raising the minimum required version for the Azure Integration logs to 8.7.2? Today the min required version is `^7.16.0 || ^8.0.0`. 

It's a big bump to address and an edge case.

File: x-pack/filebeat/input/azureeventhub/input.go (hunk 2 above)
Comment (lucianpy) [reply x-pack/filebeat/input/azureeventhub/input.go:171]: I agree that the condition serves no purpose. However, can you please clarify on:

> A []string will never be nil. It will be an empty slice.

If you run the following code, Go will actually output `true`:
```
type X struct {
	A []string
}

func main() {
	x := &X{}
	fmt.Println(x.A == nil)
}
```

Comment (dmathieu) [reply x-pack/filebeat/input/azureeventhub/input.go:171]: Yes, but it's a `[]string(nil)`.
See https://go.dev/play/p/mBOTE_L2s6E

**Comment by zmoog** [comment]
@lucianpy, please make sure the settings are easy to use in the Agent template and in integration settings UI. 

Set this PR ready for review when you're ready. 

I will ask around what are our options to make this new configuration settings available to the integration without bumping the min version from 7.17.x to 8.7.2 for an edge case.

File: x-pack/filebeat/input/azureeventhub/sanitization.go [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+func sanitizationOptFromString(s string) error {
+	switch s {
+	case "NEW_LINES":
+		return nil
+	case "SINGLE_QUOTES":
+		return nil
+	default:
+		return errors.New("invalid sanitization option")
+	}
+}
```
Comment (zmoog) [inline x-pack/filebeat/input/azureeventhub/sanitization.go:32]: In this package, similar validation functions are called `<some data type>Validate`; for example, `storageContainerValidate()`.

File: x-pack/filebeat/input/azureeventhub/sanitization.go [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+
+		if r == '\'' && !inDoubleQuotes {
+			result.WriteRune('"')
+		} else {
+			result.WriteByte(r)
+		}
+	}
+
+	return result.Bytes()
+}
```
Comment (zmoog) [inline x-pack/filebeat/input/azureeventhub/sanitization.go:86]: > Wouldn't a switch/case be more readable here (it would also allow having a default behavior).

How did it turn out for you, @dmathieu?

**Comment by zmoog** [comment]
@lucianpy I think adding a sample Filebeat configuration in the PR description would be helpful (and we probably need to add it to the docs).

File: x-pack/filebeat/input/azureeventhub/input.go [hunk 8]
```diff
@@ -167,6 +167,10 @@ func (a *azureInput) processEvents(event *eventhub.Event, partitionID string) bo
 func (a *azureInput) parseMultipleMessages(bMessage []byte) []string {
 	var mapObject map[string][]interface{}
 	var messages []string
+
+	// clean up the message for known issues producing a malformed JSON
+	bMessage = sanitize(bMessage, a.config.SanitizeOptions...)
```
Comment (zmoog) [inline x-pack/filebeat/input/azureeventhub/input.go:172]: As suggested by @gpop63, what about checking for JSON validity using https://pkg.go.dev/encoding/json#Valid before sanitizing the message?

If sanitization is enabled (options are not empty), we check if the document is valid; if is not valid, the we attempt to sanitize it.

WDYT?

File: x-pack/filebeat/input/azureeventhub/sanitization.go [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+	for _, r := range jsonStr {
+		if r == '\n' {
+			continue
+		}
+
+		result.WriteByte(r)
+	}
+
+	return result.Bytes()
+}
```
Comment (zmoog) [inline x-pack/filebeat/input/azureeventhub/sanitization.go:64]: Why did you pick a custom implementation vs. using `bytes.ReplaceAll()`?

File: x-pack/filebeat/input/azureeventhub/input.go (hunk 8 above)
Comment (lucianpy) [reply x-pack/filebeat/input/azureeventhub/input.go]: This approach is efficient if many valid messages are processed while sanitization is enabled, which I expect would be the majority of cases.

An if statement is enough here, since exceptions are evaluated in order and the subsequent expressions are not evaluated if one is already false.

File: x-pack/filebeat/input/azureeventhub/input.go [hunk 10]
```diff
@@ -166,6 +166,13 @@ func (a *azureInput) processEvents(event *eventhub.Event, partitionID string) bo
 func (a *azureInput) parseMultipleMessages(bMessage []byte) []string {
 	var mapObject map[string][]interface{}
 	var messages []string
+
+	// clean up the message for known issues producing a malformed JSON
+	// sanitization occurs if options are available and the message produces invalid JSON
```
Comment (zmoog) [inline x-pack/filebeat/input/azureeventhub/input.go:171]: Nit:

```suggestion
	// Clean up the message for known issues [1] where Azure services produce malformed JSON documents.
	// Sanitization occurs if options are available and the message contains an invalid JSON.
	//
	// [1]: https://learn.microsoft.com/en-us/answers/questions/1001797/invalid-json-logs-produced-for-function-apps
```

File: x-pack/filebeat/input/azureeventhub/sanitization.go [hunk 11]
```diff
@@ -0,0 +1,86 @@
...
+
+		if r == '\'' && !inDoubleQuotes {
+			result.WriteRune('"')
+		} else {
+			result.WriteByte(r)
+		}
+	}
+
+	return result.Bytes()
+}
```
[the remark this answers is not in the document]
Comment (lucianpy) [reply x-pack/filebeat/input/azureeventhub/sanitization.go]: Good catch , I see Azure is very creative in their JSON output: 

> `"value": "[\"AuditLog.Read.All\",\"Calendar.ReadWrite\"...]"`

Treating JSON embedded within strings as simple strings keeps the logic fairly clean while addressing this. 
Escaped double quotes are no longer toggling `inDoubleQuotes`.

**Comment by lucianpy** [comment]
@zmoog I've set up the settings. They will be separate toggles for each sanitization option under Advanced options.

**Review by zmoog — APPROVED** [review]
@lucianpy successfully tested we have everything we need to use this from the Agent integrations settings, so we're good to go!

**Comment by zmoog** [comment]
Hey, @elastic/elastic-agent-data-plane, @lucianpy also needs your review since you are the [default owner](https://github.com/elastic/beats/blob/e870503ee037f96db7be99f77a31ec16aa37b06c/.github/CODEOWNERS#L8) in the Beats repo.

**Comment by cmacknz** [comment]
Looks like the data plane team is only being pinged because there is no owner set for the azureeventhub input. Rather than requiring us to review, change the codeowner for this input to the team that actually owns it and then I'll approve that. That way we aren't needlessly pinged every time this code changes.

**Comment by lalit-satapathy** [comment]
> Looks like the data plane team is only being pinged because there is no owner set for the azureeventhub input. Rather than requiring us to review, change the codeowner for this input to the team that actually owns it and then I'll approve that. That way we aren't needlessly pinged every time this code changes.

Classic example of wrong team being pinged because _not-up-to-date CODEOWNER entry_ and hence delaying the PR review process. 

FYI: @andresrc @ruflin

**Comment by zmoog** [comment]
> Looks like the data plane team is only being pinged because there is no owner set for the azureeventhub input. Rather than requiring us to review, change the codeowner for this input to the team that actually owns it and then I'll approve that. That way we aren't needlessly pinged every time this code changes.

You are totally right @cmacknz. My apologies for the noise.

I opened a [PR](https://github.com/elastic/beats/pull/35620) to assign the ownership of this input to my team.
