### PR TITLE
Fix Prometheus metric types parser

### LINKED ISSUE #39705: Prometheus parser incorrectly classifies counters as histograms
### Overview

While attempting to ingest nginx stream metrics using the `prometheus` module, we've noticed that certain metrics such as `nginx_sts_upstream_connects_total` and `nginx_sts_server_connects_total` are not being ingested.

This issue is not present in metricbeat version `7.17.x` where all metrics are ingested correctly. However, in versions `8.7` and later, these metrics are being skipped.

The issue seems to be rooted in the text parser logic in `metricbeat/helper/prometheus/textparse.go`, specifically within the `ParseMetricFamilies` function. When processing a group of metrics, the metric type variable is set to the latest metric type in the group, even if their types might differ.

```
# HELP nginx_sts_server_bytes_total The request/response bytes
# TYPE nginx_sts_server_bytes_total counter
# HELP nginx_sts_server_connects_total The connects counter
# TYPE nginx_sts_server_connects_total counter
# HELP nginx_sts_server_session_seconds_total The session duration time
# TYPE nginx_sts_server_session_seconds_total counter
# HELP nginx_sts_server_session_seconds The average of session duration time in seconds
# TYPE nginx_sts_server_session_seconds gauge
# HELP nginx_sts_server_session_duration_seconds The histogram of session duration in seconds
# TYPE nginx_sts_server_session_duration_seconds histogram
nginx_sts_server_bytes_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",direction="in"} 0
nginx_sts_server_bytes_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",direction="out"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="1xx"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="2xx"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="3xx"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="4xx"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="5xx"} 171
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="total"} 171
nginx_sts_server_session_seconds_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP"} 0.016
nginx_sts_server_session_seconds{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP"} 0.000
```

After the loop completes for a group of metrics, `mt` is set to the last metric type in the group, which in this case is `histogram`. This is problematic because for example `nginx_sts_server_connects_total` is actually a `counter`. This causes an error later in the code when we validate if the metric name contains a suffix specific to a histogram - the check fails and these metrics are skipped.

<details>
<summary><h3><strong>How to replicate</strong></h3></summary>
<p>

(We had a recent issue with nginx, that's why the setup - it could be replicated way easier)

#### Prerequisites:
- `nginx`
- `nginx-module-sts`
- `nginx-module-stream-sts`
- `nginx-module-vts` (not sure if this one is needed)

```bash
# nginx modules
git clone https://github.com/vozlt/nginx-module-sts.git
git clone https://github.com/vozlt/nginx-module-stream-sts.git
git clone https://github.com/vozlt/nginx-module-vts.git

# nginx
wget http://nginx.org/download/nginx-1.18.0.tar.gz
tar -xzvf nginx-1.18.0.tar.gz
cd nginx-1.18.0

# configure & build nginx
./configure --with-stream --add-module=/path/to/nginx-module-sts --add-module=/path/to/nginx-module-stream-sts --add-module=/path/to/nginx-module-vts --with-http_stub_status_module
make
make install
```

Make sure to use the below `nginx.conf` which will be in `/usr/local/nginx/conf/nginx.conf` before starting `nginx`.

<details>
<summary><strong>nginx.conf</strong></summary>
<p>

```
events {
    worker_connections  1024;
}

http {
    stream_server_traffic_status_zone;
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }

        location /nginx_status {
            stub_status;
        }

        location /http_traffic_status {
            vhost_traffic_status_bypass_limit on;
            vhost_traffic_status_bypass_stats on;
            vhost_traffic_status_display;
            vhost_traffic_status_display_format html;
        }

        location /status {
            stream_server_traffic_status_display;
            stream_server_traffic_status_display_format html;
        }

        location = /50x.html {
            root   html;
        }
    }
}

stream {
    server_traffic_status_zone;

    server {
        listen 8091;
        proxy_pass localhost:8092;
    }
}
```

</p>
</details> 

Then start `nginx` and make some dummy requests.

```bash
# start nginx
sudo /usr/local/nginx/sbin/nginx

# GET request to create some stream metrics
curl http://localhost:8091
```

#### Metricbeat Prometheus config

```yaml
- module: prometheus
  period: 10s
  metricsets: ["collector"]
  hosts: ["localhost:80"]
  metrics_path: /status/format/prometheus
```

</p>
</details> 

### Possible solution

Did a quick test to see if it works and it does but not sure what the impact would be. Needs more testing.

```diff
diff --git a/metricbeat/helper/prometheus/textparse.go b/metricbeat/helper/prometheus/textparse.go
index 4dca85c3aa..e05a3783f0 100644
--- a/metricbeat/helper/prometheus/textparse.go
+++ b/metricbeat/helper/prometheus/textparse.go
@@ -489,6 +489,7 @@ func ParseMetricFamilies(b []byte, contentType string, ts time.Time, logger *log
 		histogramsByName     = map[string]map[string]*OpenMetric{}
 		fam                  *MetricFamily
 		mt                   = textparse.MetricTypeUnknown
+		metricTypes          = make(map[string]textparse.MetricType)
 	)
 	var err error
 
@@ -530,7 +531,7 @@ func ParseMetricFamilies(b []byte, contentType string, ts time.Time, logger *log
 			} else {
 				fam.Type = t
 			}
-			mt = t
+			metricTypes[s] = t
 			continue
 		case textparse.EntryHelp:
 			buf, t := parser.Help()
@@ -611,6 +612,8 @@ func ParseMetricFamilies(b []byte, contentType string, ts time.Time, logger *log
 		lookupMetricName := metricName
 		var exm *exemplar.Exemplar
 
+		mt = metricTypes[metricName]
+
 		// Suffixes - https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#suffixes
 		switch mt {
 		case textparse.MetricTypeCounter:
```

cc @agithomas

### PR DESCRIPTION
**Pull request by ghost**
## Overview

When processing a group of metrics of this format, the metric type variable is set to the latest metric type in the group, even if their types might differ. This happens because the parser thinks this is only 1 metric. This change stores the metric types for each base metric name to avoid this issue.

```
# HELP nginx_sts_server_bytes_total The request/response bytes
# TYPE nginx_sts_server_bytes_total counter
# HELP nginx_sts_server_connects_total The connects counter
# TYPE nginx_sts_server_connects_total counter
# HELP nginx_sts_server_session_seconds_total The session duration time
# TYPE nginx_sts_server_session_seconds_total counter
# HELP nginx_sts_server_session_seconds The average of session duration time in seconds
# TYPE nginx_sts_server_session_seconds gauge
# HELP nginx_sts_server_session_duration_seconds The histogram of session duration in seconds
# TYPE nginx_sts_server_session_duration_seconds histogram
nginx_sts_server_bytes_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",direction="in"} 0
nginx_sts_server_bytes_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",direction="out"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="1xx"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="2xx"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="3xx"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="4xx"} 0
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="5xx"} 171
nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="total"} 171
nginx_sts_server_session_seconds_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP"} 0.016
nginx_sts_server_session_seconds{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP"} 0.000
```

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #39705

### CODE REVIEW

File: metricbeat/helper/prometheus/textparse_test.go [hunk 1]
```diff
@@ -144,6 +144,166 @@ process_cpu 20
...
+					},
+					Gauge: &Gauge{Value: float64p(0.000)},
+				},
+			},
+		},
+	}
+
+	result, err := ParseMetricFamilies([]byte(input), ContentTypeTextFormat, time.Now(), nil)
+	if err != nil {
+		t.Fatalf("ParseMetricFamilies for content type %s returned an error.", ContentTypeTextFormat)
```
Comment (AndersonQ) [inline metricbeat/helper/prometheus/textparse_test.go:302]: [Blocker]
Please log the error as well. Otherwise if this test fail it'll be difficult to understand why it failed.

File: metricbeat/helper/prometheus/textparse_test.go [hunk 2]
```diff
@@ -144,6 +144,166 @@ process_cpu 20
...
+nginx_sts_server_bytes_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",direction="in"} 0
+nginx_sts_server_bytes_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",direction="out"} 0
+nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="1xx"} 0
+nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="2xx"} 0
+nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="3xx"} 0
+nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="4xx"} 0
+nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="5xx"} 171
+nginx_sts_server_connects_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP",code="total"} 171
+nginx_sts_server_session_seconds_total{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP"} 0.016
+nginx_sts_server_session_seconds{listen="TCP:8091:127.0.0.1",port="8091",protocol="TCP"} 0.000
```
Comment (AndersonQ) [inline metricbeat/helper/prometheus/textparse_test.go:168]: [Suggestion]

2 things:

 - from [this](https://github.com/elastic/beats/pull/39743/files#diff-d66f15900f5676672ddf353458a9373cf8b1ab8e237c473191e4a64ae93cbba2R618-R621) the metric name of `nginx_sts_server_session_seconds_total` would be `nginx_sts_server_session_seconds` and the metric name of `nginx_sts_server_session_seconds` would be `nginx_sts_server_session`. Just checking, is my understand correct and is it the expected behaviour?
 - wouldn't be good to add 2 metrics with the same base name, like in your example `summary_metric_count` and `summary_metric_sum`?

**Review by AndersonQ — CHANGES_REQUESTED** [review]

File: metricbeat/helper/prometheus/textparse_test.go (hunk 2 above)
Comment (gpop63) [reply metricbeat/helper/prometheus/textparse_test.go:168]: My example was for the metric family below. The metric family is called `summary_metric` and it includes various metrics such as `summary_metric_sum`, `summary_metric_count`, etc. We only want to store the metric type for the metric family `summary_metric` since all its metrics share the same type, which is `summary`.

```
# TYPE summary_metric summary
summary_metric{quantile="0.5"} 29735
summary_metric{quantile="0.9"} 47103
summary_metric{quantile="0.99"} 50681
summary_metric{noquantile="0.2"} 50681
summary_metric_sum 234892394
summary_metric_count 44000
summary_metric_impossible 123
# EOF
```

https://github.com/elastic/beats/blob/28ed783e6d6c90069ab1d7d5dd63839b0225ac17/metricbeat/helper/prometheus/textparse.go#L525-L535

`s` represents the metric family name (e.g., `summary_metric`). Only the metric family name is stored in the map, without its individual metrics.

For the examples you mentioned, `nginx_sts_server_session_seconds_total` and `nginx_sts_server_session_seconds`, these metrics are already the metric family names (they don't have any child metrics) and thus would not trigger the `!ok` condition. The `!ok` condition was added as an edge case for families that have multiple child metrics with different suffixes.

File: metricbeat/helper/prometheus/textparse_test.go (hunk 1 above)
Comment (pierrehilbert) [reply metricbeat/helper/prometheus/textparse_test.go:302]: @gpop63 could you please apply the requested change here?

**Comment by pierrehilbert** [comment]
@fearful-symmetry / @VihasMakwana could you please review this PR?

**Review by fearful-symmetry — APPROVED** [review]
Don't have much context for Prometheus specifically, but the code seems fine.

**Review by VihasMakwana — APPROVED** [review]

**Comment by pierrehilbert** [comment]
@gpop63 are we expecting to backport this in 8.14?

**Comment by pierrehilbert** [comment]
@gpop63 could you have a look here please?
