### PR TITLE
Save file size to registry of ignored files

### LINKED ISSUE #31924: Filebeat resends whole log files causing duplicated data
First case:
Filebeat resends the whole log files after restarting despite the log file stating that the registry file has been loaded successfully.
Second case:
Filebeat resends the whole log file, without restarting Filebeat, if the 24h period is exceeded (no logs during last 24h), then if a new log entry is saved to the file, Filebeat resends the whole log file.

For confirmed bugs, please report:
- Version: 8.1.1
- Operating System: RHEL 7.9
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-resends-log-files-after-restart/303924/5
- Steps to Reproduce: 
1.Run Filebeat
2.Insert some example log line to an existing log file from the config directory.
3.Restart FIlebeat
4.Result: all of the files with the modification date <24h are resent to the configured output.

1.Run Filebeat
2.Insert some example log line to an existing log file from the config directory.
3.Wait for the period set in "ignore_older" to pass and insert a new line to the log file after.
4.Result: all of the files with the modification date <24h are resent to the configured output.

-Snippet of configuration
`filebeat.inputs:
- type: filestream
  enabled: true
  paths:
   - /path/to/logs/*.log
  parsers:
  - multiline:
      type: pattern
      pattern: '^[0-9]{4}[[:space:]]+[A-Z]{1}[a-z]{2}[[:space:]]+[0-9]{2}'
      negate: True
      match: after
  name: tibco_int
  tags: ["tibcoint1-logs"]
  ignore_older: 24h`

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

This PR saves the size of the ignored files. Thus, if the file is updated, `filestream` input only reads the new log lines, not the whole file.

The PR also fixes a minor logging problem. Previously, resetting the cursor due to truncation was always logged at an error level. Not it is only logged if the cursor is not reset properly.

## Why is it important?

Now `filestream` input starts to read from the beginning of the file. This is not what we promise in the documentation:
> For files which were never seen before, the offset state is set to the end of the file... If a file is updated again later, reading continues at the set offset position.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

1. Create a `test.log` file with the following contents:
```
ignored line
ignored line
ignored line

```
2. Start Filebeat with the following input configuration:
```
- type: filestream
  enabled: true
  id: my-filestream-id
  paths:
    - test.log
  ignore_older: 10s
```

3. Update `test.log` with a new line:
```
published line

```
4. Check if only the message `"published line"` is published.

## Related issues

Closes #31924

### CODE REVIEW

File: filebeat/input/filestream/prospector.go [hunk 1]
```diff
@@ -195,7 +199,9 @@ func (p *fileProspector) onFSEvent(
 		log.Debugf("File %s has been truncated", event.NewPath)
 
 		err := updater.ResetCursor(src, state{Offset: 0})
-		log.Errorf("resseting cursor on truncated file: %v", err)
+		if err != nil {
```
Comment (kvch) [inline filebeat/input/filestream/prospector.go:202]: This is separate fix for a logging issue.

File: filebeat/input/filestream/prospector_test.go [hunk 2]
```diff
@@ -252,11 +253,76 @@ func TestProspectorNewAndUpdatedFiles(t *testing.T) {
 
 			p.Run(ctx, newMockMetadataUpdater(), hg)
 
-			assert.ElementsMatch(t, test.expectedEvents, hg.events)
+			assert.ElementsMatch(t, test.expectedEvents, hg.events, "expected different harvester events")
 		})
 	}
 }
 
+// TestProspectorNewAndUpdatedFiles checks if the prospector can
```
Comment (cmacknz) [inline filebeat/input/filestream/prospector_test.go:261]:
```suggestion
// TestProspectorHarvesterUpdateIgnoredFiles checks if the prospector can
```

File: filebeat/input/filestream/prospector_test.go [hunk 3]
```diff
@@ -252,11 +253,76 @@ func TestProspectorNewAndUpdatedFiles(t *testing.T) {
...
+	testStore := newMockMetadataUpdater()
+	var wg sync.WaitGroup
+	wg.Add(1)
+	go func() {
+		p.Run(ctx, testStore, hg)
+
+		wg.Done()
+	}()
+
+	// The prospector must persist the size of the to the state
```
Comment (cmacknz) [inline filebeat/input/filestream/prospector_test.go:300]:
```suggestion
	// The prospector must persist the size of the file to the state
```

File: filebeat/input/filestream/prospector_test.go [hunk 4]
```diff
@@ -438,13 +504,18 @@ func (t *testHarvesterGroup) StopGroup() error {
...
 	nextIdx     int
 	events      []loginp.FSEvent
 	filesOnDisk map[string]os.FileInfo
 }
 
 func (m *mockFileWatcher) Event() loginp.FSEvent {
+AGAIN:
 	if len(m.events) == m.nextIdx {
+		if m.ctx != nil && m.ctx.Err() == nil {
+			goto AGAIN
```
Comment (cmacknz) [inline filebeat/input/filestream/prospector_test.go:517]: Can this busy waiting be replaced by `<-m.ctx.Done()`?  The only time `err != nil` is when `ctx.Done()` has been written to, from https://pkg.go.dev/context#Context:

```go
// If Done is not yet closed, Err returns nil.
// If Done is closed, Err returns a non-nil error explaining why:
// Canceled if the context was canceled
// or DeadlineExceeded if the context's deadline passed.
// After Err returns a non-nil error, successive calls to Err return the same error.
Err() [error](https://pkg.go.dev/builtin#error)
```

Comment (kvch) [reply filebeat/input/filestream/prospector_test.go:517]: Good point. It was rather a placeholder code, I forgot to get back to. Thanks.

**Review by cmacknz — APPROVED** [review]
