### PR TITLE
Fix/change the initialization of management layer

### LINKED ISSUE #30533: Filebeat running under Elastic-Agent not harvesting logs after restart
After a restart a filebeat running under the elastic-agent doesn't start harvesting logs. Upon restart filebeat receive the config from the elastic-agent, it's processed, however only the `output` is applied.It happens inconsistently, so far reported on Linux and Windows endpoints. 

In a fleet of agents enrolled to the same fleet-server only a few will show this behaviour. A changing the elastic-agent's policy fixes the problem. A restart should do the same (needs confirmation)

Even when showing this behaviour there are no errors in the logs of either filebeat or elastic-agent.

#### Known facts:
- When a *new* configuration with changes is send to the Agent, it will restart sending events.
  This mean that the system is correctly configured and sane and it is able to recover from the situation.
- We can confirm the configuration is available it's retrieved from the *diagnostic* command.
- We can confirm in the logs that the output receive the Elasticsearch configuration, this is the only
  block that is modified after a restart.
- We know that Filebeat is up and running, this means that the Agent detect input size is > 0.
- If there is a problem in the configuration block the manager in libbeat will just ignore the error and continue.
- Filebeat load the registrar state.
- I know that Filebeat doesn't start any log harvester from the periodic metric dump.
- I know that Filebeat is not processing any events from the periodic metric dump.
- It's a random issue, if you have a fleet of agent some agent can be healthy and send events and others not.

#### What have been tried:
- We have tried to reproduce the issues by simulating the configuration changes with nginx or custom log harvester.
  We might have been able to reproduce once, but we do not have the log to inspect.

### PR DESCRIPTION
**Pull request by ph**
This fix an issue on Filebeat that makes the start sequence of Filebeat
non-deterministic. It was possible that not all the hooks were
configured correctly before the managed was receiving a configuration
from the Elastic Agent.

This causes inconsistency between the expected configuration state coming from Agent
and the actual running state. This situation can have one or many of the following symptoms:

- Having Filebeat runnings and not sending any data to Elasticsearch
- Having Filebeat partially configured, when only some inputs were
  sending data.
- Missing log from the Filebeat collector
- Having only Metricbeats running and sending logs.
- A problematic process is restarted by the agent.

This solves the issues by moving the `Start` and stop `Stop` of the
manager into the beats initialization process, each beat need to be
adjusted to support this new sequence. 

This is indeed a **breaking change for beats author**,
but the bootstrap process of beats and libbeat cannot easily be
extended to make the change into a unique place. 

**Every beats has a different code path.**

## How it was detected

This was detected on a log where log events were actually missing from the log.

### Working endpoint.
```
{"log.level":"info","@timestamp":"2022-03-03T15:21:46.739+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":109},"message":"Starting fleet management service","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-03T15:21:47.354+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":150},"message":"Status change to Configuring: Updating configuration","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-03T15:21:47.354+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":271},"message":"Applying settings for filebeat.inputs","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2022-03-03T15:21:47.354+0100","log.logger":"centralmgmt","log.origin":{"file.name":"cfgfile/list.go","file.line":63},"message":"Starting reload procedure, current runners: 0","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2022-03-03T15:21:47.355+0100","log.logger":"centralmgmt","log.origin":{"file.name":"cfgfile/list.go","file.line":81},"message":"Start list: 2, Stop list: 0","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2022-03-03T15:21:47.356+0100","log.logger":"centralmgmt","log.origin":{"file.name":"cfgfile/list.go","file.line":105},"message":"Starting runner: input [type=log]","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2022-03-03T15:21:47.358+0100","log.logger":"centralmgmt","log.origin":{"file.name":"cfgfile/list.go","file.line":105},"message":"Starting runner: input [type=log]","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-03T15:21:47.358+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":271},"message":"Applying settings for output","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-03T15:21:47.358+0100","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":102},"message":"elasticsearch url: https://<redacted>:443","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-03T15:21:47.358+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":271},"message":"Applying settings for filebeat.modules","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2022-03-03T15:21:47.358+0100","log.logger":"centralmgmt","log.origin":{"file.name":"cfgfile/list.go","file.line":63},"message":"Starting reload procedure, current runners: 0","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2022-03-03T15:21:47.358+0100","log.logger":"centralmgmt","log.origin":{"file.name":"cfgfile/list.go","file.line":81},"message":"Start list: 0, Stop list: 0","service.name":"filebeat","ecs.version":"1.6.0"}
```

### Problematic endpoint
```
{"log.level":"info","@timestamp":"2022-03-03T11:20:41.207+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":109},"message":"Starting fleet management service","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-03T11:20:41.732+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":150},"message":"Status change to Configuring: Updating configuration","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-03T11:20:41.733+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":271},"message":"Applying settings for output","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-03T11:20:41.733+0100","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":102},"message":"elasticsearch url: https://<redacted>:443","service.name":"filebeat","ecs.version":"1.6.0"}
```

The later log extract only contains information about the outputs (`Applying settings...) nothing about the inputs.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

Since the problem is non-deterministic reproducing this issue really hard, I was able to reproduce a few times by having simulated load on agent virtual machine. 

## Related issues

- Closes #30533

### CODE REVIEW

**Comment by ph** [comment]
The failure looks valid to me, I will take look.

**Comment by ph** [comment]
I've looked at the issues, I am going to rebased this PR and have another go with the test, I've added a changelog too.

File: x-pack/libbeat/management/manager.go [hunk 1]
```diff
@@ -96,24 +101,26 @@ func (cm *Manager) Enabled() bool {
...
 	cfgwarn.Beta("Fleet management is enabled")
 	cm.logger.Info("Starting fleet management service")
 
-	cm.stopFunc = stopFunc
 	cm.isRunning = true
 	err := cm.client.Start(context.Background())
 	if err != nil {
 		cm.logger.Errorf("failed to start elastic-agent-client: %s", err)
+	} else {
+		cm.logger.Info("Ready to receive configuration")
```
Comment (ph) [inline x-pack/libbeat/management/manager.go:121]:
```suggestion
		cm.logger.Info("ready to receive configuration")
````

Will merge when other review are in, so I don't have to wait the ci.

**Comment by ph** [comment]
@aleksmaus can you take a look at the osquerybeat part?

File: x-pack/libbeat/management/manager.go [hunk 2]
```diff
@@ -320,7 +324,7 @@ func (cm *Manager) toConfigBlocks(cfg common.MapStr) (ConfigBlocks, error) {
 	for _, regName := range cm.registry.GetRegisteredNames() {
 		iBlock, err := cfg.GetValue(regName)
 		if err != nil {
-			cm.logger.Errorf("failed to get '%s' from config: %v. Continuing to next one", regName, err)
+			cm.logger.Warnf("failed to get '%s' from config: %v. Continuing to next one", regName, err)
```
Comment (AndersonQ) [inline x-pack/libbeat/management/manager.go:327]: +1

File: x-pack/libbeat/management/manager_test.go [hunk 3]
```diff
@@ -72,3 +73,24 @@ type dummyReloadable struct{}
...
+	reg.Register("filebeat.inputs", &dummyReloadable{})
+	reg.Register("filebeat.modules", &dummyReloadable{})
+
+	cm := &Manager{
+		registry: reg,
+		logger:   logp.NewLogger("test"),
+	}
+
+	return cm
+}
```
Comment (AndersonQ) [inline x-pack/libbeat/management/manager_test.go:96]: [Question]
Whereas I understand the utility of having a dummy Manager for testing, I don't see any usage for them, so I wonder if it's necessary to add it now.

Comment (lykkin) [reply x-pack/libbeat/management/manager_test.go:96]: I'm a fan of adding mocks when possible. Since this will potentially be consumed by someone writing a new beat, they might just grep for a mock interface to throw into their tests.

File: x-pack/libbeat/management/manager.go [hunk 4]
```diff
@@ -29,6 +30,11 @@ var notReportedErrors = []error{
 	context.Canceled,
 }
 
+var outputRE = regexp.MustCompile(`^output$`)
+
+// Have to support all the beats.
+var inputsRE = regexp.MustCompile(`\.inputs$`)
```
[the remark this answers is not in the document]
Comment (ph) [reply x-pack/libbeat/management/manager.go:36]: I will remove them, its from another commit :)

**Comment by ph** [comment]
@AndersonQ @lykkin it seems I've mixed work from another commit, in this pr, I will remove.

File: metricbeat/beater/metricbeat.go [hunk 5]
```diff
@@ -255,6 +255,19 @@ func (bt *Metricbeat) Run(b *beat.Beat) error {
...
+	// Start the manager after all the reload hooks are configured,
+	// the Manager is stopped at the end of the execution.
+	if err := b.Manager.Start(); err != nil {
+		return err
+	}
+
+	wg.Add(1)
+	go func() {
+		defer wg.Done()
+		<-bt.done
```
[the remark this answers is not in the document]
Comment (ph) [reply metricbeat/beater/metricbeat.go:267]: The main issue, is all the beats have a different bootstrap code, which made it nearly impossible to ensure that the `reload` steps are configured before everything else. After looking more closely in the code, I can say that the boot process of beats is somewhat undefined. I would  not be surprised that other issues exist because of these quirks.


I am not a big fan of having adhoc code in each beat. But this was in my opinion to ensure that the system was in a consistent state before even starting the manager.

**Comment by ph** [comment]
@AndersonQ @lykkin I've updated the PR with your comments.

**Review by lykkin — DISMISSED** [review]
:goat: :dash:

File: x-pack/libbeat/management/manager.go [hunk 6]
```diff
@@ -96,24 +95,25 @@ func (cm *Manager) Enabled() bool {
...
 	cm.logger.Info("Starting fleet management service")
 
-	cm.stopFunc = stopFunc
 	cm.isRunning = true
 	err := cm.client.Start(context.Background())
 	if err != nil {
 		cm.logger.Errorf("failed to start elastic-agent-client: %s", err)
 	}
+	cm.logger.Info("Ready to receive configuration")
+	return err
```
Comment (AndersonQ) [inline x-pack/libbeat/management/manager.go:116]: I believe you missed the return when handling the error. 
As I'm suggesting already, I'm always for wrapping errors and giving more context. But it's up to you, just the return on error is the blocker here.

```suggestion
	if err != nil {
		fmt.Errorf("failed to start elastic-agent-client: %w", err)
		cm.logger.Errorf(err.Error())
		return err
	}
	cm.logger.Info("Ready to receive configuration")
	return nil
```

**Review by AndersonQ — CHANGES_REQUESTED** [review]

File: x-pack/libbeat/management/manager.go (hunk 6 above)
Comment (ph) [reply x-pack/libbeat/management/manager.go]: I've changed the code not exactly likes your suggestion but I do return the error.

**Review by AndersonQ — APPROVED** [review]

File: libbeat/cmd/instance/beat.go [hunk 7]
```diff
@@ -504,10 +504,6 @@ func (b *Beat) launch(settings Settings, bt beat.Creator) error {
 
 	logp.Info("%s start running.", b.Info.Beat)
 
-	// Launch config manager
-	b.Manager.Start(beater.Stop)
```
Comment (cmacknz) [inline libbeat/cmd/instance/beat.go:508]: Are there any dependencies on this outside this repository that would break? Custom beats? Maybe the new cloud beat?

Comment (ph) [reply libbeat/cmd/instance/beat.go:508]: That would be only APM-Server and Cloudbeat, I have PR to fix in APM.

File: filebeat/beater/filebeat.go [hunk 8]
```diff
@@ -392,6 +397,9 @@ func (fb *Filebeat) Run(b *beat.Beat) error {
 	adiscover.Stop()
 	crawler.Stop()
 
+	// We stop the manager and destroy his connection to Elastic Agent.
+	b.Manager.Stop()
```
Comment (blakerouse) [inline filebeat/beater/filebeat.go:401]: Should this be before the `waitPublished` below? When a beat is signaled to stop by the Elastic Agent it reports `STOPPING` back to the Elastic Agent. I think it would be better to always stop the manager after all the events have been published.

File: heartbeat/beater/heartbeat.go [hunk 9]
```diff
@@ -124,6 +124,13 @@ func (bt *Heartbeat) Run(b *beat.Beat) error {
 		defer bt.autodiscover.Stop()
 	}
 
+	// Configure the beats Manager to start after all the reloadable hooks are initialized
+	// and shutdown when the function return.
+	if err := b.Manager.Start(); err != nil {
+		return err
+	}
+	defer b.Manager.Stop()
```
Comment (blakerouse) [inline heartbeat/beater/heartbeat.go:132]: I think the defer here is going to place this in the wrong order. Because of the defer execution, the manager will be stopped before the `bt.monitorReloader.Stop()` and `defer bt.autodiscover.Stop()`. I think we should try to make sure that the manager is stopped always last.

File: libbeat/management/management.go [hunk 10]
```diff
@@ -74,9 +74,8 @@ type Manager interface {
 	// Enabled returns true if manager is enabled.
 	Enabled() bool
 
-	// Start the config manager giving it a stopFunc callback
-	// so the beat can be told when to stop.
-	Start(stopFunc func())
+	// Start the config manager.
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply libbeat/management/management.go:77]: More defined would be:

`Start() should be invoked after you are ready to start receiving configuration updates and actions.`

File: packetbeat/beater/packetbeat.go [hunk 11]
```diff
@@ -149,6 +149,13 @@ func (pb *packetbeat) runManaged(b *beat.Beat, factory *processorFactory) error
 
 	logp.Debug("main", "Waiting for the runner to finish")
 
+	// Start the manager after all the hooks are registered and terminates when
+	// the function return.
+	if err := b.Manager.Start(); err != nil {
+		return err
+	}
+	defer b.Manager.Stop()
```
Comment (blakerouse) [inline packetbeat/beater/packetbeat.go:157]: This is ordering is going to stop the manager before the runner. I think that should be switched.

File: x-pack/libbeat/management/manager.go [hunk 12]
```diff
@@ -217,10 +218,7 @@ func (cm *Manager) SetPayload(payload map[string]interface{}) {
 }
 
 func (cm *Manager) OnStop() {
-	if cm.stopFunc != nil {
-		cm.client.Status(proto.StateObserved_STOPPING, "Stopping", nil)
-		cm.stopFunc()
-	}
+	cm.client.Status(proto.StateObserved_STOPPING, "Stopping", nil)
```
Comment (blakerouse) [inline x-pack/libbeat/management/manager.go:221]: How does the Elastic Agent no signal a beat to stop? That comes from the control protocol. The Elastic Agent expects that once a beat receives a STOP that it should stop itself, only after a period of time (if it doesn't) does it force kill it.

I think this change here will really break that behavior and is incorrect.

Why the removal of the `stopFunc`?

**Review by blakerouse — CHANGES_REQUESTED** [review]

File: x-pack/libbeat/management/manager.go (hunk 12 above)
Comment (ph) [reply x-pack/libbeat/management/manager.go:221]: I will take a look, when I've moved the method and the flow of operation I thought the stopFunc was superfluous, but I will double check it.

File: libbeat/cmd/instance/beat.go [hunk 13]
```diff
@@ -504,10 +504,6 @@ func (b *Beat) launch(settings Settings, bt beat.Creator) error {
...
-	defer b.Manager.Stop()
```
Comment (ph) [inline libbeat/cmd/instance/beat.go:509]: @blakerouse Look at this code, if I am reading this correctly it mean that when the beats was shutting down we were never changing the state to the **beats** to stopping because no callback was defined see:

```golang
	if cm.stopFunc != nil {
		cm.client.Status(proto.StateObserved_STOPPING, "Stopping", nil)
		cm.stopFunc()
	}
```

So the function was never used as a synchronization mechanism.

File: x-pack/libbeat/management/manager.go (hunk 12 above)
Comment (ph) [reply x-pack/libbeat/management/manager.go:221]: @blakerouse I've looked a the code, and from what I see I believe Elastic Agent was always doing a force quit of the process, the `stopfunc()` was never configured. AFAIK, allowing a graceful shutdown on the beats is a big task, because they don't have any common shutdown flow. I am not sure this is worth the effort before refactoring the inputs into smaller components.

Comment (ph) [reply x-pack/libbeat/management/manager.go:221]: Note: I think this is a bug, but require a bigger effort and it's more risky.

File: libbeat/cmd/instance/beat.go (hunk 13 above)
Comment (blakerouse) [reply libbeat/cmd/instance/beat.go:509]: Correct if not `stopFunc` was defined we would not set it to stopping, which I still think is correct. Because without a `stopFunc` then there is no way for the manager to really signal that.

Comment (ph) [reply libbeat/cmd/instance/beat.go:509]: The problem is that signal is only defined before, so I have to set the stopFunc before doing any work downstream in the beat. I get it know, sorry I was confused by the startup sequence and clearly I didn't understand the purpose of it.

Comment (ph) [reply libbeat/cmd/instance/beat.go:509]: I think the easiest change would be to either add the StopFunc as part of the contructor of the manager or to add a `SetStopFunc`

**Comment by ph** [comment]
Do not review yet, have to make additional changes.

**Comment by ph** [comment]
@blakerouse I believe this is OK now, I've used an explicit setter for the callback so you can pass the `Beater.Stop`, The beater is not available in the context of the beater is not available inside the beats. So this will make the graceful-stop working.  After looking at the code for a long time, I still think there is a possibility of racy behavior in the beats code, The defer/channel/wait is not well defined.

**Comment by ph** [comment]
@simitt When this get reviewed approved, I will open the same PR on `apm-server` so we can get this rolling.

**Comment by ph** [comment]
@andrewkroh I've updated the godoc in this PR to make it a little clearer.

File: x-pack/osquerybeat/beater/osquerybeat.go [hunk 14]
```diff
@@ -169,6 +169,13 @@ func (bt *osquerybeat) Run(b *beat.Beat) error {
 		runner.Update(ctx, bt.config.Inputs)
 	}
 
+	// Ensure that all the hooks and actions are ready before starting the Manager
+	// to receive configuration.
+	if err := b.Manager.Start(); err != nil {
+		return err
+	}
+	defer b.Manager.Stop(func() {})
```
Comment (blakerouse) [inline x-pack/osquerybeat/beater/osquerybeat.go:177]: This needs to be updated.

**Review by blakerouse — CHANGES_REQUESTED** [review]

**Review by blakerouse — APPROVED** [review]
Change looks good now!

File: libbeat/management/management.go [hunk 15]
```diff
@@ -74,22 +74,37 @@ type Manager interface {
...
 	CheckRawConfig(cfg *common.Config) error
 
 	// RegisterAction registers action handler with the client
 	RegisterAction(action client.Action)
+
 	// UnregisterAction unregisters action handler with the client
 	UnregisterAction(action client.Action)
 
-	// SetPayload sets the client payload
+	// SetPayload Allows to add additional metadata to future requests made by the manager.
```
Comment (andrewkroh) [inline libbeat/management/management.go:107]:
```suggestion
	// SetPayload allows to add additional metadata to future requests made by the manager.
```

**Review by andrewkroh — APPROVED** [review]
LGTM. Thanks for the expanding the docs.

File: libbeat/management/management.go [hunk 16]
```diff
@@ -74,22 +74,37 @@ type Manager interface {
 	// Enabled returns true if manager is enabled.
 	Enabled() bool
 
-	// Start the config manager giving it a stopFunc callback
-	// so the beat can be told when to stop.
-	Start(stopFunc func())
-
-	// Stop the config manager.
+	// Start needs to invoked when the system is ready to receive an external configuration and
```
Comment (cmacknz) [inline libbeat/management/management.go:77]:
```suggestion
	// Start needs to be invoked when the system is ready to receive an external configuration and
```

File: libbeat/management/management.go [hunk 17]
```diff
@@ -74,22 +74,37 @@ type Manager interface {
...
+	// also ready to start ingesting new events. The manager expects that all the reloadable and
+	// reloadable list are fixed for the whole lifetime of the manager.
+	//
+	// Notes: Adding dynamically new reloadable hooks at runtime can lead to inconsistency in the
+	// execution.
+	Start() error
+
+	// Stop when this method is called, the manager will stop receiving new actions, no more action
+	// will be progated to the handlers and will not try to configure any reloadable parts.
+	// When the manager is stop the callback will be called to signal that the system can terminate.
```
Comment (cmacknz) [inline libbeat/management/management.go:87]:
```suggestion
	// When the manager is stopped the callback will be called to signal that the system can terminate.
```

**Comment by ph** [comment]
@oren-zohar When this PR is in, some changes will be required for cloudbeat, see either this PR changes in the beats or apm-server changes at https://github.com/elastic/apm-server/pull/7488

**Review by cmacknz — APPROVED** [review]

File: libbeat/management/management.go [hunk 18]
```diff
@@ -74,22 +74,37 @@ type Manager interface {
...
+	// When the manager is stopped the callback will be called to signal that the system can terminate.
+	//
+	// Calls to 'CheckRawConfig()' or 'SetPayload()' will be ignored after calling stop.
+	//
+	// Note: Stop will not call 'UnregisterAction()' automaticallty.
 	Stop()
 
+	// SetStopCallback accepts a function that need to be called when the manager want to shutdown the
+	// beats.
+	SetStopCallback(f func())
```
Comment (simitt) [inline libbeat/management/management.go:96]: When should a stop function be registered via this callback rather than providing the functionality in the [Beater `Stop()`](https://github.com/elastic/beats/blob/main/libbeat/beat/beat.go#L48-L50) function?

**Comment by ph** [comment]
@simitt Thanks, I've fixed the typo add added more information for the `SetStopCallback` see https://github.com/elastic/beats/pull/30694/files#diff-fcf0ac1927a6e4a560125bca3691cb6c27006277664735a58500420535fedc27R94

**Comment by ph** [comment]
It seems I've missed the alert of mergify concerning the conflict. I will make a followup PR.

**Comment by ph** [comment]
it seems, I've fixed that last week , time change are hard. :(
