### PR TITLE
[add_session_metadata processor] Keep exited processes in the process DB

### LINKED ISSUE #38955: [Security-Linux Platform Integrations]  Auditbeat missing Session View Process fields
Audibeat is missing process fields for Session View which is causing empty rows Sessions and Events Table.

I was testing the Session View on FE with auditbeat on my [PR](https://github.com/elastic/kibana/pull/179985). I just noticed some auditbeat events did not have Session View Icon. When I expand the event details,  I saw the process.entry_leader.entity_id  field  was missing.

To test  bug
See [Session View Cloud Credentials](https://p.elstc.co/paste/Ci0L3gSA#ASz3bkZps3AsJQyDlHDagExU2LK0-cLTuqc+aq/sf1E)

Steps to Reproduce
1. Go to Discover
2. Choose audibeat dataview
3. Apply fields not process.entry_leader.entity_id : * and event.action : "executed"
4. Click arrow icon and expand document details
image

1. Go to Explore > Hosts > Events or  Explore > Hosts > Sessions

Sessions are also Missing
image
Events are also missing
image

DOD
* For Session View events and sessions, process fields should be populated. Audibeat Index to filter documents that don't have `process.entry_leader.entity_id`  or missing Session View process fields.

### PR DESCRIPTION
**Pull request by mjwolf**
## Proposed commit message

With the add_session_metadata processor, don't remove processes from the process db when the process has exited.

The processor can be run on an fork/exec events after the process has actually exited, so the process must remain in the DB after it has exited, so the info can be used in enrichment of these events.

Now that the process is kept in the DB, the exit code is also appended on exit events, so the exit code can be used in enrichment of the exit events.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #38955

### CODE REVIEW

File: x-pack/auditbeat/processors/sessionmd/processdb/db.go [hunk 1]
```diff
@@ -406,9 +407,15 @@ func (db *DB) InsertExit(exit types.ProcessExitEvent) {
 	defer db.mutex.Unlock()
 
 	pid := exit.PIDs.Tgid
-	delete(db.processes, pid)
```
Comment (nicholasberlin) [inline x-pack/auditbeat/processors/sessionmd/processdb/db.go:409]: So, these will never be deleted, right? Won't that grow forever?

Comment (mjwolf) [reply x-pack/auditbeat/processors/sessionmd/processdb/db.go:409]: This will grow to `PID_MAX`, and then start to roll-over and replace older entries with new entries when new processes are created with reused PIDs.

Still I agree this could be unnecessarily large, I'll look into adding time-based eviction

Comment (pkoutsovasilis) [reply x-pack/auditbeat/processors/sessionmd/processdb/db.go:409]: I am writing this here as a source of inspiration https://github.com/elastic/beats/blob/main/libbeat/processors/add_process_metadata/cache.go#L86. In my perfect world this processor would be able to use the same process cache with the `add_process_metadata` processor, but definitely not for this one

Comment (mjwolf) [reply x-pack/auditbeat/processors/sessionmd/processdb/db.go:409]: I've change to use a goroutine that will run on a timer and clean up exited processes after at least 10s after they have exited. I think this should be more than enough to run the event enrichment, and then they aren't needed again.

@pkoutsovasilis I used a heap/priority queue instead of the list like in that other processor, because I think that times when the list of processes to remove gets very large will also be at times when CPU usage is very high, so it's probably worth it to use the more efficient data structure. For the `add_process_metadata` processor specifically, I don't think the processors will often run at the same time, since they mostly collect the same data, there's not going to be a need to run both

I've also now added a few test cases to exercise pid reuse scenarios.

Comment (pkoutsovasilis) [reply x-pack/auditbeat/processors/sessionmd/processdb/db.go:409]: sure @mjwolf this was just a pointer to how an existing code is doing it no objection in the approach you will choose.

> For the add_process_metadata processor specifically, I don't think the processors will often run at the same time, since they mostly collect the same data, there's not going to be a need to run both 

This is actually a really nice point and that's the reason why initially, when I first heard about this processor, I assumed this is gonna end up "extending" the `add_process_metadata` one but evidently my assumption was incorrect

**Review by pkoutsovasilis — APPROVED** [review]
lgtm
