### PR TITLE
Fix issue where autodiscover hints default configuration was not being copied.

### LINKED ISSUE #16540: [Filebeat] Elasticsearch Module w/ Kubernetes Autodiscover Causes Logs in Incorrect Fieldsets
**Issue:** Using the Filebeat Elasticsearch module in combination with Kubernetes autodiscover results in logs in the incorrect filesets or duplicate filesets:
image

**Expected behavior:** Each log message should only appear in the destination a single time, and it should have the appropriate fields associated with the fileset of that log (i.e. server, audit, deprecation, gc, etc.)

- Version: 7.6.0
- Operating System: GKE Container Optimized OS
- Steps to Reproduce: 
Deploying Filebeat using Filebeat Helm chart with values.yaml:
```
filebeat: 
  # Allows you to add any config files in /usr/share/filebeat
  # such as filebeat.yml
  filebeatConfig:
    filebeat.yml: |-
      filebeat.autodiscover:
       providers:
         - type: kubernetes
           node: ${NODE_NAME}
           hints.enabled: true

      processors:
        - add_cloud_metadata:
        - add_host_metadata:

      output.elasticsearch:
          hosts: 'http://${ELASTICSEARCH_ADDRESS}'
          username: ${ELASTICSEARCH_USERNAME}
          password: ${ELASTICSEARCH_PASSWORD}

  extraEnvs:
    - name: ELASTICSEARCH_USERNAME
      valueFrom: { secretKeyRef: { name: beats-elasticsearch, key: username } }
    - name: ELASTICSEARCH_PASSWORD
      valueFrom: { secretKeyRef: { name: beats-elasticsearch, key: password } }
    - name: ELASTICSEARCH_ADDRESS
      valueFrom: { secretKeyRef: { name: beats-elasticsearch, key: address } }

  imageTag: 7.6.0
  extraVolumeMounts: 
    - name: varlog
      mountPath: /var/log/
      readOnly: true

  extraVolumes: 
    - name: varlog
      hostPath:
        path: /var/log/
```
In this case Elasticsearch was deployed using ECK, with annotations in the podTemplate to enable the Elasticsearch module:
```
    podTemplate:
      metadata:
        annotations:
          co.elastic.logs/module: "elasticsearch"
```

I am attaching the filebeat.log file, the json of the documents from the above screenshot, and the contents of the bulk request that show the documents are being to the corresponding pipelines for each fileset (4 copies of the same document). 

The appropriate pipelines were installed in Elasticsearch prior to these logs being ingested:
image

[filebeat.log](https://github.com/elastic/beats/files/4248090/filebeat.log)
[bulk_request.txt](https://github.com/elastic/beats/files/4248135/bulk_request.txt)
[sample-docs.txt](https://github.com/elastic/beats/files/4248097/sample-docs.txt)

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

FIxes issue where when a default configuration is provided to autodiscovery in filebeat it would cause the elasticsearch module to have log messages repeated and appear in different datasets.

## Why is it important?

Without this change log messages would be repeated and reported in different datasets unless `hints.default_config.enabled: false` was set. Which also prevented filebeat from reading the logs of pods that didn't have the annotation of `co.elastic.logs/enabled: true`.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files~~
- ~~I have added tests that prove my fix is effective or that my feature works~~

## How to test this PR locally

1. Build the docker image `cd filebeat && PACKAGES="linux/amd64" mage package`
2. Push it to a registry (I used a personal private registry)
3. Use the image in the filebeat configurations:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    # To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_cloud_metadata:
      - add_host_metadata:

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    logging:
      level: debug
      metrics.enabled: false
      selectors:
        - "*"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
      annotations:
        co.elastic.logs/enabled: "false"
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: blake-creds
      containers:
      - name: filebeat
        image: blakerouse/elastic:filebeat-master
        args: [
          "run", "-c", "/etc/filebeat.yml", "-e"
        ]
        env:
        - name: ELASTIC_CLOUD_ID
          value: "***"
        - name: ELASTIC_CLOUD_AUTH
          value: "***"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
---
```

4. Deploy elasticsearch with the elasticsearch module set in the hints.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
  ES_JAVA_OPTS: -Xms256m -Xmx256m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/module: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 500Mi
          securityContext:
            privileged: true
            runAsUser: 1000
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
          env:
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: elasticsearch-config
                  key: ES_JAVA_OPTS
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 5
          ports:
            - containerPort: 9200
              name: es-http
            - containerPort: 9300
              name: es-transport
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - name: es-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
```

5. Check that the log messages are not repeated and are in the correct `event.dataset`.

## Related issues

- Closes #16540

### CODE REVIEW

File: filebeat/autodiscover/builder/hints/config.go [hunk 1]
```diff
@@ -59,7 +59,12 @@ func (c *config) Unpack(from *common.Config) error {
 			}
 		} else {
 			// full config provided, discard default
-			c.DefaultConfig = config
+			//
+			// must be a clone of the default config or the config will be
```
Comment (ChrsMark) [inline filebeat/autodiscover/builder/hints/config.go]: 1. Maybe to merge these two parts of the comments into one?
2. Is it a clone of the default or of the given config? What I understand is that it is a clone of the given config 🤔 

If my assumptions are correct I would structure the comment as below:

```
full config provided, discard default. It must be a clone of the given(?) config otherwise it will be updated...
```

Comment (blakerouse) [reply filebeat/autodiscover/builder/hints/config.go]: @ChrsMark you are correct, it is the given config.

I updated the comment to be similar to your suggestion

**Comment by blakerouse** [comment]
@ChrsMark @jsoriano This is ready for another look, thank!
