### PR TITLE
Report faulting file when config reload fails

### LINKED ISSUE #8122: Report file/source when parsing a config file fails
When the YAML parser fails to parse a config file, it only reports that a parsing error. When using config reloading of inputs and/or modules in filebeat/metricbeat, the error might be in any file. 

E.g. error log is:

```
cfgfile/reload.go:213 Error loading config: invalid config: yaml: line 9: could not find expected ':'
```

It should say

```
cfgfile/reload.go:213 Error loading config from '<source>': invalid config: yaml: line 9: could not find expected ':'
```

### PR DESCRIPTION
**Pull request by michalpristas**
Modifying error output when reload config fails from 

```
cfgfile/reload.go:213 Error loading config: invalid config: yaml: line 9: $err
```
to
```
cfgfile/reload.go:213 Error loading config from '<source>': $err
```

Fixes #8122

### CODE REVIEW

File: libbeat/cfgfile/reload.go [hunk 1]
```diff
@@ -35,6 +35,7 @@ import (
 )
 
 var (
+	// DefaultDynamicConfig provides default behavior for a Runner
```
Comment (ph) [inline libbeat/cfgfile/reload.go]: Thanks for cleaning up the godoc, can you add a dot after "Runner"?

File: libbeat/cfgfile/reload.go [hunk 2]
```diff
@@ -220,7 +225,7 @@ func (rl *Reloader) loadConfigs(files []string) ([]*reload.ConfigWithMeta, error
 		configs, err := LoadList(file)
 		if err != nil {
 			errs = append(errs, err)
-			logp.Err("Error loading config: %s", err)
+			logp.Err("Error loading config from '%s': %v", file, err)
```
Comment (ph) [inline libbeat/cfgfile/reload.go]: I would probably make a clear separation between the file and the error.
```
Error loading config from file '%s', error %v"
```
