### PR TITLE
Fix data race in Winlogbeat eventlog factory

### LINKED ISSUE #13005: Multiple instances of wineventlog in goroutines raise errors randomly.
When running multiple eventlog instances in >25% of execution errors occurs:

`Error New(): 2 errors: Invalid event log key 'api' found. Valid keys are batch_read_size, event_id, fields, fields, fields_under_root, forwarded, ignore_older, include_xml, level, name, processors, processors, provider, tags; Invalid event log key 'no_more_events' found. Valid keys are batch_read_size, event_id, fields, fields, fields_under_root, forwarded, ignore_older, include_xml, level, name, processors, processors, provider, tags`

`Error New(): 2 errors: Invalid event log key 'api' found. Valid keys are batch_read_size, event_id, fields, fields, fields_under_root, forwarded, ignore_older, include_xml, level, name, processors, processors, provider, tags; Invalid event log key 'no_more_events' found. Valid keys are batch_read_size, event_id, fields, fields, fields_under_root, forwarded, ignore_older, include_xml, level, name, processors, processors, provider, tags`

Error randomly refer to different valid field, ie. `Invalid event log key 'name' found.`, `Invalid event log key 'no_more_events' found` etc.

Looks like issue doesn't occur when running eventlog one after another (single go-routine) or when running with random sleep at the beginning for each goroutine.

- Version: v7.2.0
- Operating System: Windows 10 Enterprise (1903, build 18362.145)

Code:
```
    package main

    import (
        "fmt"
        "github.com/elastic/beats/libbeat/common"
        "github.com/elastic/beats/winlogbeat/checkpoint"
        "github.com/elastic/beats/winlogbeat/eventlog"
        "time"
    )

    func main() {
        channels := []string{"System", "Application", "Setup"}

        for _, ch := range channels {
            go func() {
                cfg, _ := common.NewConfigFrom(common.MapStr{
                    "name":            ch,
                    "api":             "wineventlog",
                    "no_more_events":  "wait",
                    "batch_read_size": 100,
                })

                st := checkpoint.EventLogState{}

                el, err := eventlog.New(cfg)
                if err != nil {
                    fmt.Printf("Error New(): %v\n", err)
                    return
                }

                err = el.Open(st)
                if err != nil {
                    fmt.Printf("Error Open(): %v\n", err)
                    return
                }

                for {
                    rec, _ := el.Read()
                    for _, r := range rec {
                        fmt.Printf("r=%#v\n", r)
                    }
                }
            }()
        }

        time.Sleep(10 * time.Second)

    }
```

### PR DESCRIPTION
**Pull request by andrewkroh**
The factory was sorting a global slice as part of its config validation. This removes the sorting and replaces it with a simpler (maybe less efficient) implementation.

Fixes #13005

### CODE REVIEW

File: winlogbeat/eventlog/factory.go [hunk 1]
```diff
@@ -48,19 +48,24 @@ func readConfig(
...
+		return fmt.Errorf("failed unpacking config. %v", err)
+	}
+
+	isValidKey := func(key string) bool {
+		for _, validKey := range validKeys {
+			if key == validKey {
+				return true
+			}
+		}
+		return false
```
Comment (urso) [inline winlogbeat/eventlog/factory.go]: See libbeat/common/stringset.go: `isValidKey := common.MakeStringSet(validKeys...).Has`

Comment (andrewkroh) [reply winlogbeat/eventlog/factory.go]: 👍  I've update this function to accept a StringSet instead.
