### PR TITLE
Copy missing go version to the generated Beats

### LINKED ISSUE #16951: Beat generator test and test-pacakge jobs on Travis are failing
The job `make -C generator/_templates/beat test test-package` is failing for the generators. I am disabling the jobs.

```
>> buildGoDaemon: Building for linux/amd64

>> golangCrossBuild: Building for windows/amd64

>> golangCrossBuild: Building for darwin/amd64

>> golangCrossBuild: Building for linux/386

>> golangCrossBuild: Building for linux/amd64

>> golangCrossBuild: Building for windows/386

>> buildGoDaemon: Building for linux/386

package ran for 21.585529427s

Error: failed to determine golang-crossbuild image tag: failed to read go version file=/home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: open /home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: no such file or directory

failed to determine golang-crossbuild image tag: failed to read go version file=/home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: open /home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: no such file or directory

failed to determine golang-crossbuild image tag: failed to read go version file=/home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: open /home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: no such file or directory

failed to determine golang-crossbuild image tag: failed to read go version file=/home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: open /home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: no such file or directory

failed to determine golang-crossbuild image tag: failed to read go version file=/home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: open /home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: no such file or directory

failed to determine golang-crossbuild image tag: failed to read go version file=/home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: open /home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: no such file or directory

failed to determine golang-crossbuild image tag: failed to read go version file=/home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: open /home/travis/gopath/src/beatpath/testmetricbeat/vendor/github.com/elastic/beats/v7/.go-version: no such file or directory

make: *** [test-package] Error 1

make: Leaving directory `/home/travis/gopath/src/github.com/elastic/beats/generator/_templates/metricbeat'
```

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

This PR makes beat generator copy `.go-version` to the vendored beats folder as it is not copied automatically.

## Why is it important?

If the file `.go-version` is missing, the beat cannot be generated and package properly.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works

## How to test this PR locally

```
$ make -C generator/_templates/beat test test-package
```

## Related issues

- Closes elastic/beats#16951

### CODE REVIEW

File: dev-tools/mage/gomod.go [hunk 1]
```diff
@@ -74,32 +74,40 @@ func Vendor() error {
...
+	err = CopyFilesToVendor(vendorFolder, copyAll)
+	if err != nil {
+		return err
+	}
+
+	for _, p := range filesToRemove {
+		p = filepath.Join(vendorFolder, p)
+		err = os.RemoveAll(p)
+		if err != nil {
+			return err
```
Comment (fearful-symmetry) [inline dev-tools/mage/gomod.go]: Can we use `errors.Wrap()` here?

**Comment by kvch** [comment]
Relevant tests are green.
