### PR TITLE
Make import_dashboards always exit 0 on errors

### LINKED ISSUE #3027: import_dashboards script return code and logging
For confirmed bugs, please report:
- Version: 5.0.1
- Operating System: Debian 8
- Steps to Reproduce: Install Filebeat, Stop Elasticsearch, import dashboards

if the script fails (for example, ES is not running), it exits with a `0` code, instead of anything `> 0`, and it prints messages to `stdout` instead of `stderr`.

```
root@default:/usr/share/filebeat/scripts# ./import_dashboards
fail to set the mapping. Error: Put http://127.0.0.1:9200/.kibana/_mapping/search: dial tcp 127.0.0.1:9200: getsockopt: connection refused
Create temporary directory /tmp/tmp053241378
Downloading https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-5.0.1.zip
Unzip archive  /tmp/tmp053241378
/tmp/tmp053241378/beats-dashboards-5.0.1/filebeat
Import directory  /tmp/tmp053241378/beats-dashboards-5.0.1/filebeat/index-pattern
Import index to /.kibana/index-pattern/filebeat-* from /tmp/tmp053241378/beats-dashboards-5.0.1/filebeat/index-pattern/filebeat.json
ERROR:  couldn't load json. Error: Put http://127.0.0.1:9200/.kibana/index-pattern/filebeat-*: dial tcp 127.0.0.1:9200: getsockopt: connection refused
fail to import index-pattern: fail to load directory /tmp/tmp053241378/beats-dashboards-5.0.1/filebeat/index-pattern: error loading /tmp/tmp053241378/beats-dashboards-5.0.1/filebeat/index-pattern/filebeat.json: couldn't load json. Error: Put http://127.0.0.1:9200/.kibana/index-pattern/filebeat-*: dial tcp 127.0.0.1:9200: getsockopt: connection refused

root@default:/usr/share/filebeat/scripts# echo $?
0
```

### PR DESCRIPTION
**Pull request by autarch**
I also did a little bit of grammar fixing on the error messages while I was in there.

Fixes #3027

### CODE REVIEW

**Comment by autarch** [comment]
Actually, this only partially fixes #3027. The errors are still going to `stdout` instead of `stderr`. Fixing that is a little more work, and I think would benefit from having someone review _all_ the output from this script to determine where it should go. It might also make sense to have a `--quiet` option to suppress info messages going to `stdout` entirely.

File: libbeat/dashboards/import_dashboards.go [hunk 1]
```diff
@@ -677,11 +676,13 @@ func main() {
 	if importer.cl.opt.Dir != "" {
 		if err = importer.ImportKibana(importer.cl.opt.Dir); err != nil {
 			fmt.Println(err)
+			os.Exit(1)
```
Comment (andrewkroh) [inline libbeat/dashboards/import_dashboards.go]: Throughout the main method where error logging is performed I think this should go to stderr (IIRC `fmt.Fprintln(os.stderr, ...)`).

File: libbeat/dashboards/import_dashboards.go [hunk 2]
```diff
@@ -211,7 +211,7 @@ func (imp Importer) CreateIndex() error {
 			},
 		})
 	if err != nil {
-		fmt.Printf("fail to set the mapping. Error: %s\n", err)
+		fmt.Printf("failed to set the mapping. Error: %s\n", err)
```
Comment (andrewkroh) [inline libbeat/dashboards/import_dashboards.go]: I wonder why this is only logging an error and not returning it. @monicasarbu do you know?

We should write this to stderr if it's not going to be returned.

Comment (autarch) [inline libbeat/dashboards/import_dashboards.go]: Three are a few other places where it prints directly to `stdout` for error besides this. The script overall is not terribly consistent about this sort of thing.

File: libbeat/dashboards/import_dashboards.go (hunk 1 above)
Comment (autarch) [inline libbeat/dashboards/import_dashboards.go]: I agree that errors should be going to stderr. That said, I think this PR is an improvement as-is, since it at least standardizes the exit codes on error.

**Comment by andrewkroh** [comment]
@autarch Thanks for the PR!

**Comment by autarch** [comment]
The test failure looks to me like it might be revealing a previous bug. Is is possible that this load test never actually worked but the failure was being masked by `import_dashboards` returning 0 even when it failed in some cases? I pushed a change so we can at least see the script output when it fails.

**Comment by autarch** [comment]
Alright, my latest commit definitely suggests that problem already existed and just was going unreported. The relevant bit of logs is ...

```
======================================================================
FAIL: Test loading dashboards for all beats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/libbeat/tests/system/test_dashboard.py", line 33, in test_load_dashboard
    self.assertEqual(p.returncode, 0, "stdout:\n{}\n\nstderr:{}\n".format(content, err))
AssertionError: stdout:
failed to import index-pattern: No directory ../../../metricbeat/etc/kibana/index-pattern
stderr:exit status 1
```

I have no idea how to fix this though. Should the test harness be creating the relevant files or is something else going wrong?

**Comment by andrewkroh** [comment]
Looks like that test was bad since it was testing the return code.

Anyways I think the fix is to change the `etc/kibana` to `_meta/kibana` in the `test_load_dashboard` code.

**Comment by autarch** [comment]
Switching to `_meta/kibana` didn't help. The files that `import_dashboard` looks for don't appear to exist in the repo at all. I think the test code needs to run `libbeat/scripts/generate_index_pattern.py` first.

**Comment by autarch** [comment]
But then that python script wants a file called `fields.yml`. However, that file doesn't exist for `filebeat` or `metricbeat` and I'm not sure exactly what generates it.

**Comment by andrewkroh** [comment]
Yeah, I think there was a recent change to not have the generated files checked into the repo. And now there is a dependency problem since a test case in libbeat depends on the `collect` target being run in each of the beat directories first.

@ruflin How do you want to handle this?

File: libbeat/dashboards/import_dashboards.go (hunk 2 above)
Comment (monicasarbu) [inline libbeat/dashboards/import_dashboards.go]: Ignoring the error here is by intention as `CreateIndex` might return an error if the index already has those settings. It might make sense to prepend "Info:" or "Warning:" to it to avoid confusion.

File: libbeat/dashboards/import_dashboards.go [hunk 3]
```diff
@@ -448,16 +448,15 @@ func (imp Importer) ImportDir(dirType string, dir string) error {
 	// check if the directory exists
 	if _, err := os.Stat(dir); err != nil {
 		// nothing to import
-		fmt.Println("No directory", dir)
-		return nil
+		return fmt.Errorf("No directory %s", dir)
```
Comment (monicasarbu) [inline libbeat/dashboards/import_dashboards.go]: Ignoring the error here was also intentional because some beats (e.g. Filebeat) only have the index-pattern but not the dashboard folder. If we return an error here, we make the script always return non-zero for Filebeat.

Comment (autarch) [inline libbeat/dashboards/import_dashboards.go]: The directory not existing should be an error, though. All the beats have a `_meta` dir. Seems like this should give an error on a missing directory and maybe just an info notice on a missing file.

Comment (autarch) [inline libbeat/dashboards/import_dashboards.go]: Oh, I see, this isn't the `_meta` dir, it's another directory further down the tree. I'll update this PR to account for this and the other non-error error.

Comment (autarch) [inline libbeat/dashboards/import_dashboards.go]: Actually, shouldn't passing a non-existent dir to this script be an error? I think the fix here is to make the test harness a bit smarter. It shouldn't blindly construct a path that doesn't exist and pass it to the `import_dashboards` code.

Comment (autarch) [inline libbeat/dashboards/import_dashboards.go]: Talking to myself is probably a sign of impending mental collapse but ... ok, I see the problem. The `ImportDir` method is called for different types of things which may or may not exist for a given beat.

To make things more complicated, AFAICT _none_ of the beats have a checked-in `index-pattern` dir. However, several of them have `dashboard` dirs and in fact some of them have per-module `dashboard` dirs. These latter cases are going to be missed by the test harness entirely, since it just passes `{beat}/_meta` to `import_dashboards`. I think what it _should_ be doing is finding all of the relevant subdirs and passing those one at a time to test them all.

So here's how I think this should work ...

* The `ImportDir` method should not return an error if the directory doesn't exist, but ...
  * The `ImportKibana` sub should check that the dir it is given exists and return an error if it doesn't.
* The test harness needs to be much smarter, finding all the relevant dirs for each beat and passing them one at a time.
* The test harness needs to call `libbeat/scripts/generate_index_pattern.py` for each beat so those can be imported as well.

Comment (monicasarbu) [inline libbeat/dashboards/import_dashboards.go]: We decided not to commit the index-pattern and generate it every time is needed. To generate the index-pattern for a Beat, we just need to call `make update`. So, in order to fix the test, we just need to find a way to call this before running test. @ruflin knows more here.

As not all the Beats have a dashboard in the latest [beats-dashboards 5.1.1](https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-5.1.1.zip) (see missing `filebeat/dashboard`), but all of them must have an `index-pattern` directory, we can raise an error only if the `index-pattern` directory is not available, and ignore or use `INFO` level in case the`dashboard` directory is not available.

Thank you @autarch for raising all these issues. I agree that there are a few points that we need to reconsider. We are planning to migrate the `import_dashboards` script to the Beat, so the user doesn't have to run an extra step to import the dashboards. This would be a good opportunity to improve the way we import the dashboards. 

Let's wait for @ruflin to find a way to fix the test, and then we see how we can proceed with the PR.

Comment (autarch) [inline libbeat/dashboards/import_dashboards.go]: I did some work on this in the meantime to clean up the error handling and outputting of status messages, so I pushed that. Even if this PR can't be merged as-is, it might be useful for someone else doing the change you talked about to move `import_dashboards`.

**Comment by autarch** [comment]
Note that 9fded29 fixes the rest of #3027, sending all error output to `os.stderr`.

File: libbeat/dashboards/import_dashboards.go [hunk 4]
```diff
@@ -639,49 +645,77 @@ func (imp Importer) ImportArchive() error {
...
+	}
+
+	types := []string{}
+	for _, c := range check {
+		if imp.subdirExists(dir, c) {
+			types = append(types, c)
+		}
+	}
+
+	if len(types) == 0 {
```
Comment (monicasarbu) [inline libbeat/dashboards/import_dashboards.go]: In case the script is run for Filebeat with the `-only-dashboards` argument, it shouldn't return an error as there aren't dashboards to import.

**Comment by ruflin** [comment]
@andrewkroh @autarch This is kind of related to https://github.com/elastic/beats/pull/2980 These tests need some cleanup. It is kind of strange that libbeat needs to know about the other beats when running the tests. I think it shouldn't and we should probably have a generic test in libbeat itself and one that can be extended for each beat with loading the dashboards.

Unfortunately such a cleanup blocks this PR. Alternative is to skip this test for the moment.

@maddin2016 As you spent quite some time with this, perhaps you have some other thoughts how we could handle this?

**Comment by maddin2016** [comment]
Hi @ruflin, actually the problem is that `import_dashboards.go` always return `0`. I think we should skip this tests for the moment until this PR is merged and then we can go on to investigate further on the tests. I also agree with you that every beat should have its own test scenario because not all of them work with the same config (see filebeat for example).

**Comment by maddin2016** [comment]
One question i have. In the script dashboards and index-patterns are loaded from a folder `etc\kibana`. Are these folders created during build?

**Comment by andrewkroh** [comment]
So it sounds like to move forward here we should disable/skip the dashboard test that is in libbeat and merge this PR. And open a new issue to track the need to move the dashboard test from libbeat to the individual beats.

File: libbeat/dashboards/import_dashboards.go (hunk 4 above)
Comment (autarch) [inline libbeat/dashboards/import_dashboards.go]: It seems odd to me to not return an error. If you tell the script you want it to do X and it can't do X, shouldn't it return an error?

**Comment by tsg** [comment]
@maddin2016 can you skip the test for now so we can merge this PR, please? We're planning to move the `imports_dashboard` code in the beat themselves for the next release, and we'll redesign the test with that occasion. You can skip by adding the `@unittest.skip` decorator.

**Comment by tsg** [comment]
Oops, I meant @autarch in the above ^. Sorry.

**Comment by autarch** [comment]
@tsg - done.

**Comment by andrewkroh** [comment]
Created #3370 to track the refactoring work.
