### PR TITLE
[azure-eventhub] Fix handling of connection strings with entity path

### LINKED ISSUE #43715: [azure-eventhub] Processor v2 doesn't support connection string format with entity path
With processor v2, if I use the connection string format that includes the entity path:

```text
Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-access-key;SharedAccessKey=[redacted];EntityPath=my-event-hub
```

The input fails to start with the following error:

```text
Input 'azure-eventhub' failed with: failed to create consumer client: connection string contains an EntityPath. eventHub must be an empty string
```

### PR DESCRIPTION
**Pull request by zmoog**
## Proposed commit message

Fix entity path handling in the event hub connection string (v1 and v2 processors).

For context on this issue, see https://github.com/elastic/beats/issues/43715.

Changes:

- v1 & v2: fully parse the connection string for validation and to check the event hub name and entity path match.
- v2: handle event hub name and connection string according to the new Event Hub SDK requirements to support all connection string formats.

Unrelated changes:

- I had to fix an unrelated problem to `metricbeat/module/windows/service/service_integration_test.go` to make the linter happy again.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #43715

### CODE REVIEW

File: x-pack/filebeat/input/azureeventhub/config_test.go [hunk 1]
```diff
@@ -55,3 +55,92 @@ func TestValidate(t *testing.T) {
...
+		config.ProcessorVersion = "v1"
+		config.ConnectionString = "Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-key;SharedAccessKey=my-secret;EntityPath=my-event-hub;"
+		config.EventHubName = "my-event-hub"
+		config.SAName = "teststorageaccount"
+		config.SAKey = "my-secret"
+		config.SAContainer = "filebeat-activitylogs-event_hub_00"
+
+		if err := config.Validate(); err != nil {
+			t.Fatalf("unexpected validation error: %v", err)
+		}
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/config_test.go:71]: [NIT]
As you're already using testify, you could instead use `require`

```suggestion
		err := config.Validate()
		require.NoError(t, err, "unexpected validation error)
		
```

File: x-pack/filebeat/input/azureeventhub/config_test.go [hunk 2]
```diff
@@ -55,3 +55,92 @@ func TestValidate(t *testing.T) {
...
+
+		assert.NotNil(t, config.ConnectionStringProperties.EntityPath)
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/config_test.go:73]: This will still panic in the check below if `config.ConnectionStringProperties.EntityPath`. Please use `require`, so it'll abort the test here.
```suggestion
		require.NotNil(t, config.ConnectionStringProperties.EntityPath)
```

File: x-pack/filebeat/input/azureeventhub/config_test.go [hunk 3]
```diff
@@ -55,3 +55,92 @@ func TestValidate(t *testing.T) {
...
+		config.ProcessorVersion = "v1"
+		config.ConnectionString = "Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-key;SharedAccessKey=my-secret"
+		config.EventHubName = "my-event-hub"
+		config.SAName = "teststorageaccount"
+		config.SAKey = "my-secret"
+		config.SAContainer = "filebeat-activitylogs-event_hub_00"
+
+		if err := config.Validate(); err != nil {
+			t.Fatalf("unexpected validation error: %v", err)
+		}
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/config_test.go:88]: [NIT]
same, you could use `require` here

File: x-pack/filebeat/input/azureeventhub/config_test.go [hunk 4]
```diff
@@ -55,3 +55,92 @@ func TestValidate(t *testing.T) {
...
+		config.EventHubName = "my-event-hub"
+		config.SAName = "teststorageaccount"
+		config.SAConnectionString = "DefaultEndpointsProtocol=https;AccountName=teststorageaccount;AccountKey=my-secret;EndpointSuffix=core.windows.net"
+		config.SAContainer = "filebeat-activitylogs-event_hub_00"
+
+		if err := config.Validate(); err != nil {
+			t.Fatalf("unexpected validation error: %v", err)
+		}
+
+		assert.NotNil(t, config.ConnectionStringProperties.EntityPath)
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/config_test.go:108]: Same as above
```suggestion
		require.NotNil(t, config.ConnectionStringProperties.EntityPath)
```

File: x-pack/filebeat/input/azureeventhub/config_test.go [hunk 5]
```diff
@@ -55,3 +55,92 @@ func TestValidate(t *testing.T) {
...
+		config.ProcessorVersion = "v2"
+		config.ConnectionString = "Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-key;SharedAccessKey=my-secret;"
+		config.EventHubName = "my-event-hub"
+		config.SAName = "teststorageaccount"
+		config.SAConnectionString = "DefaultEndpointsProtocol=https;AccountName=teststorageaccount;AccountKey=my-secret;EndpointSuffix=core.windows.net"
+		config.SAContainer = "filebeat-activitylogs-event_hub_00"
+
+		if err := config.Validate(); err != nil {
+			t.Fatalf("unexpected validation error: %v", err)
+		}
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/config_test.go:123]: same, you can use require here

File: x-pack/filebeat/input/azureeventhub/config_test.go [hunk 6]
```diff
@@ -55,3 +55,92 @@ func TestValidate(t *testing.T) {
...
+		config.SAName = "teststorageaccount"
+		config.SAConnectionString = "DefaultEndpointsProtocol=https;AccountName=teststorageaccount;AccountKey=my-secret;EndpointSuffix=core.windows.net"
+		config.SAContainer = "filebeat-activitylogs-event_hub_00"
+
+		err := config.Validate()
+		if err == nil {
+			t.Fatalf("expected validation error")
+		}
+
+		assert.NotNil(t, config.ConnectionStringProperties.EntityPath)
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/config_test.go:142]: same, please use `require` to prevent a panic after this check

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+
+	splits := strings.Split(connStr, ";")
+
+	for _, split := range splits {
+		if split == "" {
+			continue
+		}
+
+		keyAndValue := strings.SplitN(split, "=", 2)
+		if len(keyAndValue) < 2 {
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/connection_string.go:74]: [Blocker]

Looking at the test above, won't it introduce a breaking change?
In the test the connection string was:
```
sb://test-ns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SECRET
```

now it's

```
Endpoint=sb://test-ns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SECRET
```

The former won't pass this check, and if there are configs using the former format, wouldn't it make this a breaking change?

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 8]
```diff
@@ -0,0 +1,133 @@
...
+		case strings.EqualFold(sharedAccessKeyKey, key):
+			csp.SharedAccessKey = &value
+		case strings.EqualFold(entityPathKey, key):
+			csp.EntityPath = &value
+		case strings.EqualFold(sharedAccessSignatureKey, key):
+			csp.SharedAccessSignature = &value
+		case strings.EqualFold(useEmulator, key):
+			v, err := strconv.ParseBool(value)
+
+			if err != nil {
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/connection_string.go:100]: [NIT]
```suggestion
			v, err := strconv.ParseBool(value)
			if err != nil {
```

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 9]
```diff
@@ -0,0 +1,133 @@
...
+		return ConnectionStringProperties{}, fmt.Errorf("key %q must not be empty", endpointKey)
+	}
+
+	if csp.SharedAccessSignature == nil && csp.SharedAccessKeyName == nil {
+		return ConnectionStringProperties{}, fmt.Errorf("key %q must not be empty", sharedAccessKeyNameKey)
+	}
+
+	if csp.SharedAccessKey == nil && csp.SharedAccessSignature == nil {
+		return ConnectionStringProperties{}, fmt.Errorf("key %q or %q cannot both be empty", sharedAccessKeyKey, sharedAccessSignatureKey)
+	}
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/connection_string.go:130]: [Suggestion]
Perform all checks and accumulate the errors to return them all at once. It's rather frustrating from the user perspective to fix a validation error just to discover there is still another to be fixed.

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 7 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:74]: The previous connection string version (starting with `sb://test-ns.servicebus.windows.net...`) was invalid. 

The test was passing because the previous `Validate()` implementation only [checked](https://github.com/elastic/beats/blob/b4e461107f38b7a28bd92d6378773e602356accd/x-pack/filebeat/input/azureeventhub/config.go#L120-L122) that the connection string wasn't empty, instead of trying to parse it. 

According to the [EventHubConnectionStringProperties](https://learn.microsoft.com/en-us/java/api/com.azure.messaging.eventhubs.models.eventhubconnectionstringproperties?view=azure-java-stable) page:

> An Event Hubs connection string is a set of key-value pairs separated by semicolon. A typical example is "Endpoint=sb://foo.EventHub.windows.net/;SharedAccessKeyName=someKeyName;SharedAccessKey=someKeyValue".
> 
> A connection may have the following sections:
> 
> - Endpoint, which is mandatory. The fully qualifed namespace of the Event Hubs namespace. It will look similar to "{your-namespace}.servicebus.windows.net"
> - SharedAccessKeyName and SharedAccessKey, optional, used to authenticate the access to the Event Hubs namespace or Event Hub instance.
> - EntityPath, optional, the name of the Event Hub instance.
> - SharedAccessSignature, optional, an alternative way to authenticate the access to an Event Hub instance.

File: x-pack/filebeat/input/azureeventhub/config_test.go (hunk 1 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/config_test.go:71]: Great point, `require` is much better. Applying them all..

File: x-pack/filebeat/input/azureeventhub/config_test.go (hunk 3 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/config_test.go]: Replaced with `require`.

File: x-pack/filebeat/input/azureeventhub/config_test.go (hunk 5 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/config_test.go]: Replaced with `require`.

File: x-pack/filebeat/input/azureeventhub/config_test.go (hunk 6 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/config_test.go]: Replaced with `require`.

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 9 above)
Comment (Kavindu-Dodan) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:129]: Yeah good point on accumulating errors. But could be a follow up to improve the error message to reduce scope of the PR :)

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+// ParseConnectionString takes a connection string from the Azure portal and returns the
+// parsed representation.
+//
+// There are two supported formats:
+//
+//  1. Connection strings generated from the portal (or elsewhere) that contain an embedded key and keyname.
+//
+//  2. A connection string with an embedded SharedAccessSignature:
+//     Endpoint=sb://<sb>.servicebus.windows.net;SharedAccessSignature=SharedAccessSignature sr=<sb>.servicebus.windows.net&sig=<base64-sig>&se=<expiry>&skn=<keyname>"
+func parseConnectionString(connStr string) (ConnectionStringProperties, error) {
```
Comment (Kavindu-Dodan) [inline x-pack/filebeat/input/azureeventhub/connection_string.go:54]: nit (not needed now)  - Testing

I see this is moved from another place (+1 for isolation of logic). I see tests covering most of the parsing scenarios. But we could add dedicated tests focusing on `parseConnectionString`. Anyway this is not a blocker and could be a followup

**Review by Kavindu-Dodan — APPROVED** [review]
Overall looks fine :)

File: x-pack/filebeat/input/azureeventhub/config.go [hunk 11]
```diff
@@ -117,9 +120,24 @@ func defaultConfig() azureInputConfig {
...
-	if conf.ConnectionString == "" {
-		return errors.New("no connection string configured")
+
+	connectionStringProperties, err := parseConnectionString(conf.ConnectionString)
+	if err != nil {
+		return fmt.Errorf("invalid connection string: %w", err)
+	}
+	// Store the parsed connection string, so we can use it
+	// later in the input, when needed.
+	conf.ConnectionStringProperties = connectionStringProperties
```
Comment (faec) [inline x-pack/filebeat/input/azureeventhub/config.go:130]: This use of Validate to precache essential data makes me uncomfortable... I don't think it's a bug in this case, since your config struct is private and you can ensure that configs are only generated by explicitly unpacking, but it adds a confusing implicit sequencing dependency. For example I'd expect that a test should be able to call `newEventHubInputV2` with a valid config, but the way things are written here it would break unless the config was rewritten as yaml and then manually unpacked first.

I'd prefer that the cached connection string data wasn't in the user config struct at all, but if the field is there, can we at least initialize it in `newEventHubInput*`? Validation can be done with an uncached local copy (precalculating in this case is for code simplicity not performance, so there's no harm in parsing the string twice).

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+		}
+
+		keyAndValue := strings.SplitN(split, "=", 2)
+		if len(keyAndValue) < 2 {
+			return ConnectionStringProperties{}, errors.New("failed parsing connection string due to unmatched key value separated by '='")
+		}
+
+		// if a key value pair has `=` in the value, recombine them
+		key := keyAndValue[0]
+		value := strings.Join(keyAndValue[1:], "=")
```
Comment (faec) [inline x-pack/filebeat/input/azureeventhub/connection_string.go:80]: Isn't the Join here superfluous since the SplitN parameter above ensures only the first = produces a split?

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 13]
```diff
@@ -0,0 +1,132 @@
...
+			// (we don't need to validate it's a valid host since it's been through url.Parse() above)
+			return ConnectionStringProperties{}, fmt.Errorf("UseDevelopmentEmulator=true can only be used with sb://<emulator hostname> or sb://<emulator hostname>:<port number>, not %s", csp.Endpoint)
+		}
+	}
+
+	if csp.FullyQualifiedNamespace == "" {
+		return ConnectionStringProperties{}, fmt.Errorf("key %q must not be empty", endpointKey)
+	}
+
+	if csp.SharedAccessSignature == nil && csp.SharedAccessKeyName == nil {
```
Comment (faec) [inline x-pack/filebeat/input/azureeventhub/connection_string.go:123]: Couldn't these be non-nil but still empty strings? (and below)

**Comment by zmoog** [comment]
Hey @AndersonQ, @faec, thank you so much for reviewing this PR! 🙇 

I tried to cut some corners to meet a FF, but it's not worth it since we have a workaround for this issue.

I will rework the `ConnectionStringProperties` and the internal code I copied from the Microsoft libraries to parse the connection string. And I'll request a new review when ready.

Moving the status back to draft.

**Comment by zmoog** [comment]
@Kavindu-Dodan @faec @AndersonQ I'm resuming this after a while to wrap it up! 😇 

Changes:

- Removed cached `connectionStringProperties` from the `azureInputConfig` struct: optimizing for simplicity vs. marginal efficiency. Running this function twice is not a big deal since it only runs during the input setup.
- Addressed two glaring `parseConnectionString()` limitations:
  - return all the errors found during the validation instead of just the first one;
  - check for empty values in addition to nils.

The initial version of the `parseConnectionString()` function was a fork of the internal function that [ships](https://github.com/Azure/azure-sdk-for-go/blob/5afb31a43f6743fca462faed6a02e32e8147530f/sdk/messaging/azeventhubs/internal/exported/connection_string_properties.go#L51) with the Azure SDK for Go. Do you think there are other pitfalls worth addressing?

Added a couple of comments to track old side-effects that we may want to remove later on.

File: x-pack/filebeat/input/azureeventhub/config_test.go [hunk 14]
```diff
@@ -55,3 +54,91 @@ func TestValidate(t *testing.T) {
...
+		config.ConnectionString = "Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-key;SharedAccessKey=my-secret;EntityPath=my-event-hub"
+		config.EventHubName = "not-my-event-hub"
+		config.SAName = "teststorageaccount"
+		config.SAConnectionString = "DefaultEndpointsProtocol=https;AccountName=teststorageaccount;AccountKey=my-secret;EndpointSuffix=core.windows.net"
+		config.SAContainer = "filebeat-activitylogs-event_hub_00"
+
+		err := config.Validate()
+		require.Error(t, err)
+		assert.ErrorContains(t, err, "invalid config: the entity path (my-event-hub) in the connection string does not match event hub name (not-my-event-hub)")
+	})
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/config_test.go]: [NIT]
 - you don't need to ensure the error is not `nil` before calling `assert.ErrorContains`

File: x-pack/filebeat/input/azureeventhub/config_test.go [hunk 15]
```diff
@@ -55,3 +54,91 @@ func TestValidate(t *testing.T) {
 		)
 	})
 }
+
+func TestValidateConnectionStringV1(t *testing.T) {
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/config_test.go:58]: Shouldn't the V1 also have a test for mismatching entity name and event hub name?

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 12 above)
Comment (AndersonQ) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:98]: yeah, why are you joining again?
perhaps [Cut](https://pkg.go.dev/strings#Cut) is what you're looking for?

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 16]
```diff
@@ -0,0 +1,146 @@
...
+		}
+
+		// if a key value pair has `=` in the value, recombine them
+		key := keyAndValue[0]
+		value := strings.Join(keyAndValue[1:], "=")
+		switch {
+		case strings.EqualFold(endpointKey, key):
+			u, err := url.Parse(value)
+			if err != nil {
+				return ConnectionStringProperties{}, errors.New("failed parsing connection string due to an incorrectly formatted Endpoint value")
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/connection_string.go]: [Suggestion]
is it a problem to return the endpoint? Could it have sensitive information? If not, I believe it'd be helpful to have the endpoint on the error

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 17]
```diff
@@ -0,0 +1,146 @@
...
+	}
+
+	if csp.Emulator {
+		endpointParts := strings.SplitN(csp.Endpoint, ":", 3) // allow for a port, if it exists.
+
+		if len(endpointParts) < 2 || endpointParts[0] != "sb" {
+			// there should always be at least two parts "sb:" and "//<emulator hostname>"
+			// with an optional 3rd piece that's the port "1111".
+			// (we don't need to validate it's a valid host since it's been through url.Parse() above)
+			// return ConnectionStringProperties{}, fmt.Errorf("UseDevelopmentEmulator=true can only be used with sb://<emulator hostname> or sb://<emulator hostname>:<port number>, not %s", csp.Endpoint)
```
Comment (AndersonQ) [inline x-pack/filebeat/input/azureeventhub/connection_string.go]: did u forget to remove it?
```suggestion
```

File: x-pack/filebeat/input/azureeventhub/connection_string.go [hunk 18]
```diff
@@ -0,0 +1,146 @@
...
+// or more contributor license agreements. Licensed under the Elastic License;
+// you may not use this file except in compliance with the Elastic License.
+
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License.
+//
+// This code is a modified version of the code from the Azure SDK for Go.
+//
+// The original code is available at:
+// https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/internal/exported/connection_string_properties.go
```
Comment (Kavindu-Dodan) [inline x-pack/filebeat/input/azureeventhub/connection_string.go:20]: IANAL but since we burrowed the code we should do one of the below,

- Include Azure go SDK license header here
- Update NOTICE.txt with code path and add the license to there 

Azure Go SDK is released under MIT - https://github.com/Azure/azure-sdk-for-go/blob/main/LICENSE.txt

Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:20]: Headers: I agree, and I tried. However, github.com/elastic/go-licenser wants the Elastic license as the first thing in the file, and the validation fails.

So I decided not to contradict github.com/elastic/go-licenser and:

- Left Elastic header first.
- Added the Microsoft header from the original [connection_string_properties.go](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/internal/exported/connection_string_properties.go) file second.

For the NOTICE.txt, the Beats machinery already automatically adds the full license for each package listed as a dependency, including `sdk/messaging/azeventhubs`. Do you think this doesn't cover this case?

**Comment by zmoog** [comment]
> feel free to ignore them if you'd like.

@AndersonQ, oh, this is not going to happen!

File: x-pack/filebeat/input/azureeventhub/config_test.go (hunk 14 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/config_test.go]: Right, `require.Error(t, err)` is redundant here since `assert.ErrorContains()` can take care of it.

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 12 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:98]: This code comes from the Azure SDK. I copied here because the [original package](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/internal/exported/connection_string_properties.go) is internal, and I cannot use it. However, I wanted to apply the same parsing the SDK performs down the line.

My initial idea was using it like an external library, and maybe even replace it in the future, if new Azure SDK versions ship an improved revision.

Do you think we should fully own it—making all the required changes?

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 16 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/connection_string.go]: Good point. The endpoint contains Event Hubs namespace, which I don't think it qualifies as sensitive information. I think it's something we can include in the error.

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 8 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:118]: Fixed.

File: x-pack/filebeat/input/azureeventhub/config_test.go (hunk 15 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/config_test.go:58]: Yep, I missed it. Thanks!

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 13 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/connection_string.go]: Yeah, added check for empty strings.

File: x-pack/filebeat/input/azureeventhub/config.go (hunk 11 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/config.go]: Yeah, you're right. Removed!

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 18 above)
Comment (Kavindu-Dodan) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:20]: Good points on beats machinery & sdk deps. I think that should be sufficient. May be additionally say something like `check NOTICE.txt for full licence details`.

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 12 above)
Comment (AndersonQ) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:98]: It works as it's, this is the most important thing for me.
As you're taking it from the SDK, I'd add a comment to say it's that way because it comes  from the SDK.

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 16 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/connection_string.go]: Added.

File: x-pack/filebeat/input/azureeventhub/connection_string.go (hunk 12 above)
Comment (zmoog) [reply x-pack/filebeat/input/azureeventhub/connection_string.go:98]: Added a note at the beginning of the file to clarify the content: https://github.com/elastic/beats/blob/9af78554ea3d7d2d693bca2fd3a3f23c21cb7870/x-pack/filebeat/input/azureeventhub/connection_string.go#L10-L20
