### PR TITLE
auditd: Fix kernel deadlock after ENOBUFS

### LINKED ISSUE #26031: Auditbeat: kauditd deadlocks when netlink channel is congested during startup
If the netlink channel used to talk to kauditd is congested, Auditbeat's auditd module initialization can fail when setting the Audit PID:

```
2021-05-28T16:59:12.545Z	ERROR	[auditd]	auditd/audit_linux.go:154	Failure receiving audit events	{"error": "failed to set audit PID (current audit PID 0): error receiving audit reply: no buffer space available", "errorVerbose": "no buffer space available\nerror receiving audit reply\ngithub.com/elastic/go-libaudit/v2.(*AuditClient).getReply\n\t/home/azureuser/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:492\ngithub.com/elastic/go-libaudit/v2.(*AuditClient).set\n\t/home/azureuser/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:531\ngithub.com/elastic/go-libaudit/v2.(*AuditClient).SetPID\n\t/home/azureuser/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:323\ngithub.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).initClient\n\t/home/azureuser/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:358\ngithub.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).receiveEvents\n\t/home/azureuser/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:386\ngithub.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).Run\n\t/home/azureuser/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:151\ngithub.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).run\n\t/home/azureuser/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:203\ngithub.com/elastic/beats/v7/metricbeat/mb/module.(*Wrapper).Start.func1\n\t/home/azureuser/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:147\nruntime.goexit\n\t/home/azureuser/.gvm/versions/go1.15.12.linux.amd64/src/runtime/asm_amd64.s:1374\nfailed to set audit PID (current audit PID 0)\ngithub.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).initClient\n\t/home/azureuser/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:362\ngithub.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).receiveEvents\n\t/home/azureuser/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:386\ngithub.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).Run\n\t/home/azureuser/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:151\ngithub.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).run\n\t/home/azureuser/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:203\ngithub.com/elastic/beats/v7/metricbeat/mb/module.(*Wrapper).Start.func1\n\t/home/azureuser/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:147\nruntime.goexit\n\t/home/azureuser/.gvm/versions/go1.15.12.linux.amd64/src/runtime/asm_amd64.s:1374"}
```

cleaned up error:

```
failed to set audit PID (current audit PID 0): error receiving audit reply: no buffer space available
no buffer space available
error receiving audit reply
github.com/elastic/go-libaudit/v2.(*AuditClient).getReply
	/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:492
github.com/elastic/go-libaudit/v2.(*AuditClient).set
	/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:531
github.com/elastic/go-libaudit/v2.(*AuditClient).SetPID
	/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:323
github.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).initClient
	/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:356
github.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).receiveEvents
	/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:384
github.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).Run
	/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:151
github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).run
	/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:203
github.com/elastic/beats/v7/metricbeat/mb/module.(*Wrapper).Start.func1
	/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:147
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
failed to set audit PID (current audit PID 0)
github.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).initClient
	/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:360
github.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).receiveEvents
	/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:384
github.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).Run
	/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:151
github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).run
	/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:203
github.com/elastic/beats/v7/metricbeat/mb/module.(*Wrapper).Start.func1
	/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:147
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```

This error triggers closing of the netlink channel, which deadlocks the kernel when the closing routine first tries to set the Audit PID to zero.

This causes the Auditbeat process to block indefinitely:

(kernel stack)
```
[<0>] netlink_attachskb+0x1b9/0x1d0
[<0>] netlink_unicast+0xab/0x260
[<0>] audit_receive_msg+0x7e3/0xe60
[<0>] audit_receive+0x47/0xa0
[<0>] netlink_unicast+0x198/0x260
[<0>] netlink_sendmsg+0x2e2/0x3d0
[<0>] sock_sendmsg+0x3e/0x50
[<0>] SYSC_sendto+0x101/0x190
[<0>] SyS_sendto+0xe/0x10
[<0>] do_syscall_64+0x80/0x1e0
[<0>] entry_SYSCALL_64_after_hwframe+0x41/0xa6
[<0>] 0xffffffffffffffff
```

(usermode stack)
```
1 @ 0x55cfadf8f4e5 0x55cfadf8ee34 0x55cfadf8b6ce 0x55cfaf63abf7 0x55cfaf639c72 0x55cfaf63ca7e 0x55cfadf7ecee 0x55cfaf6395d9 0x55cfaf63956c 0x55cfaf6566bf 0x55cfaf626079 0x55cfaf62949b 0x55cfadf736e1
#	0x55cfadf8f4e4	syscall.Syscall6+0x4								/home/azureuser/.gvm/versions/go1.15.12.linux.amd64/src/syscall/asm_linux_amd64.s:41
#	0x55cfadf8ee33	syscall.sendto+0x93								/home/azureuser/.gvm/versions/go1.15.12.linux.amd64/src/syscall/zsyscall_linux_amd64.go:1595
#	0x55cfadf8b6cd	syscall.Sendto+0xad								/home/azureuser/.gvm/versions/go1.15.12.linux.amd64/src/syscall/syscall_unix.go:298
#	0x55cfaf63abf6	github.com/elastic/go-libaudit/v2.(*NetlinkClient).Send+0xd6			/home/azureuser/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/netlink.go:140
#	0x55cfaf639c71	github.com/elastic/go-libaudit/v2.(*AuditClient).set+0xd1			/home/azureuser/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:521
#	0x55cfaf63ca7d	github.com/elastic/go-libaudit/v2.(*AuditClient).Close.func1+0xdd		/home/azureuser/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:443
#	0x55cfadf7eced	sync.(*Once).doSlow+0xed							/home/azureuser/.gvm/versions/go1.15.12.linux.amd64/src/sync/once.go:66
#	0x55cfaf6395d8	sync.(*Once).Do+0x98								/home/azureuser/.gvm/versions/go1.15.12.linux.amd64/src/sync/once.go:57
#	0x55cfaf63956b	github.com/elastic/go-libaudit/v2.(*AuditClient).Close+0x2b			/home/azureuser/go/pkg/mod/github.com/elastic/go-libaudit/v2@v2.2.0/audit.go:436
#	0x55cfaf6566be	github.com/elastic/beats/v7/auditbeat/module/auditd.(*MetricSet).Run+0x5fe	/home/azureuser/go/src/github.com/elastic/beats/auditbeat/module/auditd/audit_linux.go:155
#	0x55cfaf626078	github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).run+0x6b8	/home/azureuser/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:203
#	0x55cfaf62949a	github.com/elastic/beats/v7/metricbeat/mb/module.(*Wrapper).Start.func1+0x25a	/home/azureuser/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:147
```

and any other process attempting to send a message to kauditd also blocks:

```
[ 1088.476058] INFO: task systemd:1 blocked for more than 120 seconds.
[ 1088.480734]       Not tainted 4.15.0-1113-azure #126~16.04.1-Ubuntu
[ 1088.485363] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1088.502837] systemd         D    0     1      0 0x00000000
[ 1088.502840] Call Trace:
[ 1088.502850]  __schedule+0x3d6/0x8b0
[ 1088.502855]  ? __wake_up_common_lock+0x8e/0xc0
[ 1088.502858]  schedule+0x36/0x80
[ 1088.502861]  schedule_preempt_disabled+0xe/0x10
[ 1088.502863]  __mutex_lock.isra.5+0x270/0x500
[ 1088.502867]  ? __kmalloc_node_track_caller+0x201/0x2c0
[ 1088.502869]  __mutex_lock_slowpath+0x13/0x20
[ 1088.502870]  ? __mutex_lock_slowpath+0x13/0x20
[ 1088.502872]  mutex_lock+0x2f/0x40
[ 1088.502875]  audit_receive+0x2a/0xa0
[ 1088.502878]  netlink_unicast+0x198/0x260
[ 1088.502880]  netlink_sendmsg+0x2e2/0x3d0
[ 1088.502885]  sock_sendmsg+0x3e/0x50
[ 1088.502886]  SYSC_sendto+0x101/0x190
[ 1088.502889]  ? handle_mm_fault+0xe7/0x220
[ 1088.502894]  ? __do_page_fault+0x2ae/0x4d0
[ 1088.502897]  SyS_sendto+0xe/0x10
[ 1088.502900]  do_syscall_64+0x80/0x1e0
[ 1088.502903]  entry_SYSCALL_64_after_hwframe+0x41/0xa6
[ 1088.502906] RIP: 0033:0x7f56ee6e2ab3
[ 1088.502907] RSP: 002b:00007ffd03bd8688 EFLAGS: 00000246 ORIG_RAX: 000000000000002c
[ 1088.502909] RAX: ffffffffffffffda RBX: 0000000000000080 RCX: 00007f56ee6e2ab3
[ 1088.502910] RDX: 0000000000000080 RSI: 00007ffd03bd86c0 RDI: 0000000000000028
[ 1088.502911] RBP: 0000000000000028 R08: 00007ffd03bd86a0 R09: 000000000000000c
[ 1088.502912] R10: 0000000000000000 R11: 0000000000000246 R12: 00007ffd03bd86c0
[ 1088.502913] R13: 00007ffd03bd86a0 R14: 000000000000046a R15: 000000000000006f
```

The only solution is to `kill -9` the auditbeat process.

For confirmed bugs, please report:
- Version: 7.x
- Operating System: Linux
- Discuss Forum URL: https://discuss.elastic.co/t/error-receiving-audit-reply-no-buffer-space-available/210382
- Steps to Reproduce: 

1. Disable all modules from Auditbeat except auditd, with default settings. Stop any auditd service.
2. Restart Auditbeat in a loop ([helper script (use root)](https://gist.github.com/adriansr/53b1452014ee4fd987f956a95820aa0a))
3. In a separate terminal, run as many instances as possible of the [netlink message flooder](https://gist.github.com/adriansr/16524e5b1242ce5cf59ca623a59a9ddb) as root. In my case it deadlocks quick with 8~12 instances.
4. Have a separate root terminal ready before the deadlock, to recover the system (killall -9 auditbeat).

### PR DESCRIPTION
**Pull request by adriansr**
## What does this PR do?

This fixes a deadlock when the netlink channel is congested (initialization fails with "no buffer space available" / errno=ENOBUFS).

Apart from preventing the deadlock by consuming events from the netlink channel during close, it adds code to handle the unlikely ENOBUFS during initialization, to prevent failure of the auditd module.

## Why is it important?

Prevents a deadlock that has been reported on large deployments where Auditbeat is restarted frequently and the hosts have a large amount of auditd events.

The deadlock is reported to happen around 3 times for ~5000 daily restarts.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

See #26031 

## Related issues

- Closes #26031

### CODE REVIEW

**Comment by adriansr** [comment]
A more correct fix is to refactor the auditd module or go-libaudit to consume audit messages before initialization and until the netlink connection is closed for good. But for a bugfix, I'd rather avoid a complex refactor.

I was a bit puzzled that errno=ENOBUFS is consistently received only by the SetPID operation. It seems that it can only be triggered from ACK responses and it can't happen until Auditbeat is configured as the Audit daemon.

File: auditbeat/module/auditd/audit_linux.go [hunk 1]
```diff
@@ -137,10 +137,32 @@ func newAuditClient(c *Config, log *logp.Logger) (*libaudit.AuditClient, error)
...
+func closeAuditClient(client *libaudit.AuditClient) error {
+	discard := func(bytes []byte) ([]syscall.NetlinkMessage, error) {
+		return nil, nil
+	}
+	// Drain the netlink channel in parallel to Close() to prevent a deadlock.
+	// This goroutine will terminate once receive from netlink errors (EBADF,
+	// EBADFD, or any other error). This happens because the fd is closed.
+	go func() {
+		for {
+			_, err := client.Netlink.Receive(true, discard)
```
Comment (andrewstucki) [inline auditbeat/module/auditd/audit_linux.go:149]: This is the only reader at this point, correct? Do we have to worry about any sort of data races in the case of a successfully started client that also has a read loop, or we don't care because we're shutting down anyway?

**Comment by wenlxie** [comment]
Another fix maybe simple that:
When there is a setPid error when do the init, then not did setPid() operation in client.close()?

File: auditbeat/module/auditd/audit_linux.go (hunk 1 above)
Comment (adriansr) [reply auditbeat/module/auditd/audit_linux.go:149]: There is the main reader from auditd that may be reading at the same time. In my tests, there's no issue of having both readers in parallel

**Comment by adriansr** [comment]
@wenlxie I've seen some cases where the SetPID succeeds but still the next SetPID in Close blocks. It's much less likely though.

**Review by andrewstucki — APPROVED** [review]

**Review by andrewkroh — APPROVED** [review]
