### PR TITLE
TCP layer drop connection state on gap

### LINKED ISSUE #342: beta4 crashing
We have upgraded from beta2 to beta4 and receiving this error now:

2015-10-29T23:03:18.249227+01:00 yesss-proda1-db01 /usr/bin/packetbeat[38501]: log.go:114: Stacktrace: 
/go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/elastic/libbeat/logp/log.go:114 (0x4c20b6)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x47d60e)
/usr/local/go/src/runtime/panic.go:423 (0x44d209)
/usr/local/go/src/runtime/panic.go:18 (0x44b749)
[/go/src/github.com/elastic/packetbeat/protos/pgsql/pgsql.go:279](https://github.com/elastic/packetbeat/blob/1.0.0-beta4/protos/pgsql/pgsql.go#L279) (0x510ff3)
[/go/src/github.com/elastic/packetbeat/protos/pgsql/pgsql.go:610](https://github.com/elastic/packetbeat/blob/1.0.0-beta4/protos/pgsql/pgsql.go#L610) (0x5134ce)
[/go/src/github.com/elastic/packetbeat/protos/pgsql/pgsql.go:707](https://github.com/elastic/packetbeat/blob/1.0.0-beta4/protos/pgsql/pgsql.go#L707) (0x513f4d)
/go/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:87 (0x51fa03)
/go/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:173 (0x520b3d)
/go/src/github.com/elastic/packetbeat/decoder/decoder.go:136 (0x6c5151)
/go/src/github.com/elastic/packetbeat/sniffer/sniffer.go:352 (0x532119)
/go/src/github.com/elastic/packetbeat/packetbeat.go:212 (0x422e0b)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x47f951)

we are using elasticsearch for output

If you need any more testing please let me know

### PR DESCRIPTION
**Pull request by urso**
Drop and reinitialize connection state on gap, so application layer parser
will be restarted (after detecting gap).

resolves #342

### CODE REVIEW

File: packetbeat/protos/tcp/tcp.go [hunk 1]
```diff
@@ -75,117 +75,136 @@ type TcpStream struct {
...
+		return TcpStream{conn: conn, dir: TcpDirectionReverse}, false
+	}
+
+	protocol := tcp.decideProtocol(&pkt.Tuple)
+	if protocol == protos.UnknownProtocol {
+		// don't follow
+		return TcpStream{}, false
+	}
+
+	timeout := time.Duration(0)
```
Comment (andrewkroh) [inline packetbeat/protos/tcp/tcp.go]: Out of curiosity, is this form preferred over  `var timeout time.Duration` for any technical reasons?

File: packetbeat/protos/tcp/tcp.go [hunk 2]
```diff
@@ -75,117 +75,136 @@ type TcpStream struct {
...
+	mod := tcp.protocols.GetTcp(protocol)
+	if mod != nil {
+		timeout = mod.ConnectionTimeout()
+	}
+
+	if isDebug {
+		debugf("Connection doesn't exist, creating new")
```
Comment (andrewkroh) [inline packetbeat/protos/tcp/tcp.go]: Consider adding the tcp tuple and ID to this message.

File: packetbeat/protos/tcp/tcp.go [hunk 3]
```diff
@@ -75,117 +75,136 @@ type TcpStream struct {
...
 				if drop {
 					if isDebug {
-						debugf("Dropping stream because of gap")
+						debugf("Dropping connection state because of gap")
 					}
-					tcp.streams.Delete(stream.tuple.Hashable())
+
+					// drop application layer connection state and
+					// update stream_id for app layer analysers using stream_id for lookups
+					conn.id = tcp.getId()
```
Comment (andrewkroh) [inline packetbeat/protos/tcp/tcp.go]: It looks like you simplified the book keeping a bit. :+1:   Are these two lines (or lack of) what was causing the issue we were seeing?

**Comment by andrewkroh** [comment]
LGTM

File: packetbeat/protos/tcp/tcp.go (hunk 3 above)
Comment (urso) [inline packetbeat/protos/tcp/tcp.go]: yes. when dropping we basically need to restart the Process function. Problem was, we reused the old state when pushing to upper layers, beside dropping it first. => parser errors, crashes, current packet data lost.

Instead of dropping and doing goto to beginning of function it's easier to just reset state ;)

File: packetbeat/protos/tcp/tcp.go (hunk 1 above)
Comment (urso) [inline packetbeat/protos/tcp/tcp.go]: ah, copy'n paste. I'd prefer the 'var timeout time.Duration'. but in this case no big difference
