### PR TITLE
[libbeat] Add Syslog parser and processor

### LINKED ISSUE #30139: Create Syslog Processor
## Overview

Syslog parsing in Beats is currently implemented as a dedicated input. It supports accepting data over UDP, TCP, and Unix sockets. Because it is implemented as an input, the parsing cannot be used by other inputs such as filestream, httpjson, or kafka.

The goal is to decouple the input from parsing by moving the parsing to a processor. This also provides the opportunity for to improve other areas of processing at the same time.

## Summary of Intended Changes

- Implement a parser for syslog
    - Strongly follow RFC 3164, allow for flexible timestamps. RFC 3146 is also rather vague in areas, and a best effort parser will be necessary for some elements (tag and content fields, for instance)
    - Strictly follow RFC 5424
    - Automatically detect format by default
    - Parsers will allow multiline to work with syslog
- Always retain event.original
- Populate ECS fields
- Deprecate syslog input

## Flexible Timestamp Parsing for RFC 3146

In addition to the RFC-defined timestamp format ("Mmm dd hh:mm:ss", e.g. Feb  5 17:32:18), the processor should also allow for parsing RFC 3339 timestamps. There tends to be low adherence to this part of the specfication due to lack of subsecond precision, year, and timezone. These deviations will be documented with examples.

## Other Notes

- Cisco does not follow RFCs. Cisco modules will use plain udp/tcp/tls inputs (without parser) and use grok or dissect to do best effort syslog header parser. Even if header parsing fails they should pick up parsing from the Cisco message ID (e.g. %SEC-6-IPACCESSLOGP)

## See Also

- https://datatracker.ietf.org/doc/html/rfc3164
- https://datatracker.ietf.org/doc/html/rfc5424

### PR DESCRIPTION
**Pull request by taylor-swanson**
## What does this PR do?

- Add Syslog parser
- Add Syslog processor
- Add unit tests and benchmarks
- Add processor documentation

## Why is it important?

This change allows us to detach syslog message parsing from a specific filebeat input. A new processor and parser have been added to libbeat, each providing the ability to parse RFC 3164 and RFC 5424-formatted syslog messages.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Run unit tests in these packages:
```
libbeat/processors/syslog
libbeat/reader/syslog
```
Benchmark tests are also available.

Example config for a filebeat processor:

```
filebeat.inputs:
- type: udp
  host: "localhost:9000"
  processors:
    - syslog:
        field: message
        format: auto
        timezone: Local
```

Example config for a filebeat parser:
```
filebeat.inputs:
- type: filestream
  paths:
    - /tmp/syslog.txt
  parsers:
    - syslog:
        format: auto
        timezone: Local
```

## Related issues

- Closes #30139

### CODE REVIEW

File: libbeat/reader/parser/parser.go [hunk 1]
```diff
@@ -157,6 +165,14 @@ func (c *Config) Create(in reader.Reader) Parser {
...
 			}
 			p = readjson.NewContainerParser(p, &config)
+		case "syslog":
+			config := syslog.DefaultConfig()
+			cfg := ns.Config()
+			err := cfg.Unpack(&config)
+			if err != nil {
+				return p
+			}
+			p = syslog.NewParser(p, &config)
```
Comment (andrewkroh) [inline libbeat/reader/parser/parser.go:175]: I think we need a test to verify parsers are working as expected.

Also I would like to see a test demonstrating one of the use cases which is syslog messages containing multiline data like stack traces. This would only be realistic for a use case where you had something like rsyslog de-muxing the incoming streams to separate files.

```
<165>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - - [beat-logstash-some-name-832-2015.11.28] IndexNotFoundException[no such index]
<165>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:566)
<165>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133)
<165>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:77)
<165>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:75)
```

File: libbeat/reader/parser/parser.go [hunk 2]
```diff
@@ -30,6 +30,7 @@ import (
 	"github.com/elastic/beats/v7/libbeat/reader/multiline"
 	"github.com/elastic/beats/v7/libbeat/reader/readfile"
 	"github.com/elastic/beats/v7/libbeat/reader/readjson"
+	"github.com/elastic/beats/v7/libbeat/reader/syslog"
 )
```
Comment (andrewkroh) [inline libbeat/reader/parser/parser.go:35]: There should be some documentation for `parsers` where we need to add `syslog`.

**Review by andrewkroh — COMMENTED** [review]
Leaving some high-level comments. I did not dive into any of the parser.

File: libbeat/reader/parser/parser.go (hunk 2 above)
Comment (taylor-swanson) [reply libbeat/reader/parser/parser.go:35]: Where is the documentation for parsers? None of the other parsers seem to have documentation, but I may have missed it. The only references I've seen are in the documentation for the filestream input. (https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#_parsers)

File: libbeat/processors/syslog/docs/syslog.asciidoc [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+      "exampleSDID@32473": {
+        "iut":         "3",
+        "eventSource": "Application",
+        "eventID":     "1011",
+      },
+      "examplePriority@32473": {
+        "class": "high",
+      },
+    }
+  },
```
[the remark this answers is not in the document]
Comment (taylor-swanson) [reply libbeat/processors/syslog/docs/syslog.asciidoc:88]: I missed the ECS mappings here, so I'll fix that up. I also agree in regards to the host and process mapping as well, especially since we already have dedicated syslog mappings for them.

File: libbeat/processors/syslog/syslog.go [hunk 4]
```diff
@@ -0,0 +1,178 @@
...
+	}, nil
+}
+
+// Run will process an event and will update the fields based on the parsed message, or an error if the
+// message could not be parsed. If an error occurs and the configuration is set to not ignore errors,
+// the 'error.message' field will be set with error that was encountered.
+func (p *processor) Run(event *beat.Event) (*beat.Event, error) {
+	if err := p.run(event); err != nil && !p.IgnoreFailure {
+		err = fmt.Errorf(procName+" failed to process field %q: %w", p.Field, err)
+		_, _ = event.PutValue("error.message", err.Error())
```
[the remark this answers is not in the document]
Comment (andrewkroh) [reply libbeat/processors/syslog/syslog.go:133]: This is where the failure semantics of Beats processors are broken IMO. The interface definition is weak so all of the processors do different things w.r.t. error handling, and we have this behavior where errors returned by processors **do not** stop the processing. It's too late (like by 3yrs) to change the behavior, but we will fix it for Agent v2.

The library implementation that does stop on error, but some refactoring happened and this code isn't used in the real pipeline.
https://github.com/elastic/beats/blob/a3fe79648592169bf81d482f5d3895a5045d140a/libbeat/processors/processor.go#L192-L195

This is the implementation that's actually used:
https://github.com/elastic/beats/blob/405c3428b9f5c135c78058aa2c183feb3200edd9/libbeat/publisher/processing/processors.go#L127-L135

If you were to use `syslog` within a `script` processor then the error would stop the pipeline and [automatically write](https://github.com/elastic/beats/blob/7930f9ed0f75696bfc8feff4400a896232184231/libbeat/processors/script/javascript/session.go#L243-L244) to `error.message` (or make `error.message` an array if it already existed).
https://github.com/elastic/beats/blob/a3fe79648592169bf81d482f5d3895a5045d140a/libbeat/processors/script/javascript/module/processor/chain.go#L190-L192

So what to do here? My advice is to append if it already exists just so that this processor is not responsible for overwriting errors. Ideally the caller would be responsible for handling the error and adding it to `error.message`, but that's not the case here.

File: libbeat/reader/parser/parser.go (hunk 2 above)
Comment (andrewkroh) [reply libbeat/reader/parser/parser.go:35]: Ok, that's all I found too. So let's update that list at the least.

File: libbeat/processors/syslog/docs/syslog.asciidoc (hunk 3 above)
[the remark this answers is not in the document]
Comment (andrewkroh) [reply libbeat/processors/syslog/docs/syslog.asciidoc:88]: Can you talk to the ECS team about adding these fields and whether they want a [PR or an RFC](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md#how-to-contribute).

File: libbeat/reader/parser/parser.go (hunk 2 above)
Comment (taylor-swanson) [reply libbeat/reader/parser/parser.go:35]: Can do, I'll also drop in a docs directory and have a file similar to the one for the processor. I'd imagine we'll eventually have a doc section for parsers, so that'll at least help the next person that comes along and works on that.

File: libbeat/processors/syslog/docs/syslog.asciidoc (hunk 3 above)
[the remark this answers is not in the document]
Comment (taylor-swanson) [reply libbeat/processors/syslog/docs/syslog.asciidoc:92]: PR for ECS changes: https://github.com/elastic/ecs/pull/1793

[the remark this answers is not in the document]
Comment (taylor-swanson) [reply libbeat/processors/syslog/docs/syslog.asciidoc:92]: Looking through the other log fields, it looks like we can also set `log.level`. Any objections to doing that?

File: libbeat/reader/parser/parser.go (hunk 1 above)
Comment (taylor-swanson) [reply libbeat/reader/parser/parser.go:175]: I added a couple of tests for parser, including a newline example. I'm not sure how we are going to combine messages like the ones you have listed above. I could be wrong, but the RFC doesn't assign provisions for combining messages like that. The only thing it may mention is that it's up to the relay or collector to handle this (rsyslog in this case?). I'm not too familiar with rsyslog's demuxing feature, so if you have any pointers on how that works, I'll see what I can do to support that.

It seems to me though that the multiline parser should handle the heavy lifting here, unless there's something specific in the syslog protocol that we can leverage.

File: libbeat/processors/syslog/docs/syslog.asciidoc (hunk 3 above)
[the remark this answers is not in the document]
Comment (andrewkroh) [reply libbeat/processors/syslog/docs/syslog.asciidoc:92]: So that would setting `log.level` based on the syslog severity values? Would it be to the severity names defined in RFC 3164? https://datatracker.ietf.org/doc/html/rfc3164#section-4.1.1

File: libbeat/reader/parser/parser.go (hunk 1 above)
Comment (andrewkroh) [reply libbeat/reader/parser/parser.go:175]: Yes, multiline should be able to do it. You would apply `syslog` first and then `multiline` would join the data contained in the `message` part. So the multiline pattern would be based on the syslog message data only and not the header.

My preamable about rsyslog was to highlight that this isn't a realistic use case if you were trying to apply a multiline parser to data coming from more than one network source.

File: libbeat/processors/syslog/syslog.go [hunk 5]
```diff
@@ -0,0 +1,207 @@
...
+	}
+
+	return event, nil
+}
+
+// run will parse the event and populate fields on the event.
+func (p *processor) run(event *beat.Event) error {
+	value, err := event.GetValue(p.Field)
+	if err != nil {
+		if err == common.ErrKeyNotFound {
```
Comment (andrewkroh) [inline libbeat/processors/syslog/syslog.go:152]: For future compatibility with wrapped errors: `errors.Is(err, common.ErrKeyNotFound)`

File: libbeat/reader/parser/parser_test.go [hunk 6]
```diff
@@ -242,13 +242,62 @@ func TestParsersConfigAndReading(t *testing.T) {
...
+<165>1 2003-08-24T05:14:20.000003-07:00 192.168.2.1 myproc 8710 - - This is some other debug message.
+<165>1 2003-08-24T05:14:30.000003-07:00 192.0.2.1 myproc 8710 - - [beat-logstash-some-name-832-2015.11.28] IndexNotFoundException[no such index]
+<165>1 2003-08-24T05:14:30.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:566)
+<165>1 2003-08-24T05:14:30.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133)
+<165>1 2003-08-24T05:14:30.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:77)
+<165>1 2003-08-24T05:14:30.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:75)
+`,
+			expectedMessages: []string{
```
Comment (andrewkroh) [inline libbeat/reader/parser/parser_test.go:286]: 👍

File: libbeat/reader/parser/parser.go (hunk 1 above)
Comment (taylor-swanson) [reply libbeat/reader/parser/parser.go:175]: I added a test for this scenario. That part worked fine (just had to remove a whitespace trim that I had when setting the message field), but one thing I noticed was that setting event.original is a bit weird. It'll only have the last message that was handled, not the whole set of original messages. That makes sense, though. Perhaps for parsers, it doesn't make sense to set event.original since we can't predict what happens before and after this parser runs.

Here's the event that's emitted from the example above for reference:

```json
{
    ...
    "event": {
        ...
        "original": "<165>1 2003-08-24T05:14:30.000003-07:00 192.0.2.1 myproc 8710 - -     at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:75)"
    },
    "message": "[beat-logstash-some-name-832-2015.11.28] IndexNotFoundException[no such index]\n    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:566)\n    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133)\n    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:77)\n    at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:75)"
}
```

File: libbeat/reader/syslog/message.go [hunk 7]
```diff
@@ -0,0 +1,220 @@
...
+		f.Put("log.syslog.version", m.version)
+	}
+	if len(m.structuredData) > 0 {
+		f.Put("log.syslog.structured_data", m.structuredData)
+	}
+
+	// Event fields.
+	f.Put("event.severity", m.severity)
+	if original != "" {
+		f.Put("event.original", original)
```
Comment (andrewkroh) [inline libbeat/reader/syslog/message.go:211]: If `event.original` already exists then it should probably leave it as is.

File: libbeat/reader/parser/parser.go (hunk 1 above)
Comment (andrewkroh) [reply libbeat/reader/parser/parser.go:175]: > Perhaps for parsers, it doesn't make sense to set event.original 

I agree. I think it would be hard to get this correct without specification of the expected behavior in the parser interface.

I think I would want event.original to be automatically set once on the way in to the parsers and then any processors that aggregate multiple events should append all `event.original` values into an array.

File: libbeat/reader/syslog/message.go (hunk 7 above)
Comment (andrewkroh) [reply libbeat/reader/syslog/message.go:211]: Maybe it shouldn't even be responsible for setting this. Users can do this on their own via copy or rename. This is how decode_cef expects it to be done. See the example at https://www.elastic.co/guide/en/beats/filebeat/8.1/processor-decode-cef.html#processor-decode-cef.

So an example of parsing a syslog message containing CEF data would be:


```
processors:
  - rename:
      fields:
        - {from: "message", to: "event.original"}
  - syslog:
      field: event.original
  - decode_cef:
      field: message
```

File: libbeat/processors/syslog/docs/syslog.asciidoc (hunk 3 above)
[the remark this answers is not in the document]
Comment (andrewkroh) [reply libbeat/processors/syslog/docs/syslog.asciidoc:92]: I think if we have it already in `log.syslog.severity.name` then I would let the user decide if they want that copied over or if they are going to be populating it with something parsed from the log message. They can use another processor to copy it.

File: libbeat/reader/syslog/message.go (hunk 7 above)
Comment (taylor-swanson) [reply libbeat/reader/syslog/message.go:211]: I agree. It's easy enough for a user to just copy the message field if they want, and gives them control over what `event.original` should represent.

**Review by andrewkroh — COMMENTED** [review]
LGTM. I recommend running golangci-lint before merging. 

It might be worthwhile to explain the behavior of dates without years in the docs. Sometimes people ingesting logs from the previous year are surprised when those logs appear to be in the future (e.g. logs from Dec 31 ingested on Jan 1 get the wrong year).

**Review by andrewkroh — APPROVED** [review]

**Review by cmacknz — APPROVED** [review]
Didn't do a thorough review but LGTM.

**Comment by taylor-swanson** [comment]
> LGTM. I recommend running golangci-lint before merging.
> 
> It might be worthwhile to explain the behavior of dates without years in the docs. Sometimes people ingesting logs from the previous year are surprised when those logs appear to be in the future (e.g. logs from Dec 31 ingested on Jan 1 get the wrong year).

What are your thoughts on something like this:

```go
func (m *message) setTimestampBSD(v string, ref time.Time) {
	if parsed, err := time.ParseInLocation(time.Stamp, v, ref.Location()); err == nil {
		year := ref.Year()
		if parsed.Month() == time.December && ref.Month() == time.January {
			year--
		}
		m.timestamp = parsed.AddDate(year, 0, 0)
	}
}
```
If the parsed month is December and the current month is now January, we decrement the year by 1. This gives a month on either side of the year boundary to make sure the year is correct. If we're outside of this window, all bets are off. Another benefit with this is the function now accepts a time.Time. We can write unit tests to explicitly test the year boundary and any other cases we can think of.

Either way, I'll document this situation and suggest that if logs are meant to be stored more long term and ingested at a later date, then it is critical that they switch to a timestamp that provides more information (ISO 8601/RFC 3339). Heck, the RFC even says this:

> It has been found that some network administrators like to archive their syslog messages over long periods of time. [...] Implementers may wish to utilize the ISO 8601 [7] date and time formats if they want to include more explicit date and time information.

**Comment by taylor-swanson** [comment]
> > What are your thoughts on something like this:
> 
> I would avoid the heuristic based solution (or at least make it optional behavior). There are a lot of edge cases. Logstash has some discussion on the topic in [logstash-plugins/logstash-filter-date#51 (comment)](https://github.com/logstash-plugins/logstash-filter-date/issues/51#issuecomment-167888907).

That's fair. In that case, I think this is something that should be handled in a separate issue. The current implementation behaves just like the existing input, so behavior hasn't changed.

Having configuration for this that could handle several different scenarios would provide the better options for customers. What I proposed would not help a customer ingest logs older than a year, for example. It was only meant to handle year boundaries, but even at that there are still edge cases.

**Review by andrewkroh — APPROVED** [review]
