### PR TITLE
Do not try to load ILM if check_exists if false

### LINKED ISSUE #26322: Beats require unnecessary privileges at startup on 7.13
Using version 7.13.1 Beats force to set ILM policies, even when configuration explicitly set them to don't set them.
 This may cause an error, if beats credentials are reduced to minimum, as in: https://www.elastic.co/guide/en/beats/filebeat/current/privileges-to-publish-events.html
 
- Version: 7.13.1 (it doesn't affect 7.10.2)
- Operating System: CentOs / Redhat
- Discuss Forum URL: https://discuss.elastic.co/t/heartbeat-ask-for-unnecessary-cluster-privileges-at-startup/275814
- Steps to Reproduce: 

1. create a user with this privileges, and use it in a metricbeat.yml configuration:
```
{
  "cluster": ["monitor" ,"cluster:admin/ingest/pipeline/get"],
  "indices": [
    {
      "names": [ "cloud-metrics*", "cloud-logs*", "metricbeat-*", "filebeat-*", "heartbeat-*" ],
      "privileges": ["create_doc"]
    }
  ],
  "metadata" : { 
    "version" : 1
  }
}
```

2. execute `metricbeat setup` with proper superuser credentials.
```
metricbeat setup -E setup.ilm.overwrite=true -E setup.template.enabled=true -E output.elasticsearch.username=elastic -E output.elasticsearch.password=***
```

3. configure metricbeat.yml with these settings:

```
setup.template.enabled: false
setup.ilm.check_exists: false
setup.ilm.overwrite: false
setup.ilm.enabled: true
 ```
 
4. start metricbeat and check for logs. It should appear something similar to:

```
{"log.level":"error","@timestamp":"2021-06-14T11:06:35.785+0200","log.logger":"index-management.ilm","log.origin":{"file.name":"ilm/std.go","file.line":166},"message":"ILM policy heartbeat creation failed: 403 Forbidden: {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"action [cluster:admin/ilm/put] is unauthorized for API key id [0e0c9nkBdKUEp4Eqeb4y] of user [apikeywriteruser], this action is granted by the cluster privileges [manage_ilm,manage,all]\"}],\"type\":\"security_exception\",\"reason\":\"action [cluster:admin/ilm/put] is unauthorized for API key id [0e0c9nkBdKUEp4Eqeb4y] of user [apikeywriteruser], this action is granted by the cluster privileges [manage_ilm,manage,all]\"},\"status\":403}","ecs.version":"1.6.0"}
```

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

Previously, if both `setup.ilm.check_exists` and `setup.ilm.overwrite` was disabled, Beats would still believe that the alias and/or the ILM policy has to be loaded.

This might be a breaking change, but from now on if `check_exists` is disabled, `overwrite` is ignored. But I think it is acceptable because people would only disable `check_exists` if the user connecting to ES does not have the required permissions. Thus, if the user does not have read permission for ILM components, it means that it does not have enough permission to load ILM components. Thus, trying to overwrite anything when `check_exists` is disabled makes no sense. If this is not good enough reasoning, the solution can be changed to still not load anything with the weird settings.

## Why is it important?

Without this change Beats will try to load ILM components if `check_exists` is set to false regardless of the `overwrite` settings.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

Closes #26322

### CODE REVIEW

File: libbeat/idxmgmt/ilm/std.go [hunk 1]
```diff
@@ -104,11 +104,16 @@ func (m *stdManager) CheckEnabled() (bool, error) {
 
 func (m *stdManager) EnsureAlias() error {
 	log := m.log
+	if !m.checkExists {
```
Comment (axw) [inline libbeat/idxmgmt/ilm/std.go:107]: Should this also check `!overwrite`? The docs say:

https://github.com/elastic/beats/blob/bbf7a581722ccf7247f07031be6aecb602e5f034/metricbeat/metricbeat.reference.yml#L2100-L2103

So I think it's fair to say that if both are false, then no ILM policy is created. Still weird config, but at least consistent with the docs.

I think the alternative is to tell users to set `setup.ilm.enabled:false`, and set `output.elasticsearch.index` to the write index.

**Comment by ruflin** [comment]
+1 on this change, I don't think the previous behaviour was expected. Lets make sure we properly document this change. I think we should even get this into 7.15 as a bugfix.

Do we need to update any docs? @axw Will this have any affect on apm?

**Comment by axw** [comment]
> Do we need to update any docs? @axw Will this have any affect on apm?

APM forces `check_exists: true`, so we should be fine.

File: libbeat/idxmgmt/ilm/std.go (hunk 1 above)
Comment (kvch) [reply libbeat/idxmgmt/ilm/std.go:107]: As agreed in https://github.com/elastic/beats/pull/27508#issuecomment-902511187 I will rather correct the behaviour of the options, not work around existing bad practice.

Comment (axw) [reply libbeat/idxmgmt/ilm/std.go:107]: It's fine by me either way, but for the record:

The config is nominally about ILM _setup_, but it's being overloaded to also configure the output index name. Seems to me this is the source of the problem. The user in https://github.com/elastic/beats/issues/26322 wants to be able to configure the output index to work with ILM without setting up ILM.

Any fix other than introducing new config is going to be less than ideal, so I guess this one is fine.

**Review by axw — APPROVED** [review]

File: libbeat/idxmgmt/ilm/std.go (hunk 1 above)
Comment (kvch) [reply libbeat/idxmgmt/ilm/std.go:107]: You are correct. I have responded to the original issue with your suggestions. However, I think my code still makes sense.
