### PR TITLE
libbeat/tests/compose: Fix conflict in container creation for integration tests

### LINKED ISSUE #36176: Build 807 for 7.17 with status FAILURE - MSSQL - Conflict. The container name "" is already in use by container ""
## :broken_heart: Tests Failed

> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[Pipeline View](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F7.17/detail/7.17/807//pipeline) [Test View](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F7.17/detail/7.17/807//tests) [Changes](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F7.17/detail/7.17/807//changes) [Artifacts](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F7.17/detail/7.17/807//artifacts) [preview](http://beats_null.docs-preview.app.elstc.co/diff)  [preview](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-07-30T03:03:26.514Z&rangeTo=2023-07-30T03:23:26.514Z&transactionName=BUILD+Beats%2Fbeats%2F7.17&transactionType=job&latencyAggregationType=avg&traceId=c593c6064cccbca5e6b461ff53489285&transactionId=1a2d2fcbc894a105)

<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Start Time: 2023-07-30T03:13:26.514+0000

* Duration: 61 min 53 sec

#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 2433  |
| Skipped      | 202 |
| Total        | 2636   |

</p>
</details>

  ### Test errors [](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F7.17/detail/7.17/807//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Extended / x-pack/metricbeat-cloud / TestFetch – github.com/elastic/beats/v7/x-pack/metricbeat/module/mssql/performance`

<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestFetch
2023-07-30T03:42:09.243Z	DEBUG	[docker]	docker/client.go:49	Docker client will negotiate the API version on the first request.
Found orphan containers (metricbeat_7_17_13_c3ff12206a-snapshot_ibmmq_1, metricbeat_7_17_13_c3ff12206a-snapshot_enterprise_search_1, metricbeat_7_17_13_c3ff12206a-snapshot_coredns_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1 ... 
Creating metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1 ... error

ERROR: for metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1  Cannot create container for service mssql: Conflict. The container name "/metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1" is already in use by container "512ad9e516c6c4e2960ecfc4cab825a2f9b70a77e762472c8b8ad0dcdc59ce6c". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for mssql  Cannot create container for service mssql: Conflict. The container name "/metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1" is already in use by container "512ad9e516c6c4e2960ecfc4cab825a2f9b70a77e762472c8b8ad0dcdc59ce6c". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project.
    performance_integration_test.go:28: failed to start service "mssql: exit status 1
Found orphan containers (metricbeat_7_17_13_c3ff12206a-snapshot_ibmmq_1, metricbeat_7_17_13_c3ff12206a-snapshot_enterprise_search_1, metricbeat_7_17_13_c3ff12206a-snapshot_coredns_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1 ... 
Creating metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1 ... error

ERROR: for metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1  Cannot create container for service mssql: Conflict. The container name "/metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1" is already in use by container "512ad9e516c6c4e2960ecfc4cab825a2f9b70a77e762472c8b8ad0dcdc59ce6c". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for mssql  Cannot create container for service mssql: Conflict. The container name "/metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1" is already in use by container "512ad9e516c6c4e2960ecfc4cab825a2f9b70a77e762472c8b8ad0dcdc59ce6c". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project.
    performance_integration_test.go:28: failed to start service "mssql: exit status 1
Found orphan containers (metricbeat_7_17_13_c3ff12206a-snapshot_ibmmq_1, metricbeat_7_17_13_c3ff12206a-snapshot_enterprise_search_1, metricbeat_7_17_13_c3ff12206a-snapshot_coredns_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1 ... 
Creating metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1 ... error

ERROR: for metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1  Cannot create container for service mssql: Conflict. The container name "/metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1" is already in use by container "512ad9e516c6c4e2960ecfc4cab825a2f9b70a77e762472c8b8ad0dcdc59ce6c". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for mssql  Cannot create container for service mssql: Conflict. The container name "/metricbeat_7_17_13_c3ff12206a-snapshot_mssql_1" is already in use by container "512ad9e516c6c4e2960ecfc4cab825a2f9b70a77e762472c8b8ad0dcdc59ce6c". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project.
    performance_integration_test.go:28: failed to start service "mssql: exit status 1
    modules.go:111: failed to create new MetricSet 1 error: could not create connection to db: error doing ping to db: Unable to open tcp connection with host "172.18.0.2:1433": dial tcp 172.18.0.2:1433: connect: connection refused
--- FAIL: TestFetch (25.76s)
 
 ```
</p></details>
</ul>
    
</p></details>

### Steps errors [](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F7.17/detail/7.17/807//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
##### `x-pack/metricbeat-cloud - mage build test`
<ul>
<li>Took 17 min 14 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/7.17/runs/807/steps/3020/log/?start=0">here</a></li>
<li>Description: <code>mage build test</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/7.17/runs/807/steps/3031/log/?start=0">here</a></li>
<li>Description: <code>Error "hudson.AbortException: script returned exit code 1"</code></l1>
</ul>
  
  </p>
  </details>

### PR DESCRIPTION
**Pull request by shmsr**
## Proposed commit message

Migrate from using [ContainerKill](https://pkg.go.dev/github.com/docker/docker@v24.0.5+incompatible/client#Client.ContainerKill) to [ContainerRemove](https://pkg.go.dev/github.com/docker/docker@v24.0.5+incompatible/client#Client.ContainerRemove) as the former terminates the container process but does not remove the container from the docker host but the latter does the removal as well i.e., removes the container and associated links and volumes. Without this change, sometimes the creating containers results in error because of the existence of containers (orphans) resulting in a conflict.

Reduce the code smells by addressing the issues reported by golangci-lint and also update outdated doc comments.

Please see the related issue to understand why the change is important. This change will also ensure effective usage of storage compared to before. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #36176
- Relates https://github.com/elastic/beats/issues/35738

### CODE REVIEW

File: libbeat/tests/compose/wrapper.go [hunk 1]
```diff
@@ -156,7 +159,7 @@ func (d *wrapperDriver) Close() error {
 }
 
 func (d *wrapperDriver) cmd(ctx context.Context, command string, arg ...string) *exec.Cmd {
-	var args []string
+	args := make([]string, 0, 4+len(d.Files)+len(arg)) // preallocate as much as possible
```
Comment (ishleenk17) [inline libbeat/tests/compose/wrapper.go:162]: How will this pre allocation help?

Comment (shmsr) [reply libbeat/tests/compose/wrapper.go:162]: Reason for this change:

- Pointed out by CI's golangci-lint (linter used: https://github.com/alexkohler/prealloc)
- Preallocation helps in lesser memory allocations. Check this out: https://github.com/alexkohler/prealloc#purpose (non prealloc vs prealloc version benchmarked).


Explaination:
```
args := make([]string, 0, 4+len(d.Files)+len(arg)) // preallocate as much as possible
args = append(args, "--no-ansi", "--project-name", d.Name) // 3 elements added
for _, f := range d.Files {                                                               // len(d.Files) elements added
	args = append(args, "--file", f)
}
args = append(args, command)                                                  // 1 element added
args = append(args, arg...)                                                          // len(arg) element added

// 3 + len(d.Files) + 1 + len(arg) = 4 + len(d.Files) + len(arg)
```

It is considered good practice to preallocate (by making the slice of the required capacity) in order to reduce memory allocation.

**Review by cmacknz — APPROVED** [review]

File: libbeat/tests/compose/compose.go [hunk 2]
```diff
@@ -102,8 +102,10 @@ func EnsureUp(t testing.TB, service string, options ...UpOption) HostInfo {
 			break
 		}
 		t.Log(err)
+
 		// Ignore errors here
-		compose.Kill(service)
+		_ = compose.Kill(service)
+		_ = compose.Remove(service, true)
```
[the remark this answers is not in the document]
Comment (shmsr) [reply libbeat/tests/compose/compose.go]: Yep, you are right. Thanks!
