### PR TITLE
Fix export dashboards

### LINKED ISSUE #29327: Failing test test_dev_tool_export_dashboard_by_id_from_space
This test fails since some change in the stack, it was found in automated PRs for snapshots used in testing, seen at least https://github.com/elastic/beats/pull/29275 (master) and https://github.com/elastic/beats/pull/29277 (8.0), it seems to work with older images.

The test is: [`libbeat/tests/system/test_dashboard.py::Test::test_dev_tool_export_dashboard_by_id_from_space`](https://github.com/elastic/beats/blob/16d587b7338b5d37bf5ad81cb58c2311d7996182/libbeat/tests/system/test_dashboard.py#L213)

We have to confirm if this is expected due to some breaking change in 8.0, or if this is an actual issue.

### PR DESCRIPTION
**Pull request by cmacknz**
## What does this PR do?

Cleans up the dashboard system tests by removing a broken test, and related tests that do not provide any valuable test coverage.

At some point in the past (during 8.0) the `test_dev_tool_export_dashboard_by_id_from_space` broke. The reason it broke is that we upload the same dashboards multiple times as part of the test, and there must have been a change in Kibana to ensure that all dashboards have unique `id` fields by generating a UUID on conflict. This made it so that we could not export the dashboard using the original ID anymore, breaking the test.

Previously the affected dashboard would always have root attributes like this:

```json
      "type": "dashboard",
      "id": "Metricbeat-system-overview",
      "namespaces": [
        "foo-bar"
      ],
```

At some point it changed so that uploading a dashboard with the same ID a second time in a different space would give you this instead:

```json
      "type": "dashboard",
      "id": "a094b66b-7cb0-4d7c-8a22-c414e510a343",
      "namespaces": [
        "foo-bar"
      ],
      "originId": "Metricbeat-system-overview",
```

When the ID is changed the response to the import API gives you the new ID back, but in these tests we the import is done by running a beat as a process and we don't have access to the import API response to save it for use during export. You also can't use the `originId` attribute in the spaces API from what I could tell.

Rather than write a bunch of code to work around this I just removed all the tests to do with Kibana spaces. The only change from the client side when interacting with a space is the addition of the `/s/<space-id>/` prefix to the path in the URL. I just updated a unit test to confirm we add this prefix when interacting with a space rather than re-testing all the API interactions a second time with a prefix added.

## Checklist

- [ x ] My code follows the style guidelines of this project
- [ x ] I have commented my code, particularly in hard-to-understand areas
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

## Related issues

- Closes #29327

### CODE REVIEW

File: libbeat/kibana/client_test.go [hunk 1]
```diff
@@ -32,55 +32,51 @@ import (
...
+		_, err := w.Write([]byte(`{"message": "Cannot export dashboard", "attributes":{"objects":[{"id":"test-*","type":"index-pattern","error":{"message":"action [indices:data/write/bulk[s]] is unauthorized for user [test]"}}]}}`))
+		assert.NoError(t, err)
 	}))
-	defer kibanaTs.Close()
+	defer kibanaTS.Close()
+
+	assertConnection(t, kibanaTS.URL, http.StatusUnauthorized)
+}
 
+func assertConnection(t *testing.T, URL string, expectedStatusCode int) {
```
Comment (belimawr) [inline libbeat/kibana/client_test.go:45]: Here you could add a call to [`t.Helper()`](https://pkg.go.dev/testing#T.Helper):
```suggestion
func assertConnection(t *testing.T, URL string, expectedStatusCode int) {
	t.Helper()
```

This helps with the error messages when the test fails.

**Review by belimawr — CHANGES_REQUESTED** [review]

File: libbeat/kibana/client_test.go (hunk 1 above)
Comment (cmacknz) [reply libbeat/kibana/client_test.go:45]: Done

**Review by rdner — APPROVED** [review]

**Review by kvch — APPROVED** [review]
