### PR TITLE
[Filebeat] Fix multiple modules in filebeat.yml

### LINKED ISSUE #29649: multiple `- module: name` configuration has different behaviour between `modules.d/module.yml` and `filebeat.yml`
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: v7.16.1, v7.16.2, master
- Operating System:  n/a
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-multiple-vpc-logs-from-different-s3-buckets-not-working/292711/10
- Steps to Reproduce: 
Define in `filebeat.yml` the following:
```
filebeat.modules:
  - module: aws
    cloudtrail:
      enabled: false
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    s3access:
      enabled: false
    elb:
      enabled: false
    vpcflow:
      enabled: true
      var.queue_url: "https://sqs.eu-central-1.amazonaws.com/account-id/queue-1"
  - module: aws
    cloudtrail:
      enabled: false
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    s3access:
      enabled: false
    elb:
      enabled: false
    vpcflow:
      enabled: true
      var.queue_url: "https://sqs.eu-central-1.amazonaws.com/account-id/queue-2"
```

run filebeat and observe how only one of the two modules/queues is actually loaded

configure the same multiple modules in `modules.d/aws.yml`:
```
  - module: aws
    cloudtrail:
      enabled: false
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    s3access:
      enabled: false
    elb:
      enabled: false
    vpcflow:
      enabled: true
      var.queue_url: "https://sqs.eu-central-1.amazonaws.com/account-id/queue-1"
  - module: aws
    cloudtrail:
      enabled: false
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    s3access:
      enabled: false
    elb:
      enabled: false
    vpcflow:
      enabled: true
      var.queue_url: "https://sqs.eu-central-1.amazonaws.com/account-id/queue-2"
```

run filebeat and observe how both the two modules/queues are loaded

it's not relevant for the test that the queues actually exist

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Fix the issue when defining multiple of the same module in filebeat.yml

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #29649

### CODE REVIEW

**Comment by kvch** [comment]
jenkins run tests

File: filebeat/fileset/factory.go [hunk 1]
```diff
@@ -179,8 +179,10 @@ func (p *inputsRunner) Start() {
 	}
 
 	// Loop through and add modules, only 1 normally
```
Comment (kvch) [inline filebeat/fileset/factory.go:181]: Do you mind updating this old comment? The "only 1 normally" is not true anymore.

File: filebeat/fileset/modules.go [hunk 2]
```diff
@@ -48,22 +48,22 @@ func newModuleRegistry(modulesPath string,
...
 		log:      logp.NewLogger(logName),
 	}
-
 	for _, mcfg := range moduleConfigs {
-		if mcfg.Enabled != nil && !(*mcfg.Enabled) {
+		if mcfg.Module == "" || (mcfg.Enabled != nil && !(*mcfg.Enabled)) {
 			continue
 		}
-
+		logp.Info("Enabled " + mcfg.Module)
```
Comment (kvch) [inline filebeat/fileset/modules.go:58]: The module registry has a logger, please use that instead of this global function call.

```suggestion
		reg.log.Info("Enabled " + mcfg.Module)
```

Comment (legoguy1000) [reply filebeat/fileset/modules.go:58]: This was left accidently as I was trying to follow the code logic.  I've removed it and updated the couple of other log lines to use the module registry logger.

**Comment by legoguy1000** [comment]
I would be curious if u have any thoughts on there is a better way of doing this.  Converting the registry from a Map to an Array of Maps seems a little jenky due to all the additional loops that I had to add everywhere else to accommodate them. During testing when it was still a map, I was adding numerical suffixes to the module names before adding to the map which then made them unique.  Any thoughts on something like that? it would remove the need for all the additional loops.

**Comment by kvch** [comment]
I am still thinking. Another issue I found is that pipelines get loaded as many times as the module is configured. It is either problematic because we are overloading Elasticsearch with unnecessary requests. Also, there are module that can affect the pipeline contents with configuration options, so it might be overwritten in a later pipeline loading. It is not yet clear to me what should be the resolution, but I will get back to you with ideas/resolution.

Otherwise, your PR is great! I just need a little time to think.

**Comment by legoguy1000** [comment]
> I am still thinking. Another issue I found is that pipelines get loaded as many times as the module is configured. It is either problematic because we are overloading Elasticsearch with unnecessary requests. Also, there are module that can affect the pipeline contents with configuration options, so it might be overwritten in a later pipeline loading. It is not yet clear to me what should be the resolution, but I will get back to you with ideas/resolution.
> 
> Otherwise, your PR is great! I just need a little time to think.

Should be easy to add a internal check to the `LoadPipelines` function to not try to load pipelines if a module ahs already been loaded.

File: filebeat/fileset/modules.go [hunk 3]
```diff
@@ -322,14 +322,17 @@ func appendWithoutDuplicates(moduleConfigs []*ModuleConfig, modules []string) ([
...
-		for name, fileset := range filesets {
-			fcfg, err := fileset.getInputConfig()
-			if err != nil {
-				return result, fmt.Errorf("error getting config for fileset %s/%s: %v",
-					module, name, err)
+	for _, modules := range reg.registry {
+		for module, filesets := range modules {
+			for name, fileset := range filesets {
+				fcfg, err := fileset.getInputConfig()
+				reg.log.Infof("%#v", fcfg)
```
Comment (kvch) [inline filebeat/fileset/modules.go:329]: Is this a leftover log message?

Comment (legoguy1000) [reply filebeat/fileset/modules.go:329]: Yes it is. I'll remove that and do another search to make sure I didn't leave any others.

**Comment by kvch** [comment]
> > I am still thinking. Another issue I found is that pipelines get loaded as many times as the module is configured. It is either problematic because we are overloading Elasticsearch with unnecessary requests. Also, there are module that can affect the pipeline contents with configuration options, so it might be overwritten in a later pipeline loading. It is not yet clear to me what should be the resolution, but I will get back to you with ideas/resolution.
> > Otherwise, your PR is great! I just need a little time to think.
> 
> Should be easy to add a internal check to the `LoadPipelines` function to not try to load pipelines if a module ahs already been loaded. Doesn't help the possible conflicts as u mentioned. However I would have to assume that issue would currently exist since you can have multiple of the same module set in the `modules.d/*.yml` files so there would already be a conflict/duplicate requests right??

Yes, the issue already exists in Beats. But I do not want to increase the scope of this PR. I will open an issue in beats to track the problem.

I was thinking about the registry and what I came up with is instead of having a list of maps, we can just create actual data type for modules just like for filesets.

```golang
type Registry struct {
    registry []Module
    log logp.Logger
}

type Module struct {
    filesets []Fileset
    config ModuleConfig
}
```

And `Fileset` does not need a pointer to `ModuleConfig`, keeping the name of the module is enough.

WDYT?

**Comment by legoguy1000** [comment]
@kvch That could probably work.  YOur thought for the Fileset struct would be something like below by replacing the `*ModuleConfig` with a string field with the module name?
```
type Fileset struct {
	name        string
	mname     string
	fcfg        *FilesetConfig
	modulePath  string
	manifest    *manifest
	vars        map[string]interface{}
	pipelineIDs []string
}
```

**Comment by kvch** [comment]
Issue: https://github.com/elastic/beats/issues/30165

**Comment by kvch** [comment]
> @kvch That could probably work. YOur thought for the Fileset struct would be something like below by replacing the `*ModuleConfig` with a string field with the module name?

 Exactly.

**Comment by legoguy1000** [comment]
Ok, I can try to make that update later today if I get a break.

**Comment by legoguy1000** [comment]
@kvch just pushed changes, locally seems to function properly

**Comment by kvch** [comment]
jenkins run tests

File: filebeat/fileset/modules.go [hunk 4]
```diff
@@ -440,10 +442,9 @@ func (reg *ModuleRegistry) ModuleAvailableFilesets(module string) ([]string, err
 
 // ModuleConfiguredFilesets return the list of configured filesets for the given module
 // it returns an empty list if the module doesn't exist
-func (reg *ModuleRegistry) ModuleConfiguredFilesets(module string) (list []string, err error) {
-	filesets, _ := reg.registry[module]
-	for name := range filesets {
-		list = append(list, name)
+func (reg *ModuleRegistry) ModuleConfiguredFilesets(module Module) (list []string, err error) {
```
Comment (kvch) [inline filebeat/fileset/modules.go:445]: Why are we returning an error param in this function? What can return an error? Am I missing something?

**Comment by kvch** [comment]
I like your changes, let's see what the CI thinks.

**Comment by kvch** [comment]
Please add a changelog entry, then this PR is ready to be merged.

File: filebeat/fileset/modules.go [hunk 5]
```diff
@@ -89,29 +93,28 @@ func newModuleRegistry(modulesPath string,
...
+			fileset, err := New(modulesPath, filesetName, mcfg.Module, fcfg)
 			if err != nil {
 				return nil, err
 			}
 			if err = fileset.Read(beatInfo); err != nil {
 				return nil, fmt.Errorf("error reading fileset %s/%s: %v", mcfg.Module, filesetName, err)
 			}
-			reg.registry[mcfg.Module][filesetName] = fileset
+			module.filesets = append(module.filesets, *fileset)
+			// registry[mcfg.Module][filesetName] = fileset
```
Comment (kvch) [inline filebeat/fileset/modules.go:104]:
```suggestion
```

File: CHANGELOG.next.asciidoc [hunk 6]
```diff
@@ -101,6 +101,13 @@ https://github.com/elastic/beats/compare/v7.0.0-alpha2...main[Check the HEAD dif
 
 - tcp/unix input: Stop accepting connections after socket is closed. {pull}29712[29712]
 - Fix using log_group_name_prefix in aws-cloudwatch input. {pull}29695[29695]
+- aws-s3: Stop trying to increase SQS message visibility after ReceiptHandleIsInvalid errors. {pull}29480[29480]
```
Comment (kvch) [inline CHANGELOG.next.asciidoc:104]: Could you please remove the extra changelog entries?

**Review by kvch — APPROVED** [review]

**Comment by kvch** [comment]
Once green, I will merge it. Thanks @legoguy1000

**Comment by kvch** [comment]
The failures are unrelated to your change. We updated the testing environment because we are releasing a new version. There might be a few hiccups here and there.

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
The test failures are unrelated. I will disable the Parser test for now in a follow up PR.

@legoguy1000 Thanks for your contribution!
