### PR TITLE
Join Docker log lines when they are split because of size

### LINKED ISSUE #6605: filebeats truncates log messages after 16k
```
# filebeat 6.2.2
filebeat.prospectors:
-
  paths: [ "/var/lib/docker/containers/*/*-json.log" ]
  harvester_buffer_size: 65536
  json.message_key: log
  json.keys_under_root: true
  json.add_error_key: true
  fields_under_root: true
  processors:
    - add_docker_metadata: ~

harvester_buffer_size: 65536

output.file:
  path: "/tmp/filebeat"
  filename: filebeat
```

- The docker container outputs a single line in valid json (about 18k)
- The value of the "log" message key is also a single line in valid json
- The message seems to be cut off at about 16k or a bit above (depends if you count the backslashes for escaping)
- A second message gets created with the remaining part of the message including full decoration (docker meta data, additional fields etc)
- Looks like filebeat splits the message into 2 separate ones
- harvester_buffer_size has no effect
- removing the json.* options has no effect

**How to reproduce:**

use my config, start a container and run the following:

```
#!/bin/bash
key="somerandomkey_"
value="somerandomvalue_"
echo -n '{'
for i in $(seq 420); do
  echo -n "\"${key}${i}\":\"${value}${i}\","
done
echo '"lastkey":"end"}'
```

This produces a valid json output. For me it cuts off at "somerand" and a new message continues with "omkey_396".

We also tried the following and it does not fix the issue: (as well as with and without the `harvester_buffer_size` option.)

```
filebeat.prospectors:
- type: docker
  containers.ids:
    - "*"
  processors:
    - add_docker_metadata: ~
```

@paltryeffort https://discuss.elastic.co/t/filebeat-splits-message-after-16k/123718/4

### PR DESCRIPTION
**Pull request by exekias**
Docker `json-file` driver splits lines longer than 16k bytes, this
change adapts the code to detect that situation and join them again to
output a single event.
    
This behavior is enabled by default, it can be disabled by using the new
`combine_partials` flag.
   
Fixes #6605

### CODE REVIEW

File: filebeat/harvester/reader/docker_json.go [hunk 1]
```diff
@@ -100,6 +100,21 @@ func (p *DockerJSON) Next() (Message, error) {
 
 		if strings.HasPrefix(string(message.Content), "{") {
 			message, err = parseDockerJSONLog(message, &dockerLine)
+			if err != nil {
+				return message, err
+			}
+			// Handle multiline messages, join lines that don't end with \n
+			for message.Content[len(message.Content)-1] != byte('\n') {
```
Comment (ruflin) [inline filebeat/harvester/reader/docker_json.go]: Should we enable this first through a config option and have it as default later on? This would allow us to start playing around with it.

@exekias I'm glad we have the docker prospector ;-)

Comment (exekias) [reply filebeat/harvester/reader/docker_json.go]: That's a great idea, I'll add it

File: filebeat/docs/inputs/input-docker.asciidoc [hunk 2]
```diff
@@ -49,6 +49,11 @@ is `/var/lib/docker/containers`.
 Reads from the specified streams only: `all`, `stdout` or `stderr`. The default
 is `all`.
 
+===== `containers.partial`
+
+Enable partial messages joining. Docker splits log lines larger than 16k bytes, enable this
+to join them while reading (default: false).
```
Comment (andrewkroh) [inline filebeat/docs/inputs/input-docker.asciidoc]: I think it would be useful to specify that it works by joining lines that don't end with \n.

**Comment by ruflin** [comment]
Code LGTM. For the config I was thinking to put it outside `container` and directly on the prospector level. Otherwise it gives the impression it's a container specific setting but I don't think it's really related to containers itself.

Naming wise I was thinking if we could find a name that is more directed into what it does instead of what problem it solves. So instead of `partial` more like `combine_partial_messages` which is too long but I hope describes what i mean. Any suggestions?

**Comment by exekias** [comment]
:+1: How about `combine_partials`? I'm not too worried as this will be a rather exotic flag (once we set it to true by default)

File: filebeat/docs/inputs/input-docker.asciidoc (hunk 2 above)
Comment (exekias) [reply filebeat/docs/inputs/input-docker.asciidoc]: uhm that's something specific to the `json-file` format, it's not the user who adds the `\n`. Do you think it's worth it? If yes, I would explain the whole story about how the format works

**Comment by ruflin** [comment]
👍 on combine_partials. I just realised the the docker input is still in experimental, so we could already turn it on by default and see what happens. Still good to have a config option so in case things go wrong, we can turn it off.

**Comment by exekias** [comment]
I've renamed the flag to `combine_partials`, set it to **true** by default and updated docs

**Comment by exekias** [comment]
done!

**Comment by bitsofinfo** [comment]
nice!

**Comment by SharpEdgeMarshall** [comment]
When should be available? version 6.4?

**Comment by exekias** [comment]
That's correct, it should be available by 6.4

**Comment by towolf** [comment]
@exekias This was _not_ released with 6.3.0 today right?

**Comment by bitsofinfo** [comment]
?! hope it was.... really need this

**Comment by bitsofinfo** [comment]
Whats the eta on 6.4?

**Comment by exekias** [comment]
I'm afraid this didn't make it to 6.3.0, it should be available with `6.4.0`. We can consider a backport to `6.3.1`if we consider this a bugfix, any opinion here @ruflin ?

**Comment by ruflin** [comment]
As Carlos mentioned we normally don't backport any features and I don't think we can qualify it as a bug. The biggest worry with backporting is that it could break something that works now which can always happen. I personally would prefer to not backport but make sure it is as stable as possible in 6.4.

**Comment by towolf** [comment]
So the cadence is roughly quarterly and we can expect 6.4 in 3 months or so?

**Comment by ruflin** [comment]
We don't give an estimates on the release dates ;-) If you want to test / use the feature we have some snapshots available: https://beats-package-snapshots.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by bitsofinfo** [comment]
so 3 more months?

**Comment by buddyledungarees** [comment]
Is it possible to use existing multiline match parameters to replicate this functionality?

```
multiline.pattern: '\n$'
multiline.negate: true
multiline.match: after
````

**Comment by wallies** [comment]
We are running a fork of this fix, but in the for loop, we are noticing that it doesnt catch EOF of files and will sometimes exit half way through processing a long line. This means that the currently-processed partial log line will not have been completely processed. *Later, when the next part of the now-half-processed log line arrives in the tailed log file, filebeat will fail to parse it.* . Specifically, the following check will fail:
```
if strings.HasPrefix(string(message.Content), "{") {
```

Below is the parse error we see
```
ERROR`	log/harvester.go:243	Read line error: parsing CRI timestamp: parsing time ",\\\"protocol\\\":\\\" as "2006-01-02T15:04:05Z07:00": cannot parse 
```

We have added a retry if io.EOF is reached for now, but im wondering whether the backoff code, that ive seen in other parts of the code, is getting into this bit of the code, or whether it should.

**Comment by exekias** [comment]
Hi @wallies, thank you for your feedback, and thank you for testing unreleased features! Could you please open a new issue for this one (or pull request :wink:)? happy to discuss it there and try to fix it for 6.4

**Comment by towolf** [comment]
@ruflin it's been 3 months now. Can't you just push this out?

**Comment by ruflin** [comment]
@towolf It will be released with the rest of the stack in 6.4 hopefully pretty soon.
